#include <stdio.h>
#include <unistd.h>
#include <sys/mman.h>

#include "HelloWorld.h"   // this header file was generated by javah


#define MAX_LEN 10000000 //10Mb
struct region {        /* Defines "structure" of shared memory */
    int len;
    char buf[MAX_LEN];
};
struct region *rptr;
int fd;




/* Now we can refer to mapped region using fields of rptr;
   for example, rptr->len */

JNIEXPORT void JNICALL Java_HelloWorld_displayMessage(JNIEnv *env, jobject obj)
{
  printf("Hello World!\n");
}



JNIEXPORT jobject JNICALL Java_HelloWorld_get(JNIEnv *env, jobject obj, jstring str)
{
  return strcat("Ojb_",str);
}

/*
 * Class:     HelloWorld
 * Method:    set
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)V */
JNIEXPORT void JNICALL Java_HelloWorld_set(JNIEnv *, jobject obj, jstring key, jobject value)
{

}


/*
 * Class:     HelloWorld
 * Method:    open
 * Signature: (Ljava/lang/String;)V*/
JNIEXPORT void JNICALL Java_HelloWorld_open(JNIEnv *env, jobject obj, jstring str)
{
	/* Create shared memory object and set its size */
	fd = shm_open(strcat("/",str), O_CREAT | O_RDWR, S_IRUSR | S_IWUSR);
	if (fd == -1)
		printf("fd == -1\n");


	if (ftruncate(fd, sizeof(struct region)) == -1)
		printf("ftruncate(fd, sizeof(struct region)) == -1\n");


	/* Map shared memory object */
	rptr = mmap(NULL, sizeof(struct region),
	       PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
	if (rptr == MAP_FAILED)
		printf("rptr == MAP_FAILED\n");

}


