/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloWorld */

#ifndef _Included_HelloWorld
#define _Included_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloWorld
 * Method:    displayMessage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HelloWorld_displayMessage
  (JNIEnv *, jobject);

/*
 * Class:     HelloWorld
 * Method:    set
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_HelloWorld_set
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     HelloWorld
 * Method:    get
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_HelloWorld_get
  (JNIEnv *, jobject, jstring);

/*
 * Class:     HelloWorld
 * Method:    open
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_HelloWorld_open
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
