/*
 * generated by Xtext
 */
package macroscipting.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MacroUiModule extends macroscipting.ui.AbstractMacroUiModule {
	public MacroUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
