package Events;

public enum FightEventType implements IEventType {

	ON_FIGHT_START,
	ON_FIGHT_END,
	ON_FIGHT_TURN_START,
	ON_FIGHT_TURN_END,
	ON_FIGHT_ROUND_START,
	ON_FIGHT_ROUND_END,
	ON_FIGHT_JOIN,
	ON_FIGHT_DIE,
	ON_FIGHT_DECONNECTED,
	ON_FIGHT_RECONNECTED,
	ON_FIGHT_QUIT,
	ON_FIGHT_SPELL_CAST, 
	ON_FIGHT_MOVE,
	
	;
	
}
