import java.awt.Insets;
import java.util.Stack;

public class cWm
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    String str1 = "mainContainer";
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localdRq1);
    localdRq1.setStyle("popup");
    localdRq1.setPrefSize(new Or(500, 0));
    localdRq1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(-2, -2));
    localcwP1.setAlign(ajb.dhZ);
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localaId1.setAlign(aFG.ech);
    localdRq1.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setExpandable(false);
    localdRq2.setPrefSize(new Or(0, 0));
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    aId localaId2 = aId.checkOut();
    localaId2.setHorizontal(false);
    localdRq2.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq2.bb(localdRq3);
    localdRq3.brn();
    aId localaId3 = aId.checkOut();
    localdRq3.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setExpandable(false);
    localczv1.setScaled(false);
    localczv1.setDisplaySize(new Or(54, 50));
    localdRq3.bb(localczv1);
    localczv1.brn();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa);
    localdpm1.setAlign(aFG.ech);
    localczv1.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv1.bb(localaAR);
    localaAR.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setName("graphicalDiagnostic");
    localNK1.setAttribute("texture");
    localNK1.setField("summaryIconURL");
    localaAR.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    localaAR.rV();
    localczv1.rV();
    cWk localcWk = new cWk();
    localcWk.aJ();
    localcWk.setElementMap(localcpa);
    localcWk.setStyle("white");
    localcWk.setMinWidth(350);
    localdRq3.bb(localcWk);
    localcWk.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("graphicalDiagnostic");
    localNK2.setAttribute("text");
    localNK2.setField("summaryDescription");
    localcWk.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localcWk.rV();
    localdRq3.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq2.bb(localdRq4);
    localdRq4.brn();
    czO localczO = new czO();
    localczO.aJ();
    localczO.setAdaptToContentSize(true);
    localdRq4.bb(localczO);
    localczO.brn();
    localczO.rV();
    biy localbiy1 = new biy();
    localbiy1.aJ();
    localbiy1.setElementMap(localcpa);
    String str2 = "%ok%";
    str2 = str2.replace("%ok%", cBQ.cxL().mL("ok"));
    localbiy1.setText(str2);
    csA localcsA = new csA();
    localcsA.hg("unloadDialog");
    localbiy1.setOnClick(localcsA);
    localdRq4.bb(localbiy1);
    localbiy1.brn();
    biy localbiy2 = localbiy1;
    Jg localJg1 = localbiy2.getAppearance();
    localJg1.setElementMap(localcpa);
    localbiy1.bb(localJg1);
    localJg1.brn();
    cuR localcuR = new cuR();
    localcuR.aJ();
    localcuR.setElementMap(localcpa);
    localcuR.setInsets(new Insets(0, 20, 0, 20));
    localJg1.bb(localcuR);
    localcuR.brn();
    localcuR.rV();
    localJg1.rV();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.dhZ);
    localbiy1.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    localbiy1.rV();
    dRq localdRq5 = dRq.checkOut();
    localdRq5.setElementMap(localcpa);
    localdRq4.bb(localdRq5);
    localdRq5.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setAlign(ajb.dia);
    localdRq5.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("popupInformation");
    String str3 = "%details%";
    str3 = str3.replace("%details%", cBQ.cxL().mL("details"));
    localcaF1.setText(str3);
    localdRq5.bb(localcaF1);
    localcaF1.brn();
    localcaF1.rV();
    br localbr1 = new br();
    localbr1.aJ();
    localbr1.setElementMap(localcpa);
    bvO localbvO = new bvO();
    localbvO.hg("wakfu.graphicalDiagnotics:toggleDetails(details)");
    localbr1.setOnSelectionChange(localbvO);
    localdRq5.bb(localbr1);
    localbr1.brn();
    br localbr2 = localbr1;
    Jg localJg2 = localbr2.getAppearance();
    localJg2.setElementMap(localcpa);
    localbr1.bb(localJg2);
    localJg2.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 5, 0, 0));
    localJg2.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg2.rV();
    localbr1.rV();
    localdRq5.rV();
    localdRq4.rV();
    localdRq2.rV();
    String str4 = "details";
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    if ((localcpa != null) && (str4 != null))
      localcpa.a(str4, localdRq6);
    localdRq6.setVisible(false);
    localdRq1.bb(localdRq6);
    localdRq6.brn();
    dRq localdRq7 = localdRq6;
    Jg localJg3 = localdRq7.getAppearance();
    localJg3.setElementMap(localcpa);
    localdRq6.bb(localJg3);
    localJg3.brn();
    localJg3.rV();
    aId localaId4 = aId.checkOut();
    localaId4.setHorizontal(false);
    localaId4.setAlign(aFG.ech);
    localdRq6.bb(localaId4);
    localaId4.brn();
    localaId4.rV();
    dRq localdRq8 = dRq.checkOut();
    localdRq8.setElementMap(localcpa);
    localdRq8.setExpandable(false);
    localdRq8.setStyle("lineSeparator");
    localdRq8.setPrefSize(new Or(0, 7));
    localdRq6.bb(localdRq8);
    localdRq8.brn();
    dRq localdRq9 = localdRq8;
    Jg localJg4 = localdRq9.getAppearance();
    localJg4.setElementMap(localcpa);
    localdRq8.bb(localJg4);
    localJg4.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(5, 0, 2, 0));
    localJg4.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg4.rV();
    localdRq8.rV();
    caF localcaF2 = new caF();
    localcaF2.aJ();
    localcaF2.setElementMap(localcpa);
    localcaF2.setExpandable(false);
    localcaF2.setStyle("whiteTitle");
    String str5 = "%details%";
    str5 = str5.replace("%details%", cBQ.cxL().mL("details"));
    localcaF2.setText(str5);
    localdRq6.bb(localcaF2);
    localcaF2.brn();
    localcaF2.rV();
    ccG localccG = new ccG();
    localccG.aJ();
    localccG.setElementMap(localcpa);
    localccG.setExpandable(false);
    localccG.setHorizontal(false);
    localccG.setCellSize(new Or(100.0F, 32));
    localccG.setAutoIdealSize(true);
    localccG.setIdealSizeMinColumns(1);
    localccG.setIdealSizeMaxColumns(1);
    localdRq6.bb(localccG);
    localccG.brn();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setName("graphicalDiagnostic");
    localNK3.setAttribute("content");
    localNK3.setField("testList");
    localccG.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    eR localeR = new eR();
    localeR.aJ();
    localeR.setElementMap(localcpa);
    localccG.bb(localeR);
    localeR.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localeR.bb(localanQ1);
    localanQ1.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localanQ1.bb(localanE);
    localanE.brn();
    localanE.rV();
    localanQ1.rV();
    dRq localdRq10 = dRq.checkOut();
    localdRq10.setElementMap(localcpa);
    localeR.bb(localdRq10);
    localdRq10.brn();
    aId localaId5 = aId.checkOut();
    localaId5.setHgap((short)5);
    localdRq10.bb(localaId5);
    localaId5.brn();
    localaId5.rV();
    czv localczv2 = new czv();
    localczv2.aJ();
    localczv2.setElementMap(localcpa);
    localczv2.setExpandable(false);
    localczv2.setScaled(false);
    localdRq10.bb(localczv2);
    localczv2.brn();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa);
    localdpm2.setAlign(aFG.eck);
    localczv2.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("style");
    localaaE1.setField("success");
    localczv2.bb(localaaE1);
    localaaE1.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localanQ2.setValue("smallValid");
    localanQ2.setElseValue("smallCancel");
    localaaE1.bb(localanQ2);
    localanQ2.brn();
    cOk localcOk = new cOk();
    localcOk.aJ();
    localcOk.setElementMap(localcpa);
    localanQ2.bb(localcOk);
    localcOk.brn();
    localcOk.rV();
    localanQ2.rV();
    localaaE1.rV();
    localczv2.rV();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setStyle("popupInformation");
    localdRq10.bb(localcaF3);
    localcaF3.brn();
    caF localcaF4 = localcaF3;
    Jg localJg5 = localcaF4.getAppearance();
    localJg5.setElementMap(localcpa);
    ((cwJ)localJg5).setAlign(aFG.ecj);
    localcaF3.bb(localJg5);
    localJg5.brn();
    localJg5.rV();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("text");
    localaaE2.setField("description");
    localcaF3.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    localcaF3.rV();
    localdRq10.rV();
    localeR.rV();
    localccG.rV();
    localdRq6.rV();
    localdRq1.rV();
    return localdRq1;
  }
}