import java.awt.Insets;
import java.util.Stack;

public class dox
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setAlign(ajb.dhR);
    localcwP1.setXOffset(5);
    localcwP1.setYOffset(0);
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(true);
    localdRq1.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    csA localcsA1 = new csA();
    localcsA1.hg("wakfu.petDialog:unloadTutorialDialog");
    localdRq2.setOnClick(localcsA1);
    localdRq2.setNonBlocking(false);
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("visible");
    localNK1.setName("tutorialMessageView");
    localdRq2.bb(localNK1);
    localNK1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localNK1.bb(localanQ1);
    localanQ1.brn();
    anE localanE1 = new anE();
    localanE1.aJ();
    localanE1.setElementMap(localcpa);
    localanQ1.bb(localanE1);
    localanE1.brn();
    localanE1.rV();
    localanQ1.rV();
    localNK1.rV();
    czO localczO1 = new czO();
    localczO1.aJ();
    localczO1.setAdaptToContentSize(true);
    localdRq2.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq3.setStyle("backgroundPopup");
    localdRq2.bb(localdRq3);
    localdRq3.brn();
    dRq localdRq4 = localdRq3;
    Jg localJg1 = localdRq4.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq3.bb(localJg1);
    localJg1.brn();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(10, 10, 15, 10));
    localJg1.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    localJg1.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setAttribute("visible");
    localNK2.setName("tutorialMessageView");
    localNK2.setField("style");
    localdRq3.bb(localNK2);
    localNK2.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localNK2.bb(localanQ2);
    localanQ2.brn();
    anE localanE2 = new anE();
    localanE2.aJ();
    localanE2.setElementMap(localcpa);
    localanQ2.bb(localanE2);
    localanE2.brn();
    localanE2.rV();
    localanQ2.rV();
    localNK2.rV();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setSize(new Or(-2, -2));
    localcwP2.setAlign(ajb.dhR);
    localcwP2.setXOffset(15);
    localdRq3.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setExpandable(false);
    localdRq3.bb(localczv1);
    localczv1.brn();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setAttribute("style");
    localNK3.setName("tutorialMessageView");
    localNK3.setField("style");
    localczv1.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    localczv1.rV();
    localdRq3.rV();
    dRq localdRq5 = dRq.checkOut();
    localdRq5.setElementMap(localcpa);
    localdRq2.bb(localdRq5);
    localdRq5.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setSize(new Or(100.0F, 100.0F));
    localdRq5.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    aId localaId2 = aId.checkOut();
    localaId2.setHorizontal(false);
    localdRq5.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    dAS localdAS = new dAS();
    localdAS.aJ();
    localdAS.setElementMap(localcpa);
    localdAS.setPrefSize(new Or(0, 35));
    localdAS.setExpandable(false);
    localdRq5.bb(localdAS);
    localdAS.brn();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa);
    localNK4.setAttribute("visible");
    localNK4.setName("tutorialMessageView");
    localNK4.setField("style");
    localdAS.bb(localNK4);
    localNK4.brn();
    anQ localanQ3 = new anQ();
    localanQ3.aJ();
    localanQ3.setElementMap(localcpa);
    localNK4.bb(localanQ3);
    localanQ3.brn();
    anE localanE3 = new anE();
    localanE3.aJ();
    localanE3.setElementMap(localcpa);
    localanQ3.bb(localanE3);
    localanE3.brn();
    localanE3.rV();
    localanQ3.rV();
    localNK4.rV();
    localdAS.rV();
    String str1 = "tutorialMessageContainer";
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localdRq6);
    localdRq6.setStyle("backgroundPopup");
    localdRq6.setPack(true);
    localdRq5.bb(localdRq6);
    localdRq6.brn();
    dRq localdRq7 = localdRq6;
    Jg localJg2 = localdRq7.getAppearance();
    localJg2.setElementMap(localcpa);
    localdRq6.bb(localJg2);
    localJg2.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(5, 0, 0, 0));
    localJg2.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(15, 15, 15, 15));
    localJg2.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    localJg2.rV();
    aId localaId3 = aId.checkOut();
    localaId3.setHorizontal(false);
    localaId3.setAlign(aFG.ech);
    localdRq6.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    czv localczv2 = new czv();
    localczv2.aJ();
    localczv2.setElementMap(localcpa);
    localczv2.setExpandable(false);
    localdRq6.bb(localczv2);
    localczv2.brn();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv2.bb(localaAR);
    localaAR.brn();
    NK localNK5 = NK.checkOut();
    localNK5.setElementMap(localcpa);
    localNK5.setAttribute("texture");
    localNK5.setName("tutorialMessageView");
    localNK5.setField("imageUrl");
    localaAR.bb(localNK5);
    localNK5.brn();
    localNK5.rV();
    localaAR.rV();
    localczv2.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setExpandable(false);
    localcWk1.setStyle("SmallBoldBordered12");
    localcWk1.setNonBlocking(true);
    localcWk1.setMinWidth(1);
    localcWk1.setMaxWidth(200);
    localdRq6.bb(localcWk1);
    localcWk1.brn();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa);
    localdpm1.setAlign(aFG.ecj);
    localcWk1.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    cWk localcWk2 = localcWk1;
    Jg localJg3 = localcWk2.getAppearance();
    localJg3.setElementMap(localcpa);
    ((cwJ)localJg3).setAlignment(aFG.ecj);
    localcWk1.bb(localJg3);
    localJg3.brn();
    cAf localcAf1 = cAf.checkOut();
    localcAf1.setElementMap(localcpa);
    localcAf1.setColor(new bNa(0.79F, 0.98F, 0.35F, 1.0F));
    localJg3.bb(localcAf1);
    localcAf1.brn();
    localcAf1.rV();
    localJg3.rV();
    NK localNK6 = NK.checkOut();
    localNK6.setElementMap(localcpa);
    localNK6.setAttribute("text");
    localNK6.setName("tutorialMessageView");
    localNK6.setField("title");
    localcWk1.bb(localNK6);
    localNK6.brn();
    localNK6.rV();
    localcWk1.rV();
    cWk localcWk3 = new cWk();
    localcWk3.aJ();
    localcWk3.setElementMap(localcpa);
    localcWk3.setStyle("SmallBoldBordered");
    localcWk3.setExpandable(false);
    localcWk3.setNonBlocking(true);
    localcWk3.setMinWidth(1);
    localcWk3.setMaxWidth(200);
    localdRq6.bb(localcWk3);
    localcWk3.brn();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa);
    localdpm2.setAlign(aFG.ecj);
    localcWk3.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    cWk localcWk4 = localcWk3;
    Jg localJg4 = localcWk4.getAppearance();
    localJg4.setElementMap(localcpa);
    ((cwJ)localJg4).setAlignment(aFG.ecj);
    localcWk3.bb(localJg4);
    localJg4.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 10, 0, 0));
    localJg4.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    cAf localcAf2 = cAf.checkOut();
    localcAf2.setElementMap(localcpa);
    localcAf2.setColor(new bNa(1.0F, 1.0F, 1.0F, 1.0F));
    localJg4.bb(localcAf2);
    localcAf2.brn();
    localcAf2.rV();
    localJg4.rV();
    NK localNK7 = NK.checkOut();
    localNK7.setElementMap(localcpa);
    localNK7.setAttribute("text");
    localNK7.setName("tutorialMessageView");
    localNK7.setField("description");
    localcWk3.bb(localNK7);
    localNK7.brn();
    localNK7.rV();
    localcWk3.rV();
    localdRq6.rV();
    localdRq5.rV();
    String str2 = "particleContainer";
    dRq localdRq8 = dRq.checkOut();
    localdRq8.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localdRq8);
    localdRq8.setNonBlocking(true);
    localdRq2.bb(localdRq8);
    localdRq8.brn();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setAlign(ajb.dhZ);
    localcwP4.setSize(new Or(95.0F, 95.0F));
    localdRq8.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    localdRq8.rV();
    localdRq2.rV();
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa);
    csA localcsA2 = new csA();
    localcsA2.hg("wakfu.petDialog:validOrSetNextMessage");
    localdRq9.setOnClick(localcsA2);
    localdRq9.setNonBlocking(false);
    localdRq9.setExpandable(false);
    localdRq1.bb(localdRq9);
    localdRq9.brn();
    dpm localdpm3 = new dpm();
    localdpm3.aJ();
    localdpm3.setElementMap(localcpa);
    localdpm3.setAlign(aFG.ech);
    localdRq9.bb(localdpm3);
    localdpm3.brn();
    localdpm3.rV();
    NK localNK8 = NK.checkOut();
    localNK8.setElementMap(localcpa);
    localNK8.setName("petBubbleMessage");
    localNK8.setAttribute("visible");
    localdRq9.bb(localNK8);
    localNK8.brn();
    anQ localanQ4 = new anQ();
    localanQ4.aJ();
    localanQ4.setElementMap(localcpa);
    localNK8.bb(localanQ4);
    localanQ4.brn();
    anE localanE4 = new anE();
    localanE4.aJ();
    localanE4.setElementMap(localcpa);
    localanQ4.bb(localanE4);
    localanE4.brn();
    localanE4.rV();
    localanQ4.rV();
    localNK8.rV();
    czO localczO2 = new czO();
    localczO2.aJ();
    localczO2.setAdaptToContentSize(true);
    localdRq9.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    dRq localdRq10 = dRq.checkOut();
    localdRq10.setElementMap(localcpa);
    localdRq10.setStyle("petBubble");
    localdRq10.setExpandable(false);
    localdRq9.bb(localdRq10);
    localdRq10.brn();
    cwP localcwP5 = new cwP();
    localcwP5.aJ();
    localcwP5.setElementMap(localcpa);
    localcwP5.setAlign(ajb.dhT);
    localdRq10.bb(localcwP5);
    localcwP5.brn();
    localcwP5.rV();
    dRq localdRq11 = localdRq10;
    Jg localJg5 = localdRq11.getAppearance();
    localJg5.setElementMap(localcpa);
    localdRq10.bb(localJg5);
    localJg5.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(23, 0, 20, 0));
    localJg5.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg5.rV();
    String str3 = "text";
    cWk localcWk5 = new cWk();
    localcWk5.aJ();
    localcWk5.setElementMap(localcpa);
    if ((localcpa != null) && (str3 != null))
      localcpa.a(str3, localcWk5);
    localcWk5.setMinWidth(10);
    localcWk5.setMaxWidth(250);
    localcWk5.setStyle("DefaultBold14");
    localdRq10.bb(localcWk5);
    localcWk5.brn();
    NK localNK9 = NK.checkOut();
    localNK9.setElementMap(localcpa);
    localNK9.setName("petBubbleMessage");
    localNK9.setAttribute("text");
    localcWk5.bb(localNK9);
    localNK9.brn();
    localNK9.rV();
    localcWk5.rV();
    localdRq10.rV();
    czv localczv3 = new czv();
    localczv3.aJ();
    localczv3.setElementMap(localcpa);
    localczv3.setStyle("petBubble");
    localczv3.setExpandable(false);
    localdRq9.bb(localczv3);
    localczv3.brn();
    cwP localcwP6 = new cwP();
    localcwP6.aJ();
    localcwP6.setElementMap(localcpa);
    localcwP6.setAlign(ajb.dhR);
    localcwP6.setSize(new Or(-2, -2));
    localcwP6.setXOffset(20);
    localczv3.bb(localcwP6);
    localcwP6.brn();
    localcwP6.rV();
    localczv3.rV();
    localdRq9.rV();
    localdRq1.rV();
    return localdRq1;
  }
}