import java.awt.Insets;
import java.util.Stack;

public class djd
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    bpn localbpn = new bpn();
    localbpn.aJ();
    localbpn.setElementMap(localcpa);
    localbpn.brn();
    czO localczO = new czO();
    localczO.aJ();
    localczO.setAdaptToContentSize(true);
    localbpn.bb(localczO);
    localczO.brn();
    localczO.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localbpn.bb(localdRq1);
    localdRq1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    localdRq1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setStyle("windowNew");
    localbpn.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(10, 5, 12, 5));
    localJg1.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    localJg1.rV();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localdRq2.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localaId1.setAlign(aFG.ech);
    localdRq2.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dqa localdqa1 = new dqa();
    localdqa1.aJ();
    localdqa1.setElementMap(localcpa);
    localdqa1.setExpandable(false);
    localdRq2.bb(localdqa1);
    localdqa1.brn();
    dqa localdqa2 = localdqa1;
    Jg localJg2 = localdqa2.getAppearance();
    localJg2.setElementMap(localcpa);
    localdqa1.bb(localJg2);
    localJg2.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 10, 0, 10));
    localJg2.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg2.rV();
    localdqa1.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq2.bb(localdRq4);
    localdRq4.brn();
    dRq localdRq5 = localdRq4;
    Jg localJg3 = localdRq5.getAppearance();
    localJg3.setElementMap(localcpa);
    localdRq4.bb(localJg3);
    localJg3.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 12, 0, 12));
    localJg3.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg3.rV();
    String str1 = "windowContentContainer";
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localdRq6);
    localdRq4.bb(localdRq6);
    localdRq6.brn();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa);
    localdpm1.setAlign(aFG.ech);
    localdRq6.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    aId localaId2 = aId.checkOut();
    localaId2.setHorizontal(false);
    localaId2.setVgap((short)3);
    localdRq6.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localdRq7.setExpandable(false);
    localdRq6.bb(localdRq7);
    localdRq7.brn();
    dRq localdRq8 = localdRq7;
    Jg localJg4 = localdRq8.getAppearance();
    localJg4.setElementMap(localcpa);
    localdRq7.bb(localJg4);
    localJg4.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 0, 0, 9));
    localJg4.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg4.rV();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa);
    localdpm2.setAlign(aFG.ecl);
    localdRq7.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    String str2 = "hour";
    bvx localbvx1 = new bvx();
    localbvx1.aJ();
    localbvx1.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localbvx1);
    localbvx1.setPrefSize(new Or(35, 0));
    localbvx1.setValue(12);
    localbvx1.setMinBound(0);
    localbvx1.setMaxBound(23);
    localbvx1.setExpandable(false);
    localbvx1.setDisplayFormat("%02d");
    localdRq7.bb(localbvx1);
    localbvx1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("value");
    localNK1.setName("calendar.editable");
    localNK1.setField("hour");
    localbvx1.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    localbvx1.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setText("H");
    localcaF1.setStyle("bold");
    localcaF1.setExpandable(false);
    localdRq7.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg5 = localcaF2.getAppearance();
    localJg5.setElementMap(localcpa);
    localcaF1.bb(localJg5);
    localJg5.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(0, 2, 0, 2));
    localJg5.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg5.rV();
    localcaF1.rV();
    String str3 = "minutes";
    bvx localbvx2 = new bvx();
    localbvx2.aJ();
    localbvx2.setElementMap(localcpa);
    if ((localcpa != null) && (str3 != null))
      localcpa.a(str3, localbvx2);
    localbvx2.setPrefSize(new Or(35, 0));
    localbvx2.setValue(0);
    localbvx2.setMinBound(0);
    localbvx2.setMaxBound(59);
    localbvx2.setExpandable(false);
    localbvx2.setDisplayFormat("%02d");
    localdRq7.bb(localbvx2);
    localbvx2.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setAttribute("value");
    localNK2.setName("calendar.editable");
    localNK2.setField("minute");
    localbvx2.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localbvx2.rV();
    localdRq7.rV();
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa);
    localdRq9.setExpandable(false);
    localdRq6.bb(localdRq9);
    localdRq9.brn();
    dpm localdpm3 = new dpm();
    localdpm3.aJ();
    localdpm3.setElementMap(localcpa);
    localdpm3.setAlign(aFG.ecl);
    localdRq9.bb(localdpm3);
    localdpm3.brn();
    localdpm3.rV();
    ddG localddG1 = new ddG();
    localddG1.aJ();
    localddG1.setElementMap(localcpa);
    localddG1.setExpandable(false);
    localddG1.setPrefSize(new Or(100, 15));
    dTZ localdTZ1 = new dTZ();
    localdTZ1.hg("wakfu.eventsCalendar:changeEditableCurrentMonth");
    localddG1.setOnListSelectionChange(localdTZ1);
    localdRq9.bb(localddG1);
    localddG1.brn();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setAttribute("content");
    localNK3.setName("calendar.editable");
    localNK3.setField("monthesList");
    localddG1.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa);
    localNK4.setAttribute("selectedValue");
    localNK4.setName("calendar.editable");
    localNK4.setField("selectedMonth");
    localddG1.bb(localNK4);
    localNK4.brn();
    localNK4.rV();
    axU localaxU1 = new axU();
    localaxU1.aJ();
    localaxU1.setElementMap(localcpa);
    localddG1.bb(localaxU1);
    localaxU1.brn();
    eR localeR1 = new eR();
    localeR1.aJ();
    localeR1.setElementMap(localcpa);
    localaxU1.bb(localeR1);
    localeR1.brn();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setNonBlocking(true);
    localeR1.bb(localcaF3);
    localcaF3.brn();
    dpm localdpm4 = new dpm();
    localdpm4.aJ();
    localdpm4.setElementMap(localcpa);
    localdpm4.setAlign(aFG.eck);
    localcaF3.bb(localdpm4);
    localdpm4.brn();
    localdpm4.rV();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("text");
    localaaE1.setField("description");
    localcaF3.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    localcaF3.rV();
    localeR1.rV();
    localaxU1.rV();
    ccG localccG1 = new ccG();
    localccG1.aJ();
    localccG1.setElementMap(localcpa);
    localccG1.setHorizontal(false);
    localccG1.setCellSize(new Or(100.0F, 16));
    localddG1.bb(localccG1);
    localccG1.brn();
    eR localeR2 = new eR();
    localeR2.aJ();
    localeR2.setElementMap(localcpa);
    localccG1.bb(localeR2);
    localeR2.brn();
    caF localcaF4 = new caF();
    localcaF4.aJ();
    localcaF4.setElementMap(localcpa);
    localcaF4.setNonBlocking(true);
    localeR2.bb(localcaF4);
    localcaF4.brn();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("text");
    localaaE2.setField("description");
    localcaF4.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    caF localcaF5 = localcaF4;
    Jg localJg6 = localcaF5.getAppearance();
    localJg6.setElementMap(localcpa);
    localcaF4.bb(localJg6);
    localJg6.brn();
    bmv localbmv5 = bmv.checkOut();
    localbmv5.setElementMap(localcpa);
    localbmv5.setInsets(new Insets(0, 10, 0, 0));
    localJg6.bb(localbmv5);
    localbmv5.brn();
    localbmv5.rV();
    localJg6.rV();
    localcaF4.rV();
    localeR2.rV();
    localccG1.rV();
    localddG1.rV();
    ddG localddG2 = new ddG();
    localddG2.aJ();
    localddG2.setElementMap(localcpa);
    localddG2.setExpandable(false);
    localddG2.setPrefSize(new Or(50, 15));
    dTZ localdTZ2 = new dTZ();
    localdTZ2.hg("wakfu.eventsCalendar:changeEditableCurrentYear");
    localddG2.setOnListSelectionChange(localdTZ2);
    localdRq9.bb(localddG2);
    localddG2.brn();
    NK localNK5 = NK.checkOut();
    localNK5.setElementMap(localcpa);
    localNK5.setAttribute("content");
    localNK5.setName("calendar.editable");
    localNK5.setField("yearsList");
    localddG2.bb(localNK5);
    localNK5.brn();
    localNK5.rV();
    NK localNK6 = NK.checkOut();
    localNK6.setElementMap(localcpa);
    localNK6.setAttribute("selectedValue");
    localNK6.setName("calendar.editable");
    localNK6.setField("selectedYear");
    localddG2.bb(localNK6);
    localNK6.brn();
    localNK6.rV();
    axU localaxU2 = new axU();
    localaxU2.aJ();
    localaxU2.setElementMap(localcpa);
    localddG2.bb(localaxU2);
    localaxU2.brn();
    eR localeR3 = new eR();
    localeR3.aJ();
    localeR3.setElementMap(localcpa);
    localaxU2.bb(localeR3);
    localeR3.brn();
    caF localcaF6 = new caF();
    localcaF6.aJ();
    localcaF6.setElementMap(localcpa);
    localcaF6.setNonBlocking(true);
    localeR3.bb(localcaF6);
    localcaF6.brn();
    dpm localdpm5 = new dpm();
    localdpm5.aJ();
    localdpm5.setElementMap(localcpa);
    localdpm5.setAlign(aFG.eck);
    localcaF6.bb(localdpm5);
    localdpm5.brn();
    localdpm5.rV();
    aaE localaaE3 = new aaE();
    localaaE3.aJ();
    localaaE3.setElementMap(localcpa);
    localaaE3.setAttribute("text");
    localcaF6.bb(localaaE3);
    localaaE3.brn();
    localaaE3.rV();
    localcaF6.rV();
    localeR3.rV();
    localaxU2.rV();
    ccG localccG2 = new ccG();
    localccG2.aJ();
    localccG2.setElementMap(localcpa);
    localccG2.setHorizontal(false);
    localccG2.setCellSize(new Or(100.0F, 16));
    localddG2.bb(localccG2);
    localccG2.brn();
    eR localeR4 = new eR();
    localeR4.aJ();
    localeR4.setElementMap(localcpa);
    localccG2.bb(localeR4);
    localeR4.brn();
    caF localcaF7 = new caF();
    localcaF7.aJ();
    localcaF7.setElementMap(localcpa);
    localcaF7.setNonBlocking(true);
    localeR4.bb(localcaF7);
    localcaF7.brn();
    aaE localaaE4 = new aaE();
    localaaE4.aJ();
    localaaE4.setElementMap(localcpa);
    localaaE4.setAttribute("text");
    localcaF7.bb(localaaE4);
    localaaE4.brn();
    localaaE4.rV();
    caF localcaF8 = localcaF7;
    Jg localJg7 = localcaF8.getAppearance();
    localJg7.setElementMap(localcpa);
    localcaF7.bb(localJg7);
    localJg7.brn();
    bmv localbmv6 = bmv.checkOut();
    localbmv6.setElementMap(localcpa);
    localbmv6.setInsets(new Insets(0, 10, 0, 0));
    localJg7.bb(localbmv6);
    localbmv6.brn();
    localbmv6.rV();
    localJg7.rV();
    localcaF7.rV();
    localeR4.rV();
    localccG2.rV();
    localddG2.rV();
    localdRq9.rV();
    String str4 = "calendar";
    bWa localbWa = new bWa();
    localbWa.aJ();
    localbWa.setElementMap(localcpa);
    if ((localcpa != null) && (str4 != null))
      localcpa.a(str4, localbWa);
    localbWa.setStyle("small");
    localbWa.setExpandable(false);
    localbWa.setCellSize(new Or(22, 22));
    localdRq6.bb(localbWa);
    localbWa.brn();
    NK localNK7 = NK.checkOut();
    localNK7.setElementMap(localcpa);
    localNK7.setAttribute("calendar");
    localNK7.setName("calendar.editable");
    localNK7.setField("calendar");
    localbWa.bb(localNK7);
    localNK7.brn();
    localNK7.rV();
    dpm localdpm6 = new dpm();
    localdpm6.aJ();
    localdpm6.setElementMap(localcpa);
    localdpm6.setAlign(aFG.eck);
    localbWa.bb(localdpm6);
    localdpm6.brn();
    localdpm6.rV();
    eR localeR5 = new eR();
    localeR5.aJ();
    localeR5.setElementMap(localcpa);
    localbWa.bb(localeR5);
    localeR5.brn();
    biy localbiy1 = new biy();
    localbiy1.aJ();
    localbiy1.setElementMap(localcpa);
    localbiy1.setStyle("flat");
    localeR5.bb(localbiy1);
    localbiy1.brn();
    aId localaId3 = aId.checkOut();
    localaId3.setAlign(aFG.ecj);
    localbiy1.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    localbiy1.rV();
    localeR5.rV();
    localbWa.rV();
    biy localbiy2 = new biy();
    localbiy2.aJ();
    localbiy2.setElementMap(localcpa);
    localbiy2.setClickSoundId(600002);
    localbiy2.setStyle("flat");
    String str5 = "%ok%";
    str5 = str5.replace("%ok%", cBQ.cxL().mL("ok"));
    localbiy2.setText(str5);
    localbiy2.setExpandable(false);
    csA localcsA = new csA();
    localcsA.hg("wakfu.eventsCalendar:selectDate(calendar,hour,minutes)");
    localbiy2.setOnClick(localcsA);
    localdRq6.bb(localbiy2);
    localbiy2.brn();
    biy localbiy3 = localbiy2;
    Jg localJg8 = localbiy3.getAppearance();
    localJg8.setElementMap(localcpa);
    localbiy2.bb(localJg8);
    localJg8.brn();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(3, 10, 3, 10));
    localJg8.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    localJg8.rV();
    dpm localdpm7 = new dpm();
    localdpm7.aJ();
    localdpm7.setElementMap(localcpa);
    localdpm7.setAlign(aFG.eck);
    localbiy2.bb(localdpm7);
    localdpm7.brn();
    localdpm7.rV();
    localbiy2.rV();
    localdRq6.rV();
    localdRq4.rV();
    localdRq2.rV();
    a(localbpn);
    b(localbpn);
    d(localbpn);
    localbpn.rV();
    return localbpn;
  }

  public bdj a(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq = dRq.checkOut();
    localdRq.setElementMap(localcpa);
    parambdj.bb(localdRq);
    localdRq.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(100.0F, 100.0F));
    localdRq.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localdRq.rV();
    return localdRq;
  }

  public bdj b(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    biy localbiy = new biy();
    localbiy.aJ();
    localbiy.setElementMap(localcpa);
    localbiy.setStyle("close");
    localbiy.setExpandable(false);
    csA localcsA = new csA();
    localcsA.hg("wakfu.eventsCalendar:closeCalendar");
    localbiy.setOnClick(localcsA);
    parambdj.bb(localbiy);
    localbiy.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(-2, -2));
    localcwP.setAlign(ajb.dhV);
    localcwP.setXOffset(-18);
    localcwP.setYOffset(-12);
    localbiy.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localbiy.rV();
    return localbiy;
  }

  public bdj d(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(-2, -2));
    localcwP.setAlign(ajb.dhZ);
    localcwP.setInitValue(true);
    parambdj.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    return localcwP;
  }
}