import java.awt.Insets;
import java.util.Stack;

public class ctu
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    String str1 = "container1";
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localdRq1);
    localdRq1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setAlign(ajb.dhZ);
    localcwP1.setYOffset(200);
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    czO localczO1 = new czO();
    localczO1.aJ();
    localczO1.setAdaptToContentSize(true);
    localdRq1.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    String str2 = "container2";
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localdRq2);
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localdRq2.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    czO localczO2 = new czO();
    localczO2.aJ();
    localczO2.setAdaptToContentSize(true);
    localdRq2.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    String str3 = "animatedElementLeft";
    auC localauC1 = new auC();
    localauC1.aJ();
    localauC1.setElementMap(localcpa);
    if ((localcpa != null) && (str3 != null))
      localcpa.a(str3, localauC1);
    localauC1.setNonBlocking(true);
    localauC1.setExpandable(false);
    localauC1.setPrefSize(new Or(220, 84));
    localauC1.setOffsetX(238.0F);
    localauC1.setOffsetY(-13.0F);
    localdRq2.bb(localauC1);
    localauC1.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setAlign(ajb.dhY);
    localcwP3.setSize(new Or(-2, 100.0F));
    localauC1.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    localauC1.rV();
    String str4 = "animatedElementRight";
    auC localauC2 = new auC();
    localauC2.aJ();
    localauC2.setElementMap(localcpa);
    if ((localcpa != null) && (str4 != null))
      localcpa.a(str4, localauC2);
    localauC2.setNonBlocking(true);
    localauC2.setExpandable(false);
    localauC2.setPrefSize(new Or(220, 84));
    localauC2.setOffsetX(-238.0F);
    localauC2.setOffsetY(-13.0F);
    localdRq2.bb(localauC2);
    localauC2.brn();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setAlign(ajb.dia);
    localcwP4.setSize(new Or(-2, -2));
    localauC2.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    localauC2.rV();
    localdRq2.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq1.bb(localdRq3);
    localdRq3.brn();
    dRq localdRq4 = localdRq3;
    Jg localJg1 = localdRq4.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq3.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 165, 5, 165));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    cwP localcwP5 = new cwP();
    localcwP5.aJ();
    localcwP5.setElementMap(localcpa);
    localcwP5.setSize(new Or(100.0F, -2));
    localdRq3.bb(localcwP5);
    localcwP5.brn();
    localcwP5.rV();
    String str5 = "image1";
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    if ((localcpa != null) && (str5 != null))
      localcpa.a(str5, localczv1);
    localczv1.setStyle("ZoneNameLeft");
    localczv1.setExpandable(false);
    localczv1.setNonBlocking(true);
    localdRq3.bb(localczv1);
    localczv1.brn();
    localczv1.rV();
    String str6 = "image2";
    czv localczv2 = new czv();
    localczv2.aJ();
    localczv2.setElementMap(localcpa);
    if ((localcpa != null) && (str6 != null))
      localcpa.a(str6, localczv2);
    localczv2.setStyle("ZoneNameCenter");
    localczv2.setNonBlocking(true);
    localczv2.setKeepAspectRatio(false);
    localczv2.setScaled(true);
    localczv2.setExpandable(true);
    localdRq3.bb(localczv2);
    localczv2.brn();
    localczv2.rV();
    String str7 = "image3";
    czv localczv3 = new czv();
    localczv3.aJ();
    localczv3.setElementMap(localcpa);
    if ((localcpa != null) && (str7 != null))
      localcpa.a(str7, localczv3);
    localczv3.setStyle("ZoneNameRight");
    localczv3.setNonBlocking(true);
    localczv3.setExpandable(false);
    localdRq3.bb(localczv3);
    localczv3.brn();
    localczv3.rV();
    localdRq3.rV();
    String str8 = "text";
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    if ((localcpa != null) && (str8 != null))
      localcpa.a(str8, localcWk1);
    localcWk1.setStyle("bigBordered");
    localcWk1.setMaxWidth(700);
    localcWk1.setNonBlocking(true);
    localdRq1.bb(localcWk1);
    localcWk1.brn();
    cwP localcwP6 = new cwP();
    localcwP6.aJ();
    localcwP6.setElementMap(localcpa);
    localcwP6.setSize(new Or(100.0F, 100.0F));
    localcWk1.bb(localcwP6);
    localcwP6.brn();
    localcwP6.rV();
    cWk localcWk2 = localcWk1;
    Jg localJg2 = localcWk2.getAppearance();
    localJg2.setElementMap(localcpa);
    ((cwJ)localJg2).setAlign(aFG.ecn);
    localcWk1.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 250, 5, 250));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    localcWk1.rV();
    localdRq1.rV();
    return localdRq1;
  }
}