import java.awt.Insets;
import java.util.Stack;

public class ND
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    String str1 = "confirmPurchaseWindow";
    bpn localbpn = new bpn();
    localbpn.aJ();
    localbpn.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localbpn);
    localbpn.setPack(true);
    localbpn.brn();
    czO localczO = new czO();
    localczO.aJ();
    localczO.setAdaptToContentSize(true);
    localbpn.bb(localczO);
    localczO.brn();
    localczO.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localbpn.bb(localdRq1);
    localdRq1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    localdRq1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setStyle("windowNew");
    localbpn.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(10, 5, 12, 5));
    localJg1.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    localJg1.rV();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localdRq2.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localaId1.setAlign(aFG.ech);
    localdRq2.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dqa localdqa1 = new dqa();
    localdqa1.aJ();
    localdqa1.setElementMap(localcpa);
    localdqa1.setExpandable(false);
    localdRq2.bb(localdqa1);
    localdqa1.brn();
    dqa localdqa2 = localdqa1;
    Jg localJg2 = localdqa2.getAppearance();
    localJg2.setElementMap(localcpa);
    localdqa1.bb(localJg2);
    localJg2.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 10, 0, 10));
    localJg2.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg2.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setStyle("titleBar");
    localdqa1.bb(localdRq4);
    localdRq4.brn();
    dRq localdRq5 = localdRq4;
    Jg localJg3 = localdRq5.getAppearance();
    localJg3.setElementMap(localcpa);
    localdRq4.bb(localJg3);
    localJg3.brn();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(2, 20, 3, 20));
    localJg3.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    localJg3.rV();
    aId localaId2 = aId.checkOut();
    localaId2.setHorizontal(false);
    localdRq4.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq6.setExpandable(false);
    localdRq4.bb(localdRq6);
    localdRq6.brn();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa);
    localdpm1.setAlign(aFG.eck);
    localdRq6.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("StyledBold16White");
    localcWk1.setNonBlocking(true);
    String str2 = "%protector.kamas.transfer%";
    str2 = str2.replace("%protector.kamas.transfer%", cBQ.cxL().mL("protector.kamas.transfer"));
    localcWk1.setText(str2);
    localdRq6.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg4 = localcWk2.getAppearance();
    localJg4.setElementMap(localcpa);
    ((cwJ)localJg4).setAlign(aFG.eck);
    localcWk1.bb(localJg4);
    localJg4.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 0, 0, 0));
    localJg4.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg4.rV();
    localcWk1.rV();
    localdRq6.rV();
    localdRq4.rV();
    localdqa1.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localdRq2.bb(localdRq7);
    localdRq7.brn();
    dRq localdRq8 = localdRq7;
    Jg localJg5 = localdRq8.getAppearance();
    localJg5.setElementMap(localcpa);
    localdRq7.bb(localJg5);
    localJg5.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 12, 0, 12));
    localJg5.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg5.rV();
    String str3 = "windowContentContainer";
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa);
    if ((localcpa != null) && (str3 != null))
      localcpa.a(str3, localdRq9);
    localdRq7.bb(localdRq9);
    localdRq9.brn();
    aId localaId3 = aId.checkOut();
    localaId3.setHorizontal(true);
    localdRq9.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    dRq localdRq10 = dRq.checkOut();
    localdRq10.setElementMap(localcpa);
    localdRq9.bb(localdRq10);
    localdRq10.brn();
    aId localaId4 = aId.checkOut();
    localaId4.setHorizontal(true);
    localdRq10.bb(localaId4);
    localaId4.brn();
    localaId4.rV();
    dRq localdRq11 = dRq.checkOut();
    localdRq11.setElementMap(localcpa);
    localdRq11.setStyle("flat");
    localdRq11.setPrefSize(new Or(0, 35));
    localdRq10.bb(localdRq11);
    localdRq11.brn();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa);
    localdpm2.setAlign(aFG.eck);
    localdRq11.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    aId localaId5 = aId.checkOut();
    localaId5.setHorizontal(false);
    localdRq11.bb(localaId5);
    localaId5.brn();
    localaId5.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    String str4 = "%protector.kamasToTransfer%";
    str4 = str4.replace("%protector.kamasToTransfer%", cBQ.cxL().mL("protector.kamasToTransfer"));
    localcaF1.setText(str4);
    localcaF1.setStyle("bold");
    localdRq11.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg6 = localcaF2.getAppearance();
    localJg6.setElementMap(localcpa);
    ((cwJ)localJg6).setAlign(aFG.eck);
    localcaF1.bb(localJg6);
    localJg6.brn();
    localJg6.rV();
    localcaF1.rV();
    dRq localdRq12 = dRq.checkOut();
    localdRq12.setElementMap(localcpa);
    localdRq12.setStyle("ShortcutRowBackgroundFull");
    localdRq12.setPrefSize(new Or(150, 0));
    localdRq11.bb(localdRq12);
    localdRq12.brn();
    dRq localdRq13 = localdRq12;
    Jg localJg7 = localdRq13.getAppearance();
    localJg7.setElementMap(localcpa);
    localdRq12.bb(localJg7);
    localJg7.brn();
    cuR localcuR3 = new cuR();
    localcuR3.aJ();
    localcuR3.setElementMap(localcpa);
    localcuR3.setInsets(new Insets(2, 5, 2, 5));
    localJg7.bb(localcuR3);
    localcuR3.brn();
    localcuR3.rV();
    localJg7.rV();
    String str5 = "amountTextEditor";
    aTp localaTp1 = new aTp();
    localaTp1.aJ();
    localaTp1.setElementMap(localcpa);
    if ((localcpa != null) && (str5 != null))
      localcpa.a(str5, localaTp1);
    localaTp1.setStyle("dark");
    localaTp1.setText("0");
    localaTp1.setRestrict("[0-9]+");
    localaTp1.setFocused(true);
    localaTp1.setSelectOnFocus(true);
    dbp localdbp = new dbp();
    localdbp.hg("wakfu.protectorManagement:validateBudgetTransfer(confirmButton)");
    localaTp1.setOnKeyType(localdbp);
    localdRq12.bb(localaTp1);
    localaTp1.brn();
    aTp localaTp2 = localaTp1;
    Jg localJg8 = localaTp2.getAppearance();
    localJg8.setElementMap(localcpa);
    ((cwJ)localJg8).setAlign(aFG.ecl);
    localaTp1.bb(localJg8);
    localJg8.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(0, 0, 0, 0));
    localJg8.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg8.rV();
    localaTp1.rV();
    localdRq12.rV();
    localdRq11.rV();
    dRq localdRq14 = dRq.checkOut();
    localdRq14.setElementMap(localcpa);
    localdRq14.setStyle("flat");
    localdRq14.setPrefSize(new Or(0, 35));
    localdRq10.bb(localdRq14);
    localdRq14.brn();
    dpm localdpm3 = new dpm();
    localdpm3.aJ();
    localdpm3.setElementMap(localcpa);
    localdpm3.setAlign(aFG.eck);
    localdRq14.bb(localdpm3);
    localdpm3.brn();
    localdpm3.rV();
    aId localaId6 = aId.checkOut();
    localaId6.setHorizontal(false);
    localdRq14.bb(localaId6);
    localaId6.brn();
    localaId6.rV();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    String str6 = "%protector.funds%";
    str6 = str6.replace("%protector.funds%", cBQ.cxL().mL("protector.funds"));
    localcaF3.setText(str6);
    localcaF3.setStyle("bold");
    localdRq14.bb(localcaF3);
    localcaF3.brn();
    caF localcaF4 = localcaF3;
    Jg localJg9 = localcaF4.getAppearance();
    localJg9.setElementMap(localcpa);
    ((cwJ)localJg9).setAlign(aFG.eck);
    localcaF3.bb(localJg9);
    localJg9.brn();
    localJg9.rV();
    localcaF3.rV();
    dRq localdRq15 = dRq.checkOut();
    localdRq15.setElementMap(localcpa);
    localdRq15.setStyle("ShortcutRowBackgroundFull");
    localdRq15.setPrefSize(new Or(100, 0));
    localdRq14.bb(localdRq15);
    localdRq15.brn();
    dRq localdRq16 = localdRq15;
    Jg localJg10 = localdRq16.getAppearance();
    localJg10.setElementMap(localcpa);
    localdRq15.bb(localJg10);
    localJg10.brn();
    cuR localcuR4 = new cuR();
    localcuR4.aJ();
    localcuR4.setElementMap(localcpa);
    localcuR4.setInsets(new Insets(2, 5, 2, 5));
    localJg10.bb(localcuR4);
    localcuR4.brn();
    localcuR4.rV();
    localJg10.rV();
    caF localcaF5 = new caF();
    localcaF5.aJ();
    localcaF5.setElementMap(localcpa);
    localcaF5.setStyle("bold");
    localdRq15.bb(localcaF5);
    localcaF5.brn();
    caF localcaF6 = localcaF5;
    Jg localJg11 = localcaF6.getAppearance();
    localJg11.setElementMap(localcpa);
    ((cwJ)localJg11).setAlign(aFG.ecl);
    localcaF5.bb(localJg11);
    localJg11.brn();
    bmv localbmv5 = bmv.checkOut();
    localbmv5.setElementMap(localcpa);
    localbmv5.setInsets(new Insets(0, 0, 0, 3));
    localJg11.bb(localbmv5);
    localbmv5.brn();
    localbmv5.rV();
    localJg11.rV();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setName("protector");
    localNK1.setAttribute("text");
    localNK1.setField("walletHandler/totalAmount");
    localcaF5.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    localcaF5.rV();
    localdRq15.rV();
    localdRq14.rV();
    String str7 = "territoryCombo";
    ddG localddG = new ddG();
    localddG.aJ();
    localddG.setElementMap(localcpa);
    if ((localcpa != null) && (str7 != null))
      localcpa.a(str7, localddG);
    localddG.setExpandable(false);
    localddG.setPrefSize(new Or(250, 0));
    localdRq10.bb(localddG);
    localddG.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setAttribute("content");
    localNK2.setName("nation");
    localNK2.setField("protectorList");
    localddG.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    axU localaxU = new axU();
    localaxU.aJ();
    localaxU.setElementMap(localcpa);
    localddG.bb(localaxU);
    localaxU.brn();
    eR localeR1 = new eR();
    localeR1.aJ();
    localeR1.setElementMap(localcpa);
    localaxU.bb(localeR1);
    localeR1.brn();
    dRq localdRq17 = dRq.checkOut();
    localdRq17.setElementMap(localcpa);
    localeR1.bb(localdRq17);
    localdRq17.brn();
    aId localaId7 = aId.checkOut();
    localaId7.setHorizontal(false);
    localdRq17.bb(localaId7);
    localaId7.brn();
    localaId7.rV();
    caF localcaF7 = new caF();
    localcaF7.aJ();
    localcaF7.setElementMap(localcpa);
    localcaF7.setNonBlocking(true);
    localcaF7.setStyle("bold");
    localdRq17.bb(localcaF7);
    localcaF7.brn();
    dpm localdpm4 = new dpm();
    localdpm4.aJ();
    localdpm4.setElementMap(localcpa);
    localdpm4.setAlign(aFG.eck);
    localcaF7.bb(localdpm4);
    localdpm4.brn();
    localdpm4.rV();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("text");
    localaaE1.setField("territoryName");
    localcaF7.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    localcaF7.rV();
    caF localcaF8 = new caF();
    localcaF8.aJ();
    localcaF8.setElementMap(localcpa);
    localcaF8.setNonBlocking(true);
    localcaF8.setStyle("bold");
    localdRq17.bb(localcaF8);
    localcaF8.brn();
    dpm localdpm5 = new dpm();
    localdpm5.aJ();
    localdpm5.setElementMap(localcpa);
    localdpm5.setAlign(aFG.eck);
    localcaF8.bb(localdpm5);
    localdpm5.brn();
    localdpm5.rV();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("text");
    localaaE2.setField("cash");
    localcaF8.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    localcaF8.rV();
    localdRq17.rV();
    localeR1.rV();
    localaxU.rV();
    ccG localccG = new ccG();
    localccG.aJ();
    localccG.setElementMap(localcpa);
    localccG.setHorizontal(false);
    localccG.setCellSize(new Or(100.0F, 30));
    localddG.bb(localccG);
    localccG.brn();
    eR localeR2 = new eR();
    localeR2.aJ();
    localeR2.setElementMap(localcpa);
    localccG.bb(localeR2);
    localeR2.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localeR2.bb(localanQ);
    localanQ.brn();
    dlQ localdlQ = new dlQ();
    localdlQ.aJ();
    localdlQ.setElementMap(localcpa);
    localdlQ.setKey("evenIndex");
    localanQ.bb(localdlQ);
    localdlQ.brn();
    cOk localcOk = new cOk();
    localcOk.aJ();
    localcOk.setElementMap(localcpa);
    localdlQ.bb(localcOk);
    localcOk.brn();
    localcOk.rV();
    localdlQ.rV();
    localanQ.rV();
    dRq localdRq18 = dRq.checkOut();
    localdRq18.setElementMap(localcpa);
    localeR2.bb(localdRq18);
    localdRq18.brn();
    aId localaId8 = aId.checkOut();
    localaId8.setHorizontal(false);
    localdRq18.bb(localaId8);
    localaId8.brn();
    localaId8.rV();
    dRq localdRq19 = localdRq18;
    Jg localJg12 = localdRq19.getAppearance();
    localJg12.setElementMap(localcpa);
    localdRq18.bb(localJg12);
    localJg12.brn();
    jO localjO = new jO();
    localjO.aJ();
    localjO.setElementMap(localcpa);
    localjO.setColor(new bNa(0.0F, 0.0F, 0.0F, 0.1F));
    localJg12.bb(localjO);
    localjO.brn();
    localjO.rV();
    localJg12.rV();
    caF localcaF9 = new caF();
    localcaF9.aJ();
    localcaF9.setElementMap(localcpa);
    localcaF9.setNonBlocking(true);
    localcaF9.setStyle("bold");
    localcaF9.setExpandable(false);
    localdRq18.bb(localcaF9);
    localcaF9.brn();
    aaE localaaE3 = new aaE();
    localaaE3.aJ();
    localaaE3.setElementMap(localcpa);
    localaaE3.setAttribute("text");
    localaaE3.setField("territoryName");
    localcaF9.bb(localaaE3);
    localaaE3.brn();
    localaaE3.rV();
    a(localcaF9);
    localcaF9.rV();
    b(localdRq18);
    localdRq18.rV();
    localeR2.rV();
    d(localccG);
    localccG.rV();
    localddG.rV();
    localdRq10.rV();
    e(localdRq9);
    localdRq9.rV();
    localdRq7.rV();
    localdRq2.rV();
    f(localbpn);
    g(localbpn);
    h(localbpn);
    localbpn.rV();
    return localbpn;
  }

  public bdj a(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dOc localdOc = (dOc)parambdj;
    Jg localJg = localdOc.getAppearance();
    localJg.setElementMap(localcpa);
    parambdj.bb(localJg);
    localJg.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(0, 10, 0, 0));
    localJg.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg.rV();
    return localJg;
  }

  public bdj b(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setNonBlocking(true);
    localcaF1.setStyle("bold");
    localcaF1.setExpandable(false);
    parambdj.bb(localcaF1);
    localcaF1.brn();
    aaE localaaE = new aaE();
    localaaE.aJ();
    localaaE.setElementMap(localcpa);
    localaaE.setAttribute("text");
    localaaE.setField("cash");
    localcaF1.bb(localaaE);
    localaaE.brn();
    localaaE.rV();
    caF localcaF2 = localcaF1;
    Jg localJg = localcaF2.getAppearance();
    localJg.setElementMap(localcpa);
    localcaF1.bb(localJg);
    localJg.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(0, 10, 0, 0));
    localJg.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg.rV();
    localcaF1.rV();
    return localcaF1;
  }

  public bdj d(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    eR localeR = new eR();
    localeR.aJ();
    localeR.setElementMap(localcpa);
    parambdj.bb(localeR);
    localeR.brn();
    dRq localdRq = dRq.checkOut();
    localdRq.setElementMap(localcpa);
    localeR.bb(localdRq);
    localdRq.brn();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(false);
    localdRq.bb(localaId);
    localaId.brn();
    localaId.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setNonBlocking(true);
    localcaF1.setStyle("bold");
    localdRq.bb(localcaF1);
    localcaF1.brn();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("text");
    localaaE1.setField("territoryName");
    localcaF1.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    caF localcaF2 = localcaF1;
    Jg localJg1 = localcaF2.getAppearance();
    localJg1.setElementMap(localcpa);
    localcaF1.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 10, 0, 0));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    localcaF1.rV();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setNonBlocking(true);
    localcaF3.setStyle("bold");
    localcaF3.setExpandable(false);
    localdRq.bb(localcaF3);
    localcaF3.brn();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("text");
    localaaE2.setField("cash");
    localcaF3.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    caF localcaF4 = localcaF3;
    Jg localJg2 = localcaF4.getAppearance();
    localJg2.setElementMap(localcpa);
    localcaF3.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 10, 0, 0));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    localcaF3.rV();
    localdRq.rV();
    localeR.rV();
    return localeR;
  }

  public bdj e(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    aId localaId = aId.checkOut();
    localaId.setAlign(aFG.ecl);
    localdRq1.bb(localaId);
    localaId.brn();
    localaId.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setExpandable(false);
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    czO localczO1 = new czO();
    localczO1.aJ();
    localczO1.setAdaptToContentSize(true);
    localdRq2.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    biy localbiy1 = new biy();
    localbiy1.aJ();
    localbiy1.setElementMap(localcpa);
    localbiy1.setStyle("yellow");
    localbiy1.setExpandable(false);
    csA localcsA1 = new csA();
    localcsA1.hg("unloadDialog");
    localbiy1.setOnClick(localcsA1);
    localdRq2.bb(localbiy1);
    localbiy1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setAlign(ajb.dhZ);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localbiy1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    biy localbiy2 = localbiy1;
    Jg localJg1 = localbiy2.getAppearance();
    localJg1.setElementMap(localcpa);
    localbiy1.bb(localJg1);
    localJg1.brn();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(7, 7, 7, 7));
    localJg1.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    localJg1.rV();
    localbiy1.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setStyle("cancel");
    localczv1.setNonBlocking(true);
    localdRq2.bb(localczv1);
    localczv1.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.dhZ);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localczv1.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    localczv1.rV();
    localdRq2.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq3.setExpandable(false);
    localdRq1.bb(localdRq3);
    localdRq3.brn();
    czO localczO2 = new czO();
    localczO2.aJ();
    localczO2.setAdaptToContentSize(true);
    localdRq3.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    String str = "confirmButton";
    biy localbiy3 = new biy();
    localbiy3.aJ();
    localbiy3.setElementMap(localcpa);
    if ((localcpa != null) && (str != null))
      localcpa.a(str, localbiy3);
    localbiy3.setStyle("yellow");
    localbiy3.setExpandable(false);
    localbiy3.setEnabled(true);
    csA localcsA2 = new csA();
    localcsA2.hg("wakfu.protectorManagement:transferBudget(amountTextEditor,territoryCombo)");
    localbiy3.setOnClick(localcsA2);
    localdRq3.bb(localbiy3);
    localbiy3.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setAlign(ajb.dhZ);
    localcwP3.setSize(new Or(100.0F, 100.0F));
    localbiy3.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    biy localbiy4 = localbiy3;
    Jg localJg2 = localbiy4.getAppearance();
    localJg2.setElementMap(localcpa);
    localbiy3.bb(localJg2);
    localJg2.brn();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(7, 7, 7, 7));
    localJg2.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    localJg2.rV();
    localbiy3.rV();
    czv localczv2 = new czv();
    localczv2.aJ();
    localczv2.setElementMap(localcpa);
    localczv2.setStyle("apply");
    localczv2.setNonBlocking(true);
    localdRq3.bb(localczv2);
    localczv2.brn();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setAlign(ajb.dhZ);
    localcwP4.setSize(new Or(100.0F, 100.0F));
    localczv2.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    localczv2.rV();
    localdRq3.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj f(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq = dRq.checkOut();
    localdRq.setElementMap(localcpa);
    parambdj.bb(localdRq);
    localdRq.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(100.0F, 100.0F));
    localdRq.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localdRq.rV();
    return localdRq;
  }

  public bdj g(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    biy localbiy = new biy();
    localbiy.aJ();
    localbiy.setElementMap(localcpa);
    localbiy.setStyle("close");
    localbiy.setExpandable(false);
    csA localcsA = new csA();
    localcsA.hg("unloadDialog");
    localbiy.setOnClick(localcsA);
    parambdj.bb(localbiy);
    localbiy.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(-2, -2));
    localcwP.setAlign(ajb.dhV);
    localcwP.setXOffset(-18);
    localcwP.setYOffset(-12);
    localbiy.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localbiy.rV();
    return localbiy;
  }

  public bdj h(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setAlign(ajb.dhZ);
    parambdj.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    return localcwP;
  }
}