import java.awt.Insets;
import java.util.Stack;

public class dzA
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setPrefSize(new Or(360, 50));
    localdRq1.setStyle("MainBackground");
    localdRq1.setNonBlocking(false);
    localdRq1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setAlign(ajb.dhZ);
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    bTm localbTm = new bTm();
    localbTm.aJ();
    localdRq1.bb(localbTm);
    localbTm.brn();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setStyle("topWindow");
    localbTm.bb(localdRq2);
    localdRq2.brn();
    cba localcba1 = cba.checkOut();
    localcba1.setElementMap(localcpa);
    localcba1.setData(cFu.izS);
    localdRq2.bb(localcba1);
    localcba1.brn();
    localcba1.rV();
    czO localczO = new czO();
    localczO.aJ();
    localczO.setAdaptToContentSize(true);
    localdRq2.bb(localczO);
    localczO.brn();
    localczO.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    String str1 = "%menu%";
    str1 = str1.replace("%menu%", cBQ.cxL().mL("menu"));
    localcaF1.setText(str1);
    localcaF1.setStyle("title");
    localdRq2.bb(localcaF1);
    localcaF1.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.dhZ);
    localcaF1.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    caF localcaF2 = localcaF1;
    Jg localJg1 = localcaF2.getAppearance();
    localJg1.setElementMap(localcpa);
    ((cwJ)localJg1).setAlignment(aFG.eck);
    localcaF1.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(5, 0, 0, 0));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    localcaF1.rV();
    dAS localdAS = new dAS();
    localdAS.aJ();
    localdAS.setElementMap(localcpa);
    localdRq2.bb(localdAS);
    localdAS.brn();
    localdAS.rV();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setExpandable(false);
    localdRq2.bb(localcaF3);
    localcaF3.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setAlign(ajb.dia);
    localcaF3.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("text");
    localNK1.setName("buildVersion");
    localcaF3.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    caF localcaF4 = localcaF3;
    Jg localJg2 = localcaF4.getAppearance();
    localJg2.setElementMap(localcpa);
    localcaF3.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 0, 0, 15));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    localcaF3.rV();
    localdRq2.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localbTm.bb(localdRq3);
    localdRq3.brn();
    dRq localdRq4 = localdRq3;
    Jg localJg3 = localdRq4.getAppearance();
    localJg3.setElementMap(localcpa);
    localdRq3.bb(localJg3);
    localJg3.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(10, 10, 10, 10));
    localJg3.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg3.rV();
    cba localcba2 = cba.checkOut();
    localcba2.setElementMap(localcpa);
    localcba2.setData(cFu.izR);
    localdRq3.bb(localcba2);
    localcba2.brn();
    localcba2.rV();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(false);
    localdRq3.bb(localaId);
    localaId.brn();
    biy localbiy1 = new biy();
    localbiy1.aJ();
    localbiy1.setElementMap(localcpa);
    String str2 = "%options%";
    str2 = str2.replace("%options%", cBQ.cxL().mL("options"));
    localbiy1.setText(str2);
    localbiy1.setExpandable(false);
    csA localcsA1 = new csA();
    localcsA1.hg("wakfu.menu:openOptionsDialog");
    localbiy1.setOnClick(localcsA1);
    localaId.bb(localbiy1);
    localbiy1.brn();
    biy localbiy2 = localbiy1;
    Jg localJg4 = localbiy2.getAppearance();
    localJg4.setElementMap(localcpa);
    localbiy1.bb(localJg4);
    localJg4.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(0, 0, 5, 0));
    localJg4.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg4.rV();
    localbiy1.rV();
    biy localbiy3 = new biy();
    localbiy3.aJ();
    localbiy3.setElementMap(localcpa);
    String str3 = "%changeCharacter%";
    str3 = str3.replace("%changeCharacter%", cBQ.cxL().mL("changeCharacter"));
    localbiy3.setText(str3);
    localbiy3.setExpandable(false);
    csA localcsA2 = new csA();
    localcsA2.hg("wakfu.menu:goToWorldChoiceDialog");
    localbiy3.setOnClick(localcsA2);
    localaId.bb(localbiy3);
    localbiy3.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("isInGame");
    localNK2.setAttribute("usedInLayout");
    localbiy3.bb(localNK2);
    localNK2.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localNK2.bb(localanQ1);
    localanQ1.brn();
    cOk localcOk1 = new cOk();
    localcOk1.aJ();
    localcOk1.setElementMap(localcpa);
    localanQ1.bb(localcOk1);
    localcOk1.brn();
    localcOk1.rV();
    localanQ1.rV();
    localNK2.rV();
    biy localbiy4 = localbiy3;
    Jg localJg5 = localbiy4.getAppearance();
    localJg5.setElementMap(localcpa);
    localbiy3.bb(localJg5);
    localJg5.brn();
    bmv localbmv5 = bmv.checkOut();
    localbmv5.setElementMap(localcpa);
    localbmv5.setInsets(new Insets(0, 0, 5, 0));
    localJg5.bb(localbmv5);
    localbmv5.brn();
    localbmv5.rV();
    localJg5.rV();
    localbiy3.rV();
    biy localbiy5 = new biy();
    localbiy5.aJ();
    localbiy5.setElementMap(localcpa);
    String str4 = "%disconnect%";
    str4 = str4.replace("%disconnect%", cBQ.cxL().mL("disconnect"));
    localbiy5.setText(str4);
    localbiy5.setExpandable(false);
    csA localcsA3 = new csA();
    localcsA3.hg("wakfu.menu:loggoff");
    localbiy5.setOnClick(localcsA3);
    localaId.bb(localbiy5);
    localbiy5.brn();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setName("isConnected");
    localNK3.setAttribute("usedInLayout");
    localbiy5.bb(localNK3);
    localNK3.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localNK3.bb(localanQ2);
    localanQ2.brn();
    cOk localcOk2 = new cOk();
    localcOk2.aJ();
    localcOk2.setElementMap(localcpa);
    localanQ2.bb(localcOk2);
    localcOk2.brn();
    localcOk2.rV();
    localanQ2.rV();
    localNK3.rV();
    biy localbiy6 = localbiy5;
    Jg localJg6 = localbiy6.getAppearance();
    localJg6.setElementMap(localcpa);
    localbiy5.bb(localJg6);
    localJg6.brn();
    bmv localbmv6 = bmv.checkOut();
    localbmv6.setElementMap(localcpa);
    localbmv6.setInsets(new Insets(0, 0, 5, 0));
    localJg6.bb(localbmv6);
    localbmv6.brn();
    localbmv6.rV();
    localJg6.rV();
    localbiy5.rV();
    biy localbiy7 = new biy();
    localbiy7.aJ();
    localbiy7.setElementMap(localcpa);
    String str5 = "%quit%";
    str5 = str5.replace("%quit%", cBQ.cxL().mL("quit"));
    localbiy7.setText(str5);
    localbiy7.setExpandable(false);
    csA localcsA4 = new csA();
    localcsA4.hg("wakfu:quit");
    localbiy7.setOnClick(localcsA4);
    localaId.bb(localbiy7);
    localbiy7.brn();
    biy localbiy8 = localbiy7;
    Jg localJg7 = localbiy8.getAppearance();
    localJg7.setElementMap(localcpa);
    localbiy7.bb(localJg7);
    localJg7.brn();
    bmv localbmv7 = bmv.checkOut();
    localbmv7.setElementMap(localcpa);
    localbmv7.setInsets(new Insets(0, 0, 5, 0));
    localJg7.bb(localbmv7);
    localbmv7.brn();
    localbmv7.rV();
    localJg7.rV();
    localbiy7.rV();
    biy localbiy9 = new biy();
    localbiy9.aJ();
    localbiy9.setElementMap(localcpa);
    String str6 = "%backToGame%";
    str6 = str6.replace("%backToGame%", cBQ.cxL().mL("backToGame"));
    localbiy9.setText(str6);
    localbiy9.setExpandable(false);
    csA localcsA5 = new csA();
    localcsA5.hg("wakfu.menu:closeMenuDialog");
    localbiy9.setOnClick(localcsA5);
    localaId.bb(localbiy9);
    localbiy9.brn();
    biy localbiy10 = localbiy9;
    Jg localJg8 = localbiy10.getAppearance();
    localJg8.setElementMap(localcpa);
    localbiy9.bb(localJg8);
    localJg8.brn();
    bmv localbmv8 = bmv.checkOut();
    localbmv8.setElementMap(localcpa);
    localbmv8.setInsets(new Insets(5, 0, 0, 0));
    localJg8.bb(localbmv8);
    localbmv8.brn();
    localbmv8.rV();
    localJg8.rV();
    localbiy9.rV();
    localaId.rV();
    localdRq3.rV();
    localbTm.rV();
    localdRq1.rV();
    return localdRq1;
  }
}