import java.awt.Insets;
import java.util.Stack;

public class dar
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    bpn localbpn = new bpn();
    localbpn.aJ();
    localbpn.setElementMap(localcpa);
    localbpn.setPack(true);
    localbpn.brn();
    czO localczO1 = new czO();
    localczO1.aJ();
    localczO1.setAdaptToContentSize(true);
    localbpn.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localbpn.bb(localdRq1);
    localdRq1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    localdRq1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setStyle("windowNew");
    localbpn.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(10, 5, 12, 5));
    localJg1.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    localJg1.rV();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localdRq2.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localaId1.setAlign(aFG.ech);
    localdRq2.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dqa localdqa1 = new dqa();
    localdqa1.aJ();
    localdqa1.setElementMap(localcpa);
    localdqa1.setExpandable(false);
    localdRq2.bb(localdqa1);
    localdqa1.brn();
    dqa localdqa2 = localdqa1;
    Jg localJg2 = localdqa2.getAppearance();
    localJg2.setElementMap(localcpa);
    localdqa1.bb(localJg2);
    localJg2.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 10, 0, 10));
    localJg2.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg2.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setStyle("titleBar");
    localdqa1.bb(localdRq4);
    localdRq4.brn();
    dRq localdRq5 = localdRq4;
    Jg localJg3 = localdRq5.getAppearance();
    localJg3.setElementMap(localcpa);
    localdRq4.bb(localJg3);
    localJg3.brn();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(2, 20, 3, 20));
    localJg3.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    localJg3.rV();
    aId localaId2 = aId.checkOut();
    localaId2.setHorizontal(false);
    localdRq4.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq6.setExpandable(false);
    localdRq4.bb(localdRq6);
    localdRq6.brn();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.eck);
    localdRq6.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("StyledBold16White");
    localcaF1.setNonBlocking(true);
    String str1 = "%chat.contactList%";
    str1 = str1.replace("%chat.contactList%", cBQ.cxL().mL("chat.contactList"));
    localcaF1.setText(str1);
    localdRq6.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg4 = localcaF2.getAppearance();
    localJg4.setElementMap(localcpa);
    ((cwJ)localJg4).setAlignment(aFG.eck);
    localcaF1.bb(localJg4);
    localJg4.brn();
    localJg4.rV();
    localcaF1.rV();
    localdRq6.rV();
    localdRq4.rV();
    localdqa1.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localdRq2.bb(localdRq7);
    localdRq7.brn();
    dRq localdRq8 = localdRq7;
    Jg localJg5 = localdRq8.getAppearance();
    localJg5.setElementMap(localcpa);
    localdRq7.bb(localJg5);
    localJg5.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 12, 0, 12));
    localJg5.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg5.rV();
    String str2 = "windowContentContainer";
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localdRq9);
    localdRq7.bb(localdRq9);
    localdRq9.brn();
    dRq localdRq10 = dRq.checkOut();
    localdRq10.setElementMap(localcpa);
    localdRq9.bb(localdRq10);
    localdRq10.brn();
    czO localczO2 = new czO();
    localczO2.aJ();
    localczO2.setAdaptToContentSize(true);
    localdRq10.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    dRq localdRq11 = dRq.checkOut();
    localdRq11.setElementMap(localcpa);
    localdRq10.bb(localdRq11);
    localdRq11.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setAlign(ajb.dif);
    localcwP3.setSize(new Or(100.0F, 100.0F));
    localdRq11.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    aId localaId3 = aId.checkOut();
    localaId3.setHorizontal(false);
    localaId3.setAlign(aFG.ech);
    localdRq11.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    String str3 = "tabbedContainer";
    dad localdad1 = new dad();
    localdad1.aJ();
    localdad1.setElementMap(localcpa);
    if ((localcpa != null) && (str3 != null))
      localcpa.a(str3, localdad1);
    localdad1.setTabsXOffset(6);
    localdad1.setTabsYOffset(-6);
    localdad1.setTabsSizesEquilibrate(false);
    localdad1.setTextOrientation(Pw.chX);
    localdad1.setTabsLabelAlignment(aFG.eck);
    localdad1.setTabsPosition(aFD.ebV);
    localdad1.setTabsAlignment(aFE.ecd);
    localdad1.setExpandable(false);
    localdad1.setPrefSize(new Or(480, 350));
    localdRq11.bb(localdad1);
    localdad1.brn();
    dad localdad2 = localdad1;
    Jg localJg6 = localdad2.getAppearance();
    localJg6.setElementMap(localcpa);
    localdad1.bb(localJg6);
    localJg6.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(5, 5, 0, 0));
    localJg6.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg6.rV();
    buA localbuA = new buA();
    localbuA.aJ();
    localbuA.setElementMap(localcpa);
    String str4 = "%desc.friendList%";
    str4 = str4.replace("%desc.friendList%", cBQ.cxL().mL("desc.friendList"));
    localbuA.setText(str4);
    localdad1.bb(localbuA);
    localbuA.brn();
    dRq localdRq12 = dRq.checkOut();
    localdRq12.setElementMap(localcpa);
    localdRq12.setStyle("white");
    localbuA.bb(localdRq12);
    localdRq12.brn();
    dRq localdRq13 = localdRq12;
    Jg localJg7 = localdRq13.getAppearance();
    localJg7.setElementMap(localcpa);
    localdRq12.bb(localJg7);
    localJg7.brn();
    cuR localcuR3 = new cuR();
    localcuR3.aJ();
    localcuR3.setElementMap(localcpa);
    localcuR3.setInsets(new Insets(0, 15, 10, 15));
    localJg7.bb(localcuR3);
    localcuR3.brn();
    localcuR3.rV();
    localJg7.rV();
    aId localaId4 = aId.checkOut();
    localaId4.setHorizontal(false);
    localdRq12.bb(localaId4);
    localaId4.brn();
    localaId4.rV();
    dRq localdRq14 = dRq.checkOut();
    localdRq14.setElementMap(localcpa);
    localdRq14.setExpandable(false);
    localdRq12.bb(localdRq14);
    localdRq14.brn();
    aId localaId5 = aId.checkOut();
    localaId5.setAlign(aFG.ecj);
    localdRq14.bb(localaId5);
    localaId5.brn();
    localaId5.rV();
    dRq localdRq15 = dRq.checkOut();
    localdRq15.setElementMap(localcpa);
    localdRq15.setExpandable(false);
    localdRq14.bb(localdRq15);
    localdRq15.brn();
    dRq localdRq16 = localdRq15;
    Jg localJg8 = localdRq16.getAppearance();
    localJg8.setElementMap(localcpa);
    localdRq15.bb(localJg8);
    localJg8.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(3, 3, 3, 0));
    localJg8.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg8.rV();
    aId localaId6 = aId.checkOut();
    localaId6.setAlign(aFG.ecj);
    localdRq15.bb(localaId6);
    localaId6.brn();
    localaId6.rV();
    String str5 = "customFriendName";
    aTp localaTp = new aTp();
    localaTp.aJ();
    localaTp.setElementMap(localcpa);
    if ((localcpa != null) && (str5 != null))
      localcpa.a(str5, localaTp);
    localaTp.setMaxChars(64);
    localaTp.setPrefSize(new Or(175, 0));
    localaTp.setExpandable(false);
    String str6 = "%guild.nameToInvite%";
    str6 = str6.replace("%guild.nameToInvite%", cBQ.cxL().mL("guild.nameToInvite"));
    localaTp.setGhostText(str6);
    localaTp.setSelectOnFocus(true);
    aOn localaOn = new aOn();
    localaOn.hg("wakfu.contactList:addFriend()");
    localaTp.setOnKeyPress(localaOn);
    localdRq15.bb(localaTp);
    localaTp.brn();
    localaTp.rV();
    biy localbiy1 = new biy();
    localbiy1.aJ();
    localbiy1.setElementMap(localcpa);
    localbiy1.setStyle("add");
    localbiy1.setExpandable(false);
    csA localcsA = new csA();
    localcsA.hg("wakfu.contactList:addFriend()");
    localbiy1.setOnClick(localcsA);
    cCu localcCu1 = new cCu();
    localcCu1.hg("popup(addToFriendPopup)");
    localbiy1.setOnPopupDisplay(localcCu1);
    jL localjL1 = new jL();
    localjL1.hg("closePopup");
    localbiy1.setOnPopupHide(localjL1);
    localdRq15.bb(localbiy1);
    localbiy1.brn();
    biy localbiy2 = localbiy1;
    Jg localJg9 = localbiy2.getAppearance();
    localJg9.setElementMap(localcpa);
    localbiy1.bb(localJg9);
    localJg9.brn();
    cuR localcuR4 = new cuR();
    localcuR4.aJ();
    localcuR4.setElementMap(localcpa);
    localcuR4.setInsets(new Insets(2, 2, 2, 2));
    localJg9.bb(localcuR4);
    localcuR4.brn();
    localcuR4.rV();
    localJg9.rV();
    String str7 = "addToFriendPopup";
    anG localanG1 = new anG();
    localanG1.aJ();
    localanG1.setElementMap(localcpa);
    if ((localcpa != null) && (str7 != null))
      localcpa.a(str7, localanG1);
    localanG1.setAlign(aFG.ech);
    localanG1.setHotSpotPosition(aFG.ecn);
    localbiy1.bb(localanG1);
    localanG1.brn();
    dRq localdRq17 = dRq.checkOut();
    localdRq17.setElementMap(localcpa);
    localdRq17.setPrefSize(new Or(10, 0));
    localdRq17.setStyle("popup");
    localanG1.bb(localdRq17);
    localdRq17.brn();
    cba localcba1 = cba.checkOut();
    localcba1.setElementMap(localcpa);
    localcba1.setData(cFu.izV);
    localdRq17.bb(localcba1);
    localcba1.brn();
    localcba1.rV();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setStyle("PopupInformation");
    String str8 = "%addToFriendList%";
    str8 = str8.replace("%addToFriendList%", cBQ.cxL().mL("addToFriendList"));
    localcaF3.setText(str8);
    localdRq17.bb(localcaF3);
    localcaF3.brn();
    caF localcaF4 = localcaF3;
    Jg localJg10 = localcaF4.getAppearance();
    localJg10.setElementMap(localcpa);
    ((cwJ)localJg10).setAlignment(aFG.ecj);
    localcaF3.bb(localJg10);
    localJg10.brn();
    localJg10.rV();
    localcaF3.rV();
    localdRq17.rV();
    localanG1.rV();
    localbiy1.rV();
    localdRq15.rV();
    localdRq14.rV();
    String str9 = "guildTable";
    aXE localaXE = new aXE();
    localaXE.aJ();
    localaXE.setElementMap(localcpa);
    if ((localcpa != null) && (str9 != null))
      localcpa.a(str9, localaXE);
    localaXE.setCellHeight(30);
    localaXE.setMinRows(8);
    localaXE.setMaxRows(8);
    localaXE.setExpandable(false);
    localdRq12.bb(localaXE);
    localaXE.brn();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setName("contact.list");
    localNK.setAttribute("content");
    localNK.setField("friendsList/contentList");
    localaXE.bb(localNK);
    localNK.brn();
    localNK.rV();
    bSJ localbSJ = new bSJ();
    localbSJ.aJ();
    localbSJ.setElementMap(localcpa);
    localbSJ.setCellWidth(250);
    String str10 = "%name%";
    str10 = str10.replace("%name%", cBQ.cxL().mL("name"));
    localbSJ.setName(str10);
    localbSJ.setColumnId("name");
    localaXE.bb(localbSJ);
    localbSJ.brn();
    eR localeR = new eR();
    localeR.aJ();
    localeR.setElementMap(localcpa);
    localbSJ.bb(localeR);
    localeR.brn();
    String str11 = "name";
    dRq localdRq18 = dRq.checkOut();
    localdRq18.setElementMap(localcpa);
    if ((localcpa != null) && (str11 != null))
      localcpa.a(str11, localdRq18);
    cCu localcCu2 = new cCu();
    localcCu2.hg("popup(contactPopup)");
    localdRq18.setOnPopupDisplay(localcCu2);
    jL localjL2 = new jL();
    localjL2.hg("closePopup");
    localdRq18.setOnPopupHide(localjL2);
    localeR.bb(localdRq18);
    localdRq18.brn();
    String str12 = "contactPopup";
    anG localanG2 = new anG();
    localanG2.aJ();
    localanG2.setElementMap(localcpa);
    if ((localcpa != null) && (str12 != null))
      localcpa.a(str12, localanG2);
    localanG2.setAlign(aFG.ech);
    localanG2.setHotSpotPosition(aFG.ecn);
    localdRq18.bb(localanG2);
    localanG2.brn();
    dRq localdRq19 = dRq.checkOut();
    localdRq19.setElementMap(localcpa);
    localdRq19.setPrefSize(new Or(10, 0));
    localdRq19.setStyle("popup");
    localanG2.bb(localdRq19);
    localdRq19.brn();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("visible");
    localaaE1.setField("commentary");
    localdRq19.bb(localaaE1);
    localaaE1.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localaaE1.bb(localanQ);
    localanQ.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localanQ.bb(localanE);
    localanE.brn();
    localanE.rV();
    localanQ.rV();
    localaaE1.rV();
    cba localcba2 = cba.checkOut();
    localcba2.setElementMap(localcpa);
    localcba2.setData(cFu.izR);
    localdRq19.bb(localcba2);
    localcba2.brn();
    localcba2.rV();
    caF localcaF5 = new caF();
    localcaF5.aJ();
    localcaF5.setElementMap(localcpa);
    localcaF5.setStyle("PopupInformation");
    localdRq19.bb(localcaF5);
    localcaF5.brn();
    caF localcaF6 = localcaF5;
    Jg localJg11 = localcaF6.getAppearance();
    localJg11.setElementMap(localcpa);
    ((cwJ)localJg11).setAlignment(aFG.ecj);
    localcaF5.bb(localJg11);
    localJg11.brn();
    localJg11.rV();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("text");
    localaaE2.setField("commentary");
    localcaF5.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    localcaF5.rV();
    localdRq19.rV();
    localanG2.rV();
    dRq localdRq20 = localdRq18;
    Jg localJg12 = localdRq20.getAppearance();
    localJg12.setElementMap(localcpa);
    localJg12.setModulationColor(new bNa(1.0F, 1.0F, 1.0F, 0.0F));
    localdRq18.bb(localJg12);
    localJg12.brn();
    jO localjO = new jO();
    localjO.aJ();
    localjO.setElementMap(localcpa);
    localjO.setColor(new bNa(1.0F, 1.0F, 1.0F, 1.0F));
    localJg12.bb(localjO);
    localjO.brn();
    localjO.rV();
    localJg12.rV();
    aId localaId7 = aId.checkOut();
    localaId7.setAlign(aFG.ecj);
    localdRq18.bb(localaId7);
    localaId7.brn();
    localaId7.rV();
    dRq localdRq21 = localdRq18;
    Jg localJg13 = localdRq21.getAppearance();
    localJg13.setElementMap(localcpa);
    localdRq18.bb(localJg13);
    localJg13.brn();
    a(localJg13);
    localJg13.rV();
    b(localdRq18);
    d(localdRq18);
    e(localdRq18);
    localdRq18.rV();
    localeR.rV();
    localbSJ.rV();
    f(localaXE);
    g(localaXE);
    localaXE.rV();
    localdRq12.rV();
    localbuA.rV();
    m(localdad1);
    localdad1.rV();
    localdRq11.rV();
    o(localdRq10);
    localdRq10.rV();
    localdRq9.rV();
    localdRq7.rV();
    localdRq2.rV();
    p(localbpn);
    q(localbpn);
    r(localbpn);
    localbpn.rV();
    return localbpn;
  }

  public bdj a(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    cuR localcuR = new cuR();
    localcuR.aJ();
    localcuR.setElementMap(localcpa);
    localcuR.setInsets(new Insets(0, 1, 0, 0));
    parambdj.bb(localcuR);
    localcuR.brn();
    localcuR.rV();
    return localcuR;
  }

  public bdj b(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setExpandable(false);
    parambdj.bb(localczv1);
    localczv1.brn();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("visible");
    localczv1.bb(localaaE1);
    localaaE1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localaaE1.bb(localanQ1);
    localanQ1.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localanQ1.bb(localanE);
    localanE.brn();
    localanE.rV();
    localanQ1.rV();
    localaaE1.rV();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("style");
    localaaE2.setField("online");
    localczv1.bb(localaaE2);
    localaaE2.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localanQ2.setValue("ConnectedStatut");
    localanQ2.setElseValue("DisconnectedStatut");
    localaaE2.bb(localanQ2);
    localanQ2.brn();
    cOk localcOk = new cOk();
    localcOk.aJ();
    localcOk.setElementMap(localcpa);
    localanQ2.bb(localcOk);
    localcOk.brn();
    localcOk.rV();
    localanQ2.rV();
    localaaE2.rV();
    czv localczv2 = localczv1;
    Jg localJg = localczv2.getAppearance();
    localJg.setElementMap(localcpa);
    localczv1.bb(localJg);
    localJg.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(2, 2, 2, 4));
    localJg.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg.rV();
    localczv1.rV();
    return localczv1;
  }

  public bdj d(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq = dRq.checkOut();
    localdRq.setElementMap(localcpa);
    localdRq.setNeedsScissor(true);
    localdRq.setExpandable(false);
    parambdj.bb(localdRq);
    localdRq.brn();
    czO localczO = new czO();
    localczO.aJ();
    localczO.setAdaptToContentSize(true);
    localdRq.bb(localczO);
    localczO.brn();
    localczO.rV();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setExpandable(false);
    localczv.setScaled(true);
    localdRq.bb(localczv);
    localczv.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(85, 28));
    localczv.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv.bb(localaAR);
    localaAR.brn();
    aaE localaaE = new aaE();
    localaaE.aJ();
    localaaE.setElementMap(localcpa);
    localaaE.setAttribute("texture");
    localaaE.setField("illustrationUrl");
    localaAR.bb(localaaE);
    localaaE.brn();
    localaaE.rV();
    localaAR.rV();
    localczv.rV();
    localdRq.rV();
    return localdRq;
  }

  public bdj e(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq = dRq.checkOut();
    localdRq.setElementMap(localcpa);
    localdRq.setExpandable(false);
    parambdj.bb(localdRq);
    localdRq.brn();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(false);
    localaId.setAlign(aFG.ech);
    localdRq.bb(localaId);
    localaId.brn();
    localaId.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("whiteBold");
    localcaF1.setMinWidth(150);
    localcaF1.setMaxWidth(150);
    localcaF1.setExpandable(false);
    localcaF1.setEnableAutoZoomShrink(true);
    localdRq.bb(localcaF1);
    localcaF1.brn();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("text");
    localaaE1.setField("name");
    localcaF1.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    caF localcaF2 = localcaF1;
    Jg localJg1 = localcaF2.getAppearance();
    localJg1.setElementMap(localcpa);
    localcaF1.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(3, 3, 0, 0));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    localcaF1.rV();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setStyle("LightBlue");
    localcaF3.setMinWidth(150);
    localcaF3.setMaxWidth(150);
    localcaF3.setExpandable(false);
    localcaF3.setEnableAutoZoomShrink(true);
    localdRq.bb(localcaF3);
    localcaF3.brn();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("text");
    localaaE2.setField("characterName");
    localcaF3.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    caF localcaF4 = localcaF3;
    Jg localJg2 = localcaF4.getAppearance();
    localJg2.setElementMap(localcpa);
    localcaF3.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 3, 0, 0));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    localcaF3.rV();
    localdRq.rV();
    return localdRq;
  }

  public bdj f(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    bSJ localbSJ = new bSJ();
    localbSJ.aJ();
    localbSJ.setElementMap(localcpa);
    localbSJ.setCellWidth(45);
    String str1 = "%levelShort%";
    str1 = str1.replace("%levelShort%", cBQ.cxL().mL("levelShort"));
    localbSJ.setName(str1);
    localbSJ.setColumnId("level");
    parambdj.bb(localbSJ);
    localbSJ.brn();
    eR localeR1 = new eR();
    localeR1.aJ();
    localeR1.setElementMap(localcpa);
    localbSJ.bb(localeR1);
    localeR1.brn();
    String str2 = "level";
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localdRq1);
    localeR1.bb(localdRq1);
    localdRq1.brn();
    dRq localdRq2 = localdRq1;
    Jg localJg1 = localdRq2.getAppearance();
    localJg1.setElementMap(localcpa);
    localJg1.setModulationColor(new bNa(1.0F, 1.0F, 1.0F, 0.0F));
    localdRq1.bb(localJg1);
    localJg1.brn();
    jO localjO = new jO();
    localjO.aJ();
    localjO.setElementMap(localcpa);
    localjO.setColor(new bNa(1.0F, 1.0F, 1.0F, 1.0F));
    localJg1.bb(localjO);
    localjO.brn();
    localjO.rV();
    localJg1.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq3.setExpandable(false);
    localdRq1.bb(localdRq3);
    localdRq3.brn();
    dRq localdRq4 = localdRq3;
    Jg localJg2 = localdRq4.getAppearance();
    localJg2.setElementMap(localcpa);
    localdRq3.bb(localJg2);
    localJg2.brn();
    ams localams1 = new ams();
    localams1.aJ();
    localams1.setElementMap(localcpa);
    localams1.setInsets(new Insets(0, 1, 0, 0));
    localams1.setColor(new bNa(1.0F, 1.0F, 1.0F, 1.0F));
    localJg2.bb(localams1);
    localams1.brn();
    localams1.rV();
    localJg2.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setPrefSize(new Or(45, 0));
    localcaF1.setMaxSize(new Or(45, 24));
    localcaF1.setExpandable(false);
    localcaF1.setStyle("whiteBold");
    localdRq3.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg3 = localcaF2.getAppearance();
    localJg3.setElementMap(localcpa);
    ((cwJ)localJg3).setAlign(aFG.eck);
    localcaF1.bb(localJg3);
    localJg3.brn();
    localJg3.rV();
    aaE localaaE = new aaE();
    localaaE.aJ();
    localaaE.setElementMap(localcpa);
    localaaE.setAttribute("text");
    localaaE.setField("level");
    localcaF1.bb(localaaE);
    localaaE.brn();
    localaaE.rV();
    localcaF1.rV();
    localdRq3.rV();
    localdRq1.rV();
    localeR1.rV();
    eR localeR2 = new eR();
    localeR2.aJ();
    localeR2.setElementMap(localcpa);
    localbSJ.bb(localeR2);
    localeR2.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localeR2.bb(localanQ);
    localanQ.brn();
    bxx localbxx = new bxx();
    localbxx.aJ();
    localbxx.setElementMap(localcpa);
    localanQ.bb(localbxx);
    localbxx.brn();
    aIB localaIB = new aIB();
    localaIB.aJ();
    localaIB.setElementMap(localcpa);
    localbxx.bb(localaIB);
    localaIB.brn();
    localaIB.rV();
    localbxx.rV();
    localanQ.rV();
    dRq localdRq5 = dRq.checkOut();
    localdRq5.setElementMap(localcpa);
    localdRq5.setExpandable(false);
    localeR2.bb(localdRq5);
    localdRq5.brn();
    dRq localdRq6 = localdRq5;
    Jg localJg4 = localdRq6.getAppearance();
    localJg4.setElementMap(localcpa);
    localdRq5.bb(localJg4);
    localJg4.brn();
    ams localams2 = new ams();
    localams2.aJ();
    localams2.setElementMap(localcpa);
    localams2.setInsets(new Insets(0, 1, 0, 0));
    localams2.setColor(new bNa(1.0F, 1.0F, 1.0F, 1.0F));
    localJg4.bb(localams2);
    localams2.brn();
    localams2.rV();
    localJg4.rV();
    localdRq5.rV();
    localeR2.rV();
    localbSJ.rV();
    return localbSJ;
  }

  public bdj g(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    bSJ localbSJ = new bSJ();
    localbSJ.aJ();
    localbSJ.setElementMap(localcpa);
    localbSJ.setCellWidth(144);
    localbSJ.setColumnId("controls");
    parambdj.bb(localbSJ);
    localbSJ.brn();
    eR localeR = new eR();
    localeR.aJ();
    localeR.setElementMap(localcpa);
    localbSJ.bb(localeR);
    localeR.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localeR.bb(localanQ1);
    localanQ1.brn();
    bxx localbxx = new bxx();
    localbxx.aJ();
    localbxx.setElementMap(localcpa);
    localanQ1.bb(localbxx);
    localbxx.brn();
    anE localanE1 = new anE();
    localanE1.aJ();
    localanE1.setElementMap(localcpa);
    localbxx.bb(localanE1);
    localanE1.brn();
    localanE1.rV();
    localbxx.rV();
    localanQ1.rV();
    String str1 = "primaryContact";
    avo localavo = new avo();
    localavo.aJ();
    localavo.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localavo);
    localeR.bb(localavo);
    localavo.brn();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("value");
    localavo.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    localavo.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localeR.bb(localdRq1);
    localdRq1.brn();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setExpandable(false);
    localdRq2.setPrefSize(new Or(143, 0));
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    ams localams = new ams();
    localams.aJ();
    localams.setElementMap(localcpa);
    localams.setInsets(new Insets(0, 1, 0, 0));
    localams.setColor(new bNa(1.0F, 1.0F, 1.0F, 1.0F));
    localJg1.bb(localams);
    localams.brn();
    localams.rV();
    localJg1.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setAlign(aFG.ecj);
    localdRq2.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setPrefSize(new Or(143, 0));
    localdRq4.setMaxSize(new Or(143, 24));
    localdRq4.setShrinkable(true);
    localdRq4.setExpandable(false);
    localdRq2.bb(localdRq4);
    localdRq4.brn();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("visible");
    localdRq4.bb(localaaE2);
    localaaE2.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localaaE2.bb(localanQ2);
    localanQ2.brn();
    anE localanE2 = new anE();
    localanE2.aJ();
    localanE2.setElementMap(localcpa);
    localanQ2.bb(localanE2);
    localanE2.brn();
    localanE2.rV();
    localanQ2.rV();
    localaaE2.rV();
    dRq localdRq5 = localdRq4;
    Jg localJg2 = localdRq5.getAppearance();
    localJg2.setElementMap(localcpa);
    localdRq4.bb(localJg2);
    localJg2.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 2, 0, 0));
    localJg2.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg2.rV();
    czO localczO1 = new czO();
    localczO1.aJ();
    localczO1.setAdaptToContentSize(true);
    localdRq4.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq4.bb(localdRq6);
    localdRq6.brn();
    aaE localaaE3 = new aaE();
    localaaE3.aJ();
    localaaE3.setElementMap(localcpa);
    localaaE3.setAttribute("visible");
    localaaE3.setField("commentaryEdition");
    localdRq6.bb(localaaE3);
    localaaE3.brn();
    anQ localanQ3 = new anQ();
    localanQ3.aJ();
    localanQ3.setElementMap(localcpa);
    localaaE3.bb(localanQ3);
    localanQ3.brn();
    bqW localbqW = new bqW();
    localbqW.aJ();
    localbqW.setElementMap(localcpa);
    localanQ3.bb(localbqW);
    localbqW.brn();
    localbqW.rV();
    localanQ3.rV();
    localaaE3.rV();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setAlign(ajb.dhZ);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localdRq6.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    aId localaId2 = aId.checkOut();
    localaId2.setAlign(aFG.ecj);
    localdRq6.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localdRq7.setExpandable(false);
    localdRq7.setPrefSize(new Or(30, 25));
    localdRq6.bb(localdRq7);
    localdRq7.brn();
    czO localczO2 = new czO();
    localczO2.aJ();
    localdRq7.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    biy localbiy1 = new biy();
    localbiy1.aJ();
    localbiy1.setElementMap(localcpa);
    localbiy1.setStyle("yellow");
    localbiy1.setExpandable(false);
    csA localcsA1 = new csA();
    localcsA1.hg("wakfu.contactList:addCommentary(primaryContact)");
    localbiy1.setOnClick(localcsA1);
    cCu localcCu1 = new cCu();
    localcCu1.hg("popup(addCommentaryPopup)");
    localbiy1.setOnPopupDisplay(localcCu1);
    jL localjL1 = new jL();
    localjL1.hg("closePopup");
    localbiy1.setOnPopupHide(localjL1);
    localdRq7.bb(localbiy1);
    localbiy1.brn();
    aaE localaaE4 = new aaE();
    localaaE4.aJ();
    localaaE4.setElementMap(localcpa);
    localaaE4.setAttribute("enabled");
    localaaE4.setField("online");
    localbiy1.bb(localaaE4);
    localaaE4.brn();
    localaaE4.rV();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.dhZ);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localbiy1.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    biy localbiy2 = localbiy1;
    Jg localJg3 = localbiy2.getAppearance();
    localJg3.setElementMap(localcpa);
    localbiy1.bb(localJg3);
    localJg3.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(2, 2, 2, 0));
    localJg3.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg3.rV();
    String str2 = "addCommentaryPopup";
    anG localanG1 = new anG();
    localanG1.aJ();
    localanG1.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localanG1);
    localanG1.setAlign(aFG.eci);
    localanG1.setHotSpotPosition(aFG.ecm);
    localbiy1.bb(localanG1);
    localanG1.brn();
    dRq localdRq8 = dRq.checkOut();
    localdRq8.setElementMap(localcpa);
    localdRq8.setPrefSize(new Or(10, 0));
    localdRq8.setStyle("popup");
    localanG1.bb(localdRq8);
    localdRq8.brn();
    cba localcba1 = cba.checkOut();
    localcba1.setElementMap(localcpa);
    localcba1.setData(cFu.izR);
    localdRq8.bb(localcba1);
    localcba1.brn();
    localcba1.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("PopupInformation");
    String str3 = "%desc.addCommentary%";
    str3 = str3.replace("%desc.addCommentary%", cBQ.cxL().mL("desc.addCommentary"));
    localcaF1.setText(str3);
    localdRq8.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg4 = localcaF2.getAppearance();
    localJg4.setElementMap(localcpa);
    ((cwJ)localJg4).setAlignment(aFG.ecj);
    localcaF1.bb(localJg4);
    localJg4.brn();
    localJg4.rV();
    localcaF1.rV();
    localdRq8.rV();
    localanG1.rV();
    localbiy1.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setNonBlocking(true);
    localczv1.setStyle("Commentary");
    localczv1.setScaled(true);
    localdRq7.bb(localczv1);
    localczv1.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setAlign(ajb.dhZ);
    localcwP3.setXOffset(1);
    localczv1.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    czv localczv2 = localczv1;
    Jg localJg5 = localczv2.getAppearance();
    localJg5.setElementMap(localcpa);
    localczv1.bb(localJg5);
    localJg5.brn();
    aaE localaaE5 = new aaE();
    localaaE5.aJ();
    localaaE5.setElementMap(localcpa);
    localaaE5.setAttribute("modulationColor");
    localaaE5.setField("online");
    localJg5.bb(localaaE5);
    localaaE5.brn();
    anQ localanQ4 = new anQ();
    localanQ4.aJ();
    localanQ4.setElementMap(localcpa);
    localanQ4.setValue("1,1,1");
    localanQ4.setElseValue("1,1,1,0.5");
    localaaE5.bb(localanQ4);
    localanQ4.brn();
    cOk localcOk1 = new cOk();
    localcOk1.aJ();
    localcOk1.setElementMap(localcpa);
    localanQ4.bb(localcOk1);
    localcOk1.brn();
    localcOk1.rV();
    localanQ4.rV();
    localaaE5.rV();
    localJg5.rV();
    localczv1.rV();
    localdRq7.rV();
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa);
    localdRq9.setExpandable(false);
    localdRq9.setPrefSize(new Or(30, 25));
    localdRq6.bb(localdRq9);
    localdRq9.brn();
    czO localczO3 = new czO();
    localczO3.aJ();
    localdRq9.bb(localczO3);
    localczO3.brn();
    localczO3.rV();
    biy localbiy3 = new biy();
    localbiy3.aJ();
    localbiy3.setElementMap(localcpa);
    localbiy3.setStyle("yellow");
    localbiy3.setExpandable(false);
    csA localcsA2 = new csA();
    localcsA2.hg("wakfu.contactList:addFriendToGroup(primaryContact)");
    localbiy3.setOnClick(localcsA2);
    cCu localcCu2 = new cCu();
    localcCu2.hg("popup(addToGroupPopup)");
    localbiy3.setOnPopupDisplay(localcCu2);
    jL localjL2 = new jL();
    localjL2.hg("closePopup");
    localbiy3.setOnPopupHide(localjL2);
    localdRq9.bb(localbiy3);
    localbiy3.brn();
    aaE localaaE6 = new aaE();
    localaaE6.aJ();
    localaaE6.setElementMap(localcpa);
    localaaE6.setAttribute("enabled");
    localaaE6.setField("online");
    localbiy3.bb(localaaE6);
    localaaE6.brn();
    localaaE6.rV();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setAlign(ajb.dhZ);
    localcwP4.setSize(new Or(100.0F, 100.0F));
    localbiy3.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    biy localbiy4 = localbiy3;
    Jg localJg6 = localbiy4.getAppearance();
    localJg6.setElementMap(localcpa);
    localbiy3.bb(localJg6);
    localJg6.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(2, 2, 2, 0));
    localJg6.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg6.rV();
    String str4 = "addToGroupPopup";
    anG localanG2 = new anG();
    localanG2.aJ();
    localanG2.setElementMap(localcpa);
    if ((localcpa != null) && (str4 != null))
      localcpa.a(str4, localanG2);
    localanG2.setAlign(aFG.eci);
    localanG2.setHotSpotPosition(aFG.ecm);
    localbiy3.bb(localanG2);
    localanG2.brn();
    dRq localdRq10 = dRq.checkOut();
    localdRq10.setElementMap(localcpa);
    localdRq10.setPrefSize(new Or(10, 0));
    localdRq10.setStyle("popup");
    localanG2.bb(localdRq10);
    localdRq10.brn();
    cba localcba2 = cba.checkOut();
    localcba2.setElementMap(localcpa);
    localcba2.setData(cFu.izR);
    localdRq10.bb(localcba2);
    localcba2.brn();
    localcba2.rV();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setStyle("PopupInformation");
    String str5 = "%invitToJoinGroup%";
    str5 = str5.replace("%invitToJoinGroup%", cBQ.cxL().mL("invitToJoinGroup"));
    localcaF3.setText(str5);
    localdRq10.bb(localcaF3);
    localcaF3.brn();
    caF localcaF4 = localcaF3;
    Jg localJg7 = localcaF4.getAppearance();
    localJg7.setElementMap(localcpa);
    ((cwJ)localJg7).setAlignment(aFG.ecj);
    localcaF3.bb(localJg7);
    localJg7.brn();
    localJg7.rV();
    localcaF3.rV();
    localdRq10.rV();
    localanG2.rV();
    localbiy3.rV();
    czv localczv3 = new czv();
    localczv3.aJ();
    localczv3.setElementMap(localcpa);
    localczv3.setNonBlocking(true);
    localczv3.setStyle("contactsIcon");
    localdRq9.bb(localczv3);
    localczv3.brn();
    cwP localcwP5 = new cwP();
    localcwP5.aJ();
    localcwP5.setElementMap(localcpa);
    localcwP5.setAlign(ajb.dhZ);
    localcwP5.setSize(new Or(30, 30));
    localcwP5.setYOffset(-1);
    localcwP5.setXOffset(1);
    localczv3.bb(localcwP5);
    localcwP5.brn();
    localcwP5.rV();
    czv localczv4 = localczv3;
    Jg localJg8 = localczv4.getAppearance();
    localJg8.setElementMap(localcpa);
    localczv3.bb(localJg8);
    localJg8.brn();
    aaE localaaE7 = new aaE();
    localaaE7.aJ();
    localaaE7.setElementMap(localcpa);
    localaaE7.setAttribute("modulationColor");
    localaaE7.setField("online");
    localJg8.bb(localaaE7);
    localaaE7.brn();
    anQ localanQ5 = new anQ();
    localanQ5.aJ();
    localanQ5.setElementMap(localcpa);
    localanQ5.setValue("1,1,1");
    localanQ5.setElseValue("1,1,1,0.5");
    localaaE7.bb(localanQ5);
    localanQ5.brn();
    cOk localcOk2 = new cOk();
    localcOk2.aJ();
    localcOk2.setElementMap(localcpa);
    localanQ5.bb(localcOk2);
    localcOk2.brn();
    localcOk2.rV();
    localanQ5.rV();
    localaaE7.rV();
    localJg8.rV();
    localczv3.rV();
    localdRq9.rV();
    dRq localdRq11 = dRq.checkOut();
    localdRq11.setElementMap(localcpa);
    localdRq11.setExpandable(false);
    localdRq11.setPrefSize(new Or(30, 25));
    localdRq6.bb(localdRq11);
    localdRq11.brn();
    czO localczO4 = new czO();
    localczO4.aJ();
    localdRq11.bb(localczO4);
    localczO4.brn();
    localczO4.rV();
    biy localbiy5 = new biy();
    localbiy5.aJ();
    localbiy5.setElementMap(localcpa);
    localbiy5.setStyle("yellow");
    localbiy5.setExpandable(false);
    csA localcsA3 = new csA();
    localcsA3.hg("wakfu.chat:addPrivatePipe(primaryContact)");
    localbiy5.setOnClick(localcsA3);
    cCu localcCu3 = new cCu();
    localcCu3.hg("popup(privateChatPopup)");
    localbiy5.setOnPopupDisplay(localcCu3);
    jL localjL3 = new jL();
    localjL3.hg("closePopup");
    localbiy5.setOnPopupHide(localjL3);
    localbiy5.setPrefSize(new Or(19, 19));
    localdRq11.bb(localbiy5);
    localbiy5.brn();
    aaE localaaE8 = new aaE();
    localaaE8.aJ();
    localaaE8.setElementMap(localcpa);
    localaaE8.setAttribute("enabled");
    localaaE8.setField("online");
    localbiy5.bb(localaaE8);
    localaaE8.brn();
    localaaE8.rV();
    cwP localcwP6 = new cwP();
    localcwP6.aJ();
    localcwP6.setElementMap(localcpa);
    localcwP6.setAlign(ajb.dhZ);
    localcwP6.setSize(new Or(100.0F, 100.0F));
    localbiy5.bb(localcwP6);
    localcwP6.brn();
    localcwP6.rV();
    biy localbiy6 = localbiy5;
    Jg localJg9 = localbiy6.getAppearance();
    localJg9.setElementMap(localcpa);
    localbiy5.bb(localJg9);
    localJg9.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(2, 2, 2, 0));
    localJg9.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg9.rV();
    h(localbiy5);
    localbiy5.rV();
    i(localdRq11);
    localdRq11.rV();
    j(localdRq6);
    localdRq6.rV();
    k(localdRq4);
    localdRq4.rV();
    localdRq2.rV();
    localdRq1.rV();
    localeR.rV();
    l(localbSJ);
    localbSJ.rV();
    return localbSJ;
  }

  public bdj h(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    String str1 = "privateChatPopup";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localanG);
    localanG.setAlign(aFG.eci);
    localanG.setHotSpotPosition(aFG.ecm);
    parambdj.bb(localanG);
    localanG.brn();
    dRq localdRq = dRq.checkOut();
    localdRq.setElementMap(localcpa);
    localdRq.setPrefSize(new Or(10, 0));
    localdRq.setStyle("popup");
    localanG.bb(localdRq);
    localdRq.brn();
    cba localcba = cba.checkOut();
    localcba.setElementMap(localcpa);
    localcba.setData(cFu.izR);
    localdRq.bb(localcba);
    localcba.brn();
    localcba.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("PopupInformation");
    String str2 = "%createPrivateChat%";
    str2 = str2.replace("%createPrivateChat%", cBQ.cxL().mL("createPrivateChat"));
    localcaF1.setText(str2);
    localdRq.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg = localcaF2.getAppearance();
    localJg.setElementMap(localcpa);
    ((cwJ)localJg).setAlignment(aFG.ecj);
    localcaF1.bb(localJg);
    localJg.brn();
    localJg.rV();
    localcaF1.rV();
    localdRq.rV();
    localanG.rV();
    return localanG;
  }

  public bdj i(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setNonBlocking(true);
    localczv1.setStyle("privateChat");
    localczv1.setScaled(true);
    localczv1.setDisplaySize(new Or(20, 20));
    parambdj.bb(localczv1);
    localczv1.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setAlign(ajb.dhZ);
    localcwP.setXOffset(2);
    localczv1.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    czv localczv2 = localczv1;
    Jg localJg = localczv2.getAppearance();
    localJg.setElementMap(localcpa);
    localczv1.bb(localJg);
    localJg.brn();
    aaE localaaE = new aaE();
    localaaE.aJ();
    localaaE.setElementMap(localcpa);
    localaaE.setAttribute("modulationColor");
    localaaE.setField("online");
    localJg.bb(localaaE);
    localaaE.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localanQ.setValue("1,1,1");
    localanQ.setElseValue("1,1,1,0.5");
    localaaE.bb(localanQ);
    localanQ.brn();
    cOk localcOk = new cOk();
    localcOk.aJ();
    localcOk.setElementMap(localcpa);
    localanQ.bb(localcOk);
    localcOk.brn();
    localcOk.rV();
    localanQ.rV();
    localaaE.rV();
    localJg.rV();
    localczv1.rV();
    return localczv1;
  }

  public bdj j(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    localdRq1.setPrefSize(new Or(35, 0));
    parambdj.bb(localdRq1);
    localdRq1.brn();
    biy localbiy = new biy();
    localbiy.aJ();
    localbiy.setElementMap(localcpa);
    localbiy.setStyle("smallCancel");
    localbiy.setExpandable(false);
    csA localcsA = new csA();
    localcsA.hg("wakfu.contactList:removeFriend(primaryContact)");
    localbiy.setOnClick(localcsA);
    cCu localcCu = new cCu();
    localcCu.hg("popup(descRemoveFromContactsPopup)");
    localbiy.setOnPopupDisplay(localcCu);
    jL localjL = new jL();
    localjL.hg("closePopup");
    localbiy.setOnPopupHide(localjL);
    localdRq1.bb(localbiy);
    localbiy.brn();
    String str1 = "descRemoveFromContactsPopup";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localanG);
    localanG.setAlign(aFG.eci);
    localanG.setHotSpotPosition(aFG.ecm);
    localbiy.bb(localanG);
    localanG.brn();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setPrefSize(new Or(10, 0));
    localdRq2.setStyle("popup");
    localanG.bb(localdRq2);
    localdRq2.brn();
    cba localcba = cba.checkOut();
    localcba.setElementMap(localcpa);
    localcba.setData(cFu.izR);
    localdRq2.bb(localcba);
    localcba.brn();
    localcba.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("PopupInformation");
    String str2 = "%chat.removeFromContactList%";
    str2 = str2.replace("%chat.removeFromContactList%", cBQ.cxL().mL("chat.removeFromContactList"));
    localcaF1.setText(str2);
    localdRq2.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg = localcaF2.getAppearance();
    localJg.setElementMap(localcpa);
    ((cwJ)localJg).setAlignment(aFG.ecj);
    localcaF1.bb(localJg);
    localJg.brn();
    localJg.rV();
    localcaF1.rV();
    localdRq2.rV();
    localanG.rV();
    localbiy.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj k(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq = dRq.checkOut();
    localdRq.setElementMap(localcpa);
    localdRq.setExpandable(false);
    localdRq.setVisible(false);
    parambdj.bb(localdRq);
    localdRq.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setAlign(ajb.dhZ);
    localcwP.setSize(new Or(100.0F, 100.0F));
    localdRq.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("visible");
    localaaE1.setField("commentaryEdition");
    localdRq.bb(localaaE1);
    localaaE1.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localaaE1.bb(localanQ);
    localanQ.brn();
    cOk localcOk = new cOk();
    localcOk.aJ();
    localcOk.setElementMap(localcpa);
    localanQ.bb(localcOk);
    localcOk.brn();
    localcOk.rV();
    localanQ.rV();
    localaaE1.rV();
    String str = "customCommentary";
    aTp localaTp1 = new aTp();
    localaTp1.aJ();
    localaTp1.setElementMap(localcpa);
    if ((localcpa != null) && (str != null))
      localcpa.a(str, localaTp1);
    localaTp1.setAutoHorizontalScrolled(Boolean.valueOf(true));
    localaTp1.setExpandable(false);
    localaTp1.setMaxChars(255);
    aOn localaOn = new aOn();
    localaOn.hg("wakfu.contactList:validCommentary(primaryContact,customCommentary)");
    localaTp1.setOnKeyPress(localaOn);
    localaTp1.setPrefSize(new Or(93, 0));
    localdRq.bb(localaTp1);
    localaTp1.brn();
    aTp localaTp2 = localaTp1;
    Jg localJg = localaTp2.getAppearance();
    localJg.setElementMap(localcpa);
    localaTp1.bb(localJg);
    localJg.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(5, 0, 5, 5));
    localJg.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg.rV();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("text");
    localaaE2.setField("commentary");
    localaTp1.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    localaTp1.rV();
    biy localbiy = new biy();
    localbiy.aJ();
    localbiy.setElementMap(localcpa);
    localbiy.setAlign(aFG.ecj);
    localbiy.setStyle("smallValid");
    localbiy.setExpandable(false);
    csA localcsA = new csA();
    localcsA.hg("wakfu.contactList:validCommentary(primaryContact,customCommentary)");
    localbiy.setOnClick(localcsA);
    localdRq.bb(localbiy);
    localbiy.brn();
    localbiy.rV();
    localdRq.rV();
    return localdRq;
  }

  public bdj l(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    eR localeR = new eR();
    localeR.aJ();
    localeR.setElementMap(localcpa);
    parambdj.bb(localeR);
    localeR.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localeR.bb(localanQ);
    localanQ.brn();
    bxx localbxx = new bxx();
    localbxx.aJ();
    localbxx.setElementMap(localcpa);
    localanQ.bb(localbxx);
    localbxx.brn();
    aIB localaIB = new aIB();
    localaIB.aJ();
    localaIB.setElementMap(localcpa);
    localbxx.bb(localaIB);
    localaIB.brn();
    localaIB.rV();
    localbxx.rV();
    localanQ.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    localdRq1.setPrefSize(new Or(143, 0));
    localeR.bb(localdRq1);
    localdRq1.brn();
    dRq localdRq2 = localdRq1;
    Jg localJg = localdRq2.getAppearance();
    localJg.setElementMap(localcpa);
    localdRq1.bb(localJg);
    localJg.brn();
    ams localams = new ams();
    localams.aJ();
    localams.setElementMap(localcpa);
    localams.setInsets(new Insets(0, 1, 0, 0));
    localams.setColor(new bNa(1.0F, 1.0F, 1.0F, 1.0F));
    localJg.bb(localams);
    localams.brn();
    localams.rV();
    localJg.rV();
    localdRq1.rV();
    localeR.rV();
    return localeR;
  }

  public bdj m(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    buA localbuA = new buA();
    localbuA.aJ();
    localbuA.setElementMap(localcpa);
    String str1 = "%desc.ignoreList%";
    str1 = str1.replace("%desc.ignoreList%", cBQ.cxL().mL("desc.ignoreList"));
    localbuA.setText(str1);
    parambdj.bb(localbuA);
    localbuA.brn();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setStyle("white");
    localbuA.bb(localdRq1);
    localdRq1.brn();
    dRq localdRq2 = localdRq1;
    Jg localJg1 = localdRq2.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq1.bb(localJg1);
    localJg1.brn();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(0, 15, 10, 15));
    localJg1.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    localJg1.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localdRq1.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq3.setExpandable(false);
    localdRq1.bb(localdRq3);
    localdRq3.brn();
    aId localaId2 = aId.checkOut();
    localaId2.setAlign(aFG.ecj);
    localdRq3.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setExpandable(false);
    localdRq3.bb(localdRq4);
    localdRq4.brn();
    dRq localdRq5 = localdRq4;
    Jg localJg2 = localdRq5.getAppearance();
    localJg2.setElementMap(localcpa);
    localdRq4.bb(localJg2);
    localJg2.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(3, 3, 3, 0));
    localJg2.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg2.rV();
    aId localaId3 = aId.checkOut();
    localaId3.setAlign(aFG.ecj);
    localdRq4.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    String str2 = "customIgnoreName";
    aTp localaTp = new aTp();
    localaTp.aJ();
    localaTp.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localaTp);
    localaTp.setMaxChars(64);
    localaTp.setPrefSize(new Or(175, 0));
    localaTp.setExpandable(false);
    String str3 = "%nameToIgnore%";
    str3 = str3.replace("%nameToIgnore%", cBQ.cxL().mL("nameToIgnore"));
    localaTp.setGhostText(str3);
    localaTp.setSelectOnFocus(true);
    aOn localaOn = new aOn();
    localaOn.hg("wakfu.contactList:addIgnore()");
    localaTp.setOnKeyPress(localaOn);
    localdRq4.bb(localaTp);
    localaTp.brn();
    localaTp.rV();
    biy localbiy1 = new biy();
    localbiy1.aJ();
    localbiy1.setElementMap(localcpa);
    localbiy1.setStyle("add");
    localbiy1.setExpandable(false);
    csA localcsA1 = new csA();
    localcsA1.hg("wakfu.contactList:addIgnore()");
    localbiy1.setOnClick(localcsA1);
    cCu localcCu1 = new cCu();
    localcCu1.hg("popup(addToIgnorePopup)");
    localbiy1.setOnPopupDisplay(localcCu1);
    jL localjL1 = new jL();
    localjL1.hg("closePopup");
    localbiy1.setOnPopupHide(localjL1);
    localdRq4.bb(localbiy1);
    localbiy1.brn();
    biy localbiy2 = localbiy1;
    Jg localJg3 = localbiy2.getAppearance();
    localJg3.setElementMap(localcpa);
    localbiy1.bb(localJg3);
    localJg3.brn();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(2, 2, 2, 2));
    localJg3.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    localJg3.rV();
    String str4 = "addToIgnorePopup";
    anG localanG1 = new anG();
    localanG1.aJ();
    localanG1.setElementMap(localcpa);
    if ((localcpa != null) && (str4 != null))
      localcpa.a(str4, localanG1);
    localanG1.setAlign(aFG.ech);
    localanG1.setHotSpotPosition(aFG.ecn);
    localbiy1.bb(localanG1);
    localanG1.brn();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq6.setPrefSize(new Or(10, 0));
    localdRq6.setStyle("popup");
    localanG1.bb(localdRq6);
    localdRq6.brn();
    cba localcba1 = cba.checkOut();
    localcba1.setElementMap(localcpa);
    localcba1.setData(cFu.izV);
    localdRq6.bb(localcba1);
    localcba1.brn();
    localcba1.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("PopupInformation");
    String str5 = "%chat.addToIgnoreList%";
    str5 = str5.replace("%chat.addToIgnoreList%", cBQ.cxL().mL("chat.addToIgnoreList"));
    localcaF1.setText(str5);
    localdRq6.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg4 = localcaF2.getAppearance();
    localJg4.setElementMap(localcpa);
    ((cwJ)localJg4).setAlignment(aFG.ecj);
    localcaF1.bb(localJg4);
    localJg4.brn();
    localJg4.rV();
    localcaF1.rV();
    localdRq6.rV();
    localanG1.rV();
    localbiy1.rV();
    localdRq4.rV();
    localdRq3.rV();
    aXE localaXE = new aXE();
    localaXE.aJ();
    localaXE.setElementMap(localcpa);
    localaXE.setCellHeight(30);
    localaXE.setMinRows(8);
    localaXE.setMaxRows(8);
    localaXE.setExpandable(false);
    localdRq1.bb(localaXE);
    localaXE.brn();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setName("contact.list");
    localNK.setAttribute("content");
    localNK.setField("ignoreList/contentList");
    localaXE.bb(localNK);
    localNK.brn();
    localNK.rV();
    bSJ localbSJ1 = new bSJ();
    localbSJ1.aJ();
    localbSJ1.setElementMap(localcpa);
    localbSJ1.setCellWidth(399);
    String str6 = "%name%";
    str6 = str6.replace("%name%", cBQ.cxL().mL("name"));
    localbSJ1.setName(str6);
    localbSJ1.setColumnId("name");
    localaXE.bb(localbSJ1);
    localbSJ1.brn();
    eR localeR1 = new eR();
    localeR1.aJ();
    localeR1.setElementMap(localcpa);
    localbSJ1.bb(localeR1);
    localeR1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localeR1.bb(localanQ1);
    localanQ1.brn();
    bxx localbxx1 = new bxx();
    localbxx1.aJ();
    localbxx1.setElementMap(localcpa);
    localanQ1.bb(localbxx1);
    localbxx1.brn();
    anE localanE1 = new anE();
    localanE1.aJ();
    localanE1.setElementMap(localcpa);
    localbxx1.bb(localanE1);
    localanE1.brn();
    localanE1.rV();
    localbxx1.rV();
    localanQ1.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localeR1.bb(localdRq7);
    localdRq7.brn();
    dRq localdRq8 = localdRq7;
    Jg localJg5 = localdRq8.getAppearance();
    localJg5.setElementMap(localcpa);
    localJg5.setModulationColor(new bNa(1.0F, 1.0F, 1.0F, 0.0F));
    localdRq7.bb(localJg5);
    localJg5.brn();
    jO localjO = new jO();
    localjO.aJ();
    localjO.setElementMap(localcpa);
    localjO.setColor(new bNa(1.0F, 1.0F, 1.0F, 1.0F));
    localJg5.bb(localjO);
    localjO.brn();
    localjO.rV();
    localJg5.rV();
    aId localaId4 = aId.checkOut();
    localaId4.setAlign(aFG.ecj);
    localdRq7.bb(localaId4);
    localaId4.brn();
    localaId4.rV();
    dRq localdRq9 = localdRq7;
    Jg localJg6 = localdRq9.getAppearance();
    localJg6.setElementMap(localcpa);
    localdRq7.bb(localJg6);
    localJg6.brn();
    cuR localcuR3 = new cuR();
    localcuR3.aJ();
    localcuR3.setElementMap(localcpa);
    localcuR3.setInsets(new Insets(0, 1, 0, 0));
    localJg6.bb(localcuR3);
    localcuR3.brn();
    localcuR3.rV();
    localJg6.rV();
    dRq localdRq10 = dRq.checkOut();
    localdRq10.setElementMap(localcpa);
    localdRq10.setExpandable(false);
    localdRq7.bb(localdRq10);
    localdRq10.brn();
    aId localaId5 = aId.checkOut();
    localaId5.setHorizontal(false);
    localaId5.setAlign(aFG.ech);
    localdRq10.bb(localaId5);
    localaId5.brn();
    localaId5.rV();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setStyle("whiteBold");
    localcaF3.setMinWidth(150);
    localcaF3.setMaxWidth(150);
    localcaF3.setExpandable(false);
    localcaF3.setEnableAutoZoomShrink(true);
    localdRq10.bb(localcaF3);
    localcaF3.brn();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("text");
    localaaE1.setField("name");
    localcaF3.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    caF localcaF4 = localcaF3;
    Jg localJg7 = localcaF4.getAppearance();
    localJg7.setElementMap(localcpa);
    localcaF3.bb(localJg7);
    localJg7.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(3, 3, 0, 0));
    localJg7.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg7.rV();
    localcaF3.rV();
    localdRq10.rV();
    localdRq7.rV();
    localeR1.rV();
    localbSJ1.rV();
    bSJ localbSJ2 = new bSJ();
    localbSJ2.aJ();
    localbSJ2.setElementMap(localcpa);
    localbSJ2.setCellWidth(40);
    localbSJ2.setColumnId("controls");
    localaXE.bb(localbSJ2);
    localbSJ2.brn();
    eR localeR2 = new eR();
    localeR2.aJ();
    localeR2.setElementMap(localcpa);
    localbSJ2.bb(localeR2);
    localeR2.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localeR2.bb(localanQ2);
    localanQ2.brn();
    bxx localbxx2 = new bxx();
    localbxx2.aJ();
    localbxx2.setElementMap(localcpa);
    localanQ2.bb(localbxx2);
    localbxx2.brn();
    anE localanE2 = new anE();
    localanE2.aJ();
    localanE2.setElementMap(localcpa);
    localbxx2.bb(localanE2);
    localanE2.brn();
    localanE2.rV();
    localbxx2.rV();
    localanQ2.rV();
    String str7 = "primaryContact";
    avo localavo = new avo();
    localavo.aJ();
    localavo.setElementMap(localcpa);
    if ((localcpa != null) && (str7 != null))
      localcpa.a(str7, localavo);
    localeR2.bb(localavo);
    localavo.brn();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("value");
    localavo.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    localavo.rV();
    dRq localdRq11 = dRq.checkOut();
    localdRq11.setElementMap(localcpa);
    localeR2.bb(localdRq11);
    localdRq11.brn();
    dRq localdRq12 = dRq.checkOut();
    localdRq12.setElementMap(localcpa);
    localdRq12.setExpandable(false);
    localdRq12.setPrefSize(new Or(40, 0));
    localdRq11.bb(localdRq12);
    localdRq12.brn();
    dRq localdRq13 = localdRq12;
    Jg localJg8 = localdRq13.getAppearance();
    localJg8.setElementMap(localcpa);
    localdRq12.bb(localJg8);
    localJg8.brn();
    ams localams = new ams();
    localams.aJ();
    localams.setElementMap(localcpa);
    localams.setInsets(new Insets(0, 1, 0, 0));
    localams.setColor(new bNa(1.0F, 1.0F, 1.0F, 1.0F));
    localJg8.bb(localams);
    localams.brn();
    localams.rV();
    localJg8.rV();
    aId localaId6 = aId.checkOut();
    localaId6.setAlign(aFG.ecj);
    localdRq12.bb(localaId6);
    localaId6.brn();
    localaId6.rV();
    dRq localdRq14 = dRq.checkOut();
    localdRq14.setElementMap(localcpa);
    localdRq14.setExpandable(false);
    localdRq12.bb(localdRq14);
    localdRq14.brn();
    aaE localaaE3 = new aaE();
    localaaE3.aJ();
    localaaE3.setElementMap(localcpa);
    localaaE3.setAttribute("visible");
    localdRq14.bb(localaaE3);
    localaaE3.brn();
    anQ localanQ3 = new anQ();
    localanQ3.aJ();
    localanQ3.setElementMap(localcpa);
    localaaE3.bb(localanQ3);
    localanQ3.brn();
    anE localanE3 = new anE();
    localanE3.aJ();
    localanE3.setElementMap(localcpa);
    localanQ3.bb(localanE3);
    localanE3.brn();
    localanE3.rV();
    localanQ3.rV();
    localaaE3.rV();
    dRq localdRq15 = localdRq14;
    Jg localJg9 = localdRq15.getAppearance();
    localJg9.setElementMap(localcpa);
    localdRq14.bb(localJg9);
    localJg9.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 2, 0, 0));
    localJg9.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg9.rV();
    dRq localdRq16 = dRq.checkOut();
    localdRq16.setElementMap(localcpa);
    localdRq16.setExpandable(false);
    localdRq16.setPrefSize(new Or(35, 0));
    localdRq14.bb(localdRq16);
    localdRq16.brn();
    biy localbiy3 = new biy();
    localbiy3.aJ();
    localbiy3.setElementMap(localcpa);
    localbiy3.setStyle("smallCancel");
    localbiy3.setExpandable(false);
    csA localcsA2 = new csA();
    localcsA2.hg("wakfu.contactList:removeIgnore(primaryContact)");
    localbiy3.setOnClick(localcsA2);
    cCu localcCu2 = new cCu();
    localcCu2.hg("popup(descRemoveFromContactsPopup)");
    localbiy3.setOnPopupDisplay(localcCu2);
    jL localjL2 = new jL();
    localjL2.hg("closePopup");
    localbiy3.setOnPopupHide(localjL2);
    localdRq16.bb(localbiy3);
    localbiy3.brn();
    String str8 = "descRemoveFromContactsPopup";
    anG localanG2 = new anG();
    localanG2.aJ();
    localanG2.setElementMap(localcpa);
    if ((localcpa != null) && (str8 != null))
      localcpa.a(str8, localanG2);
    localanG2.setAlign(aFG.eci);
    localanG2.setHotSpotPosition(aFG.ecm);
    localbiy3.bb(localanG2);
    localanG2.brn();
    dRq localdRq17 = dRq.checkOut();
    localdRq17.setElementMap(localcpa);
    localdRq17.setPrefSize(new Or(10, 0));
    localdRq17.setStyle("popup");
    localanG2.bb(localdRq17);
    localdRq17.brn();
    cba localcba2 = cba.checkOut();
    localcba2.setElementMap(localcpa);
    localcba2.setData(cFu.izR);
    localdRq17.bb(localcba2);
    localcba2.brn();
    localcba2.rV();
    caF localcaF5 = new caF();
    localcaF5.aJ();
    localcaF5.setElementMap(localcpa);
    localcaF5.setStyle("PopupInformation");
    String str9 = "%chat.removeFromContactList%";
    str9 = str9.replace("%chat.removeFromContactList%", cBQ.cxL().mL("chat.removeFromContactList"));
    localcaF5.setText(str9);
    localdRq17.bb(localcaF5);
    localcaF5.brn();
    caF localcaF6 = localcaF5;
    Jg localJg10 = localcaF6.getAppearance();
    localJg10.setElementMap(localcpa);
    ((cwJ)localJg10).setAlignment(aFG.ecj);
    localcaF5.bb(localJg10);
    localJg10.brn();
    localJg10.rV();
    localcaF5.rV();
    localdRq17.rV();
    localanG2.rV();
    localbiy3.rV();
    localdRq16.rV();
    localdRq14.rV();
    localdRq12.rV();
    localdRq11.rV();
    localeR2.rV();
    eR localeR3 = new eR();
    localeR3.aJ();
    localeR3.setElementMap(localcpa);
    localbSJ2.bb(localeR3);
    localeR3.brn();
    anQ localanQ4 = new anQ();
    localanQ4.aJ();
    localanQ4.setElementMap(localcpa);
    localeR3.bb(localanQ4);
    localanQ4.brn();
    bxx localbxx3 = new bxx();
    localbxx3.aJ();
    localbxx3.setElementMap(localcpa);
    localanQ4.bb(localbxx3);
    localbxx3.brn();
    aIB localaIB = new aIB();
    localaIB.aJ();
    localaIB.setElementMap(localcpa);
    localbxx3.bb(localaIB);
    localaIB.brn();
    localaIB.rV();
    localbxx3.rV();
    localanQ4.rV();
    dRq localdRq18 = dRq.checkOut();
    localdRq18.setElementMap(localcpa);
    localdRq18.setExpandable(false);
    localdRq18.setPrefSize(new Or(40, 0));
    localeR3.bb(localdRq18);
    localdRq18.brn();
    dRq localdRq19 = localdRq18;
    Jg localJg11 = localdRq19.getAppearance();
    localJg11.setElementMap(localcpa);
    localdRq18.bb(localJg11);
    localJg11.brn();
    n(localJg11);
    localJg11.rV();
    localdRq18.rV();
    localeR3.rV();
    localbSJ2.rV();
    localaXE.rV();
    localdRq1.rV();
    localbuA.rV();
    return localbuA;
  }

  public bdj n(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    ams localams = new ams();
    localams.aJ();
    localams.setElementMap(localcpa);
    localams.setInsets(new Insets(0, 1, 0, 0));
    localams.setColor(new bNa(1.0F, 1.0F, 1.0F, 1.0F));
    parambdj.bb(localams);
    localams.brn();
    localams.rV();
    return localams;
  }

  public bdj o(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    br localbr1 = new br();
    localbr1.aJ();
    localbr1.setElementMap(localcpa);
    String str = "%guild.displayDisconnectedMembers%";
    str = str.replace("%guild.displayDisconnectedMembers%", cBQ.cxL().mL("guild.displayDisconnectedMembers"));
    localbr1.setText(str);
    localbr1.setSelected(true);
    bvO localbvO = new bvO();
    localbvO.hg("wakfu.contactList:displayDisconnectedPlayers");
    localbr1.setOnSelectionChange(localbvO);
    localbr1.setExpandable(false);
    parambdj.bb(localbr1);
    localbr1.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setAlign(ajb.dhV);
    localbr1.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    br localbr2 = localbr1;
    Jg localJg = localbr2.getAppearance();
    localJg.setElementMap(localcpa);
    localbr1.bb(localJg);
    localJg.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(20, 0, 0, 10));
    localJg.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg.rV();
    localbr1.rV();
    return localbr1;
  }

  public bdj p(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq = dRq.checkOut();
    localdRq.setElementMap(localcpa);
    parambdj.bb(localdRq);
    localdRq.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(100.0F, 100.0F));
    localdRq.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localdRq.rV();
    return localdRq;
  }

  public bdj q(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    biy localbiy = new biy();
    localbiy.aJ();
    localbiy.setElementMap(localcpa);
    localbiy.setStyle("close");
    localbiy.setExpandable(false);
    csA localcsA = new csA();
    localcsA.hg("unloadDialog");
    localbiy.setOnClick(localcsA);
    parambdj.bb(localbiy);
    localbiy.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(-2, -2));
    localcwP.setAlign(ajb.dhV);
    localcwP.setXOffset(-18);
    localcwP.setYOffset(-12);
    localbiy.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localbiy.rV();
    return localbiy;
  }

  public bdj r(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(-2, -2));
    localcwP.setAlign(ajb.dia);
    localcwP.setResizeOnce(true);
    parambdj.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    return localcwP;
  }
}