import java.awt.Insets;
import java.util.Stack;

public class caP
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    bpn localbpn = new bpn();
    localbpn.aJ();
    localbpn.setElementMap(localcpa);
    localbpn.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setAlign(ajb.dhZ);
    localcwP1.setInitValue(true);
    localbpn.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    czO localczO = new czO();
    localczO.aJ();
    localczO.setAdaptToContentSize(true);
    localbpn.bb(localczO);
    localczO.brn();
    localczO.rV();
    dqa localdqa = new dqa();
    localdqa.aJ();
    localdqa.setElementMap(localcpa);
    localbpn.bb(localdqa);
    localdqa.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localdqa.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setStyle("challengeCurrent");
    localdRq1.setPrefSize(new Or(250, 0));
    localdqa.bb(localdRq1);
    localdRq1.brn();
    dRq localdRq2 = localdRq1;
    Jg localJg1 = localdRq2.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq1.bb(localJg1);
    localJg1.brn();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(15, 32, 28, 32));
    localJg1.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    localJg1.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localdRq1.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq1.bb(localdRq3);
    localdRq3.brn();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setExpandable(false);
    localdRq3.bb(localdRq4);
    localdRq4.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setLocal(true);
    localNK1.setName("climateDetail");
    localNK1.setAttribute("visible");
    localNK1.setField("temperatureIconUrl");
    localdRq4.bb(localNK1);
    localNK1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localNK1.bb(localanQ1);
    localanQ1.brn();
    anE localanE1 = new anE();
    localanE1.aJ();
    localanE1.setElementMap(localcpa);
    localanQ1.bb(localanE1);
    localanE1.brn();
    localanE1.rV();
    localanQ1.rV();
    localNK1.rV();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa);
    localdpm1.setAlign(aFG.eck);
    localdRq4.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    dRq localdRq5 = localdRq4;
    Jg localJg2 = localdRq5.getAppearance();
    localJg2.setElementMap(localcpa);
    localdRq4.bb(localJg2);
    localJg2.brn();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(5, 6, 6, 5));
    localJg2.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    localJg2.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setNonBlocking(true);
    localczv1.setDisplaySize(new Or(32, 32));
    localczv1.setExpandable(false);
    localdRq4.bb(localczv1);
    localczv1.brn();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa);
    localdpm2.setAlign(aFG.eck);
    localczv1.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    aAR localaAR1 = aAR.checkOut();
    localaAR1.setElementMap(localcpa);
    localczv1.bb(localaAR1);
    localaAR1.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setLocal(true);
    localNK2.setName("climateDetail");
    localNK2.setAttribute("texture");
    localNK2.setField("temperatureIconUrl");
    localaAR1.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localaAR1.rV();
    localczv1.rV();
    localdRq4.rV();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq6.setExpandable(false);
    localdRq3.bb(localdRq6);
    localdRq6.brn();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setLocal(true);
    localNK3.setName("climateDetail");
    localNK3.setAttribute("visible");
    localNK3.setField("rainIconUrl");
    localdRq6.bb(localNK3);
    localNK3.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localNK3.bb(localanQ2);
    localanQ2.brn();
    anE localanE2 = new anE();
    localanE2.aJ();
    localanE2.setElementMap(localcpa);
    localanQ2.bb(localanE2);
    localanE2.brn();
    localanE2.rV();
    localanQ2.rV();
    localNK3.rV();
    dpm localdpm3 = new dpm();
    localdpm3.aJ();
    localdpm3.setElementMap(localcpa);
    localdpm3.setAlign(aFG.eck);
    localdRq6.bb(localdpm3);
    localdpm3.brn();
    localdpm3.rV();
    dRq localdRq7 = localdRq6;
    Jg localJg3 = localdRq7.getAppearance();
    localJg3.setElementMap(localcpa);
    localdRq6.bb(localJg3);
    localJg3.brn();
    cuR localcuR3 = new cuR();
    localcuR3.aJ();
    localcuR3.setElementMap(localcpa);
    localcuR3.setInsets(new Insets(5, 6, 6, 5));
    localJg3.bb(localcuR3);
    localcuR3.brn();
    localcuR3.rV();
    localJg3.rV();
    czv localczv2 = new czv();
    localczv2.aJ();
    localczv2.setElementMap(localcpa);
    localczv2.setNonBlocking(true);
    localczv2.setDisplaySize(new Or(32, 32));
    localczv2.setExpandable(false);
    localdRq6.bb(localczv2);
    localczv2.brn();
    dpm localdpm4 = new dpm();
    localdpm4.aJ();
    localdpm4.setElementMap(localcpa);
    localdpm4.setAlign(aFG.eck);
    localczv2.bb(localdpm4);
    localdpm4.brn();
    localdpm4.rV();
    aAR localaAR2 = aAR.checkOut();
    localaAR2.setElementMap(localcpa);
    localczv2.bb(localaAR2);
    localaAR2.brn();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa);
    localNK4.setLocal(true);
    localNK4.setAttribute("texture");
    localNK4.setName("climateDetail");
    localNK4.setField("rainIconUrl");
    localaAR2.bb(localNK4);
    localNK4.brn();
    localNK4.rV();
    localaAR2.rV();
    localczv2.rV();
    localdRq6.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setNonBlocking(true);
    localcWk1.setStyle("styledBold12");
    localcWk1.setExpandable(true);
    localcWk1.setMinWidth(10);
    localcWk1.setMaxWidth(200);
    localdRq3.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg4 = localcWk2.getAppearance();
    localJg4.setElementMap(localcpa);
    ((cwJ)localJg4).setAlign(aFG.ecj);
    localcWk1.bb(localJg4);
    localJg4.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 3, 0, 3));
    localJg4.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg4.rV();
    NK localNK5 = NK.checkOut();
    localNK5.setElementMap(localcpa);
    localNK5.setLocal(true);
    localNK5.setAttribute("text");
    localNK5.setName("climateDetail");
    localNK5.setField("name");
    localcWk1.bb(localNK5);
    localNK5.brn();
    localNK5.rV();
    localcWk1.rV();
    localdRq3.rV();
    dRq localdRq8 = dRq.checkOut();
    localdRq8.setElementMap(localcpa);
    localdRq8.setExpandable(false);
    localdRq1.bb(localdRq8);
    localdRq8.brn();
    dRq localdRq9 = localdRq8;
    Jg localJg5 = localdRq9.getAppearance();
    localJg5.setElementMap(localcpa);
    localdRq8.bb(localJg5);
    localJg5.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(5, 0, 0, 0));
    localJg5.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg5.rV();
    aId localaId2 = aId.checkOut();
    localaId2.setHorizontal(false);
    localaId2.setAlign(aFG.ech);
    localdRq8.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    dRq localdRq10 = dRq.checkOut();
    localdRq10.setElementMap(localcpa);
    localdRq10.setStyle("encyclopediaSplashTitle");
    localdRq8.bb(localdRq10);
    localdRq10.brn();
    dRq localdRq11 = localdRq10;
    Jg localJg6 = localdRq11.getAppearance();
    localJg6.setElementMap(localcpa);
    localdRq10.bb(localJg6);
    localJg6.brn();
    cuR localcuR4 = new cuR();
    localcuR4.aJ();
    localcuR4.setElementMap(localcpa);
    localcuR4.setInsets(new Insets(5, 10, 7, 5));
    localJg6.bb(localcuR4);
    localcuR4.brn();
    localcuR4.rV();
    localJg6.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setNonBlocking(true);
    localcaF1.setStyle("smallTitle");
    String str1 = "%description%";
    str1 = str1.replace("%description%", cBQ.cxL().mL("description"));
    localcaF1.setText(str1);
    localdRq10.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg7 = localcaF2.getAppearance();
    localJg7.setElementMap(localcpa);
    localcaF1.bb(localJg7);
    localJg7.brn();
    cAf localcAf = cAf.checkOut();
    localcAf.setElementMap(localcpa);
    localcAf.setColor(new bNa(1.0F, 1.0F, 1.0F, 1.0F));
    localcAf.setName("text");
    localJg7.bb(localcAf);
    localcAf.brn();
    localcAf.rV();
    localJg7.rV();
    localcaF1.rV();
    localdRq10.rV();
    String str2 = "requirementsContent";
    cWk localcWk3 = new cWk();
    localcWk3.aJ();
    localcWk3.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localcWk3);
    localcWk3.setStyle("bold");
    localcWk3.setExpandable(false);
    localcWk3.setMinWidth(1);
    localcWk3.setMaxWidth(235);
    localcWk3.setNonBlocking(true);
    localdRq8.bb(localcWk3);
    localcWk3.brn();
    NK localNK6 = NK.checkOut();
    localNK6.setElementMap(localcpa);
    localNK6.setLocal(true);
    localNK6.setAttribute("text");
    localNK6.setName("climateDetail");
    localNK6.setField("description");
    localcWk3.bb(localNK6);
    localNK6.brn();
    localNK6.rV();
    cWk localcWk4 = localcWk3;
    Jg localJg8 = localcWk4.getAppearance();
    localJg8.setElementMap(localcpa);
    ((cwJ)localJg8).setAlign(aFG.ecj);
    localcWk3.bb(localJg8);
    localJg8.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 10, 0, 10));
    localJg8.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg8.rV();
    localcWk3.rV();
    localdRq8.rV();
    localdRq1.rV();
    localdqa.rV();
    biy localbiy = new biy();
    localbiy.aJ();
    localbiy.setElementMap(localcpa);
    localbiy.setStyle("close");
    csA localcsA = new csA();
    localcsA.hg("unloadDialog");
    localbiy.setOnClick(localcsA);
    localbpn.bb(localbiy);
    localbiy.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setAlign(ajb.dhV);
    localcwP3.setXOffset(-28);
    localcwP3.setYOffset(-9);
    localbiy.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    localbiy.rV();
    localbpn.rV();
    return localbpn;
  }
}