import java.awt.Insets;
import java.util.Stack;

public class RO
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    bpn localbpn = new bpn();
    localbpn.aJ();
    localbpn.setElementMap(localcpa);
    localbpn.setPack(true);
    localbpn.brn();
    czO localczO1 = new czO();
    localczO1.aJ();
    localczO1.setAdaptToContentSize(true);
    localbpn.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localbpn.bb(localdRq1);
    localdRq1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    localdRq1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setStyle("windowNew");
    localbpn.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(10, 5, 12, 5));
    localJg1.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    localJg1.rV();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localdRq2.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localaId1.setAlign(aFG.ech);
    localdRq2.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dqa localdqa1 = new dqa();
    localdqa1.aJ();
    localdqa1.setElementMap(localcpa);
    localdqa1.setExpandable(false);
    localdRq2.bb(localdqa1);
    localdqa1.brn();
    dqa localdqa2 = localdqa1;
    Jg localJg2 = localdqa2.getAppearance();
    localJg2.setElementMap(localcpa);
    localdqa1.bb(localJg2);
    localJg2.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 10, 0, 10));
    localJg2.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg2.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setStyle("titleBar");
    localdqa1.bb(localdRq4);
    localdRq4.brn();
    dRq localdRq5 = localdRq4;
    Jg localJg3 = localdRq5.getAppearance();
    localJg3.setElementMap(localcpa);
    localdRq4.bb(localJg3);
    localJg3.brn();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(2, 20, 3, 20));
    localJg3.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    localJg3.rV();
    aId localaId2 = aId.checkOut();
    localaId2.setHorizontal(false);
    localdRq4.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq6.setExpandable(false);
    localdRq4.bb(localdRq6);
    localdRq6.brn();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa);
    localdpm1.setAlign(aFG.eck);
    localdRq6.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("StyledBold16White");
    localcaF1.setNonBlocking(true);
    localdRq6.bb(localcaF1);
    localcaF1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("text");
    localNK1.setField("name");
    localNK1.setName("selectedBuilding");
    localcaF1.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    caF localcaF2 = localcaF1;
    Jg localJg4 = localcaF2.getAppearance();
    localJg4.setElementMap(localcpa);
    ((cwJ)localJg4).setAlignment(aFG.eck);
    localcaF1.bb(localJg4);
    localJg4.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 0, 0, 5));
    localJg4.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg4.rV();
    localcaF1.rV();
    localdRq6.rV();
    localdRq4.rV();
    localdqa1.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localdRq2.bb(localdRq7);
    localdRq7.brn();
    dRq localdRq8 = localdRq7;
    Jg localJg5 = localdRq8.getAppearance();
    localJg5.setElementMap(localcpa);
    localdRq7.bb(localJg5);
    localJg5.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 12, 0, 12));
    localJg5.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg5.rV();
    String str1 = "windowContentContainer";
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localdRq9);
    localdRq7.bb(localdRq9);
    localdRq9.brn();
    dRq localdRq10 = localdRq9;
    Jg localJg6 = localdRq10.getAppearance();
    localJg6.setElementMap(localcpa);
    localdRq9.bb(localJg6);
    localJg6.brn();
    cuR localcuR3 = new cuR();
    localcuR3.aJ();
    localcuR3.setElementMap(localcpa);
    localcuR3.setInsets(new Insets(10, 0, 0, 0));
    localJg6.bb(localcuR3);
    localcuR3.brn();
    localcuR3.rV();
    localJg6.rV();
    aId localaId3 = aId.checkOut();
    localaId3.setHorizontal(false);
    localaId3.setAlign(aFG.ech);
    localdRq9.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    dRq localdRq11 = dRq.checkOut();
    localdRq11.setElementMap(localcpa);
    localdRq11.setExpandable(false);
    localdRq11.setPrefSize(new Or(465, 500));
    localdRq9.bb(localdRq11);
    localdRq11.brn();
    czO localczO2 = new czO();
    localczO2.aJ();
    localczO2.setAdaptToContentSize(true);
    localdRq11.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    dRq localdRq12 = dRq.checkOut();
    localdRq12.setElementMap(localcpa);
    localdRq12.setStyle("ScrollString");
    localdRq11.bb(localdRq12);
    localdRq12.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setAlign(ajb.dia);
    localcwP3.setSize(new Or(10, 100.0F));
    localcwP3.setXOffset(-11);
    localdRq12.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    dRq localdRq13 = localdRq12;
    Jg localJg7 = localdRq13.getAppearance();
    localJg7.setElementMap(localcpa);
    localdRq12.bb(localJg7);
    localJg7.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(30, 0, 35, 0));
    localJg7.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg7.rV();
    localdRq12.rV();
    bbp localbbp1 = new bbp();
    localbbp1.aJ();
    localbbp1.setElementMap(localcpa);
    localbbp1.setStyle("Encyclopedia");
    localbbp1.setExpandable(false);
    localbbp1.setHorizontalScrollBarBehaviour(dOf.mfK);
    localbbp1.setVerticalScrollBarBehaviour(dOf.mfJ);
    localbbp1.setPageJumpRatio(0.3F);
    localdRq11.bb(localbbp1);
    localbbp1.brn();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setSize(new Or(100.0F, 100.0F));
    localcwP4.setAlign(ajb.dhZ);
    localbbp1.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    bbp localbbp2 = localbbp1;
    Jg localJg8 = localbbp2.getAppearance();
    localJg8.setElementMap(localcpa);
    localbbp1.bb(localJg8);
    localJg8.brn();
    cuR localcuR4 = new cuR();
    localcuR4.aJ();
    localcuR4.setElementMap(localcpa);
    localcuR4.setInsets(new Insets(0, 10, 0, 0));
    localJg8.bb(localcuR4);
    localcuR4.brn();
    localcuR4.rV();
    bmv localbmv5 = bmv.checkOut();
    localbmv5.setElementMap(localcpa);
    localbmv5.setInsets(new Insets(17, 3, 20, 0));
    localJg8.bb(localbmv5);
    localbmv5.brn();
    localbmv5.rV();
    localJg8.rV();
    dRq localdRq14 = dRq.checkOut();
    localdRq14.setElementMap(localcpa);
    localdRq14.setStyle("tiledScroll");
    localdRq14.setExpandable(false);
    localbbp1.bb(localdRq14);
    localdRq14.brn();
    dRq localdRq15 = localdRq14;
    Jg localJg9 = localdRq15.getAppearance();
    localJg9.setElementMap(localcpa);
    localdRq14.bb(localJg9);
    localJg9.brn();
    cuR localcuR5 = new cuR();
    localcuR5.aJ();
    localcuR5.setElementMap(localcpa);
    localcuR5.setInsets(new Insets(5, 0, 20, 0));
    localJg9.bb(localcuR5);
    localcuR5.brn();
    localcuR5.rV();
    bmv localbmv6 = bmv.checkOut();
    localbmv6.setElementMap(localcpa);
    localbmv6.setInsets(new Insets(0, 10, 0, 15));
    localJg9.bb(localbmv6);
    localbmv6.brn();
    localbmv6.rV();
    localJg9.rV();
    czO localczO3 = new czO();
    localczO3.aJ();
    localczO3.setAdaptToContentSize(true);
    localdRq14.bb(localczO3);
    localczO3.brn();
    localczO3.rV();
    dRq localdRq16 = dRq.checkOut();
    localdRq16.setElementMap(localcpa);
    localdRq14.bb(localdRq16);
    localdRq16.brn();
    cwP localcwP5 = new cwP();
    localcwP5.aJ();
    localcwP5.setElementMap(localcpa);
    localcwP5.setAlign(ajb.dhZ);
    localcwP5.setSize(new Or(100.0F, 100.0F));
    localdRq16.bb(localcwP5);
    localcwP5.brn();
    localcwP5.rV();
    aId localaId4 = aId.checkOut();
    localaId4.setAlign(aFG.ech);
    localaId4.setHorizontal(false);
    localdRq16.bb(localaId4);
    localaId4.brn();
    localaId4.rV();
    dRq localdRq17 = dRq.checkOut();
    localdRq17.setElementMap(localcpa);
    localdRq17.setExpandable(false);
    localdRq17.setPrefSize(new Or(300, 200));
    localdRq16.bb(localdRq17);
    localdRq17.brn();
    czO localczO4 = new czO();
    localczO4.aJ();
    localczO4.setAdaptToContentSize(true);
    localdRq17.bb(localczO4);
    localczO4.brn();
    localczO4.rV();
    dRq localdRq18 = localdRq17;
    Jg localJg10 = localdRq18.getAppearance();
    localJg10.setElementMap(localcpa);
    localdRq17.bb(localJg10);
    localJg10.brn();
    cuR localcuR6 = new cuR();
    localcuR6.aJ();
    localcuR6.setElementMap(localcpa);
    localcuR6.setInsets(new Insets(0, 20, 0, 20));
    localJg10.bb(localcuR6);
    localcuR6.brn();
    localcuR6.rV();
    localJg10.rV();
    dRq localdRq19 = dRq.checkOut();
    localdRq19.setElementMap(localcpa);
    localdRq19.setStyle("AchievementUnlockedSplashScaled");
    localdRq19.setExpandable(false);
    localdRq19.setPrefSize(new Or(0, 70));
    localdRq17.bb(localdRq19);
    localdRq19.brn();
    cwP localcwP6 = new cwP();
    localcwP6.aJ();
    localcwP6.setElementMap(localcpa);
    localcwP6.setAlign(ajb.dif);
    localcwP6.setSize(new Or(100.0F, -2));
    localdRq19.bb(localcwP6);
    localcwP6.brn();
    localcwP6.rV();
    localdRq19.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setDisplaySize(new Or(83, 39));
    localczv1.setStyle("NationLeftDecorator");
    localdRq17.bb(localczv1);
    localczv1.brn();
    cwP localcwP7 = new cwP();
    localcwP7.aJ();
    localcwP7.setElementMap(localcpa);
    localcwP7.setAlign(ajb.did);
    localcwP7.setSize(new Or(83, 39));
    localcwP7.setXOffset(20);
    localcwP7.setYOffset(10);
    localczv1.bb(localcwP7);
    localcwP7.brn();
    localcwP7.rV();
    localczv1.rV();
    czv localczv2 = new czv();
    localczv2.aJ();
    localczv2.setElementMap(localcpa);
    localczv2.setDisplaySize(new Or(83, 39));
    localczv2.setStyle("NationRightDecorator");
    localdRq17.bb(localczv2);
    localczv2.brn();
    cwP localcwP8 = new cwP();
    localcwP8.aJ();
    localcwP8.setElementMap(localcpa);
    localcwP8.setAlign(ajb.dih);
    localcwP8.setSize(new Or(83, 39));
    localcwP8.setXOffset(-20);
    localcwP8.setYOffset(10);
    localczv2.bb(localcwP8);
    localcwP8.brn();
    localcwP8.rV();
    localczv2.rV();
    czv localczv3 = new czv();
    localczv3.aJ();
    localczv3.setElementMap(localcpa);
    localczv3.setNonBlocking(true);
    localczv3.setScaled(true);
    localczv3.setKeepAspectRatio(true);
    localdRq17.bb(localczv3);
    localczv3.brn();
    cwP localcwP9 = new cwP();
    localcwP9.aJ();
    localcwP9.setElementMap(localcpa);
    localcwP9.setAlign(ajb.dif);
    localcwP9.setSize(new Or(200, 200));
    localczv3.bb(localcwP9);
    localcwP9.brn();
    localcwP9.rV();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv3.bb(localaAR);
    localaAR.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setAttribute("texture");
    localNK2.setField("iconUrl");
    localNK2.setName("selectedBuilding");
    localaAR.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localaAR.rV();
    localczv3.rV();
    localdRq17.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setMultiline(true);
    localcWk1.setMinWidth(1);
    localcWk1.setMaxWidth(395);
    localcWk1.setStyle("styledBoldDark10");
    localcWk1.setExpandable(false);
    localdRq16.bb(localcWk1);
    localcWk1.brn();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setAttribute("text");
    localNK3.setField("description");
    localNK3.setName("selectedBuilding");
    localcWk1.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa);
    localdpm2.setAlign(aFG.ecj);
    localcWk1.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    cWk localcWk2 = localcWk1;
    Jg localJg11 = localcWk2.getAppearance();
    localJg11.setElementMap(localcpa);
    localcWk1.bb(localJg11);
    localJg11.brn();
    bmv localbmv7 = bmv.checkOut();
    localbmv7.setElementMap(localcpa);
    localbmv7.setInsets(new Insets(5, 15, 5, 15));
    localJg11.bb(localbmv7);
    localbmv7.brn();
    localbmv7.rV();
    localJg11.rV();
    localcWk1.rV();
    dRq localdRq20 = dRq.checkOut();
    localdRq20.setElementMap(localcpa);
    localdRq20.setExpandable(false);
    localdRq16.bb(localdRq20);
    localdRq20.brn();
    dRq localdRq21 = localdRq20;
    Jg localJg12 = localdRq21.getAppearance();
    localJg12.setElementMap(localcpa);
    localdRq20.bb(localJg12);
    localJg12.brn();
    bmv localbmv8 = bmv.checkOut();
    localbmv8.setElementMap(localcpa);
    localbmv8.setInsets(new Insets(10, 0, 5, 0));
    localJg12.bb(localbmv8);
    localbmv8.brn();
    localbmv8.rV();
    localJg12.rV();
    czO localczO5 = new czO();
    localczO5.aJ();
    localczO5.setAdaptToContentSize(true);
    localdRq20.bb(localczO5);
    localczO5.brn();
    localczO5.rV();
    czv localczv4 = new czv();
    localczv4.aJ();
    localczv4.setElementMap(localcpa);
    localczv4.setStyle("scrollTitleBar");
    localczv4.setPrefSize(new Or(423, 29));
    localdRq20.bb(localczv4);
    localczv4.brn();
    cwP localcwP10 = new cwP();
    localcwP10.aJ();
    localcwP10.setElementMap(localcpa);
    localcwP10.setAlign(ajb.dhZ);
    localcwP10.setSize(new Or(100.0F, 100.0F));
    localczv4.bb(localcwP10);
    localcwP10.brn();
    localcwP10.rV();
    localczv4.rV();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setStyle("StyledBold16White");
    localcaF3.setExpandable(false);
    String str2 = "%buildingDate%";
    str2 = str2.replace("%buildingDate%", cBQ.cxL().mL("buildingDate"));
    localcaF3.setText(str2);
    localdRq20.bb(localcaF3);
    localcaF3.brn();
    a(localcaF3);
    localcaF3.rV();
    localdRq20.rV();
    b(localdRq16);
    d(localdRq16);
    e(localdRq16);
    f(localdRq16);
    g(localdRq16);
    localdRq16.rV();
    h(localdRq14);
    localdRq14.rV();
    localbbp1.rV();
    i(localdRq11);
    localdRq11.rV();
    j(localdRq9);
    k(localdRq9);
    localdRq9.rV();
    localdRq7.rV();
    localdRq2.rV();
    l(localbpn);
    m(localbpn);
    n(localbpn);
    localbpn.rV();
    return localbpn;
  }

  public bdj a(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setAlign(ajb.dhZ);
    localcwP.setSize(new Or(100.0F, 100.0F));
    parambdj.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    return localcwP;
  }

  public bdj b(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setMultiline(true);
    localcWk1.setMinWidth(1);
    localcWk1.setMaxWidth(280);
    localcWk1.setStyle("darkTitle");
    localcWk1.setExpandable(false);
    parambdj.bb(localcWk1);
    localcWk1.brn();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setAttribute("text");
    localNK.setField("constructionDate");
    localNK.setName("selectedBuilding");
    localcWk1.bb(localNK);
    localNK.brn();
    localNK.rV();
    cWk localcWk2 = localcWk1;
    Jg localJg = localcWk2.getAppearance();
    localJg.setElementMap(localcpa);
    ((cwJ)localJg).setAlign(aFG.eck);
    localcWk1.bb(localJg);
    localJg.brn();
    localJg.rV();
    localcWk1.rV();
    return localcWk1;
  }

  public bdj d(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setAttribute("visible");
    localNK.setField("remainingTime");
    localNK.setName("selectedBuilding");
    localdRq1.bb(localNK);
    localNK.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localNK.bb(localanQ);
    localanQ.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localanQ.bb(localanE);
    localanE.brn();
    localanE.rV();
    localanQ.rV();
    localNK.rV();
    dRq localdRq2 = localdRq1;
    Jg localJg = localdRq2.getAppearance();
    localJg.setElementMap(localcpa);
    localdRq1.bb(localJg);
    localJg.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(10, 0, 5, 0));
    localJg.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg.rV();
    czO localczO = new czO();
    localczO.aJ();
    localczO.setAdaptToContentSize(true);
    localdRq1.bb(localczO);
    localczO.brn();
    localczO.rV();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setStyle("scrollTitleBar");
    localczv.setPrefSize(new Or(423, 29));
    localdRq1.bb(localczv);
    localczv.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setAlign(ajb.dhZ);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localczv.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    localczv.rV();
    caF localcaF = new caF();
    localcaF.aJ();
    localcaF.setElementMap(localcpa);
    localcaF.setStyle("StyledBold16White");
    localcaF.setExpandable(false);
    String str = "%havenWorld.buildingRemainingTime%";
    str = str.replace("%havenWorld.buildingRemainingTime%", cBQ.cxL().mL("havenWorld.buildingRemainingTime"));
    localcaF.setText(str);
    localdRq1.bb(localcaF);
    localcaF.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.dhZ);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localcaF.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    localcaF.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj e(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setMultiline(true);
    localcWk1.setMinWidth(1);
    localcWk1.setMaxWidth(280);
    localcWk1.setStyle("darkTitle");
    localcWk1.setExpandable(false);
    parambdj.bb(localcWk1);
    localcWk1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("visible");
    localNK1.setField("remainingTime");
    localNK1.setName("selectedBuilding");
    localcWk1.bb(localNK1);
    localNK1.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localNK1.bb(localanQ);
    localanQ.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localanQ.bb(localanE);
    localanE.brn();
    localanE.rV();
    localanQ.rV();
    localNK1.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setAttribute("text");
    localNK2.setField("remainingTime");
    localNK2.setName("selectedBuilding");
    localcWk1.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    cWk localcWk2 = localcWk1;
    Jg localJg = localcWk2.getAppearance();
    localJg.setElementMap(localcpa);
    ((cwJ)localJg).setAlign(aFG.eck);
    localcWk1.bb(localJg);
    localJg.brn();
    localJg.rV();
    localcWk1.rV();
    return localcWk1;
  }

  public bdj f(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setName("selectedBuilding");
    localNK.setAttribute("visible");
    localNK.setField("effects");
    localdRq1.bb(localNK);
    localNK.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localNK.bb(localanQ);
    localanQ.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localanQ.bb(localanE);
    localanE.brn();
    localanE.rV();
    localanQ.rV();
    localNK.rV();
    dRq localdRq2 = localdRq1;
    Jg localJg = localdRq2.getAppearance();
    localJg.setElementMap(localcpa);
    localdRq1.bb(localJg);
    localJg.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(10, 0, 5, 0));
    localJg.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg.rV();
    czO localczO = new czO();
    localczO.aJ();
    localczO.setAdaptToContentSize(true);
    localdRq1.bb(localczO);
    localczO.brn();
    localczO.rV();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setStyle("scrollTitleBar");
    localczv.setPrefSize(new Or(423, 29));
    localdRq1.bb(localczv);
    localczv.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setAlign(ajb.dhZ);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localczv.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    localczv.rV();
    caF localcaF = new caF();
    localcaF.aJ();
    localcaF.setElementMap(localcpa);
    localcaF.setStyle("StyledBold16White");
    localcaF.setExpandable(false);
    String str = "%buildingEffects%";
    str = str.replace("%buildingEffects%", cBQ.cxL().mL("buildingEffects"));
    localcaF.setText(str);
    localdRq1.bb(localcaF);
    localcaF.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.dhZ);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localcaF.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    localcaF.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj g(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    at localat1 = new at();
    localat1.aJ();
    localat1.setElementMap(localcpa);
    localat1.setHorizontal(false);
    localat1.setInnerExpandable(false);
    parambdj.bb(localat1);
    localat1.brn();
    at localat2 = localat1;
    Jg localJg1 = localat2.getAppearance();
    localJg1.setElementMap(localcpa);
    localat1.bb(localJg1);
    localJg1.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(0, 15, 0, 15));
    localJg1.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg1.rV();
    aId localaId = aId.checkOut();
    localaId.setAlign(aFG.ech);
    localaId.setHorizontal(false);
    localat1.bb(localaId);
    localaId.brn();
    localaId.rV();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setName("selectedBuilding");
    localNK1.setAttribute("visible");
    localNK1.setField("effects");
    localat1.bb(localNK1);
    localNK1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localNK1.bb(localanQ1);
    localanQ1.brn();
    anE localanE1 = new anE();
    localanE1.aJ();
    localanE1.setElementMap(localcpa);
    localanQ1.bb(localanE1);
    localanE1.brn();
    localanE1.rV();
    localanQ1.rV();
    localNK1.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("selectedBuilding");
    localNK2.setAttribute("content");
    localNK2.setField("effects");
    localat1.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    eR localeR1 = new eR();
    localeR1.aJ();
    localeR1.setElementMap(localcpa);
    localat1.bb(localeR1);
    localeR1.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localeR1.bb(localanQ2);
    localanQ2.brn();
    bJJ localbJJ1 = new bJJ();
    localbJJ1.aJ();
    localbJJ1.setElementMap(localcpa);
    localanQ2.bb(localbJJ1);
    localbJJ1.brn();
    bxx localbxx1 = new bxx();
    localbxx1.aJ();
    localbxx1.setElementMap(localcpa);
    localbJJ1.bb(localbxx1);
    localbxx1.brn();
    anE localanE2 = new anE();
    localanE2.aJ();
    localanE2.setElementMap(localcpa);
    localbxx1.bb(localanE2);
    localanE2.brn();
    localanE2.rV();
    localbxx1.rV();
    dlQ localdlQ1 = new dlQ();
    localdlQ1.aJ();
    localdlQ1.setElementMap(localcpa);
    localdlQ1.setKey("evenIndex");
    localbJJ1.bb(localdlQ1);
    localdlQ1.brn();
    cOk localcOk1 = new cOk();
    localcOk1.aJ();
    localcOk1.setElementMap(localcpa);
    localdlQ1.bb(localcOk1);
    localcOk1.brn();
    localcOk1.rV();
    localdlQ1.rV();
    localbJJ1.rV();
    localanQ2.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localeR1.bb(localdRq1);
    localdRq1.brn();
    dRq localdRq2 = localdRq1;
    Jg localJg2 = localdRq2.getAppearance();
    localJg2.setElementMap(localcpa);
    localdRq1.bb(localJg2);
    localJg2.brn();
    jO localjO = new jO();
    localjO.aJ();
    localjO.setElementMap(localcpa);
    localjO.setColor(new bNa(0.35F, 0.35F, 0.42F, 0.3F));
    localJg2.bb(localjO);
    localjO.brn();
    localjO.rV();
    ams localams = new ams();
    localams.aJ();
    localams.setElementMap(localcpa);
    localams.setColor(new bNa(0.35F, 0.35F, 0.42F, 0.8F));
    localams.setInsets(new Insets(1, 0, 1, 0));
    localJg2.bb(localams);
    localams.brn();
    localams.rV();
    localJg2.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("styledBoldDark10");
    localcWk1.setMultiline(true);
    localcWk1.setMinWidth(1);
    localcWk1.setMaxWidth(395);
    localcWk1.setExpandable(false);
    localdRq1.bb(localcWk1);
    localcWk1.brn();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("text");
    localcWk1.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    localcWk1.rV();
    localdRq1.rV();
    localeR1.rV();
    eR localeR2 = new eR();
    localeR2.aJ();
    localeR2.setElementMap(localcpa);
    localat1.bb(localeR2);
    localeR2.brn();
    anQ localanQ3 = new anQ();
    localanQ3.aJ();
    localanQ3.setElementMap(localcpa);
    localeR2.bb(localanQ3);
    localanQ3.brn();
    bJJ localbJJ2 = new bJJ();
    localbJJ2.aJ();
    localbJJ2.setElementMap(localcpa);
    localanQ3.bb(localbJJ2);
    localbJJ2.brn();
    bxx localbxx2 = new bxx();
    localbxx2.aJ();
    localbxx2.setElementMap(localcpa);
    localbJJ2.bb(localbxx2);
    localbxx2.brn();
    anE localanE3 = new anE();
    localanE3.aJ();
    localanE3.setElementMap(localcpa);
    localbxx2.bb(localanE3);
    localanE3.brn();
    localanE3.rV();
    localbxx2.rV();
    dlQ localdlQ2 = new dlQ();
    localdlQ2.aJ();
    localdlQ2.setElementMap(localcpa);
    localdlQ2.setKey("oddIndex");
    localbJJ2.bb(localdlQ2);
    localdlQ2.brn();
    cOk localcOk2 = new cOk();
    localcOk2.aJ();
    localcOk2.setElementMap(localcpa);
    localdlQ2.bb(localcOk2);
    localcOk2.brn();
    localcOk2.rV();
    localdlQ2.rV();
    localbJJ2.rV();
    localanQ3.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localeR2.bb(localdRq3);
    localdRq3.brn();
    cWk localcWk2 = new cWk();
    localcWk2.aJ();
    localcWk2.setElementMap(localcpa);
    localcWk2.setStyle("styledBoldDark10");
    localcWk2.setMultiline(true);
    localcWk2.setMinWidth(1);
    localcWk2.setMaxWidth(395);
    localcWk2.setExpandable(false);
    localdRq3.bb(localcWk2);
    localcWk2.brn();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("text");
    localcWk2.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    localcWk2.rV();
    localdRq3.rV();
    localeR2.rV();
    localat1.rV();
    return localat1;
  }

  public bdj h(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setAlign(ajb.dhV);
    localcwP1.setXOffset(-10);
    localcwP1.setYOffset(-10);
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    aId localaId = aId.checkOut();
    localaId.setAlign(aFG.ech);
    localaId.setHorizontal(false);
    localdRq1.bb(localaId);
    localaId.brn();
    localaId.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setExpandable(false);
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("visible");
    localNK1.setField("canBeEvolved");
    localNK1.setName("selectedBuilding");
    localdRq2.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    czO localczO1 = new czO();
    localczO1.aJ();
    localczO1.setAdaptToContentSize(true);
    localdRq2.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    biy localbiy1 = new biy();
    localbiy1.aJ();
    localbiy1.setElementMap(localcpa);
    localbiy1.setStyle("yellow");
    csA localcsA1 = new csA();
    localcsA1.hg("wakfu.havenWorld:evolveBuilding");
    localbiy1.setOnClick(localcsA1);
    cCu localcCu1 = new cCu();
    localcCu1.hg("popup(evolveBuildingButtonPopup)");
    localbiy1.setOnPopupDisplay(localcCu1);
    jL localjL1 = new jL();
    localjL1.hg("closePopup");
    localbiy1.setOnPopupHide(localjL1);
    localdRq2.bb(localbiy1);
    localbiy1.brn();
    String str1 = "evolveBuildingButtonPopup";
    anG localanG1 = new anG();
    localanG1.aJ();
    localanG1.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localanG1);
    localanG1.setAlign(aFG.ech);
    localanG1.setHotSpotPosition(aFG.ecn);
    localbiy1.bb(localanG1);
    localanG1.brn();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq3.setPrefSize(new Or(10, 0));
    localdRq3.setStyle("popup");
    localanG1.bb(localdRq3);
    localdRq3.brn();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("white");
    localcWk1.setEnableShrinking(false);
    String str2 = "%havenWorld.buildingEvolve%";
    str2 = str2.replace("%havenWorld.buildingEvolve%", cBQ.cxL().mL("havenWorld.buildingEvolve"));
    localcWk1.setText(str2);
    localdRq3.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg1 = localcWk2.getAppearance();
    localJg1.setElementMap(localcpa);
    ((cwJ)localJg1).setAlignment(aFG.eck);
    localcWk1.bb(localJg1);
    localJg1.brn();
    localJg1.rV();
    localcWk1.rV();
    localdRq3.rV();
    localanG1.rV();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.dhZ);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localbiy1.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    localbiy1.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setStyle("HavenWorldEvolution");
    localczv1.setNonBlocking(true);
    localczv1.setDisplaySize(new Or(32, 32));
    localdRq2.bb(localczv1);
    localczv1.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setAlign(ajb.dhZ);
    localczv1.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    czv localczv2 = localczv1;
    Jg localJg2 = localczv2.getAppearance();
    localJg2.setElementMap(localcpa);
    localczv1.bb(localJg2);
    localJg2.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(5, 5, 5, 5));
    localJg2.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg2.rV();
    localczv1.rV();
    localdRq2.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setExpandable(false);
    localdRq1.bb(localdRq4);
    localdRq4.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setAttribute("visible");
    localNK2.setField("canBeDestroyed");
    localNK2.setName("selectedBuilding");
    localdRq4.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    dRq localdRq5 = localdRq4;
    Jg localJg3 = localdRq5.getAppearance();
    localJg3.setElementMap(localcpa);
    localdRq4.bb(localJg3);
    localJg3.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(5, 0, 0, 0));
    localJg3.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg3.rV();
    czO localczO2 = new czO();
    localczO2.aJ();
    localczO2.setAdaptToContentSize(true);
    localdRq4.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    biy localbiy2 = new biy();
    localbiy2.aJ();
    localbiy2.setElementMap(localcpa);
    localbiy2.setStyle("yellow");
    csA localcsA2 = new csA();
    localcsA2.hg("wakfu.buildingPanel:deleteBuilding");
    localbiy2.setOnClick(localcsA2);
    cCu localcCu2 = new cCu();
    localcCu2.hg("popup(removeBuildingButtonPopup)");
    localbiy2.setOnPopupDisplay(localcCu2);
    jL localjL2 = new jL();
    localjL2.hg("closePopup");
    localbiy2.setOnPopupHide(localjL2);
    localdRq4.bb(localbiy2);
    localbiy2.brn();
    String str3 = "removeBuildingButtonPopup";
    anG localanG2 = new anG();
    localanG2.aJ();
    localanG2.setElementMap(localcpa);
    if ((localcpa != null) && (str3 != null))
      localcpa.a(str3, localanG2);
    localanG2.setAlign(aFG.ech);
    localanG2.setHotSpotPosition(aFG.ecn);
    localbiy2.bb(localanG2);
    localanG2.brn();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq6.setPrefSize(new Or(10, 0));
    localdRq6.setStyle("popup");
    localanG2.bb(localdRq6);
    localdRq6.brn();
    cWk localcWk3 = new cWk();
    localcWk3.aJ();
    localcWk3.setElementMap(localcpa);
    localcWk3.setStyle("white");
    localcWk3.setEnableShrinking(false);
    String str4 = "%havenWorld.destroyElement%";
    str4 = str4.replace("%havenWorld.destroyElement%", cBQ.cxL().mL("havenWorld.destroyElement"));
    localcWk3.setText(str4);
    localdRq6.bb(localcWk3);
    localcWk3.brn();
    cWk localcWk4 = localcWk3;
    Jg localJg4 = localcWk4.getAppearance();
    localJg4.setElementMap(localcpa);
    ((cwJ)localJg4).setAlignment(aFG.eck);
    localcWk3.bb(localJg4);
    localJg4.brn();
    localJg4.rV();
    localcWk3.rV();
    localdRq6.rV();
    localanG2.rV();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setAlign(ajb.dhZ);
    localcwP4.setSize(new Or(100.0F, 100.0F));
    localbiy2.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    localbiy2.rV();
    czv localczv3 = new czv();
    localczv3.aJ();
    localczv3.setElementMap(localcpa);
    localczv3.setStyle("HavenWorldDelete");
    localczv3.setNonBlocking(true);
    localczv3.setDisplaySize(new Or(32, 32));
    localdRq4.bb(localczv3);
    localczv3.brn();
    cwP localcwP5 = new cwP();
    localcwP5.aJ();
    localcwP5.setElementMap(localcpa);
    localcwP5.setAlign(ajb.dhZ);
    localczv3.bb(localcwP5);
    localcwP5.brn();
    localcwP5.rV();
    czv localczv4 = localczv3;
    Jg localJg5 = localczv4.getAppearance();
    localJg5.setElementMap(localcpa);
    localczv3.bb(localJg5);
    localJg5.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(5, 5, 5, 5));
    localJg5.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg5.rV();
    localczv3.rV();
    localdRq4.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj i(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq = dRq.checkOut();
    localdRq.setElementMap(localcpa);
    localdRq.setStyle("EncyclopediaPane");
    localdRq.setNonBlocking(true);
    parambdj.bb(localdRq);
    localdRq.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setAlign(ajb.dhT);
    localcwP.setSize(new Or(465, 100.0F));
    localcwP.setXOffset(-9);
    localcwP.setYOffset(1);
    localdRq.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localdRq.rV();
    return localdRq;
  }

  public bdj j(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("darkTitle");
    localcWk1.setExpandable(false);
    String str = "%havenWorld.buildingFrontChange%";
    str = str.replace("%havenWorld.buildingFrontChange%", cBQ.cxL().mL("havenWorld.buildingFrontChange"));
    localcWk1.setText(str);
    parambdj.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg = localcWk2.getAppearance();
    localJg.setElementMap(localcpa);
    ((cwJ)localJg).setAlignment(aFG.eck);
    localcWk1.bb(localJg);
    localJg.brn();
    localJg.rV();
    localcWk1.rV();
    return localcWk1;
  }

  public bdj k(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    czO localczO = new czO();
    localczO.aJ();
    localczO.setAdaptToContentSize(true);
    localdRq1.bb(localczO);
    localczO.brn();
    localczO.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setNonBlocking(true);
    localczv1.setStyle("FrontManualDecorator");
    localdRq1.bb(localczv1);
    localczv1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setAlign(ajb.dhZ);
    localcwP1.setXOffset(-50);
    localczv1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    localczv1.rV();
    String str1 = "frontSlot";
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localdRq2);
    localdRq2.setStyle("itemBackground");
    localdRq2.setPrefSize(new Or(55, 55));
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.dhZ);
    localdRq2.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    localdRq2.rV();
    axU localaxU = new axU();
    localaxU.aJ();
    localaxU.setElementMap(localcpa);
    localdRq1.bb(localaxU);
    localaxU.brn();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setAttribute("content");
    localNK.setName("selectedBuilding");
    localNK.setField("customItem");
    localaxU.bb(localNK);
    localNK.brn();
    localNK.rV();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setAlign(ajb.dhZ);
    localcwP3.setSize(new Or(55, 55));
    localaxU.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    eR localeR = new eR();
    localeR.aJ();
    localeR.setElementMap(localcpa);
    localaxU.bb(localeR);
    localeR.brn();
    bXx localbXx = new bXx();
    localbXx.aJ();
    localbXx.setElementMap(localcpa);
    bQa localbQa = new bQa();
    localbQa.hg("wakfu.buildingPanel:dropFrontManual");
    localbXx.setOnDrop(localbQa);
    dVA localdVA = new dVA();
    localdVA.hg("wakfu.buildingPanel:removeFrontManual");
    localbXx.setOnDrag(localdVA);
    localbXx.setNonBlocking(false);
    cCu localcCu = new cCu();
    localcCu.hg("popup(frontPopup)");
    localbXx.setOnPopupDisplay(localcCu);
    jL localjL = new jL();
    localjL.hg("closePopup");
    localbXx.setOnPopupHide(localjL);
    localeR.bb(localbXx);
    localbXx.brn();
    String str2 = "frontPopup";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localanG);
    localanG.setAlign(aFG.ech);
    localanG.setHotSpotPosition(aFG.ecn);
    localbXx.bb(localanG);
    localanG.brn();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq3.setStyle("popup");
    localanG.bb(localdRq3);
    localdRq3.brn();
    cba localcba = cba.checkOut();
    localcba.setElementMap(localcpa);
    localcba.setData(cFu.izR);
    localdRq3.bb(localcba);
    localcba.brn();
    localcba.rV();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(false);
    localdRq3.bb(localaId);
    localaId.brn();
    localaId.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("whiteBold");
    localcaF1.setExpandable(false);
    String str3 = "%frontManual%";
    str3 = str3.replace("%frontManual%", cBQ.cxL().mL("frontManual"));
    localcaF1.setText(str3);
    localdRq3.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg1 = localcaF2.getAppearance();
    localJg1.setElementMap(localcpa);
    ((cwJ)localJg1).setAlignment(aFG.ecj);
    localcaF1.bb(localJg1);
    localJg1.brn();
    localJg1.rV();
    localcaF1.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("PopupInformation");
    localcWk1.setExpandable(false);
    String str4 = "%desc.frontManual%";
    str4 = str4.replace("%desc.frontManual%", cBQ.cxL().mL("desc.frontManual"));
    localcWk1.setText(str4);
    localdRq3.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg2 = localcWk2.getAppearance();
    localJg2.setElementMap(localcpa);
    ((cwJ)localJg2).setAlignment(aFG.ecj);
    localcWk1.bb(localJg2);
    localJg2.brn();
    cAf localcAf = cAf.checkOut();
    localcAf.setElementMap(localcpa);
    localcAf.setColor(new bNa(0.8F, 0.8F, 0.8F, 0.8F));
    localJg2.bb(localcAf);
    localcAf.brn();
    localcAf.rV();
    localJg2.rV();
    localcWk1.rV();
    localdRq3.rV();
    localanG.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setNonBlocking(true);
    localbXx.bb(localdRq4);
    localdRq4.brn();
    czv localczv2 = new czv();
    localczv2.aJ();
    localczv2.setElementMap(localcpa);
    localczv2.setNonBlocking(true);
    localczv2.setDisplaySize(new Or(40, 40));
    localdRq4.bb(localczv2);
    localczv2.brn();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv2.bb(localaAR);
    localaAR.brn();
    aaE localaaE = new aaE();
    localaaE.aJ();
    localaaE.setElementMap(localcpa);
    localaaE.setAttribute("texture");
    localaaE.setField("iconUrl");
    localaAR.bb(localaaE);
    localaaE.brn();
    localaaE.rV();
    localaAR.rV();
    localczv2.rV();
    localdRq4.rV();
    localbXx.rV();
    localeR.rV();
    localaxU.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj l(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq = dRq.checkOut();
    localdRq.setElementMap(localcpa);
    parambdj.bb(localdRq);
    localdRq.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(100.0F, 100.0F));
    localdRq.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localdRq.rV();
    return localdRq;
  }

  public bdj m(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    biy localbiy = new biy();
    localbiy.aJ();
    localbiy.setElementMap(localcpa);
    localbiy.setStyle("close");
    localbiy.setExpandable(false);
    csA localcsA = new csA();
    localcsA.hg("unloadDialog");
    localbiy.setOnClick(localcsA);
    parambdj.bb(localbiy);
    localbiy.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(-2, -2));
    localcwP.setAlign(ajb.dhV);
    localcwP.setXOffset(-18);
    localcwP.setYOffset(-12);
    localbiy.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localbiy.rV();
    return localbiy;
  }

  public bdj n(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(-2, -2));
    localcwP.setAlign(ajb.dhZ);
    localcwP.setResizeOnce(true);
    parambdj.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    return localcwP;
  }
}