import java.awt.Insets;
import java.util.Stack;

public class cfT
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    String str1 = "governorMemberDetailWindow";
    bpn localbpn = new bpn();
    localbpn.aJ();
    localbpn.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localbpn);
    localbpn.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setInitValue(true);
    localcwP1.setSize(new Or(-2, -2));
    localcwP1.setAlign(ajb.dhV);
    localbpn.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    dqa localdqa = new dqa();
    localdqa.aJ();
    localdqa.setElementMap(localcpa);
    localbpn.bb(localdqa);
    localdqa.brn();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setStyle("challengeCurrent");
    localdRq1.setPrefSize(new Or(390, 0));
    localdqa.bb(localdRq1);
    localdRq1.brn();
    dRq localdRq2 = localdRq1;
    Jg localJg1 = localdRq2.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq1.bb(localJg1);
    localJg1.brn();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(5, 25, 25, 30));
    localJg1.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    localJg1.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localdRq1.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq3.setExpandable(false);
    localdRq1.bb(localdRq3);
    localdRq3.brn();
    czO localczO1 = new czO();
    localczO1.aJ();
    localczO1.setAdaptToContentSize(true);
    localdRq3.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq3.bb(localdRq4);
    localdRq4.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.dhZ);
    localcwP2.setSize(new Or(350, 100.0F));
    localdRq4.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    dRq localdRq5 = localdRq4;
    Jg localJg2 = localdRq5.getAppearance();
    localJg2.setElementMap(localcpa);
    localdRq4.bb(localJg2);
    localJg2.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 50, 0, 0));
    localJg2.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg2.rV();
    aId localaId2 = aId.checkOut();
    localaId2.setHorizontal(false);
    localaId2.setAlign(aFG.ech);
    localdRq4.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq6.setExpandable(false);
    localdRq4.bb(localdRq6);
    localdRq6.brn();
    czO localczO2 = new czO();
    localczO2.aJ();
    localczO2.setAdaptToContentSize(true);
    localdRq6.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localdRq7.setExpandable(false);
    localdRq6.bb(localdRq7);
    localdRq7.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setAlign(ajb.dhZ);
    localcwP3.setSize(new Or(100.0F, 100.0F));
    localcwP3.setYOffset(-5);
    localdRq7.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    dRq localdRq8 = localdRq7;
    Jg localJg3 = localdRq8.getAppearance();
    localJg3.setElementMap(localcpa);
    localdRq7.bb(localJg3);
    localJg3.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 0, 2, 0));
    localJg3.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(0, 9, 2, 9));
    localJg3.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    localJg3.rV();
    czO localczO3 = new czO();
    localczO3.aJ();
    localczO3.setAdaptToContentSize(true);
    localdRq7.bb(localczO3);
    localczO3.brn();
    localczO3.rV();
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa);
    localdRq9.setStyle("EncyclopediaSplashTitle");
    localdRq7.bb(localdRq9);
    localdRq9.brn();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setAlign(ajb.dhY);
    localcwP4.setSize(new Or(362, 38));
    localcwP4.setXOffset(-20);
    localdRq9.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    czO localczO4 = new czO();
    localczO4.aJ();
    localczO4.setAdaptToContentSize(true);
    localdRq9.bb(localczO4);
    localczO4.brn();
    localczO4.rV();
    dRq localdRq10 = localdRq9;
    Jg localJg4 = localdRq10.getAppearance();
    localJg4.setElementMap(localcpa);
    localdRq9.bb(localJg4);
    localJg4.brn();
    cuR localcuR3 = new cuR();
    localcuR3.aJ();
    localcuR3.setElementMap(localcpa);
    localcuR3.setInsets(new Insets(0, 25, 0, 0));
    localJg4.bb(localcuR3);
    localcuR3.brn();
    localcuR3.rV();
    localJg4.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("StyledBold16White");
    localcaF1.setNonBlocking(true);
    localcaF1.setExpandable(false);
    localdRq9.bb(localcaF1);
    localcaF1.brn();
    cwP localcwP5 = new cwP();
    localcwP5.aJ();
    localcwP5.setElementMap(localcpa);
    localcwP5.setAlign(ajb.dhY);
    localcaF1.bb(localcwP5);
    localcwP5.brn();
    localcwP5.rV();
    caF localcaF2 = localcaF1;
    Jg localJg5 = localcaF2.getAppearance();
    localJg5.setElementMap(localcpa);
    ((cwJ)localJg5).setAlignment(aFG.ecj);
    localcaF1.bb(localJg5);
    localJg5.brn();
    localJg5.rV();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setLocal(true);
    localNK1.setField("name");
    localNK1.setName("governmentMemberDetails");
    localNK1.setAttribute("text");
    localcaF1.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    localcaF1.rV();
    String str2 = "closeButton";
    biy localbiy1 = new biy();
    localbiy1.aJ();
    localbiy1.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localbiy1);
    localbiy1.setStyle("backgroundDisplayClose");
    csA localcsA = new csA();
    localcsA.hg("unloadDialog");
    localbiy1.setOnClick(localcsA);
    localdRq9.bb(localbiy1);
    localbiy1.brn();
    cwP localcwP6 = new cwP();
    localcwP6.aJ();
    localcwP6.setElementMap(localcpa);
    localcwP6.setAlign(ajb.dhV);
    localbiy1.bb(localcwP6);
    localcwP6.brn();
    localcwP6.rV();
    biy localbiy2 = localbiy1;
    Jg localJg6 = localbiy2.getAppearance();
    localJg6.setElementMap(localcpa);
    localbiy1.bb(localJg6);
    localJg6.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(5, 0, 0, 40));
    localJg6.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg6.rV();
    localbiy1.rV();
    localdRq9.rV();
    localdRq7.rV();
    localdRq6.rV();
    dRq localdRq11 = dRq.checkOut();
    localdRq11.setElementMap(localcpa);
    localdRq11.setExpandable(false);
    localdRq11.setNonBlocking(true);
    localdRq4.bb(localdRq11);
    localdRq11.brn();
    dRq localdRq12 = localdRq11;
    Jg localJg7 = localdRq12.getAppearance();
    localJg7.setElementMap(localcpa);
    localdRq11.bb(localJg7);
    localJg7.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(0, 15, 0, 0));
    localJg7.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg7.rV();
    czO localczO5 = new czO();
    localczO5.aJ();
    localczO5.setAdaptToContentSize(true);
    localdRq11.bb(localczO5);
    localczO5.brn();
    localczO5.rV();
    dRq localdRq13 = dRq.checkOut();
    localdRq13.setElementMap(localcpa);
    localdRq13.setStyle("TiledScrollCenter");
    localdRq13.setPrefSize(new Or(334, 30));
    localdRq13.setNonBlocking(true);
    localdRq11.bb(localdRq13);
    localdRq13.brn();
    cwP localcwP7 = new cwP();
    localcwP7.aJ();
    localcwP7.setElementMap(localcpa);
    localcwP7.setAlign(ajb.dhY);
    localdRq13.bb(localcwP7);
    localcwP7.brn();
    localcwP7.rV();
    localdRq13.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setStyle("TiledScrollTop");
    localczv1.setNonBlocking(true);
    localdRq11.bb(localczv1);
    localczv1.brn();
    cwP localcwP8 = new cwP();
    localcwP8.aJ();
    localcwP8.setElementMap(localcpa);
    localcwP8.setAlign(ajb.dhR);
    localczv1.bb(localcwP8);
    localcwP8.brn();
    localcwP8.rV();
    localczv1.rV();
    czv localczv2 = new czv();
    localczv2.aJ();
    localczv2.setElementMap(localcpa);
    localczv2.setStyle("TiledScrollBottom");
    localczv2.setNonBlocking(true);
    localdRq11.bb(localczv2);
    localczv2.brn();
    cwP localcwP9 = new cwP();
    localcwP9.aJ();
    localcwP9.setElementMap(localcpa);
    localcwP9.setAlign(ajb.did);
    localczv2.bb(localcwP9);
    localcwP9.brn();
    localcwP9.rV();
    localczv2.rV();
    dRq localdRq14 = dRq.checkOut();
    localdRq14.setElementMap(localcpa);
    localdRq14.setNonBlocking(true);
    localdRq11.bb(localdRq14);
    localdRq14.brn();
    cwP localcwP10 = new cwP();
    localcwP10.aJ();
    localcwP10.setElementMap(localcpa);
    localcwP10.setAlign(ajb.dia);
    localcwP10.setSize(new Or(100.0F, 100.0F));
    localdRq14.bb(localcwP10);
    localcwP10.brn();
    localcwP10.rV();
    aId localaId3 = aId.checkOut();
    localaId3.setAlign(aFG.ecj);
    localdRq14.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setStyle("blackBold");
    localcaF3.setExpandable(false);
    String str3 = "%nation.rank%%colon%";
    str3 = str3.replace("%nation.rank%", cBQ.cxL().mL("nation.rank"));
    str3 = str3.replace("%colon%", cBQ.cxL().mL("colon"));
    localcaF3.setText(str3);
    localcaF3.setNonBlocking(true);
    localdRq14.bb(localcaF3);
    localcaF3.brn();
    localcaF3.rV();
    cWk localcWk = new cWk();
    localcWk.aJ();
    localcWk.setElementMap(localcpa);
    localcWk.setStyle("DefaultDarkBold14");
    localcWk.setExpandable(false);
    localcWk.setNonBlocking(true);
    localdRq14.bb(localcWk);
    localcWk.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setLocal(true);
    localNK2.setAttribute("text");
    localNK2.setName("governmentMemberDetails");
    localNK2.setField("rankDescription");
    localcWk.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localcWk.rV();
    dAS localdAS = new dAS();
    localdAS.aJ();
    localdAS.setElementMap(localcpa);
    localdAS.setNonBlocking(true);
    localdRq14.bb(localdAS);
    localdAS.brn();
    localdAS.rV();
    czv localczv3 = new czv();
    localczv3.aJ();
    localczv3.setElementMap(localcpa);
    localczv3.setExpandable(false);
    localczv3.setNonBlocking(true);
    localdRq14.bb(localczv3);
    localczv3.brn();
    cwP localcwP11 = new cwP();
    localcwP11.aJ();
    localcwP11.setElementMap(localcpa);
    localcwP11.setAlign(ajb.dia);
    localczv3.bb(localcwP11);
    localcwP11.brn();
    localcwP11.rV();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setLocal(true);
    localNK3.setName("governmentMemberDetails");
    localNK3.setAttribute("style");
    localNK3.setField("wakfuValue");
    localczv3.bb(localNK3);
    localNK3.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localanQ.setValue("StasisIcon");
    localanQ.setElseValue("WakfuIcon");
    localNK3.bb(localanQ);
    localanQ.brn();
    asH localasH = new asH();
    localasH.aJ();
    localasH.setElementMap(localcpa);
    localasH.setValue("0");
    localanQ.bb(localasH);
    localasH.brn();
    localasH.rV();
    localanQ.rV();
    localNK3.rV();
    czv localczv4 = localczv3;
    Jg localJg8 = localczv4.getAppearance();
    localJg8.setElementMap(localcpa);
    localczv3.bb(localJg8);
    localJg8.brn();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa);
    localNK4.setLocal(true);
    localNK4.setName("governmentMemberDetails");
    localNK4.setAttribute("modulationColor");
    localNK4.setField("wakfuStasisColor");
    localJg8.bb(localNK4);
    localNK4.brn();
    localNK4.rV();
    localJg8.rV();
    localczv3.rV();
    caF localcaF4 = new caF();
    localcaF4.aJ();
    localcaF4.setElementMap(localcpa);
    localcaF4.setStyle("darkBold");
    localcaF4.setExpandable(false);
    localcaF4.setNonBlocking(true);
    localdRq14.bb(localcaF4);
    localcaF4.brn();
    NK localNK5 = NK.checkOut();
    localNK5.setElementMap(localcpa);
    localNK5.setLocal(true);
    localNK5.setName("governmentMemberDetails");
    localNK5.setAttribute("text");
    localNK5.setField("wakfuStasisDescription");
    localcaF4.bb(localNK5);
    localNK5.brn();
    localNK5.rV();
    localcaF4.rV();
    localdRq14.rV();
    localdRq11.rV();
    dRq localdRq15 = dRq.checkOut();
    localdRq15.setElementMap(localcpa);
    localdRq15.setExpandable(false);
    localdRq4.bb(localdRq15);
    localdRq15.brn();
    dRq localdRq16 = localdRq15;
    Jg localJg9 = localdRq16.getAppearance();
    localJg9.setElementMap(localcpa);
    localdRq15.bb(localJg9);
    localJg9.brn();
    bmv localbmv5 = bmv.checkOut();
    localbmv5.setElementMap(localcpa);
    localbmv5.setInsets(new Insets(0, 15, 0, 0));
    localJg9.bb(localbmv5);
    localbmv5.brn();
    localbmv5.rV();
    localJg9.rV();
    czO localczO6 = new czO();
    localczO6.aJ();
    localczO6.setAdaptToContentSize(true);
    localdRq15.bb(localczO6);
    localczO6.brn();
    localczO6.rV();
    dRq localdRq17 = dRq.checkOut();
    localdRq17.setElementMap(localcpa);
    localdRq17.setStyle("TiledScrollCenter");
    localdRq17.setPrefSize(new Or(334, 30));
    localdRq17.setNonBlocking(true);
    localdRq15.bb(localdRq17);
    localdRq17.brn();
    cwP localcwP12 = new cwP();
    localcwP12.aJ();
    localcwP12.setElementMap(localcpa);
    localcwP12.setAlign(ajb.dhY);
    localdRq17.bb(localcwP12);
    localcwP12.brn();
    localcwP12.rV();
    localdRq17.rV();
    czv localczv5 = new czv();
    localczv5.aJ();
    localczv5.setElementMap(localcpa);
    localczv5.setStyle("TiledScrollTop");
    localczv5.setNonBlocking(true);
    localdRq15.bb(localczv5);
    localczv5.brn();
    cwP localcwP13 = new cwP();
    localcwP13.aJ();
    localcwP13.setElementMap(localcpa);
    localcwP13.setAlign(ajb.dhR);
    localczv5.bb(localcwP13);
    localcwP13.brn();
    localcwP13.rV();
    localczv5.rV();
    czv localczv6 = new czv();
    localczv6.aJ();
    localczv6.setElementMap(localcpa);
    localczv6.setStyle("TiledScrollBottom");
    localczv6.setNonBlocking(true);
    localdRq15.bb(localczv6);
    localczv6.brn();
    cwP localcwP14 = new cwP();
    localcwP14.aJ();
    localcwP14.setElementMap(localcpa);
    localcwP14.setAlign(ajb.did);
    localczv6.bb(localcwP14);
    localcwP14.brn();
    localcwP14.rV();
    localczv6.rV();
    a(localdRq15);
    localdRq15.rV();
    localdRq4.rV();
    b(localdRq3);
    localdRq3.rV();
    localdRq1.rV();
    localdqa.rV();
    localbpn.rV();
    return localbpn;
  }

  public bdj a(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq = dRq.checkOut();
    localdRq.setElementMap(localcpa);
    parambdj.bb(localdRq);
    localdRq.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setAlign(ajb.dia);
    localcwP.setSize(new Or(100.0F, 100.0F));
    localdRq.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    aId localaId = aId.checkOut();
    localaId.setAlign(aFG.ecj);
    localdRq.bb(localaId);
    localaId.brn();
    localaId.rV();
    caF localcaF = new caF();
    localcaF.aJ();
    localcaF.setElementMap(localcpa);
    localcaF.setStyle("blackBold");
    localcaF.setExpandable(false);
    String str = "%desc.guild%%colon%";
    str = str.replace("%desc.guild%", cBQ.cxL().mL("desc.guild"));
    str = str.replace("%colon%", cBQ.cxL().mL("colon"));
    localcaF.setText(str);
    localcaF.setNonBlocking(true);
    localdRq.bb(localcaF);
    localcaF.brn();
    localcaF.rV();
    cWk localcWk = new cWk();
    localcWk.aJ();
    localcWk.setElementMap(localcpa);
    localcWk.setStyle("DefaultDarkBold14");
    localcWk.setExpandable(false);
    localcWk.setNonBlocking(true);
    localdRq.bb(localcWk);
    localcWk.brn();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setLocal(true);
    localNK.setAttribute("text");
    localNK.setName("governmentMemberDetails");
    localNK.setField("guildName");
    localcWk.bb(localNK);
    localNK.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localanQ.setElseValue("-");
    localanQ.setReturnOriginalValue(true);
    localNK.bb(localanQ);
    localanQ.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localanQ.bb(localanE);
    localanE.brn();
    localanE.rV();
    localanQ.rV();
    localNK.rV();
    localcWk.rV();
    localdRq.rV();
    return localdRq;
  }

  public bdj b(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setAlign(ajb.dhY);
    localcwP1.setSize(new Or(-2, 100.0F));
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    czO localczO1 = new czO();
    localczO1.aJ();
    localczO1.setAdaptToContentSize(true);
    localdRq1.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.dhT);
    localdRq2.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    czO localczO2 = new czO();
    localczO2.aJ();
    localczO2.setAdaptToContentSize(true);
    localdRq2.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setStyle("Portrait");
    localczv.setNonBlocking(true);
    localdRq2.bb(localczv);
    localczv.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setAlign(ajb.dhZ);
    localcwP3.setSize(new Or(87, 102));
    localczv.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    localczv.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq3.setNeedsScissor(true);
    localdRq2.bb(localdRq3);
    localdRq3.brn();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setAlign(ajb.dhZ);
    localcwP4.setSize(new Or(55, 68));
    localcwP4.setXOffset(-1);
    localdRq3.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    auC localauC = new auC();
    localauC.aJ();
    localauC.setElementMap(localcpa);
    localauC.setOffsetY(-125.0F);
    localauC.setOffsetX(0.0F);
    localauC.setScale(2.2F);
    localauC.setAnimName("AnimStatique");
    localauC.setDirection(2);
    localauC.setNonBlocking(true);
    localdRq3.bb(localauC);
    localauC.brn();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setLocal(true);
    localNK.setField("actorDescriptorLibrary");
    localNK.setName("governmentMemberDetails");
    localNK.setAttribute("animatedElement");
    localauC.bb(localNK);
    localNK.brn();
    localNK.rV();
    localauC.rV();
    localdRq3.rV();
    localdRq2.rV();
    localdRq1.rV();
    return localdRq1;
  }
}