import java.util.Stack;

public class bdF
  implements aTK
{
  private uk W;
  private Stack X = new Stack();

  public void a(cpa paramcpa, uk paramuk, dOc paramdOc)
  {
    this.W = paramuk;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    dOc localdOc = paramdOc;
    Jg localJg = localdOc.getAppearance();
    localJg.setElementMap(localcpa);
    paramdOc.bb(localJg);
    localJg.brn();
    String str = "rollOverContainer";
    aen localaen = aen.checkOut();
    localaen.setElementMap(localcpa);
    if ((localcpa != null) && (str != null))
      localcpa.a(str, localaen);
    localaen.setScaled(true);
    localJg.bb(localaen);
    localaen.brn();
    aAR localaAR1 = aAR.checkOut();
    localaAR1.setElementMap(localcpa);
    localaAR1.setPosition(ajb.dhR);
    localaAR1.setX(283);
    localaAR1.setY(238);
    localaAR1.setWidth(36);
    localaAR1.setHeight(34);
    localaAR1.setTexture(this.W.aH("preWorld_0.tga"));
    localaen.bb(localaAR1);
    localaAR1.brn();
    localaAR1.rV();
    aAR localaAR2 = aAR.checkOut();
    localaAR2.setElementMap(localcpa);
    localaAR2.setPosition(ajb.dhT);
    localaAR2.setX(283);
    localaAR2.setY(201);
    localaAR2.setWidth(24);
    localaAR2.setHeight(34);
    localaAR2.setTexture(this.W.aH("preWorld_0.tga"));
    localaen.bb(localaAR2);
    localaAR2.brn();
    localaAR2.rV();
    aAR localaAR3 = aAR.checkOut();
    localaAR3.setElementMap(localcpa);
    localaAR3.setPosition(ajb.dhV);
    localaAR3.setX(283);
    localaAR3.setY(275);
    localaAR3.setWidth(36);
    localaAR3.setHeight(34);
    localaAR3.setTexture(this.W.aH("preWorld_0.tga"));
    localaen.bb(localaAR3);
    localaAR3.brn();
    localaAR3.rV();
    aAR localaAR4 = aAR.checkOut();
    localaAR4.setElementMap(localcpa);
    localaAR4.setPosition(ajb.dia);
    localaAR4.setX(43);
    localaAR4.setY(38);
    localaAR4.setWidth(36);
    localaAR4.setHeight(12);
    localaAR4.setTexture(this.W.aH("preWorld_0.tga"));
    localaen.bb(localaAR4);
    localaAR4.brn();
    localaAR4.rV();
    aAR localaAR5 = aAR.checkOut();
    localaAR5.setElementMap(localcpa);
    localaAR5.setPosition(ajb.dih);
    localaAR5.setX(673);
    localaAR5.setY(238);
    localaAR5.setWidth(36);
    localaAR5.setHeight(34);
    localaAR5.setTexture(this.W.aH("preWorld_0.tga"));
    localaen.bb(localaAR5);
    localaAR5.brn();
    localaAR5.rV();
    aAR localaAR6 = aAR.checkOut();
    localaAR6.setElementMap(localcpa);
    localaAR6.setPosition(ajb.dif);
    localaAR6.setX(213);
    localaAR6.setY(206);
    localaAR6.setWidth(24);
    localaAR6.setHeight(34);
    localaAR6.setTexture(this.W.aH("preWorld_0.tga"));
    localaen.bb(localaAR6);
    localaAR6.brn();
    localaAR6.rV();
    aAR localaAR7 = aAR.checkOut();
    localaAR7.setElementMap(localcpa);
    localaAR7.setPosition(ajb.did);
    localaAR7.setX(983);
    localaAR7.setY(914);
    localaAR7.setWidth(36);
    localaAR7.setHeight(34);
    localaAR7.setTexture(this.W.aH("preWorld_0.tga"));
    localaen.bb(localaAR7);
    localaAR7.brn();
    localaAR7.rV();
    aAR localaAR8 = aAR.checkOut();
    localaAR8.setElementMap(localcpa);
    localaAR8.setPosition(ajb.dhY);
    localaAR8.setX(82);
    localaAR8.setY(38);
    localaAR8.setWidth(36);
    localaAR8.setHeight(12);
    localaAR8.setTexture(this.W.aH("preWorld_0.tga"));
    localaen.bb(localaAR8);
    localaAR8.brn();
    localaAR8.rV();
    aAR localaAR9 = aAR.checkOut();
    localaAR9.setElementMap(localcpa);
    localaAR9.setPosition(ajb.dhZ);
    localaAR9.setX(990);
    localaAR9.setY(149);
    localaAR9.setWidth(25);
    localaAR9.setHeight(17);
    localaAR9.setTexture(this.W.aH("preWorld_0.tga"));
    localaen.bb(localaAR9);
    localaAR9.brn();
    localaAR9.rV();
    localaen.rV();
    localJg.rV();
  }
}