import java.awt.Insets;
import java.util.Stack;

public class VB
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    String str1 = "stateBarWindow";
    bpn localbpn = new bpn();
    localbpn.aJ();
    localbpn.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localbpn);
    localbpn.setNonBlocking(true);
    aFU localaFU = new aFU();
    localaFU.hg("wakfu.windowStick:stickStateBar");
    localbpn.setOnStick(localaFU);
    localbpn.setPack(true);
    localbpn.brn();
    String str2 = "statePopup";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localanG);
    localanG.setAlign(aFG.ech);
    localanG.setHotSpotPosition(aFG.ecn);
    localbpn.bb(localanG);
    localanG.brn();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setPrefSize(new Or(10, 0));
    localdRq1.setStyle("popup");
    localanG.bb(localdRq1);
    localdRq1.brn();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localaId1.setAlign(aFG.ech);
    localdRq1.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setPrefSize(new Or(150, 0));
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(3, 3, 3, 3));
    localJg1.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    localJg1.rV();
    aId localaId2 = aId.checkOut();
    localaId2.setHorizontal(false);
    localdRq2.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq2.bb(localdRq4);
    localdRq4.brn();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setExpandable(false);
    localczv.setScaled(true);
    localczv.setDisplaySize(new Or(48, 48));
    localczv.setNonBlocking(true);
    localdRq4.bb(localczv);
    localczv.brn();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.ech);
    localczv.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv.bb(localaAR);
    localaAR.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setName("describedRunningEffect");
    localNK1.setLocal(true);
    localNK1.setField("iconUrl");
    localNK1.setAttribute("texture");
    localaAR.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    localaAR.rV();
    localczv.rV();
    dRq localdRq5 = dRq.checkOut();
    localdRq5.setElementMap(localcpa);
    localdRq4.bb(localdRq5);
    localdRq5.brn();
    dRq localdRq6 = localdRq5;
    Jg localJg2 = localdRq6.getAppearance();
    localJg2.setElementMap(localcpa);
    localdRq5.bb(localJg2);
    localJg2.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 3, 0, 0));
    localJg2.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg2.rV();
    aId localaId3 = aId.checkOut();
    localaId3.setAlign(aFG.ech);
    localaId3.setHorizontal(false);
    localdRq5.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localdRq7.setStyle("smallDarkBackground");
    localdRq7.setPrefSize(new Or(0, 20));
    localdRq7.setExpandable(false);
    localdRq5.bb(localdRq7);
    localdRq7.brn();
    dRq localdRq8 = localdRq7;
    Jg localJg3 = localdRq8.getAppearance();
    localJg3.setElementMap(localcpa);
    localdRq7.bb(localJg3);
    localJg3.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(2, 0, 2, 0));
    localJg3.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg3.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("whiteBold11");
    localcWk1.setNonBlocking(true);
    localdRq7.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg4 = localcWk2.getAppearance();
    localJg4.setElementMap(localcpa);
    ((cwJ)localJg4).setAlign(aFG.ecj);
    localcWk1.bb(localJg4);
    localJg4.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 5, 0, 5));
    localJg4.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg4.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("describedRunningEffect");
    localNK2.setLocal(true);
    localNK2.setAttribute("text");
    localNK2.setField("nameAndLevel");
    localcWk1.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localcWk1.rV();
    localdRq7.rV();
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa);
    localdRq9.setExpandable(false);
    localdRq9.setPrefSize(new Or(0, 20));
    localdRq9.setStyle("smallDarkBackground");
    localdRq5.bb(localdRq9);
    localdRq9.brn();
    dRq localdRq10 = localdRq9;
    Jg localJg5 = localdRq10.getAppearance();
    localJg5.setElementMap(localcpa);
    localdRq9.bb(localJg5);
    localJg5.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(2, 0, 2, 0));
    localJg5.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(0, 5, 0, 5));
    localJg5.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    localJg5.rV();
    aId localaId4 = aId.checkOut();
    localaId4.setAlign(aFG.ecj);
    localdRq9.bb(localaId4);
    localaId4.brn();
    localaId4.rV();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setName("describedRunningEffect");
    localNK3.setLocal(true);
    localNK3.setAttribute("visible");
    localNK3.setField("remainingDurationText");
    localdRq9.bb(localNK3);
    localNK3.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localNK3.bb(localanQ1);
    localanQ1.brn();
    anE localanE1 = new anE();
    localanE1.aJ();
    localanE1.setElementMap(localcpa);
    localanQ1.bb(localanE1);
    localanE1.brn();
    localanE1.rV();
    localanQ1.rV();
    localNK3.rV();
    caF localcaF = new caF();
    localcaF.aJ();
    localcaF.setElementMap(localcpa);
    localcaF.setExpandable(false);
    localcaF.setStyle("whiteBold");
    String str3 = "%duration% ";
    str3 = str3.replace("%duration%", cBQ.cxL().mL("duration"));
    localcaF.setText(str3);
    localcaF.setNonBlocking(true);
    localdRq9.bb(localcaF);
    localcaF.brn();
    localcaF.rV();
    cWk localcWk3 = new cWk();
    localcWk3.aJ();
    localcWk3.setElementMap(localcpa);
    localcWk3.setStyle("white");
    localcWk3.setNonBlocking(true);
    localdRq9.bb(localcWk3);
    localcWk3.brn();
    cWk localcWk4 = localcWk3;
    Jg localJg6 = localcWk4.getAppearance();
    localJg6.setElementMap(localcpa);
    ((cwJ)localJg6).setAlign(aFG.ecj);
    localcWk3.bb(localJg6);
    localJg6.brn();
    localJg6.rV();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa);
    localNK4.setName("describedRunningEffect");
    localNK4.setLocal(true);
    localNK4.setAttribute("text");
    localNK4.setField("remainingDurationText");
    localcWk3.bb(localNK4);
    localNK4.brn();
    localNK4.rV();
    NK localNK5 = NK.checkOut();
    localNK5.setElementMap(localcpa);
    localNK5.setName("describedRunningEffect");
    localNK5.setLocal(true);
    localNK5.setAttribute("visible");
    localNK5.setField("remainingDurationText");
    localcWk3.bb(localNK5);
    localNK5.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localNK5.bb(localanQ2);
    localanQ2.brn();
    anE localanE2 = new anE();
    localanE2.aJ();
    localanE2.setElementMap(localcpa);
    localanQ2.bb(localanE2);
    localanE2.brn();
    localanE2.rV();
    localanQ2.rV();
    localNK5.rV();
    localcWk3.rV();
    localdRq9.rV();
    localdRq5.rV();
    localdRq4.rV();
    dRq localdRq11 = dRq.checkOut();
    localdRq11.setElementMap(localcpa);
    localdRq11.setStyle("smallDarkBackground");
    localdRq11.setPrefSize(new Or(0, 20));
    localdRq11.setExpandable(false);
    localdRq2.bb(localdRq11);
    localdRq11.brn();
    NK localNK6 = NK.checkOut();
    localNK6.setElementMap(localcpa);
    localNK6.setName("isInFight");
    localNK6.setAttribute("visible");
    localdRq11.bb(localNK6);
    localNK6.brn();
    anQ localanQ3 = new anQ();
    localanQ3.aJ();
    localanQ3.setElementMap(localcpa);
    localNK6.bb(localanQ3);
    localanQ3.brn();
    bJJ localbJJ = new bJJ();
    localbJJ.aJ();
    localbJJ.setElementMap(localcpa);
    localanQ3.bb(localbJJ);
    localbJJ.brn();
    bqW localbqW = new bqW();
    localbqW.aJ();
    localbqW.setElementMap(localcpa);
    localbJJ.bb(localbqW);
    localbqW.brn();
    localbqW.rV();
    cOk localcOk = new cOk();
    localcOk.aJ();
    localcOk.setElementMap(localcpa);
    localbJJ.bb(localcOk);
    localcOk.brn();
    NK localNK7 = NK.checkOut();
    localNK7.setElementMap(localcpa);
    localNK7.setName("describedRunningEffect");
    localNK7.setLocal(true);
    localNK7.setAttribute("comparedValue");
    localNK7.setField("description");
    localcOk.bb(localNK7);
    localNK7.brn();
    anQ localanQ4 = new anQ();
    localanQ4.aJ();
    localanQ4.setElementMap(localcpa);
    localNK7.bb(localanQ4);
    localanQ4.brn();
    anE localanE3 = new anE();
    localanE3.aJ();
    localanE3.setElementMap(localcpa);
    localanQ4.bb(localanE3);
    localanE3.brn();
    localanE3.rV();
    localanQ4.rV();
    localNK7.rV();
    localcOk.rV();
    localbJJ.rV();
    localanQ3.rV();
    localNK6.rV();
    dRq localdRq12 = localdRq11;
    Jg localJg7 = localdRq12.getAppearance();
    localJg7.setElementMap(localcpa);
    localdRq11.bb(localJg7);
    localJg7.brn();
    bmv localbmv5 = bmv.checkOut();
    localbmv5.setElementMap(localcpa);
    localbmv5.setInsets(new Insets(2, 0, 2, 0));
    localJg7.bb(localbmv5);
    localbmv5.brn();
    localbmv5.rV();
    cuR localcuR3 = new cuR();
    localcuR3.aJ();
    localcuR3.setElementMap(localcpa);
    localcuR3.setInsets(new Insets(5, 5, 5, 5));
    localJg7.bb(localcuR3);
    localcuR3.brn();
    localcuR3.rV();
    localJg7.rV();
    cWk localcWk5 = new cWk();
    localcWk5.aJ();
    localcWk5.setElementMap(localcpa);
    localcWk5.setStyle("narrow12");
    localcWk5.setNonBlocking(true);
    localcWk5.setMinWidth(1);
    localcWk5.setMaxWidth(230);
    localdRq11.bb(localcWk5);
    localcWk5.brn();
    cWk localcWk6 = localcWk5;
    Jg localJg8 = localcWk6.getAppearance();
    localJg8.setElementMap(localcpa);
    ((cwJ)localJg8).setAlign(aFG.ecj);
    localcWk5.bb(localJg8);
    localJg8.brn();
    cAf localcAf = cAf.checkOut();
    localcAf.setElementMap(localcpa);
    localcAf.setColor(new bNa(0.98F, 0.77F, 0.0F, 1.0F));
    localJg8.bb(localcAf);
    localcAf.brn();
    localcAf.rV();
    localJg8.rV();
    NK localNK8 = NK.checkOut();
    localNK8.setElementMap(localcpa);
    localNK8.setName("describedRunningEffect");
    localNK8.setLocal(true);
    localNK8.setAttribute("text");
    localNK8.setField("description");
    localcWk5.bb(localNK8);
    localNK8.brn();
    localNK8.rV();
    localcWk5.rV();
    localdRq11.rV();
    dRq localdRq13 = dRq.checkOut();
    localdRq13.setElementMap(localcpa);
    localdRq13.setExpandable(false);
    localdRq13.setStyle("smallDarkBackground");
    localdRq2.bb(localdRq13);
    localdRq13.brn();
    NK localNK9 = NK.checkOut();
    localNK9.setElementMap(localcpa);
    localNK9.setName("describedRunningEffect");
    localNK9.setLocal(true);
    localNK9.setAttribute("visible");
    localNK9.setField("effects");
    localdRq13.bb(localNK9);
    localNK9.brn();
    anQ localanQ5 = new anQ();
    localanQ5.aJ();
    localanQ5.setElementMap(localcpa);
    localNK9.bb(localanQ5);
    localanQ5.brn();
    anE localanE4 = new anE();
    localanE4.aJ();
    localanE4.setElementMap(localcpa);
    localanQ5.bb(localanE4);
    localanE4.brn();
    localanE4.rV();
    localanQ5.rV();
    localNK9.rV();
    dRq localdRq14 = localdRq13;
    Jg localJg9 = localdRq14.getAppearance();
    localJg9.setElementMap(localcpa);
    localdRq13.bb(localJg9);
    localJg9.brn();
    bmv localbmv6 = bmv.checkOut();
    localbmv6.setElementMap(localcpa);
    localbmv6.setInsets(new Insets(2, 0, 2, 0));
    localJg9.bb(localbmv6);
    localbmv6.brn();
    localbmv6.rV();
    cuR localcuR4 = new cuR();
    localcuR4.aJ();
    localcuR4.setElementMap(localcpa);
    localcuR4.setInsets(new Insets(5, 5, 5, 5));
    localJg9.bb(localcuR4);
    localcuR4.brn();
    localcuR4.rV();
    localJg9.rV();
    cWk localcWk7 = new cWk();
    localcWk7.aJ();
    localcWk7.setElementMap(localcpa);
    localcWk7.setStyle("white11");
    localcWk7.setMinWidth(1);
    localcWk7.setMaxWidth(230);
    localcWk7.setEnableOnlySelectablePartInteraction(true);
    csA localcsA = new csA();
    localcsA.hg("wakfu.spellDetails:processText(container,stateDetailPopup)");
    localcWk7.setOnClick(localcsA);
    bDy localbDy = new bDy();
    localbDy.hg("wakfu.spellDetails:processText(container,stateDetailPopup)");
    localcWk7.setOnMouseEnter(localbDy);
    DY localDY = new DY();
    localDY.hg("xulor:closePopup");
    localcWk7.setOnMouseExit(localDY);
    localdRq13.bb(localcWk7);
    localcWk7.brn();
    NK localNK10 = NK.checkOut();
    localNK10.setElementMap(localcpa);
    localNK10.setName("describedRunningEffect");
    localNK10.setLocal(true);
    localNK10.setAttribute("text");
    localNK10.setField("effects");
    localcWk7.bb(localNK10);
    localNK10.brn();
    localNK10.rV();
    cWk localcWk8 = localcWk7;
    Jg localJg10 = localcWk8.getAppearance();
    localJg10.setElementMap(localcpa);
    localcWk7.bb(localJg10);
    localJg10.brn();
    bmv localbmv7 = bmv.checkOut();
    localbmv7.setElementMap(localcpa);
    localbmv7.setInsets(new Insets(0, 0, 0, 0));
    localJg10.bb(localbmv7);
    localbmv7.brn();
    localbmv7.rV();
    localJg10.rV();
    localcWk7.rV();
    localdRq13.rV();
    localdRq2.rV();
    localdRq1.rV();
    localanG.rV();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setAlign(ajb.dif);
    localcwP.setSize(new Or(-2, -2));
    localcwP.setInitValue(true);
    localcwP.setXOffset(100);
    localcwP.setYOffset(50);
    localbpn.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    dqa localdqa = new dqa();
    localdqa.aJ();
    localdqa.setElementMap(localcpa);
    localbpn.bb(localdqa);
    localdqa.brn();
    dRq localdRq15 = dRq.checkOut();
    localdRq15.setElementMap(localcpa);
    localdqa.bb(localdRq15);
    localdRq15.brn();
    a(localdRq15);
    b(localdRq15);
    d(localdRq15);
    localdRq15.rV();
    localdqa.rV();
    localbpn.rV();
    return localbpn;
  }

  public bdj a(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    czO localczO = new czO();
    localczO.aJ();
    localczO.setAdaptToContentSize(true);
    parambdj.bb(localczO);
    localczO.brn();
    localczO.rV();
    return null;
  }

  public bdj b(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(false);
    localdRq1.bb(localaId);
    localaId.brn();
    localaId.rV();
    dRq localdRq2 = localdRq1;
    Jg localJg = localdRq2.getAppearance();
    localJg.setElementMap(localcpa);
    localdRq1.bb(localJg);
    localJg.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(0, 3, 0, 0));
    localJg.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg.rV();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(-2, 100.0F));
    localcwP.setAlign(ajb.dhY);
    localdRq1.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setStyle("stateBarContainerTop");
    localczv1.setExpandable(false);
    localczv1.setNonBlocking(true);
    localdRq1.bb(localczv1);
    localczv1.brn();
    localczv1.rV();
    czv localczv2 = new czv();
    localczv2.aJ();
    localczv2.setElementMap(localcpa);
    localczv2.setStyle("stateBarContainerCenterVertical");
    localczv2.setScaled(true);
    localczv2.setExpandable(true);
    localczv2.setNonBlocking(true);
    localdRq1.bb(localczv2);
    localczv2.brn();
    localczv2.rV();
    czv localczv3 = new czv();
    localczv3.aJ();
    localczv3.setElementMap(localcpa);
    localczv3.setStyle("stateBarContainerBottom");
    localczv3.setExpandable(false);
    localczv3.setNonBlocking(true);
    localdRq1.bb(localczv3);
    localczv3.brn();
    localczv3.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj d(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    ccG localccG1 = new ccG();
    localccG1.aJ();
    localccG1.setElementMap(localcpa);
    localccG1.setCellSize(new Or(34, 42));
    localccG1.setExpandable(false);
    localccG1.setHorizontal(true);
    localccG1.setAutoIdealSize(true);
    localccG1.setIdealSizeMinRows(1);
    localccG1.setIdealSizeMaxRows(6);
    localccG1.setPrefSize(new Or(34, 42));
    localccG1.setNonBlocking(true);
    anx localanx = new anx();
    localanx.hg("wakfu.popupInfos:showPopup(statePopup,stateBarWindow)");
    localccG1.setOnItemOver(localanx);
    cVk localcVk = new cVk();
    localcVk.hg("wakfu.popupInfos:closePopup");
    localccG1.setOnItemOut(localcVk);
    aqC localaqC = new aqC();
    localaqC.hg("wakfu.controlCenter:openRunningEffectDescription");
    localccG1.setOnItemClick(localaqC);
    parambdj.bb(localccG1);
    localccG1.brn();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setName("observedCharacter");
    localNK.setAttribute("content");
    localNK.setField("allStates");
    localccG1.bb(localNK);
    localNK.brn();
    localNK.rV();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localccG1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    ccG localccG2 = localccG1;
    Jg localJg1 = localccG2.getAppearance();
    localJg1.setElementMap(localcpa);
    localccG1.bb(localJg1);
    localJg1.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(5, 9, 5, 0));
    localJg1.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg1.rV();
    eR localeR = new eR();
    localeR.aJ();
    localeR.setElementMap(localcpa);
    localccG1.bb(localeR);
    localeR.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localeR.bb(localanQ1);
    localanQ1.brn();
    bxx localbxx = new bxx();
    localbxx.aJ();
    localbxx.setElementMap(localcpa);
    localanQ1.bb(localbxx);
    localbxx.brn();
    anE localanE1 = new anE();
    localanE1.aJ();
    localanE1.setElementMap(localcpa);
    localbxx.bb(localanE1);
    localanE1.brn();
    localanE1.rV();
    localbxx.rV();
    localanQ1.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localeR.bb(localdRq1);
    localdRq1.brn();
    czO localczO1 = new czO();
    localczO1.aJ();
    localdRq1.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setStyle("white2");
    localdRq2.setExpandable(false);
    localdRq2.setNonBlocking(false);
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setSize(new Or(32, 32));
    localcwP2.setAlign(ajb.dhT);
    localdRq2.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    dRq localdRq3 = localdRq2;
    Jg localJg2 = localdRq3.getAppearance();
    localJg2.setElementMap(localcpa);
    localdRq2.bb(localJg2);
    localJg2.brn();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(2, 2, 2, 2));
    localJg2.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    localJg2.rV();
    czO localczO2 = new czO();
    localczO2.aJ();
    localczO2.setAdaptToContentSize(true);
    localdRq2.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setExpandable(false);
    localczv.setScaled(true);
    localczv.setDisplaySize(new Or(24, 24));
    localczv.setNonBlocking(true);
    localdRq2.bb(localczv);
    localczv.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setAlign(ajb.dhZ);
    localcwP3.setSize(new Or(100.0F, 100.0F));
    localczv.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv.bb(localaAR);
    localaAR.brn();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setField("iconUrl");
    localaaE1.setAttribute("texture");
    localaAR.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    localaAR.rV();
    localczv.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setStyle("backgroundPopupLight");
    localdRq2.bb(localdRq4);
    localdRq4.brn();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("visible");
    localaaE2.setField("stackSize");
    localdRq4.bb(localaaE2);
    localaaE2.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localaaE2.bb(localanQ2);
    localanQ2.brn();
    aEJ localaEJ = new aEJ();
    localaEJ.aJ();
    localaEJ.setElementMap(localcpa);
    localaEJ.setValue("1");
    localanQ2.bb(localaEJ);
    localaEJ.brn();
    localaEJ.rV();
    localanQ2.rV();
    localaaE2.rV();
    dRq localdRq5 = localdRq4;
    Jg localJg3 = localdRq5.getAppearance();
    localJg3.setElementMap(localcpa);
    localdRq4.bb(localJg3);
    localJg3.brn();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(2, 2, 2, 2));
    localJg3.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    localJg3.rV();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setAlign(ajb.dih);
    localcwP4.setSize(new Or(-2, -2));
    localcwP4.setXOffset(3);
    localcwP4.setYOffset(-3);
    localdRq4.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("White10Bordered");
    localcaF1.setExpandable(false);
    localcaF1.setNonBlocking(true);
    localdRq4.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg4 = localcaF2.getAppearance();
    localJg4.setElementMap(localcpa);
    ((cwJ)localJg4).setAlign(aFG.eck);
    localcaF1.bb(localJg4);
    localJg4.brn();
    localJg4.rV();
    aaE localaaE3 = new aaE();
    localaaE3.aJ();
    localaaE3.setElementMap(localcpa);
    localaaE3.setAttribute("text");
    localaaE3.setField("stackSize");
    localcaF1.bb(localaaE3);
    localaaE3.brn();
    localaaE3.rV();
    localcaF1.rV();
    localdRq4.rV();
    localdRq2.rV();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq6.setStyle("backgroundPopupLight");
    localdRq1.bb(localdRq6);
    localdRq6.brn();
    cwP localcwP5 = new cwP();
    localcwP5.aJ();
    localcwP5.setElementMap(localcpa);
    localcwP5.setSize(new Or(-2, -2));
    localcwP5.setAlign(ajb.dif);
    localdRq6.bb(localcwP5);
    localcwP5.brn();
    localcwP5.rV();
    aaE localaaE4 = new aaE();
    localaaE4.aJ();
    localaaE4.setElementMap(localcpa);
    localaaE4.setAttribute("visible");
    localaaE4.setField("remainingDuration");
    localdRq6.bb(localaaE4);
    localaaE4.brn();
    anQ localanQ3 = new anQ();
    localanQ3.aJ();
    localanQ3.setElementMap(localcpa);
    localaaE4.bb(localanQ3);
    localanQ3.brn();
    anE localanE2 = new anE();
    localanE2.aJ();
    localanE2.setElementMap(localcpa);
    localanQ3.bb(localanE2);
    localanE2.brn();
    localanE2.rV();
    localanQ3.rV();
    localaaE4.rV();
    dRq localdRq7 = localdRq6;
    Jg localJg5 = localdRq7.getAppearance();
    localJg5.setElementMap(localcpa);
    localdRq6.bb(localJg5);
    localJg5.brn();
    cuR localcuR3 = new cuR();
    localcuR3.aJ();
    localcuR3.setElementMap(localcpa);
    localcuR3.setInsets(new Insets(0, 3, 0, 3));
    localJg5.bb(localcuR3);
    localcuR3.brn();
    localcuR3.rV();
    localJg5.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("white");
    localcWk1.setExpandable(false);
    localcWk1.setNonBlocking(true);
    localdRq6.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg6 = localcWk2.getAppearance();
    localJg6.setElementMap(localcpa);
    ((cwJ)localJg6).setAlign(aFG.eck);
    localcWk1.bb(localJg6);
    localJg6.brn();
    localJg6.rV();
    aaE localaaE5 = new aaE();
    localaaE5.aJ();
    localaaE5.setElementMap(localcpa);
    localaaE5.setAttribute("text");
    localaaE5.setField("remainingDuration");
    localcWk1.bb(localaaE5);
    localaaE5.brn();
    localaaE5.rV();
    localcWk1.rV();
    localdRq6.rV();
    localdRq1.rV();
    localeR.rV();
    localccG1.rV();
    return localccG1;
  }
}