import java.awt.Insets;
import java.util.Stack;

public class aIS
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    String str1 = "consoleDialog";
    bpn localbpn = new bpn();
    localbpn.aJ();
    localbpn.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localbpn);
    localbpn.setNonBlocking(true);
    localbpn.setSize(new Or(300, 300));
    localbpn.setX(100);
    localbpn.setY(100);
    localbpn.setPrefSize(new Or(100, 100));
    localbpn.setStyle("console");
    localbpn.brn();
    bTm localbTm1 = new bTm();
    localbTm1.aJ();
    localbpn.bb(localbTm1);
    localbTm1.brn();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localbTm1.bb(localdRq1);
    localdRq1.brn();
    cba localcba1 = cba.checkOut();
    localcba1.setElementMap(localcpa);
    localcba1.setData(cFu.izR);
    localdRq1.bb(localcba1);
    localcba1.brn();
    localcba1.rV();
    bTm localbTm2 = new bTm();
    localbTm2.aJ();
    localdRq1.bb(localbTm2);
    localbTm2.brn();
    dqa localdqa = new dqa();
    localdqa.aJ();
    localdqa.setElementMap(localcpa);
    localdqa.setThemeElementName("titleBar");
    localdqa.setThemeElementParentType("window");
    Zd localZd = new Zd();
    localZd.hg("xulor:toggleVisible(windowContentContainer)");
    localdqa.setOnDoubleClick(localZd);
    localbTm2.bb(localdqa);
    localdqa.brn();
    cba localcba2 = cba.checkOut();
    localcba2.setElementMap(localcpa);
    localcba2.setData(cFu.izV);
    localdqa.bb(localcba2);
    localcba2.brn();
    localcba2.rV();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(false);
    localdqa.bb(localaId);
    localaId.brn();
    biy localbiy1 = new biy();
    localbiy1.aJ();
    localbiy1.setElementMap(localcpa);
    localbiy1.setStyle("smallDelete");
    localbiy1.setExpandable(false);
    csA localcsA1 = new csA();
    localcsA1.hg("unloadDialog");
    localbiy1.setOnClick(localcsA1);
    localaId.bb(localbiy1);
    localbiy1.brn();
    localbiy1.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setThemeElementName("label");
    localcaF1.setThemeElementParentType("window");
    localcaF1.setOrientation(Pw.chV);
    localcaF1.setNonBlocking(true);
    String str2 = "%dialog.console.title%";
    str2 = str2.replace("%dialog.console.title%", cBQ.cxL().mL("dialog.console.title"));
    localcaF1.setText(str2);
    localaId.bb(localcaF1);
    localcaF1.brn();
    localcaF1.rV();
    localaId.rV();
    localdqa.rV();
    String str3 = "windowContentContainer";
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    if ((localcpa != null) && (str3 != null))
      localcpa.a(str3, localdRq2);
    localdRq2.setThemeElementName("content");
    localdRq2.setThemeElementParentType("window");
    localbTm2.bb(localdRq2);
    localdRq2.brn();
    cba localcba3 = cba.checkOut();
    localcba3.setElementMap(localcpa);
    localcba3.setData(cFu.izR);
    localdRq2.bb(localcba3);
    localcba3.brn();
    localcba3.rV();
    czO localczO1 = new czO();
    localczO1.aJ();
    localdRq2.bb(localczO1);
    localczO1.brn();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localczO1.bb(localdRq3);
    localdRq3.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setAlign(ajb.dhZ);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localdRq3.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    bTm localbTm3 = new bTm();
    localbTm3.aJ();
    localdRq3.bb(localbTm3);
    localbTm3.brn();
    bbp localbbp = new bbp();
    localbbp.aJ();
    localbbp.setElementMap(localcpa);
    localbbp.setNonBlocking(true);
    localbTm3.bb(localbbp);
    localbbp.brn();
    cba localcba4 = cba.checkOut();
    localcba4.setElementMap(localcpa);
    localcba4.setData(cFu.izR);
    localbbp.bb(localcba4);
    localcba4.brn();
    localcba4.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setSelectable(true);
    localcWk1.setEnableShrinking(false);
    localbbp.bb(localcWk1);
    localcWk1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setName("debug.console");
    localNK1.setField("logs");
    localNK1.setAttribute("text");
    localcWk1.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    cWk localcWk2 = localcWk1;
    Jg localJg1 = localcWk2.getAppearance();
    localJg1.setElementMap(localcpa);
    localcWk1.bb(localJg1);
    localJg1.brn();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(0, 5, 0, 0));
    localJg1.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    localJg1.rV();
    localcWk1.rV();
    localbbp.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setStyle("ConsoleInput");
    localbTm3.bb(localdRq4);
    localdRq4.brn();
    cba localcba5 = cba.checkOut();
    localcba5.setElementMap(localcpa);
    localcba5.setData(cFu.izT);
    localdRq4.bb(localcba5);
    localcba5.brn();
    localcba5.rV();
    bTm localbTm4 = new bTm();
    localbTm4.aJ();
    localdRq4.bb(localbTm4);
    localbTm4.brn();
    String str4 = "consoleForm";
    dso localdso = new dso();
    localdso.aJ();
    localdso.setElementMap(localcpa);
    if ((localcpa != null) && (str4 != null))
      localcpa.a(str4, localdso);
    this.Y.a((localcpa != null ? localcpa.getId() : "") + ".consoleForm", localdso);
    localbTm4.bb(localdso);
    localdso.brn();
    caF localcaF2 = new caF();
    localcaF2.aJ();
    localcaF2.setElementMap(localcpa);
    localdso.bb(localcaF2);
    localcaF2.brn();
    cba localcba6 = cba.checkOut();
    localcba6.setElementMap(localcpa);
    localcba6.setData(cFu.izV);
    localcaF2.bb(localcba6);
    localcba6.brn();
    localcba6.rV();
    caF localcaF3 = localcaF2;
    Jg localJg2 = localcaF3.getAppearance();
    localJg2.setElementMap(localcpa);
    localcaF2.bb(localJg2);
    localJg2.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 2, 0, 2));
    localJg2.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg2.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("debug.console");
    localNK2.setField("prompt");
    localNK2.setAttribute("text");
    localcaF2.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localcaF2.rV();
    aTp localaTp = new aTp();
    localaTp.aJ();
    localaTp.setElementMap(localcpa);
    localaTp.setAutoHorizontalScrolled(Boolean.valueOf(true));
    aOn localaOn = new aOn();
    localaOn.hg("console:processInputKeyEvent(consoleForm)");
    localaTp.setOnKeyPress(localaOn);
    localaTp.setFocused(true);
    localaTp.setStyle("dark");
    localdso.bb(localaTp);
    localaTp.brn();
    cba localcba7 = cba.checkOut();
    localcba7.setElementMap(localcpa);
    localcba7.setData(cFu.izR);
    localaTp.bb(localcba7);
    localcba7.brn();
    localcba7.rV();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setName("debug.console");
    localNK3.setField("input");
    localNK3.setAttribute("text");
    localaTp.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    localaTp.rV();
    biy localbiy2 = new biy();
    localbiy2.aJ();
    localbiy2.setElementMap(localcpa);
    localbiy2.setStyle("small");
    String str5 = "%clear%";
    str5 = str5.replace("%clear%", cBQ.cxL().mL("clear"));
    localbiy2.setText(str5);
    csA localcsA2 = new csA();
    localcsA2.hg("console:clear()");
    localbiy2.setOnClick(localcsA2);
    localdso.bb(localbiy2);
    localbiy2.brn();
    biy localbiy3 = localbiy2;
    Jg localJg3 = localbiy3.getAppearance();
    localJg3.setElementMap(localcpa);
    localbiy2.bb(localJg3);
    localJg3.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 0, 0, 20));
    localJg3.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg3.rV();
    cba localcba8 = cba.checkOut();
    localcba8.setElementMap(localcpa);
    localcba8.setData(cFu.izU);
    localbiy2.bb(localcba8);
    localcba8.brn();
    localcba8.rV();
    localbiy2.rV();
    localdso.rV();
    this.Y.nh((localcpa != null ? localcpa.getId() : "") + ".consoleForm");
    localbTm4.rV();
    localdRq4.rV();
    localbTm3.rV();
    localdRq3.rV();
    WV localWV = new WV();
    localWV.aJ();
    localWV.setElementMap(localcpa);
    localWV.setPointAlign(aFG.eco);
    localczO1.bb(localWV);
    localWV.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.dih);
    localWV.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    czO localczO2 = new czO();
    localczO2.aJ();
    localczO2.setAdaptToContentSize(true);
    localWV.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    biy localbiy4 = new biy();
    localbiy4.aJ();
    localbiy4.setElementMap(localcpa);
    localbiy4.setStyle("Yellow");
    localbiy4.setExpandable(false);
    localbiy4.setNonBlocking(true);
    localWV.bb(localbiy4);
    localbiy4.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setAlign(ajb.dhZ);
    localcwP3.setSize(new Or(100.0F, 100.0F));
    localbiy4.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    biy localbiy5 = localbiy4;
    Jg localJg4 = localbiy5.getAppearance();
    localJg4.setElementMap(localcpa);
    localbiy4.bb(localJg4);
    localJg4.brn();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(2, 2, 2, 3));
    localJg4.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    localJg4.rV();
    localbiy4.rV();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setStyle("multidirectionnalCross");
    localczv.setNonBlocking(true);
    localWV.bb(localczv);
    localczv.brn();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setAlign(ajb.dhZ);
    localczv.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    localczv.rV();
    localWV.rV();
    localczO1.rV();
    localdRq2.rV();
    localbTm2.rV();
    localdRq1.rV();
    localbTm1.rV();
    cwP localcwP5 = new cwP();
    localcwP5.aJ();
    localcwP5.setElementMap(localcpa);
    localcwP5.setSize(new Or(600, 300));
    localcwP5.setInitValue(true);
    localbpn.bb(localcwP5);
    localcwP5.brn();
    localcwP5.rV();
    localbpn.rV();
    return localbpn;
  }
}