import java.awt.Insets;
import java.util.Stack;

public class dfA
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    String str = "mainContainer";
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    if ((localcpa != null) && (str != null))
      localcpa.a(str, localdRq1);
    localdRq1.setNonBlocking(false);
    localdRq1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(-2, -2));
    localcwP1.setAlign(ajb.dif);
    localcwP1.setYOffset(50);
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    czO localczO1 = new czO();
    localczO1.aJ();
    localczO1.setAdaptToContentSize(true);
    localdRq1.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setStyle("DialogBackground");
    localdRq1.bb(localczv1);
    localczv1.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.did);
    localcwP2.setSize(new Or(-2, -2));
    localcwP2.setYOffset(0);
    localcwP2.setXOffset(-30);
    localczv1.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    localczv1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(82, 0, 0, 0));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setSize(new Or(399, -2));
    localcwP3.setAlign(ajb.dih);
    localcwP3.setXOffset(-101);
    localcwP3.setYOffset(82);
    localdRq2.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    czO localczO2 = new czO();
    localczO2.aJ();
    localczO2.setAdaptToContentSize(true);
    localdRq2.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq2.bb(localdRq4);
    localdRq4.brn();
    dRq localdRq5 = localdRq4;
    Jg localJg2 = localdRq5.getAppearance();
    localJg2.setElementMap(localcpa);
    localdRq4.bb(localJg2);
    localJg2.brn();
    localJg2.rV();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setSize(new Or(100.0F, 100.0F));
    localdRq4.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localaId1.setAlign(aFG.ech);
    localdRq4.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    czv localczv2 = new czv();
    localczv2.aJ();
    localczv2.setElementMap(localcpa);
    localczv2.setStyle("DialogTop");
    localczv2.setExpandable(false);
    localdRq4.bb(localczv2);
    localczv2.brn();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa);
    localdpm1.setAlign(aFG.ecl);
    localczv2.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    czv localczv3 = localczv2;
    Jg localJg3 = localczv3.getAppearance();
    localJg3.setElementMap(localcpa);
    localczv2.bb(localJg3);
    localJg3.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 1, 0, 0));
    localJg3.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg3.rV();
    localczv2.rV();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq6.setStyle("tiledScroll2");
    localdRq4.bb(localdRq6);
    localdRq6.brn();
    localdRq6.rV();
    localdRq4.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localdRq2.bb(localdRq7);
    localdRq7.brn();
    cwP localcwP5 = new cwP();
    localcwP5.aJ();
    localcwP5.setElementMap(localcpa);
    localcwP5.setSize(new Or(100.0F, 100.0F));
    localdRq7.bb(localcwP5);
    localcwP5.brn();
    localcwP5.rV();
    dRq localdRq8 = localdRq7;
    Jg localJg4 = localdRq8.getAppearance();
    localJg4.setElementMap(localcpa);
    localdRq7.bb(localJg4);
    localJg4.brn();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(0, 33, 0, 33));
    localJg4.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(30, 0, 0, 0));
    localJg4.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg4.rV();
    aId localaId2 = aId.checkOut();
    localaId2.setHorizontal(false);
    localdRq7.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa);
    localdRq9.setStyle("EncyclopediaSplashTitle");
    localdRq9.setPrefSize(new Or(0, 30));
    localdRq9.setExpandable(false);
    localdRq7.bb(localdRq9);
    localdRq9.brn();
    dRq localdRq10 = localdRq9;
    Jg localJg5 = localdRq10.getAppearance();
    localJg5.setElementMap(localcpa);
    localdRq9.bb(localJg5);
    localJg5.brn();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(0, 0, 3, 0));
    localJg5.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    localJg5.rV();
    aId localaId3 = aId.checkOut();
    localaId3.setAlign(aFG.eck);
    localdRq9.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    czv localczv4 = new czv();
    localczv4.aJ();
    localczv4.setElementMap(localcpa);
    localczv4.setDisplaySize(new Or(83, 39));
    localczv4.setStyle("NationLeftDecorator");
    localczv4.setExpandable(false);
    localdRq9.bb(localczv4);
    localczv4.brn();
    localczv4.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("StyledBold16White");
    localcWk1.setNonBlocking(true);
    localcWk1.setExpandable(false);
    localdRq9.bb(localcWk1);
    localcWk1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setName("almanach");
    localNK1.setAttribute("text");
    localNK1.setField("currentDateText");
    localcWk1.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    localcWk1.rV();
    czv localczv5 = new czv();
    localczv5.aJ();
    localczv5.setElementMap(localcpa);
    localczv5.setDisplaySize(new Or(83, 39));
    localczv5.setStyle("NationRightDecorator");
    localczv5.setExpandable(false);
    localdRq9.bb(localczv5);
    localczv5.brn();
    localczv5.rV();
    localdRq9.rV();
    cWk localcWk2 = new cWk();
    localcWk2.aJ();
    localcWk2.setElementMap(localcpa);
    localcWk2.setStyle("darkTitle");
    localcWk2.setExpandable(false);
    localdRq7.bb(localcWk2);
    localcWk2.brn();
    cWk localcWk3 = localcWk2;
    Jg localJg6 = localcWk3.getAppearance();
    localJg6.setElementMap(localcpa);
    ((cwJ)localJg6).setAlign(aFG.eck);
    localcWk2.bb(localJg6);
    localJg6.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(0, 0, 0, 0));
    localJg6.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg6.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("almanach");
    localNK2.setAttribute("text");
    localNK2.setField("currentEphemeris/merydName");
    localcWk2.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localcWk2.rV();
    dRq localdRq11 = dRq.checkOut();
    localdRq11.setElementMap(localcpa);
    localdRq7.bb(localdRq11);
    localdRq11.brn();
    aId localaId4 = aId.checkOut();
    localaId4.setAlign(aFG.ecj);
    localdRq11.bb(localaId4);
    localaId4.brn();
    localaId4.rV();
    czv localczv6 = new czv();
    localczv6.aJ();
    localczv6.setElementMap(localcpa);
    localczv6.setDisplaySize(new Or(73, 100));
    localczv6.setExpandable(false);
    localdRq11.bb(localczv6);
    localczv6.brn();
    czv localczv7 = localczv6;
    Jg localJg7 = localczv7.getAppearance();
    localJg7.setElementMap(localcpa);
    localczv6.bb(localJg7);
    localJg7.brn();
    bmv localbmv5 = bmv.checkOut();
    localbmv5.setElementMap(localcpa);
    localbmv5.setInsets(new Insets(0, 0, 0, 5));
    localJg7.bb(localbmv5);
    localbmv5.brn();
    localbmv5.rV();
    localJg7.rV();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa);
    localdpm2.setAlign(aFG.ech);
    localczv6.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv6.bb(localaAR);
    localaAR.brn();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setName("almanach");
    localNK3.setAttribute("texture");
    localNK3.setField("currentEphemeris/merydIconUrl");
    localaAR.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    localaAR.rV();
    localczv6.rV();
    cWk localcWk4 = new cWk();
    localcWk4.aJ();
    localcWk4.setElementMap(localcpa);
    localcWk4.setStyle("darkBold");
    localcWk4.setNonBlocking(true);
    localcWk4.setMinWidth(1);
    localcWk4.setMaxWidth(250);
    localcWk4.setExpandable(false);
    localdRq11.bb(localcWk4);
    localcWk4.brn();
    dpm localdpm3 = new dpm();
    localdpm3.aJ();
    localdpm3.setElementMap(localcpa);
    localdpm3.setAlign(aFG.ech);
    localcWk4.bb(localdpm3);
    localdpm3.brn();
    localdpm3.rV();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa);
    localNK4.setName("almanach");
    localNK4.setAttribute("text");
    localNK4.setField("currentEphemeris/merydDesc");
    localcWk4.bb(localNK4);
    localNK4.brn();
    localNK4.rV();
    localcWk4.rV();
    localdRq11.rV();
    dRq localdRq12 = dRq.checkOut();
    localdRq12.setElementMap(localcpa);
    localdRq12.setStyle("caracs");
    localdRq7.bb(localdRq12);
    localdRq12.brn();
    dRq localdRq13 = localdRq12;
    Jg localJg8 = localdRq13.getAppearance();
    localJg8.setElementMap(localcpa);
    localJg8.setModulationColor(new bNa(0.22F, 0.17F, 0.14F, 0.75F));
    localdRq12.bb(localJg8);
    localJg8.brn();
    bmv localbmv6 = bmv.checkOut();
    localbmv6.setElementMap(localcpa);
    localbmv6.setInsets(new Insets(3, 0, 0, 0));
    localJg8.bb(localbmv6);
    localbmv6.brn();
    localbmv6.rV();
    cuR localcuR3 = new cuR();
    localcuR3.aJ();
    localcuR3.setElementMap(localcpa);
    localcuR3.setInsets(new Insets(0, 0, 3, 0));
    localJg8.bb(localcuR3);
    localcuR3.brn();
    localcuR3.rV();
    localJg8.rV();
    aId localaId5 = aId.checkOut();
    localaId5.setHorizontal(false);
    localdRq12.bb(localaId5);
    localaId5.brn();
    localaId5.rV();
    dRq localdRq14 = dRq.checkOut();
    localdRq14.setElementMap(localcpa);
    localdRq12.bb(localdRq14);
    localdRq14.brn();
    aId localaId6 = aId.checkOut();
    localaId6.setAlign(aFG.ecj);
    localdRq14.bb(localaId6);
    localaId6.brn();
    localaId6.rV();
    czv localczv8 = new czv();
    localczv8.aJ();
    localczv8.setElementMap(localcpa);
    localczv8.setDisplaySize(new Or(32, 32));
    localczv8.setExpandable(false);
    localczv8.setStyle("warning");
    localdRq14.bb(localczv8);
    localczv8.brn();
    localczv8.rV();
    cWk localcWk5 = new cWk();
    localcWk5.aJ();
    localcWk5.setElementMap(localcpa);
    localcWk5.setStyle("styledBoldWhite12");
    localcWk5.setMinWidth(1);
    localcWk5.setMaxWidth(250);
    localcWk5.setExpandable(false);
    localdRq14.bb(localcWk5);
    localcWk5.brn();
    NK localNK5 = NK.checkOut();
    localNK5.setElementMap(localcpa);
    localNK5.setLocal(true);
    localNK5.setName("displayedAchievement");
    localNK5.setAttribute("text");
    localNK5.setField("name");
    localcWk5.bb(localNK5);
    localNK5.brn();
    localNK5.rV();
    cWk localcWk6 = localcWk5;
    Jg localJg9 = localcWk6.getAppearance();
    localJg9.setElementMap(localcpa);
    localcWk5.bb(localJg9);
    localJg9.brn();
    bmv localbmv7 = bmv.checkOut();
    localbmv7.setElementMap(localcpa);
    localbmv7.setInsets(new Insets(0, 5, 0, 0));
    localJg9.bb(localbmv7);
    localbmv7.brn();
    localbmv7.rV();
    cAf localcAf1 = cAf.checkOut();
    localcAf1.setElementMap(localcpa);
    localcAf1.setColor(new bNa(1.0F, 0.78F, 0.15F, 1.0F));
    localJg9.bb(localcAf1);
    localcAf1.brn();
    localcAf1.rV();
    localJg9.rV();
    localcWk5.rV();
    localdRq14.rV();
    cWk localcWk7 = new cWk();
    localcWk7.aJ();
    localcWk7.setElementMap(localcpa);
    localcWk7.setStyle("bold");
    localcWk7.setMinWidth(1);
    localcWk7.setMaxWidth(310);
    localcWk7.setExpandable(false);
    localdRq12.bb(localcWk7);
    localcWk7.brn();
    dpm localdpm4 = new dpm();
    localdpm4.aJ();
    localdpm4.setElementMap(localcpa);
    localdpm4.setAlign(aFG.ecj);
    localcWk7.bb(localdpm4);
    localdpm4.brn();
    localdpm4.rV();
    cWk localcWk8 = localcWk7;
    Jg localJg10 = localcWk8.getAppearance();
    localJg10.setElementMap(localcpa);
    localcWk7.bb(localJg10);
    localJg10.brn();
    cAf localcAf2 = cAf.checkOut();
    localcAf2.setElementMap(localcpa);
    localcAf2.setColor(new bNa(0.94F, 0.86F, 0.66F, 1.0F));
    localJg10.bb(localcAf2);
    localcAf2.brn();
    localcAf2.rV();
    bmv localbmv8 = bmv.checkOut();
    localbmv8.setElementMap(localcpa);
    localbmv8.setInsets(new Insets(0, 3, 0, 3));
    localJg10.bb(localbmv8);
    localbmv8.brn();
    localbmv8.rV();
    localJg10.rV();
    NK localNK6 = NK.checkOut();
    localNK6.setElementMap(localcpa);
    localNK6.setLocal(true);
    localNK6.setName("displayedAchievement");
    localNK6.setField("backgroundText");
    localNK6.setAttribute("text");
    localcWk7.bb(localNK6);
    localNK6.brn();
    localNK6.rV();
    localcWk7.rV();
    localdRq12.rV();
    dRq localdRq15 = dRq.checkOut();
    localdRq15.setElementMap(localcpa);
    localdRq15.setExpandable(false);
    localdRq7.bb(localdRq15);
    localdRq15.brn();
    dRq localdRq16 = localdRq15;
    Jg localJg11 = localdRq16.getAppearance();
    localJg11.setElementMap(localcpa);
    localdRq15.bb(localJg11);
    localJg11.brn();
    bmv localbmv9 = bmv.checkOut();
    localbmv9.setElementMap(localcpa);
    localbmv9.setInsets(new Insets(5, 0, 5, 0));
    localJg11.bb(localbmv9);
    localbmv9.brn();
    localbmv9.rV();
    localJg11.rV();
    dpm localdpm5 = new dpm();
    localdpm5.aJ();
    localdpm5.setElementMap(localcpa);
    localdpm5.setAlign(aFG.ecj);
    localdRq15.bb(localdpm5);
    localdpm5.brn();
    localdpm5.rV();
    czO localczO3 = new czO();
    localczO3.aJ();
    localczO3.setAdaptToContentSize(true);
    localdRq15.bb(localczO3);
    localczO3.brn();
    localczO3.rV();
    czv localczv9 = new czv();
    localczv9.aJ();
    localczv9.setElementMap(localcpa);
    localczv9.setStyle("scrollTitleBar");
    localczv9.setDisplaySize(new Or(330, 29));
    localdRq15.bb(localczv9);
    localczv9.brn();
    a(localczv9);
    localczv9.rV();
    b(localdRq15);
    localdRq15.rV();
    d(localdRq7);
    localdRq7.rV();
    e(localdRq2);
    f(localdRq2);
    g(localdRq2);
    localdRq2.rV();
    h(localdRq1);
    k(localdRq1);
    localdRq1.rV();
    return localdRq1;
  }

  public bdj a(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(-2, -2));
    localcwP.setAlign(ajb.dhY);
    parambdj.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    return localcwP;
  }

  public bdj b(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("styledBoldWhite12");
    localcWk1.setNonBlocking(true);
    String str = "%achievement.reward%";
    str = str.replace("%achievement.reward%", cBQ.cxL().mL("achievement.reward"));
    localcWk1.setText(str);
    parambdj.bb(localcWk1);
    localcWk1.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setAlign(ajb.dhY);
    localcwP.setSize(new Or(100.0F, 2));
    localcWk1.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    cWk localcWk2 = localcWk1;
    Jg localJg = localcWk2.getAppearance();
    localJg.setElementMap(localcpa);
    ((cwJ)localJg).setAlign(aFG.eck);
    localcWk1.bb(localJg);
    localJg.brn();
    cAf localcAf = cAf.checkOut();
    localcAf.setElementMap(localcpa);
    localcAf.setColor(new bNa(0.94F, 0.86F, 0.66F, 1.0F));
    localJg.bb(localcAf);
    localcAf.brn();
    localcAf.rV();
    localJg.rV();
    localcWk1.rV();
    return localcWk1;
  }

  public bdj d(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    ccG localccG1 = new ccG();
    localccG1.aJ();
    localccG1.setElementMap(localcpa);
    localccG1.setCellSize(new Or(52, 52));
    localccG1.setExpandable(false);
    localccG1.setAutoIdealSize(true);
    localccG1.setIdealSizeMinRows(1);
    localccG1.setIdealSizeMaxRows(1);
    parambdj.bb(localccG1);
    localccG1.brn();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setLocal(true);
    localNK.setName("displayedAchievement");
    localNK.setField("rewards");
    localNK.setAttribute("content");
    localccG1.bb(localNK);
    localNK.brn();
    localNK.rV();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.eck);
    localccG1.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    ccG localccG2 = localccG1;
    Jg localJg1 = localccG2.getAppearance();
    localJg1.setElementMap(localcpa);
    localccG1.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 0, 0, 0));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    eR localeR = new eR();
    localeR.aJ();
    localeR.setElementMap(localcpa);
    aqC localaqC = new aqC();
    localaqC.hg("wakfu:openItemDetailWindow()");
    localeR.setOnItemClick(localaqC);
    localccG1.bb(localeR);
    localeR.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localeR.bb(localanQ1);
    localanQ1.brn();
    bxx localbxx = new bxx();
    localbxx.aJ();
    localbxx.setElementMap(localcpa);
    localanQ1.bb(localbxx);
    localbxx.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localbxx.bb(localanE);
    localanE.brn();
    localanE.rV();
    localbxx.rV();
    localanQ1.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localeR.bb(localdRq1);
    localdRq1.brn();
    aId localaId = aId.checkOut();
    localaId.setAlign(aFG.ecj);
    localdRq1.bb(localaId);
    localaId.brn();
    localaId.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setExpandable(false);
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg2 = localdRq3.getAppearance();
    localJg2.setElementMap(localcpa);
    localdRq2.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 0, 0, 5));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    czO localczO = new czO();
    localczO.aJ();
    localczO.setAdaptToContentSize(true);
    localdRq2.bb(localczO);
    localczO.brn();
    localczO.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setStyle("IconEmptyEmote");
    localdRq2.bb(localczv1);
    localczv1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(-2, -2));
    localcwP1.setAlign(ajb.dhZ);
    localczv1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    localczv1.rV();
    czv localczv2 = new czv();
    localczv2.aJ();
    localczv2.setElementMap(localcpa);
    localczv2.setDisplaySize(new Or(48, 48));
    localdRq2.bb(localczv2);
    localczv2.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.dhZ);
    localcwP2.setSize(new Or(-2, -2));
    localczv2.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv2.bb(localaAR);
    localaAR.brn();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("texture");
    localaaE1.setField("iconUrl");
    localaAR.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    localaAR.rV();
    localczv2.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("bold");
    localdRq2.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg3 = localcaF2.getAppearance();
    localJg3.setElementMap(localcpa);
    localcaF1.bb(localJg3);
    localJg3.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(5, 5, 5, 5));
    localJg3.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    cAf localcAf = cAf.checkOut();
    localcAf.setElementMap(localcpa);
    localcAf.setColor(new bNa(0.29F, 0.17F, 0.07F, 1.0F));
    localcAf.setName("text");
    localJg3.bb(localcAf);
    localcAf.brn();
    localcAf.rV();
    localJg3.rV();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setSize(new Or(-2, -2));
    localcwP3.setAlign(ajb.dih);
    localcaF1.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("text");
    localaaE2.setField("quantity");
    localcaF1.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    aaE localaaE3 = new aaE();
    localaaE3.aJ();
    localaaE3.setElementMap(localcpa);
    localaaE3.setAttribute("visible");
    localaaE3.setField("quantity");
    localcaF1.bb(localaaE3);
    localaaE3.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localaaE3.bb(localanQ2);
    localanQ2.brn();
    aEJ localaEJ = new aEJ();
    localaEJ.aJ();
    localaEJ.setElementMap(localcpa);
    localaEJ.setValue("1");
    localanQ2.bb(localaEJ);
    localaEJ.brn();
    localaEJ.rV();
    localanQ2.rV();
    localaaE3.rV();
    localcaF1.rV();
    localdRq2.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("styledBoldDark10");
    localcWk1.setMinWidth(1);
    localcWk1.setMaxWidth(115);
    localcWk1.setExpandable(false);
    localdRq1.bb(localcWk1);
    localcWk1.brn();
    aaE localaaE4 = new aaE();
    localaaE4.aJ();
    localaaE4.setElementMap(localcpa);
    localaaE4.setAttribute("text");
    localaaE4.setField("description");
    localcWk1.bb(localaaE4);
    localaaE4.brn();
    localaaE4.rV();
    cWk localcWk2 = localcWk1;
    Jg localJg4 = localcWk2.getAppearance();
    localJg4.setElementMap(localcpa);
    ((cwJ)localJg4).setAlign(aFG.ech);
    localcWk1.bb(localJg4);
    localJg4.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(10, 0, 0, 0));
    localJg4.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg4.rV();
    localcWk1.rV();
    localdRq1.rV();
    localeR.rV();
    localccG1.rV();
    return localccG1;
  }

  public bdj e(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    biy localbiy = new biy();
    localbiy.aJ();
    localbiy.setElementMap(localcpa);
    localbiy.setStyle("close");
    csA localcsA = new csA();
    localcsA.hg("unloadDialog");
    localbiy.setOnClick(localcsA);
    parambdj.bb(localbiy);
    localbiy.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setAlign(ajb.dhV);
    localcwP.setSize(new Or(-2, -2));
    localcwP.setXOffset(-20);
    localcwP.setYOffset(-20);
    localbiy.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localbiy.rV();
    return localbiy;
  }

  public bdj f(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setNonBlocking(true);
    localczv.setStyle("MessageBoxIconDecorator");
    parambdj.bb(localczv);
    localczv.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(-2, -2));
    localcwP.setAlign(ajb.dhT);
    localcwP.setXOffset(0);
    localcwP.setYOffset(20);
    localczv.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localczv.rV();
    return localczv;
  }

  public bdj g(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setNonBlocking(true);
    localczv.setStyle("AlmanachBigIcon");
    parambdj.bb(localczv);
    localczv.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(-2, -2));
    localcwP.setAlign(ajb.dhT);
    localcwP.setXOffset(0);
    localcwP.setYOffset(20);
    localczv.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localczv.rV();
    return localczv;
  }

  public bdj h(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setStyle("dialogBackgroundTitle");
    localdRq1.setPrefSize(new Or(150, 26));
    parambdj.bb(localdRq1);
    localdRq1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setAlign(ajb.did);
    localcwP1.setSize(new Or(-2, -2));
    localcwP1.setYOffset(71);
    localcwP1.setXOffset(85);
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    dRq localdRq2 = localdRq1;
    Jg localJg1 = localdRq2.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq1.bb(localJg1);
    localJg1.brn();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(5, 0, 10, 0));
    localJg1.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    localJg1.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq3.setExpandable(false);
    localdRq1.bb(localdRq3);
    localdRq3.brn();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localdRq3.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setStyle("caracsBackground");
    localdRq4.setExpandable(false);
    localdRq4.setPrefSize(new Or(0, 20));
    localdRq3.bb(localdRq4);
    localdRq4.brn();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.eck);
    localdRq4.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    dRq localdRq5 = localdRq4;
    Jg localJg2 = localdRq5.getAppearance();
    localJg2.setElementMap(localcpa);
    localdRq4.bb(localJg2);
    localJg2.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(7, 15, 0, 15));
    localJg2.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(4, 4, 4, 4));
    localJg2.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    localJg2.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setDisplaySize(new Or(100, 100));
    cCu localcCu1 = new cCu();
    localcCu1.hg("popup(protectorPopup)");
    localczv1.setOnPopupDisplay(localcCu1);
    jL localjL1 = new jL();
    localjL1.hg("closePopup");
    localczv1.setOnPopupHide(localjL1);
    localdRq4.bb(localczv1);
    localczv1.brn();
    String str1 = "protectorPopup";
    anG localanG1 = new anG();
    localanG1.aJ();
    localanG1.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localanG1);
    localanG1.setAlign(aFG.ech);
    localanG1.setHotSpotPosition(aFG.ecn);
    localczv1.bb(localanG1);
    localanG1.brn();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq6.setStyle("popup");
    localanG1.bb(localdRq6);
    localdRq6.brn();
    aId localaId2 = aId.checkOut();
    localaId2.setHorizontal(false);
    localdRq6.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("styledBoldWhite12");
    localcWk1.setMinWidth(1);
    localcWk1.setMaxWidth(250);
    localcWk1.setExpandable(false);
    localdRq6.bb(localcWk1);
    localcWk1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setName("almanach");
    localNK1.setAttribute("text");
    localNK1.setField("currentMonth/protectorName");
    localcWk1.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    cWk localcWk2 = localcWk1;
    Jg localJg3 = localcWk2.getAppearance();
    localJg3.setElementMap(localcpa);
    localcWk1.bb(localJg3);
    localJg3.brn();
    cAf localcAf1 = cAf.checkOut();
    localcAf1.setElementMap(localcpa);
    localcAf1.setColor(new bNa(1.0F, 0.78F, 0.15F, 1.0F));
    localJg3.bb(localcAf1);
    localcAf1.brn();
    localcAf1.rV();
    localJg3.rV();
    localcWk1.rV();
    cWk localcWk3 = new cWk();
    localcWk3.aJ();
    localcWk3.setElementMap(localcpa);
    localcWk3.setStyle("bold");
    localcWk3.setMinWidth(1);
    localcWk3.setMaxWidth(250);
    localcWk3.setExpandable(false);
    localdRq6.bb(localcWk3);
    localcWk3.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("almanach");
    localNK2.setAttribute("text");
    localNK2.setField("currentMonth/protectorDesc");
    localcWk3.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    cWk localcWk4 = localcWk3;
    Jg localJg4 = localcWk4.getAppearance();
    localJg4.setElementMap(localcpa);
    localcWk3.bb(localJg4);
    localJg4.brn();
    cAf localcAf2 = cAf.checkOut();
    localcAf2.setElementMap(localcpa);
    localcAf2.setColor(new bNa(0.94F, 0.86F, 0.66F, 1.0F));
    localJg4.bb(localcAf2);
    localcAf2.brn();
    localcAf2.rV();
    localJg4.rV();
    localcWk3.rV();
    localdRq6.rV();
    localanG1.rV();
    czv localczv2 = localczv1;
    Jg localJg5 = localczv2.getAppearance();
    localJg5.setElementMap(localcpa);
    localczv1.bb(localJg5);
    localJg5.brn();
    jO localjO = new jO();
    localjO.aJ();
    localjO.setElementMap(localcpa);
    localjO.setColor(new bNa(1.0F, 1.0F, 1.0F, 1.0F));
    localJg5.bb(localjO);
    localjO.brn();
    localjO.rV();
    localJg5.rV();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv1.bb(localaAR);
    localaAR.brn();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setName("almanach");
    localNK3.setAttribute("texture");
    localNK3.setField("currentMonth/protectorIconUrl");
    localaAR.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    localaAR.rV();
    localczv1.rV();
    localdRq4.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localdRq7.setExpandable(false);
    localdRq3.bb(localdRq7);
    localdRq7.brn();
    dRq localdRq8 = localdRq7;
    Jg localJg6 = localdRq8.getAppearance();
    localJg6.setElementMap(localcpa);
    localdRq7.bb(localJg6);
    localJg6.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(5, 12, 0, 12));
    localJg6.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    ams localams = new ams();
    localams.aJ();
    localams.setElementMap(localcpa);
    localams.setInsets(new Insets(0, 0, 1, 0));
    localams.setColor(new bNa(0.0F, 0.0F, 0.0F, 0.25F));
    localJg6.bb(localams);
    localams.brn();
    localams.rV();
    cuR localcuR3 = new cuR();
    localcuR3.aJ();
    localcuR3.setElementMap(localcpa);
    localcuR3.setInsets(new Insets(0, 10, 5, 10));
    localJg6.bb(localcuR3);
    localcuR3.brn();
    localcuR3.rV();
    localJg6.rV();
    aId localaId3 = aId.checkOut();
    localaId3.setAlign(aFG.eck);
    localdRq7.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    biy localbiy1 = new biy();
    localbiy1.aJ();
    localbiy1.setElementMap(localcpa);
    localbiy1.setStyle("yellowLeftArrow");
    csA localcsA1 = new csA();
    localcsA1.hg("wakfu.almanach:previousMonth");
    localbiy1.setOnClick(localcsA1);
    localbiy1.setExpandable(false);
    localdRq7.bb(localbiy1);
    localbiy1.brn();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa);
    localNK4.setName("almanach");
    localNK4.setAttribute("enabled");
    localNK4.setField("canGoBefore");
    localbiy1.bb(localNK4);
    localNK4.brn();
    localNK4.rV();
    localbiy1.rV();
    cWk localcWk5 = new cWk();
    localcWk5.aJ();
    localcWk5.setElementMap(localcpa);
    localcWk5.setStyle("StyledBold16Dark");
    localcWk5.setExpandable(true);
    localdRq7.bb(localcWk5);
    localcWk5.brn();
    cWk localcWk6 = localcWk5;
    Jg localJg7 = localcWk6.getAppearance();
    localJg7.setElementMap(localcpa);
    ((cwJ)localJg7).setAlign(aFG.eck);
    localcWk5.bb(localJg7);
    localJg7.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 5, 0, 5));
    localJg7.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg7.rV();
    NK localNK5 = NK.checkOut();
    localNK5.setElementMap(localcpa);
    localNK5.setName("almanach");
    localNK5.setAttribute("text");
    localNK5.setField("currentMonth/monthName");
    localcWk5.bb(localNK5);
    localNK5.brn();
    localNK5.rV();
    localcWk5.rV();
    biy localbiy2 = new biy();
    localbiy2.aJ();
    localbiy2.setElementMap(localcpa);
    localbiy2.setStyle("yellowRightArrow");
    csA localcsA2 = new csA();
    localcsA2.hg("wakfu.almanach:nextMonth");
    localbiy2.setOnClick(localcsA2);
    localbiy2.setExpandable(false);
    localdRq7.bb(localbiy2);
    localbiy2.brn();
    NK localNK6 = NK.checkOut();
    localNK6.setElementMap(localcpa);
    localNK6.setName("almanach");
    localNK6.setAttribute("enabled");
    localNK6.setField("canGoAfter");
    localbiy2.bb(localNK6);
    localNK6.brn();
    localNK6.rV();
    localbiy2.rV();
    localdRq7.rV();
    cWk localcWk7 = new cWk();
    localcWk7.aJ();
    localcWk7.setElementMap(localcpa);
    localcWk7.setStyle("darkBold");
    cCu localcCu2 = new cCu();
    localcCu2.hg("popup(zodiakPopup)");
    localcWk7.setOnPopupDisplay(localcCu2);
    jL localjL2 = new jL();
    localjL2.hg("closePopup");
    localcWk7.setOnPopupHide(localjL2);
    localdRq3.bb(localcWk7);
    localcWk7.brn();
    String str2 = "zodiakPopup";
    anG localanG2 = new anG();
    localanG2.aJ();
    localanG2.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localanG2);
    localanG2.setAlign(aFG.ech);
    localanG2.setHotSpotPosition(aFG.ecn);
    localcWk7.bb(localanG2);
    localanG2.brn();
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa);
    localdRq9.setStyle("popup");
    localanG2.bb(localdRq9);
    localdRq9.brn();
    aId localaId4 = aId.checkOut();
    localaId4.setHorizontal(false);
    localdRq9.bb(localaId4);
    localaId4.brn();
    localaId4.rV();
    cWk localcWk8 = new cWk();
    localcWk8.aJ();
    localcWk8.setElementMap(localcpa);
    localcWk8.setStyle("styledBoldWhite12");
    localcWk8.setMinWidth(1);
    localcWk8.setMaxWidth(250);
    localcWk8.setExpandable(false);
    localdRq9.bb(localcWk8);
    localcWk8.brn();
    NK localNK7 = NK.checkOut();
    localNK7.setElementMap(localcpa);
    localNK7.setName("almanach");
    localNK7.setAttribute("text");
    localNK7.setField("currentZodiak/name");
    localcWk8.bb(localNK7);
    localNK7.brn();
    localNK7.rV();
    cWk localcWk9 = localcWk8;
    Jg localJg8 = localcWk9.getAppearance();
    localJg8.setElementMap(localcpa);
    localcWk8.bb(localJg8);
    localJg8.brn();
    cAf localcAf3 = cAf.checkOut();
    localcAf3.setElementMap(localcpa);
    localcAf3.setColor(new bNa(1.0F, 0.78F, 0.15F, 1.0F));
    localJg8.bb(localcAf3);
    localcAf3.brn();
    localcAf3.rV();
    localJg8.rV();
    localcWk8.rV();
    cWk localcWk10 = new cWk();
    localcWk10.aJ();
    localcWk10.setElementMap(localcpa);
    localcWk10.setStyle("bold");
    localcWk10.setMinWidth(1);
    localcWk10.setMaxWidth(250);
    localcWk10.setExpandable(false);
    localdRq9.bb(localcWk10);
    localcWk10.brn();
    NK localNK8 = NK.checkOut();
    localNK8.setElementMap(localcpa);
    localNK8.setName("almanach");
    localNK8.setAttribute("text");
    localNK8.setField("currentZodiak/description");
    localcWk10.bb(localNK8);
    localNK8.brn();
    localNK8.rV();
    cWk localcWk11 = localcWk10;
    Jg localJg9 = localcWk11.getAppearance();
    localJg9.setElementMap(localcpa);
    localcWk10.bb(localJg9);
    localJg9.brn();
    cAf localcAf4 = cAf.checkOut();
    localcAf4.setElementMap(localcpa);
    localcAf4.setColor(new bNa(0.94F, 0.86F, 0.66F, 1.0F));
    localJg9.bb(localcAf4);
    localcAf4.brn();
    localcAf4.rV();
    localJg9.rV();
    localcWk10.rV();
    localdRq9.rV();
    localanG2.rV();
    NK localNK9 = NK.checkOut();
    localNK9.setElementMap(localcpa);
    localNK9.setName("almanach");
    localNK9.setAttribute("text");
    localNK9.setField("currentZodiak/name");
    localcWk7.bb(localNK9);
    localNK9.brn();
    localNK9.rV();
    cWk localcWk12 = localcWk7;
    Jg localJg10 = localcWk12.getAppearance();
    localJg10.setElementMap(localcpa);
    ((cwJ)localJg10).setAlign(aFG.eck);
    localcWk7.bb(localJg10);
    localJg10.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(5, 0, 0, 0));
    localJg10.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    cAf localcAf5 = cAf.checkOut();
    localcAf5.setElementMap(localcpa);
    localcAf5.setColor(new bNa(0.5F, 0.5F, 0.5F, 1.0F));
    localJg10.bb(localcAf5);
    localcAf5.brn();
    localcAf5.rV();
    localJg10.rV();
    localcWk7.rV();
    String str3 = "calendar";
    bWa localbWa1 = new bWa();
    localbWa1.aJ();
    localbWa1.setElementMap(localcpa);
    if ((localcpa != null) && (str3 != null))
      localcpa.a(str3, localbWa1);
    localbWa1.setCellSize(new Or(22, 22));
    localbWa1.setStyle("almanach");
    localbWa1.setExpandable(false);
    aqC localaqC = new aqC();
    localaqC.hg("wakfu.almanach:selectDate");
    localbWa1.setOnItemClick(localaqC);
    localdRq3.bb(localbWa1);
    localbWa1.brn();
    bWa localbWa2 = localbWa1;
    Jg localJg11 = localbWa2.getAppearance();
    localJg11.setElementMap(localcpa);
    localbWa1.bb(localJg11);
    localJg11.brn();
    bmv localbmv5 = bmv.checkOut();
    localbmv5.setElementMap(localcpa);
    localbmv5.setInsets(new Insets(5, 20, 0, 20));
    localJg11.bb(localbmv5);
    localbmv5.brn();
    localbmv5.rV();
    localJg11.rV();
    NK localNK10 = NK.checkOut();
    localNK10.setElementMap(localcpa);
    localNK10.setName("almanach");
    localNK10.setAttribute("content");
    localNK10.setField("currentMonthDays");
    localbWa1.bb(localNK10);
    localNK10.brn();
    localNK10.rV();
    NK localNK11 = NK.checkOut();
    localNK11.setElementMap(localcpa);
    localNK11.setName("almanach");
    localNK11.setAttribute("calendar");
    localNK11.setField("calendar");
    localbWa1.bb(localNK11);
    localNK11.brn();
    localNK11.rV();
    eR localeR = new eR();
    localeR.aJ();
    localeR.setElementMap(localcpa);
    localbWa1.bb(localeR);
    localeR.brn();
    dRq localdRq10 = dRq.checkOut();
    localdRq10.setElementMap(localcpa);
    localeR.bb(localdRq10);
    localdRq10.brn();
    czO localczO = new czO();
    localczO.aJ();
    localczO.setAdaptToContentSize(true);
    localdRq10.bb(localczO);
    localczO.brn();
    localczO.rV();
    biy localbiy3 = new biy();
    localbiy3.aJ();
    localbiy3.setElementMap(localcpa);
    localbiy3.setStyle("flat");
    localdRq10.bb(localbiy3);
    localbiy3.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localbiy3.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    aaE localaaE = new aaE();
    localaaE.aJ();
    localaaE.setElementMap(localcpa);
    localaaE.setAttribute("enabled");
    localaaE.setField("isEnabled");
    localbiy3.bb(localaaE);
    localaaE.brn();
    localaaE.rV();
    i(localbiy3);
    localbiy3.rV();
    j(localdRq10);
    localdRq10.rV();
    localeR.rV();
    localbWa1.rV();
    localdRq3.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj i(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dOc localdOc = (dOc)parambdj;
    Jg localJg = localdOc.getAppearance();
    localJg.setElementMap(localcpa);
    parambdj.bb(localJg);
    localJg.brn();
    aaE localaaE = new aaE();
    localaaE.aJ();
    localaaE.setElementMap(localcpa);
    localaaE.setAttribute("modulationColor");
    localaaE.setField("isToday");
    localJg.bb(localaaE);
    localaaE.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localanQ.setValue("1, 0.78, 0.15, 1.0");
    localanQ.setElseValue("1,1,1,1");
    localaaE.bb(localanQ);
    localanQ.brn();
    cOk localcOk = new cOk();
    localcOk.aJ();
    localcOk.setElementMap(localcpa);
    localanQ.bb(localcOk);
    localcOk.brn();
    localcOk.rV();
    localanQ.rV();
    localaaE.rV();
    localJg.rV();
    return localJg;
  }

  public bdj j(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setStyle("almanachQuestDone");
    localczv1.setNonBlocking(true);
    parambdj.bb(localczv1);
    localczv1.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(-2, -2));
    localcwP.setAlign(ajb.dif);
    localcwP.setYOffset(3);
    localczv1.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("visible");
    localaaE1.setField("isEnabled");
    localczv1.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    czv localczv2 = localczv1;
    Jg localJg = localczv2.getAppearance();
    localJg.setElementMap(localcpa);
    localczv1.bb(localJg);
    localJg.brn();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("modulationColor");
    localaaE2.setField("entry/quest/isCompleted");
    localJg.bb(localaaE2);
    localaaE2.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localanQ.setValue("0,1,0");
    localanQ.setElseValue("1,0,0");
    localaaE2.bb(localanQ);
    localanQ.brn();
    cOk localcOk = new cOk();
    localcOk.aJ();
    localcOk.setElementMap(localcpa);
    localanQ.bb(localcOk);
    localcOk.brn();
    localcOk.rV();
    localanQ.rV();
    localaaE2.rV();
    localJg.rV();
    localczv1.rV();
    return localczv1;
  }

  public bdj k(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setAlign(ajb.dih);
    localcwP1.setSize(new Or(-2, -2));
    localcwP1.setXOffset(-114);
    localcwP1.setYOffset(72);
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    czO localczO = new czO();
    localczO.aJ();
    localczO.setAdaptToContentSize(true);
    localdRq1.bb(localczO);
    localczO.brn();
    localczO.rV();
    biy localbiy = new biy();
    localbiy.aJ();
    localbiy.setElementMap(localcpa);
    localbiy.setStyle("bigLeftWindow");
    cCu localcCu = new cCu();
    localcCu.hg("popup(almanachRewardPopup)");
    localbiy.setOnPopupDisplay(localcCu);
    jL localjL = new jL();
    localjL.hg("closePopup");
    localbiy.setOnPopupHide(localjL);
    csA localcsA = new csA();
    localcsA.hg("wakfu.almanach:displayRewardMachine");
    localbiy.setOnClick(localcsA);
    localdRq1.bb(localbiy);
    localbiy.brn();
    String str1 = "almanachRewardPopup";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localanG);
    localanG.setAlign(aFG.ech);
    localanG.setHotSpotPosition(aFG.ecn);
    localbiy.bb(localanG);
    localanG.brn();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setPrefSize(new Or(10, 0));
    localdRq2.setStyle("popup");
    localanG.bb(localdRq2);
    localdRq2.brn();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("white");
    localcWk1.setEnableShrinking(false);
    String str2 = "%almanach.rewardMachine%";
    str2 = str2.replace("%almanach.rewardMachine%", cBQ.cxL().mL("almanach.rewardMachine"));
    localcWk1.setText(str2);
    localdRq2.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg = localcWk2.getAppearance();
    localJg.setElementMap(localcpa);
    ((cwJ)localJg).setAlignment(aFG.eck);
    localcWk1.bb(localJg);
    localJg.brn();
    localJg.rV();
    localcWk1.rV();
    localdRq2.rV();
    localanG.rV();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setSize(new Or(69, 58));
    localcwP2.setAlign(ajb.dif);
    localbiy.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    localbiy.rV();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setNonBlocking(true);
    localczv.setStyle("almanachRewardMachine");
    localdRq1.bb(localczv);
    localczv.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setSize(new Or(-2, -2));
    localcwP3.setAlign(ajb.dhT);
    localcwP3.setXOffset(0);
    localcwP3.setYOffset(7);
    localczv.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    localczv.rV();
    localdRq1.rV();
    return localdRq1;
  }
}