import java.util.Stack;

public class Hq
  implements aTK
{
  private uk W;
  private Stack X = new Stack();

  public void a(cpa paramcpa, uk paramuk, dOc paramdOc)
  {
    this.W = paramuk;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    dOc localdOc1 = paramdOc;
    Jg localJg1 = localdOc1.getAppearance();
    localJg1.setElementMap(localcpa);
    localJg1.setState("default");
    paramdOc.bb(localJg1);
    localJg1.brn();
    String str1 = "caracContainerBorder";
    Cx localCx1 = new Cx();
    localCx1.aJ();
    localCx1.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localCx1);
    localJg1.bb(localCx1);
    localCx1.brn();
    aAR localaAR1 = aAR.checkOut();
    localaAR1.setElementMap(localcpa);
    localaAR1.setPosition(ajb.dhR);
    localaAR1.setX(548);
    localaAR1.setY(170);
    localaAR1.setWidth(5);
    localaAR1.setHeight(4);
    localaAR1.setTexture(this.W.aH("default_1.tga"));
    localCx1.bb(localaAR1);
    localaAR1.brn();
    localaAR1.rV();
    aAR localaAR2 = aAR.checkOut();
    localaAR2.setElementMap(localcpa);
    localaAR2.setPosition(ajb.dhT);
    localaAR2.setX(2);
    localaAR2.setY(337);
    localaAR2.setWidth(1);
    localaAR2.setHeight(4);
    localaAR2.setTexture(this.W.aH("default_0.tga"));
    localCx1.bb(localaAR2);
    localaAR2.brn();
    localaAR2.rV();
    aAR localaAR3 = aAR.checkOut();
    localaAR3.setElementMap(localcpa);
    localaAR3.setFlipHorizontaly(true);
    localaAR3.setPosition(ajb.dhV);
    localaAR3.setX(548);
    localaAR3.setY(170);
    localaAR3.setWidth(5);
    localaAR3.setHeight(4);
    localaAR3.setTexture(this.W.aH("default_1.tga"));
    localCx1.bb(localaAR3);
    localaAR3.brn();
    localaAR3.rV();
    aAR localaAR4 = aAR.checkOut();
    localaAR4.setElementMap(localcpa);
    localaAR4.setPosition(ajb.dhY);
    localaAR4.setX(967);
    localaAR4.setY(83);
    localaAR4.setWidth(5);
    localaAR4.setHeight(1);
    localaAR4.setTexture(this.W.aH("default_0.tga"));
    localCx1.bb(localaAR4);
    localaAR4.brn();
    localaAR4.rV();
    aAR localaAR5 = aAR.checkOut();
    localaAR5.setElementMap(localcpa);
    localaAR5.setFlipHorizontaly(true);
    localaAR5.setPosition(ajb.dia);
    localaAR5.setX(967);
    localaAR5.setY(83);
    localaAR5.setWidth(5);
    localaAR5.setHeight(1);
    localaAR5.setTexture(this.W.aH("default_0.tga"));
    localCx1.bb(localaAR5);
    localaAR5.brn();
    localaAR5.rV();
    aAR localaAR6 = aAR.checkOut();
    localaAR6.setElementMap(localcpa);
    localaAR6.setFlipVerticaly(true);
    localaAR6.setPosition(ajb.did);
    localaAR6.setX(548);
    localaAR6.setY(170);
    localaAR6.setWidth(5);
    localaAR6.setHeight(4);
    localaAR6.setTexture(this.W.aH("default_1.tga"));
    localCx1.bb(localaAR6);
    localaAR6.brn();
    localaAR6.rV();
    aAR localaAR7 = aAR.checkOut();
    localaAR7.setElementMap(localcpa);
    localaAR7.setFlipVerticaly(true);
    localaAR7.setPosition(ajb.dif);
    localaAR7.setX(2);
    localaAR7.setY(337);
    localaAR7.setWidth(1);
    localaAR7.setHeight(4);
    localaAR7.setTexture(this.W.aH("default_0.tga"));
    localCx1.bb(localaAR7);
    localaAR7.brn();
    localaAR7.rV();
    aAR localaAR8 = aAR.checkOut();
    localaAR8.setElementMap(localcpa);
    localaAR8.setFlipHorizontaly(true);
    localaAR8.setFlipVerticaly(true);
    localaAR8.setPosition(ajb.dih);
    localaAR8.setX(548);
    localaAR8.setY(170);
    localaAR8.setWidth(5);
    localaAR8.setHeight(4);
    localaAR8.setTexture(this.W.aH("default_1.tga"));
    localCx1.bb(localaAR8);
    localaAR8.brn();
    localaAR8.rV();
    localCx1.rV();
    String str2 = "caracContainerBackground2";
    aen localaen1 = aen.checkOut();
    localaen1.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localaen1);
    localaen1.setScaled(true);
    localJg1.bb(localaen1);
    localaen1.brn();
    aAR localaAR9 = aAR.checkOut();
    localaAR9.setElementMap(localcpa);
    localaAR9.setPosition(ajb.dhZ);
    localaAR9.setX(2);
    localaAR9.setY(156);
    localaAR9.setWidth(1);
    localaAR9.setHeight(1);
    localaAR9.setTexture(this.W.aH("default_0.tga"));
    localaen1.bb(localaAR9);
    localaAR9.brn();
    localaAR9.rV();
    localaen1.rV();
    cAf localcAf1 = cAf.checkOut();
    localcAf1.setElementMap(localcpa);
    localcAf1.setColor(new bNa(1.0F, 1.0F, 1.0F, 1.0F));
    localcAf1.setDecoratorSwitch(true);
    localcAf1.setName("modulation");
    localJg1.bb(localcAf1);
    localcAf1.brn();
    localcAf1.rV();
    localJg1.rV();
    dOc localdOc2 = paramdOc;
    Jg localJg2 = localdOc2.getAppearance();
    localJg2.setElementMap(localcpa);
    localJg2.setState("mouseHover");
    paramdOc.bb(localJg2);
    localJg2.brn();
    String str3 = "caracContainerBorder";
    Cx localCx2 = new Cx();
    localCx2.aJ();
    localCx2.setElementMap(localcpa);
    if ((localcpa != null) && (str3 != null))
      localcpa.a(str3, localCx2);
    localJg2.bb(localCx2);
    localCx2.brn();
    aAR localaAR10 = aAR.checkOut();
    localaAR10.setElementMap(localcpa);
    localaAR10.setPosition(ajb.dhR);
    localaAR10.setX(548);
    localaAR10.setY(170);
    localaAR10.setWidth(5);
    localaAR10.setHeight(4);
    localaAR10.setTexture(this.W.aH("default_1.tga"));
    localCx2.bb(localaAR10);
    localaAR10.brn();
    localaAR10.rV();
    aAR localaAR11 = aAR.checkOut();
    localaAR11.setElementMap(localcpa);
    localaAR11.setPosition(ajb.dhT);
    localaAR11.setX(2);
    localaAR11.setY(337);
    localaAR11.setWidth(1);
    localaAR11.setHeight(4);
    localaAR11.setTexture(this.W.aH("default_0.tga"));
    localCx2.bb(localaAR11);
    localaAR11.brn();
    localaAR11.rV();
    aAR localaAR12 = aAR.checkOut();
    localaAR12.setElementMap(localcpa);
    localaAR12.setFlipHorizontaly(true);
    localaAR12.setPosition(ajb.dhV);
    localaAR12.setX(548);
    localaAR12.setY(170);
    localaAR12.setWidth(5);
    localaAR12.setHeight(4);
    localaAR12.setTexture(this.W.aH("default_1.tga"));
    localCx2.bb(localaAR12);
    localaAR12.brn();
    localaAR12.rV();
    aAR localaAR13 = aAR.checkOut();
    localaAR13.setElementMap(localcpa);
    localaAR13.setPosition(ajb.dhY);
    localaAR13.setX(967);
    localaAR13.setY(83);
    localaAR13.setWidth(5);
    localaAR13.setHeight(1);
    localaAR13.setTexture(this.W.aH("default_0.tga"));
    localCx2.bb(localaAR13);
    localaAR13.brn();
    localaAR13.rV();
    aAR localaAR14 = aAR.checkOut();
    localaAR14.setElementMap(localcpa);
    localaAR14.setFlipHorizontaly(true);
    localaAR14.setPosition(ajb.dia);
    localaAR14.setX(967);
    localaAR14.setY(83);
    localaAR14.setWidth(5);
    localaAR14.setHeight(1);
    localaAR14.setTexture(this.W.aH("default_0.tga"));
    localCx2.bb(localaAR14);
    localaAR14.brn();
    localaAR14.rV();
    aAR localaAR15 = aAR.checkOut();
    localaAR15.setElementMap(localcpa);
    localaAR15.setFlipVerticaly(true);
    localaAR15.setPosition(ajb.did);
    localaAR15.setX(548);
    localaAR15.setY(170);
    localaAR15.setWidth(5);
    localaAR15.setHeight(4);
    localaAR15.setTexture(this.W.aH("default_1.tga"));
    localCx2.bb(localaAR15);
    localaAR15.brn();
    localaAR15.rV();
    aAR localaAR16 = aAR.checkOut();
    localaAR16.setElementMap(localcpa);
    localaAR16.setFlipVerticaly(true);
    localaAR16.setPosition(ajb.dif);
    localaAR16.setX(2);
    localaAR16.setY(337);
    localaAR16.setWidth(1);
    localaAR16.setHeight(4);
    localaAR16.setTexture(this.W.aH("default_0.tga"));
    localCx2.bb(localaAR16);
    localaAR16.brn();
    localaAR16.rV();
    aAR localaAR17 = aAR.checkOut();
    localaAR17.setElementMap(localcpa);
    localaAR17.setFlipHorizontaly(true);
    localaAR17.setFlipVerticaly(true);
    localaAR17.setPosition(ajb.dih);
    localaAR17.setX(548);
    localaAR17.setY(170);
    localaAR17.setWidth(5);
    localaAR17.setHeight(4);
    localaAR17.setTexture(this.W.aH("default_1.tga"));
    localCx2.bb(localaAR17);
    localaAR17.brn();
    localaAR17.rV();
    localCx2.rV();
    String str4 = "caracContainerBackground2";
    aen localaen2 = aen.checkOut();
    localaen2.setElementMap(localcpa);
    if ((localcpa != null) && (str4 != null))
      localcpa.a(str4, localaen2);
    localaen2.setScaled(true);
    localJg2.bb(localaen2);
    localaen2.brn();
    aAR localaAR18 = aAR.checkOut();
    localaAR18.setElementMap(localcpa);
    localaAR18.setPosition(ajb.dhZ);
    localaAR18.setX(2);
    localaAR18.setY(156);
    localaAR18.setWidth(1);
    localaAR18.setHeight(1);
    localaAR18.setTexture(this.W.aH("default_0.tga"));
    localaen2.bb(localaAR18);
    localaAR18.brn();
    localaAR18.rV();
    localaen2.rV();
    cAf localcAf2 = cAf.checkOut();
    localcAf2.setElementMap(localcpa);
    localcAf2.setColor(new bNa(0.8F, 0.8F, 0.8F, 1.0F));
    localcAf2.setDecoratorSwitch(true);
    localcAf2.setName("modulation");
    localJg2.bb(localcAf2);
    localcAf2.brn();
    localcAf2.rV();
    localJg2.rV();
    dOc localdOc3 = paramdOc;
    Jg localJg3 = localdOc3.getAppearance();
    localJg3.setElementMap(localcpa);
    localJg3.setState("pressed");
    paramdOc.bb(localJg3);
    localJg3.brn();
    String str5 = "caracContainerBorder";
    Cx localCx3 = new Cx();
    localCx3.aJ();
    localCx3.setElementMap(localcpa);
    if ((localcpa != null) && (str5 != null))
      localcpa.a(str5, localCx3);
    localJg3.bb(localCx3);
    localCx3.brn();
    aAR localaAR19 = aAR.checkOut();
    localaAR19.setElementMap(localcpa);
    localaAR19.setPosition(ajb.dhR);
    localaAR19.setX(548);
    localaAR19.setY(170);
    localaAR19.setWidth(5);
    localaAR19.setHeight(4);
    localaAR19.setTexture(this.W.aH("default_1.tga"));
    localCx3.bb(localaAR19);
    localaAR19.brn();
    localaAR19.rV();
    aAR localaAR20 = aAR.checkOut();
    localaAR20.setElementMap(localcpa);
    localaAR20.setPosition(ajb.dhT);
    localaAR20.setX(2);
    localaAR20.setY(337);
    localaAR20.setWidth(1);
    localaAR20.setHeight(4);
    localaAR20.setTexture(this.W.aH("default_0.tga"));
    localCx3.bb(localaAR20);
    localaAR20.brn();
    localaAR20.rV();
    aAR localaAR21 = aAR.checkOut();
    localaAR21.setElementMap(localcpa);
    localaAR21.setFlipHorizontaly(true);
    localaAR21.setPosition(ajb.dhV);
    localaAR21.setX(548);
    localaAR21.setY(170);
    localaAR21.setWidth(5);
    localaAR21.setHeight(4);
    localaAR21.setTexture(this.W.aH("default_1.tga"));
    localCx3.bb(localaAR21);
    localaAR21.brn();
    localaAR21.rV();
    aAR localaAR22 = aAR.checkOut();
    localaAR22.setElementMap(localcpa);
    localaAR22.setPosition(ajb.dhY);
    localaAR22.setX(967);
    localaAR22.setY(83);
    localaAR22.setWidth(5);
    localaAR22.setHeight(1);
    localaAR22.setTexture(this.W.aH("default_0.tga"));
    localCx3.bb(localaAR22);
    localaAR22.brn();
    localaAR22.rV();
    aAR localaAR23 = aAR.checkOut();
    localaAR23.setElementMap(localcpa);
    localaAR23.setFlipHorizontaly(true);
    localaAR23.setPosition(ajb.dia);
    localaAR23.setX(967);
    localaAR23.setY(83);
    localaAR23.setWidth(5);
    localaAR23.setHeight(1);
    localaAR23.setTexture(this.W.aH("default_0.tga"));
    localCx3.bb(localaAR23);
    localaAR23.brn();
    localaAR23.rV();
    aAR localaAR24 = aAR.checkOut();
    localaAR24.setElementMap(localcpa);
    localaAR24.setFlipVerticaly(true);
    localaAR24.setPosition(ajb.did);
    localaAR24.setX(548);
    localaAR24.setY(170);
    localaAR24.setWidth(5);
    localaAR24.setHeight(4);
    localaAR24.setTexture(this.W.aH("default_1.tga"));
    localCx3.bb(localaAR24);
    localaAR24.brn();
    localaAR24.rV();
    aAR localaAR25 = aAR.checkOut();
    localaAR25.setElementMap(localcpa);
    localaAR25.setFlipVerticaly(true);
    localaAR25.setPosition(ajb.dif);
    localaAR25.setX(2);
    localaAR25.setY(337);
    localaAR25.setWidth(1);
    localaAR25.setHeight(4);
    localaAR25.setTexture(this.W.aH("default_0.tga"));
    localCx3.bb(localaAR25);
    localaAR25.brn();
    localaAR25.rV();
    aAR localaAR26 = aAR.checkOut();
    localaAR26.setElementMap(localcpa);
    localaAR26.setFlipHorizontaly(true);
    localaAR26.setFlipVerticaly(true);
    localaAR26.setPosition(ajb.dih);
    localaAR26.setX(548);
    localaAR26.setY(170);
    localaAR26.setWidth(5);
    localaAR26.setHeight(4);
    localaAR26.setTexture(this.W.aH("default_1.tga"));
    localCx3.bb(localaAR26);
    localaAR26.brn();
    localaAR26.rV();
    localCx3.rV();
    String str6 = "caracContainerBackground2";
    aen localaen3 = aen.checkOut();
    localaen3.setElementMap(localcpa);
    if ((localcpa != null) && (str6 != null))
      localcpa.a(str6, localaen3);
    localaen3.setScaled(true);
    localJg3.bb(localaen3);
    localaen3.brn();
    aAR localaAR27 = aAR.checkOut();
    localaAR27.setElementMap(localcpa);
    localaAR27.setPosition(ajb.dhZ);
    localaAR27.setX(2);
    localaAR27.setY(156);
    localaAR27.setWidth(1);
    localaAR27.setHeight(1);
    localaAR27.setTexture(this.W.aH("default_0.tga"));
    localaen3.bb(localaAR27);
    localaAR27.brn();
    localaAR27.rV();
    localaen3.rV();
    cAf localcAf3 = cAf.checkOut();
    localcAf3.setElementMap(localcpa);
    localcAf3.setColor(new bNa(0.6F, 0.6F, 0.6F, 1.0F));
    localcAf3.setDecoratorSwitch(true);
    localcAf3.setName("modulation");
    localJg3.bb(localcAf3);
    localcAf3.brn();
    localcAf3.rV();
    localJg3.rV();
    dOc localdOc4 = paramdOc;
    Jg localJg4 = localdOc4.getAppearance();
    localJg4.setElementMap(localcpa);
    localJg4.setState("disabled");
    paramdOc.bb(localJg4);
    localJg4.brn();
    String str7 = "caracContainerBorder";
    Cx localCx4 = new Cx();
    localCx4.aJ();
    localCx4.setElementMap(localcpa);
    if ((localcpa != null) && (str7 != null))
      localcpa.a(str7, localCx4);
    localJg4.bb(localCx4);
    localCx4.brn();
    aAR localaAR28 = aAR.checkOut();
    localaAR28.setElementMap(localcpa);
    localaAR28.setPosition(ajb.dhR);
    localaAR28.setX(548);
    localaAR28.setY(170);
    localaAR28.setWidth(5);
    localaAR28.setHeight(4);
    localaAR28.setTexture(this.W.aH("default_1.tga"));
    localCx4.bb(localaAR28);
    localaAR28.brn();
    localaAR28.rV();
    aAR localaAR29 = aAR.checkOut();
    localaAR29.setElementMap(localcpa);
    localaAR29.setPosition(ajb.dhT);
    localaAR29.setX(2);
    localaAR29.setY(337);
    localaAR29.setWidth(1);
    localaAR29.setHeight(4);
    localaAR29.setTexture(this.W.aH("default_0.tga"));
    localCx4.bb(localaAR29);
    localaAR29.brn();
    localaAR29.rV();
    aAR localaAR30 = aAR.checkOut();
    localaAR30.setElementMap(localcpa);
    localaAR30.setFlipHorizontaly(true);
    localaAR30.setPosition(ajb.dhV);
    localaAR30.setX(548);
    localaAR30.setY(170);
    localaAR30.setWidth(5);
    localaAR30.setHeight(4);
    localaAR30.setTexture(this.W.aH("default_1.tga"));
    localCx4.bb(localaAR30);
    localaAR30.brn();
    localaAR30.rV();
    aAR localaAR31 = aAR.checkOut();
    localaAR31.setElementMap(localcpa);
    localaAR31.setPosition(ajb.dhY);
    localaAR31.setX(967);
    localaAR31.setY(83);
    localaAR31.setWidth(5);
    localaAR31.setHeight(1);
    localaAR31.setTexture(this.W.aH("default_0.tga"));
    localCx4.bb(localaAR31);
    localaAR31.brn();
    localaAR31.rV();
    aAR localaAR32 = aAR.checkOut();
    localaAR32.setElementMap(localcpa);
    localaAR32.setFlipHorizontaly(true);
    localaAR32.setPosition(ajb.dia);
    localaAR32.setX(967);
    localaAR32.setY(83);
    localaAR32.setWidth(5);
    localaAR32.setHeight(1);
    localaAR32.setTexture(this.W.aH("default_0.tga"));
    localCx4.bb(localaAR32);
    localaAR32.brn();
    localaAR32.rV();
    aAR localaAR33 = aAR.checkOut();
    localaAR33.setElementMap(localcpa);
    localaAR33.setFlipVerticaly(true);
    localaAR33.setPosition(ajb.did);
    localaAR33.setX(548);
    localaAR33.setY(170);
    localaAR33.setWidth(5);
    localaAR33.setHeight(4);
    localaAR33.setTexture(this.W.aH("default_1.tga"));
    localCx4.bb(localaAR33);
    localaAR33.brn();
    localaAR33.rV();
    a(localCx4);
    b(localCx4);
    localCx4.rV();
    d(localJg4);
    localJg4.rV();
    e(paramdOc);
    f(paramdOc);
    g(paramdOc);
    h(paramdOc);
  }

  public bdj a(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localaAR.setFlipVerticaly(true);
    localaAR.setPosition(ajb.dif);
    localaAR.setX(2);
    localaAR.setY(337);
    localaAR.setWidth(1);
    localaAR.setHeight(4);
    localaAR.setTexture(this.W.aH("default_0.tga"));
    parambdj.bb(localaAR);
    localaAR.brn();
    localaAR.rV();
    return localaAR;
  }

  public bdj b(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localaAR.setFlipHorizontaly(true);
    localaAR.setFlipVerticaly(true);
    localaAR.setPosition(ajb.dih);
    localaAR.setX(548);
    localaAR.setY(170);
    localaAR.setWidth(5);
    localaAR.setHeight(4);
    localaAR.setTexture(this.W.aH("default_1.tga"));
    parambdj.bb(localaAR);
    localaAR.brn();
    localaAR.rV();
    return localaAR;
  }

  public bdj d(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    cAf localcAf = cAf.checkOut();
    localcAf.setElementMap(localcpa);
    localcAf.setColor(new bNa(0.9F, 0.9F, 0.9F, 0.8F));
    localcAf.setDecoratorSwitch(true);
    localcAf.setName("modulation");
    parambdj.bb(localcAf);
    localcAf.brn();
    localcAf.rV();
    return localcAf;
  }

  public bdj e(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dOc localdOc = (dOc)parambdj;
    Jg localJg = localdOc.getAppearance();
    localJg.setElementMap(localcpa);
    localJg.setState("selected");
    parambdj.bb(localJg);
    localJg.brn();
    String str1 = "caracContainerBorder";
    Cx localCx = new Cx();
    localCx.aJ();
    localCx.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localCx);
    localJg.bb(localCx);
    localCx.brn();
    aAR localaAR1 = aAR.checkOut();
    localaAR1.setElementMap(localcpa);
    localaAR1.setPosition(ajb.dhR);
    localaAR1.setX(548);
    localaAR1.setY(170);
    localaAR1.setWidth(5);
    localaAR1.setHeight(4);
    localaAR1.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR1);
    localaAR1.brn();
    localaAR1.rV();
    aAR localaAR2 = aAR.checkOut();
    localaAR2.setElementMap(localcpa);
    localaAR2.setPosition(ajb.dhT);
    localaAR2.setX(2);
    localaAR2.setY(337);
    localaAR2.setWidth(1);
    localaAR2.setHeight(4);
    localaAR2.setTexture(this.W.aH("default_0.tga"));
    localCx.bb(localaAR2);
    localaAR2.brn();
    localaAR2.rV();
    aAR localaAR3 = aAR.checkOut();
    localaAR3.setElementMap(localcpa);
    localaAR3.setFlipHorizontaly(true);
    localaAR3.setPosition(ajb.dhV);
    localaAR3.setX(548);
    localaAR3.setY(170);
    localaAR3.setWidth(5);
    localaAR3.setHeight(4);
    localaAR3.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR3);
    localaAR3.brn();
    localaAR3.rV();
    aAR localaAR4 = aAR.checkOut();
    localaAR4.setElementMap(localcpa);
    localaAR4.setPosition(ajb.dhY);
    localaAR4.setX(967);
    localaAR4.setY(83);
    localaAR4.setWidth(5);
    localaAR4.setHeight(1);
    localaAR4.setTexture(this.W.aH("default_0.tga"));
    localCx.bb(localaAR4);
    localaAR4.brn();
    localaAR4.rV();
    aAR localaAR5 = aAR.checkOut();
    localaAR5.setElementMap(localcpa);
    localaAR5.setFlipHorizontaly(true);
    localaAR5.setPosition(ajb.dia);
    localaAR5.setX(967);
    localaAR5.setY(83);
    localaAR5.setWidth(5);
    localaAR5.setHeight(1);
    localaAR5.setTexture(this.W.aH("default_0.tga"));
    localCx.bb(localaAR5);
    localaAR5.brn();
    localaAR5.rV();
    aAR localaAR6 = aAR.checkOut();
    localaAR6.setElementMap(localcpa);
    localaAR6.setFlipVerticaly(true);
    localaAR6.setPosition(ajb.did);
    localaAR6.setX(548);
    localaAR6.setY(170);
    localaAR6.setWidth(5);
    localaAR6.setHeight(4);
    localaAR6.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR6);
    localaAR6.brn();
    localaAR6.rV();
    aAR localaAR7 = aAR.checkOut();
    localaAR7.setElementMap(localcpa);
    localaAR7.setFlipVerticaly(true);
    localaAR7.setPosition(ajb.dif);
    localaAR7.setX(2);
    localaAR7.setY(337);
    localaAR7.setWidth(1);
    localaAR7.setHeight(4);
    localaAR7.setTexture(this.W.aH("default_0.tga"));
    localCx.bb(localaAR7);
    localaAR7.brn();
    localaAR7.rV();
    aAR localaAR8 = aAR.checkOut();
    localaAR8.setElementMap(localcpa);
    localaAR8.setFlipHorizontaly(true);
    localaAR8.setFlipVerticaly(true);
    localaAR8.setPosition(ajb.dih);
    localaAR8.setX(548);
    localaAR8.setY(170);
    localaAR8.setWidth(5);
    localaAR8.setHeight(4);
    localaAR8.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR8);
    localaAR8.brn();
    localaAR8.rV();
    localCx.rV();
    String str2 = "caracContainerBackground2";
    aen localaen = aen.checkOut();
    localaen.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localaen);
    localaen.setScaled(true);
    localJg.bb(localaen);
    localaen.brn();
    aAR localaAR9 = aAR.checkOut();
    localaAR9.setElementMap(localcpa);
    localaAR9.setPosition(ajb.dhZ);
    localaAR9.setX(2);
    localaAR9.setY(156);
    localaAR9.setWidth(1);
    localaAR9.setHeight(1);
    localaAR9.setTexture(this.W.aH("default_0.tga"));
    localaen.bb(localaAR9);
    localaAR9.brn();
    localaAR9.rV();
    localaen.rV();
    cAf localcAf = cAf.checkOut();
    localcAf.setElementMap(localcpa);
    localcAf.setColor(new bNa(0.74F, 0.81F, 0.89F, 1.0F));
    localcAf.setDecoratorSwitch(true);
    localcAf.setName("modulation");
    localJg.bb(localcAf);
    localcAf.brn();
    localcAf.rV();
    localJg.rV();
    return localJg;
  }

  public bdj f(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dOc localdOc = (dOc)parambdj;
    Jg localJg = localdOc.getAppearance();
    localJg.setElementMap(localcpa);
    localJg.setState("mouseHoverSelected");
    parambdj.bb(localJg);
    localJg.brn();
    String str1 = "caracContainerBorder";
    Cx localCx = new Cx();
    localCx.aJ();
    localCx.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localCx);
    localJg.bb(localCx);
    localCx.brn();
    aAR localaAR1 = aAR.checkOut();
    localaAR1.setElementMap(localcpa);
    localaAR1.setPosition(ajb.dhR);
    localaAR1.setX(548);
    localaAR1.setY(170);
    localaAR1.setWidth(5);
    localaAR1.setHeight(4);
    localaAR1.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR1);
    localaAR1.brn();
    localaAR1.rV();
    aAR localaAR2 = aAR.checkOut();
    localaAR2.setElementMap(localcpa);
    localaAR2.setPosition(ajb.dhT);
    localaAR2.setX(2);
    localaAR2.setY(337);
    localaAR2.setWidth(1);
    localaAR2.setHeight(4);
    localaAR2.setTexture(this.W.aH("default_0.tga"));
    localCx.bb(localaAR2);
    localaAR2.brn();
    localaAR2.rV();
    aAR localaAR3 = aAR.checkOut();
    localaAR3.setElementMap(localcpa);
    localaAR3.setFlipHorizontaly(true);
    localaAR3.setPosition(ajb.dhV);
    localaAR3.setX(548);
    localaAR3.setY(170);
    localaAR3.setWidth(5);
    localaAR3.setHeight(4);
    localaAR3.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR3);
    localaAR3.brn();
    localaAR3.rV();
    aAR localaAR4 = aAR.checkOut();
    localaAR4.setElementMap(localcpa);
    localaAR4.setPosition(ajb.dhY);
    localaAR4.setX(967);
    localaAR4.setY(83);
    localaAR4.setWidth(5);
    localaAR4.setHeight(1);
    localaAR4.setTexture(this.W.aH("default_0.tga"));
    localCx.bb(localaAR4);
    localaAR4.brn();
    localaAR4.rV();
    aAR localaAR5 = aAR.checkOut();
    localaAR5.setElementMap(localcpa);
    localaAR5.setFlipHorizontaly(true);
    localaAR5.setPosition(ajb.dia);
    localaAR5.setX(967);
    localaAR5.setY(83);
    localaAR5.setWidth(5);
    localaAR5.setHeight(1);
    localaAR5.setTexture(this.W.aH("default_0.tga"));
    localCx.bb(localaAR5);
    localaAR5.brn();
    localaAR5.rV();
    aAR localaAR6 = aAR.checkOut();
    localaAR6.setElementMap(localcpa);
    localaAR6.setFlipVerticaly(true);
    localaAR6.setPosition(ajb.did);
    localaAR6.setX(548);
    localaAR6.setY(170);
    localaAR6.setWidth(5);
    localaAR6.setHeight(4);
    localaAR6.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR6);
    localaAR6.brn();
    localaAR6.rV();
    aAR localaAR7 = aAR.checkOut();
    localaAR7.setElementMap(localcpa);
    localaAR7.setFlipVerticaly(true);
    localaAR7.setPosition(ajb.dif);
    localaAR7.setX(2);
    localaAR7.setY(337);
    localaAR7.setWidth(1);
    localaAR7.setHeight(4);
    localaAR7.setTexture(this.W.aH("default_0.tga"));
    localCx.bb(localaAR7);
    localaAR7.brn();
    localaAR7.rV();
    aAR localaAR8 = aAR.checkOut();
    localaAR8.setElementMap(localcpa);
    localaAR8.setFlipHorizontaly(true);
    localaAR8.setFlipVerticaly(true);
    localaAR8.setPosition(ajb.dih);
    localaAR8.setX(548);
    localaAR8.setY(170);
    localaAR8.setWidth(5);
    localaAR8.setHeight(4);
    localaAR8.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR8);
    localaAR8.brn();
    localaAR8.rV();
    localCx.rV();
    String str2 = "caracContainerBackground2";
    aen localaen = aen.checkOut();
    localaen.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localaen);
    localaen.setScaled(true);
    localJg.bb(localaen);
    localaen.brn();
    aAR localaAR9 = aAR.checkOut();
    localaAR9.setElementMap(localcpa);
    localaAR9.setPosition(ajb.dhZ);
    localaAR9.setX(2);
    localaAR9.setY(156);
    localaAR9.setWidth(1);
    localaAR9.setHeight(1);
    localaAR9.setTexture(this.W.aH("default_0.tga"));
    localaen.bb(localaAR9);
    localaAR9.brn();
    localaAR9.rV();
    localaen.rV();
    cAf localcAf = cAf.checkOut();
    localcAf.setElementMap(localcpa);
    localcAf.setColor(new bNa(0.64F, 0.71F, 0.79F, 1.0F));
    localcAf.setDecoratorSwitch(true);
    localcAf.setName("modulation");
    localJg.bb(localcAf);
    localcAf.brn();
    localcAf.rV();
    localJg.rV();
    return localJg;
  }

  public bdj g(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dOc localdOc = (dOc)parambdj;
    Jg localJg = localdOc.getAppearance();
    localJg.setElementMap(localcpa);
    localJg.setState("pressedSelected");
    parambdj.bb(localJg);
    localJg.brn();
    String str1 = "caracContainerBorder";
    Cx localCx = new Cx();
    localCx.aJ();
    localCx.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localCx);
    localJg.bb(localCx);
    localCx.brn();
    aAR localaAR1 = aAR.checkOut();
    localaAR1.setElementMap(localcpa);
    localaAR1.setPosition(ajb.dhR);
    localaAR1.setX(548);
    localaAR1.setY(170);
    localaAR1.setWidth(5);
    localaAR1.setHeight(4);
    localaAR1.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR1);
    localaAR1.brn();
    localaAR1.rV();
    aAR localaAR2 = aAR.checkOut();
    localaAR2.setElementMap(localcpa);
    localaAR2.setPosition(ajb.dhT);
    localaAR2.setX(2);
    localaAR2.setY(337);
    localaAR2.setWidth(1);
    localaAR2.setHeight(4);
    localaAR2.setTexture(this.W.aH("default_0.tga"));
    localCx.bb(localaAR2);
    localaAR2.brn();
    localaAR2.rV();
    aAR localaAR3 = aAR.checkOut();
    localaAR3.setElementMap(localcpa);
    localaAR3.setFlipHorizontaly(true);
    localaAR3.setPosition(ajb.dhV);
    localaAR3.setX(548);
    localaAR3.setY(170);
    localaAR3.setWidth(5);
    localaAR3.setHeight(4);
    localaAR3.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR3);
    localaAR3.brn();
    localaAR3.rV();
    aAR localaAR4 = aAR.checkOut();
    localaAR4.setElementMap(localcpa);
    localaAR4.setPosition(ajb.dhY);
    localaAR4.setX(967);
    localaAR4.setY(83);
    localaAR4.setWidth(5);
    localaAR4.setHeight(1);
    localaAR4.setTexture(this.W.aH("default_0.tga"));
    localCx.bb(localaAR4);
    localaAR4.brn();
    localaAR4.rV();
    aAR localaAR5 = aAR.checkOut();
    localaAR5.setElementMap(localcpa);
    localaAR5.setFlipHorizontaly(true);
    localaAR5.setPosition(ajb.dia);
    localaAR5.setX(967);
    localaAR5.setY(83);
    localaAR5.setWidth(5);
    localaAR5.setHeight(1);
    localaAR5.setTexture(this.W.aH("default_0.tga"));
    localCx.bb(localaAR5);
    localaAR5.brn();
    localaAR5.rV();
    aAR localaAR6 = aAR.checkOut();
    localaAR6.setElementMap(localcpa);
    localaAR6.setFlipVerticaly(true);
    localaAR6.setPosition(ajb.did);
    localaAR6.setX(548);
    localaAR6.setY(170);
    localaAR6.setWidth(5);
    localaAR6.setHeight(4);
    localaAR6.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR6);
    localaAR6.brn();
    localaAR6.rV();
    aAR localaAR7 = aAR.checkOut();
    localaAR7.setElementMap(localcpa);
    localaAR7.setFlipVerticaly(true);
    localaAR7.setPosition(ajb.dif);
    localaAR7.setX(2);
    localaAR7.setY(337);
    localaAR7.setWidth(1);
    localaAR7.setHeight(4);
    localaAR7.setTexture(this.W.aH("default_0.tga"));
    localCx.bb(localaAR7);
    localaAR7.brn();
    localaAR7.rV();
    aAR localaAR8 = aAR.checkOut();
    localaAR8.setElementMap(localcpa);
    localaAR8.setFlipHorizontaly(true);
    localaAR8.setFlipVerticaly(true);
    localaAR8.setPosition(ajb.dih);
    localaAR8.setX(548);
    localaAR8.setY(170);
    localaAR8.setWidth(5);
    localaAR8.setHeight(4);
    localaAR8.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR8);
    localaAR8.brn();
    localaAR8.rV();
    localCx.rV();
    String str2 = "caracContainerBackground2";
    aen localaen = aen.checkOut();
    localaen.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localaen);
    localaen.setScaled(true);
    localJg.bb(localaen);
    localaen.brn();
    aAR localaAR9 = aAR.checkOut();
    localaAR9.setElementMap(localcpa);
    localaAR9.setPosition(ajb.dhZ);
    localaAR9.setX(2);
    localaAR9.setY(156);
    localaAR9.setWidth(1);
    localaAR9.setHeight(1);
    localaAR9.setTexture(this.W.aH("default_0.tga"));
    localaen.bb(localaAR9);
    localaAR9.brn();
    localaAR9.rV();
    localaen.rV();
    cAf localcAf = cAf.checkOut();
    localcAf.setElementMap(localcpa);
    localcAf.setColor(new bNa(0.54F, 0.61F, 0.69F, 1.0F));
    localcAf.setDecoratorSwitch(true);
    localcAf.setName("modulation");
    localJg.bb(localcAf);
    localcAf.brn();
    localcAf.rV();
    localJg.rV();
    return localJg;
  }

  public bdj h(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dOc localdOc = (dOc)parambdj;
    Jg localJg = localdOc.getAppearance();
    localJg.setElementMap(localcpa);
    localJg.setState("disabledSelected");
    parambdj.bb(localJg);
    localJg.brn();
    String str = "caracContainerBorder";
    Cx localCx = new Cx();
    localCx.aJ();
    localCx.setElementMap(localcpa);
    if ((localcpa != null) && (str != null))
      localcpa.a(str, localCx);
    localJg.bb(localCx);
    localCx.brn();
    aAR localaAR1 = aAR.checkOut();
    localaAR1.setElementMap(localcpa);
    localaAR1.setPosition(ajb.dhR);
    localaAR1.setX(548);
    localaAR1.setY(170);
    localaAR1.setWidth(5);
    localaAR1.setHeight(4);
    localaAR1.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR1);
    localaAR1.brn();
    localaAR1.rV();
    aAR localaAR2 = aAR.checkOut();
    localaAR2.setElementMap(localcpa);
    localaAR2.setPosition(ajb.dhT);
    localaAR2.setX(2);
    localaAR2.setY(337);
    localaAR2.setWidth(1);
    localaAR2.setHeight(4);
    localaAR2.setTexture(this.W.aH("default_0.tga"));
    localCx.bb(localaAR2);
    localaAR2.brn();
    localaAR2.rV();
    aAR localaAR3 = aAR.checkOut();
    localaAR3.setElementMap(localcpa);
    localaAR3.setFlipHorizontaly(true);
    localaAR3.setPosition(ajb.dhV);
    localaAR3.setX(548);
    localaAR3.setY(170);
    localaAR3.setWidth(5);
    localaAR3.setHeight(4);
    localaAR3.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR3);
    localaAR3.brn();
    localaAR3.rV();
    aAR localaAR4 = aAR.checkOut();
    localaAR4.setElementMap(localcpa);
    localaAR4.setPosition(ajb.dhY);
    localaAR4.setX(967);
    localaAR4.setY(83);
    localaAR4.setWidth(5);
    localaAR4.setHeight(1);
    localaAR4.setTexture(this.W.aH("default_0.tga"));
    localCx.bb(localaAR4);
    localaAR4.brn();
    localaAR4.rV();
    aAR localaAR5 = aAR.checkOut();
    localaAR5.setElementMap(localcpa);
    localaAR5.setFlipHorizontaly(true);
    localaAR5.setPosition(ajb.dia);
    localaAR5.setX(967);
    localaAR5.setY(83);
    localaAR5.setWidth(5);
    localaAR5.setHeight(1);
    localaAR5.setTexture(this.W.aH("default_0.tga"));
    localCx.bb(localaAR5);
    localaAR5.brn();
    localaAR5.rV();
    aAR localaAR6 = aAR.checkOut();
    localaAR6.setElementMap(localcpa);
    localaAR6.setFlipVerticaly(true);
    localaAR6.setPosition(ajb.did);
    localaAR6.setX(548);
    localaAR6.setY(170);
    localaAR6.setWidth(5);
    localaAR6.setHeight(4);
    localaAR6.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR6);
    localaAR6.brn();
    localaAR6.rV();
    aAR localaAR7 = aAR.checkOut();
    localaAR7.setElementMap(localcpa);
    localaAR7.setFlipVerticaly(true);
    localaAR7.setPosition(ajb.dif);
    localaAR7.setX(2);
    localaAR7.setY(337);
    localaAR7.setWidth(1);
    localaAR7.setHeight(4);
    localaAR7.setTexture(this.W.aH("default_0.tga"));
    localCx.bb(localaAR7);
    localaAR7.brn();
    localaAR7.rV();
    aAR localaAR8 = aAR.checkOut();
    localaAR8.setElementMap(localcpa);
    localaAR8.setFlipHorizontaly(true);
    localaAR8.setFlipVerticaly(true);
    localaAR8.setPosition(ajb.dih);
    localaAR8.setX(548);
    localaAR8.setY(170);
    localaAR8.setWidth(5);
    localaAR8.setHeight(4);
    localaAR8.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR8);
    localaAR8.brn();
    localaAR8.rV();
    localCx.rV();
    cAf localcAf = cAf.checkOut();
    localcAf.setElementMap(localcpa);
    localcAf.setColor(new bNa(0.74F, 0.81F, 0.89F, 0.8F));
    localcAf.setDecoratorSwitch(true);
    localcAf.setName("modulation");
    localJg.bb(localcAf);
    localcAf.brn();
    localcAf.rV();
    localJg.rV();
    return localJg;
  }
}