import java.awt.Insets;
import java.util.Stack;

public class alC
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(100.0F, -2));
    localcwP1.setAlign(ajb.dhT);
    localcwP1.setYOffset(17);
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    crl localcrl = new crl();
    localcrl.aJ();
    localcrl.setHorizontal(true);
    localdRq1.bb(localcrl);
    localcrl.brn();
    localcrl.rV();
    bpn localbpn = new bpn();
    localbpn.aJ();
    localbpn.setElementMap(localcpa);
    localbpn.setUserDefinedPosition(true);
    localbpn.setNonBlocking(true);
    localdRq1.bb(localbpn);
    localbpn.brn();
    cYf localcYf = new cYf();
    localcYf.aJ();
    localcYf.setElementMap(localcpa);
    localcYf.setAlign(aFG.ech);
    localcYf.setInitAlign(aFG.eck);
    localcYf.setInitValue(true);
    localbpn.bb(localcYf);
    localcYf.brn();
    localcYf.rV();
    dqa localdqa = new dqa();
    localdqa.aJ();
    localdqa.setElementMap(localcpa);
    localdqa.setExpandable(false);
    localbpn.bb(localdqa);
    localdqa.brn();
    czO localczO = new czO();
    localczO.aJ();
    localczO.setAdaptToContentSize(true);
    localdqa.bb(localczO);
    localczO.brn();
    localczO.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdqa.bb(localdRq2);
    localdRq2.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localdRq2.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(17, 0, 0, 0));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setStyle("challengeZoneLeft");
    localdRq4.setPrefSize(new Or(280, 56));
    localdRq2.bb(localdRq4);
    localdRq4.brn();
    dRq localdRq5 = localdRq4;
    Jg localJg2 = localdRq5.getAppearance();
    localJg2.setElementMap(localcpa);
    localdRq4.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 38, 0, 0));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(false);
    localaId.setAlign(aFG.ech);
    localdRq4.bb(localaId);
    localaId.brn();
    localaId.rV();
    dRq localdRq6 = localdRq4;
    Jg localJg3 = localdRq6.getAppearance();
    localJg3.setElementMap(localcpa);
    localdRq4.bb(localJg3);
    localJg3.brn();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(0, 18, 0, 12));
    localJg3.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    localJg3.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("StyledBoldWhite12");
    String str1 = "%jail.remainingTime%";
    str1 = str1.replace("%jail.remainingTime%", cBQ.cxL().mL("jail.remainingTime"));
    localcWk1.setText(str1);
    localcWk1.setExpandable(false);
    localcWk1.setNonBlocking(true);
    localcWk1.setPrefSize(new Or(0, 23));
    localdRq4.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg4 = localcWk2.getAppearance();
    localJg4.setElementMap(localcpa);
    ((cwJ)localJg4).setAlign(aFG.eck);
    localcWk1.bb(localJg4);
    localJg4.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 0, 0, 0));
    localJg4.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    cAf localcAf = cAf.checkOut();
    localcAf.setElementMap(localcpa);
    localcAf.setName("text");
    localcAf.setColor(new bNa(1.0F, 1.0F, 1.0F, 1.0F));
    localJg4.bb(localcAf);
    localcAf.brn();
    localcAf.rV();
    localJg4.rV();
    localcWk1.rV();
    cWk localcWk3 = new cWk();
    localcWk3.aJ();
    localcWk3.setElementMap(localcpa);
    localcWk3.setStyle("StyledBold12");
    localcWk3.setExpandable(false);
    localcWk3.setNonBlocking(true);
    localcWk3.setPrefSize(new Or(0, 23));
    localdRq4.bb(localcWk3);
    localcWk3.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("text");
    localNK1.setName("jailFlag");
    localNK1.setField("remainingTime");
    localcWk3.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    cWk localcWk4 = localcWk3;
    Jg localJg5 = localcWk4.getAppearance();
    localJg5.setElementMap(localcpa);
    ((cwJ)localJg5).setAlign(aFG.eck);
    localcWk3.bb(localJg5);
    localJg5.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(0, 0, 0, 0));
    localJg5.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg5.rV();
    localcWk3.rV();
    localdRq4.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localdRq7.setStyle("challengeZoneRight");
    localdRq7.setPrefSize(new Or(0, 56));
    localdRq2.bb(localdRq7);
    localdRq7.brn();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.ech);
    localdRq7.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    dRq localdRq8 = localdRq7;
    Jg localJg6 = localdRq8.getAppearance();
    localJg6.setElementMap(localcpa);
    localdRq7.bb(localJg6);
    localJg6.brn();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(0, 0, 0, 15));
    localJg6.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    localJg6.rV();
    localdRq7.rV();
    localdRq2.rV();
    String str2 = "timerImage";
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localczv1);
    localdqa.bb(localczv1);
    localczv1.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setSize(new Or(-2, -2));
    localcwP3.setAlign(ajb.dhR);
    localcwP3.setYOffset(-13);
    localczv1.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("jailFlag");
    localNK2.setAttribute("style");
    localNK2.setField("lastTimerChange");
    localczv1.bb(localNK2);
    localNK2.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localanQ.setValue("jailTimer");
    localanQ.setElseValue("jailTimerChange");
    localNK2.bb(localanQ);
    localanQ.brn();
    bSP localbSP = new bSP();
    localbSP.aJ();
    localbSP.setElementMap(localcpa);
    localbSP.setValue("0");
    localanQ.bb(localbSP);
    localbSP.brn();
    localbSP.rV();
    localanQ.rV();
    localNK2.rV();
    czv localczv2 = localczv1;
    Jg localJg7 = localczv2.getAppearance();
    localJg7.setElementMap(localcpa);
    localJg7.setShape(bGn.gCC);
    localczv1.bb(localJg7);
    localJg7.brn();
    localJg7.rV();
    localczv1.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("bigTitle");
    localcaF1.setPrefSize(new Or(65, 65));
    localcaF1.setMinWidth(1);
    localcaF1.setMaxWidth(65);
    localcaF1.setEnableAutoZoomShrink(true);
    localdqa.bb(localcaF1);
    localcaF1.brn();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setSize(new Or(-2, -2));
    localcwP4.setAlign(ajb.dhR);
    localcwP4.setYOffset(-13);
    localcaF1.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    caF localcaF2 = localcaF1;
    Jg localJg8 = localcaF2.getAppearance();
    localJg8.setElementMap(localcpa);
    ((cwJ)localJg8).setAlign(aFG.eck);
    ((cwJ)localJg8).setTextColor(new bNa(1.0F, 1.0F, 1.0F, 1.0F));
    localcaF1.bb(localJg8);
    localJg8.brn();
    localJg8.rV();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setName("jailFlag");
    localNK3.setAttribute("text");
    localNK3.setField("formatedLastTimerChange");
    localcaF1.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    localcaF1.rV();
    localdqa.rV();
    localbpn.rV();
    localdRq1.rV();
    return localdRq1;
  }
}