import java.awt.Insets;
import java.util.Stack;

public class ddP
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    dxn localdxn = new dxn();
    localdxn.aJ();
    localdxn.setElementMap(localcpa);
    localdxn.setAlign(aFG.ech);
    localdxn.setYOffset(20);
    localdxn.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(-2, -2));
    localdxn.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setStyle("popup");
    localdxn.bb(localdRq1);
    localdRq1.brn();
    czO localczO1 = new czO();
    localczO1.aJ();
    localczO1.setAdaptToContentSize(true);
    localdRq1.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localdRq2.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localcwP2.setAlign(ajb.dhZ);
    localdRq2.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setNonBlocking(true);
    localcWk1.setStyle("white");
    localcWk1.setEnableShrinking(false);
    localcWk1.setExpandable(false);
    localcWk1.setMinWidth(1);
    localcWk1.setMaxWidth(300);
    localdRq2.bb(localcWk1);
    localcWk1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("text");
    localNK1.setName("overHead");
    localNK1.setField("title");
    localcWk1.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setAttribute("visible");
    localNK2.setName("overHead");
    localNK2.setField("title");
    localcWk1.bb(localNK2);
    localNK2.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localNK2.bb(localanQ1);
    localanQ1.brn();
    anE localanE1 = new anE();
    localanE1.aJ();
    localanE1.setElementMap(localcpa);
    localanQ1.bb(localanE1);
    localanE1.brn();
    localanE1.rV();
    localanQ1.rV();
    localNK2.rV();
    localcWk1.rV();
    at localat1 = new at();
    localat1.aJ();
    localat1.setElementMap(localcpa);
    localat1.setNonBlocking(true);
    localat1.setHorizontal(false);
    localat1.setInnerExpandable(false);
    localat1.setSelectionable(false);
    localat1.setExpandable(false);
    localdRq2.bb(localat1);
    localat1.brn();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa);
    localdpm1.setAlign(aFG.ecl);
    localat1.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    at localat2 = localat1;
    Jg localJg1 = localat2.getAppearance();
    localJg1.setElementMap(localcpa);
    localat1.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 0, 0, 3));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setAttribute("content");
    localNK3.setName("overHead");
    localNK3.setField("overHeadInfos");
    localat1.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa);
    localNK4.setAttribute("visible");
    localNK4.setName("overHead");
    localNK4.setField("overHeadInfos");
    localat1.bb(localNK4);
    localNK4.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localNK4.bb(localanQ2);
    localanQ2.brn();
    anE localanE2 = new anE();
    localanE2.aJ();
    localanE2.setElementMap(localcpa);
    localanQ2.bb(localanE2);
    localanE2.brn();
    localanE2.rV();
    localanQ2.rV();
    localNK4.rV();
    eR localeR1 = new eR();
    localeR1.aJ();
    localeR1.setElementMap(localcpa);
    localat1.bb(localeR1);
    localeR1.brn();
    bxx localbxx1 = new bxx();
    localbxx1.aJ();
    localbxx1.setElementMap(localcpa);
    localeR1.bb(localbxx1);
    localbxx1.brn();
    anQ localanQ3 = new anQ();
    localanQ3.aJ();
    localanQ3.setElementMap(localcpa);
    localbxx1.bb(localanQ3);
    localanQ3.brn();
    anE localanE3 = new anE();
    localanE3.aJ();
    localanE3.setElementMap(localcpa);
    localanQ3.bb(localanE3);
    localanE3.brn();
    localanE3.rV();
    localanQ3.rV();
    localbxx1.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localeR1.bb(localdRq3);
    localdRq3.brn();
    aId localaId2 = aId.checkOut();
    localaId2.setAlign(aFG.ecj);
    localdRq3.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setExpandable(false);
    localczv1.setNonBlocking(true);
    localczv1.setDisplaySize(new Or(32, 32));
    localdRq3.bb(localczv1);
    localczv1.brn();
    czv localczv2 = localczv1;
    Jg localJg2 = localczv2.getAppearance();
    localJg2.setElementMap(localcpa);
    localczv1.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 0, 0, 3));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("visible");
    localaaE1.setField("iconUrl");
    localczv1.bb(localaaE1);
    localaaE1.brn();
    anQ localanQ4 = new anQ();
    localanQ4.aJ();
    localanQ4.setElementMap(localcpa);
    localaaE1.bb(localanQ4);
    localanQ4.brn();
    anE localanE4 = new anE();
    localanE4.aJ();
    localanE4.setElementMap(localcpa);
    localanQ4.bb(localanE4);
    localanE4.brn();
    localanE4.rV();
    localanQ4.rV();
    localaaE1.rV();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setSize(new Or(100.0F, 100.0F));
    localczv1.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    aAR localaAR1 = aAR.checkOut();
    localaAR1.setElementMap(localcpa);
    localczv1.bb(localaAR1);
    localaAR1.brn();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("texture");
    localaaE2.setField("iconUrl");
    localaAR1.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    localaAR1.rV();
    localczv1.rV();
    cWk localcWk2 = new cWk();
    localcWk2.aJ();
    localcWk2.setElementMap(localcpa);
    localcWk2.setNonBlocking(true);
    localcWk2.setStyle("white");
    localcWk2.setEnableShrinking(false);
    localcWk2.setMinWidth(1);
    localcWk2.setMaxWidth(300);
    localdRq3.bb(localcWk2);
    localcWk2.brn();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa);
    localdpm2.setAlign(aFG.eck);
    localcWk2.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    aaE localaaE3 = new aaE();
    localaaE3.aJ();
    localaaE3.setElementMap(localcpa);
    localaaE3.setAttribute("text");
    localaaE3.setField("text");
    localcWk2.bb(localaaE3);
    localaaE3.brn();
    localaaE3.rV();
    localcWk2.rV();
    dAS localdAS = new dAS();
    localdAS.aJ();
    localdAS.setElementMap(localcpa);
    localdRq3.bb(localdAS);
    localdAS.brn();
    localdAS.rV();
    at localat3 = new at();
    localat3.aJ();
    localat3.setElementMap(localcpa);
    localdRq3.bb(localat3);
    localat3.brn();
    aaE localaaE4 = new aaE();
    localaaE4.aJ();
    localaaE4.setElementMap(localcpa);
    localaaE4.setAttribute("visible");
    localaaE4.setField("overIconsUrl");
    localat3.bb(localaaE4);
    localaaE4.brn();
    anQ localanQ5 = new anQ();
    localanQ5.aJ();
    localanQ5.setElementMap(localcpa);
    localaaE4.bb(localanQ5);
    localanQ5.brn();
    anE localanE5 = new anE();
    localanE5.aJ();
    localanE5.setElementMap(localcpa);
    localanQ5.bb(localanE5);
    localanE5.brn();
    localanE5.rV();
    localanQ5.rV();
    localaaE4.rV();
    aaE localaaE5 = new aaE();
    localaaE5.aJ();
    localaaE5.setElementMap(localcpa);
    localaaE5.setAttribute("content");
    localaaE5.setField("overIconsUrl");
    localat3.bb(localaaE5);
    localaaE5.brn();
    localaaE5.rV();
    eR localeR2 = new eR();
    localeR2.aJ();
    localeR2.setElementMap(localcpa);
    localat3.bb(localeR2);
    localeR2.brn();
    bxx localbxx2 = new bxx();
    localbxx2.aJ();
    localbxx2.setElementMap(localcpa);
    localeR2.bb(localbxx2);
    localbxx2.brn();
    anQ localanQ6 = new anQ();
    localanQ6.aJ();
    localanQ6.setElementMap(localcpa);
    localbxx2.bb(localanQ6);
    localanQ6.brn();
    anE localanE6 = new anE();
    localanE6.aJ();
    localanE6.setElementMap(localcpa);
    localanQ6.bb(localanE6);
    localanE6.brn();
    localanE6.rV();
    localanQ6.rV();
    localbxx2.rV();
    czv localczv3 = new czv();
    localczv3.aJ();
    localczv3.setElementMap(localcpa);
    localczv3.setExpandable(false);
    localczv3.setNonBlocking(true);
    localczv3.setDisplaySize(new Or(32, 32));
    localeR2.bb(localczv3);
    localczv3.brn();
    aAR localaAR2 = aAR.checkOut();
    localaAR2.setElementMap(localcpa);
    localczv3.bb(localaAR2);
    localaAR2.brn();
    aaE localaaE6 = new aaE();
    localaaE6.aJ();
    localaaE6.setElementMap(localcpa);
    localaaE6.setAttribute("texture");
    localaAR2.bb(localaaE6);
    localaaE6.brn();
    localaaE6.rV();
    localaAR2.rV();
    localczv3.rV();
    localeR2.rV();
    localat3.rV();
    localdRq3.rV();
    localeR1.rV();
    localat1.rV();
    localdRq2.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setExpandable(false);
    localdRq1.bb(localdRq4);
    localdRq4.brn();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setAlign(ajb.dhV);
    localdRq4.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    NK localNK5 = NK.checkOut();
    localNK5.setElementMap(localcpa);
    localNK5.setAttribute("visible");
    localNK5.setName("overHead");
    localNK5.setField("breedIconUrl");
    localdRq4.bb(localNK5);
    localNK5.brn();
    anQ localanQ7 = new anQ();
    localanQ7.aJ();
    localanQ7.setElementMap(localcpa);
    localNK5.bb(localanQ7);
    localanQ7.brn();
    anE localanE7 = new anE();
    localanE7.aJ();
    localanE7.setElementMap(localcpa);
    localanQ7.bb(localanE7);
    localanE7.brn();
    localanE7.rV();
    localanQ7.rV();
    localNK5.rV();
    czO localczO2 = new czO();
    localczO2.aJ();
    localdRq4.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    czv localczv4 = new czv();
    localczv4.aJ();
    localczv4.setElementMap(localcpa);
    localczv4.setNonBlocking(true);
    localczv4.setExpandable(false);
    localdRq4.bb(localczv4);
    localczv4.brn();
    cwP localcwP5 = new cwP();
    localcwP5.aJ();
    localcwP5.setElementMap(localcpa);
    localcwP5.setAlign(ajb.dhZ);
    localcwP5.setXOffset(-7);
    localcwP5.setYOffset(-1);
    localczv4.bb(localcwP5);
    localcwP5.brn();
    localcwP5.rV();
    czv localczv5 = localczv4;
    Jg localJg3 = localczv5.getAppearance();
    localJg3.setElementMap(localcpa);
    localczv4.bb(localJg3);
    localJg3.brn();
    NK localNK6 = NK.checkOut();
    localNK6.setElementMap(localcpa);
    localNK6.setName("overHead");
    localNK6.setAttribute("modulationColor");
    localNK6.setField("breedIconColor");
    localJg3.bb(localNK6);
    localNK6.brn();
    localNK6.rV();
    localJg3.rV();
    aAR localaAR3 = aAR.checkOut();
    localaAR3.setElementMap(localcpa);
    localczv4.bb(localaAR3);
    localaAR3.brn();
    NK localNK7 = NK.checkOut();
    localNK7.setElementMap(localcpa);
    localNK7.setAttribute("texture");
    localNK7.setName("overHead");
    localNK7.setField("breedIconUrl");
    localaAR3.bb(localNK7);
    localNK7.brn();
    localNK7.rV();
    localaAR3.rV();
    localczv4.rV();
    localdRq4.rV();
    localdRq1.rV();
    localdxn.rV();
    return localdxn;
  }
}