import java.awt.Insets;
import java.util.Stack;

public class cjl
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    String str1 = "mainContainer";
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localdRq1);
    localdRq1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(350, -2));
    localcwP1.setAlign(ajb.dif);
    localcwP1.setYOffset(-200);
    localcwP1.setXOffset(20);
    localcwP1.setResizeOnce(true);
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setAlign(aFG.ecn);
    localaId1.setHorizontal(false);
    localdRq1.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setExpandable(false);
    localdRq2.setPrefSize(new Or(350, 85));
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    czO localczO1 = new czO();
    localczO1.aJ();
    localczO1.setAdaptToContentSize(true);
    localdRq2.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    String str2 = "messageGroup";
    bmG localbmG = new bmG();
    localbmG.aJ();
    localbmG.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localbmG);
    localdRq2.bb(localbmG);
    localbmG.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("value");
    localNK1.setName("currentNotification");
    localbmG.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    localbmG.rV();
    String str3 = "messagesList";
    ccG localccG1 = new ccG();
    localccG1.aJ();
    localccG1.setElementMap(localcpa);
    if ((localcpa != null) && (str3 != null))
      localcpa.a(str3, localccG1);
    localccG1.setAutoIdealSize(true);
    localccG1.setExpandable(false);
    localccG1.setCellSize(new Or(35, 35));
    localccG1.setIdealSizeMinColumns(1);
    localccG1.setIdealSizeMaxColumns(9);
    localdRq2.bb(localccG1);
    localccG1.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.dhV);
    localccG1.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    ccG localccG2 = localccG1;
    Jg localJg1 = localccG2.getAppearance();
    localJg1.setElementMap(localcpa);
    localccG1.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 0, 0, 17));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setAttribute("content");
    localNK2.setName("notificationPanel");
    localccG1.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    eR localeR1 = new eR();
    localeR1.aJ();
    localeR1.setElementMap(localcpa);
    aqC localaqC = new aqC();
    localaqC.hg("wakfu.notificationPanel:selectMessage");
    localeR1.setOnItemClick(localaqC);
    localccG1.bb(localeR1);
    localeR1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localeR1.bb(localanQ1);
    localanQ1.brn();
    bxx localbxx1 = new bxx();
    localbxx1.aJ();
    localbxx1.setElementMap(localcpa);
    localanQ1.bb(localbxx1);
    localbxx1.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localbxx1.bb(localanE);
    localanE.brn();
    localanE.rV();
    localbxx1.rV();
    localanQ1.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localeR1.bb(localdRq3);
    localdRq3.brn();
    czO localczO2 = new czO();
    localczO2.aJ();
    localczO2.setAdaptToContentSize(true);
    localdRq3.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    String str4 = "background";
    aHd localaHd = new aHd();
    localaHd.aJ();
    localaHd.setElementMap(localcpa);
    if ((localcpa != null) && (str4 != null))
      localcpa.a(str4, localaHd);
    localaHd.setGroupId("messageGroup");
    localaHd.setStyle("Tab");
    localaHd.setNonBlocking(false);
    localdRq3.bb(localaHd);
    localaHd.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setAlign(ajb.dhZ);
    localcwP3.setSize(new Or(35, 30));
    localcwP3.setYOffset(4);
    localaHd.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("value");
    localaHd.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    localaHd.rV();
    String str5 = "icon";
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    if ((localcpa != null) && (str5 != null))
      localcpa.a(str5, localczv);
    localczv.setNonBlocking(true);
    localdRq3.bb(localczv);
    localczv.brn();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setAlign(ajb.dhZ);
    localcwP4.setYOffset(1);
    localczv.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("style");
    localaaE2.setField("iconStyle");
    localczv.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    localczv.rV();
    localdRq3.rV();
    localeR1.rV();
    localccG1.rV();
    String str6 = "renderableContainer";
    axU localaxU1 = new axU();
    localaxU1.aJ();
    localaxU1.setElementMap(localcpa);
    if ((localcpa != null) && (str6 != null))
      localcpa.a(str6, localaxU1);
    localaxU1.setExpandable(false);
    bDy localbDy = new bDy();
    localbDy.hg("wakfu.notificationPanel:overMessage");
    localaxU1.setOnMouseEnter(localbDy);
    DY localDY = new DY();
    localDY.hg("wakfu.notificationPanel:outMessage");
    localaxU1.setOnMouseExit(localDY);
    localdRq2.bb(localaxU1);
    localaxU1.brn();
    axU localaxU2 = localaxU1;
    Jg localJg2 = localaxU2.getAppearance();
    localJg2.setElementMap(localcpa);
    localaxU1.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(20, 0, 0, 0));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    cwP localcwP5 = new cwP();
    localcwP5.aJ();
    localcwP5.setElementMap(localcpa);
    localcwP5.setAlign(ajb.dhZ);
    localcwP5.setSize(new Or(100.0F, 100.0F));
    localaxU1.bb(localcwP5);
    localcwP5.brn();
    localcwP5.rV();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setAttribute("content");
    localNK3.setName("currentNotification");
    localaxU1.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    eR localeR2 = new eR();
    localeR2.aJ();
    localeR2.setElementMap(localcpa);
    localaxU1.bb(localeR2);
    localeR2.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localeR2.bb(localanQ2);
    localanQ2.brn();
    bxx localbxx2 = new bxx();
    localbxx2.aJ();
    localbxx2.setElementMap(localcpa);
    localbxx2.setField("type");
    localanQ2.bb(localbxx2);
    localbxx2.brn();
    bSP localbSP1 = new bSP();
    localbSP1.aJ();
    localbSP1.setElementMap(localcpa);
    localbSP1.setValue("0");
    localbxx2.bb(localbSP1);
    localbSP1.brn();
    localbSP1.rV();
    localbxx2.rV();
    localanQ2.rV();
    String str7 = "message";
    avo localavo1 = new avo();
    localavo1.aJ();
    localavo1.setElementMap(localcpa);
    if ((localcpa != null) && (str7 != null))
      localcpa.a(str7, localavo1);
    localeR2.bb(localavo1);
    localavo1.brn();
    aaE localaaE3 = new aaE();
    localaaE3.aJ();
    localaaE3.setElementMap(localcpa);
    localaaE3.setAttribute("value");
    localavo1.bb(localaaE3);
    localaaE3.brn();
    localaaE3.rV();
    localavo1.rV();
    String str8 = "container";
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    if ((localcpa != null) && (str8 != null))
      localcpa.a(str8, localdRq4);
    localdRq4.setStyle("popup");
    localdRq4.setNonBlocking(false);
    csA localcsA1 = new csA();
    localcsA1.hg("wakfu.notificationPanel:forceCycle");
    localdRq4.setOnClick(localcsA1);
    localeR2.bb(localdRq4);
    localdRq4.brn();
    aId localaId2 = aId.checkOut();
    localaId2.setHorizontal(false);
    localaId2.setAlign(aFG.ech);
    localdRq4.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    dRq localdRq5 = dRq.checkOut();
    localdRq5.setElementMap(localcpa);
    localdRq5.setExpandable(false);
    localdRq4.bb(localdRq5);
    localdRq5.brn();
    czO localczO3 = new czO();
    localczO3.aJ();
    localczO3.setAdaptToContentSize(true);
    localdRq5.bb(localczO3);
    localczO3.brn();
    localczO3.rV();
    String str9 = "lineContainer";
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    if ((localcpa != null) && (str9 != null))
      localcpa.a(str9, localdRq6);
    localdRq5.bb(localdRq6);
    localdRq6.brn();
    cwP localcwP6 = new cwP();
    localcwP6.aJ();
    localcwP6.setElementMap(localcpa);
    localcwP6.setAlign(ajb.dif);
    localcwP6.setSize(new Or(100.0F, 1));
    localcwP6.setYOffset(5);
    localdRq6.bb(localcwP6);
    localcwP6.brn();
    localcwP6.rV();
    dRq localdRq7 = localdRq6;
    Jg localJg3 = localdRq7.getAppearance();
    localJg3.setElementMap(localcpa);
    localJg3.setModulationColor(new bNa(1.0F, 1.0F, 1.0F, 1.0F));
    localdRq6.bb(localJg3);
    localJg3.brn();
    ams localams = new ams();
    localams.aJ();
    localams.setElementMap(localcpa);
    localams.setColor(new bNa(1.0F, 1.0F, 1.0F, 1.0F));
    localams.setInsets(new Insets(0, 0, 1, 0));
    localJg3.bb(localams);
    localams.brn();
    localams.rV();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 15, 0, 15));
    localJg3.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg3.rV();
    localdRq6.rV();
    String str10 = "title";
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    if ((localcpa != null) && (str10 != null))
      localcpa.a(str10, localcWk1);
    localcWk1.setStyle("title");
    localcWk1.setExpandable(false);
    localcWk1.setNonBlocking(true);
    localcWk1.setMaxWidth(300);
    localdRq5.bb(localcWk1);
    localcWk1.brn();
    cwP localcwP7 = new cwP();
    localcwP7.aJ();
    localcwP7.setElementMap(localcpa);
    localcwP7.setAlign(ajb.dhZ);
    localcwP7.setSize(new Or(100.0F, 100.0F));
    localcwP7.setYOffset(5);
    localcWk1.bb(localcwP7);
    localcwP7.brn();
    localcwP7.rV();
    cWk localcWk2 = localcWk1;
    Jg localJg4 = localcWk2.getAppearance();
    localJg4.setElementMap(localcpa);
    ((cwJ)localJg4).setAlignment(aFG.ecj);
    localJg4.setModulationColor(new bNa(1.0F, 1.0F, 1.0F, 1.0F));
    localcWk1.bb(localJg4);
    localJg4.brn();
    cAf localcAf1 = cAf.checkOut();
    localcAf1.setElementMap(localcpa);
    localcAf1.setColor(new bNa(0.94F, 0.8F, 0.04F, 1.0F));
    localJg4.bb(localcAf1);
    localcAf1.brn();
    localcAf1.rV();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(0, 40, 0, 0));
    localJg4.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg4.rV();
    aaE localaaE4 = new aaE();
    localaaE4.aJ();
    localaaE4.setElementMap(localcpa);
    localaaE4.setAttribute("text");
    localaaE4.setField("title");
    localcWk1.bb(localaaE4);
    localaaE4.brn();
    localaaE4.rV();
    localcWk1.rV();
    localdRq5.rV();
    String str11 = "text";
    cWk localcWk3 = new cWk();
    localcWk3.aJ();
    localcWk3.setElementMap(localcpa);
    if ((localcpa != null) && (str11 != null))
      localcpa.a(str11, localcWk3);
    localcWk3.setStyle("smallTitle");
    localcWk3.setExpandable(false);
    localcWk3.setEnableOnlySelectablePartInteraction(true);
    localcWk3.setNonBlocking(true);
    localcWk3.setMinWidth(280);
    localcWk3.setMaxWidth(280);
    localcWk3.setMaxSize(new Or(280, 75));
    csA localcsA2 = new csA();
    localcsA2.hg("wakfu.notificationPanel:gotoNotificationLink(message)");
    localcWk3.setOnClick(localcsA2);
    cCu localcCu = new cCu();
    localcCu.hg("wakfu.notificationPanel:gotoNotificationLinkTooltip(rightClickPopup)");
    localcWk3.setOnPopupDisplay(localcCu);
    jL localjL = new jL();
    localjL.hg("closePopup");
    localcWk3.setOnPopupHide(localjL);
    localdRq4.bb(localcWk3);
    localcWk3.brn();
    String str12 = "rightClickPopup";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa);
    if ((localcpa != null) && (str12 != null))
      localcpa.a(str12, localanG);
    localanG.setAlign(aFG.ecl);
    localanG.setHotSpotPosition(aFG.ecj);
    localcWk3.bb(localanG);
    localanG.brn();
    dRq localdRq8 = dRq.checkOut();
    localdRq8.setElementMap(localcpa);
    localdRq8.setPrefSize(new Or(10, 0));
    localdRq8.setStyle("popup");
    localanG.bb(localdRq8);
    localdRq8.brn();
    cWk localcWk4 = new cWk();
    localcWk4.aJ();
    localcWk4.setElementMap(localcpa);
    localcWk4.setStyle("white11");
    localcWk4.setMultiline(false);
    localcWk4.setExpandable(false);
    String str13 = "%rightClickToOpenLinkedDialog%";
    str13 = str13.replace("%rightClickToOpenLinkedDialog%", cBQ.cxL().mL("rightClickToOpenLinkedDialog"));
    localcWk4.setText(str13);
    localdRq8.bb(localcWk4);
    localcWk4.brn();
    localcWk4.rV();
    localdRq8.rV();
    localanG.rV();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.eck);
    localcWk3.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    cWk localcWk5 = localcWk3;
    Jg localJg5 = localcWk5.getAppearance();
    localJg5.setElementMap(localcpa);
    ((cwJ)localJg5).setAlignment(aFG.ecj);
    localJg5.setModulationColor(new bNa(1.0F, 1.0F, 1.0F, 1.0F));
    localcWk3.bb(localJg5);
    localJg5.brn();
    cAf localcAf2 = cAf.checkOut();
    localcAf2.setElementMap(localcpa);
    localcAf2.setColor(new bNa(1.0F, 1.0F, 1.0F, 1.0F));
    localJg5.bb(localcAf2);
    localcAf2.brn();
    localcAf2.rV();
    localJg5.rV();
    aaE localaaE5 = new aaE();
    localaaE5.aJ();
    localaaE5.setElementMap(localcpa);
    localaaE5.setAttribute("text");
    localaaE5.setField("text");
    localcWk3.bb(localaaE5);
    localaaE5.brn();
    localaaE5.rV();
    localcWk3.rV();
    localdRq4.rV();
    localeR2.rV();
    eR localeR3 = new eR();
    localeR3.aJ();
    localeR3.setElementMap(localcpa);
    localaxU1.bb(localeR3);
    localeR3.brn();
    anQ localanQ3 = new anQ();
    localanQ3.aJ();
    localanQ3.setElementMap(localcpa);
    localeR3.bb(localanQ3);
    localanQ3.brn();
    bxx localbxx3 = new bxx();
    localbxx3.aJ();
    localbxx3.setElementMap(localcpa);
    localbxx3.setField("type");
    localanQ3.bb(localbxx3);
    localbxx3.brn();
    bSP localbSP2 = new bSP();
    localbSP2.aJ();
    localbSP2.setElementMap(localcpa);
    localbSP2.setValue("2");
    localbxx3.bb(localbSP2);
    localbSP2.brn();
    localbSP2.rV();
    localbxx3.rV();
    localanQ3.rV();
    String str14 = "message";
    avo localavo2 = new avo();
    localavo2.aJ();
    localavo2.setElementMap(localcpa);
    if ((localcpa != null) && (str14 != null))
      localcpa.a(str14, localavo2);
    localeR3.bb(localavo2);
    localavo2.brn();
    a(localavo2);
    localavo2.rV();
    b(localeR3);
    localeR3.rV();
    d(localaxU1);
    localaxU1.rV();
    localdRq2.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj a(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    aaE localaaE = new aaE();
    localaaE.aJ();
    localaaE.setElementMap(localcpa);
    localaaE.setAttribute("value");
    parambdj.bb(localaaE);
    localaaE.brn();
    localaaE.rV();
    return localaaE;
  }

  public bdj b(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    String str1 = "container";
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localdRq1);
    localdRq1.setStyle("popup");
    localdRq1.setNonBlocking(false);
    csA localcsA = new csA();
    localcsA.hg("wakfu.notificationPanel:forceCycle");
    localdRq1.setOnClick(localcsA);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(false);
    localaId.setAlign(aFG.ech);
    localdRq1.bb(localaId);
    localaId.brn();
    localaId.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setExpandable(false);
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    czO localczO = new czO();
    localczO.aJ();
    localczO.setAdaptToContentSize(true);
    localdRq2.bb(localczO);
    localczO.brn();
    localczO.rV();
    String str2 = "lineContainer";
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localdRq3);
    localdRq2.bb(localdRq3);
    localdRq3.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setAlign(ajb.dif);
    localcwP1.setSize(new Or(100.0F, 1));
    localcwP1.setYOffset(5);
    localdRq3.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    dRq localdRq4 = localdRq3;
    Jg localJg1 = localdRq4.getAppearance();
    localJg1.setElementMap(localcpa);
    localJg1.setModulationColor(new bNa(1.0F, 1.0F, 1.0F, 1.0F));
    localdRq3.bb(localJg1);
    localJg1.brn();
    ams localams = new ams();
    localams.aJ();
    localams.setElementMap(localcpa);
    localams.setColor(new bNa(1.0F, 1.0F, 1.0F, 1.0F));
    localams.setInsets(new Insets(0, 0, 1, 0));
    localJg1.bb(localams);
    localams.brn();
    localams.rV();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 15, 0, 15));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    localdRq3.rV();
    String str3 = "title";
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    if ((localcpa != null) && (str3 != null))
      localcpa.a(str3, localcWk1);
    localcWk1.setStyle("title");
    localcWk1.setExpandable(false);
    localcWk1.setNonBlocking(true);
    localcWk1.setMaxWidth(300);
    localdRq2.bb(localcWk1);
    localcWk1.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.dhZ);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localcwP2.setYOffset(5);
    localcWk1.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    cWk localcWk2 = localcWk1;
    Jg localJg2 = localcWk2.getAppearance();
    localJg2.setElementMap(localcpa);
    ((cwJ)localJg2).setAlignment(aFG.ecj);
    localJg2.setModulationColor(new bNa(1.0F, 1.0F, 1.0F, 1.0F));
    localcWk1.bb(localJg2);
    localJg2.brn();
    cAf localcAf = cAf.checkOut();
    localcAf.setElementMap(localcpa);
    localcAf.setColor(new bNa(0.94F, 0.8F, 0.04F, 1.0F));
    localJg2.bb(localcAf);
    localcAf.brn();
    localcAf.rV();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 40, 0, 0));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    aaE localaaE = new aaE();
    localaaE.aJ();
    localaaE.setElementMap(localcpa);
    localaaE.setAttribute("text");
    localaaE.setField("title");
    localcWk1.bb(localaaE);
    localaaE.brn();
    localaaE.rV();
    localcWk1.rV();
    localdRq2.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj d(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    eR localeR1 = new eR();
    localeR1.aJ();
    localeR1.setElementMap(localcpa);
    parambdj.bb(localeR1);
    localeR1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localeR1.bb(localanQ1);
    localanQ1.brn();
    bxx localbxx1 = new bxx();
    localbxx1.aJ();
    localbxx1.setElementMap(localcpa);
    localbxx1.setField("type");
    localanQ1.bb(localbxx1);
    localbxx1.brn();
    bSP localbSP = new bSP();
    localbSP.aJ();
    localbSP.setElementMap(localcpa);
    localbSP.setValue("1");
    localbxx1.bb(localbSP);
    localbSP.brn();
    localbSP.rV();
    localbxx1.rV();
    localanQ1.rV();
    String str1 = "message";
    avo localavo = new avo();
    localavo.aJ();
    localavo.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localavo);
    localeR1.bb(localavo);
    localavo.brn();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("value");
    localavo.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    localavo.rV();
    String str2 = "container";
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localdRq1);
    localdRq1.setStyle("popup");
    localdRq1.setNonBlocking(false);
    csA localcsA = new csA();
    localcsA.hg("wakfu.notificationPanel:forceCycle");
    localdRq1.setOnClick(localcsA);
    localeR1.bb(localdRq1);
    localdRq1.brn();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(false);
    localaId.setAlign(aFG.ech);
    localdRq1.bb(localaId);
    localaId.brn();
    localaId.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setExpandable(false);
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    czO localczO1 = new czO();
    localczO1.aJ();
    localczO1.setAdaptToContentSize(true);
    localdRq2.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    String str3 = "lineContainer";
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    if ((localcpa != null) && (str3 != null))
      localcpa.a(str3, localdRq3);
    localdRq2.bb(localdRq3);
    localdRq3.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setAlign(ajb.dif);
    localcwP1.setSize(new Or(100.0F, 1));
    localcwP1.setYOffset(5);
    localdRq3.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    dRq localdRq4 = localdRq3;
    Jg localJg1 = localdRq4.getAppearance();
    localJg1.setElementMap(localcpa);
    localJg1.setModulationColor(new bNa(1.0F, 1.0F, 1.0F, 1.0F));
    localdRq3.bb(localJg1);
    localJg1.brn();
    ams localams = new ams();
    localams.aJ();
    localams.setElementMap(localcpa);
    localams.setColor(new bNa(1.0F, 1.0F, 1.0F, 1.0F));
    localams.setInsets(new Insets(0, 0, 1, 0));
    localJg1.bb(localams);
    localams.brn();
    localams.rV();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 15, 0, 15));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    localdRq3.rV();
    String str4 = "title";
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    if ((localcpa != null) && (str4 != null))
      localcpa.a(str4, localcWk1);
    localcWk1.setStyle("styledBoldDark12");
    localcWk1.setExpandable(false);
    localcWk1.setNonBlocking(true);
    localcWk1.setMinWidth(1);
    localcWk1.setMaxWidth(300);
    localdRq2.bb(localcWk1);
    localcWk1.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.dhZ);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localcwP2.setYOffset(5);
    localcWk1.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    cWk localcWk2 = localcWk1;
    Jg localJg2 = localcWk2.getAppearance();
    localJg2.setElementMap(localcpa);
    ((cwJ)localJg2).setAlignment(aFG.ecj);
    localJg2.setModulationColor(new bNa(1.0F, 1.0F, 1.0F, 1.0F));
    localcWk1.bb(localJg2);
    localJg2.brn();
    cAf localcAf1 = cAf.checkOut();
    localcAf1.setElementMap(localcpa);
    localcAf1.setColor(new bNa(0.94F, 0.8F, 0.04F, 1.0F));
    localJg2.bb(localcAf1);
    localcAf1.brn();
    localcAf1.rV();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 40, 0, 0));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("text");
    localaaE2.setField("title");
    localcWk1.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    localcWk1.rV();
    localdRq2.rV();
    ccG localccG = new ccG();
    localccG.aJ();
    localccG.setElementMap(localcpa);
    localccG.setCellSize(new Or(32, 32));
    localccG.setExpandable(false);
    localccG.setAutoIdealSize(true);
    localccG.setIdealSizeMinColumns(6);
    localccG.setIdealSizeMaxColumns(6);
    localdRq1.bb(localccG);
    localccG.brn();
    aaE localaaE3 = new aaE();
    localaaE3.aJ();
    localaaE3.setElementMap(localcpa);
    localaaE3.setField("rewards");
    localaaE3.setAttribute("content");
    localccG.bb(localaaE3);
    localaaE3.brn();
    localaaE3.rV();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.eck);
    localccG.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    eR localeR2 = new eR();
    localeR2.aJ();
    localeR2.setElementMap(localcpa);
    aqC localaqC = new aqC();
    localaqC.hg("wakfu:openItemDetailWindow()");
    localeR2.setOnItemClick(localaqC);
    localccG.bb(localeR2);
    localeR2.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localeR2.bb(localanQ2);
    localanQ2.brn();
    bxx localbxx2 = new bxx();
    localbxx2.aJ();
    localbxx2.setElementMap(localcpa);
    localanQ2.bb(localbxx2);
    localbxx2.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localbxx2.bb(localanE);
    localanE.brn();
    localanE.rV();
    localbxx2.rV();
    localanQ2.rV();
    dRq localdRq5 = dRq.checkOut();
    localdRq5.setElementMap(localcpa);
    cCu localcCu = new cCu();
    localcCu.hg("popup(rewardDetailPopup)");
    localdRq5.setOnPopupDisplay(localcCu);
    jL localjL = new jL();
    localjL.hg("closePopup");
    localdRq5.setOnPopupHide(localjL);
    localeR2.bb(localdRq5);
    localdRq5.brn();
    czO localczO2 = new czO();
    localczO2.aJ();
    localczO2.setAdaptToContentSize(true);
    localdRq5.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    String str5 = "imageBG";
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    if ((localcpa != null) && (str5 != null))
      localcpa.a(str5, localczv1);
    localczv1.setStyle("IconEmptyEmote");
    localczv1.setDisplaySize(new Or(32, 32));
    localdRq5.bb(localczv1);
    localczv1.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setSize(new Or(-2, -2));
    localcwP3.setAlign(ajb.dhZ);
    localczv1.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    localczv1.rV();
    String str6 = "image";
    czv localczv2 = new czv();
    localczv2.aJ();
    localczv2.setElementMap(localcpa);
    if ((localcpa != null) && (str6 != null))
      localcpa.a(str6, localczv2);
    localczv2.setDisplaySize(new Or(32, 32));
    localdRq5.bb(localczv2);
    localczv2.brn();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setAlign(ajb.dhZ);
    localcwP4.setSize(new Or(-2, -2));
    localczv2.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv2.bb(localaAR);
    localaAR.brn();
    aaE localaaE4 = new aaE();
    localaaE4.aJ();
    localaaE4.setElementMap(localcpa);
    localaaE4.setAttribute("texture");
    localaaE4.setField("iconUrl");
    localaAR.bb(localaaE4);
    localaaE4.brn();
    localaaE4.rV();
    localaAR.rV();
    localczv2.rV();
    String str7 = "quantityLabel";
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    if ((localcpa != null) && (str7 != null))
      localcpa.a(str7, localcaF1);
    localcaF1.setStyle("bold");
    localdRq5.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg3 = localcaF2.getAppearance();
    localJg3.setElementMap(localcpa);
    localcaF1.bb(localJg3);
    localJg3.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(5, 5, 5, 5));
    localJg3.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    cAf localcAf2 = cAf.checkOut();
    localcAf2.setElementMap(localcpa);
    localcAf2.setColor(new bNa(0.29F, 0.17F, 0.07F, 1.0F));
    localcAf2.setName("text");
    localJg3.bb(localcAf2);
    localcAf2.brn();
    localcAf2.rV();
    localJg3.rV();
    cwP localcwP5 = new cwP();
    localcwP5.aJ();
    localcwP5.setElementMap(localcpa);
    localcwP5.setSize(new Or(-2, -2));
    localcwP5.setAlign(ajb.dih);
    localcaF1.bb(localcwP5);
    localcwP5.brn();
    localcwP5.rV();
    aaE localaaE5 = new aaE();
    localaaE5.aJ();
    localaaE5.setElementMap(localcpa);
    localaaE5.setAttribute("text");
    localaaE5.setField("quantity");
    localcaF1.bb(localaaE5);
    localaaE5.brn();
    localaaE5.rV();
    aaE localaaE6 = new aaE();
    localaaE6.aJ();
    localaaE6.setElementMap(localcpa);
    localaaE6.setAttribute("visible");
    localaaE6.setField("quantity");
    localcaF1.bb(localaaE6);
    localaaE6.brn();
    anQ localanQ3 = new anQ();
    localanQ3.aJ();
    localanQ3.setElementMap(localcpa);
    localaaE6.bb(localanQ3);
    localanQ3.brn();
    aEJ localaEJ = new aEJ();
    localaEJ.aJ();
    localaEJ.setElementMap(localcpa);
    localaEJ.setValue("1");
    localanQ3.bb(localaEJ);
    localaEJ.brn();
    localaEJ.rV();
    localanQ3.rV();
    localaaE6.rV();
    localcaF1.rV();
    String str8 = "rewardDetailPopup";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa);
    if ((localcpa != null) && (str8 != null))
      localcpa.a(str8, localanG);
    localanG.setAlign(aFG.ech);
    localanG.setHotSpotPosition(aFG.ecn);
    localdRq5.bb(localanG);
    localanG.brn();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq6.setPrefSize(new Or(10, 0));
    localdRq6.setStyle("popup");
    localanG.bb(localdRq6);
    localdRq6.brn();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setStyle("11");
    localdRq6.bb(localcaF3);
    localcaF3.brn();
    caF localcaF4 = localcaF3;
    Jg localJg4 = localcaF4.getAppearance();
    localJg4.setElementMap(localcpa);
    ((cwJ)localJg4).setAlign(aFG.ecj);
    localcaF3.bb(localJg4);
    localJg4.brn();
    cAf localcAf3 = cAf.checkOut();
    localcAf3.setElementMap(localcpa);
    localcAf3.setColor(new bNa(1.0F, 1.0F, 1.0F, 1.0F));
    localJg4.bb(localcAf3);
    localcAf3.brn();
    localcAf3.rV();
    localJg4.rV();
    aaE localaaE7 = new aaE();
    localaaE7.aJ();
    localaaE7.setElementMap(localcpa);
    localaaE7.setAttribute("text");
    localaaE7.setField("description");
    localcaF3.bb(localaaE7);
    localaaE7.brn();
    localaaE7.rV();
    localcaF3.rV();
    localdRq6.rV();
    localanG.rV();
    localdRq5.rV();
    localeR2.rV();
    localccG.rV();
    localdRq1.rV();
    localeR1.rV();
    return localeR1;
  }
}