import java.util.Stack;

public class dfg
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    String str1 = "window";
    bpn localbpn1 = new bpn();
    localbpn1.aJ();
    localbpn1.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localbpn1);
    localbpn1.setNonBlocking(true);
    localbpn1.setPack(true);
    localbpn1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("visible");
    localNK1.setName("miniMap");
    localNK1.setField("isMapAvailable");
    localbpn1.bb(localNK1);
    localNK1.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localNK1.bb(localanQ);
    localanQ.brn();
    bJJ localbJJ = new bJJ();
    localbJJ.aJ();
    localbJJ.setElementMap(localcpa);
    localanQ.bb(localbJJ);
    localbJJ.brn();
    cOk localcOk1 = new cOk();
    localcOk1.aJ();
    localcOk1.setElementMap(localcpa);
    localbJJ.bb(localcOk1);
    localcOk1.brn();
    localcOk1.rV();
    cOk localcOk2 = new cOk();
    localcOk2.aJ();
    localcOk2.setElementMap(localcpa);
    localbJJ.bb(localcOk2);
    localcOk2.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("gamePreferences");
    localNK2.setField("minimapEnable");
    localNK2.setAttribute("comparedValue");
    localcOk2.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localcOk2.rV();
    bqW localbqW = new bqW();
    localbqW.aJ();
    localbqW.setElementMap(localcpa);
    localbJJ.bb(localbqW);
    localbqW.brn();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setName("isInFight");
    localNK3.setAttribute("comparedValue");
    localbqW.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    localbqW.rV();
    localbJJ.rV();
    localanQ.rV();
    localNK1.rV();
    bpn localbpn2 = localbpn1;
    Jg localJg1 = localbpn2.getAppearance();
    localJg1.setElementMap(localcpa);
    localJg1.setShape(bGn.gCA);
    localbpn1.bb(localJg1);
    localJg1.brn();
    localJg1.rV();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setAlign(ajb.dhV);
    localcwP1.setXOffset(-10);
    localcwP1.setYOffset(-85);
    localcwP1.setSize(new Or(-2, -2));
    localcwP1.setInitValue(true);
    localbpn1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    czO localczO1 = new czO();
    localczO1.aJ();
    localczO1.setAdaptToContentSize(true);
    localbpn1.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setNeedsScissor(true);
    localbpn1.bb(localdRq1);
    localdRq1.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setSize(new Or(130, 130));
    localcwP2.setX(13);
    localcwP2.setY(10);
    localdRq1.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    String str2 = "navigator";
    gQ localgQ1 = new gQ();
    localgQ1.aJ();
    localgQ1.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localgQ1);
    localgQ1.setNeedsScissor(true);
    localgQ1.setEnableTooltip(false);
    localgQ1.setLandMarkZoom(0.75F);
    localgQ1.setMaxZoom(0.065F);
    localgQ1.setMinZoom(0.065F);
    localgQ1.setIsoMap(true);
    localgQ1.setCursorType(duv.lyl);
    vT localvT = new vT();
    localvT.hg("wakfu.controlCenter:radarZoom");
    localgQ1.setOnMouseWheel(localvT);
    anx localanx = new anx();
    localanx.hg("wakfu.controlCenter:onMiniMapItemOver");
    localgQ1.setOnItemOver(localanx);
    cVk localcVk = new cVk();
    localcVk.hg("wakfu.controlCenter:onMiniMapItemOut");
    localgQ1.setOnItemOut(localcVk);
    localdRq1.bb(localgQ1);
    localgQ1.brn();
    gQ localgQ2 = localgQ1;
    Jg localJg2 = localgQ2.getAppearance();
    localJg2.setElementMap(localcpa);
    localgQ1.bb(localJg2);
    localJg2.brn();
    jO localjO = new jO();
    localjO.aJ();
    localjO.setElementMap(localcpa);
    localJg2.bb(localjO);
    localjO.brn();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa);
    localNK4.setAttribute("color");
    localNK4.setName("miniMap");
    localNK4.setField("bgColor");
    localjO.bb(localNK4);
    localNK4.brn();
    localNK4.rV();
    localjO.rV();
    localJg2.rV();
    NK localNK5 = NK.checkOut();
    localNK5.setElementMap(localcpa);
    localNK5.setAttribute("mapPath");
    localNK5.setName("miniMap");
    localNK5.setField("map");
    localgQ1.bb(localNK5);
    localNK5.brn();
    localNK5.rV();
    NK localNK6 = NK.checkOut();
    localNK6.setElementMap(localcpa);
    localNK6.setAttribute("content");
    localNK6.setName("miniMap");
    localNK6.setField("points");
    localgQ1.bb(localNK6);
    localNK6.brn();
    localNK6.rV();
    NK localNK7 = NK.checkOut();
    localNK7.setElementMap(localcpa);
    localNK7.setAttribute("compassContent");
    localNK7.setName("miniMap");
    localNK7.setField("compass");
    localgQ1.bb(localNK7);
    localNK7.brn();
    localNK7.rV();
    NK localNK8 = NK.checkOut();
    localNK8.setElementMap(localcpa);
    localNK8.setAttribute("isoCenterX");
    localNK8.setName("miniMap");
    localNK8.setField("centerX");
    localgQ1.bb(localNK8);
    localNK8.brn();
    localNK8.rV();
    NK localNK9 = NK.checkOut();
    localNK9.setElementMap(localcpa);
    localNK9.setAttribute("isoCenterY");
    localNK9.setName("miniMap");
    localNK9.setField("centerY");
    localgQ1.bb(localNK9);
    localNK9.brn();
    localNK9.rV();
    NK localNK10 = NK.checkOut();
    localNK10.setElementMap(localcpa);
    localNK10.setAttribute("isoCenterZ");
    localNK10.setName("miniMap");
    localNK10.setField("centerZ");
    localgQ1.bb(localNK10);
    localNK10.brn();
    localNK10.rV();
    localgQ1.rV();
    localdRq1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setStyle("minimapShadow");
    localbpn1.bb(localdRq2);
    localdRq2.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setSize(new Or(130, 130));
    localcwP3.setX(13);
    localcwP3.setY(10);
    localdRq2.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    localdRq2.rV();
    String str3 = "background";
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    if ((localcpa != null) && (str3 != null))
      localcpa.a(str3, localdRq3);
    localdRq3.setStyle("minimapDecorator");
    localbpn1.bb(localdRq3);
    localdRq3.brn();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setSize(new Or(150, 150));
    localdRq3.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    localdRq3.rV();
    dqa localdqa1 = new dqa();
    localdqa1.aJ();
    localdqa1.setElementMap(localcpa);
    localbpn1.bb(localdqa1);
    localdqa1.brn();
    dqa localdqa2 = localdqa1;
    Jg localJg3 = localdqa2.getAppearance();
    localJg3.setElementMap(localcpa);
    localJg3.setShape(bGn.gCA);
    localdqa1.bb(localJg3);
    localJg3.brn();
    localJg3.rV();
    cwP localcwP5 = new cwP();
    localcwP5.aJ();
    localcwP5.setElementMap(localcpa);
    localcwP5.setAlign(ajb.dif);
    localcwP5.setSize(new Or(150, 15));
    localcwP5.setYOffset(5);
    localdqa1.bb(localcwP5);
    localcwP5.brn();
    localcwP5.rV();
    localdqa1.rV();
    dqa localdqa3 = new dqa();
    localdqa3.aJ();
    localdqa3.setElementMap(localcpa);
    localbpn1.bb(localdqa3);
    localdqa3.brn();
    dqa localdqa4 = localdqa3;
    Jg localJg4 = localdqa4.getAppearance();
    localJg4.setElementMap(localcpa);
    localJg4.setShape(bGn.gCA);
    localdqa3.bb(localJg4);
    localJg4.brn();
    localJg4.rV();
    cwP localcwP6 = new cwP();
    localcwP6.aJ();
    localcwP6.setElementMap(localcpa);
    localcwP6.setAlign(ajb.dhT);
    localcwP6.setSize(new Or(150, 15));
    localcwP6.setYOffset(-5);
    localdqa3.bb(localcwP6);
    localcwP6.brn();
    localcwP6.rV();
    czO localczO2 = new czO();
    localczO2.aJ();
    localdqa3.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    localdqa3.rV();
    dqa localdqa5 = new dqa();
    localdqa5.aJ();
    localdqa5.setElementMap(localcpa);
    localbpn1.bb(localdqa5);
    localdqa5.brn();
    dqa localdqa6 = localdqa5;
    Jg localJg5 = localdqa6.getAppearance();
    localJg5.setElementMap(localcpa);
    localJg5.setShape(bGn.gCA);
    localdqa5.bb(localJg5);
    localJg5.brn();
    localJg5.rV();
    cwP localcwP7 = new cwP();
    localcwP7.aJ();
    localcwP7.setElementMap(localcpa);
    localcwP7.setAlign(ajb.dia);
    localcwP7.setSize(new Or(15, 150));
    localcwP7.setXOffset(-5);
    localdqa5.bb(localcwP7);
    localcwP7.brn();
    localcwP7.rV();
    czO localczO3 = new czO();
    localczO3.aJ();
    localdqa5.bb(localczO3);
    localczO3.brn();
    localczO3.rV();
    localdqa5.rV();
    dqa localdqa7 = new dqa();
    localdqa7.aJ();
    localdqa7.setElementMap(localcpa);
    localbpn1.bb(localdqa7);
    localdqa7.brn();
    dqa localdqa8 = localdqa7;
    Jg localJg6 = localdqa8.getAppearance();
    localJg6.setElementMap(localcpa);
    localJg6.setShape(bGn.gCA);
    localdqa7.bb(localJg6);
    localJg6.brn();
    localJg6.rV();
    cwP localcwP8 = new cwP();
    localcwP8.aJ();
    localcwP8.setElementMap(localcpa);
    localcwP8.setAlign(ajb.dhY);
    localcwP8.setSize(new Or(15, 150));
    localcwP8.setXOffset(5);
    localdqa7.bb(localcwP8);
    localcwP8.brn();
    localcwP8.rV();
    czO localczO4 = new czO();
    localczO4.aJ();
    localdqa7.bb(localczO4);
    localczO4.brn();
    localczO4.rV();
    localdqa7.rV();
    localbpn1.rV();
    return localbpn1;
  }
}