import java.awt.Insets;
import java.util.Stack;

public class Jc
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    bpn localbpn = new bpn();
    localbpn.aJ();
    localbpn.setElementMap(localcpa);
    localbpn.setPack(true);
    localbpn.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setInitValue(true);
    localcwP1.setAlign(ajb.dhR);
    localcwP1.setSize(new Or(-2, -2));
    localcwP1.setXOffset(340);
    localbpn.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setStyle("popup");
    localbpn.bb(localdRq1);
    localdRq1.brn();
    czO localczO1 = new czO();
    localczO1.aJ();
    localczO1.setAdaptToContentSize(true);
    localdRq1.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    dqa localdqa = new dqa();
    localdqa.aJ();
    localdqa.setElementMap(localcpa);
    localdRq1.bb(localdqa);
    localdqa.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.dhZ);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localdqa.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    czO localczO2 = new czO();
    localczO2.aJ();
    localczO2.setAdaptToContentSize(true);
    localdqa.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setNonBlocking(true);
    localdqa.bb(localdRq2);
    localdRq2.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setAlign(ajb.dhZ);
    localcwP3.setSize(new Or(100.0F, 100.0F));
    localdRq2.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq3.setNonBlocking(true);
    localdRq2.bb(localdRq3);
    localdRq3.brn();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(true);
    localdRq3.bb(localaId);
    localaId.brn();
    localaId.rV();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setNonBlocking(true);
    localczv.setDisplaySize(new Or(48, 48));
    localczv.setExpandable(false);
    localdRq3.bb(localczv);
    localczv.brn();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa);
    localdpm1.setAlign(aFG.eck);
    localczv.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv.bb(localaAR);
    localaAR.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("texture");
    localNK1.setName("weather.manager");
    localNK1.setField("currentWeather/iconUrl");
    localaAR.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    localaAR.rV();
    localczv.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setNonBlocking(true);
    localcaF1.setStyle("defaultBold22");
    localcaF1.setExpandable(false);
    localdRq3.bb(localcaF1);
    localcaF1.brn();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa);
    localdpm2.setAlign(aFG.eck);
    localcaF1.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    caF localcaF2 = localcaF1;
    Jg localJg = localcaF2.getAppearance();
    localJg.setElementMap(localcpa);
    localcaF1.bb(localJg);
    localJg.brn();
    cAf localcAf = cAf.checkOut();
    localcAf.setElementMap(localcpa);
    localcAf.setName("text");
    localcAf.setColor(new bNa(1.0F, 1.0F, 1.0F, 1.0F));
    localJg.bb(localcAf);
    localcAf.brn();
    localcAf.rV();
    ams localams = new ams();
    localams.aJ();
    localams.setElementMap(localcpa);
    localams.setInsets(new Insets(0, 1, 0, 0));
    localams.setColor(new bNa(0.8F, 0.8F, 0.8F, 0.3F));
    localJg.bb(localams);
    localams.brn();
    localams.rV();
    cuR localcuR = new cuR();
    localcuR.aJ();
    localcuR.setElementMap(localcpa);
    localcuR.setInsets(new Insets(0, 3, 0, 0));
    localJg.bb(localcuR);
    localcuR.brn();
    localcuR.rV();
    localJg.rV();
    dpm localdpm3 = new dpm();
    localdpm3.aJ();
    localdpm3.setElementMap(localcpa);
    localdpm3.setAlign(aFG.eck);
    localcaF1.bb(localdpm3);
    localdpm3.brn();
    localdpm3.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setAttribute("text");
    localNK2.setName("weather.manager");
    localNK2.setField("currentWeather/currentTemperature");
    localcaF1.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localcaF1.rV();
    localdRq3.rV();
    localdRq2.rV();
    biy localbiy = new biy();
    localbiy.aJ();
    localbiy.setElementMap(localcpa);
    localbiy.setStyle("close");
    localbiy.setExpandable(false);
    localbiy.setNonBlocking(false);
    csA localcsA = new csA();
    localcsA.hg("unloadDialog");
    localbiy.setOnClick(localcsA);
    localdqa.bb(localbiy);
    localbiy.brn();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setSize(new Or(-2, -2));
    localcwP4.setAlign(ajb.dhV);
    localbiy.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    localbiy.rV();
    localdqa.rV();
    localdRq1.rV();
    localbpn.rV();
    return localbpn;
  }
}