import java.awt.Insets;
import java.util.Stack;

public class dTb
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setAlign(ajb.dhT);
    localcwP1.setYOffset(20);
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    czO localczO = new czO();
    localczO.aJ();
    localczO.setAdaptToContentSize(true);
    localdRq1.bb(localczO);
    localczO.brn();
    localczO.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setPrefSize(new Or(575, 94));
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.dhZ);
    localdRq2.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq3.setStyle("genericSplash");
    localdRq2.bb(localdRq3);
    localdRq3.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setName("dungeonStatut");
    localNK1.setAttribute("visible");
    localNK1.setField("positionResult");
    localdRq3.bb(localNK1);
    localNK1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localNK1.bb(localanQ1);
    localanQ1.brn();
    dDu localdDu1 = new dDu();
    localdDu1.aJ();
    localdDu1.setElementMap(localcpa);
    localanQ1.bb(localdDu1);
    localdDu1.brn();
    bSP localbSP1 = new bSP();
    localbSP1.aJ();
    localbSP1.setElementMap(localcpa);
    localbSP1.setValue("-1");
    localdDu1.bb(localbSP1);
    localbSP1.brn();
    localbSP1.rV();
    localdDu1.rV();
    localanQ1.rV();
    localNK1.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setExpandable(false);
    localdRq3.bb(localdRq4);
    localdRq4.brn();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(false);
    localaId.setAlign(aFG.ech);
    localdRq4.bb(localaId);
    localaId.brn();
    localaId.rV();
    dRq localdRq5 = localdRq4;
    Jg localJg1 = localdRq5.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq4.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(45, 10, 0, 0));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq6.setExpandable(false);
    localdRq4.bb(localdRq6);
    localdRq6.brn();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("DefaultBold16White");
    localcWk1.setExpandable(false);
    String str1 = "%dungeon.youWin%";
    str1 = str1.replace("%dungeon.youWin%", cBQ.cxL().mL("dungeon.youWin"));
    localcWk1.setText(str1);
    localdRq6.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg2 = localcWk2.getAppearance();
    localJg2.setElementMap(localcpa);
    localcWk1.bb(localJg2);
    localJg2.brn();
    cAf localcAf1 = cAf.checkOut();
    localcAf1.setElementMap(localcpa);
    localcAf1.setColor(new bNa(0.94F, 0.8F, 0.04F, 1.0F));
    localJg2.bb(localcAf1);
    localcAf1.brn();
    localcAf1.rV();
    localJg2.rV();
    localcWk1.rV();
    cWk localcWk3 = new cWk();
    localcWk3.aJ();
    localcWk3.setElementMap(localcpa);
    localcWk3.setStyle("DefaultBold16White");
    localcWk3.setExpandable(false);
    localdRq6.bb(localcWk3);
    localcWk3.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setAttribute("text");
    localNK2.setName("dungeonStatut");
    localNK2.setField("dungeonType");
    localcWk3.bb(localNK2);
    localNK2.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    String str2 = "%dongeon.timeAttackType%";
    str2 = str2.replace("%dongeon.timeAttackType%", cBQ.cxL().mL("dongeon.timeAttackType"));
    localanQ2.setValue(str2);
    String str3 = "%dongeon.survivalType%";
    str3 = str3.replace("%dongeon.survivalType%", cBQ.cxL().mL("dongeon.survivalType"));
    localanQ2.setElseValue(str3);
    localNK2.bb(localanQ2);
    localanQ2.brn();
    bSP localbSP2 = new bSP();
    localbSP2.aJ();
    localbSP2.setElementMap(localcpa);
    localbSP2.setValue("0");
    localanQ2.bb(localbSP2);
    localbSP2.brn();
    localbSP2.rV();
    localanQ2.rV();
    localNK2.rV();
    cWk localcWk4 = localcWk3;
    Jg localJg3 = localcWk4.getAppearance();
    localJg3.setElementMap(localcpa);
    localcWk3.bb(localJg3);
    localJg3.brn();
    cAf localcAf2 = cAf.checkOut();
    localcAf2.setElementMap(localcpa);
    localcAf2.setColor(new bNa(0.94F, 0.8F, 0.04F, 1.0F));
    localJg3.bb(localcAf2);
    localcAf2.brn();
    localcAf2.rV();
    localJg3.rV();
    localcWk3.rV();
    localdRq6.rV();
    cWk localcWk5 = new cWk();
    localcWk5.aJ();
    localcWk5.setElementMap(localcpa);
    localcWk5.setStyle("whiteBold");
    localcWk5.setExpandable(false);
    localdRq4.bb(localcWk5);
    localcWk5.brn();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setName("dungeonStatut");
    localNK3.setAttribute("visible");
    localNK3.setField("positionResult");
    localcWk5.bb(localNK3);
    localNK3.brn();
    anQ localanQ3 = new anQ();
    localanQ3.aJ();
    localanQ3.setElementMap(localcpa);
    localNK3.bb(localanQ3);
    localanQ3.brn();
    dDu localdDu2 = new dDu();
    localdDu2.aJ();
    localdDu2.setElementMap(localcpa);
    localanQ3.bb(localdDu2);
    localdDu2.brn();
    bSP localbSP3 = new bSP();
    localbSP3.aJ();
    localbSP3.setElementMap(localcpa);
    localbSP3.setValue("-1");
    localdDu2.bb(localbSP3);
    localbSP3.brn();
    localbSP3.rV();
    localdDu2.rV();
    localanQ3.rV();
    localNK3.rV();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa);
    localNK4.setAttribute("text");
    localNK4.setName("dungeonStatut");
    localNK4.setField("buffs");
    localcWk5.bb(localNK4);
    localNK4.brn();
    localNK4.rV();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.eck);
    localcWk5.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    localcWk5.rV();
    localdRq4.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localdRq7.setExpandable(false);
    localdRq3.bb(localdRq7);
    localdRq7.brn();
    dRq localdRq8 = localdRq7;
    Jg localJg4 = localdRq8.getAppearance();
    localJg4.setElementMap(localcpa);
    localdRq7.bb(localJg4);
    localJg4.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(35, 30, 0, 0));
    localJg4.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg4.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localdRq7.bb(localczv1);
    localczv1.brn();
    NK localNK5 = NK.checkOut();
    localNK5.setElementMap(localcpa);
    localNK5.setName("dungeonStatut");
    localNK5.setAttribute("style");
    localNK5.setField("medalStyle");
    localczv1.bb(localNK5);
    localNK5.brn();
    localNK5.rV();
    localczv1.rV();
    localdRq7.rV();
    localdRq3.rV();
    localdRq2.rV();
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa);
    localdRq1.bb(localdRq9);
    localdRq9.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setAlign(ajb.dhY);
    localcwP3.setYOffset(10);
    localdRq9.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    dRq localdRq10 = dRq.checkOut();
    localdRq10.setElementMap(localcpa);
    localdRq10.setStyle("LevelGainParticle");
    localdRq9.bb(localdRq10);
    localdRq10.brn();
    NK localNK6 = NK.checkOut();
    localNK6.setElementMap(localcpa);
    localNK6.setName("dungeonStatut");
    localNK6.setAttribute("style");
    localNK6.setField("positionResult");
    localdRq10.bb(localNK6);
    localNK6.brn();
    anQ localanQ4 = new anQ();
    localanQ4.aJ();
    localanQ4.setElementMap(localcpa);
    localanQ4.setValue("LevelGainParticle");
    localanQ4.setElseValue("");
    localNK6.bb(localanQ4);
    localanQ4.brn();
    dDu localdDu3 = new dDu();
    localdDu3.aJ();
    localdDu3.setElementMap(localcpa);
    localanQ4.bb(localdDu3);
    localdDu3.brn();
    bSP localbSP4 = new bSP();
    localbSP4.aJ();
    localbSP4.setElementMap(localcpa);
    localbSP4.setValue("-1");
    localdDu3.bb(localbSP4);
    localbSP4.brn();
    localbSP4.rV();
    localdDu3.rV();
    localanQ4.rV();
    localNK6.rV();
    cWk localcWk6 = new cWk();
    localcWk6.aJ();
    localcWk6.setElementMap(localcpa);
    localcWk6.setStyle("BigBordered");
    localcWk6.setEnableAutoZoomShrink(true);
    localdRq10.bb(localcWk6);
    localcWk6.brn();
    cWk localcWk7 = localcWk6;
    Jg localJg5 = localcWk7.getAppearance();
    localJg5.setElementMap(localcpa);
    ((cwJ)localJg5).setAlign(aFG.eck);
    localcWk6.bb(localJg5);
    localJg5.brn();
    localJg5.rV();
    NK localNK7 = NK.checkOut();
    localNK7.setElementMap(localcpa);
    localNK7.setName("dungeonStatut");
    localNK7.setAttribute("text");
    localNK7.setField("text");
    localcWk6.bb(localNK7);
    localNK7.brn();
    localNK7.rV();
    localcWk6.rV();
    localdRq10.rV();
    czv localczv2 = new czv();
    localczv2.aJ();
    localczv2.setElementMap(localcpa);
    localczv2.setExpandable(false);
    localdRq9.bb(localczv2);
    localczv2.brn();
    NK localNK8 = NK.checkOut();
    localNK8.setElementMap(localcpa);
    localNK8.setName("dungeonStatut");
    localNK8.setAttribute("style");
    localNK8.setField("dungeonType");
    localczv2.bb(localNK8);
    localNK8.brn();
    anQ localanQ5 = new anQ();
    localanQ5.aJ();
    localanQ5.setElementMap(localcpa);
    localanQ5.setValue("ChallengeBigTimer");
    localanQ5.setElseValue("BigBox");
    localNK8.bb(localanQ5);
    localanQ5.brn();
    bSP localbSP5 = new bSP();
    localbSP5.aJ();
    localbSP5.setElementMap(localcpa);
    localbSP5.setValue("0");
    localanQ5.bb(localbSP5);
    localbSP5.brn();
    localbSP5.rV();
    localanQ5.rV();
    localNK8.rV();
    localczv2.rV();
    localdRq9.rV();
    localdRq1.rV();
    return localdRq1;
  }
}