import java.awt.Insets;
import java.util.Stack;

public class my
  implements aTK
{
  private uk W;
  private Stack X = new Stack();

  public void a(cpa paramcpa, uk paramuk, dOc paramdOc)
  {
    this.W = paramuk;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    cuR localcuR = new cuR();
    localcuR.aJ();
    localcuR.setElementMap(localcpa);
    localcuR.setInsets(new Insets(2, 2, 2, 2));
    paramdOc.bb(localcuR);
    localcuR.brn();
    localcuR.rV();
    dOc localdOc1 = paramdOc;
    Jg localJg1 = localdOc1.getAppearance();
    localJg1.setElementMap(localcpa);
    ((cwJ)localJg1).setAlignment(aFG.eck);
    localJg1.setState("default");
    paramdOc.bb(localJg1);
    localJg1.brn();
    bJA localbJA = bJA.checkOut();
    localbJA.setRenderer(cBQ.cxL().bSM().aI("defaultFont"));
    localbJA.setElementMap(localcpa);
    localJg1.bb(localbJA);
    localbJA.brn();
    localbJA.rV();
    String str1 = "defaultDarkColor";
    cAf localcAf1 = cAf.checkOut();
    localcAf1.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localcAf1);
    localcAf1.setColor(new bNa(0.29F, 0.17F, 0.07F, 1.0F));
    localJg1.bb(localcAf1);
    localcAf1.brn();
    localcAf1.rV();
    String str2 = "tabDefaultBackground";
    aen localaen1 = aen.checkOut();
    localaen1.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localaen1);
    localaen1.setScaled(true);
    localJg1.bb(localaen1);
    localaen1.brn();
    aAR localaAR1 = aAR.checkOut();
    localaAR1.setElementMap(localcpa);
    localaAR1.setPosition(ajb.dhZ);
    localaAR1.setX(728);
    localaAR1.setY(149);
    localaAR1.setWidth(9);
    localaAR1.setHeight(9);
    localaAR1.setTexture(this.W.aH("default_1.tga"));
    localaen1.bb(localaAR1);
    localaAR1.brn();
    localaAR1.rV();
    localaen1.rV();
    String str3 = "tabDefaultBorder";
    Cx localCx1 = new Cx();
    localCx1.aJ();
    localCx1.setElementMap(localcpa);
    if ((localcpa != null) && (str3 != null))
      localcpa.a(str3, localCx1);
    localJg1.bb(localCx1);
    localCx1.brn();
    aAR localaAR2 = aAR.checkOut();
    localaAR2.setElementMap(localcpa);
    localaAR2.setPosition(ajb.dhR);
    localaAR2.setX(366);
    localaAR2.setY(149);
    localaAR2.setWidth(10);
    localaAR2.setHeight(11);
    localaAR2.setTexture(this.W.aH("default_1.tga"));
    localCx1.bb(localaAR2);
    localaAR2.brn();
    localaAR2.rV();
    aAR localaAR3 = aAR.checkOut();
    localaAR3.setElementMap(localcpa);
    localaAR3.setPosition(ajb.dhT);
    localaAR3.setX(652);
    localaAR3.setY(219);
    localaAR3.setWidth(9);
    localaAR3.setHeight(11);
    localaAR3.setTexture(this.W.aH("default_0.tga"));
    localCx1.bb(localaAR3);
    localaAR3.brn();
    localaAR3.rV();
    aAR localaAR4 = aAR.checkOut();
    localaAR4.setElementMap(localcpa);
    localaAR4.setPosition(ajb.dhV);
    localaAR4.setX(310);
    localaAR4.setY(149);
    localaAR4.setWidth(10);
    localaAR4.setHeight(11);
    localaAR4.setTexture(this.W.aH("default_1.tga"));
    localCx1.bb(localaAR4);
    localaAR4.brn();
    localaAR4.rV();
    aAR localaAR5 = aAR.checkOut();
    localaAR5.setElementMap(localcpa);
    localaAR5.setPosition(ajb.dia);
    localaAR5.setX(633);
    localaAR5.setY(149);
    localaAR5.setWidth(10);
    localaAR5.setHeight(9);
    localaAR5.setTexture(this.W.aH("default_1.tga"));
    localCx1.bb(localaAR5);
    localaAR5.brn();
    localaAR5.rV();
    aAR localaAR6 = aAR.checkOut();
    localaAR6.setElementMap(localcpa);
    localaAR6.setPosition(ajb.dih);
    localaAR6.setX(510);
    localaAR6.setY(139);
    localaAR6.setWidth(10);
    localaAR6.setHeight(7);
    localaAR6.setTexture(this.W.aH("default_1.tga"));
    localCx1.bb(localaAR6);
    localaAR6.brn();
    localaAR6.rV();
    aAR localaAR7 = aAR.checkOut();
    localaAR7.setElementMap(localcpa);
    localaAR7.setPosition(ajb.dif);
    localaAR7.setX(698);
    localaAR7.setY(139);
    localaAR7.setWidth(9);
    localaAR7.setHeight(7);
    localaAR7.setTexture(this.W.aH("default_1.tga"));
    localCx1.bb(localaAR7);
    localaAR7.brn();
    localaAR7.rV();
    aAR localaAR8 = aAR.checkOut();
    localaAR8.setElementMap(localcpa);
    localaAR8.setPosition(ajb.did);
    localaAR8.setX(297);
    localaAR8.setY(139);
    localaAR8.setWidth(10);
    localaAR8.setHeight(7);
    localaAR8.setTexture(this.W.aH("default_1.tga"));
    localCx1.bb(localaAR8);
    localaAR8.brn();
    localaAR8.rV();
    aAR localaAR9 = aAR.checkOut();
    localaAR9.setElementMap(localcpa);
    localaAR9.setPosition(ajb.dhY);
    localaAR9.setX(650);
    localaAR9.setY(139);
    localaAR9.setWidth(10);
    localaAR9.setHeight(7);
    localaAR9.setTexture(this.W.aH("default_1.tga"));
    localCx1.bb(localaAR9);
    localaAR9.brn();
    localaAR9.rV();
    localCx1.rV();
    localJg1.rV();
    dOc localdOc2 = paramdOc;
    Jg localJg2 = localdOc2.getAppearance();
    localJg2.setElementMap(localcpa);
    ((cwJ)localJg2).setAlignment(aFG.eck);
    localJg2.setState("mouseHover");
    paramdOc.bb(localJg2);
    localJg2.brn();
    String str4 = "defaultDarkColor";
    cAf localcAf2 = cAf.checkOut();
    localcAf2.setElementMap(localcpa);
    if ((localcpa != null) && (str4 != null))
      localcpa.a(str4, localcAf2);
    localcAf2.setColor(new bNa(0.29F, 0.17F, 0.07F, 1.0F));
    localJg2.bb(localcAf2);
    localcAf2.brn();
    localcAf2.rV();
    String str5 = "tabOverBackground";
    aen localaen2 = aen.checkOut();
    localaen2.setElementMap(localcpa);
    if ((localcpa != null) && (str5 != null))
      localcpa.a(str5, localaen2);
    localaen2.setScaled(true);
    localJg2.bb(localaen2);
    localaen2.brn();
    aAR localaAR10 = aAR.checkOut();
    localaAR10.setElementMap(localcpa);
    localaAR10.setPosition(ajb.dhZ);
    localaAR10.setX(728);
    localaAR10.setY(149);
    localaAR10.setWidth(9);
    localaAR10.setHeight(9);
    localaAR10.setTexture(this.W.aH("default_1.tga"));
    localaen2.bb(localaAR10);
    localaAR10.brn();
    localaAR10.rV();
    localaen2.rV();
    String str6 = "tabOverBorder";
    Cx localCx2 = new Cx();
    localCx2.aJ();
    localCx2.setElementMap(localcpa);
    if ((localcpa != null) && (str6 != null))
      localcpa.a(str6, localCx2);
    localJg2.bb(localCx2);
    localCx2.brn();
    aAR localaAR11 = aAR.checkOut();
    localaAR11.setElementMap(localcpa);
    localaAR11.setPosition(ajb.dhR);
    localaAR11.setX(177);
    localaAR11.setY(181);
    localaAR11.setWidth(10);
    localaAR11.setHeight(11);
    localaAR11.setTexture(this.W.aH("default_1.tga"));
    localCx2.bb(localaAR11);
    localaAR11.brn();
    localaAR11.rV();
    aAR localaAR12 = aAR.checkOut();
    localaAR12.setElementMap(localcpa);
    localaAR12.setPosition(ajb.dhT);
    localaAR12.setX(576);
    localaAR12.setY(148);
    localaAR12.setWidth(9);
    localaAR12.setHeight(11);
    localaAR12.setTexture(this.W.aH("default_1.tga"));
    localCx2.bb(localaAR12);
    localaAR12.brn();
    localaAR12.rV();
    aAR localaAR13 = aAR.checkOut();
    localaAR13.setElementMap(localcpa);
    localaAR13.setPosition(ajb.dhV);
    localaAR13.setX(650);
    localaAR13.setY(149);
    localaAR13.setWidth(10);
    localaAR13.setHeight(11);
    localaAR13.setTexture(this.W.aH("default_1.tga"));
    localCx2.bb(localaAR13);
    localaAR13.brn();
    localaAR13.rV();
    aAR localaAR14 = aAR.checkOut();
    localaAR14.setElementMap(localcpa);
    localaAR14.setPosition(ajb.dia);
    localaAR14.setX(668);
    localaAR14.setY(149);
    localaAR14.setWidth(10);
    localaAR14.setHeight(9);
    localaAR14.setTexture(this.W.aH("default_1.tga"));
    localCx2.bb(localaAR14);
    localaAR14.brn();
    localaAR14.rV();
    aAR localaAR15 = aAR.checkOut();
    localaAR15.setElementMap(localcpa);
    localaAR15.setPosition(ajb.dih);
    localaAR15.setX(786);
    localaAR15.setY(140);
    localaAR15.setWidth(10);
    localaAR15.setHeight(7);
    localaAR15.setTexture(this.W.aH("default_1.tga"));
    localCx2.bb(localaAR15);
    localaAR15.brn();
    localaAR15.rV();
    aAR localaAR16 = aAR.checkOut();
    localaAR16.setElementMap(localcpa);
    localaAR16.setPosition(ajb.dif);
    localaAR16.setX(280);
    localaAR16.setY(139);
    localaAR16.setWidth(9);
    localaAR16.setHeight(7);
    localaAR16.setTexture(this.W.aH("default_1.tga"));
    localCx2.bb(localaAR16);
    localaAR16.brn();
    localaAR16.rV();
    aAR localaAR17 = aAR.checkOut();
    localaAR17.setElementMap(localcpa);
    localaAR17.setPosition(ajb.did);
    localaAR17.setX(262);
    localaAR17.setY(140);
    localaAR17.setWidth(10);
    localaAR17.setHeight(7);
    localaAR17.setTexture(this.W.aH("default_1.tga"));
    localCx2.bb(localaAR17);
    localaAR17.brn();
    localaAR17.rV();
    aAR localaAR18 = aAR.checkOut();
    localaAR18.setElementMap(localcpa);
    localaAR18.setPosition(ajb.dhY);
    localaAR18.setX(858);
    localaAR18.setY(140);
    localaAR18.setWidth(10);
    localaAR18.setHeight(7);
    localaAR18.setTexture(this.W.aH("default_1.tga"));
    localCx2.bb(localaAR18);
    localaAR18.brn();
    localaAR18.rV();
    localCx2.rV();
    localJg2.rV();
    dOc localdOc3 = paramdOc;
    Jg localJg3 = localdOc3.getAppearance();
    localJg3.setElementMap(localcpa);
    ((cwJ)localJg3).setAlignment(aFG.eck);
    localJg3.setState("pressed");
    paramdOc.bb(localJg3);
    localJg3.brn();
    String str7 = "defaultDarkColor";
    cAf localcAf3 = cAf.checkOut();
    localcAf3.setElementMap(localcpa);
    if ((localcpa != null) && (str7 != null))
      localcpa.a(str7, localcAf3);
    localcAf3.setColor(new bNa(0.29F, 0.17F, 0.07F, 1.0F));
    localJg3.bb(localcAf3);
    localcAf3.brn();
    localcAf3.rV();
    String str8 = "tabPressedBackground";
    aen localaen3 = aen.checkOut();
    localaen3.setElementMap(localcpa);
    if ((localcpa != null) && (str8 != null))
      localcpa.a(str8, localaen3);
    localaen3.setScaled(true);
    localJg3.bb(localaen3);
    localaen3.brn();
    aAR localaAR19 = aAR.checkOut();
    localaAR19.setElementMap(localcpa);
    localaAR19.setPosition(ajb.dhZ);
    localaAR19.setX(683);
    localaAR19.setY(149);
    localaAR19.setWidth(9);
    localaAR19.setHeight(9);
    localaAR19.setTexture(this.W.aH("default_1.tga"));
    localaen3.bb(localaAR19);
    localaAR19.brn();
    localaAR19.rV();
    localaen3.rV();
    String str9 = "tabPressedBorder";
    Cx localCx3 = new Cx();
    localCx3.aJ();
    localCx3.setElementMap(localcpa);
    if ((localcpa != null) && (str9 != null))
      localcpa.a(str9, localCx3);
    localJg3.bb(localCx3);
    localCx3.brn();
    aAR localaAR20 = aAR.checkOut();
    localaAR20.setElementMap(localcpa);
    localaAR20.setPosition(ajb.dhR);
    localaAR20.setX(879);
    localaAR20.setY(166);
    localaAR20.setWidth(10);
    localaAR20.setHeight(11);
    localaAR20.setTexture(this.W.aH("default_1.tga"));
    localCx3.bb(localaAR20);
    localaAR20.brn();
    localaAR20.rV();
    aAR localaAR21 = aAR.checkOut();
    localaAR21.setElementMap(localcpa);
    localaAR21.setPosition(ajb.dhT);
    localaAR21.setX(199);
    localaAR21.setY(220);
    localaAR21.setWidth(9);
    localaAR21.setHeight(11);
    localaAR21.setTexture(this.W.aH("default_1.tga"));
    localCx3.bb(localaAR21);
    localaAR21.brn();
    localaAR21.rV();
    aAR localaAR22 = aAR.checkOut();
    localaAR22.setElementMap(localcpa);
    localaAR22.setPosition(ajb.dhV);
    localaAR22.setX(879);
    localaAR22.setY(152);
    localaAR22.setWidth(10);
    localaAR22.setHeight(11);
    localaAR22.setTexture(this.W.aH("default_1.tga"));
    localCx3.bb(localaAR22);
    localaAR22.brn();
    localaAR22.rV();
    aAR localaAR23 = aAR.checkOut();
    localaAR23.setElementMap(localcpa);
    localaAR23.setPosition(ajb.dia);
    localaAR23.setX(280);
    localaAR23.setY(149);
    localaAR23.setWidth(10);
    localaAR23.setHeight(9);
    localaAR23.setTexture(this.W.aH("default_1.tga"));
    localCx3.bb(localaAR23);
    localaAR23.brn();
    localaAR23.rV();
    aAR localaAR24 = aAR.checkOut();
    localaAR24.setElementMap(localcpa);
    localaAR24.setPosition(ajb.dih);
    localaAR24.setX(556);
    localaAR24.setY(139);
    localaAR24.setWidth(10);
    localaAR24.setHeight(7);
    localaAR24.setTexture(this.W.aH("default_1.tga"));
    localCx3.bb(localaAR24);
    localaAR24.brn();
    localaAR24.rV();
    aAR localaAR25 = aAR.checkOut();
    localaAR25.setElementMap(localcpa);
    localaAR25.setPosition(ajb.dif);
    localaAR25.setX(633);
    localaAR25.setY(139);
    localaAR25.setWidth(9);
    localaAR25.setHeight(7);
    localaAR25.setTexture(this.W.aH("default_1.tga"));
    localCx3.bb(localaAR25);
    localaAR25.brn();
    localaAR25.rV();
    aAR localaAR26 = aAR.checkOut();
    localaAR26.setElementMap(localcpa);
    localaAR26.setPosition(ajb.did);
    localaAR26.setX(841);
    localaAR26.setY(140);
    localaAR26.setWidth(10);
    localaAR26.setHeight(7);
    localaAR26.setTexture(this.W.aH("default_1.tga"));
    localCx3.bb(localaAR26);
    localaAR26.brn();
    localaAR26.rV();
    aAR localaAR27 = aAR.checkOut();
    localaAR27.setElementMap(localcpa);
    localaAR27.setPosition(ajb.dhY);
    localaAR27.setX(464);
    localaAR27.setY(139);
    localaAR27.setWidth(10);
    localaAR27.setHeight(7);
    localaAR27.setTexture(this.W.aH("default_1.tga"));
    localCx3.bb(localaAR27);
    localaAR27.brn();
    localaAR27.rV();
    localCx3.rV();
    localJg3.rV();
    dOc localdOc4 = paramdOc;
    Jg localJg4 = localdOc4.getAppearance();
    localJg4.setElementMap(localcpa);
    ((cwJ)localJg4).setAlignment(aFG.eck);
    localJg4.setState("disabled");
    paramdOc.bb(localJg4);
    localJg4.brn();
    String str10 = "defaultDarkColor";
    cAf localcAf4 = cAf.checkOut();
    localcAf4.setElementMap(localcpa);
    if ((localcpa != null) && (str10 != null))
      localcpa.a(str10, localcAf4);
    localcAf4.setColor(new bNa(0.29F, 0.17F, 0.07F, 1.0F));
    localJg4.bb(localcAf4);
    localcAf4.brn();
    localcAf4.rV();
    String str11 = "tabDisabledBackground";
    aen localaen4 = aen.checkOut();
    localaen4.setElementMap(localcpa);
    if ((localcpa != null) && (str11 != null))
      localcpa.a(str11, localaen4);
    localaen4.setScaled(true);
    localJg4.bb(localaen4);
    localaen4.brn();
    aAR localaAR28 = aAR.checkOut();
    localaAR28.setElementMap(localcpa);
    localaAR28.setPosition(ajb.dhZ);
    localaAR28.setX(728);
    localaAR28.setY(149);
    localaAR28.setWidth(9);
    localaAR28.setHeight(9);
    localaAR28.setTexture(this.W.aH("default_1.tga"));
    localaen4.bb(localaAR28);
    localaAR28.brn();
    localaAR28.rV();
    localaen4.rV();
    String str12 = "tabDisabledBorder";
    Cx localCx4 = new Cx();
    localCx4.aJ();
    localCx4.setElementMap(localcpa);
    if ((localcpa != null) && (str12 != null))
      localcpa.a(str12, localCx4);
    localJg4.bb(localCx4);
    localCx4.brn();
    aAR localaAR29 = aAR.checkOut();
    localaAR29.setElementMap(localcpa);
    localaAR29.setPosition(ajb.dhR);
    localaAR29.setX(366);
    localaAR29.setY(149);
    localaAR29.setWidth(10);
    localaAR29.setHeight(11);
    localaAR29.setTexture(this.W.aH("default_1.tga"));
    localCx4.bb(localaAR29);
    localaAR29.brn();
    localaAR29.rV();
    aAR localaAR30 = aAR.checkOut();
    localaAR30.setElementMap(localcpa);
    localaAR30.setPosition(ajb.dhT);
    localaAR30.setX(652);
    localaAR30.setY(219);
    localaAR30.setWidth(9);
    localaAR30.setHeight(11);
    localaAR30.setTexture(this.W.aH("default_0.tga"));
    localCx4.bb(localaAR30);
    localaAR30.brn();
    localaAR30.rV();
    aAR localaAR31 = aAR.checkOut();
    localaAR31.setElementMap(localcpa);
    localaAR31.setPosition(ajb.dhV);
    localaAR31.setX(310);
    localaAR31.setY(149);
    localaAR31.setWidth(10);
    localaAR31.setHeight(11);
    localaAR31.setTexture(this.W.aH("default_1.tga"));
    localCx4.bb(localaAR31);
    localaAR31.brn();
    localaAR31.rV();
    aAR localaAR32 = aAR.checkOut();
    localaAR32.setElementMap(localcpa);
    localaAR32.setPosition(ajb.dia);
    localaAR32.setX(633);
    localaAR32.setY(149);
    localaAR32.setWidth(10);
    localaAR32.setHeight(9);
    localaAR32.setTexture(this.W.aH("default_1.tga"));
    localCx4.bb(localaAR32);
    localaAR32.brn();
    localaAR32.rV();
    a(localCx4);
    b(localCx4);
    d(localCx4);
    e(localCx4);
    localCx4.rV();
    localJg4.rV();
    f(paramdOc);
    g(paramdOc);
    h(paramdOc);
    i(paramdOc);
  }

  public bdj a(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localaAR.setPosition(ajb.dih);
    localaAR.setX(510);
    localaAR.setY(139);
    localaAR.setWidth(10);
    localaAR.setHeight(7);
    localaAR.setTexture(this.W.aH("default_1.tga"));
    parambdj.bb(localaAR);
    localaAR.brn();
    localaAR.rV();
    return localaAR;
  }

  public bdj b(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localaAR.setPosition(ajb.dif);
    localaAR.setX(698);
    localaAR.setY(139);
    localaAR.setWidth(9);
    localaAR.setHeight(7);
    localaAR.setTexture(this.W.aH("default_1.tga"));
    parambdj.bb(localaAR);
    localaAR.brn();
    localaAR.rV();
    return localaAR;
  }

  public bdj d(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localaAR.setPosition(ajb.did);
    localaAR.setX(297);
    localaAR.setY(139);
    localaAR.setWidth(10);
    localaAR.setHeight(7);
    localaAR.setTexture(this.W.aH("default_1.tga"));
    parambdj.bb(localaAR);
    localaAR.brn();
    localaAR.rV();
    return localaAR;
  }

  public bdj e(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localaAR.setPosition(ajb.dhY);
    localaAR.setX(650);
    localaAR.setY(139);
    localaAR.setWidth(10);
    localaAR.setHeight(7);
    localaAR.setTexture(this.W.aH("default_1.tga"));
    parambdj.bb(localaAR);
    localaAR.brn();
    localaAR.rV();
    return localaAR;
  }

  public bdj f(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dOc localdOc = (dOc)parambdj;
    Jg localJg = localdOc.getAppearance();
    localJg.setElementMap(localcpa);
    ((cwJ)localJg).setAlignment(aFG.eck);
    localJg.setState("selected");
    parambdj.bb(localJg);
    localJg.brn();
    String str1 = "defaultDarkColor";
    cAf localcAf = cAf.checkOut();
    localcAf.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localcAf);
    localcAf.setColor(new bNa(0.29F, 0.17F, 0.07F, 1.0F));
    localJg.bb(localcAf);
    localcAf.brn();
    localcAf.rV();
    String str2 = "tabDefaultSelectedBackground";
    aen localaen = aen.checkOut();
    localaen.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localaen);
    localaen.setScaled(true);
    localJg.bb(localaen);
    localaen.brn();
    aAR localaAR1 = aAR.checkOut();
    localaAR1.setElementMap(localcpa);
    localaAR1.setPosition(ajb.dhZ);
    localaAR1.setX(728);
    localaAR1.setY(149);
    localaAR1.setWidth(9);
    localaAR1.setHeight(9);
    localaAR1.setTexture(this.W.aH("default_1.tga"));
    localaen.bb(localaAR1);
    localaAR1.brn();
    localaAR1.rV();
    localaen.rV();
    String str3 = "tabDefaultSelectedBorder";
    Cx localCx = new Cx();
    localCx.aJ();
    localCx.setElementMap(localcpa);
    if ((localcpa != null) && (str3 != null))
      localcpa.a(str3, localCx);
    localJg.bb(localCx);
    localCx.brn();
    aAR localaAR2 = aAR.checkOut();
    localaAR2.setElementMap(localcpa);
    localaAR2.setPosition(ajb.dhR);
    localaAR2.setX(1011);
    localaAR2.setY(164);
    localaAR2.setWidth(10);
    localaAR2.setHeight(11);
    localaAR2.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR2);
    localaAR2.brn();
    localaAR2.rV();
    aAR localaAR3 = aAR.checkOut();
    localaAR3.setElementMap(localcpa);
    localaAR3.setPosition(ajb.dhT);
    localaAR3.setX(994);
    localaAR3.setY(148);
    localaAR3.setWidth(9);
    localaAR3.setHeight(11);
    localaAR3.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR3);
    localaAR3.brn();
    localaAR3.rV();
    aAR localaAR4 = aAR.checkOut();
    localaAR4.setElementMap(localcpa);
    localaAR4.setPosition(ajb.dhV);
    localaAR4.setX(858);
    localaAR4.setY(162);
    localaAR4.setWidth(10);
    localaAR4.setHeight(11);
    localaAR4.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR4);
    localaAR4.brn();
    localaAR4.rV();
    aAR localaAR5 = aAR.checkOut();
    localaAR5.setElementMap(localcpa);
    localaAR5.setPosition(ajb.dia);
    localaAR5.setX(349);
    localaAR5.setY(149);
    localaAR5.setWidth(10);
    localaAR5.setHeight(9);
    localaAR5.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR5);
    localaAR5.brn();
    localaAR5.rV();
    aAR localaAR6 = aAR.checkOut();
    localaAR6.setElementMap(localcpa);
    localaAR6.setPosition(ajb.dih);
    localaAR6.setX(588);
    localaAR6.setY(140);
    localaAR6.setWidth(10);
    localaAR6.setHeight(7);
    localaAR6.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR6);
    localaAR6.brn();
    localaAR6.rV();
    aAR localaAR7 = aAR.checkOut();
    localaAR7.setElementMap(localcpa);
    localaAR7.setPosition(ajb.dif);
    localaAR7.setX(698);
    localaAR7.setY(139);
    localaAR7.setWidth(9);
    localaAR7.setHeight(7);
    localaAR7.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR7);
    localaAR7.brn();
    localaAR7.rV();
    aAR localaAR8 = aAR.checkOut();
    localaAR8.setElementMap(localcpa);
    localaAR8.setPosition(ajb.did);
    localaAR8.setX(487);
    localaAR8.setY(139);
    localaAR8.setWidth(10);
    localaAR8.setHeight(7);
    localaAR8.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR8);
    localaAR8.brn();
    localaAR8.rV();
    aAR localaAR9 = aAR.checkOut();
    localaAR9.setElementMap(localcpa);
    localaAR9.setPosition(ajb.dhY);
    localaAR9.setX(614);
    localaAR9.setY(140);
    localaAR9.setWidth(10);
    localaAR9.setHeight(7);
    localaAR9.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR9);
    localaAR9.brn();
    localaAR9.rV();
    localCx.rV();
    localJg.rV();
    return localJg;
  }

  public bdj g(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dOc localdOc = (dOc)parambdj;
    Jg localJg = localdOc.getAppearance();
    localJg.setElementMap(localcpa);
    ((cwJ)localJg).setAlignment(aFG.eck);
    localJg.setState("mouseHoverSelected");
    parambdj.bb(localJg);
    localJg.brn();
    cAf localcAf = cAf.checkOut();
    localcAf.setElementMap(localcpa);
    localcAf.setColor(new bNa(0.0F, 0.0F, 0.0F, 1.0F));
    localJg.bb(localcAf);
    localcAf.brn();
    localcAf.rV();
    String str1 = "tabOverSelectedBackground";
    aen localaen = aen.checkOut();
    localaen.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localaen);
    localaen.setScaled(true);
    localJg.bb(localaen);
    localaen.brn();
    aAR localaAR1 = aAR.checkOut();
    localaAR1.setElementMap(localcpa);
    localaAR1.setPosition(ajb.dhZ);
    localaAR1.setX(728);
    localaAR1.setY(149);
    localaAR1.setWidth(9);
    localaAR1.setHeight(9);
    localaAR1.setTexture(this.W.aH("default_1.tga"));
    localaen.bb(localaAR1);
    localaAR1.brn();
    localaAR1.rV();
    localaen.rV();
    String str2 = "tabOverSelectedBorder";
    Cx localCx = new Cx();
    localCx.aJ();
    localCx.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localCx);
    localJg.bb(localCx);
    localCx.brn();
    aAR localaAR2 = aAR.checkOut();
    localaAR2.setElementMap(localcpa);
    localaAR2.setPosition(ajb.dhR);
    localaAR2.setX(959);
    localaAR2.setY(181);
    localaAR2.setWidth(10);
    localaAR2.setHeight(11);
    localaAR2.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR2);
    localaAR2.brn();
    localaAR2.rV();
    aAR localaAR3 = aAR.checkOut();
    localaAR3.setElementMap(localcpa);
    localaAR3.setPosition(ajb.dhT);
    localaAR3.setX(656);
    localaAR3.setY(181);
    localaAR3.setWidth(9);
    localaAR3.setHeight(11);
    localaAR3.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR3);
    localaAR3.brn();
    localaAR3.rV();
    aAR localaAR4 = aAR.checkOut();
    localaAR4.setElementMap(localcpa);
    localaAR4.setPosition(ajb.dhV);
    localaAR4.setX(297);
    localaAR4.setY(149);
    localaAR4.setWidth(10);
    localaAR4.setHeight(11);
    localaAR4.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR4);
    localaAR4.brn();
    localaAR4.rV();
    aAR localaAR5 = aAR.checkOut();
    localaAR5.setElementMap(localcpa);
    localaAR5.setPosition(ajb.dia);
    localaAR5.setX(911);
    localaAR5.setY(149);
    localaAR5.setWidth(10);
    localaAR5.setHeight(9);
    localaAR5.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR5);
    localaAR5.brn();
    localaAR5.rV();
    aAR localaAR6 = aAR.checkOut();
    localaAR6.setElementMap(localcpa);
    localaAR6.setPosition(ajb.dih);
    localaAR6.setX(588);
    localaAR6.setY(140);
    localaAR6.setWidth(10);
    localaAR6.setHeight(7);
    localaAR6.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR6);
    localaAR6.brn();
    localaAR6.rV();
    aAR localaAR7 = aAR.checkOut();
    localaAR7.setElementMap(localcpa);
    localaAR7.setPosition(ajb.dif);
    localaAR7.setX(698);
    localaAR7.setY(139);
    localaAR7.setWidth(9);
    localaAR7.setHeight(7);
    localaAR7.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR7);
    localaAR7.brn();
    localaAR7.rV();
    aAR localaAR8 = aAR.checkOut();
    localaAR8.setElementMap(localcpa);
    localaAR8.setPosition(ajb.did);
    localaAR8.setX(487);
    localaAR8.setY(139);
    localaAR8.setWidth(10);
    localaAR8.setHeight(7);
    localaAR8.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR8);
    localaAR8.brn();
    localaAR8.rV();
    aAR localaAR9 = aAR.checkOut();
    localaAR9.setElementMap(localcpa);
    localaAR9.setPosition(ajb.dhY);
    localaAR9.setX(366);
    localaAR9.setY(139);
    localaAR9.setWidth(10);
    localaAR9.setHeight(7);
    localaAR9.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR9);
    localaAR9.brn();
    localaAR9.rV();
    localCx.rV();
    localJg.rV();
    return localJg;
  }

  public bdj h(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dOc localdOc = (dOc)parambdj;
    Jg localJg = localdOc.getAppearance();
    localJg.setElementMap(localcpa);
    ((cwJ)localJg).setAlignment(aFG.eck);
    localJg.setState("pressedSelected");
    parambdj.bb(localJg);
    localJg.brn();
    cAf localcAf = cAf.checkOut();
    localcAf.setElementMap(localcpa);
    localcAf.setColor(new bNa(0.0F, 0.0F, 0.0F, 1.0F));
    localJg.bb(localcAf);
    localcAf.brn();
    localcAf.rV();
    String str1 = "tabPressedSelectedBackground";
    aen localaen = aen.checkOut();
    localaen.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localaen);
    localaen.setScaled(true);
    localJg.bb(localaen);
    localaen.brn();
    aAR localaAR1 = aAR.checkOut();
    localaAR1.setElementMap(localcpa);
    localaAR1.setPosition(ajb.dhZ);
    localaAR1.setX(698);
    localaAR1.setY(149);
    localaAR1.setWidth(9);
    localaAR1.setHeight(9);
    localaAR1.setTexture(this.W.aH("default_1.tga"));
    localaen.bb(localaAR1);
    localaAR1.brn();
    localaAR1.rV();
    localaen.rV();
    String str2 = "tabPressedSelectedBorder";
    Cx localCx = new Cx();
    localCx.aJ();
    localCx.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localCx);
    localJg.bb(localCx);
    localCx.brn();
    aAR localaAR2 = aAR.checkOut();
    localaAR2.setElementMap(localcpa);
    localaAR2.setPosition(ajb.dhR);
    localaAR2.setX(879);
    localaAR2.setY(180);
    localaAR2.setWidth(10);
    localaAR2.setHeight(11);
    localaAR2.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR2);
    localaAR2.brn();
    localaAR2.rV();
    aAR localaAR3 = aAR.checkOut();
    localaAR3.setElementMap(localcpa);
    localaAR3.setPosition(ajb.dhT);
    localaAR3.setX(602);
    localaAR3.setY(148);
    localaAR3.setWidth(9);
    localaAR3.setHeight(11);
    localaAR3.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR3);
    localaAR3.brn();
    localaAR3.rV();
    aAR localaAR4 = aAR.checkOut();
    localaAR4.setElementMap(localcpa);
    localaAR4.setPosition(ajb.dhV);
    localaAR4.setX(379);
    localaAR4.setY(149);
    localaAR4.setWidth(10);
    localaAR4.setHeight(11);
    localaAR4.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR4);
    localaAR4.brn();
    localaAR4.rV();
    aAR localaAR5 = aAR.checkOut();
    localaAR5.setElementMap(localcpa);
    localaAR5.setPosition(ajb.dia);
    localaAR5.setX(936);
    localaAR5.setY(149);
    localaAR5.setWidth(10);
    localaAR5.setHeight(9);
    localaAR5.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR5);
    localaAR5.brn();
    localaAR5.rV();
    aAR localaAR6 = aAR.checkOut();
    localaAR6.setElementMap(localcpa);
    localaAR6.setPosition(ajb.dih);
    localaAR6.setX(533);
    localaAR6.setY(139);
    localaAR6.setWidth(10);
    localaAR6.setHeight(7);
    localaAR6.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR6);
    localaAR6.brn();
    localaAR6.rV();
    aAR localaAR7 = aAR.checkOut();
    localaAR7.setElementMap(localcpa);
    localaAR7.setPosition(ajb.dif);
    localaAR7.setX(683);
    localaAR7.setY(139);
    localaAR7.setWidth(9);
    localaAR7.setHeight(7);
    localaAR7.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR7);
    localaAR7.brn();
    localaAR7.rV();
    aAR localaAR8 = aAR.checkOut();
    localaAR8.setElementMap(localcpa);
    localaAR8.setPosition(ajb.did);
    localaAR8.setX(395);
    localaAR8.setY(139);
    localaAR8.setWidth(10);
    localaAR8.setHeight(7);
    localaAR8.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR8);
    localaAR8.brn();
    localaAR8.rV();
    aAR localaAR9 = aAR.checkOut();
    localaAR9.setElementMap(localcpa);
    localaAR9.setPosition(ajb.dhY);
    localaAR9.setX(1011);
    localaAR9.setY(140);
    localaAR9.setWidth(10);
    localaAR9.setHeight(7);
    localaAR9.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR9);
    localaAR9.brn();
    localaAR9.rV();
    localCx.rV();
    localJg.rV();
    return localJg;
  }

  public bdj i(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dOc localdOc = (dOc)parambdj;
    Jg localJg = localdOc.getAppearance();
    localJg.setElementMap(localcpa);
    ((cwJ)localJg).setAlignment(aFG.eck);
    localJg.setState("disabledSelected");
    parambdj.bb(localJg);
    localJg.brn();
    cAf localcAf = cAf.checkOut();
    localcAf.setElementMap(localcpa);
    localcAf.setColor(new bNa(0.0F, 0.0F, 0.0F, 1.0F));
    localJg.bb(localcAf);
    localcAf.brn();
    localcAf.rV();
    String str1 = "tabDisabledSelectedBackground";
    aen localaen = aen.checkOut();
    localaen.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localaen);
    localaen.setScaled(true);
    localJg.bb(localaen);
    localaen.brn();
    aAR localaAR1 = aAR.checkOut();
    localaAR1.setElementMap(localcpa);
    localaAR1.setPosition(ajb.dhZ);
    localaAR1.setX(728);
    localaAR1.setY(149);
    localaAR1.setWidth(9);
    localaAR1.setHeight(9);
    localaAR1.setTexture(this.W.aH("default_1.tga"));
    localaen.bb(localaAR1);
    localaAR1.brn();
    localaAR1.rV();
    localaen.rV();
    String str2 = "tabDisabledSelectedBorder";
    Cx localCx = new Cx();
    localCx.aJ();
    localCx.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localCx);
    localJg.bb(localCx);
    localCx.brn();
    aAR localaAR2 = aAR.checkOut();
    localaAR2.setElementMap(localcpa);
    localaAR2.setPosition(ajb.dhR);
    localaAR2.setX(1011);
    localaAR2.setY(164);
    localaAR2.setWidth(10);
    localaAR2.setHeight(11);
    localaAR2.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR2);
    localaAR2.brn();
    localaAR2.rV();
    aAR localaAR3 = aAR.checkOut();
    localaAR3.setElementMap(localcpa);
    localaAR3.setPosition(ajb.dhT);
    localaAR3.setX(994);
    localaAR3.setY(148);
    localaAR3.setWidth(9);
    localaAR3.setHeight(11);
    localaAR3.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR3);
    localaAR3.brn();
    localaAR3.rV();
    aAR localaAR4 = aAR.checkOut();
    localaAR4.setElementMap(localcpa);
    localaAR4.setPosition(ajb.dhV);
    localaAR4.setX(858);
    localaAR4.setY(162);
    localaAR4.setWidth(10);
    localaAR4.setHeight(11);
    localaAR4.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR4);
    localaAR4.brn();
    localaAR4.rV();
    aAR localaAR5 = aAR.checkOut();
    localaAR5.setElementMap(localcpa);
    localaAR5.setPosition(ajb.dia);
    localaAR5.setX(349);
    localaAR5.setY(149);
    localaAR5.setWidth(10);
    localaAR5.setHeight(9);
    localaAR5.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR5);
    localaAR5.brn();
    localaAR5.rV();
    aAR localaAR6 = aAR.checkOut();
    localaAR6.setElementMap(localcpa);
    localaAR6.setPosition(ajb.dih);
    localaAR6.setX(588);
    localaAR6.setY(140);
    localaAR6.setWidth(10);
    localaAR6.setHeight(7);
    localaAR6.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR6);
    localaAR6.brn();
    localaAR6.rV();
    aAR localaAR7 = aAR.checkOut();
    localaAR7.setElementMap(localcpa);
    localaAR7.setPosition(ajb.dif);
    localaAR7.setX(698);
    localaAR7.setY(139);
    localaAR7.setWidth(9);
    localaAR7.setHeight(7);
    localaAR7.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR7);
    localaAR7.brn();
    localaAR7.rV();
    aAR localaAR8 = aAR.checkOut();
    localaAR8.setElementMap(localcpa);
    localaAR8.setPosition(ajb.did);
    localaAR8.setX(487);
    localaAR8.setY(139);
    localaAR8.setWidth(10);
    localaAR8.setHeight(7);
    localaAR8.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR8);
    localaAR8.brn();
    localaAR8.rV();
    aAR localaAR9 = aAR.checkOut();
    localaAR9.setElementMap(localcpa);
    localaAR9.setPosition(ajb.dhY);
    localaAR9.setX(614);
    localaAR9.setY(140);
    localaAR9.setWidth(10);
    localaAR9.setHeight(7);
    localaAR9.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR9);
    localaAR9.brn();
    localaAR9.rV();
    localCx.rV();
    localJg.rV();
    return localJg;
  }
}