import java.awt.Insets;
import java.util.Stack;

public class ue
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    String str1 = "setContainerPopup";
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localdRq1);
    localdRq1.setPrefSize(new Or(260, 0));
    localdRq1.setStyle("popup");
    localdRq1.brn();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localdRq1.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("bigTitle");
    localcWk1.setExpandable(false);
    localcWk1.setMinWidth(260);
    localdRq1.bb(localcWk1);
    localcWk1.brn();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa);
    localdpm1.setAlign(aFG.ecj);
    localcWk1.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setName("itemPopupDetail");
    localNK1.setAttribute("text");
    localNK1.setField("nameAndNumber");
    localcWk1.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    localcWk1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setExpandable(false);
    localdRq2.setStyle("lineSeparator2");
    localdRq2.setPrefSize(new Or(50, 1));
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(5, 20, 5, 20));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    localdRq2.rV();
    ccG localccG = new ccG();
    localccG.aJ();
    localccG.setElementMap(localcpa);
    localccG.setExpandable(false);
    localccG.setPrefSize(new Or(205, 0));
    localccG.setCellSize(new Or(20.0F, 41));
    localccG.setHorizontal(false);
    localccG.setAutoIdealSize(true);
    localccG.setIdealSizeMaxColumns(5);
    localccG.setIdealSizeMinColumns(5);
    localccG.setIdealSizeMaxRows(3);
    localccG.setIdealSizeMinRows(1);
    localdRq1.bb(localccG);
    localccG.brn();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa);
    localdpm2.setAlign(aFG.eck);
    localccG.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("itemPopupDetail");
    localNK2.setField("items");
    localNK2.setAttribute("content");
    localccG.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    eR localeR = new eR();
    localeR.aJ();
    localeR.setElementMap(localcpa);
    localccG.bb(localeR);
    localeR.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localeR.bb(localanQ1);
    localanQ1.brn();
    bxx localbxx = new bxx();
    localbxx.aJ();
    localbxx.setElementMap(localcpa);
    localanQ1.bb(localbxx);
    localbxx.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localbxx.bb(localanE);
    localanE.brn();
    localanE.rV();
    localbxx.rV();
    localanQ1.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localeR.bb(localdRq4);
    localdRq4.brn();
    czO localczO = new czO();
    localczO.aJ();
    localdRq4.bb(localczO);
    localczO.brn();
    dRq localdRq5 = dRq.checkOut();
    localdRq5.setElementMap(localcpa);
    localczO.bb(localdRq5);
    localdRq5.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localdRq5.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("style");
    localdRq5.bb(localaaE1);
    localaaE1.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localanQ2.setValue("itemVirtualBackground");
    localanQ2.setElseValue("itemBackground");
    localaaE1.bb(localanQ2);
    localanQ2.brn();
    bJJ localbJJ1 = new bJJ();
    localbJJ1.aJ();
    localbJJ1.setElementMap(localcpa);
    localanQ2.bb(localbJJ1);
    localbJJ1.brn();
    bqW localbqW1 = new bqW();
    localbqW1.aJ();
    localbqW1.setElementMap(localcpa);
    localbJJ1.bb(localbqW1);
    localbqW1.brn();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("comparedValue");
    localaaE2.setField("isInInventory");
    localbqW1.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    localbqW1.rV();
    bqW localbqW2 = new bqW();
    localbqW2.aJ();
    localbqW2.setElementMap(localcpa);
    localbJJ1.bb(localbqW2);
    localbqW2.brn();
    aaE localaaE3 = new aaE();
    localaaE3.aJ();
    localaaE3.setElementMap(localcpa);
    localaaE3.setAttribute("comparedValue");
    localaaE3.setField("isEquiped");
    localbqW2.bb(localaaE3);
    localaaE3.brn();
    localaaE3.rV();
    localbqW2.rV();
    localbJJ1.rV();
    localanQ2.rV();
    localaaE1.rV();
    dRq localdRq6 = localdRq5;
    Jg localJg2 = localdRq6.getAppearance();
    localJg2.setElementMap(localcpa);
    localdRq5.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(2, 2, 2, 2));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setNonBlocking(true);
    localczv.setDisplaySize(new Or(32, 32));
    localdRq5.bb(localczv);
    localczv.brn();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv.bb(localaAR);
    localaAR.brn();
    aaE localaaE4 = new aaE();
    localaaE4.aJ();
    localaaE4.setElementMap(localcpa);
    localaaE4.setAttribute("texture");
    localaaE4.setField("iconUrl");
    localaAR.bb(localaaE4);
    localaaE4.brn();
    localaaE4.rV();
    localaAR.rV();
    localczv.rV();
    localdRq5.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localdRq7.setStyle("itemDisabled");
    localczO.bb(localdRq7);
    localdRq7.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localdRq7.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    aaE localaaE5 = new aaE();
    localaaE5.aJ();
    localaaE5.setElementMap(localcpa);
    localaaE5.setAttribute("visible");
    localdRq7.bb(localaaE5);
    localaaE5.brn();
    anQ localanQ3 = new anQ();
    localanQ3.aJ();
    localanQ3.setElementMap(localcpa);
    localaaE5.bb(localanQ3);
    localanQ3.brn();
    bJJ localbJJ2 = new bJJ();
    localbJJ2.aJ();
    localbJJ2.setElementMap(localcpa);
    localanQ3.bb(localbJJ2);
    localbJJ2.brn();
    cOk localcOk = new cOk();
    localcOk.aJ();
    localcOk.setElementMap(localcpa);
    localbJJ2.bb(localcOk);
    localcOk.brn();
    aaE localaaE6 = new aaE();
    localaaE6.aJ();
    localaaE6.setElementMap(localcpa);
    localaaE6.setAttribute("comparedValue");
    localaaE6.setField("isInInventory");
    localcOk.bb(localaaE6);
    localaaE6.brn();
    localaaE6.rV();
    localcOk.rV();
    bqW localbqW3 = new bqW();
    localbqW3.aJ();
    localbqW3.setElementMap(localcpa);
    localbJJ2.bb(localbqW3);
    localbqW3.brn();
    aaE localaaE7 = new aaE();
    localaaE7.aJ();
    localaaE7.setElementMap(localcpa);
    localaaE7.setAttribute("comparedValue");
    localaaE7.setField("isEquiped");
    localbqW3.bb(localaaE7);
    localaaE7.brn();
    localaaE7.rV();
    localbqW3.rV();
    localbJJ2.rV();
    localanQ3.rV();
    localaaE5.rV();
    localdRq7.rV();
    localczO.rV();
    localdRq4.rV();
    localeR.rV();
    localccG.rV();
    dRq localdRq8 = dRq.checkOut();
    localdRq8.setElementMap(localcpa);
    localdRq8.setExpandable(false);
    localdRq1.bb(localdRq8);
    localdRq8.brn();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setAttribute("visible");
    localNK3.setName("itemPopupDetail");
    localNK3.setField("characteristic");
    localdRq8.bb(localNK3);
    localNK3.brn();
    anQ localanQ4 = new anQ();
    localanQ4.aJ();
    localanQ4.setElementMap(localcpa);
    localanQ4.setValue("false");
    localanQ4.setElseValue("true");
    localNK3.bb(localanQ4);
    localanQ4.brn();
    bSP localbSP1 = new bSP();
    localbSP1.aJ();
    localbSP1.setElementMap(localcpa);
    localbSP1.setValue("");
    localanQ4.bb(localbSP1);
    localbSP1.brn();
    localbSP1.rV();
    localanQ4.rV();
    localNK3.rV();
    aId localaId2 = aId.checkOut();
    localaId2.setHorizontal(false);
    localdRq8.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa);
    localdRq9.setExpandable(false);
    localdRq9.setStyle("lineSeparator2");
    localdRq9.setPrefSize(new Or(50, 1));
    localdRq8.bb(localdRq9);
    localdRq9.brn();
    dRq localdRq10 = localdRq9;
    Jg localJg3 = localdRq10.getAppearance();
    localJg3.setElementMap(localcpa);
    localdRq9.bb(localJg3);
    localJg3.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(5, 20, 5, 20));
    localJg3.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg3.rV();
    localdRq9.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setExpandable(false);
    String str2 = "%bonusPenalties%";
    str2 = str2.replace("%bonusPenalties%", cBQ.cxL().mL("bonusPenalties"));
    localcaF1.setText(str2);
    localcaF1.setStyle("11BoldLight");
    localdRq8.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg4 = localcaF2.getAppearance();
    localJg4.setElementMap(localcpa);
    localcaF1.bb(localJg4);
    localJg4.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(0, 5, 5, 0));
    localJg4.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg4.rV();
    localcaF1.rV();
    cWk localcWk2 = new cWk();
    localcWk2.aJ();
    localcWk2.setElementMap(localcpa);
    localcWk2.setExpandable(false);
    localcWk2.setStyle("white11");
    localcWk2.setMinWidth(190);
    localdRq8.bb(localcWk2);
    localcWk2.brn();
    cWk localcWk3 = localcWk2;
    Jg localJg5 = localcWk3.getAppearance();
    localJg5.setElementMap(localcpa);
    localcWk2.bb(localJg5);
    localJg5.brn();
    bmv localbmv5 = bmv.checkOut();
    localbmv5.setElementMap(localcpa);
    localbmv5.setInsets(new Insets(0, 20, 0, 0));
    localJg5.bb(localbmv5);
    localbmv5.brn();
    localbmv5.rV();
    localJg5.rV();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa);
    localNK4.setName("itemPopupDetail");
    localNK4.setAttribute("text");
    localNK4.setField("characteristic");
    localcWk2.bb(localNK4);
    localNK4.brn();
    localNK4.rV();
    localcWk2.rV();
    localdRq8.rV();
    dRq localdRq11 = dRq.checkOut();
    localdRq11.setElementMap(localcpa);
    localdRq11.setExpandable(false);
    localdRq1.bb(localdRq11);
    localdRq11.brn();
    NK localNK5 = NK.checkOut();
    localNK5.setElementMap(localcpa);
    localNK5.setName("itemPopupDetail");
    localNK5.setAttribute("visible");
    localNK5.setField("bonusByEquiped");
    localdRq11.bb(localNK5);
    localNK5.brn();
    anQ localanQ5 = new anQ();
    localanQ5.aJ();
    localanQ5.setElementMap(localcpa);
    localanQ5.setValue("false");
    localanQ5.setElseValue("true");
    localNK5.bb(localanQ5);
    localanQ5.brn();
    bSP localbSP2 = new bSP();
    localbSP2.aJ();
    localbSP2.setElementMap(localcpa);
    localbSP2.setValue("");
    localanQ5.bb(localbSP2);
    localbSP2.brn();
    localbSP2.rV();
    localanQ5.rV();
    localNK5.rV();
    aId localaId3 = aId.checkOut();
    localaId3.setHorizontal(false);
    localdRq11.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    dRq localdRq12 = dRq.checkOut();
    localdRq12.setElementMap(localcpa);
    localdRq12.setExpandable(false);
    localdRq12.setStyle("lineSeparator2");
    localdRq12.setPrefSize(new Or(50, 1));
    localdRq11.bb(localdRq12);
    localdRq12.brn();
    dRq localdRq13 = localdRq12;
    Jg localJg6 = localdRq13.getAppearance();
    localJg6.setElementMap(localcpa);
    localdRq12.bb(localJg6);
    localJg6.brn();
    bmv localbmv6 = bmv.checkOut();
    localbmv6.setElementMap(localcpa);
    localbmv6.setInsets(new Insets(5, 20, 5, 20));
    localJg6.bb(localbmv6);
    localbmv6.brn();
    localbmv6.rV();
    localJg6.rV();
    localdRq12.rV();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setExpandable(false);
    String str3 = "%set.bonus%";
    str3 = str3.replace("%set.bonus%", cBQ.cxL().mL("set.bonus"));
    localcaF3.setText(str3);
    localcaF3.setStyle("11BoldLight");
    localdRq11.bb(localcaF3);
    localcaF3.brn();
    caF localcaF4 = localcaF3;
    Jg localJg7 = localcaF4.getAppearance();
    localJg7.setElementMap(localcpa);
    localcaF3.bb(localJg7);
    localJg7.brn();
    bmv localbmv7 = bmv.checkOut();
    localbmv7.setElementMap(localcpa);
    localbmv7.setInsets(new Insets(0, 5, 5, 0));
    localJg7.bb(localbmv7);
    localbmv7.brn();
    localbmv7.rV();
    localJg7.rV();
    localcaF3.rV();
    cWk localcWk4 = new cWk();
    localcWk4.aJ();
    localcWk4.setElementMap(localcpa);
    localcWk4.setExpandable(false);
    localcWk4.setStyle("white11");
    localcWk4.setMinWidth(190);
    localdRq11.bb(localcWk4);
    localcWk4.brn();
    cWk localcWk5 = localcWk4;
    Jg localJg8 = localcWk5.getAppearance();
    localJg8.setElementMap(localcpa);
    localcWk4.bb(localJg8);
    localJg8.brn();
    bmv localbmv8 = bmv.checkOut();
    localbmv8.setElementMap(localcpa);
    localbmv8.setInsets(new Insets(0, 20, 0, 0));
    localJg8.bb(localbmv8);
    localbmv8.brn();
    localbmv8.rV();
    localJg8.rV();
    NK localNK6 = NK.checkOut();
    localNK6.setElementMap(localcpa);
    localNK6.setName("itemPopupDetail");
    localNK6.setAttribute("text");
    localNK6.setField("bonusByEquiped");
    localcWk4.bb(localNK6);
    localNK6.brn();
    localNK6.rV();
    localcWk4.rV();
    localdRq11.rV();
    localdRq1.rV();
    return localdRq1;
  }
}