import java.awt.Insets;
import java.util.Stack;

public class adk
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    String str1 = "mapWindow";
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localdRq1);
    localdRq1.setNonBlocking(false);
    localdRq1.brn();
    dRq localdRq2 = localdRq1;
    Jg localJg1 = localdRq2.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq1.bb(localJg1);
    localJg1.brn();
    jO localjO = new jO();
    localjO.aJ();
    localjO.setElementMap(localcpa);
    localjO.setColor(new bNa(0.0F, 0.0F, 0.0F, 0.7F));
    localJg1.bb(localjO);
    localjO.brn();
    localjO.rV();
    localJg1.rV();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localcwP1.setAlign(ajb.dhZ);
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    czO localczO1 = new czO();
    localczO1.aJ();
    localdRq1.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq1.bb(localdRq3);
    localdRq3.brn();
    czO localczO2 = new czO();
    localczO2.aJ();
    localczO2.setAdaptToContentSize(true);
    localdRq3.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setSize(new Or(-2, -2));
    localcwP2.setAlign(ajb.dhZ);
    localdRq3.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq3.bb(localdRq4);
    localdRq4.brn();
    czO localczO3 = new czO();
    localczO3.aJ();
    localczO3.setAdaptToContentSize(true);
    localdRq4.bb(localczO3);
    localczO3.brn();
    localczO3.rV();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setSize(new Or(-2, -2));
    localcwP3.setAlign(ajb.dhZ);
    localdRq4.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    dRq localdRq5 = localdRq4;
    Jg localJg2 = localdRq5.getAppearance();
    localJg2.setElementMap(localcpa);
    localdRq4.bb(localJg2);
    localJg2.brn();
    cuR localcuR = new cuR();
    localcuR.aJ();
    localcuR.setElementMap(localcpa);
    localcuR.setInsets(new Insets(100, 50, 100, 50));
    localJg2.bb(localcuR);
    localcuR.brn();
    localcuR.rV();
    localJg2.rV();
    String str2 = "map";
    acq localacq1 = new acq();
    localacq1.aJ();
    localacq1.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localacq1);
    localacq1.setIsoMap(true);
    localacq1.setTooltipHotPoint(bSi.hcG);
    aMB localaMB = new aMB();
    localaMB.hg("wakfu.dragoMap:onMousePress");
    localacq1.setOnMousePress(localaMB);
    adV localadV = new adV();
    localadV.hg("wakfu.dragoMap:onMouseRelease");
    localacq1.setOnMouseRelease(localadV);
    bDy localbDy = new bDy();
    localbDy.hg("wakfu.dragoMap:onMouseEnter");
    localacq1.setOnMouseEnter(localbDy);
    DY localDY = new DY();
    localDY.hg("wakfu.dragoMap:onMouseExit");
    localacq1.setOnMouseExit(localDY);
    ajE localajE = new ajE();
    localajE.hg("wakfu.dragoMap:onMapMove");
    localacq1.setOnMapMove(localajE);
    blg localblg = new blg();
    localblg.hg("wakfu.dragoMap:onMapClick(map)");
    localacq1.setOnMapClick(localblg);
    cnr localcnr = new cnr();
    localcnr.hg("wakfu.dragoMap:adminTP");
    localacq1.setOnMapDoubleClick(localcnr);
    aqC localaqC = new aqC();
    localaqC.hg("wakfu.dragoMap:onMapItemClick");
    localacq1.setOnItemClick(localaqC);
    anx localanx = new anx();
    localanx.hg("wakfu.dragoMap:onMapItemOver");
    localacq1.setOnItemOver(localanx);
    cVk localcVk = new cVk();
    localcVk.hg("wakfu.dragoMap:onMapItemOut");
    localacq1.setOnItemOut(localcVk);
    localacq1.setExpandable(false);
    localdRq4.bb(localacq1);
    localacq1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("mapPath");
    localNK1.setName("map");
    localNK1.setField("map");
    localacq1.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setAttribute("content");
    localNK2.setName("map");
    localNK2.setField("points");
    localacq1.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setAttribute("compassContent");
    localNK3.setName("map");
    localNK3.setField("compass");
    localacq1.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa);
    localNK4.setAttribute("knownMaps");
    localNK4.setName("map");
    localNK4.setField("availableMapsCoords");
    localacq1.bb(localNK4);
    localNK4.brn();
    localNK4.rV();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setSize(new Or(-2, -2));
    localcwP4.setAlign(ajb.dhZ);
    localacq1.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    acq localacq2 = localacq1;
    Jg localJg3 = localacq2.getAppearance();
    localJg3.setElementMap(localcpa);
    localJg3.setShape(bGn.gCB);
    localacq1.bb(localJg3);
    localJg3.brn();
    localJg3.rV();
    localacq1.rV();
    localdRq4.rV();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq3.bb(localdRq6);
    localdRq6.brn();
    dRq localdRq7 = localdRq6;
    Jg localJg4 = localdRq7.getAppearance();
    localJg4.setElementMap(localcpa);
    localdRq6.bb(localJg4);
    localJg4.brn();
    localJg4.rV();
    cwP localcwP5 = new cwP();
    localcwP5.aJ();
    localcwP5.setElementMap(localcpa);
    localcwP5.setSize(new Or(100.0F, 100.0F));
    localdRq6.bb(localcwP5);
    localcwP5.brn();
    localcwP5.rV();
    czO localczO4 = new czO();
    localczO4.aJ();
    localczO4.setAdaptToContentSize(true);
    localdRq6.bb(localczO4);
    localczO4.brn();
    localczO4.rV();
    dRq localdRq8 = dRq.checkOut();
    localdRq8.setElementMap(localcpa);
    localdRq6.bb(localdRq8);
    localdRq8.brn();
    cwP localcwP6 = new cwP();
    localcwP6.aJ();
    localcwP6.setElementMap(localcpa);
    localcwP6.setSize(new Or(-2, -2));
    localcwP6.setXPerc(new cwC(80.0D));
    localcwP6.setYPerc(new cwC(80.0D));
    localdRq8.bb(localcwP6);
    localcwP6.brn();
    localcwP6.rV();
    czO localczO5 = new czO();
    localczO5.aJ();
    localczO5.setAdaptToContentSize(true);
    localdRq8.bb(localczO5);
    localczO5.brn();
    localczO5.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setStyle("mapButtons");
    localdRq8.bb(localczv1);
    localczv1.brn();
    czv localczv2 = localczv1;
    Jg localJg5 = localczv2.getAppearance();
    localJg5.setElementMap(localcpa);
    localczv1.bb(localJg5);
    localJg5.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(5, 0, 0, 0));
    localJg5.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg5.rV();
    cwP localcwP7 = new cwP();
    localcwP7.aJ();
    localcwP7.setElementMap(localcpa);
    localcwP7.setSize(new Or(-2, -2));
    localczv1.bb(localcwP7);
    localcwP7.brn();
    localcwP7.rV();
    localczv1.rV();
    String str3 = "closeMapButton";
    biy localbiy = new biy();
    localbiy.aJ();
    localbiy.setElementMap(localcpa);
    if ((localcpa != null) && (str3 != null))
      localcpa.a(str3, localbiy);
    localbiy.setStyle("mapClose");
    localbiy.setExpandable(false);
    csA localcsA = new csA();
    localcsA.hg("unloadDialog");
    localbiy.setOnClick(localcsA);
    localbiy.setPrefSize(new Or(35, 20));
    localdRq8.bb(localbiy);
    localbiy.brn();
    cwP localcwP8 = new cwP();
    localcwP8.aJ();
    localcwP8.setElementMap(localcpa);
    localcwP8.setSize(new Or(-2, -2));
    localcwP8.setAlign(ajb.dhZ);
    localcwP8.setXOffset(44);
    localcwP8.setYOffset(-15);
    localbiy.bb(localcwP8);
    localcwP8.brn();
    localcwP8.rV();
    localbiy.rV();
    localdRq8.rV();
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa);
    localdRq6.bb(localdRq9);
    localdRq9.brn();
    cwP localcwP9 = new cwP();
    localcwP9.aJ();
    localcwP9.setElementMap(localcpa);
    localcwP9.setSize(new Or(-2, -2));
    localcwP9.setXPerc(new cwC(12.0D));
    localcwP9.setYPerc(new cwC(12.0D));
    localdRq9.bb(localcwP9);
    localcwP9.brn();
    localcwP9.rV();
    czO localczO6 = new czO();
    localczO6.aJ();
    localczO6.setAdaptToContentSize(true);
    localdRq9.bb(localczO6);
    localczO6.brn();
    localczO6.rV();
    czv localczv3 = new czv();
    localczv3.aJ();
    localczv3.setElementMap(localcpa);
    localczv3.setStyle("filterBackground");
    localdRq9.bb(localczv3);
    localczv3.brn();
    czv localczv4 = localczv3;
    Jg localJg6 = localczv4.getAppearance();
    localJg6.setElementMap(localcpa);
    localczv3.bb(localJg6);
    localJg6.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(5, 0, 0, 0));
    localJg6.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg6.rV();
    cwP localcwP10 = new cwP();
    localcwP10.aJ();
    localcwP10.setElementMap(localcpa);
    localcwP10.setSize(new Or(-2, -2));
    localczv3.bb(localcwP10);
    localcwP10.brn();
    localcwP10.rV();
    localczv3.rV();
    ccG localccG1 = new ccG();
    localccG1.aJ();
    localccG1.setElementMap(localcpa);
    localccG1.setCellSize(new Or(64, 32));
    localccG1.setListLayoutMode(cD.RN);
    localccG1.setIsoColumnCount(1);
    localccG1.setIsoPositiveFactor(false);
    localccG1.setExpandable(false);
    localdRq9.bb(localccG1);
    localccG1.brn();
    cwP localcwP11 = new cwP();
    localcwP11.aJ();
    localcwP11.setElementMap(localcpa);
    localcwP11.setSize(new Or(-2, -2));
    localcwP11.setAlign(ajb.dhT);
    localcwP11.setXOffset(-4);
    localcwP11.setYOffset(-2);
    localccG1.bb(localcwP11);
    localcwP11.brn();
    localcwP11.rV();
    ccG localccG2 = localccG1;
    Jg localJg7 = localccG2.getAppearance();
    localJg7.setElementMap(localcpa);
    localccG1.bb(localJg7);
    localJg7.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 30, 0, 0));
    localJg7.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg7.rV();
    NK localNK5 = NK.checkOut();
    localNK5.setElementMap(localcpa);
    localNK5.setAttribute("content");
    localNK5.setName("landMark.filters");
    localNK5.setField("typeFilterList");
    localccG1.bb(localNK5);
    localNK5.brn();
    localNK5.rV();
    eR localeR = new eR();
    localeR.aJ();
    localeR.setElementMap(localcpa);
    localccG1.bb(localeR);
    localeR.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localeR.bb(localanQ);
    localanQ.brn();
    bxx localbxx = new bxx();
    localbxx.aJ();
    localbxx.setElementMap(localcpa);
    localanQ.bb(localbxx);
    localbxx.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localbxx.bb(localanE);
    localanE.brn();
    localanE.rV();
    localbxx.rV();
    localanQ.rV();
    String str4 = "typeFilter";
    avo localavo = new avo();
    localavo.aJ();
    localavo.setElementMap(localcpa);
    if ((localcpa != null) && (str4 != null))
      localcpa.a(str4, localavo);
    localeR.bb(localavo);
    localavo.brn();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("value");
    localaaE1.setField("id");
    localavo.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    localavo.rV();
    String str5 = "filter";
    br localbr1 = new br();
    localbr1.aJ();
    localbr1.setElementMap(localcpa);
    if ((localcpa != null) && (str5 != null))
      localcpa.a(str5, localbr1);
    bvO localbvO1 = new bvO();
    localbvO1.hg("wakfu.dragoMap:setTypeFilter(typeFilter)");
    localbr1.setOnSelectionChange(localbvO1);
    cCu localcCu1 = new cCu();
    localcCu1.hg("popup(filterDescPopup,filter)");
    localbr1.setOnPopupDisplay(localcCu1);
    jL localjL1 = new jL();
    localjL1.hg("closePopup");
    localbr1.setOnPopupHide(localjL1);
    localeR.bb(localbr1);
    localbr1.brn();
    br localbr2 = localbr1;
    Jg localJg8 = localbr2.getAppearance();
    localJg8.setElementMap(localcpa);
    localbr1.bb(localJg8);
    localJg8.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(0, 0, 0, 43));
    localJg8.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg8.rV();
    String str6 = "filterDescPopup";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa);
    if ((localcpa != null) && (str6 != null))
      localcpa.a(str6, localanG);
    localanG.setAlign(aFG.ecn);
    localanG.setHotSpotPosition(aFG.ech);
    localbr1.bb(localanG);
    localanG.brn();
    dRq localdRq10 = dRq.checkOut();
    localdRq10.setElementMap(localcpa);
    localdRq10.setPrefSize(new Or(10, 0));
    localdRq10.setStyle("popup");
    localanG.bb(localdRq10);
    localdRq10.brn();
    cba localcba = cba.checkOut();
    localcba.setElementMap(localcpa);
    localcba.setData(cFu.izV);
    localdRq10.bb(localcba);
    localcba.brn();
    localcba.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("White11");
    localdRq10.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg9 = localcWk2.getAppearance();
    localJg9.setElementMap(localcpa);
    ((cwJ)localJg9).setAlignment(aFG.ecj);
    localcWk1.bb(localJg9);
    localJg9.brn();
    localJg9.rV();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("text");
    localaaE2.setField("name");
    localcWk1.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    localcWk1.rV();
    localdRq10.rV();
    localanG.rV();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.eck);
    localbr1.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    aaE localaaE3 = new aaE();
    localaaE3.aJ();
    localaaE3.setElementMap(localcpa);
    localaaE3.setAttribute("style");
    localaaE3.setField("style");
    localbr1.bb(localaaE3);
    localaaE3.brn();
    localaaE3.rV();
    aaE localaaE4 = new aaE();
    localaaE4.aJ();
    localaaE4.setElementMap(localcpa);
    localaaE4.setAttribute("selected");
    localaaE4.setField("selected");
    localbr1.bb(localaaE4);
    localaaE4.brn();
    localaaE4.rV();
    localbr1.rV();
    localeR.rV();
    localccG1.rV();
    String str7 = "territoryFilter";
    br localbr3 = new br();
    localbr3.aJ();
    localbr3.setElementMap(localcpa);
    if ((localcpa != null) && (str7 != null))
      localcpa.a(str7, localbr3);
    localbr3.setStyle("filterTerritory");
    bvO localbvO2 = new bvO();
    localbvO2.hg("wakfu.dragoMap:setDisplayTerritories");
    localbr3.setOnSelectionChange(localbvO2);
    localbr3.setExpandable(false);
    cCu localcCu2 = new cCu();
    localcCu2.hg("popup(filterDescPopup,territoryFilter)");
    localbr3.setOnPopupDisplay(localcCu2);
    jL localjL2 = new jL();
    localjL2.hg("closePopup");
    localbr3.setOnPopupHide(localjL2);
    localdRq9.bb(localbr3);
    localbr3.brn();
    a(localbr3);
    b(localbr3);
    d(localbr3);
    localbr3.rV();
    localdRq9.rV();
    localdRq6.rV();
    localdRq3.rV();
    e(localdRq1);
    f(localdRq1);
    localdRq1.rV();
    return localdRq1;
  }

  public bdj a(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setAlign(ajb.dih);
    localcwP.setYOffset(24);
    localcwP.setXOffset(-40);
    parambdj.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    return localcwP;
  }

  public bdj b(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setName("map");
    localNK.setAttribute("selected");
    localNK.setField("displayTerritories");
    parambdj.bb(localNK);
    localNK.brn();
    localNK.rV();
    return localNK;
  }

  public bdj d(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    String str1 = "filterDescPopup";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localanG);
    localanG.setAlign(aFG.ecn);
    localanG.setHotSpotPosition(aFG.ech);
    parambdj.bb(localanG);
    localanG.brn();
    dRq localdRq = dRq.checkOut();
    localdRq.setElementMap(localcpa);
    localdRq.setPrefSize(new Or(10, 0));
    localdRq.setStyle("popup");
    localanG.bb(localdRq);
    localdRq.brn();
    cba localcba = cba.checkOut();
    localcba.setElementMap(localcpa);
    localcba.setData(cFu.izV);
    localdRq.bb(localcba);
    localcba.brn();
    localcba.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("White11");
    String str2 = "%map.territories%";
    str2 = str2.replace("%map.territories%", cBQ.cxL().mL("map.territories"));
    localcWk1.setText(str2);
    localdRq.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg = localcWk2.getAppearance();
    localJg.setElementMap(localcpa);
    ((cwJ)localJg).setAlignment(aFG.ecj);
    localcWk1.bb(localJg);
    localJg.brn();
    localJg.rV();
    localcWk1.rV();
    localdRq.rV();
    localanG.rV();
    return localanG;
  }

  public bdj e(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setStyle("new");
    parambdj.bb(localdRq1);
    localdRq1.brn();
    dRq localdRq2 = localdRq1;
    Jg localJg1 = localdRq2.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq1.bb(localJg1);
    localJg1.brn();
    cuR localcuR = new cuR();
    localcuR.aJ();
    localcuR.setElementMap(localcpa);
    localcuR.setInsets(new Insets(5, 15, 5, 15));
    localJg1.bb(localcuR);
    localcuR.brn();
    localcuR.rV();
    localJg1.rV();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setAlign(ajb.dhV);
    localcwP1.setSize(new Or(-2, -2));
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq3.setPrefSize(new Or(66, 66));
    cCu localcCu = new cCu();
    localcCu.hg("popup(protectorDescPopup)");
    localdRq3.setOnPopupDisplay(localcCu);
    jL localjL = new jL();
    localjL.hg("closePopup");
    localdRq3.setOnPopupHide(localjL);
    localdRq1.bb(localdRq3);
    localdRq3.brn();
    czO localczO = new czO();
    localczO.aJ();
    localczO.setAdaptToContentSize(true);
    localdRq3.bb(localczO);
    localczO.brn();
    localczO.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setNeedsScissor(true);
    localdRq3.bb(localdRq4);
    localdRq4.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.dhZ);
    localcwP2.setSize(new Or(46, 46));
    localdRq4.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    auC localauC1 = new auC();
    localauC1.aJ();
    localauC1.setElementMap(localcpa);
    localauC1.setOffsetY(-7.0F);
    localauC1.setOffsetX(1.0F);
    localauC1.setScale(0.75F);
    localauC1.setAnimName("AnimStatique-Neutre");
    localauC1.setDirection(1);
    localdRq4.bb(localauC1);
    localauC1.brn();
    auC localauC2 = localauC1;
    Jg localJg2 = localauC2.getAppearance();
    localJg2.setElementMap(localcpa);
    localauC1.bb(localJg2);
    localJg2.brn();
    jO localjO = new jO();
    localjO.aJ();
    localjO.setElementMap(localcpa);
    localjO.setColor(new bNa(0.0F, 0.0F, 0.0F, 0.5F));
    localJg2.bb(localjO);
    localjO.brn();
    localjO.rV();
    localJg2.rV();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setName("protector");
    localNK1.setAttribute("animatedElement");
    localNK1.setField("animation");
    localauC1.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("protector");
    localNK2.setAttribute("animName");
    localNK2.setField("animName");
    localauC1.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localauC1.rV();
    localdRq4.rV();
    dRq localdRq5 = dRq.checkOut();
    localdRq5.setElementMap(localcpa);
    localdRq5.setStyle("protectorSimpleFrameOver");
    localdRq3.bb(localdRq5);
    localdRq5.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setSize(new Or(100.0F, 100.0F));
    localcwP3.setXOffset(1);
    localcwP3.setYOffset(-1);
    localdRq5.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    localdRq5.rV();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setName("protector");
    localNK3.setAttribute("visible");
    localNK3.setField("currentProtector");
    localdRq3.bb(localNK3);
    localNK3.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localNK3.bb(localanQ1);
    localanQ1.brn();
    boQ localboQ = new boQ();
    localboQ.aJ();
    localboQ.setElementMap(localcpa);
    localanQ1.bb(localboQ);
    localboQ.brn();
    anE localanE1 = new anE();
    localanE1.aJ();
    localanE1.setElementMap(localcpa);
    localboQ.bb(localanE1);
    localanE1.brn();
    localanE1.rV();
    cOk localcOk = new cOk();
    localcOk.aJ();
    localcOk.setElementMap(localcpa);
    localboQ.bb(localcOk);
    localcOk.brn();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa);
    localNK4.setName("protector");
    localNK4.setAttribute("comparedValue");
    localNK4.setField("isStatic");
    localcOk.bb(localNK4);
    localNK4.brn();
    localNK4.rV();
    localcOk.rV();
    localboQ.rV();
    localanQ1.rV();
    localNK3.rV();
    String str = "protectorDescPopup";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa);
    if ((localcpa != null) && (str != null))
      localcpa.a(str, localanG);
    localanG.setAlign(aFG.ecn);
    localanG.setHotSpotPosition(aFG.ech);
    localdRq3.bb(localanG);
    localanG.brn();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq6.setPrefSize(new Or(10, 0));
    localdRq6.setStyle("popup");
    localanG.bb(localdRq6);
    localdRq6.brn();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("White11");
    localdRq6.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg3 = localcWk2.getAppearance();
    localJg3.setElementMap(localcpa);
    ((cwJ)localJg3).setAlign(aFG.ecj);
    localcWk1.bb(localJg3);
    localJg3.brn();
    localJg3.rV();
    NK localNK5 = NK.checkOut();
    localNK5.setElementMap(localcpa);
    localNK5.setAttribute("text");
    localNK5.setName("map");
    localNK5.setField("currentProtectorDescription");
    localcWk1.bb(localNK5);
    localNK5.brn();
    localNK5.rV();
    localcWk1.rV();
    localdRq6.rV();
    localanG.rV();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setAlign(ajb.dhR);
    localcwP4.setSize(new Or(81, 81));
    localcwP4.setYOffset(-1);
    localcwP4.setXOffset(2);
    localdRq3.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    localdRq3.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localdRq7.setPrefSize(new Or(0, 48));
    localdRq1.bb(localdRq7);
    localdRq7.brn();
    dRq localdRq8 = localdRq7;
    Jg localJg4 = localdRq8.getAppearance();
    localJg4.setElementMap(localcpa);
    localdRq7.bb(localJg4);
    localJg4.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(5, 3, 5, 3));
    localJg4.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg4.rV();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(false);
    localdRq7.bb(localaId);
    localaId.brn();
    localaId.rV();
    cWk localcWk3 = new cWk();
    localcWk3.aJ();
    localcWk3.setElementMap(localcpa);
    localcWk3.setStyle("title");
    localdRq7.bb(localcWk3);
    localcWk3.brn();
    cWk localcWk4 = localcWk3;
    Jg localJg5 = localcWk4.getAppearance();
    localJg5.setElementMap(localcpa);
    ((cwJ)localJg5).setAlign(aFG.eck);
    localcWk3.bb(localJg5);
    localJg5.brn();
    localJg5.rV();
    NK localNK6 = NK.checkOut();
    localNK6.setElementMap(localcpa);
    localNK6.setAttribute("text");
    localNK6.setName("map");
    localNK6.setField("currentMapName");
    localcWk3.bb(localNK6);
    localNK6.brn();
    localNK6.rV();
    localcWk3.rV();
    cWk localcWk5 = new cWk();
    localcWk5.aJ();
    localcWk5.setElementMap(localcpa);
    localcWk5.setStyle("title");
    localdRq7.bb(localcWk5);
    localcWk5.brn();
    cWk localcWk6 = localcWk5;
    Jg localJg6 = localcWk6.getAppearance();
    localJg6.setElementMap(localcpa);
    ((cwJ)localJg6).setAlign(aFG.eck);
    localcWk5.bb(localJg6);
    localJg6.brn();
    localJg6.rV();
    NK localNK7 = NK.checkOut();
    localNK7.setElementMap(localcpa);
    localNK7.setAttribute("text");
    localNK7.setName("map");
    localNK7.setField("currentTerritoryName");
    localcWk5.bb(localNK7);
    localNK7.brn();
    localNK7.rV();
    localcWk5.rV();
    localdRq7.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setDisplaySize(new Or(48, 48));
    localdRq1.bb(localczv1);
    localczv1.brn();
    czv localczv2 = localczv1;
    Jg localJg7 = localczv2.getAppearance();
    localJg7.setElementMap(localcpa);
    localczv1.bb(localJg7);
    localJg7.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(5, 0, 5, 5));
    localJg7.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg7.rV();
    NK localNK8 = NK.checkOut();
    localNK8.setElementMap(localcpa);
    localNK8.setAttribute("visible");
    localNK8.setName("map");
    localNK8.setField("currentTerritoryIconUrl");
    localczv1.bb(localNK8);
    localNK8.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localNK8.bb(localanQ2);
    localanQ2.brn();
    anE localanE2 = new anE();
    localanE2.aJ();
    localanE2.setElementMap(localcpa);
    localanQ2.bb(localanE2);
    localanE2.brn();
    localanE2.rV();
    localanQ2.rV();
    localNK8.rV();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv1.bb(localaAR);
    localaAR.brn();
    NK localNK9 = NK.checkOut();
    localNK9.setElementMap(localcpa);
    localNK9.setAttribute("texture");
    localNK9.setName("map");
    localNK9.setField("currentTerritoryIconUrl");
    localaAR.bb(localNK9);
    localNK9.brn();
    localNK9.rV();
    localaAR.rV();
    localczv1.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj f(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    dRq localdRq2 = localdRq1;
    Jg localJg1 = localdRq2.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq1.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 0, 0, 0));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(100.0F, -2));
    localcwP.setAlign(ajb.dif);
    localdRq1.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    aId localaId = aId.checkOut();
    localaId.setAlign(aFG.ecj);
    localdRq1.bb(localaId);
    localaId.brn();
    localaId.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("BigTitle");
    String str = "%map.position%";
    str = str.replace("%map.position%", cBQ.cxL().mL("map.position"));
    localcaF1.setText(str);
    localcaF1.setExpandable(false);
    localdRq1.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg2 = localcaF2.getAppearance();
    localJg2.setElementMap(localcpa);
    localcaF1.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 10, 0, 0));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    localcaF1.rV();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setExpandable(false);
    localcaF3.setStyle("11Light");
    localdRq1.bb(localcaF3);
    localcaF3.brn();
    caF localcaF4 = localcaF3;
    Jg localJg3 = localcaF4.getAppearance();
    localJg3.setElementMap(localcpa);
    localcaF3.bb(localJg3);
    localJg3.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 3, 0, 0));
    localJg3.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg3.rV();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setName("map");
    localNK.setAttribute("text");
    localNK.setField("displayedPosition");
    localcaF3.bb(localNK);
    localNK.brn();
    localNK.rV();
    localcaF3.rV();
    localdRq1.rV();
    return localdRq1;
  }
}