import java.awt.Insets;
import java.util.Stack;

public class ddg
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa1 = (cpa)this.X.peek();
    String str1 = "temporaryTransferInventoryWindow";
    bpn localbpn = new bpn();
    localbpn.aJ();
    localbpn.setElementMap(localcpa1);
    if ((localcpa1 != null) && (str1 != null))
      localcpa1.a(str1, localbpn);
    localbpn.setX(150);
    localbpn.setY(200);
    localbpn.brn();
    czO localczO1 = new czO();
    localczO1.aJ();
    localczO1.setAdaptToContentSize(true);
    localbpn.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa1);
    localbpn.bb(localdRq1);
    localdRq1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa1);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    localdRq1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa1);
    localdRq2.setStyle("windowNew");
    localbpn.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa1);
    localdRq2.bb(localJg1);
    localJg1.brn();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa1);
    localcuR1.setInsets(new Insets(10, 5, 12, 5));
    localJg1.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    localJg1.rV();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa1);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localdRq2.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localaId1.setAlign(aFG.ech);
    localdRq2.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dqa localdqa1 = new dqa();
    localdqa1.aJ();
    localdqa1.setElementMap(localcpa1);
    localdqa1.setExpandable(false);
    localdRq2.bb(localdqa1);
    localdqa1.brn();
    dqa localdqa2 = localdqa1;
    Jg localJg2 = localdqa2.getAppearance();
    localJg2.setElementMap(localcpa1);
    localdqa1.bb(localJg2);
    localJg2.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa1);
    localbmv1.setInsets(new Insets(0, 10, 0, 10));
    localJg2.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg2.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa1);
    localdRq4.setStyle("titleBar");
    localdqa1.bb(localdRq4);
    localdRq4.brn();
    dRq localdRq5 = localdRq4;
    Jg localJg3 = localdRq5.getAppearance();
    localJg3.setElementMap(localcpa1);
    localdRq4.bb(localJg3);
    localJg3.brn();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa1);
    localcuR2.setInsets(new Insets(2, 20, 3, 20));
    localJg3.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    localJg3.rV();
    aId localaId2 = aId.checkOut();
    localaId2.setHorizontal(false);
    localdRq4.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa1);
    localdRq6.setExpandable(false);
    localdRq4.bb(localdRq6);
    localdRq6.brn();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa1);
    localdpm.setAlign(aFG.eck);
    localdRq6.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa1);
    localcaF1.setStyle("StyledBold16White");
    localcaF1.setNonBlocking(true);
    String str2 = "%temporaryInventory.name%";
    str2 = str2.replace("%temporaryInventory.name%", cBQ.cxL().mL("temporaryInventory.name"));
    localcaF1.setText(str2);
    localdRq6.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg4 = localcaF2.getAppearance();
    localJg4.setElementMap(localcpa1);
    ((cwJ)localJg4).setAlign(aFG.eck);
    localcaF1.bb(localJg4);
    localJg4.brn();
    localJg4.rV();
    localcaF1.rV();
    localdRq6.rV();
    localdRq4.rV();
    localdqa1.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa1);
    localdRq2.bb(localdRq7);
    localdRq7.brn();
    dRq localdRq8 = localdRq7;
    Jg localJg5 = localdRq8.getAppearance();
    localJg5.setElementMap(localcpa1);
    localdRq7.bb(localJg5);
    localJg5.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa1);
    localbmv2.setInsets(new Insets(0, 12, 0, 12));
    localJg5.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg5.rV();
    String str3 = "windowContentContainer";
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa1);
    if ((localcpa1 != null) && (str3 != null))
      localcpa1.a(str3, localdRq9);
    localdRq9.setPrefSize(new Or(0, 0));
    localdRq7.bb(localdRq9);
    localdRq9.brn();
    String str4 = "itemList";
    ccG localccG = new ccG();
    localccG.aJ();
    localccG.setElementMap(localcpa1);
    if ((localcpa1 != null) && (str4 != null))
      localcpa1.a(str4, localccG);
    localccG.setExpandable(false);
    localccG.setCellSize(new Or(40, 40));
    localccG.setHorizontal(false);
    localccG.setAutoIdealSize(true);
    localccG.setIdealSizeMaxRows(2);
    localccG.setIdealSizeMinRows(2);
    localccG.setIdealSizeMaxColumns(5);
    localccG.setIdealSizeMinColumns(5);
    localccG.setSelectionTogglable(false);
    fp localfp = new fp();
    localfp.hg("wakfu.temporaryInventory:dropOut()");
    localccG.setOnDropOut(localfp);
    anx localanx = new anx();
    localanx.hg("wakfu.popupInfos:showPopup(itemDetailPopup)");
    localccG.setOnItemOver(localanx);
    cVk localcVk = new cVk();
    localcVk.hg("closePopup");
    localccG.setOnItemOut(localcVk);
    localdRq9.bb(localccG);
    localccG.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa1);
    localNK1.setName("localPlayer");
    localNK1.setField("temporaryTransferInventory/temporaryBagInventory");
    localNK1.setAttribute("content");
    localccG.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    eR localeR1 = new eR();
    localeR1.aJ();
    localeR1.setElementMap(localcpa1);
    bpP localbpP = new bpP();
    localbpP.hg("wakfu.temporaryInventory:onItemDoubleClick()");
    localeR1.setOnItemDoubleClick(localbpP);
    localccG.bb(localeR1);
    localeR1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa1);
    localeR1.bb(localanQ1);
    localanQ1.brn();
    bxx localbxx1 = new bxx();
    localbxx1.aJ();
    localbxx1.setElementMap(localcpa1);
    localanQ1.bb(localbxx1);
    localbxx1.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa1);
    localbxx1.bb(localanE);
    localanE.brn();
    localanE.rV();
    localbxx1.rV();
    localanQ1.rV();
    dRq localdRq10 = dRq.checkOut();
    localdRq10.setElementMap(localcpa1);
    localeR1.bb(localdRq10);
    localdRq10.brn();
    czO localczO2 = new czO();
    localczO2.aJ();
    localczO2.setAdaptToContentSize(true);
    localdRq10.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    String str5 = "itemContainer";
    dRq localdRq11 = dRq.checkOut();
    localdRq11.setElementMap(localcpa1);
    if ((localcpa1 != null) && (str5 != null))
      localcpa1.a(str5, localdRq11);
    localdRq11.setNonBlocking(false);
    localdRq11.setStyle("itemBackground");
    localdRq10.bb(localdRq11);
    localdRq11.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa1);
    localcwP3.setAlign(ajb.dhZ);
    localcwP3.setSize(new Or(43, 43));
    localdRq11.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    bXx localbXx = new bXx();
    localbXx.aJ();
    localbXx.setElementMap(localcpa1);
    dVA localdVA = new dVA();
    localdVA.hg("wakfu.temporaryInventory:dragItem()");
    localbXx.setOnDrag(localdVA);
    localdRq11.bb(localbXx);
    localbXx.brn();
    czO localczO3 = new czO();
    localczO3.aJ();
    localbXx.bb(localczO3);
    localczO3.brn();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa1);
    localczv.setNonBlocking(true);
    localczv.setDisplaySize(new Or(32, 32));
    localczO3.bb(localczv);
    localczv.brn();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa1);
    localcwP4.setAlign(ajb.dhZ);
    localczv.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa1);
    localczv.bb(localaAR);
    localaAR.brn();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa1);
    localaaE1.setAttribute("texture");
    localaaE1.setField("iconUrl");
    localaAR.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    localaAR.rV();
    localczv.rV();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa1);
    localcaF3.setNonBlocking(true);
    localcaF3.setStyle("White10Bordered");
    localczO3.bb(localcaF3);
    localcaF3.brn();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa1);
    localaaE2.setAttribute("visible");
    localaaE2.setField("quantity");
    localcaF3.bb(localaaE2);
    localaaE2.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa1);
    localaaE2.bb(localanQ2);
    localanQ2.brn();
    aEJ localaEJ = new aEJ();
    localaEJ.aJ();
    localaEJ.setElementMap(localcpa1);
    localaEJ.setValue("1");
    localanQ2.bb(localaEJ);
    localaEJ.brn();
    localaEJ.rV();
    localanQ2.rV();
    localaaE2.rV();
    cwP localcwP5 = new cwP();
    localcwP5.aJ();
    localcwP5.setElementMap(localcpa1);
    localcwP5.setAlign(ajb.did);
    localcaF3.bb(localcwP5);
    localcwP5.brn();
    localcwP5.rV();
    caF localcaF4 = localcaF3;
    Jg localJg6 = localcaF4.getAppearance();
    localJg6.setElementMap(localcpa1);
    localcaF3.bb(localJg6);
    localJg6.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa1);
    localbmv3.setInsets(new Insets(0, 6, 6, 0));
    localJg6.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg6.rV();
    aaE localaaE3 = new aaE();
    localaaE3.aJ();
    localaaE3.setElementMap(localcpa1);
    localaaE3.setAttribute("text");
    localaaE3.setField("quantity");
    localcaF3.bb(localaaE3);
    localaaE3.brn();
    localaaE3.rV();
    localcaF3.rV();
    localczO3.rV();
    localbXx.rV();
    localdRq11.rV();
    dRq localdRq12 = dRq.checkOut();
    localdRq12.setElementMap(localcpa1);
    localdRq12.setNonBlocking(true);
    localdRq12.setStyle("ItemBackgroundPerfectVariant");
    localdRq10.bb(localdRq12);
    localdRq12.brn();
    cwP localcwP6 = new cwP();
    localcwP6.aJ();
    localcwP6.setElementMap(localcpa1);
    localcwP6.setAlign(ajb.dhZ);
    localcwP6.setSize(new Or(43, 43));
    localdRq12.bb(localcwP6);
    localcwP6.brn();
    localcwP6.rV();
    aaE localaaE4 = new aaE();
    localaaE4.aJ();
    localaaE4.setElementMap(localcpa1);
    localaaE4.setAttribute("visible");
    localaaE4.setField("isPerfect");
    localdRq12.bb(localaaE4);
    localaaE4.brn();
    localaaE4.rV();
    localdRq12.rV();
    localdRq10.rV();
    localeR1.rV();
    eR localeR2 = new eR();
    localeR2.aJ();
    localeR2.setElementMap(localcpa1);
    localccG.bb(localeR2);
    localeR2.brn();
    anQ localanQ3 = new anQ();
    localanQ3.aJ();
    localanQ3.setElementMap(localcpa1);
    localeR2.bb(localanQ3);
    localanQ3.brn();
    bxx localbxx2 = new bxx();
    localbxx2.aJ();
    localbxx2.setElementMap(localcpa1);
    localanQ3.bb(localbxx2);
    localbxx2.brn();
    aIB localaIB = new aIB();
    localaIB.aJ();
    localaIB.setElementMap(localcpa1);
    localbxx2.bb(localaIB);
    localaIB.brn();
    localaIB.rV();
    localbxx2.rV();
    localanQ3.rV();
    dRq localdRq13 = dRq.checkOut();
    localdRq13.setElementMap(localcpa1);
    localeR2.bb(localdRq13);
    localdRq13.brn();
    czO localczO4 = new czO();
    localczO4.aJ();
    localczO4.setAdaptToContentSize(true);
    localdRq13.bb(localczO4);
    localczO4.brn();
    localczO4.rV();
    String str6 = "itemBackgroundContainer";
    dRq localdRq14 = dRq.checkOut();
    localdRq14.setElementMap(localcpa1);
    if ((localcpa1 != null) && (str6 != null))
      localcpa1.a(str6, localdRq14);
    localdRq14.setStyle("itemBackground");
    localdRq13.bb(localdRq14);
    localdRq14.brn();
    cwP localcwP7 = new cwP();
    localcwP7.aJ();
    localcwP7.setElementMap(localcpa1);
    localcwP7.setSize(new Or(43, 43));
    localcwP7.setAlign(ajb.dhZ);
    localdRq14.bb(localcwP7);
    localcwP7.brn();
    localcwP7.rV();
    localdRq14.rV();
    localdRq13.rV();
    localeR2.rV();
    localccG.rV();
    localdRq9.rV();
    localdRq7.rV();
    localdRq2.rV();
    dRq localdRq15 = dRq.checkOut();
    localdRq15.setElementMap(localcpa1);
    localbpn.bb(localdRq15);
    localdRq15.brn();
    cwP localcwP8 = new cwP();
    localcwP8.aJ();
    localcwP8.setElementMap(localcpa1);
    localcwP8.setSize(new Or(100.0F, 100.0F));
    localdRq15.bb(localcwP8);
    localcwP8.brn();
    localcwP8.rV();
    localdRq15.rV();
    String str7 = "closeTempInventoryButton";
    biy localbiy = new biy();
    localbiy.aJ();
    localbiy.setElementMap(localcpa1);
    if ((localcpa1 != null) && (str7 != null))
      localcpa1.a(str7, localbiy);
    localbiy.setStyle("close");
    localbiy.setExpandable(false);
    csA localcsA = new csA();
    localcsA.hg("wakfu.temporaryInventory:closeTemporaryInventory()");
    localbiy.setOnClick(localcsA);
    localbpn.bb(localbiy);
    localbiy.brn();
    cwP localcwP9 = new cwP();
    localcwP9.aJ();
    localcwP9.setElementMap(localcpa1);
    localcwP9.setSize(new Or(-2, -2));
    localcwP9.setAlign(ajb.dhV);
    localcwP9.setXOffset(-18);
    localcwP9.setYOffset(-12);
    localbiy.bb(localcwP9);
    localcwP9.brn();
    localcwP9.rV();
    localbiy.rV();
    String str8 = "itemDetailPopup";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa1);
    if ((localcpa1 != null) && (str8 != null))
      localcpa1.a(str8, localanG);
    localanG.setAlign(aFG.eci);
    localanG.setHotSpotPosition(aFG.ecg);
    localbpn.bb(localanG);
    localanG.brn();
    cpa localcpa2 = localcpa1;
    localcpa1 = this.Y.nd((localcpa1 != null ? localcpa1.getId() : "") + ".itemDetailPopupInc");
    localcpa1.d(localcpa2);
    this.X.push(localcpa1);
    dRq localdRq16 = dRq.checkOut();
    localdRq16.setElementMap(localcpa1);
    localanG.bb(localdRq16);
    localdRq16.brn();
    dRq localdRq17 = dRq.checkOut();
    localdRq17.setElementMap(localcpa1);
    localdRq17.setVisible(false);
    localdRq16.bb(localdRq17);
    localdRq17.brn();
    aId localaId3 = aId.checkOut();
    localdRq17.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa1);
    localNK2.setName("itemPopupDetail");
    localNK2.setAttribute("visible");
    localdRq17.bb(localNK2);
    localNK2.brn();
    anQ localanQ4 = new anQ();
    localanQ4.aJ();
    localanQ4.setElementMap(localcpa1);
    localNK2.bb(localanQ4);
    localanQ4.brn();
    a(localanQ4);
    localanQ4.rV();
    localNK2.rV();
    b(localdRq17);
    localdRq17.rV();
    localdRq16.rV();
    this.X.pop();
    localcpa1 = (cpa)this.X.peek();
    localanG.rV();
    j(localbpn);
    k(localbpn);
    localbpn.rV();
    return localbpn;
  }

  public bdj a(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    parambdj.bb(localanE);
    localanE.brn();
    localanE.rV();
    return localanE;
  }

  public bdj b(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    localdRq1.setPrefSize(new Or(250, 0));
    localdRq1.setStyle("popup");
    parambdj.bb(localdRq1);
    localdRq1.brn();
    dRq localdRq2 = localdRq1;
    Jg localJg1 = localdRq2.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq1.bb(localJg1);
    localJg1.brn();
    localJg1.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setAlign(aFG.ech);
    localaId1.setHorizontal(false);
    localdRq1.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("DefaultBold14White");
    localcWk1.setExpandable(false);
    localcWk1.setMinWidth(210);
    localdRq1.bb(localcWk1);
    localcWk1.brn();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa);
    localdpm1.setAlign(aFG.ecj);
    localcWk1.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setName("itemPopupDetail");
    localNK1.setAttribute("text");
    localNK1.setField("nameWithRarity");
    localcWk1.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    localcWk1.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq3.setExpandable(false);
    localdRq1.bb(localdRq3);
    localdRq3.brn();
    aId localaId2 = aId.checkOut();
    localdRq3.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setExpandable(false);
    localdRq3.bb(localdRq4);
    localdRq4.brn();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa);
    localdpm2.setAlign(aFG.ech);
    localdRq4.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    czO localczO = new czO();
    localczO.aJ();
    localczO.setAdaptToContentSize(true);
    localdRq4.bb(localczO);
    localczO.brn();
    localczO.rV();
    dRq localdRq5 = localdRq4;
    Jg localJg2 = localdRq5.getAppearance();
    localJg2.setElementMap(localcpa);
    localdRq4.bb(localJg2);
    localJg2.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 0, 0, 2));
    localJg2.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg2.rV();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq6.setStyle("caracs");
    localdRq4.bb(localdRq6);
    localdRq6.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localdRq6.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    localdRq6.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setDisplaySize(new Or(64, 64));
    localdRq4.bb(localczv1);
    localczv1.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.dhZ);
    localcwP2.setSize(new Or(-2, -2));
    localczv1.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv1.bb(localaAR);
    localaAR.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("itemPopupDetail");
    localNK2.setAttribute("texture");
    localNK2.setField("iconUrl");
    localaAR.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localaAR.rV();
    localczv1.rV();
    localdRq4.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localdRq3.bb(localdRq7);
    localdRq7.brn();
    dRq localdRq8 = localdRq7;
    Jg localJg3 = localdRq8.getAppearance();
    localJg3.setElementMap(localcpa);
    localdRq7.bb(localJg3);
    localJg3.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 0, 0, 0));
    localJg3.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg3.rV();
    aId localaId3 = aId.checkOut();
    localaId3.setHorizontal(false);
    localaId3.setAlign(aFG.ech);
    localdRq7.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    cWk localcWk2 = new cWk();
    localcWk2.aJ();
    localcWk2.setElementMap(localcpa);
    localcWk2.setStyle("11light");
    localcWk2.setExpandable(false);
    localdRq7.bb(localcWk2);
    localcWk2.brn();
    dpm localdpm3 = new dpm();
    localdpm3.aJ();
    localdpm3.setElementMap(localcpa);
    localdpm3.setAlign(aFG.ecl);
    localcWk2.bb(localdpm3);
    localdpm3.brn();
    localdpm3.rV();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setName("itemPopupDetail");
    localNK3.setAttribute("text");
    localNK3.setField("levelDescription");
    localcWk2.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    localcWk2.rV();
    cWk localcWk3 = new cWk();
    localcWk3.aJ();
    localcWk3.setElementMap(localcpa);
    localcWk3.setStyle("white11");
    localcWk3.setMultiline(false);
    localcWk3.setExpandable(false);
    localdRq7.bb(localcWk3);
    localcWk3.brn();
    dpm localdpm4 = new dpm();
    localdpm4.aJ();
    localdpm4.setElementMap(localcpa);
    localdpm4.setAlign(aFG.ecj);
    localcWk3.bb(localdpm4);
    localdpm4.brn();
    localdpm4.rV();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa);
    localNK4.setAttribute("text");
    localNK4.setName("itemPopupDetail");
    localNK4.setField("type");
    localcWk3.bb(localNK4);
    localNK4.brn();
    localNK4.rV();
    localcWk3.rV();
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa);
    localdRq9.setExpandable(false);
    localdRq7.bb(localdRq9);
    localdRq9.brn();
    dpm localdpm5 = new dpm();
    localdpm5.aJ();
    localdpm5.setElementMap(localcpa);
    localdpm5.setAlign(aFG.ecl);
    localdRq9.bb(localdpm5);
    localdpm5.brn();
    localdpm5.rV();
    NK localNK5 = NK.checkOut();
    localNK5.setElementMap(localcpa);
    localNK5.setName("itemPopupDetail");
    localNK5.setAttribute("visible");
    localNK5.setField("ap");
    localdRq9.bb(localNK5);
    localNK5.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localNK5.bb(localanQ1);
    localanQ1.brn();
    bJJ localbJJ = new bJJ();
    localbJJ.aJ();
    localbJJ.setElementMap(localcpa);
    localanQ1.bb(localbJJ);
    localbJJ.brn();
    jA localjA1 = new jA();
    localjA1.aJ();
    localjA1.setElementMap(localcpa);
    localjA1.setValue("0");
    localbJJ.bb(localjA1);
    localjA1.brn();
    localjA1.rV();
    cOk localcOk = new cOk();
    localcOk.aJ();
    localcOk.setElementMap(localcpa);
    localbJJ.bb(localcOk);
    localcOk.brn();
    NK localNK6 = NK.checkOut();
    localNK6.setElementMap(localcpa);
    localNK6.setName("itemPopupDetail");
    localNK6.setAttribute("comparedValue");
    localNK6.setField("usableInFight");
    localcOk.bb(localNK6);
    localNK6.brn();
    localNK6.rV();
    localcOk.rV();
    localbJJ.rV();
    localanQ1.rV();
    localNK5.rV();
    dRq localdRq10 = dRq.checkOut();
    localdRq10.setElementMap(localcpa);
    localdRq10.setExpandable(false);
    localdRq9.bb(localdRq10);
    localdRq10.brn();
    dpm localdpm6 = new dpm();
    localdpm6.aJ();
    localdpm6.setElementMap(localcpa);
    localdpm6.setAlign(aFG.ecl);
    localdRq10.bb(localdpm6);
    localdpm6.brn();
    localdpm6.rV();
    aId localaId4 = aId.checkOut();
    localaId4.setHgap((short)2);
    localdRq10.bb(localaId4);
    localaId4.brn();
    localaId4.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("11Light");
    localdRq10.bb(localcaF1);
    localcaF1.brn();
    NK localNK7 = NK.checkOut();
    localNK7.setElementMap(localcpa);
    localNK7.setName("itemPopupDetail");
    localNK7.setAttribute("text");
    localNK7.setField("ap");
    localcaF1.bb(localNK7);
    localNK7.brn();
    localNK7.rV();
    localcaF1.rV();
    czv localczv2 = new czv();
    localczv2.aJ();
    localczv2.setElementMap(localcpa);
    localczv2.setStyle("iconAP");
    localczv2.setExpandable(false);
    localdRq10.bb(localczv2);
    localczv2.brn();
    localczv2.rV();
    localdRq10.rV();
    localdRq9.rV();
    dRq localdRq11 = dRq.checkOut();
    localdRq11.setElementMap(localcpa);
    localdRq11.setExpandable(false);
    localdRq7.bb(localdRq11);
    localdRq11.brn();
    dpm localdpm7 = new dpm();
    localdpm7.aJ();
    localdpm7.setElementMap(localcpa);
    localdpm7.setAlign(aFG.ecl);
    localdRq11.bb(localdpm7);
    localdpm7.brn();
    localdpm7.rV();
    NK localNK8 = NK.checkOut();
    localNK8.setElementMap(localcpa);
    localNK8.setName("itemPopupDetail");
    localNK8.setAttribute("visible");
    localNK8.setField("range");
    localdRq11.bb(localNK8);
    localNK8.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localNK8.bb(localanQ2);
    localanQ2.brn();
    anE localanE1 = new anE();
    localanE1.aJ();
    localanE1.setElementMap(localcpa);
    localanQ2.bb(localanE1);
    localanE1.brn();
    localanE1.rV();
    localanQ2.rV();
    localNK8.rV();
    dRq localdRq12 = dRq.checkOut();
    localdRq12.setElementMap(localcpa);
    localdRq12.setExpandable(false);
    localdRq11.bb(localdRq12);
    localdRq12.brn();
    dpm localdpm8 = new dpm();
    localdpm8.aJ();
    localdpm8.setElementMap(localcpa);
    localdpm8.setAlign(aFG.ecl);
    localdRq12.bb(localdpm8);
    localdpm8.brn();
    localdpm8.rV();
    aId localaId5 = aId.checkOut();
    localaId5.setHgap((short)2);
    localdRq12.bb(localaId5);
    localaId5.brn();
    localaId5.rV();
    caF localcaF2 = new caF();
    localcaF2.aJ();
    localcaF2.setElementMap(localcpa);
    localcaF2.setStyle("11Light");
    localdRq12.bb(localcaF2);
    localcaF2.brn();
    NK localNK9 = NK.checkOut();
    localNK9.setElementMap(localcpa);
    localNK9.setName("itemPopupDetail");
    localNK9.setAttribute("text");
    localNK9.setField("range");
    localcaF2.bb(localNK9);
    localNK9.brn();
    localNK9.rV();
    localcaF2.rV();
    czv localczv3 = new czv();
    localczv3.aJ();
    localczv3.setElementMap(localcpa);
    localczv3.setStyle("rangeIcon");
    localczv3.setExpandable(false);
    localdRq12.bb(localczv3);
    localczv3.brn();
    localczv3.rV();
    localdRq12.rV();
    localdRq11.rV();
    localdRq7.rV();
    localdRq3.rV();
    dRq localdRq13 = dRq.checkOut();
    localdRq13.setElementMap(localcpa);
    localdRq13.setExpandable(false);
    localdRq1.bb(localdRq13);
    localdRq13.brn();
    aId localaId6 = aId.checkOut();
    localaId6.setHorizontal(false);
    localdRq13.bb(localaId6);
    localaId6.brn();
    localaId6.rV();
    NK localNK10 = NK.checkOut();
    localNK10.setElementMap(localcpa);
    localNK10.setAttribute("visible");
    localNK10.setName("itemPopupDetail");
    localNK10.setField("description");
    localdRq13.bb(localNK10);
    localNK10.brn();
    anQ localanQ3 = new anQ();
    localanQ3.aJ();
    localanQ3.setElementMap(localcpa);
    localNK10.bb(localanQ3);
    localanQ3.brn();
    anE localanE2 = new anE();
    localanE2.aJ();
    localanE2.setElementMap(localcpa);
    localanQ3.bb(localanE2);
    localanE2.brn();
    localanE2.rV();
    localanQ3.rV();
    localNK10.rV();
    dRq localdRq14 = dRq.checkOut();
    localdRq14.setElementMap(localcpa);
    localdRq14.setExpandable(false);
    localdRq14.setStyle("lineSeparator2");
    localdRq14.setPrefSize(new Or(50, 1));
    localdRq13.bb(localdRq14);
    localdRq14.brn();
    dRq localdRq15 = localdRq14;
    Jg localJg4 = localdRq15.getAppearance();
    localJg4.setElementMap(localcpa);
    localdRq14.bb(localJg4);
    localJg4.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(5, 20, 5, 20));
    localJg4.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg4.rV();
    localdRq14.rV();
    cWk localcWk4 = new cWk();
    localcWk4.aJ();
    localcWk4.setElementMap(localcpa);
    localcWk4.setStyle("narrow12");
    localcWk4.setMinWidth(1);
    localcWk4.setMaxWidth(250);
    localcWk4.setExpandable(false);
    localdRq13.bb(localcWk4);
    localcWk4.brn();
    cWk localcWk5 = localcWk4;
    Jg localJg5 = localcWk5.getAppearance();
    localJg5.setElementMap(localcpa);
    localcWk4.bb(localJg5);
    localJg5.brn();
    cAf localcAf = cAf.checkOut();
    localcAf.setElementMap(localcpa);
    localcAf.setColor(new bNa(0.98F, 0.77F, 0.0F, 1.0F));
    localJg5.bb(localcAf);
    localcAf.brn();
    localcAf.rV();
    localJg5.rV();
    NK localNK11 = NK.checkOut();
    localNK11.setElementMap(localcpa);
    localNK11.setName("itemPopupDetail");
    localNK11.setAttribute("text");
    localNK11.setField("description");
    localcWk4.bb(localNK11);
    localNK11.brn();
    localNK11.rV();
    localcWk4.rV();
    localdRq13.rV();
    dRq localdRq16 = dRq.checkOut();
    localdRq16.setElementMap(localcpa);
    localdRq16.setExpandable(false);
    localdRq1.bb(localdRq16);
    localdRq16.brn();
    NK localNK12 = NK.checkOut();
    localNK12.setElementMap(localcpa);
    localNK12.setAttribute("visible");
    localNK12.setName("itemPopupDetail");
    localNK12.setField("requirement");
    localdRq16.bb(localNK12);
    localNK12.brn();
    anQ localanQ4 = new anQ();
    localanQ4.aJ();
    localanQ4.setElementMap(localcpa);
    localNK12.bb(localanQ4);
    localanQ4.brn();
    jA localjA2 = new jA();
    localjA2.aJ();
    localjA2.setElementMap(localcpa);
    localjA2.setValue("");
    localanQ4.bb(localjA2);
    localjA2.brn();
    localjA2.rV();
    localanQ4.rV();
    localNK12.rV();
    aId localaId7 = aId.checkOut();
    localaId7.setHorizontal(false);
    localdRq16.bb(localaId7);
    localaId7.brn();
    localaId7.rV();
    dRq localdRq17 = dRq.checkOut();
    localdRq17.setElementMap(localcpa);
    localdRq17.setExpandable(false);
    localdRq17.setStyle("lineSeparator2");
    localdRq17.setPrefSize(new Or(50, 1));
    localdRq16.bb(localdRq17);
    localdRq17.brn();
    dRq localdRq18 = localdRq17;
    Jg localJg6 = localdRq18.getAppearance();
    localJg6.setElementMap(localcpa);
    localdRq17.bb(localJg6);
    localJg6.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(5, 20, 5, 20));
    localJg6.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg6.rV();
    localdRq17.rV();
    cWk localcWk6 = new cWk();
    localcWk6.aJ();
    localcWk6.setElementMap(localcpa);
    localcWk6.setExpandable(false);
    localcWk6.setStyle("white11");
    localcWk6.setMinWidth(250);
    localdRq16.bb(localcWk6);
    localcWk6.brn();
    d(localcWk6);
    e(localcWk6);
    localcWk6.rV();
    localdRq16.rV();
    f(localdRq1);
    g(localdRq1);
    h(localdRq1);
    i(localdRq1);
    localdRq1.rV();
    return localdRq1;
  }

  public bdj d(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dOc localdOc = (dOc)parambdj;
    Jg localJg = localdOc.getAppearance();
    localJg.setElementMap(localcpa);
    parambdj.bb(localJg);
    localJg.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(0, 0, 0, 0));
    localJg.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg.rV();
    return localJg;
  }

  public bdj e(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setName("itemPopupDetail");
    localNK.setAttribute("text");
    localNK.setField("requirement");
    parambdj.bb(localNK);
    localNK.brn();
    localNK.rV();
    return localNK;
  }

  public bdj f(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("visible");
    localNK1.setName("itemPopupDetail");
    localNK1.setField("useRequirement");
    localdRq1.bb(localNK1);
    localNK1.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localNK1.bb(localanQ);
    localanQ.brn();
    jA localjA = new jA();
    localjA.aJ();
    localjA.setElementMap(localcpa);
    localjA.setValue("");
    localanQ.bb(localjA);
    localjA.brn();
    localjA.rV();
    localanQ.rV();
    localNK1.rV();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(false);
    localdRq1.bb(localaId);
    localaId.brn();
    localaId.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setExpandable(false);
    localdRq2.setStyle("lineSeparator2");
    localdRq2.setPrefSize(new Or(50, 1));
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(5, 20, 5, 20));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    localdRq2.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setExpandable(false);
    String str = "%use.requirements%";
    str = str.replace("%use.requirements%", cBQ.cxL().mL("use.requirements"));
    localcaF1.setText(str);
    localcaF1.setStyle("11BoldLight");
    localcaF1.setNonBlocking(true);
    localdRq1.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg2 = localcaF2.getAppearance();
    localJg2.setElementMap(localcpa);
    localcaF1.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 5, 5, 0));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    localcaF1.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setExpandable(false);
    localcWk1.setStyle("white11");
    localcWk1.setMinWidth(1);
    localcWk1.setMaxWidth(250);
    localcWk1.setNonBlocking(true);
    localdRq1.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg3 = localcWk2.getAppearance();
    localJg3.setElementMap(localcpa);
    localcWk1.bb(localJg3);
    localJg3.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 20, 0, 0));
    localJg3.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg3.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("itemPopupDetail");
    localNK2.setAttribute("text");
    localNK2.setField("useRequirement");
    localcWk1.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localcWk1.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj g(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("visible");
    localNK1.setName("itemPopupDetail");
    localNK1.setField("hasCaracteristic");
    localdRq1.bb(localNK1);
    localNK1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localNK1.bb(localanQ1);
    localanQ1.brn();
    cOk localcOk = new cOk();
    localcOk.aJ();
    localcOk.setElementMap(localcpa);
    localanQ1.bb(localcOk);
    localcOk.brn();
    localcOk.rV();
    localanQ1.rV();
    localNK1.rV();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(false);
    localdRq1.bb(localaId);
    localaId.brn();
    localaId.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setExpandable(false);
    localdRq2.setStyle("lineSeparator2");
    localdRq2.setPrefSize(new Or(0, 1));
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(5, 20, 5, 20));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    localdRq2.rV();
    at localat = new at();
    localat.aJ();
    localat.setElementMap(localcpa);
    localat.setHorizontal(false);
    localdRq1.bb(localat);
    localat.brn();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.ecj);
    localat.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("itemPopupDetail");
    localNK2.setAttribute("content");
    localNK2.setField("caracteristic");
    localat.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    eR localeR = new eR();
    localeR.aJ();
    localeR.setElementMap(localcpa);
    localat.bb(localeR);
    localeR.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localeR.bb(localanQ2);
    localanQ2.brn();
    bxx localbxx = new bxx();
    localbxx.aJ();
    localbxx.setElementMap(localcpa);
    localanQ2.bb(localbxx);
    localbxx.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localbxx.bb(localanE);
    localanE.brn();
    localanE.rV();
    localbxx.rV();
    localanQ2.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localeR.bb(localdRq4);
    localdRq4.brn();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("white11");
    localcWk1.setMultiline(false);
    localcWk1.setMinWidth(250);
    localcWk1.setMaxWidth(250);
    localcWk1.setExpandable(false);
    localdRq4.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg2 = localcWk2.getAppearance();
    localJg2.setElementMap(localcpa);
    localcWk1.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 5, 0, 0));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    aaE localaaE = new aaE();
    localaaE.aJ();
    localaaE.setElementMap(localcpa);
    localaaE.setAttribute("text");
    localcWk1.bb(localaaE);
    localaaE.brn();
    localaaE.rV();
    localcWk1.rV();
    localdRq4.rV();
    localeR.rV();
    localat.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj h(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("visible");
    localNK1.setName("itemPopupDetail");
    localNK1.setField("effect");
    localdRq1.bb(localNK1);
    localNK1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localNK1.bb(localanQ1);
    localanQ1.brn();
    anE localanE1 = new anE();
    localanE1.aJ();
    localanE1.setElementMap(localcpa);
    localanQ1.bb(localanE1);
    localanE1.brn();
    localanE1.rV();
    localanQ1.rV();
    localNK1.rV();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(false);
    localdRq1.bb(localaId);
    localaId.brn();
    localaId.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setExpandable(false);
    localdRq2.setStyle("lineSeparator2");
    localdRq2.setPrefSize(new Or(50, 1));
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(5, 20, 5, 20));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    localdRq2.rV();
    at localat = new at();
    localat.aJ();
    localat.setElementMap(localcpa);
    localat.setHorizontal(false);
    localdRq1.bb(localat);
    localat.brn();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.ecj);
    localat.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    eR localeR = new eR();
    localeR.aJ();
    localeR.setElementMap(localcpa);
    localat.bb(localeR);
    localeR.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localeR.bb(localanQ2);
    localanQ2.brn();
    bxx localbxx = new bxx();
    localbxx.aJ();
    localbxx.setElementMap(localcpa);
    localanQ2.bb(localbxx);
    localbxx.brn();
    anE localanE2 = new anE();
    localanE2.aJ();
    localanE2.setElementMap(localcpa);
    localbxx.bb(localanE2);
    localanE2.brn();
    localanE2.rV();
    localbxx.rV();
    localanQ2.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localeR.bb(localdRq4);
    localdRq4.brn();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("white11");
    localcWk1.setMultiline(false);
    localcWk1.setMinWidth(250);
    localcWk1.setMaxWidth(250);
    localcWk1.setExpandable(false);
    localdRq4.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg2 = localcWk2.getAppearance();
    localJg2.setElementMap(localcpa);
    localcWk1.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 5, 0, 0));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    aaE localaaE = new aaE();
    localaaE.aJ();
    localaaE.setElementMap(localcpa);
    localaaE.setAttribute("text");
    localcWk1.bb(localaaE);
    localaaE.brn();
    localaaE.rV();
    localcWk1.rV();
    localdRq4.rV();
    localeR.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("itemPopupDetail");
    localNK2.setAttribute("content");
    localNK2.setField("effectDetails");
    localat.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localat.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj i(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("visible");
    localNK1.setName("itemPopupDetail");
    localNK1.setField("storingCapacity");
    localdRq1.bb(localNK1);
    localNK1.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localNK1.bb(localanQ);
    localanQ.brn();
    aEJ localaEJ = new aEJ();
    localaEJ.aJ();
    localaEJ.setElementMap(localcpa);
    localaEJ.setValue("0");
    localanQ.bb(localaEJ);
    localaEJ.brn();
    localaEJ.rV();
    localanQ.rV();
    localNK1.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localdRq1.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setExpandable(false);
    localdRq2.setStyle("lineSeparator2");
    localdRq2.setPrefSize(new Or(50, 1));
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(5, 20, 5, 20));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    localdRq2.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq1.bb(localdRq4);
    localdRq4.brn();
    aId localaId2 = aId.checkOut();
    localaId2.setAlign(aFG.ecj);
    localdRq4.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("whiteBold");
    localcaF1.setNonBlocking(true);
    String str1 = "%capacity%";
    str1 = str1.replace("%capacity%", cBQ.cxL().mL("capacity"));
    localcaF1.setText(str1);
    localcaF1.setExpandable(false);
    localdRq4.bb(localcaF1);
    localcaF1.brn();
    cba localcba1 = cba.checkOut();
    localcba1.setElementMap(localcpa);
    localcba1.setData(cFu.izT);
    localcaF1.bb(localcba1);
    localcba1.brn();
    localcba1.rV();
    caF localcaF2 = localcaF1;
    Jg localJg2 = localcaF2.getAppearance();
    localJg2.setElementMap(localcpa);
    localcaF1.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 5, 0, 0));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    localcaF1.rV();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setStyle("white");
    localcaF3.setNonBlocking(true);
    String str2 = "%capacity%";
    str2 = str2.replace("%capacity%", cBQ.cxL().mL("capacity"));
    localcaF3.setText(str2);
    localcaF3.setExpandable(false);
    localdRq4.bb(localcaF3);
    localcaF3.brn();
    cba localcba2 = cba.checkOut();
    localcba2.setElementMap(localcpa);
    localcba2.setData(cFu.izT);
    localcaF3.bb(localcba2);
    localcba2.brn();
    localcba2.rV();
    caF localcaF4 = localcaF3;
    Jg localJg3 = localcaF4.getAppearance();
    localJg3.setElementMap(localcpa);
    localcaF3.bb(localJg3);
    localJg3.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 5, 0, 0));
    localJg3.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg3.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setAttribute("text");
    localNK2.setName("itemPopupDetail");
    localNK2.setField("storingCapacity");
    localcaF3.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localcaF3.rV();
    localdRq4.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj j(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(-2, -2));
    parambdj.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    return localcwP;
  }

  public bdj k(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    String str = "bag";
    avo localavo = new avo();
    localavo.aJ();
    localavo.setElementMap(localcpa);
    if ((localcpa != null) && (str != null))
      localcpa.a(str, localavo);
    parambdj.bb(localavo);
    localavo.brn();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setLocal(true);
    localNK.setName("editableBag");
    localNK.setAttribute("value");
    localavo.bb(localNK);
    localNK.brn();
    localNK.rV();
    localavo.rV();
    return localavo;
  }
}