import java.awt.Insets;
import java.util.Stack;

public class bkU
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa1 = (cpa)this.X.peek();
    String str1 = "window";
    bpn localbpn = new bpn();
    localbpn.aJ();
    localbpn.setElementMap(localcpa1);
    if ((localcpa1 != null) && (str1 != null))
      localcpa1.a(str1, localbpn);
    localbpn.setPack(true);
    aFU localaFU = new aFU();
    localaFU.hg("wakfu.windowStick:stickShortcutBar(shortcutBar)");
    localbpn.setOnStick(localaFU);
    localbpn.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa1);
    localNK1.setAttribute("visible");
    localNK1.setName("localPlayer");
    localNK1.setField("shortcutBarManager/displaySymbiotBar");
    localbpn.bb(localNK1);
    localNK1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa1);
    localNK1.bb(localanQ1);
    localanQ1.brn();
    bqW localbqW = new bqW();
    localbqW.aJ();
    localbqW.setElementMap(localcpa1);
    localanQ1.bb(localbqW);
    localbqW.brn();
    localbqW.rV();
    localanQ1.rV();
    localNK1.rV();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa1);
    localcwP.setSize(new Or(-2, -2));
    localcwP.setAlign(ajb.dih);
    localcwP.setXOffset(-150);
    localcwP.setYOffset(50);
    localcwP.setInitValue(true);
    localbpn.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    String str2 = "spellDetailPopup";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa1);
    if ((localcpa1 != null) && (str2 != null))
      localcpa1.a(str2, localanG);
    localanG.setAlign(aFG.ech);
    localanG.setHotSpotPosition(aFG.ecn);
    localbpn.bb(localanG);
    localanG.brn();
    cpa localcpa2 = localcpa1;
    localcpa1 = this.Y.nd((localcpa1 != null ? localcpa1.getId() : "") + ".itemDetailPopupInc");
    localcpa1.d(localcpa2);
    this.X.push(localcpa1);
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa1);
    localanG.bb(localdRq1);
    localdRq1.brn();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa1);
    localdRq2.setStyle("popup");
    localdRq2.setPrefSize(new Or(240, 0));
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa1);
    localNK2.setName("describedSpell");
    localNK2.setAttribute("visible");
    localdRq2.bb(localNK2);
    localNK2.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa1);
    localNK2.bb(localanQ2);
    localanQ2.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa1);
    localanQ2.bb(localanE);
    localanE.brn();
    localanE.rV();
    localanQ2.rV();
    localNK2.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localaId1.setAlign(aFG.ech);
    localdRq2.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa1);
    localdRq3.setExpandable(false);
    localdRq2.bb(localdRq3);
    localdRq3.brn();
    aId localaId2 = aId.checkOut();
    localaId2.setHorizontal(false);
    localdRq3.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa1);
    localdRq3.bb(localdRq4);
    localdRq4.brn();
    dRq localdRq5 = dRq.checkOut();
    localdRq5.setElementMap(localcpa1);
    localdRq5.setExpandable(false);
    localdRq4.bb(localdRq5);
    localdRq5.brn();
    aId localaId3 = aId.checkOut();
    localaId3.setAlign(aFG.ecj);
    localdRq5.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa1);
    localczv1.setPrefSize(new Or(24, 24));
    localczv1.setExpandable(false);
    localdRq5.bb(localczv1);
    localczv1.brn();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa1);
    localdpm1.setAlign(aFG.eck);
    localczv1.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa1);
    localczv1.bb(localaAR);
    localaAR.brn();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa1);
    localNK3.setName("describedSpell");
    localNK3.setAttribute("texture");
    localNK3.setField("elementsUsedIconURL");
    localaAR.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    localaAR.rV();
    localczv1.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa1);
    localcWk1.setStyle("DefaultBold14White");
    localcWk1.setExpandable(false);
    localcWk1.setMinWidth(1);
    localcWk1.setMaxWidth(180);
    localdRq5.bb(localcWk1);
    localcWk1.brn();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa1);
    localdpm2.setAlign(aFG.eck);
    localcWk1.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    cWk localcWk2 = localcWk1;
    Jg localJg1 = localcWk2.getAppearance();
    localJg1.setElementMap(localcpa1);
    ((cwJ)localJg1).setAlign(aFG.ecg);
    localcWk1.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa1);
    localbmv1.setInsets(new Insets(0, 5, 0, 0));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa1);
    localNK4.setName("describedSpell");
    localNK4.setAttribute("text");
    localNK4.setField("name");
    localcWk1.bb(localNK4);
    localNK4.brn();
    localNK4.rV();
    localcWk1.rV();
    localdRq5.rV();
    dAS localdAS = new dAS();
    localdAS.aJ();
    localdAS.setElementMap(localcpa1);
    localdRq4.bb(localdAS);
    localdAS.brn();
    localdAS.rV();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa1);
    localdRq6.setExpandable(false);
    localdRq4.bb(localdRq6);
    localdRq6.brn();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa1);
    localcaF1.setStyle("11light");
    localdRq6.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg2 = localcaF2.getAppearance();
    localJg2.setElementMap(localcpa1);
    localcaF1.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa1);
    localbmv2.setInsets(new Insets(0, 5, 0, 0));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    cAf localcAf = cAf.checkOut();
    localcAf.setElementMap(localcpa1);
    localcAf.setColor(new bNa(1.0F, 1.0F, 1.0F, 1.0F));
    localJg2.bb(localcAf);
    localcAf.brn();
    localcAf.rV();
    localJg2.rV();
    NK localNK5 = NK.checkOut();
    localNK5.setElementMap(localcpa1);
    localNK5.setName("describedSpell");
    localNK5.setAttribute("text");
    localNK5.setField("levelTextShort");
    localcaF1.bb(localNK5);
    localNK5.brn();
    localNK5.rV();
    localcaF1.rV();
    localdRq6.rV();
    localdRq4.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa1);
    localdRq7.setExpandable(false);
    localdRq3.bb(localdRq7);
    localdRq7.brn();
    dRq localdRq8 = localdRq7;
    Jg localJg3 = localdRq8.getAppearance();
    localJg3.setElementMap(localcpa1);
    localdRq7.bb(localJg3);
    localJg3.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa1);
    localbmv3.setInsets(new Insets(0, 0, 0, 0));
    localJg3.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg3.rV();
    aId localaId4 = aId.checkOut();
    localaId4.setAlign(aFG.ecl);
    localdRq7.bb(localaId4);
    localaId4.brn();
    localaId4.rV();
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa1);
    localdRq9.setExpandable(false);
    localdRq9.setVisible(false);
    localdRq7.bb(localdRq9);
    localdRq9.brn();
    aId localaId5 = aId.checkOut();
    localaId5.setHgap((short)2);
    localdRq9.bb(localaId5);
    localaId5.brn();
    localaId5.rV();
    NK localNK6 = NK.checkOut();
    localNK6.setElementMap(localcpa1);
    localNK6.setAttribute("visible");
    localNK6.setName("describedSpell");
    localNK6.setField("ap");
    localdRq9.bb(localNK6);
    localNK6.brn();
    anQ localanQ3 = new anQ();
    localanQ3.aJ();
    localanQ3.setElementMap(localcpa1);
    localNK6.bb(localanQ3);
    localanQ3.brn();
    aEJ localaEJ1 = new aEJ();
    localaEJ1.aJ();
    localaEJ1.setElementMap(localcpa1);
    localaEJ1.setValue("0");
    localanQ3.bb(localaEJ1);
    localaEJ1.brn();
    localaEJ1.rV();
    localanQ3.rV();
    localNK6.rV();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa1);
    localcaF3.setStyle("11Light");
    localcaF3.setExpandable(false);
    localdRq9.bb(localcaF3);
    localcaF3.brn();
    NK localNK7 = NK.checkOut();
    localNK7.setElementMap(localcpa1);
    localNK7.setName("describedSpell");
    localNK7.setAttribute("text");
    localNK7.setField("ap");
    localcaF3.bb(localNK7);
    localNK7.brn();
    localNK7.rV();
    localcaF3.rV();
    czv localczv2 = new czv();
    localczv2.aJ();
    localczv2.setElementMap(localcpa1);
    localczv2.setStyle("iconAP");
    localczv2.setExpandable(false);
    localdRq9.bb(localczv2);
    localczv2.brn();
    localczv2.rV();
    dRq localdRq10 = localdRq9;
    Jg localJg4 = localdRq10.getAppearance();
    localJg4.setElementMap(localcpa1);
    localdRq9.bb(localJg4);
    localJg4.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa1);
    localbmv4.setInsets(new Insets(0, 3, 0, 0));
    localJg4.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg4.rV();
    localdRq9.rV();
    dRq localdRq11 = dRq.checkOut();
    localdRq11.setElementMap(localcpa1);
    localdRq11.setExpandable(false);
    localdRq11.setVisible(false);
    localdRq7.bb(localdRq11);
    localdRq11.brn();
    aId localaId6 = aId.checkOut();
    localaId6.setHgap((short)2);
    localdRq11.bb(localaId6);
    localaId6.brn();
    localaId6.rV();
    NK localNK8 = NK.checkOut();
    localNK8.setElementMap(localcpa1);
    localNK8.setAttribute("visible");
    localNK8.setName("describedSpell");
    localNK8.setField("chrage");
    localdRq11.bb(localNK8);
    localNK8.brn();
    anQ localanQ4 = new anQ();
    localanQ4.aJ();
    localanQ4.setElementMap(localcpa1);
    localNK8.bb(localanQ4);
    localanQ4.brn();
    aEJ localaEJ2 = new aEJ();
    localaEJ2.aJ();
    localaEJ2.setElementMap(localcpa1);
    localaEJ2.setValue("0");
    localanQ4.bb(localaEJ2);
    localaEJ2.brn();
    localaEJ2.rV();
    localanQ4.rV();
    localNK8.rV();
    caF localcaF4 = new caF();
    localcaF4.aJ();
    localcaF4.setElementMap(localcpa1);
    localcaF4.setStyle("11Light");
    localcaF4.setExpandable(false);
    localdRq11.bb(localcaF4);
    localcaF4.brn();
    NK localNK9 = NK.checkOut();
    localNK9.setElementMap(localcpa1);
    localNK9.setName("describedSpell");
    localNK9.setAttribute("text");
    localNK9.setField("chrage");
    localcaF4.bb(localNK9);
    localNK9.brn();
    localNK9.rV();
    localcaF4.rV();
    czv localczv3 = new czv();
    localczv3.aJ();
    localczv3.setElementMap(localcpa1);
    localczv3.setStyle("iconCHRAGE");
    localczv3.setExpandable(false);
    localdRq11.bb(localczv3);
    localczv3.brn();
    localczv3.rV();
    dRq localdRq12 = localdRq11;
    Jg localJg5 = localdRq12.getAppearance();
    localJg5.setElementMap(localcpa1);
    localdRq11.bb(localJg5);
    localJg5.brn();
    bmv localbmv5 = bmv.checkOut();
    localbmv5.setElementMap(localcpa1);
    localbmv5.setInsets(new Insets(0, 3, 0, 0));
    localJg5.bb(localbmv5);
    localbmv5.brn();
    localbmv5.rV();
    localJg5.rV();
    localdRq11.rV();
    dRq localdRq13 = dRq.checkOut();
    localdRq13.setElementMap(localcpa1);
    localdRq13.setExpandable(false);
    localdRq13.setVisible(false);
    localdRq7.bb(localdRq13);
    localdRq13.brn();
    aId localaId7 = aId.checkOut();
    localaId7.setHgap((short)2);
    localdRq13.bb(localaId7);
    localaId7.brn();
    localaId7.rV();
    NK localNK10 = NK.checkOut();
    localNK10.setElementMap(localcpa1);
    localNK10.setAttribute("visible");
    localNK10.setName("describedSpell");
    localNK10.setField("mp");
    localdRq13.bb(localNK10);
    localNK10.brn();
    anQ localanQ5 = new anQ();
    localanQ5.aJ();
    localanQ5.setElementMap(localcpa1);
    localNK10.bb(localanQ5);
    localanQ5.brn();
    aEJ localaEJ3 = new aEJ();
    localaEJ3.aJ();
    localaEJ3.setElementMap(localcpa1);
    localaEJ3.setValue("0");
    localanQ5.bb(localaEJ3);
    localaEJ3.brn();
    localaEJ3.rV();
    localanQ5.rV();
    localNK10.rV();
    caF localcaF5 = new caF();
    localcaF5.aJ();
    localcaF5.setElementMap(localcpa1);
    localcaF5.setStyle("11Light");
    localcaF5.setExpandable(false);
    localdRq13.bb(localcaF5);
    localcaF5.brn();
    NK localNK11 = NK.checkOut();
    localNK11.setElementMap(localcpa1);
    localNK11.setName("describedSpell");
    localNK11.setAttribute("text");
    localNK11.setField("mp");
    localcaF5.bb(localNK11);
    localNK11.brn();
    localNK11.rV();
    localcaF5.rV();
    czv localczv4 = new czv();
    localczv4.aJ();
    localczv4.setElementMap(localcpa1);
    localczv4.setStyle("iconMP");
    localczv4.setExpandable(false);
    localdRq13.bb(localczv4);
    localczv4.brn();
    localczv4.rV();
    dRq localdRq14 = localdRq13;
    Jg localJg6 = localdRq14.getAppearance();
    localJg6.setElementMap(localcpa1);
    localdRq13.bb(localJg6);
    localJg6.brn();
    bmv localbmv6 = bmv.checkOut();
    localbmv6.setElementMap(localcpa1);
    localbmv6.setInsets(new Insets(0, 3, 0, 0));
    localJg6.bb(localbmv6);
    localbmv6.brn();
    localbmv6.rV();
    localJg6.rV();
    localdRq13.rV();
    dRq localdRq15 = dRq.checkOut();
    localdRq15.setElementMap(localcpa1);
    localdRq15.setExpandable(false);
    localdRq15.setVisible(false);
    localdRq7.bb(localdRq15);
    localdRq15.brn();
    aId localaId8 = aId.checkOut();
    localaId8.setHgap((short)2);
    localdRq15.bb(localaId8);
    localaId8.brn();
    localaId8.rV();
    NK localNK12 = NK.checkOut();
    localNK12.setElementMap(localcpa1);
    localNK12.setAttribute("visible");
    localNK12.setName("describedSpell");
    localNK12.setField("wp");
    localdRq15.bb(localNK12);
    localNK12.brn();
    anQ localanQ6 = new anQ();
    localanQ6.aJ();
    localanQ6.setElementMap(localcpa1);
    localNK12.bb(localanQ6);
    localanQ6.brn();
    aEJ localaEJ4 = new aEJ();
    localaEJ4.aJ();
    localaEJ4.setElementMap(localcpa1);
    localaEJ4.setValue("0");
    localanQ6.bb(localaEJ4);
    localaEJ4.brn();
    localaEJ4.rV();
    localanQ6.rV();
    localNK12.rV();
    caF localcaF6 = new caF();
    localcaF6.aJ();
    localcaF6.setElementMap(localcpa1);
    localcaF6.setStyle("11Light");
    localcaF6.setExpandable(false);
    localdRq15.bb(localcaF6);
    localcaF6.brn();
    NK localNK13 = NK.checkOut();
    localNK13.setElementMap(localcpa1);
    localNK13.setName("describedSpell");
    localNK13.setAttribute("text");
    localNK13.setField("wp");
    localcaF6.bb(localNK13);
    localNK13.brn();
    localNK13.rV();
    localcaF6.rV();
    a(localdRq15);
    b(localdRq15);
    localdRq15.rV();
    d(localdRq7);
    localdRq7.rV();
    localdRq3.rV();
    e(localdRq2);
    f(localdRq2);
    g(localdRq2);
    h(localdRq2);
    localdRq2.rV();
    localdRq1.rV();
    this.X.pop();
    localcpa1 = (cpa)this.X.peek();
    localanG.rV();
    i(localbpn);
    m(localbpn);
    r(localbpn);
    s(localbpn);
    localbpn.rV();
    return localbpn;
  }

  public bdj a(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setStyle("iconWP");
    localczv.setExpandable(false);
    parambdj.bb(localczv);
    localczv.brn();
    localczv.rV();
    return localczv;
  }

  public bdj b(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dOc localdOc = (dOc)parambdj;
    Jg localJg = localdOc.getAppearance();
    localJg.setElementMap(localcpa);
    parambdj.bb(localJg);
    localJg.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(0, 3, 0, 0));
    localJg.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg.rV();
    return localJg;
  }

  public bdj d(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    dRq localdRq2 = localdRq1;
    Jg localJg1 = localdRq2.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq1.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(2, 0, 0, 0));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.ecl);
    localdRq1.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    aId localaId = aId.checkOut();
    localaId.setHgap((short)2);
    localdRq1.bb(localaId);
    localaId.brn();
    localaId.rV();
    caF localcaF = new caF();
    localcaF.aJ();
    localcaF.setElementMap(localcpa);
    localcaF.setStyle("11Light");
    localdRq1.bb(localcaF);
    localcaF.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setName("describedSpell");
    localNK1.setAttribute("text");
    localNK1.setField("range");
    localcaF.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    localcaF.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setStyle("rangeIcon");
    localczv1.setExpandable(false);
    localdRq1.bb(localczv1);
    localczv1.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("describedSpell");
    localNK2.setAttribute("style");
    localNK2.setField("testLineOfSight");
    localczv1.bb(localNK2);
    localNK2.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localanQ.setValue("rangeIcon");
    localanQ.setElseValue("noLineOfSightIcon");
    localNK2.bb(localanQ);
    localanQ.brn();
    cOk localcOk = new cOk();
    localcOk.aJ();
    localcOk.setElementMap(localcpa);
    localanQ.bb(localcOk);
    localcOk.brn();
    localcOk.rV();
    localanQ.rV();
    localNK2.rV();
    localczv1.rV();
    czv localczv2 = new czv();
    localczv2.aJ();
    localczv2.setElementMap(localcpa);
    localczv2.setStyle("UnlockedRange");
    localczv2.setExpandable(false);
    localczv2.setNonBlocking(false);
    localdRq1.bb(localczv2);
    localczv2.brn();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setName("describedSpell");
    localNK3.setAttribute("visible");
    localNK3.setField("modifiableRange");
    localczv2.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    localczv2.rV();
    czv localczv3 = new czv();
    localczv3.aJ();
    localczv3.setElementMap(localcpa);
    localczv3.setStyle("SpellInLine");
    localczv3.setExpandable(false);
    localczv3.setNonBlocking(false);
    localdRq1.bb(localczv3);
    localczv3.brn();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa);
    localNK4.setName("describedSpell");
    localNK4.setAttribute("visible");
    localNK4.setField("castOnlyInLine");
    localczv3.bb(localNK4);
    localNK4.brn();
    localNK4.rV();
    localczv3.rV();
    dRq localdRq3 = localdRq1;
    Jg localJg2 = localdRq3.getAppearance();
    localJg2.setElementMap(localcpa);
    localdRq1.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 3, 0, 0));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj e(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(false);
    localaId.setAlign(aFG.ech);
    localdRq1.bb(localaId);
    localaId.brn();
    localaId.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setExpandable(false);
    localdRq2.setStyle("lineSeparator2");
    localdRq2.setPrefSize(new Or(50, 1));
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(5, 20, 5, 20));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    localdRq2.rV();
    at localat = new at();
    localat.aJ();
    localat.setElementMap(localcpa);
    localat.setHorizontal(false);
    localdRq1.bb(localat);
    localat.brn();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.ecj);
    localat.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("visible");
    localNK1.setName("describedSpell");
    localNK1.setField("effectNumber");
    localat.bb(localNK1);
    localNK1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localanQ1.setValue("false");
    localanQ1.setElseValue("true");
    localNK1.bb(localanQ1);
    localanQ1.brn();
    bSP localbSP = new bSP();
    localbSP.aJ();
    localbSP.setElementMap(localcpa);
    localbSP.setValue("0");
    localanQ1.bb(localbSP);
    localbSP.brn();
    localbSP.rV();
    localanQ1.rV();
    localNK1.rV();
    eR localeR = new eR();
    localeR.aJ();
    localeR.setElementMap(localcpa);
    localat.bb(localeR);
    localeR.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localeR.bb(localanQ2);
    localanQ2.brn();
    bxx localbxx = new bxx();
    localbxx.aJ();
    localbxx.setElementMap(localcpa);
    localanQ2.bb(localbxx);
    localbxx.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localbxx.bb(localanE);
    localanE.brn();
    localanE.rV();
    localbxx.rV();
    localanQ2.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localeR.bb(localdRq4);
    localdRq4.brn();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("white11");
    localcWk1.setMultiline(false);
    localcWk1.setMinWidth(250);
    localcWk1.setMaxWidth(250);
    localcWk1.setExpandable(false);
    localdRq4.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg2 = localcWk2.getAppearance();
    localJg2.setElementMap(localcpa);
    localcWk1.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 5, 0, 0));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    aaE localaaE = new aaE();
    localaaE.aJ();
    localaaE.setElementMap(localcpa);
    localaaE.setAttribute("text");
    localcWk1.bb(localaaE);
    localaaE.brn();
    localaaE.rV();
    localcWk1.rV();
    localdRq4.rV();
    localeR.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("describedSpell");
    localNK2.setAttribute("content");
    localNK2.setField("shortDescription");
    localat.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localat.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj f(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(false);
    localaId.setAlign(aFG.ech);
    localdRq1.bb(localaId);
    localaId.brn();
    localaId.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setExpandable(false);
    localdRq2.setStyle("lineSeparator2");
    localdRq2.setPrefSize(new Or(50, 1));
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(5, 20, 5, 20));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    localdRq2.rV();
    at localat = new at();
    localat.aJ();
    localat.setElementMap(localcpa);
    localat.setHorizontal(false);
    localdRq1.bb(localat);
    localat.brn();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.ecj);
    localat.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    eR localeR = new eR();
    localeR.aJ();
    localeR.setElementMap(localcpa);
    localat.bb(localeR);
    localeR.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localeR.bb(localanQ1);
    localanQ1.brn();
    bxx localbxx = new bxx();
    localbxx.aJ();
    localbxx.setElementMap(localcpa);
    localanQ1.bb(localbxx);
    localbxx.brn();
    anE localanE1 = new anE();
    localanE1.aJ();
    localanE1.setElementMap(localcpa);
    localbxx.bb(localanE1);
    localanE1.brn();
    localanE1.rV();
    localbxx.rV();
    localanQ1.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localeR.bb(localdRq4);
    localdRq4.brn();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("white11");
    localcWk1.setMultiline(false);
    localcWk1.setMinWidth(250);
    localcWk1.setMaxWidth(250);
    localcWk1.setExpandable(false);
    localdRq4.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg2 = localcWk2.getAppearance();
    localJg2.setElementMap(localcpa);
    localcWk1.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 5, 0, 0));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    aaE localaaE = new aaE();
    localaaE.aJ();
    localaaE.setElementMap(localcpa);
    localaaE.setAttribute("text");
    localcWk1.bb(localaaE);
    localaaE.brn();
    localaaE.rV();
    localcWk1.rV();
    localdRq4.rV();
    localeR.rV();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setName("describedSpell");
    localNK1.setAttribute("content");
    localNK1.setField("conditionsDescription");
    localat.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    localat.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setAttribute("visible");
    localNK2.setName("describedSpell");
    localNK2.setField("conditionsDescription");
    localdRq1.bb(localNK2);
    localNK2.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localNK2.bb(localanQ2);
    localanQ2.brn();
    anE localanE2 = new anE();
    localanE2.aJ();
    localanE2.setElementMap(localcpa);
    localanQ2.bb(localanE2);
    localanE2.brn();
    localanE2.rV();
    localanQ2.rV();
    localNK2.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj g(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    localdRq1.setStyle("lineSeparator2");
    localdRq1.setPrefSize(new Or(50, 1));
    parambdj.bb(localdRq1);
    localdRq1.brn();
    dRq localdRq2 = localdRq1;
    Jg localJg = localdRq2.getAppearance();
    localJg.setElementMap(localcpa);
    localdRq1.bb(localJg);
    localJg.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(5, 20, 5, 20));
    localJg.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj h(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setExpandable(false);
    localcaF1.setMultiline(true);
    localcaF1.setMinWidth(0);
    localcaF1.setStyle("PopupInformation");
    String str = "%rightClickToShowDetailWindow%";
    str = str.replace("%rightClickToShowDetailWindow%", cBQ.cxL().mL("rightClickToShowDetailWindow"));
    localcaF1.setText(str);
    parambdj.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg = localcaF2.getAppearance();
    localJg.setElementMap(localcpa);
    ((cwJ)localJg).setAlignment(aFG.ecj);
    localcaF1.bb(localJg);
    localJg.brn();
    localJg.rV();
    localcaF1.rV();
    return localcaF1;
  }

  public bdj i(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    String str1 = "itemDetailPopup";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localanG);
    localanG.setAlign(aFG.ech);
    localanG.setHotSpotPosition(aFG.ecn);
    parambdj.bb(localanG);
    localanG.brn();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localanG.bb(localdRq1);
    localdRq1.brn();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setVisible(false);
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    aId localaId1 = aId.checkOut();
    localdRq2.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setName("itemPopupDetail");
    localNK1.setAttribute("visible");
    localdRq2.bb(localNK1);
    localNK1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localNK1.bb(localanQ1);
    localanQ1.brn();
    anE localanE1 = new anE();
    localanE1.aJ();
    localanE1.setElementMap(localcpa);
    localanQ1.bb(localanE1);
    localanE1.brn();
    localanE1.rV();
    localanQ1.rV();
    localNK1.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq3.setExpandable(false);
    localdRq3.setPrefSize(new Or(250, 0));
    localdRq3.setStyle("popup");
    localdRq2.bb(localdRq3);
    localdRq3.brn();
    dRq localdRq4 = localdRq3;
    Jg localJg1 = localdRq4.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq3.bb(localJg1);
    localJg1.brn();
    localJg1.rV();
    aId localaId2 = aId.checkOut();
    localaId2.setAlign(aFG.ech);
    localaId2.setHorizontal(false);
    localdRq3.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("DefaultBold14White");
    localcWk1.setExpandable(false);
    localcWk1.setMinWidth(210);
    localdRq3.bb(localcWk1);
    localcWk1.brn();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa);
    localdpm1.setAlign(aFG.ecj);
    localcWk1.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("itemPopupDetail");
    localNK2.setAttribute("text");
    localNK2.setField("nameWithRarity");
    localcWk1.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localcWk1.rV();
    dRq localdRq5 = dRq.checkOut();
    localdRq5.setElementMap(localcpa);
    localdRq5.setExpandable(false);
    localdRq3.bb(localdRq5);
    localdRq5.brn();
    aId localaId3 = aId.checkOut();
    localdRq5.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq6.setExpandable(false);
    localdRq5.bb(localdRq6);
    localdRq6.brn();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa);
    localdpm2.setAlign(aFG.ech);
    localdRq6.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    czO localczO = new czO();
    localczO.aJ();
    localczO.setAdaptToContentSize(true);
    localdRq6.bb(localczO);
    localczO.brn();
    localczO.rV();
    dRq localdRq7 = localdRq6;
    Jg localJg2 = localdRq7.getAppearance();
    localJg2.setElementMap(localcpa);
    localdRq6.bb(localJg2);
    localJg2.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 0, 0, 2));
    localJg2.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg2.rV();
    dRq localdRq8 = dRq.checkOut();
    localdRq8.setElementMap(localcpa);
    localdRq8.setStyle("caracs");
    localdRq6.bb(localdRq8);
    localdRq8.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localdRq8.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    localdRq8.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setDisplaySize(new Or(64, 64));
    localdRq6.bb(localczv1);
    localczv1.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.dhZ);
    localcwP2.setSize(new Or(-2, -2));
    localczv1.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv1.bb(localaAR);
    localaAR.brn();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setName("itemPopupDetail");
    localNK3.setAttribute("texture");
    localNK3.setField("iconUrl");
    localaAR.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    localaAR.rV();
    localczv1.rV();
    localdRq6.rV();
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa);
    localdRq5.bb(localdRq9);
    localdRq9.brn();
    dRq localdRq10 = localdRq9;
    Jg localJg3 = localdRq10.getAppearance();
    localJg3.setElementMap(localcpa);
    localdRq9.bb(localJg3);
    localJg3.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 0, 0, 0));
    localJg3.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg3.rV();
    aId localaId4 = aId.checkOut();
    localaId4.setHorizontal(false);
    localaId4.setAlign(aFG.ech);
    localdRq9.bb(localaId4);
    localaId4.brn();
    localaId4.rV();
    cWk localcWk2 = new cWk();
    localcWk2.aJ();
    localcWk2.setElementMap(localcpa);
    localcWk2.setStyle("11light");
    localcWk2.setExpandable(false);
    localdRq9.bb(localcWk2);
    localcWk2.brn();
    dpm localdpm3 = new dpm();
    localdpm3.aJ();
    localdpm3.setElementMap(localcpa);
    localdpm3.setAlign(aFG.ecl);
    localcWk2.bb(localdpm3);
    localdpm3.brn();
    localdpm3.rV();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa);
    localNK4.setName("itemPopupDetail");
    localNK4.setAttribute("text");
    localNK4.setField("levelDescription");
    localcWk2.bb(localNK4);
    localNK4.brn();
    localNK4.rV();
    localcWk2.rV();
    cWk localcWk3 = new cWk();
    localcWk3.aJ();
    localcWk3.setElementMap(localcpa);
    localcWk3.setStyle("white11");
    localcWk3.setMultiline(false);
    localcWk3.setExpandable(false);
    localdRq9.bb(localcWk3);
    localcWk3.brn();
    dpm localdpm4 = new dpm();
    localdpm4.aJ();
    localdpm4.setElementMap(localcpa);
    localdpm4.setAlign(aFG.ecj);
    localcWk3.bb(localdpm4);
    localdpm4.brn();
    localdpm4.rV();
    NK localNK5 = NK.checkOut();
    localNK5.setElementMap(localcpa);
    localNK5.setAttribute("text");
    localNK5.setName("itemPopupDetail");
    localNK5.setField("type");
    localcWk3.bb(localNK5);
    localNK5.brn();
    localNK5.rV();
    localcWk3.rV();
    dRq localdRq11 = dRq.checkOut();
    localdRq11.setElementMap(localcpa);
    localdRq11.setExpandable(false);
    localdRq9.bb(localdRq11);
    localdRq11.brn();
    dpm localdpm5 = new dpm();
    localdpm5.aJ();
    localdpm5.setElementMap(localcpa);
    localdpm5.setAlign(aFG.ecl);
    localdRq11.bb(localdpm5);
    localdpm5.brn();
    localdpm5.rV();
    NK localNK6 = NK.checkOut();
    localNK6.setElementMap(localcpa);
    localNK6.setName("itemPopupDetail");
    localNK6.setAttribute("visible");
    localNK6.setField("ap");
    localdRq11.bb(localNK6);
    localNK6.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localNK6.bb(localanQ2);
    localanQ2.brn();
    bJJ localbJJ = new bJJ();
    localbJJ.aJ();
    localbJJ.setElementMap(localcpa);
    localanQ2.bb(localbJJ);
    localbJJ.brn();
    jA localjA1 = new jA();
    localjA1.aJ();
    localjA1.setElementMap(localcpa);
    localjA1.setValue("0");
    localbJJ.bb(localjA1);
    localjA1.brn();
    localjA1.rV();
    cOk localcOk = new cOk();
    localcOk.aJ();
    localcOk.setElementMap(localcpa);
    localbJJ.bb(localcOk);
    localcOk.brn();
    NK localNK7 = NK.checkOut();
    localNK7.setElementMap(localcpa);
    localNK7.setName("itemPopupDetail");
    localNK7.setAttribute("comparedValue");
    localNK7.setField("usableInFight");
    localcOk.bb(localNK7);
    localNK7.brn();
    localNK7.rV();
    localcOk.rV();
    localbJJ.rV();
    localanQ2.rV();
    localNK6.rV();
    dRq localdRq12 = dRq.checkOut();
    localdRq12.setElementMap(localcpa);
    localdRq12.setExpandable(false);
    localdRq11.bb(localdRq12);
    localdRq12.brn();
    dpm localdpm6 = new dpm();
    localdpm6.aJ();
    localdpm6.setElementMap(localcpa);
    localdpm6.setAlign(aFG.ecl);
    localdRq12.bb(localdpm6);
    localdpm6.brn();
    localdpm6.rV();
    aId localaId5 = aId.checkOut();
    localaId5.setHgap((short)2);
    localdRq12.bb(localaId5);
    localaId5.brn();
    localaId5.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("11Light");
    localdRq12.bb(localcaF1);
    localcaF1.brn();
    NK localNK8 = NK.checkOut();
    localNK8.setElementMap(localcpa);
    localNK8.setName("itemPopupDetail");
    localNK8.setAttribute("text");
    localNK8.setField("ap");
    localcaF1.bb(localNK8);
    localNK8.brn();
    localNK8.rV();
    localcaF1.rV();
    czv localczv2 = new czv();
    localczv2.aJ();
    localczv2.setElementMap(localcpa);
    localczv2.setStyle("iconAP");
    localczv2.setExpandable(false);
    localdRq12.bb(localczv2);
    localczv2.brn();
    localczv2.rV();
    localdRq12.rV();
    localdRq11.rV();
    dRq localdRq13 = dRq.checkOut();
    localdRq13.setElementMap(localcpa);
    localdRq13.setExpandable(false);
    localdRq9.bb(localdRq13);
    localdRq13.brn();
    dpm localdpm7 = new dpm();
    localdpm7.aJ();
    localdpm7.setElementMap(localcpa);
    localdpm7.setAlign(aFG.ecl);
    localdRq13.bb(localdpm7);
    localdpm7.brn();
    localdpm7.rV();
    NK localNK9 = NK.checkOut();
    localNK9.setElementMap(localcpa);
    localNK9.setName("itemPopupDetail");
    localNK9.setAttribute("visible");
    localNK9.setField("range");
    localdRq13.bb(localNK9);
    localNK9.brn();
    anQ localanQ3 = new anQ();
    localanQ3.aJ();
    localanQ3.setElementMap(localcpa);
    localNK9.bb(localanQ3);
    localanQ3.brn();
    anE localanE2 = new anE();
    localanE2.aJ();
    localanE2.setElementMap(localcpa);
    localanQ3.bb(localanE2);
    localanE2.brn();
    localanE2.rV();
    localanQ3.rV();
    localNK9.rV();
    dRq localdRq14 = dRq.checkOut();
    localdRq14.setElementMap(localcpa);
    localdRq14.setExpandable(false);
    localdRq13.bb(localdRq14);
    localdRq14.brn();
    dpm localdpm8 = new dpm();
    localdpm8.aJ();
    localdpm8.setElementMap(localcpa);
    localdpm8.setAlign(aFG.ecl);
    localdRq14.bb(localdpm8);
    localdpm8.brn();
    localdpm8.rV();
    aId localaId6 = aId.checkOut();
    localaId6.setHgap((short)2);
    localdRq14.bb(localaId6);
    localaId6.brn();
    localaId6.rV();
    caF localcaF2 = new caF();
    localcaF2.aJ();
    localcaF2.setElementMap(localcpa);
    localcaF2.setStyle("11Light");
    localdRq14.bb(localcaF2);
    localcaF2.brn();
    NK localNK10 = NK.checkOut();
    localNK10.setElementMap(localcpa);
    localNK10.setName("itemPopupDetail");
    localNK10.setAttribute("text");
    localNK10.setField("range");
    localcaF2.bb(localNK10);
    localNK10.brn();
    localNK10.rV();
    localcaF2.rV();
    czv localczv3 = new czv();
    localczv3.aJ();
    localczv3.setElementMap(localcpa);
    localczv3.setStyle("rangeIcon");
    localczv3.setExpandable(false);
    localdRq14.bb(localczv3);
    localczv3.brn();
    localczv3.rV();
    localdRq14.rV();
    localdRq13.rV();
    localdRq9.rV();
    localdRq5.rV();
    dRq localdRq15 = dRq.checkOut();
    localdRq15.setElementMap(localcpa);
    localdRq15.setExpandable(false);
    localdRq3.bb(localdRq15);
    localdRq15.brn();
    NK localNK11 = NK.checkOut();
    localNK11.setElementMap(localcpa);
    localNK11.setAttribute("visible");
    localNK11.setName("itemPopupDetail");
    localNK11.setField("useRequirement");
    localdRq15.bb(localNK11);
    localNK11.brn();
    anQ localanQ4 = new anQ();
    localanQ4.aJ();
    localanQ4.setElementMap(localcpa);
    localNK11.bb(localanQ4);
    localanQ4.brn();
    jA localjA2 = new jA();
    localjA2.aJ();
    localjA2.setElementMap(localcpa);
    localjA2.setValue("");
    localanQ4.bb(localjA2);
    localjA2.brn();
    localjA2.rV();
    localanQ4.rV();
    localNK11.rV();
    aId localaId7 = aId.checkOut();
    localaId7.setHorizontal(false);
    localdRq15.bb(localaId7);
    localaId7.brn();
    localaId7.rV();
    dRq localdRq16 = dRq.checkOut();
    localdRq16.setElementMap(localcpa);
    localdRq16.setExpandable(false);
    localdRq16.setStyle("lineSeparator2");
    localdRq16.setPrefSize(new Or(50, 1));
    localdRq15.bb(localdRq16);
    localdRq16.brn();
    dRq localdRq17 = localdRq16;
    Jg localJg4 = localdRq17.getAppearance();
    localJg4.setElementMap(localcpa);
    localdRq16.bb(localJg4);
    localJg4.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(5, 20, 5, 20));
    localJg4.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg4.rV();
    localdRq16.rV();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setExpandable(false);
    String str2 = "%use.requirements%";
    str2 = str2.replace("%use.requirements%", cBQ.cxL().mL("use.requirements"));
    localcaF3.setText(str2);
    localcaF3.setStyle("11BoldLight");
    localcaF3.setNonBlocking(true);
    localdRq15.bb(localcaF3);
    localcaF3.brn();
    caF localcaF4 = localcaF3;
    Jg localJg5 = localcaF4.getAppearance();
    localJg5.setElementMap(localcpa);
    localcaF3.bb(localJg5);
    localJg5.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(0, 5, 5, 0));
    localJg5.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg5.rV();
    localcaF3.rV();
    cWk localcWk4 = new cWk();
    localcWk4.aJ();
    localcWk4.setElementMap(localcpa);
    localcWk4.setExpandable(false);
    localcWk4.setStyle("white11");
    localcWk4.setMinWidth(1);
    localcWk4.setMaxWidth(250);
    localcWk4.setNonBlocking(true);
    localdRq15.bb(localcWk4);
    localcWk4.brn();
    cWk localcWk5 = localcWk4;
    Jg localJg6 = localcWk5.getAppearance();
    localJg6.setElementMap(localcpa);
    localcWk4.bb(localJg6);
    localJg6.brn();
    bmv localbmv5 = bmv.checkOut();
    localbmv5.setElementMap(localcpa);
    localbmv5.setInsets(new Insets(0, 20, 0, 0));
    localJg6.bb(localbmv5);
    localbmv5.brn();
    localbmv5.rV();
    localJg6.rV();
    j(localcWk4);
    localcWk4.rV();
    localdRq15.rV();
    k(localdRq3);
    l(localdRq3);
    localdRq3.rV();
    localdRq2.rV();
    localdRq1.rV();
    localanG.rV();
    return localanG;
  }

  public bdj j(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setName("itemPopupDetail");
    localNK.setAttribute("text");
    localNK.setField("useRequirement");
    parambdj.bb(localNK);
    localNK.brn();
    localNK.rV();
    return localNK;
  }

  public bdj k(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("visible");
    localNK1.setName("itemPopupDetail");
    localNK1.setField("effect");
    localdRq1.bb(localNK1);
    localNK1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localNK1.bb(localanQ1);
    localanQ1.brn();
    anE localanE1 = new anE();
    localanE1.aJ();
    localanE1.setElementMap(localcpa);
    localanQ1.bb(localanE1);
    localanE1.brn();
    localanE1.rV();
    localanQ1.rV();
    localNK1.rV();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(false);
    localdRq1.bb(localaId);
    localaId.brn();
    localaId.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setExpandable(false);
    localdRq2.setStyle("lineSeparator2");
    localdRq2.setPrefSize(new Or(50, 1));
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(5, 20, 5, 20));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    localdRq2.rV();
    at localat = new at();
    localat.aJ();
    localat.setElementMap(localcpa);
    localat.setHorizontal(false);
    localdRq1.bb(localat);
    localat.brn();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.ecj);
    localat.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    eR localeR = new eR();
    localeR.aJ();
    localeR.setElementMap(localcpa);
    localat.bb(localeR);
    localeR.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localeR.bb(localanQ2);
    localanQ2.brn();
    bxx localbxx = new bxx();
    localbxx.aJ();
    localbxx.setElementMap(localcpa);
    localanQ2.bb(localbxx);
    localbxx.brn();
    anE localanE2 = new anE();
    localanE2.aJ();
    localanE2.setElementMap(localcpa);
    localbxx.bb(localanE2);
    localanE2.brn();
    localanE2.rV();
    localbxx.rV();
    localanQ2.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localeR.bb(localdRq4);
    localdRq4.brn();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("white11");
    localcWk1.setMultiline(false);
    localcWk1.setMinWidth(250);
    localcWk1.setMaxWidth(250);
    localcWk1.setExpandable(false);
    localdRq4.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg2 = localcWk2.getAppearance();
    localJg2.setElementMap(localcpa);
    localcWk1.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 5, 0, 0));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    aaE localaaE = new aaE();
    localaaE.aJ();
    localaaE.setElementMap(localcpa);
    localaaE.setAttribute("text");
    localcWk1.bb(localaaE);
    localaaE.brn();
    localaaE.rV();
    localcWk1.rV();
    localdRq4.rV();
    localeR.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("itemPopupDetail");
    localNK2.setAttribute("content");
    localNK2.setField("shortEffectDetails");
    localat.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localat.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj l(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("visible");
    localNK1.setName("itemPopupDetail");
    localNK1.setField("storingCapacity");
    localdRq1.bb(localNK1);
    localNK1.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localNK1.bb(localanQ);
    localanQ.brn();
    aEJ localaEJ = new aEJ();
    localaEJ.aJ();
    localaEJ.setElementMap(localcpa);
    localaEJ.setValue("0");
    localanQ.bb(localaEJ);
    localaEJ.brn();
    localaEJ.rV();
    localanQ.rV();
    localNK1.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localdRq1.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setExpandable(false);
    localdRq2.setStyle("lineSeparator2");
    localdRq2.setPrefSize(new Or(50, 1));
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(5, 20, 5, 20));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    localdRq2.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq1.bb(localdRq4);
    localdRq4.brn();
    aId localaId2 = aId.checkOut();
    localaId2.setAlign(aFG.ecj);
    localdRq4.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("whiteBold");
    localcaF1.setNonBlocking(true);
    String str1 = "%capacity%";
    str1 = str1.replace("%capacity%", cBQ.cxL().mL("capacity"));
    localcaF1.setText(str1);
    localcaF1.setExpandable(false);
    localdRq4.bb(localcaF1);
    localcaF1.brn();
    cba localcba1 = cba.checkOut();
    localcba1.setElementMap(localcpa);
    localcba1.setData(cFu.izT);
    localcaF1.bb(localcba1);
    localcba1.brn();
    localcba1.rV();
    caF localcaF2 = localcaF1;
    Jg localJg2 = localcaF2.getAppearance();
    localJg2.setElementMap(localcpa);
    localcaF1.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 5, 0, 0));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    localcaF1.rV();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setStyle("white");
    localcaF3.setNonBlocking(true);
    String str2 = "%capacity%";
    str2 = str2.replace("%capacity%", cBQ.cxL().mL("capacity"));
    localcaF3.setText(str2);
    localcaF3.setExpandable(false);
    localdRq4.bb(localcaF3);
    localcaF3.brn();
    cba localcba2 = cba.checkOut();
    localcba2.setElementMap(localcpa);
    localcba2.setData(cFu.izT);
    localcaF3.bb(localcba2);
    localcba2.brn();
    localcba2.rV();
    caF localcaF4 = localcaF3;
    Jg localJg3 = localcaF4.getAppearance();
    localJg3.setElementMap(localcpa);
    localcaF3.bb(localJg3);
    localJg3.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 5, 0, 0));
    localJg3.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg3.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setAttribute("text");
    localNK2.setName("itemPopupDetail");
    localNK2.setField("storingCapacity");
    localcaF3.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localcaF3.rV();
    localdRq4.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj m(bdj parambdj)
  {
    cpa localcpa1 = (cpa)this.X.peek();
    String str1 = "itemSimplePopup";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa1);
    if ((localcpa1 != null) && (str1 != null))
      localcpa1.a(str1, localanG);
    localanG.setAlign(aFG.ech);
    localanG.setHotSpotPosition(aFG.ecn);
    parambdj.bb(localanG);
    localanG.brn();
    cpa localcpa2 = localcpa1;
    localcpa1 = this.Y.nd((localcpa1 != null ? localcpa1.getId() : "") + ".itemDetailPopupInc");
    localcpa1.d(localcpa2);
    this.X.push(localcpa1);
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa1);
    localanG.bb(localdRq1);
    localdRq1.brn();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa1);
    localdRq2.setVisible(false);
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    aId localaId1 = aId.checkOut();
    localdRq2.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa1);
    localNK1.setName("itemPopupDetail");
    localNK1.setAttribute("visible");
    localdRq2.bb(localNK1);
    localNK1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa1);
    localNK1.bb(localanQ1);
    localanQ1.brn();
    anE localanE1 = new anE();
    localanE1.aJ();
    localanE1.setElementMap(localcpa1);
    localanQ1.bb(localanE1);
    localanE1.brn();
    localanE1.rV();
    localanQ1.rV();
    localNK1.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa1);
    localdRq3.setExpandable(false);
    localdRq3.setPrefSize(new Or(250, 0));
    localdRq3.setStyle("popup");
    localdRq2.bb(localdRq3);
    localdRq3.brn();
    dRq localdRq4 = localdRq3;
    Jg localJg1 = localdRq4.getAppearance();
    localJg1.setElementMap(localcpa1);
    localdRq3.bb(localJg1);
    localJg1.brn();
    localJg1.rV();
    aId localaId2 = aId.checkOut();
    localaId2.setAlign(aFG.ech);
    localaId2.setHorizontal(false);
    localdRq3.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa1);
    localcWk1.setStyle("DefaultBold14White");
    localcWk1.setExpandable(false);
    localcWk1.setMinWidth(210);
    localdRq3.bb(localcWk1);
    localcWk1.brn();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa1);
    localdpm1.setAlign(aFG.ecj);
    localcWk1.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa1);
    localNK2.setName("itemPopupDetail");
    localNK2.setAttribute("text");
    localNK2.setField("nameWithRarity");
    localcWk1.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localcWk1.rV();
    dRq localdRq5 = dRq.checkOut();
    localdRq5.setElementMap(localcpa1);
    localdRq5.setExpandable(false);
    localdRq3.bb(localdRq5);
    localdRq5.brn();
    aId localaId3 = aId.checkOut();
    localdRq5.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa1);
    localdRq6.setExpandable(false);
    localdRq5.bb(localdRq6);
    localdRq6.brn();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa1);
    localdpm2.setAlign(aFG.ech);
    localdRq6.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    czO localczO = new czO();
    localczO.aJ();
    localczO.setAdaptToContentSize(true);
    localdRq6.bb(localczO);
    localczO.brn();
    localczO.rV();
    dRq localdRq7 = localdRq6;
    Jg localJg2 = localdRq7.getAppearance();
    localJg2.setElementMap(localcpa1);
    localdRq6.bb(localJg2);
    localJg2.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa1);
    localbmv1.setInsets(new Insets(0, 0, 0, 2));
    localJg2.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg2.rV();
    dRq localdRq8 = dRq.checkOut();
    localdRq8.setElementMap(localcpa1);
    localdRq8.setStyle("caracs");
    localdRq6.bb(localdRq8);
    localdRq8.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa1);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localdRq8.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    localdRq8.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa1);
    localczv1.setDisplaySize(new Or(64, 64));
    localdRq6.bb(localczv1);
    localczv1.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa1);
    localcwP2.setAlign(ajb.dhZ);
    localcwP2.setSize(new Or(-2, -2));
    localczv1.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa1);
    localczv1.bb(localaAR);
    localaAR.brn();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa1);
    localNK3.setName("itemPopupDetail");
    localNK3.setAttribute("texture");
    localNK3.setField("iconUrl");
    localaAR.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    localaAR.rV();
    localczv1.rV();
    localdRq6.rV();
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa1);
    localdRq5.bb(localdRq9);
    localdRq9.brn();
    dRq localdRq10 = localdRq9;
    Jg localJg3 = localdRq10.getAppearance();
    localJg3.setElementMap(localcpa1);
    localdRq9.bb(localJg3);
    localJg3.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa1);
    localbmv2.setInsets(new Insets(0, 0, 0, 0));
    localJg3.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg3.rV();
    aId localaId4 = aId.checkOut();
    localaId4.setHorizontal(false);
    localaId4.setAlign(aFG.ech);
    localdRq9.bb(localaId4);
    localaId4.brn();
    localaId4.rV();
    cWk localcWk2 = new cWk();
    localcWk2.aJ();
    localcWk2.setElementMap(localcpa1);
    localcWk2.setStyle("11light");
    localcWk2.setExpandable(false);
    localdRq9.bb(localcWk2);
    localcWk2.brn();
    dpm localdpm3 = new dpm();
    localdpm3.aJ();
    localdpm3.setElementMap(localcpa1);
    localdpm3.setAlign(aFG.ecl);
    localcWk2.bb(localdpm3);
    localdpm3.brn();
    localdpm3.rV();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa1);
    localNK4.setName("itemPopupDetail");
    localNK4.setAttribute("text");
    localNK4.setField("levelDescription");
    localcWk2.bb(localNK4);
    localNK4.brn();
    localNK4.rV();
    localcWk2.rV();
    cWk localcWk3 = new cWk();
    localcWk3.aJ();
    localcWk3.setElementMap(localcpa1);
    localcWk3.setStyle("white11");
    localcWk3.setMultiline(false);
    localcWk3.setExpandable(false);
    localdRq9.bb(localcWk3);
    localcWk3.brn();
    dpm localdpm4 = new dpm();
    localdpm4.aJ();
    localdpm4.setElementMap(localcpa1);
    localdpm4.setAlign(aFG.ecj);
    localcWk3.bb(localdpm4);
    localdpm4.brn();
    localdpm4.rV();
    NK localNK5 = NK.checkOut();
    localNK5.setElementMap(localcpa1);
    localNK5.setAttribute("text");
    localNK5.setName("itemPopupDetail");
    localNK5.setField("type");
    localcWk3.bb(localNK5);
    localNK5.brn();
    localNK5.rV();
    localcWk3.rV();
    dRq localdRq11 = dRq.checkOut();
    localdRq11.setElementMap(localcpa1);
    localdRq11.setExpandable(false);
    localdRq9.bb(localdRq11);
    localdRq11.brn();
    dpm localdpm5 = new dpm();
    localdpm5.aJ();
    localdpm5.setElementMap(localcpa1);
    localdpm5.setAlign(aFG.ecl);
    localdRq11.bb(localdpm5);
    localdpm5.brn();
    localdpm5.rV();
    NK localNK6 = NK.checkOut();
    localNK6.setElementMap(localcpa1);
    localNK6.setName("itemPopupDetail");
    localNK6.setAttribute("visible");
    localNK6.setField("ap");
    localdRq11.bb(localNK6);
    localNK6.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa1);
    localNK6.bb(localanQ2);
    localanQ2.brn();
    bJJ localbJJ = new bJJ();
    localbJJ.aJ();
    localbJJ.setElementMap(localcpa1);
    localanQ2.bb(localbJJ);
    localbJJ.brn();
    jA localjA1 = new jA();
    localjA1.aJ();
    localjA1.setElementMap(localcpa1);
    localjA1.setValue("0");
    localbJJ.bb(localjA1);
    localjA1.brn();
    localjA1.rV();
    cOk localcOk = new cOk();
    localcOk.aJ();
    localcOk.setElementMap(localcpa1);
    localbJJ.bb(localcOk);
    localcOk.brn();
    NK localNK7 = NK.checkOut();
    localNK7.setElementMap(localcpa1);
    localNK7.setName("itemPopupDetail");
    localNK7.setAttribute("comparedValue");
    localNK7.setField("usableInFight");
    localcOk.bb(localNK7);
    localNK7.brn();
    localNK7.rV();
    localcOk.rV();
    localbJJ.rV();
    localanQ2.rV();
    localNK6.rV();
    dRq localdRq12 = dRq.checkOut();
    localdRq12.setElementMap(localcpa1);
    localdRq12.setExpandable(false);
    localdRq11.bb(localdRq12);
    localdRq12.brn();
    dpm localdpm6 = new dpm();
    localdpm6.aJ();
    localdpm6.setElementMap(localcpa1);
    localdpm6.setAlign(aFG.ecl);
    localdRq12.bb(localdpm6);
    localdpm6.brn();
    localdpm6.rV();
    aId localaId5 = aId.checkOut();
    localaId5.setHgap((short)2);
    localdRq12.bb(localaId5);
    localaId5.brn();
    localaId5.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa1);
    localcaF1.setStyle("11Light");
    localdRq12.bb(localcaF1);
    localcaF1.brn();
    NK localNK8 = NK.checkOut();
    localNK8.setElementMap(localcpa1);
    localNK8.setName("itemPopupDetail");
    localNK8.setAttribute("text");
    localNK8.setField("ap");
    localcaF1.bb(localNK8);
    localNK8.brn();
    localNK8.rV();
    localcaF1.rV();
    czv localczv2 = new czv();
    localczv2.aJ();
    localczv2.setElementMap(localcpa1);
    localczv2.setStyle("iconAP");
    localczv2.setExpandable(false);
    localdRq12.bb(localczv2);
    localczv2.brn();
    localczv2.rV();
    localdRq12.rV();
    localdRq11.rV();
    dRq localdRq13 = dRq.checkOut();
    localdRq13.setElementMap(localcpa1);
    localdRq13.setExpandable(false);
    localdRq9.bb(localdRq13);
    localdRq13.brn();
    dpm localdpm7 = new dpm();
    localdpm7.aJ();
    localdpm7.setElementMap(localcpa1);
    localdpm7.setAlign(aFG.ecl);
    localdRq13.bb(localdpm7);
    localdpm7.brn();
    localdpm7.rV();
    NK localNK9 = NK.checkOut();
    localNK9.setElementMap(localcpa1);
    localNK9.setName("itemPopupDetail");
    localNK9.setAttribute("visible");
    localNK9.setField("range");
    localdRq13.bb(localNK9);
    localNK9.brn();
    anQ localanQ3 = new anQ();
    localanQ3.aJ();
    localanQ3.setElementMap(localcpa1);
    localNK9.bb(localanQ3);
    localanQ3.brn();
    anE localanE2 = new anE();
    localanE2.aJ();
    localanE2.setElementMap(localcpa1);
    localanQ3.bb(localanE2);
    localanE2.brn();
    localanE2.rV();
    localanQ3.rV();
    localNK9.rV();
    dRq localdRq14 = dRq.checkOut();
    localdRq14.setElementMap(localcpa1);
    localdRq14.setExpandable(false);
    localdRq13.bb(localdRq14);
    localdRq14.brn();
    dpm localdpm8 = new dpm();
    localdpm8.aJ();
    localdpm8.setElementMap(localcpa1);
    localdpm8.setAlign(aFG.ecl);
    localdRq14.bb(localdpm8);
    localdpm8.brn();
    localdpm8.rV();
    aId localaId6 = aId.checkOut();
    localaId6.setHgap((short)2);
    localdRq14.bb(localaId6);
    localaId6.brn();
    localaId6.rV();
    caF localcaF2 = new caF();
    localcaF2.aJ();
    localcaF2.setElementMap(localcpa1);
    localcaF2.setStyle("11Light");
    localdRq14.bb(localcaF2);
    localcaF2.brn();
    NK localNK10 = NK.checkOut();
    localNK10.setElementMap(localcpa1);
    localNK10.setName("itemPopupDetail");
    localNK10.setAttribute("text");
    localNK10.setField("range");
    localcaF2.bb(localNK10);
    localNK10.brn();
    localNK10.rV();
    localcaF2.rV();
    czv localczv3 = new czv();
    localczv3.aJ();
    localczv3.setElementMap(localcpa1);
    localczv3.setStyle("rangeIcon");
    localczv3.setExpandable(false);
    localdRq14.bb(localczv3);
    localczv3.brn();
    localczv3.rV();
    localdRq14.rV();
    localdRq13.rV();
    localdRq9.rV();
    localdRq5.rV();
    dRq localdRq15 = dRq.checkOut();
    localdRq15.setElementMap(localcpa1);
    localdRq15.setExpandable(false);
    localdRq3.bb(localdRq15);
    localdRq15.brn();
    NK localNK11 = NK.checkOut();
    localNK11.setElementMap(localcpa1);
    localNK11.setAttribute("visible");
    localNK11.setName("itemPopupDetail");
    localNK11.setField("useRequirement");
    localdRq15.bb(localNK11);
    localNK11.brn();
    anQ localanQ4 = new anQ();
    localanQ4.aJ();
    localanQ4.setElementMap(localcpa1);
    localNK11.bb(localanQ4);
    localanQ4.brn();
    jA localjA2 = new jA();
    localjA2.aJ();
    localjA2.setElementMap(localcpa1);
    localjA2.setValue("");
    localanQ4.bb(localjA2);
    localjA2.brn();
    localjA2.rV();
    localanQ4.rV();
    localNK11.rV();
    aId localaId7 = aId.checkOut();
    localaId7.setHorizontal(false);
    localdRq15.bb(localaId7);
    localaId7.brn();
    localaId7.rV();
    dRq localdRq16 = dRq.checkOut();
    localdRq16.setElementMap(localcpa1);
    localdRq16.setExpandable(false);
    localdRq16.setStyle("lineSeparator2");
    localdRq16.setPrefSize(new Or(50, 1));
    localdRq15.bb(localdRq16);
    localdRq16.brn();
    dRq localdRq17 = localdRq16;
    Jg localJg4 = localdRq17.getAppearance();
    localJg4.setElementMap(localcpa1);
    localdRq16.bb(localJg4);
    localJg4.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa1);
    localbmv3.setInsets(new Insets(5, 20, 5, 20));
    localJg4.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg4.rV();
    localdRq16.rV();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa1);
    localcaF3.setExpandable(false);
    String str2 = "%use.requirements%";
    str2 = str2.replace("%use.requirements%", cBQ.cxL().mL("use.requirements"));
    localcaF3.setText(str2);
    localcaF3.setStyle("11BoldLight");
    localcaF3.setNonBlocking(true);
    localdRq15.bb(localcaF3);
    localcaF3.brn();
    caF localcaF4 = localcaF3;
    Jg localJg5 = localcaF4.getAppearance();
    localJg5.setElementMap(localcpa1);
    localcaF3.bb(localJg5);
    localJg5.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa1);
    localbmv4.setInsets(new Insets(0, 5, 5, 0));
    localJg5.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg5.rV();
    localcaF3.rV();
    cWk localcWk4 = new cWk();
    localcWk4.aJ();
    localcWk4.setElementMap(localcpa1);
    localcWk4.setExpandable(false);
    localcWk4.setStyle("white11");
    localcWk4.setMinWidth(1);
    localcWk4.setMaxWidth(250);
    localcWk4.setNonBlocking(true);
    localdRq15.bb(localcWk4);
    localcWk4.brn();
    cWk localcWk5 = localcWk4;
    Jg localJg6 = localcWk5.getAppearance();
    localJg6.setElementMap(localcpa1);
    localcWk4.bb(localJg6);
    localJg6.brn();
    n(localJg6);
    localJg6.rV();
    o(localcWk4);
    localcWk4.rV();
    localdRq15.rV();
    p(localdRq3);
    q(localdRq3);
    localdRq3.rV();
    localdRq2.rV();
    localdRq1.rV();
    this.X.pop();
    localcpa1 = (cpa)this.X.peek();
    localanG.rV();
    return localanG;
  }

  public bdj n(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(0, 20, 0, 0));
    parambdj.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    return localbmv;
  }

  public bdj o(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setName("itemPopupDetail");
    localNK.setAttribute("text");
    localNK.setField("useRequirement");
    parambdj.bb(localNK);
    localNK.brn();
    localNK.rV();
    return localNK;
  }

  public bdj p(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("visible");
    localNK1.setName("itemPopupDetail");
    localNK1.setField("effect");
    localdRq1.bb(localNK1);
    localNK1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localNK1.bb(localanQ1);
    localanQ1.brn();
    anE localanE1 = new anE();
    localanE1.aJ();
    localanE1.setElementMap(localcpa);
    localanQ1.bb(localanE1);
    localanE1.brn();
    localanE1.rV();
    localanQ1.rV();
    localNK1.rV();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(false);
    localdRq1.bb(localaId);
    localaId.brn();
    localaId.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setExpandable(false);
    localdRq2.setStyle("lineSeparator2");
    localdRq2.setPrefSize(new Or(50, 1));
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(5, 20, 5, 20));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    localdRq2.rV();
    at localat = new at();
    localat.aJ();
    localat.setElementMap(localcpa);
    localat.setHorizontal(false);
    localdRq1.bb(localat);
    localat.brn();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.ecj);
    localat.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    eR localeR = new eR();
    localeR.aJ();
    localeR.setElementMap(localcpa);
    localat.bb(localeR);
    localeR.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localeR.bb(localanQ2);
    localanQ2.brn();
    bxx localbxx = new bxx();
    localbxx.aJ();
    localbxx.setElementMap(localcpa);
    localanQ2.bb(localbxx);
    localbxx.brn();
    anE localanE2 = new anE();
    localanE2.aJ();
    localanE2.setElementMap(localcpa);
    localbxx.bb(localanE2);
    localanE2.brn();
    localanE2.rV();
    localbxx.rV();
    localanQ2.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localeR.bb(localdRq4);
    localdRq4.brn();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("white11");
    localcWk1.setMultiline(false);
    localcWk1.setMinWidth(250);
    localcWk1.setMaxWidth(250);
    localcWk1.setExpandable(false);
    localdRq4.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg2 = localcWk2.getAppearance();
    localJg2.setElementMap(localcpa);
    localcWk1.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 5, 0, 0));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    aaE localaaE = new aaE();
    localaaE.aJ();
    localaaE.setElementMap(localcpa);
    localaaE.setAttribute("text");
    localcWk1.bb(localaaE);
    localaaE.brn();
    localaaE.rV();
    localcWk1.rV();
    localdRq4.rV();
    localeR.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("itemPopupDetail");
    localNK2.setAttribute("content");
    localNK2.setField("shortEffectDetails");
    localat.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localat.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj q(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("visible");
    localNK1.setName("itemPopupDetail");
    localNK1.setField("storingCapacity");
    localdRq1.bb(localNK1);
    localNK1.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localNK1.bb(localanQ);
    localanQ.brn();
    aEJ localaEJ = new aEJ();
    localaEJ.aJ();
    localaEJ.setElementMap(localcpa);
    localaEJ.setValue("0");
    localanQ.bb(localaEJ);
    localaEJ.brn();
    localaEJ.rV();
    localanQ.rV();
    localNK1.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localdRq1.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setExpandable(false);
    localdRq2.setStyle("lineSeparator2");
    localdRq2.setPrefSize(new Or(50, 1));
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(5, 20, 5, 20));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    localdRq2.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq1.bb(localdRq4);
    localdRq4.brn();
    aId localaId2 = aId.checkOut();
    localaId2.setAlign(aFG.ecj);
    localdRq4.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("whiteBold");
    localcaF1.setNonBlocking(true);
    String str1 = "%capacity%";
    str1 = str1.replace("%capacity%", cBQ.cxL().mL("capacity"));
    localcaF1.setText(str1);
    localcaF1.setExpandable(false);
    localdRq4.bb(localcaF1);
    localcaF1.brn();
    cba localcba1 = cba.checkOut();
    localcba1.setElementMap(localcpa);
    localcba1.setData(cFu.izT);
    localcaF1.bb(localcba1);
    localcba1.brn();
    localcba1.rV();
    caF localcaF2 = localcaF1;
    Jg localJg2 = localcaF2.getAppearance();
    localJg2.setElementMap(localcpa);
    localcaF1.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 5, 0, 0));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    localcaF1.rV();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setStyle("white");
    localcaF3.setNonBlocking(true);
    String str2 = "%capacity%";
    str2 = str2.replace("%capacity%", cBQ.cxL().mL("capacity"));
    localcaF3.setText(str2);
    localcaF3.setExpandable(false);
    localdRq4.bb(localcaF3);
    localcaF3.brn();
    cba localcba2 = cba.checkOut();
    localcba2.setElementMap(localcpa);
    localcba2.setData(cFu.izT);
    localcaF3.bb(localcba2);
    localcba2.brn();
    localcba2.rV();
    caF localcaF4 = localcaF3;
    Jg localJg3 = localcaF4.getAppearance();
    localJg3.setElementMap(localcpa);
    localcaF3.bb(localJg3);
    localJg3.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 5, 0, 0));
    localJg3.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg3.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setAttribute("text");
    localNK2.setName("itemPopupDetail");
    localNK2.setField("storingCapacity");
    localcaF3.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localcaF3.rV();
    localdRq4.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj r(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    String str = "emotePopup";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa);
    if ((localcpa != null) && (str != null))
      localcpa.a(str, localanG);
    localanG.setAlign(aFG.ech);
    localanG.setHotSpotPosition(aFG.ecn);
    parambdj.bb(localanG);
    localanG.brn();
    dRq localdRq = dRq.checkOut();
    localdRq.setElementMap(localcpa);
    localdRq.setPrefSize(new Or(10, 0));
    localdRq.setStyle("popup");
    localanG.bb(localdRq);
    localdRq.brn();
    aId localaId = aId.checkOut();
    localaId.setAlign(aFG.ech);
    localaId.setHorizontal(false);
    localdRq.bb(localaId);
    localaId.brn();
    localaId.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("white");
    localdRq.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg = localcWk2.getAppearance();
    localJg.setElementMap(localcpa);
    ((cwJ)localJg).setAlignment(aFG.ecj);
    localcWk1.bb(localJg);
    localJg.brn();
    localJg.rV();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setName("currentDescribedEmote");
    localNK.setAttribute("text");
    localNK.setField("description");
    localcWk1.bb(localNK);
    localNK.brn();
    localNK.rV();
    localcWk1.rV();
    localdRq.rV();
    localanG.rV();
    return localanG;
  }

  public bdj s(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setNonBlocking(true);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    dRq localdRq2 = localdRq1;
    Jg localJg1 = localdRq2.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq1.bb(localJg1);
    localJg1.brn();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(1, 1, 1, 1));
    localJg1.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    localJg1.rV();
    czO localczO1 = new czO();
    localczO1.aJ();
    localczO1.setAdaptToContentSize(true);
    localdRq1.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq3.setNonBlocking(true);
    localdRq1.bb(localdRq3);
    localdRq3.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setAlign(ajb.dhY);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localdRq3.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    String str1 = "shortcutBar";
    avo localavo1 = new avo();
    localavo1.aJ();
    localavo1.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localavo1);
    localdRq3.bb(localavo1);
    localavo1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setName("shortcutBar");
    localNK1.setAttribute("value");
    localNK1.setLocal(true);
    localavo1.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    localavo1.rV();
    String str2 = "shortcutBarIndex";
    avo localavo2 = new avo();
    localavo2.aJ();
    localavo2.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localavo2);
    localdRq3.bb(localavo2);
    localavo2.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("shortcutBar");
    localNK2.setAttribute("value");
    localNK2.setLocal(true);
    localNK2.setField("index");
    localavo2.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localavo2.rV();
    ccG localccG = new ccG();
    localccG.aJ();
    localccG.setElementMap(localcpa);
    localccG.setExpandable(false);
    localccG.setPrefSize(new Or(0, 31));
    localccG.setScrollBar(false);
    localccG.setCellSize(new Or(39, 31));
    localccG.setHorizontal(true);
    localccG.setAutoIdealSize(true);
    localccG.setIdealSizeMinRows(1);
    localccG.setIdealSizeMaxRows(1);
    fp localfp = new fp();
    localfp.hg("wakfu.shortcutBar:dropOutItem(shortcutBarIndex)");
    localccG.setOnDropOut(localfp);
    localdRq3.bb(localccG);
    localccG.brn();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setName("shortcutBar");
    localNK3.setAttribute("content");
    localNK3.setLocal(true);
    localNK3.setField("shortcuts");
    localccG.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    eR localeR1 = new eR();
    localeR1.aJ();
    localeR1.setElementMap(localcpa);
    localccG.bb(localeR1);
    localeR1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localeR1.bb(localanQ1);
    localanQ1.brn();
    bxx localbxx1 = new bxx();
    localbxx1.aJ();
    localbxx1.setElementMap(localcpa);
    localanQ1.bb(localbxx1);
    localbxx1.brn();
    aIB localaIB = new aIB();
    localaIB.aJ();
    localaIB.setElementMap(localcpa);
    localbxx1.bb(localaIB);
    localaIB.brn();
    localaIB.rV();
    localbxx1.rV();
    localanQ1.rV();
    String str3 = "borderContainer";
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    if ((localcpa != null) && (str3 != null))
      localcpa.a(str3, localdRq4);
    localdRq4.setStyle("ShortcutBarBoxShadowBackground");
    localeR1.bb(localdRq4);
    localdRq4.brn();
    dRq localdRq5 = localdRq4;
    Jg localJg2 = localdRq5.getAppearance();
    localJg2.setElementMap(localcpa);
    localdRq4.bb(localJg2);
    localJg2.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 3, 0, 3));
    localJg2.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(0, 4, 0, 4));
    localJg2.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    localJg2.rV();
    bXx localbXx1 = new bXx();
    localbXx1.aJ();
    localbXx1.setElementMap(localcpa);
    bQa localbQa1 = new bQa();
    localbQa1.hg("wakfu.shortcutBar:dropItem(shortcutBarIndex)");
    localbXx1.setOnDrop(localbQa1);
    localdRq4.bb(localbXx1);
    localbXx1.brn();
    localbXx1.rV();
    localdRq4.rV();
    localeR1.rV();
    eR localeR2 = new eR();
    localeR2.aJ();
    localeR2.setElementMap(localcpa);
    aqC localaqC = new aqC();
    localaqC.hg("wakfu.shortcutBar:useItem");
    localeR2.setOnItemClick(localaqC);
    anx localanx = new anx();
    localanx.hg("wakfu.shortcutBar:openCloseShortcutDescription(window)");
    localeR2.setOnItemOver(localanx);
    cVk localcVk = new cVk();
    localcVk.hg("wakfu.shortcutBar:openCloseShortcutDescription(window)");
    localeR2.setOnItemOut(localcVk);
    bpP localbpP = new bpP();
    localbpP.hg("wakfu.shortcutBar:doubleClickItem");
    localeR2.setOnItemDoubleClick(localbpP);
    localccG.bb(localeR2);
    localeR2.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localeR2.bb(localanQ2);
    localanQ2.brn();
    bxx localbxx2 = new bxx();
    localbxx2.aJ();
    localbxx2.setElementMap(localcpa);
    localanQ2.bb(localbxx2);
    localbxx2.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localbxx2.bb(localanE);
    localanE.brn();
    localanE.rV();
    localbxx2.rV();
    localanQ2.rV();
    String str4 = "borderContainer";
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    if ((localcpa != null) && (str4 != null))
      localcpa.a(str4, localdRq6);
    localdRq6.setStyle("ShortcutBarBoxShadowBackground");
    localeR2.bb(localdRq6);
    localdRq6.brn();
    dRq localdRq7 = localdRq6;
    Jg localJg3 = localdRq7.getAppearance();
    localJg3.setElementMap(localcpa);
    localdRq6.bb(localJg3);
    localJg3.brn();
    cag localcag = new cag();
    localcag.aJ();
    localcag.setElementMap(localcpa);
    localcag.setAlignment(aFG.eck);
    localJg3.bb(localcag);
    localcag.brn();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("file");
    localaaE1.setField("particleFile");
    localcag.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    localcag.rV();
    localJg3.rV();
    dRq localdRq8 = localdRq6;
    Jg localJg4 = localdRq8.getAppearance();
    localJg4.setElementMap(localcpa);
    localdRq6.bb(localJg4);
    localJg4.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 3, 0, 3));
    localJg4.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg4.rV();
    bXx localbXx2 = new bXx();
    localbXx2.aJ();
    localbXx2.setElementMap(localcpa);
    dVA localdVA = new dVA();
    localdVA.hg("wakfu.shortcutBar:dragItem(shortcutBarIndex)");
    localbXx2.setOnDrag(localdVA);
    bQa localbQa2 = new bQa();
    localbQa2.hg("wakfu.shortcutBar:dropItem(shortcutBarIndex)");
    localbXx2.setOnDrop(localbQa2);
    localdRq6.bb(localbXx2);
    localbXx2.brn();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa);
    localNK4.setAttribute("dragEnabled");
    localNK4.setName("isInFight");
    localbXx2.bb(localNK4);
    localNK4.brn();
    anQ localanQ3 = new anQ();
    localanQ3.aJ();
    localanQ3.setElementMap(localcpa);
    localNK4.bb(localanQ3);
    localanQ3.brn();
    boQ localboQ = new boQ();
    localboQ.aJ();
    localboQ.setElementMap(localcpa);
    localanQ3.bb(localboQ);
    localboQ.brn();
    bqW localbqW1 = new bqW();
    localbqW1.aJ();
    localbqW1.setElementMap(localcpa);
    localboQ.bb(localbqW1);
    localbqW1.brn();
    localbqW1.rV();
    cOk localcOk = new cOk();
    localcOk.aJ();
    localcOk.setElementMap(localcpa);
    localboQ.bb(localcOk);
    localcOk.brn();
    NK localNK5 = NK.checkOut();
    localNK5.setElementMap(localcpa);
    localNK5.setAttribute("comparedValue");
    localNK5.setName("isInFightPlacement");
    localcOk.bb(localNK5);
    localNK5.brn();
    localNK5.rV();
    localcOk.rV();
    localboQ.rV();
    localanQ3.rV();
    localNK4.rV();
    bXx localbXx3 = localbXx2;
    Jg localJg5 = localbXx3.getAppearance();
    localJg5.setElementMap(localcpa);
    localbXx2.bb(localJg5);
    localJg5.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 0, 0, 0));
    localJg5.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg5.rV();
    czO localczO2 = new czO();
    localczO2.aJ();
    localbXx2.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setNonBlocking(true);
    localczv1.setScaled(true);
    localczv1.setDisplaySize(new Or(31, 31));
    localbXx2.bb(localczv1);
    localczv1.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localczv1.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    aAR localaAR1 = aAR.checkOut();
    localaAR1.setElementMap(localcpa);
    localczv1.bb(localaAR1);
    localaAR1.brn();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("texture");
    localaaE2.setField("backgroundTypeIcon");
    localaAR1.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    localaAR1.rV();
    localczv1.rV();
    czv localczv2 = new czv();
    localczv2.aJ();
    localczv2.setElementMap(localcpa);
    localczv2.setNonBlocking(true);
    localczv2.setScaled(true);
    localczv2.setDisplaySize(new Or(31, 31));
    localbXx2.bb(localczv2);
    localczv2.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setSize(new Or(100.0F, 100.0F));
    localczv2.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    aAR localaAR2 = aAR.checkOut();
    localaAR2.setElementMap(localcpa);
    localczv2.bb(localaAR2);
    localaAR2.brn();
    aaE localaaE3 = new aaE();
    localaaE3.aJ();
    localaaE3.setElementMap(localcpa);
    localaaE3.setAttribute("texture");
    localaaE3.setField("smallIconUrl");
    localaAR2.bb(localaaE3);
    localaaE3.brn();
    localaaE3.rV();
    localaAR2.rV();
    localczv2.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setNonBlocking(true);
    localcaF1.setStyle("White10Bordered");
    localbXx2.bb(localcaF1);
    localcaF1.brn();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setAlign(ajb.dih);
    localcaF1.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    caF localcaF2 = localcaF1;
    Jg localJg6 = localcaF2.getAppearance();
    localJg6.setElementMap(localcpa);
    localcaF1.bb(localJg6);
    localJg6.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(0, 5, 3, 0));
    localJg6.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg6.rV();
    aaE localaaE4 = new aaE();
    localaaE4.aJ();
    localaaE4.setElementMap(localcpa);
    localaaE4.setAttribute("text");
    localaaE4.setField("quantity");
    localcaF1.bb(localaaE4);
    localaaE4.brn();
    localaaE4.rV();
    localcaF1.rV();
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa);
    localdRq9.setStyle("fighterControlsNotAllowed");
    localbXx2.bb(localdRq9);
    localdRq9.brn();
    cwP localcwP5 = new cwP();
    localcwP5.aJ();
    localcwP5.setElementMap(localcpa);
    localcwP5.setSize(new Or(31, 31));
    localcwP5.setAlign(ajb.dhZ);
    localdRq9.bb(localcwP5);
    localcwP5.brn();
    localcwP5.rV();
    aaE localaaE5 = new aaE();
    localaaE5.aJ();
    localaaE5.setElementMap(localcpa);
    localaaE5.setAttribute("usedInLayout");
    localaaE5.setField("usable");
    localdRq9.bb(localaaE5);
    localaaE5.brn();
    anQ localanQ4 = new anQ();
    localanQ4.aJ();
    localanQ4.setElementMap(localcpa);
    localaaE5.bb(localanQ4);
    localanQ4.brn();
    bqW localbqW2 = new bqW();
    localbqW2.aJ();
    localbqW2.setElementMap(localcpa);
    localanQ4.bb(localbqW2);
    localbqW2.brn();
    localbqW2.rV();
    localanQ4.rV();
    localaaE5.rV();
    localdRq9.rV();
    cWk localcWk = new cWk();
    localcWk.aJ();
    localcWk.setElementMap(localcpa);
    localcWk.setNonBlocking(true);
    localcWk.setStyle("bigTitle");
    localbXx2.bb(localcWk);
    localcWk.brn();
    cwP localcwP6 = new cwP();
    localcwP6.aJ();
    localcwP6.setElementMap(localcpa);
    localcwP6.setAlign(ajb.dhZ);
    localcWk.bb(localcwP6);
    localcwP6.brn();
    localcwP6.rV();
    aaE localaaE6 = new aaE();
    localaaE6.aJ();
    localaaE6.setElementMap(localcpa);
    localaaE6.setAttribute("text");
    localaaE6.setField("cooldown");
    localcWk.bb(localaaE6);
    localaaE6.brn();
    localaaE6.rV();
    localcWk.rV();
    localbXx2.rV();
    localdRq6.rV();
    localeR2.rV();
    localccG.rV();
    dqa localdqa = new dqa();
    localdqa.aJ();
    localdqa.setElementMap(localcpa);
    localdRq3.bb(localdqa);
    localdqa.brn();
    dRq localdRq10 = dRq.checkOut();
    localdRq10.setElementMap(localcpa);
    localdRq10.setStyle("mainBackground");
    localdRq10.setExpandable(false);
    localdqa.bb(localdRq10);
    localdRq10.brn();
    dRq localdRq11 = localdRq10;
    Jg localJg7 = localdRq11.getAppearance();
    localJg7.setElementMap(localcpa);
    localdRq10.bb(localJg7);
    localJg7.brn();
    cuR localcuR3 = new cuR();
    localcuR3.aJ();
    localcuR3.setElementMap(localcpa);
    localcuR3.setInsets(new Insets(0, 12, 0, 12));
    localJg7.bb(localcuR3);
    localcuR3.brn();
    localcuR3.rV();
    localJg7.rV();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setStyle("blackBold");
    localcaF3.setNonBlocking(true);
    localdRq10.bb(localcaF3);
    localcaF3.brn();
    caF localcaF4 = localcaF3;
    Jg localJg8 = localcaF4.getAppearance();
    localJg8.setElementMap(localcpa);
    ((cwJ)localJg8).setAlign(aFG.eck);
    localcaF3.bb(localJg8);
    localJg8.brn();
    localJg8.rV();
    cba localcba = cba.checkOut();
    localcba.setElementMap(localcpa);
    localcba.setData(cFu.izR);
    localcaF3.bb(localcba);
    localcba.brn();
    localcba.rV();
    NK localNK6 = NK.checkOut();
    localNK6.setElementMap(localcpa);
    localNK6.setName("shortcutBar");
    localNK6.setAttribute("text");
    localNK6.setLocal(true);
    localNK6.setField("indexText");
    localcaF3.bb(localNK6);
    localNK6.brn();
    localNK6.rV();
    localcaF3.rV();
    localdRq10.rV();
    localdqa.rV();
    localdRq3.rV();
    t(localdRq1);
    localdRq1.rV();
    return localdRq1;
  }

  public bdj t(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    ccG localccG = new ccG();
    localccG.aJ();
    localccG.setElementMap(localcpa);
    localccG.setPrefSize(new Or(0, 31));
    localccG.setScrollBar(false);
    localccG.setCellSize(new Or(39, 31));
    localccG.setHorizontal(true);
    localccG.setAutoIdealSize(true);
    localccG.setIdealSizeMinRows(1);
    localccG.setIdealSizeMaxRows(1);
    localccG.setNonBlocking(true);
    parambdj.bb(localccG);
    localccG.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setAlign(ajb.dhY);
    localccG.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setName("shortcutBar");
    localNK.setAttribute("content");
    localNK.setLocal(true);
    localNK.setField("keyList");
    localccG.bb(localNK);
    localNK.brn();
    localNK.rV();
    eR localeR = new eR();
    localeR.aJ();
    localeR.setElementMap(localcpa);
    localccG.bb(localeR);
    localeR.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localeR.bb(localanQ);
    localanQ.brn();
    bxx localbxx = new bxx();
    localbxx.aJ();
    localbxx.setElementMap(localcpa);
    localanQ.bb(localbxx);
    localbxx.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localbxx.bb(localanE);
    localanE.brn();
    localanE.rV();
    localbxx.rV();
    localanQ.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localeR.bb(localdRq1);
    localdRq1.brn();
    dRq localdRq2 = localdRq1;
    Jg localJg1 = localdRq2.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq1.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 6, 0, 6));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    czO localczO = new czO();
    localczO.aJ();
    localdRq1.bb(localczO);
    localczO.brn();
    localczO.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setNonBlocking(true);
    localcWk1.setMultiline(true);
    localcWk1.setMinWidth(1);
    localcWk1.setMaxWidth(31);
    localcWk1.setStyle("smallBold");
    localdRq1.bb(localcWk1);
    localcWk1.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.dhR);
    localcwP2.setSize(new Or(100.0F, -2));
    localcWk1.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    cWk localcWk2 = localcWk1;
    Jg localJg2 = localcWk2.getAppearance();
    localJg2.setElementMap(localcpa);
    ((cwJ)localJg2).setAlign(aFG.ecj);
    localJg2.setModulationColor(new bNa(1.0F, 1.0F, 1.0F, 0.7F));
    localcWk1.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 0, 0, 0));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    aaE localaaE = new aaE();
    localaaE.aJ();
    localaaE.setElementMap(localcpa);
    localaaE.setAttribute("text");
    localcWk1.bb(localaaE);
    localaaE.brn();
    localaaE.rV();
    localcWk1.rV();
    localdRq1.rV();
    localeR.rV();
    localccG.rV();
    return localccG;
  }
}