import java.awt.Insets;
import java.util.Stack;

public class dq
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    String str1 = "window";
    bpn localbpn = new bpn();
    localbpn.aJ();
    localbpn.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localbpn);
    localbpn.setPack(true);
    localbpn.brn();
    czO localczO = new czO();
    localczO.aJ();
    localczO.setAdaptToContentSize(true);
    localbpn.bb(localczO);
    localczO.brn();
    localczO.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localbpn.bb(localdRq1);
    localdRq1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    localdRq1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setStyle("windowNew");
    localbpn.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(10, 5, 12, 5));
    localJg1.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    localJg1.rV();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localdRq2.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localaId1.setAlign(aFG.ech);
    localdRq2.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dqa localdqa1 = new dqa();
    localdqa1.aJ();
    localdqa1.setElementMap(localcpa);
    localdqa1.setExpandable(false);
    localdRq2.bb(localdqa1);
    localdqa1.brn();
    dqa localdqa2 = localdqa1;
    Jg localJg2 = localdqa2.getAppearance();
    localJg2.setElementMap(localcpa);
    localdqa1.bb(localJg2);
    localJg2.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 10, 0, 10));
    localJg2.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg2.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setStyle("titleBar");
    localdqa1.bb(localdRq4);
    localdRq4.brn();
    dRq localdRq5 = localdRq4;
    Jg localJg3 = localdRq5.getAppearance();
    localJg3.setElementMap(localcpa);
    localdRq4.bb(localJg3);
    localJg3.brn();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(2, 20, 3, 20));
    localJg3.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    localJg3.rV();
    aId localaId2 = aId.checkOut();
    localaId2.setHorizontal(false);
    localdRq4.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq6.setExpandable(false);
    localdRq4.bb(localdRq6);
    localdRq6.brn();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa);
    localdpm1.setAlign(aFG.eck);
    localdRq6.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("StyledBold16White");
    localcaF1.setNonBlocking(true);
    String str2 = "%webShop.title%";
    str2 = str2.replace("%webShop.title%", cBQ.cxL().mL("webShop.title"));
    localcaF1.setText(str2);
    localdRq6.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg4 = localcaF2.getAppearance();
    localJg4.setElementMap(localcpa);
    ((cwJ)localJg4).setAlignment(aFG.eck);
    localcaF1.bb(localJg4);
    localJg4.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 0, 0, 5));
    localJg4.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg4.rV();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("text");
    localNK1.setName("market");
    localNK1.setField("name");
    localcaF1.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    localcaF1.rV();
    localdRq6.rV();
    localdRq4.rV();
    localdqa1.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localdRq2.bb(localdRq7);
    localdRq7.brn();
    dRq localdRq8 = localdRq7;
    Jg localJg5 = localdRq8.getAppearance();
    localJg5.setElementMap(localcpa);
    localdRq7.bb(localJg5);
    localJg5.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 12, 0, 12));
    localJg5.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg5.rV();
    String str3 = "windowContentContainer";
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa);
    if ((localcpa != null) && (str3 != null))
      localcpa.a(str3, localdRq9);
    localdRq7.bb(localdRq9);
    localdRq9.brn();
    String str4 = "session";
    avo localavo = new avo();
    localavo.aJ();
    localavo.setElementMap(localcpa);
    if ((localcpa != null) && (str4 != null))
      localcpa.a(str4, localavo);
    localdRq9.bb(localavo);
    localavo.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("webShop");
    localNK2.setAttribute("value");
    localavo.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localavo.rV();
    aId localaId3 = aId.checkOut();
    localaId3.setHorizontal(false);
    localdRq9.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    dRq localdRq10 = dRq.checkOut();
    localdRq10.setElementMap(localcpa);
    localdRq10.setStyle("caracs");
    localdRq9.bb(localdRq10);
    localdRq10.brn();
    aId localaId4 = aId.checkOut();
    localaId4.setHorizontal(true);
    localdRq10.bb(localaId4);
    localaId4.brn();
    localaId4.rV();
    ddG localddG1 = new ddG();
    localddG1.aJ();
    localddG1.setElementMap(localcpa);
    localddG1.setExpandable(false);
    localddG1.setPrefSize(new Or(200, 15));
    localddG1.setStyle("webShop");
    dTZ localdTZ = new dTZ();
    localdTZ.hg("wakfu.webShop:selectCategory(session)");
    localddG1.setOnListSelectionChange(localdTZ);
    localdRq10.bb(localddG1);
    localddG1.brn();
    ddG localddG2 = localddG1;
    Jg localJg6 = localddG2.getAppearance();
    localJg6.setElementMap(localcpa);
    localddG1.bb(localJg6);
    localJg6.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(0, 0, 0, 3));
    localJg6.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg6.rV();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setAttribute("content");
    localNK3.setName("webShop");
    localNK3.setField("categories");
    localddG1.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa);
    localNK4.setAttribute("selectedValue");
    localNK4.setName("webShop");
    localNK4.setField("currentCategory");
    localddG1.bb(localNK4);
    localNK4.brn();
    localNK4.rV();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa);
    localdpm2.setAlign(aFG.eck);
    localddG1.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    axU localaxU = new axU();
    localaxU.aJ();
    localaxU.setElementMap(localcpa);
    localddG1.bb(localaxU);
    localaxU.brn();
    eR localeR1 = new eR();
    localeR1.aJ();
    localeR1.setElementMap(localcpa);
    localaxU.bb(localeR1);
    localeR1.brn();
    dRq localdRq11 = dRq.checkOut();
    localdRq11.setElementMap(localcpa);
    localdRq11.setNonBlocking(false);
    cCu localcCu1 = new cCu();
    localcCu1.hg("popup(serverInfoPopup)");
    localdRq11.setOnPopupDisplay(localcCu1);
    jL localjL1 = new jL();
    localjL1.hg("closePopup");
    localdRq11.setOnPopupHide(localjL1);
    localeR1.bb(localdRq11);
    localdRq11.brn();
    String str5 = "serverInfoPopup";
    anG localanG1 = new anG();
    localanG1.aJ();
    localanG1.setElementMap(localcpa);
    if ((localcpa != null) && (str5 != null))
      localcpa.a(str5, localanG1);
    localanG1.setAlign(aFG.ecl);
    localanG1.setHotSpotPosition(aFG.ecj);
    localdRq11.bb(localanG1);
    localanG1.brn();
    dRq localdRq12 = dRq.checkOut();
    localdRq12.setElementMap(localcpa);
    localdRq12.setPrefSize(new Or(10, 0));
    localdRq12.setStyle("popup");
    localanG1.bb(localdRq12);
    localdRq12.brn();
    dRq localdRq13 = localdRq12;
    Jg localJg7 = localdRq13.getAppearance();
    localJg7.setElementMap(localcpa);
    localdRq12.bb(localJg7);
    localJg7.brn();
    bmv localbmv5 = bmv.checkOut();
    localbmv5.setElementMap(localcpa);
    localbmv5.setInsets(new Insets(0, 10, 0, 0));
    localJg7.bb(localbmv5);
    localbmv5.brn();
    localbmv5.rV();
    localJg7.rV();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("visible");
    localaaE1.setField("description");
    localdRq12.bb(localaaE1);
    localaaE1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localaaE1.bb(localanQ1);
    localanQ1.brn();
    anE localanE1 = new anE();
    localanE1.aJ();
    localanE1.setElementMap(localcpa);
    localanQ1.bb(localanE1);
    localanE1.brn();
    localanE1.rV();
    localanQ1.rV();
    localaaE1.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("PopupInformation");
    localcWk1.setMinWidth(1);
    localcWk1.setMaxWidth(200);
    localdRq12.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg8 = localcWk2.getAppearance();
    localJg8.setElementMap(localcpa);
    ((cwJ)localJg8).setAlignment(aFG.ecj);
    localcWk1.bb(localJg8);
    localJg8.brn();
    localJg8.rV();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("text");
    localaaE2.setField("description");
    localcWk1.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    localcWk1.rV();
    localdRq12.rV();
    localanG1.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setExpandable(false);
    localczv1.setDisplaySize(new Or(20, 14));
    localczv1.setNonBlocking(true);
    localdRq11.bb(localczv1);
    localczv1.brn();
    czv localczv2 = localczv1;
    Jg localJg9 = localczv2.getAppearance();
    localJg9.setElementMap(localcpa);
    localczv1.bb(localJg9);
    localJg9.brn();
    bmv localbmv6 = bmv.checkOut();
    localbmv6.setElementMap(localcpa);
    localbmv6.setInsets(new Insets(0, 2, 0, 3));
    localJg9.bb(localbmv6);
    localbmv6.brn();
    localbmv6.rV();
    localJg9.rV();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv1.bb(localaAR);
    localaAR.brn();
    aaE localaaE3 = new aaE();
    localaaE3.aJ();
    localaaE3.setElementMap(localcpa);
    localaaE3.setAttribute("texture");
    localaaE3.setField("iconUrl");
    localaAR.bb(localaaE3);
    localaaE3.brn();
    localaaE3.rV();
    localaAR.rV();
    localczv1.rV();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setNonBlocking(true);
    localcaF3.setStyle("11bold");
    localdRq11.bb(localcaF3);
    localcaF3.brn();
    dpm localdpm3 = new dpm();
    localdpm3.aJ();
    localdpm3.setElementMap(localcpa);
    localdpm3.setAlign(aFG.eck);
    localcaF3.bb(localdpm3);
    localdpm3.brn();
    localdpm3.rV();
    aaE localaaE4 = new aaE();
    localaaE4.aJ();
    localaaE4.setElementMap(localcpa);
    localaaE4.setAttribute("text");
    localaaE4.setField("name");
    localcaF3.bb(localaaE4);
    localaaE4.brn();
    localaaE4.rV();
    localcaF3.rV();
    localdRq11.rV();
    localeR1.rV();
    localaxU.rV();
    ccG localccG = new ccG();
    localccG.aJ();
    localccG.setElementMap(localcpa);
    localccG.setHorizontal(false);
    localccG.setCellSize(new Or(100.0F, 16));
    localddG1.bb(localccG);
    localccG.brn();
    eR localeR2 = new eR();
    localeR2.aJ();
    localeR2.setElementMap(localcpa);
    localccG.bb(localeR2);
    localeR2.brn();
    dRq localdRq14 = dRq.checkOut();
    localdRq14.setElementMap(localcpa);
    localdRq14.setNonBlocking(false);
    cCu localcCu2 = new cCu();
    localcCu2.hg("popup(serverInfoPopup)");
    localdRq14.setOnPopupDisplay(localcCu2);
    jL localjL2 = new jL();
    localjL2.hg("closePopup");
    localdRq14.setOnPopupHide(localjL2);
    localeR2.bb(localdRq14);
    localdRq14.brn();
    dRq localdRq15 = localdRq14;
    Jg localJg10 = localdRq15.getAppearance();
    localJg10.setElementMap(localcpa);
    localdRq14.bb(localJg10);
    localJg10.brn();
    bmv localbmv7 = bmv.checkOut();
    localbmv7.setElementMap(localcpa);
    localbmv7.setInsets(new Insets(0, 0, 0, 0));
    localJg10.bb(localbmv7);
    localbmv7.brn();
    aaE localaaE5 = new aaE();
    localaaE5.aJ();
    localaaE5.setElementMap(localcpa);
    localaaE5.setAttribute("insets");
    localaaE5.setField("depthMargin");
    localbmv7.bb(localaaE5);
    localaaE5.brn();
    localaaE5.rV();
    localbmv7.rV();
    localJg10.rV();
    String str6 = "serverInfoPopup";
    anG localanG2 = new anG();
    localanG2.aJ();
    localanG2.setElementMap(localcpa);
    if ((localcpa != null) && (str6 != null))
      localcpa.a(str6, localanG2);
    localanG2.setAlign(aFG.ecl);
    localanG2.setHotSpotPosition(aFG.ecj);
    localdRq14.bb(localanG2);
    localanG2.brn();
    dRq localdRq16 = dRq.checkOut();
    localdRq16.setElementMap(localcpa);
    localdRq16.setPrefSize(new Or(10, 0));
    localdRq16.setStyle("popup");
    localanG2.bb(localdRq16);
    localdRq16.brn();
    aaE localaaE6 = new aaE();
    localaaE6.aJ();
    localaaE6.setElementMap(localcpa);
    localaaE6.setAttribute("visible");
    localaaE6.setField("description");
    localdRq16.bb(localaaE6);
    localaaE6.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localaaE6.bb(localanQ2);
    localanQ2.brn();
    anE localanE2 = new anE();
    localanE2.aJ();
    localanE2.setElementMap(localcpa);
    localanQ2.bb(localanE2);
    localanE2.brn();
    localanE2.rV();
    localanQ2.rV();
    localaaE6.rV();
    cWk localcWk3 = new cWk();
    localcWk3.aJ();
    localcWk3.setElementMap(localcpa);
    localcWk3.setStyle("PopupInformation");
    localcWk3.setMinWidth(1);
    localcWk3.setMaxWidth(200);
    localdRq16.bb(localcWk3);
    localcWk3.brn();
    cWk localcWk4 = localcWk3;
    Jg localJg11 = localcWk4.getAppearance();
    localJg11.setElementMap(localcpa);
    ((cwJ)localJg11).setAlignment(aFG.ecj);
    localcWk3.bb(localJg11);
    localJg11.brn();
    localJg11.rV();
    aaE localaaE7 = new aaE();
    localaaE7.aJ();
    localaaE7.setElementMap(localcpa);
    localaaE7.setAttribute("text");
    localaaE7.setField("description");
    localcWk3.bb(localaaE7);
    localaaE7.brn();
    localaaE7.rV();
    localcWk3.rV();
    localdRq16.rV();
    localanG2.rV();
    a(localdRq14);
    b(localdRq14);
    localdRq14.rV();
    localeR2.rV();
    localccG.rV();
    localddG1.rV();
    d(localdRq10);
    e(localdRq10);
    f(localdRq10);
    g(localdRq10);
    h(localdRq10);
    localdRq10.rV();
    i(localdRq9);
    j(localdRq9);
    localdRq9.rV();
    localdRq7.rV();
    k(localdRq2);
    localdRq2.rV();
    l(localbpn);
    m(localbpn);
    n(localbpn);
    localbpn.rV();
    return localbpn;
  }

  public bdj a(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setExpandable(false);
    localczv1.setDisplaySize(new Or(20, 14));
    localczv1.setNonBlocking(true);
    parambdj.bb(localczv1);
    localczv1.brn();
    czv localczv2 = localczv1;
    Jg localJg = localczv2.getAppearance();
    localJg.setElementMap(localcpa);
    localczv1.bb(localJg);
    localJg.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(0, 2, 0, 3));
    localJg.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg.rV();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv1.bb(localaAR);
    localaAR.brn();
    aaE localaaE = new aaE();
    localaaE.aJ();
    localaaE.setElementMap(localcpa);
    localaaE.setAttribute("texture");
    localaaE.setField("iconUrl");
    localaAR.bb(localaaE);
    localaaE.brn();
    localaaE.rV();
    localaAR.rV();
    localczv1.rV();
    return localczv1;
  }

  public bdj b(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    cWk localcWk = new cWk();
    localcWk.aJ();
    localcWk.setElementMap(localcpa);
    localcWk.setNonBlocking(true);
    localcWk.setStyle("darkbold11");
    localcWk.setMinWidth(1);
    localcWk.setMaxWidth(250);
    parambdj.bb(localcWk);
    localcWk.brn();
    aaE localaaE = new aaE();
    localaaE.aJ();
    localaaE.setElementMap(localcpa);
    localaaE.setAttribute("text");
    localaaE.setField("name");
    localcWk.bb(localaaE);
    localaaE.brn();
    localaaE.rV();
    localcWk.rV();
    return localcWk;
  }

  public bdj d(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setStyle("ShortcutRowBackgroundFull");
    localdRq1.setExpandable(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.eck);
    localdRq1.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    dRq localdRq2 = localdRq1;
    Jg localJg1 = localdRq2.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq1.bb(localJg1);
    localJg1.brn();
    cuR localcuR = new cuR();
    localcuR.aJ();
    localcuR.setElementMap(localcpa);
    localcuR.setInsets(new Insets(9, 6, 9, 6));
    localJg1.bb(localcuR);
    localcuR.brn();
    localcuR.rV();
    localJg1.rV();
    String str1 = "textEditor";
    aTp localaTp1 = new aTp();
    localaTp1.aJ();
    localaTp1.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localaTp1);
    localaTp1.setStyle("withoutBorder");
    localaTp1.setPrefSize(new Or(150, 0));
    String str2 = "%editSearch%";
    str2 = str2.replace("%editSearch%", cBQ.cxL().mL("editSearch"));
    localaTp1.setGhostText(str2);
    localaTp1.setSelectOnFocus(true);
    aOn localaOn = new aOn();
    localaOn.hg("wakfu.market:search(lowestPriceCB,textEditor,minLevel,maxLevel,minPrice,maxPrice)");
    localaTp1.setOnKeyPress(localaOn);
    localdRq1.bb(localaTp1);
    localaTp1.brn();
    aTp localaTp2 = localaTp1;
    Jg localJg2 = localaTp2.getAppearance();
    localJg2.setElementMap(localcpa);
    ((cwJ)localJg2).setAlign(aFG.ecj);
    localaTp1.bb(localJg2);
    localJg2.brn();
    localJg2.rV();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setAttribute("enabled");
    localNK.setName("webShop");
    localNK.setField("ready");
    localaTp1.bb(localNK);
    localNK.brn();
    localNK.rV();
    localaTp1.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj e(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    biy localbiy = new biy();
    localbiy.aJ();
    localbiy.setElementMap(localcpa);
    localbiy.setExpandable(false);
    csA localcsA = new csA();
    localcsA.hg("wakfu.webShop:search(session,textEditor)");
    localbiy.setOnClick(localcsA);
    parambdj.bb(localbiy);
    localbiy.brn();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.eck);
    localbiy.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setStyle("magnifyingGlass2");
    localczv.setDisplaySize(new Or(20, 20));
    localczv.setNonBlocking(true);
    localbiy.bb(localczv);
    localczv.brn();
    localczv.rV();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setAttribute("enabled");
    localNK.setName("webShop");
    localNK.setField("ready");
    localbiy.bb(localNK);
    localNK.brn();
    localNK.rV();
    localbiy.rV();
    return localbiy;
  }

  public bdj f(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    biy localbiy = new biy();
    localbiy.aJ();
    localbiy.setElementMap(localcpa);
    localbiy.setExpandable(false);
    csA localcsA = new csA();
    localcsA.hg("wakfu.webShop:resetSearch(session,textEditor)");
    localbiy.setOnClick(localcsA);
    parambdj.bb(localbiy);
    localbiy.brn();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.eck);
    localbiy.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setStyle("cancel");
    localczv.setDisplaySize(new Or(20, 20));
    localczv.setNonBlocking(true);
    localbiy.bb(localczv);
    localczv.brn();
    localczv.rV();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setAttribute("enabled");
    localNK.setName("webShop");
    localNK.setField("ready");
    localbiy.bb(localNK);
    localNK.brn();
    localNK.rV();
    localbiy.rV();
    return localbiy;
  }

  public bdj g(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dAS localdAS = new dAS();
    localdAS.aJ();
    localdAS.setElementMap(localcpa);
    parambdj.bb(localdAS);
    localdAS.brn();
    localdAS.rV();
    return localdAS;
  }

  public bdj h(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    ccG localccG = new ccG();
    localccG.aJ();
    localccG.setElementMap(localcpa);
    localccG.setCellSize(new Or(200, 30));
    localccG.setAutoIdealSize(true);
    localccG.setIdealSizeMinColumns(1);
    localccG.setIdealSizeMaxColumns(1);
    localdRq1.bb(localccG);
    localccG.brn();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setName("webShop");
    localNK.setAttribute("content");
    localNK.setField("wallet");
    localccG.bb(localNK);
    localNK.brn();
    localNK.rV();
    eR localeR = new eR();
    localeR.aJ();
    localeR.setElementMap(localcpa);
    localccG.bb(localeR);
    localeR.brn();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setStyle("white");
    localeR.bb(localdRq2);
    localdRq2.brn();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(true);
    localdRq2.bb(localaId);
    localaId.brn();
    localaId.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setMinWidth(1);
    localcWk1.setMaxWidth(100);
    localdRq2.bb(localcWk1);
    localcWk1.brn();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa);
    localdpm1.setAlign(aFG.eck);
    localcWk1.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("text");
    localaaE1.setField("description");
    localcWk1.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    localcWk1.rV();
    cWk localcWk2 = new cWk();
    localcWk2.aJ();
    localcWk2.setElementMap(localcpa);
    localcWk2.setMinWidth(1);
    localcWk2.setMaxWidth(100);
    localcWk2.setStyle("title");
    localcWk2.setExpandable(false);
    localdRq2.bb(localcWk2);
    localcWk2.brn();
    cWk localcWk3 = localcWk2;
    Jg localJg = localcWk3.getAppearance();
    localJg.setElementMap(localcpa);
    localcWk2.bb(localJg);
    localJg.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(0, 0, 0, 4));
    localJg.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg.rV();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa);
    localdpm2.setAlign(aFG.eck);
    localcWk2.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("text");
    localaaE2.setField("value");
    localcWk2.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    localcWk2.rV();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setExpandable(false);
    localdRq2.bb(localczv);
    localczv.brn();
    dpm localdpm3 = new dpm();
    localdpm3.aJ();
    localdpm3.setElementMap(localcpa);
    localdpm3.setAlign(aFG.eck);
    localczv.bb(localdpm3);
    localdpm3.brn();
    localdpm3.rV();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv.bb(localaAR);
    localaAR.brn();
    aaE localaaE3 = new aaE();
    localaaE3.aJ();
    localaaE3.setElementMap(localcpa);
    localaaE3.setAttribute("texture");
    localaaE3.setField("currency");
    localaAR.bb(localaaE3);
    localaaE3.brn();
    localaaE3.rV();
    localaAR.rV();
    localczv.rV();
    localdRq2.rV();
    localeR.rV();
    localccG.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj i(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setStyle("chatBubble");
    parambdj.bb(localdRq1);
    localdRq1.brn();
    dRq localdRq2 = localdRq1;
    Jg localJg1 = localdRq2.getAppearance();
    localJg1.setElementMap(localcpa);
    localJg1.setModulationColor(new bNa(0.3647059F, 0.3098039F, 0.2705883F, 1.0F));
    localdRq1.bb(localJg1);
    localJg1.brn();
    cuR localcuR = new cuR();
    localcuR.aJ();
    localcuR.setElementMap(localcpa);
    localcuR.setInsets(new Insets(10, 10, 10, 10));
    localJg1.bb(localcuR);
    localcuR.brn();
    localcuR.rV();
    localJg1.rV();
    ccG localccG = new ccG();
    localccG.aJ();
    localccG.setElementMap(localcpa);
    localccG.setCellSize(new Or(350, 80));
    localccG.setAutoIdealSize(true);
    localccG.setIdealSizeMinColumns(2);
    localccG.setIdealSizeMaxColumns(2);
    localccG.setIdealSizeMinRows(5);
    localccG.setIdealSizeMaxRows(5);
    localdRq1.bb(localccG);
    localccG.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setName("webShop");
    localNK1.setAttribute("content");
    localNK1.setField("articles");
    localccG.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    eR localeR = new eR();
    localeR.aJ();
    localeR.setElementMap(localcpa);
    localccG.bb(localeR);
    localeR.brn();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localeR.bb(localdRq3);
    localdRq3.brn();
    String str1 = "article";
    avo localavo1 = new avo();
    localavo1.aJ();
    localavo1.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localavo1);
    localdRq3.bb(localavo1);
    localavo1.brn();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("value");
    localavo1.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    localavo1.rV();
    String str2 = "articleContent";
    avo localavo2 = new avo();
    localavo2.aJ();
    localavo2.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localavo2);
    localdRq3.bb(localavo2);
    localavo2.brn();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("value");
    localaaE2.setField("content");
    localavo2.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    localavo2.rV();
    dRq localdRq4 = localdRq3;
    Jg localJg2 = localdRq4.getAppearance();
    localJg2.setElementMap(localcpa);
    localdRq3.bb(localJg2);
    localJg2.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 2, 0, 2));
    localJg2.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg2.rV();
    dRq localdRq5 = dRq.checkOut();
    localdRq5.setElementMap(localcpa);
    localdRq5.setStyle("WebShopItemLeft");
    localdRq5.setPrefSize(new Or(170, 0));
    localdRq3.bb(localdRq5);
    localdRq5.brn();
    dRq localdRq6 = localdRq5;
    Jg localJg3 = localdRq6.getAppearance();
    localJg3.setElementMap(localcpa);
    localJg3.setModulationColor(new bNa(0.3686275F, 0.9490196F, 0.9019608F, 1.0F));
    localdRq5.bb(localJg3);
    localJg3.brn();
    localJg3.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localdRq7.setStyle("webShopItem");
    localdRq7.setExpandable(false);
    csA localcsA1 = new csA();
    localcsA1.hg("wakfu.webShop:openItemDescription(articleContent)");
    localdRq7.setOnClick(localcsA1);
    localdRq5.bb(localdRq7);
    localdRq7.brn();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa);
    localdpm1.setAlign(aFG.eck);
    localdRq7.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    dRq localdRq8 = localdRq7;
    Jg localJg4 = localdRq8.getAppearance();
    localJg4.setElementMap(localcpa);
    localJg4.setModulationColor(new bNa(0.2352941F, 0.6F, 0.5686275F, 1.0F));
    localdRq7.bb(localJg4);
    localJg4.brn();
    localJg4.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setDisplaySize(new Or(48, 48));
    localczv1.setExpandable(false);
    localdRq7.bb(localczv1);
    localczv1.brn();
    aAR localaAR1 = aAR.checkOut();
    localaAR1.setElementMap(localcpa);
    localczv1.bb(localaAR1);
    localaAR1.brn();
    aaE localaaE3 = new aaE();
    localaaE3.aJ();
    localaaE3.setElementMap(localcpa);
    localaaE3.setAttribute("texture");
    localaaE3.setField("iconUrl");
    localaAR1.bb(localaaE3);
    localaaE3.brn();
    localaaE3.rV();
    localaAR1.rV();
    localczv1.rV();
    localdRq7.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setMinWidth(120);
    localcWk1.setMaxWidth(120);
    localcWk1.setStyle("whiteBold11");
    localdRq5.bb(localcWk1);
    localcWk1.brn();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa);
    localdpm2.setAlign(aFG.eck);
    localcWk1.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    aaE localaaE4 = new aaE();
    localaaE4.aJ();
    localaaE4.setElementMap(localcpa);
    localaaE4.setAttribute("text");
    localaaE4.setField("name");
    localcWk1.bb(localaaE4);
    localaaE4.brn();
    localaaE4.rV();
    cWk localcWk2 = localcWk1;
    Jg localJg5 = localcWk2.getAppearance();
    localJg5.setElementMap(localcpa);
    localcWk1.bb(localJg5);
    localJg5.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 5, 0, 5));
    localJg5.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg5.rV();
    localcWk1.rV();
    localdRq5.rV();
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa);
    localdRq9.setStyle("WebShopItemCenter");
    localdRq9.setPrefSize(new Or(80, 0));
    localdRq9.setExpandable(false);
    localdRq3.bb(localdRq9);
    localdRq9.brn();
    dRq localdRq10 = localdRq9;
    Jg localJg6 = localdRq10.getAppearance();
    localJg6.setElementMap(localcpa);
    localJg6.setModulationColor(new bNa(0.3686275F, 0.9490196F, 0.9019608F, 1.0F));
    localdRq9.bb(localJg6);
    localJg6.brn();
    localJg6.rV();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(false);
    localdRq9.bb(localaId);
    localaId.brn();
    localaId.rV();
    dRq localdRq11 = dRq.checkOut();
    localdRq11.setElementMap(localcpa);
    localdRq11.setExpandable(false);
    localdRq9.bb(localdRq11);
    localdRq11.brn();
    dpm localdpm3 = new dpm();
    localdpm3.aJ();
    localdpm3.setElementMap(localcpa);
    localdpm3.setAlign(aFG.eck);
    localdRq11.bb(localdpm3);
    localdpm3.brn();
    localdpm3.rV();
    aaE localaaE5 = new aaE();
    localaaE5.aJ();
    localaaE5.setElementMap(localcpa);
    localaaE5.setAttribute("visible");
    localaaE5.setField("originalPrice");
    localdRq11.bb(localaaE5);
    localaaE5.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localaaE5.bb(localanQ1);
    localanQ1.brn();
    anE localanE1 = new anE();
    localanE1.aJ();
    localanE1.setElementMap(localcpa);
    localanQ1.bb(localanE1);
    localanE1.brn();
    localanE1.rV();
    localanQ1.rV();
    localaaE5.rV();
    cWk localcWk3 = new cWk();
    localcWk3.aJ();
    localcWk3.setElementMap(localcpa);
    localcWk3.setStyle("whiteBold11");
    localdRq11.bb(localcWk3);
    localcWk3.brn();
    dpm localdpm4 = new dpm();
    localdpm4.aJ();
    localdpm4.setElementMap(localcpa);
    localdpm4.setAlign(aFG.eck);
    localcWk3.bb(localdpm4);
    localdpm4.brn();
    localdpm4.rV();
    aaE localaaE6 = new aaE();
    localaaE6.aJ();
    localaaE6.setElementMap(localcpa);
    localaaE6.setAttribute("text");
    localaaE6.setField("originalPrice");
    localcWk3.bb(localaaE6);
    localaaE6.brn();
    localaaE6.rV();
    localcWk3.rV();
    czv localczv2 = new czv();
    localczv2.aJ();
    localczv2.setElementMap(localcpa);
    localczv2.setExpandable(false);
    localdRq11.bb(localczv2);
    localczv2.brn();
    dpm localdpm5 = new dpm();
    localdpm5.aJ();
    localdpm5.setElementMap(localcpa);
    localdpm5.setAlign(aFG.eck);
    localczv2.bb(localdpm5);
    localdpm5.brn();
    localdpm5.rV();
    aAR localaAR2 = aAR.checkOut();
    localaAR2.setElementMap(localcpa);
    localczv2.bb(localaAR2);
    localaAR2.brn();
    aaE localaaE7 = new aaE();
    localaaE7.aJ();
    localaaE7.setElementMap(localcpa);
    localaaE7.setAttribute("texture");
    localaaE7.setField("currency");
    localaAR2.bb(localaaE7);
    localaaE7.brn();
    localaaE7.rV();
    localaAR2.rV();
    localczv2.rV();
    localdRq11.rV();
    dRq localdRq12 = dRq.checkOut();
    localdRq12.setElementMap(localcpa);
    localdRq12.setExpandable(false);
    localdRq9.bb(localdRq12);
    localdRq12.brn();
    dpm localdpm6 = new dpm();
    localdpm6.aJ();
    localdpm6.setElementMap(localcpa);
    localdpm6.setAlign(aFG.eck);
    localdRq12.bb(localdpm6);
    localdpm6.brn();
    localdpm6.rV();
    cWk localcWk4 = new cWk();
    localcWk4.aJ();
    localcWk4.setElementMap(localcpa);
    localcWk4.setStyle("whiteTitle");
    localcWk4.setMinWidth(1);
    localcWk4.setMaxWidth(50);
    localdRq12.bb(localcWk4);
    localcWk4.brn();
    dpm localdpm7 = new dpm();
    localdpm7.aJ();
    localdpm7.setElementMap(localcpa);
    localdpm7.setAlign(aFG.eck);
    localcWk4.bb(localdpm7);
    localdpm7.brn();
    localdpm7.rV();
    aaE localaaE8 = new aaE();
    localaaE8.aJ();
    localaaE8.setElementMap(localcpa);
    localaaE8.setAttribute("text");
    localaaE8.setField("price");
    localcWk4.bb(localaaE8);
    localaaE8.brn();
    localaaE8.rV();
    localcWk4.rV();
    czv localczv3 = new czv();
    localczv3.aJ();
    localczv3.setElementMap(localcpa);
    localczv3.setExpandable(false);
    localdRq12.bb(localczv3);
    localczv3.brn();
    dpm localdpm8 = new dpm();
    localdpm8.aJ();
    localdpm8.setElementMap(localcpa);
    localdpm8.setAlign(aFG.eck);
    localczv3.bb(localdpm8);
    localdpm8.brn();
    localdpm8.rV();
    aAR localaAR3 = aAR.checkOut();
    localaAR3.setElementMap(localcpa);
    localczv3.bb(localaAR3);
    localaAR3.brn();
    aaE localaaE9 = new aaE();
    localaaE9.aJ();
    localaaE9.setElementMap(localcpa);
    localaaE9.setAttribute("texture");
    localaaE9.setField("currency");
    localaAR3.bb(localaaE9);
    localaaE9.brn();
    localaaE9.rV();
    localaAR3.rV();
    localczv3.rV();
    localdRq12.rV();
    cWk localcWk5 = new cWk();
    localcWk5.aJ();
    localcWk5.setElementMap(localcpa);
    localcWk5.setStyle("whiteBold11");
    localcWk5.setMinWidth(1);
    localcWk5.setMaxWidth(60);
    localdRq9.bb(localcWk5);
    localcWk5.brn();
    dpm localdpm9 = new dpm();
    localdpm9.aJ();
    localdpm9.setElementMap(localcpa);
    localdpm9.setAlign(aFG.eck);
    localcWk5.bb(localdpm9);
    localdpm9.brn();
    localdpm9.rV();
    aaE localaaE10 = new aaE();
    localaaE10.aJ();
    localaaE10.setElementMap(localcpa);
    localaaE10.setAttribute("text");
    localaaE10.setField("stock");
    localcWk5.bb(localaaE10);
    localaaE10.brn();
    localaaE10.rV();
    aaE localaaE11 = new aaE();
    localaaE11.aJ();
    localaaE11.setElementMap(localcpa);
    localaaE11.setAttribute("visible");
    localaaE11.setField("stock");
    localcWk5.bb(localaaE11);
    localaaE11.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localaaE11.bb(localanQ2);
    localanQ2.brn();
    anE localanE2 = new anE();
    localanE2.aJ();
    localanE2.setElementMap(localcpa);
    localanQ2.bb(localanE2);
    localanE2.brn();
    localanE2.rV();
    localanQ2.rV();
    localaaE11.rV();
    localcWk5.rV();
    localdRq9.rV();
    dRq localdRq13 = dRq.checkOut();
    localdRq13.setElementMap(localcpa);
    localdRq13.setStyle("WebShopItemRight");
    localdRq13.setPrefSize(new Or(50, 0));
    localdRq13.setExpandable(false);
    localdRq3.bb(localdRq13);
    localdRq13.brn();
    dRq localdRq14 = localdRq13;
    Jg localJg7 = localdRq14.getAppearance();
    localJg7.setElementMap(localcpa);
    localJg7.setModulationColor(new bNa(0.3686275F, 0.9490196F, 0.9019608F, 1.0F));
    localdRq13.bb(localJg7);
    localJg7.brn();
    localJg7.rV();
    biy localbiy = new biy();
    localbiy.aJ();
    localbiy.setElementMap(localcpa);
    localbiy.setStyle("WebShopBuy");
    csA localcsA2 = new csA();
    localcsA2.hg("wakfu.webShop:openArticleDescription(article)");
    localbiy.setOnClick(localcsA2);
    localdRq13.bb(localbiy);
    localbiy.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setAttribute("enabled");
    localNK2.setName("webShop");
    localNK2.setField("ready");
    localbiy.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localbiy.rV();
    localdRq13.rV();
    localdRq3.rV();
    localeR.rV();
    localccG.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj j(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    dRq localdRq2 = localdRq1;
    Jg localJg1 = localdRq2.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq1.bb(localJg1);
    localJg1.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(5, 0, 0, 0));
    localJg1.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg1.rV();
    aId localaId = aId.checkOut();
    localaId.setAlign(aFG.eck);
    localdRq1.bb(localaId);
    localaId.brn();
    localaId.rV();
    biy localbiy1 = new biy();
    localbiy1.aJ();
    localbiy1.setElementMap(localcpa);
    localbiy1.setExpandable(false);
    localbiy1.setStyle("whiteLeftArrowWithStop");
    localbiy1.setNetEnabledId("marketBoardSearchLock");
    localbiy1.setEnabled(false);
    csA localcsA1 = new csA();
    localcsA1.hg("wakfu.webShop:first(session)");
    localbiy1.setOnClick(localcsA1);
    localdRq1.bb(localbiy1);
    localbiy1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setName("webShop");
    localNK1.setField("currentPage");
    localNK1.setAttribute("enabled");
    localbiy1.bb(localNK1);
    localNK1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localNK1.bb(localanQ1);
    localanQ1.brn();
    aEJ localaEJ1 = new aEJ();
    localaEJ1.aJ();
    localaEJ1.setElementMap(localcpa);
    localaEJ1.setValue("1");
    localanQ1.bb(localaEJ1);
    localaEJ1.brn();
    localaEJ1.rV();
    localanQ1.rV();
    localNK1.rV();
    localbiy1.rV();
    biy localbiy2 = new biy();
    localbiy2.aJ();
    localbiy2.setElementMap(localcpa);
    localbiy2.setExpandable(false);
    localbiy2.setStyle("whiteLeftArrow");
    localbiy2.setNetEnabledId("marketBoardSearchLock");
    localbiy2.setEnabled(false);
    csA localcsA2 = new csA();
    localcsA2.hg("wakfu.webShop:previous(session)");
    localbiy2.setOnClick(localcsA2);
    localdRq1.bb(localbiy2);
    localbiy2.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("webShop");
    localNK2.setField("currentPage");
    localNK2.setAttribute("enabled");
    localbiy2.bb(localNK2);
    localNK2.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localNK2.bb(localanQ2);
    localanQ2.brn();
    aEJ localaEJ2 = new aEJ();
    localaEJ2.aJ();
    localaEJ2.setElementMap(localcpa);
    localaEJ2.setValue("1");
    localanQ2.bb(localaEJ2);
    localaEJ2.brn();
    localaEJ2.rV();
    localanQ2.rV();
    localNK2.rV();
    localbiy2.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setExpandable(false);
    localcaF1.setPrefSize(new Or(250, 0));
    String str = "%marketBoard.noResults%";
    str = str.replace("%marketBoard.noResults%", cBQ.cxL().mL("marketBoard.noResults"));
    localcaF1.setText(str);
    localdRq1.bb(localcaF1);
    localcaF1.brn();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setName("webShop");
    localNK3.setField("pagesDescription");
    localNK3.setAttribute("text");
    localcaF1.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    caF localcaF2 = localcaF1;
    Jg localJg2 = localcaF2.getAppearance();
    localJg2.setElementMap(localcpa);
    ((cwJ)localJg2).setAlign(aFG.eck);
    localcaF1.bb(localJg2);
    localJg2.brn();
    localJg2.rV();
    localcaF1.rV();
    biy localbiy3 = new biy();
    localbiy3.aJ();
    localbiy3.setElementMap(localcpa);
    localbiy3.setExpandable(false);
    localbiy3.setStyle("whiteRightArrow");
    localbiy3.setNetEnabledId("marketBoardSearchLock");
    localbiy3.setEnabled(false);
    csA localcsA3 = new csA();
    localcsA3.hg("wakfu.webShop:next(session)");
    localbiy3.setOnClick(localcsA3);
    localdRq1.bb(localbiy3);
    localbiy3.brn();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa);
    localNK4.setName("webShop");
    localNK4.setField("currentPage");
    localNK4.setAttribute("enabled");
    localbiy3.bb(localNK4);
    localNK4.brn();
    anQ localanQ3 = new anQ();
    localanQ3.aJ();
    localanQ3.setElementMap(localcpa);
    localNK4.bb(localanQ3);
    localanQ3.brn();
    asH localasH1 = new asH();
    localasH1.aJ();
    localasH1.setElementMap(localcpa);
    localanQ3.bb(localasH1);
    localasH1.brn();
    NK localNK5 = NK.checkOut();
    localNK5.setElementMap(localcpa);
    localNK5.setName("webShop");
    localNK5.setAttribute("value");
    localNK5.setField("totalPages");
    localasH1.bb(localNK5);
    localNK5.brn();
    localNK5.rV();
    localasH1.rV();
    localanQ3.rV();
    localNK4.rV();
    localbiy3.rV();
    biy localbiy4 = new biy();
    localbiy4.aJ();
    localbiy4.setElementMap(localcpa);
    localbiy4.setExpandable(false);
    localbiy4.setStyle("whiteRightArrowWithStop");
    localbiy4.setNetEnabledId("marketBoardSearchLock");
    localbiy4.setEnabled(false);
    csA localcsA4 = new csA();
    localcsA4.hg("wakfu.webShop:last(session)");
    localbiy4.setOnClick(localcsA4);
    localdRq1.bb(localbiy4);
    localbiy4.brn();
    NK localNK6 = NK.checkOut();
    localNK6.setElementMap(localcpa);
    localNK6.setName("webShop");
    localNK6.setField("currentPage");
    localNK6.setAttribute("enabled");
    localbiy4.bb(localNK6);
    localNK6.brn();
    anQ localanQ4 = new anQ();
    localanQ4.aJ();
    localanQ4.setElementMap(localcpa);
    localNK6.bb(localanQ4);
    localanQ4.brn();
    asH localasH2 = new asH();
    localasH2.aJ();
    localasH2.setElementMap(localcpa);
    localanQ4.bb(localasH2);
    localasH2.brn();
    NK localNK7 = NK.checkOut();
    localNK7.setElementMap(localcpa);
    localNK7.setName("webShop");
    localNK7.setAttribute("value");
    localNK7.setField("totalPages");
    localasH2.bb(localNK7);
    localNK7.brn();
    localNK7.rV();
    localasH2.rV();
    localanQ4.rV();
    localNK6.rV();
    localbiy4.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj k(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dOc localdOc = (dOc)parambdj;
    Jg localJg = localdOc.getAppearance();
    localJg.setElementMap(localcpa);
    parambdj.bb(localJg);
    localJg.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(0, 61, 0, 0));
    localJg.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    cuR localcuR = new cuR();
    localcuR.aJ();
    localcuR.setElementMap(localcpa);
    localcuR.setInsets(new Insets(10, 5, 12, 5));
    localJg.bb(localcuR);
    localcuR.brn();
    localcuR.rV();
    localJg.rV();
    return localJg;
  }

  public bdj l(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setVisible(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setAlign(aFG.ecj);
    localdRq1.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setExpandable(false);
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(50, 0, 0, 0));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.ech);
    localdRq2.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    aId localaId2 = aId.checkOut();
    localaId2.setHorizontal(false);
    localdRq2.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    String str1 = "searchRadio";
    bmG localbmG = new bmG();
    localbmG.aJ();
    localbmG.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localbmG);
    localbmG.setValue("0");
    localdRq2.bb(localbmG);
    localbmG.brn();
    localbmG.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setExpandable(false);
    localdRq2.bb(localdRq4);
    localdRq4.brn();
    dRq localdRq5 = localdRq4;
    Jg localJg2 = localdRq5.getAppearance();
    localJg2.setElementMap(localcpa);
    localdRq4.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(10, 0, 0, 0));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    czO localczO1 = new czO();
    localczO1.aJ();
    localczO1.setAdaptToContentSize(true);
    localdRq4.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    aHd localaHd1 = new aHd();
    localaHd1.aJ();
    localaHd1.setElementMap(localcpa);
    localaHd1.setGroupId("searchRadio");
    localaHd1.setValue("0");
    localaHd1.setStyle("bigLeftWindow");
    cCu localcCu1 = new cCu();
    localcCu1.hg("popup(guildDescButtonPopup)");
    localaHd1.setOnPopupDisplay(localcCu1);
    jL localjL1 = new jL();
    localjL1.hg("closePopup");
    localaHd1.setOnPopupHide(localjL1);
    bvO localbvO1 = new bvO();
    localbvO1.hg("wakfu.webShop:search1(session)");
    localaHd1.setOnSelectionChange(localbvO1);
    localdRq4.bb(localaHd1);
    localaHd1.brn();
    String str2 = "guildDescButtonPopup";
    anG localanG1 = new anG();
    localanG1.aJ();
    localanG1.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localanG1);
    localanG1.setAlign(aFG.ech);
    localanG1.setHotSpotPosition(aFG.ecn);
    localaHd1.bb(localanG1);
    localanG1.brn();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq6.setPrefSize(new Or(10, 0));
    localdRq6.setStyle("popup");
    localanG1.bb(localdRq6);
    localdRq6.brn();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("white");
    localcWk1.setEnableShrinking(false);
    String str3 = "%webShop.search1%";
    str3 = str3.replace("%webShop.search1%", cBQ.cxL().mL("webShop.search1"));
    localcWk1.setText(str3);
    localdRq6.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg3 = localcWk2.getAppearance();
    localJg3.setElementMap(localcpa);
    ((cwJ)localJg3).setAlignment(aFG.eck);
    localcWk1.bb(localJg3);
    localJg3.brn();
    localJg3.rV();
    localcWk1.rV();
    localdRq6.rV();
    localanG1.rV();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setSize(new Or(-2, -2));
    localcwP2.setAlign(ajb.dif);
    localaHd1.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    localaHd1.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setNonBlocking(true);
    localczv1.setStyle("MarketSell");
    localdRq4.bb(localczv1);
    localczv1.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setSize(new Or(-2, -2));
    localcwP3.setAlign(ajb.dhT);
    localcwP3.setYOffset(20);
    localcwP3.setXOffset(1);
    localczv1.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    localczv1.rV();
    localdRq4.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localdRq7.setExpandable(false);
    localdRq2.bb(localdRq7);
    localdRq7.brn();
    czO localczO2 = new czO();
    localczO2.aJ();
    localczO2.setAdaptToContentSize(true);
    localdRq7.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    aHd localaHd2 = new aHd();
    localaHd2.aJ();
    localaHd2.setElementMap(localcpa);
    localaHd2.setGroupId("searchRadio");
    localaHd2.setValue("1");
    localaHd2.setStyle("bigLeftWindow");
    cCu localcCu2 = new cCu();
    localcCu2.hg("popup(generalButtonPopup)");
    localaHd2.setOnPopupDisplay(localcCu2);
    jL localjL2 = new jL();
    localjL2.hg("closePopup");
    localaHd2.setOnPopupHide(localjL2);
    bvO localbvO2 = new bvO();
    localbvO2.hg("wakfu.webShop:search2(session)");
    localaHd2.setOnSelectionChange(localbvO2);
    localdRq7.bb(localaHd2);
    localaHd2.brn();
    String str4 = "generalButtonPopup";
    anG localanG2 = new anG();
    localanG2.aJ();
    localanG2.setElementMap(localcpa);
    if ((localcpa != null) && (str4 != null))
      localcpa.a(str4, localanG2);
    localanG2.setAlign(aFG.ech);
    localanG2.setHotSpotPosition(aFG.ecn);
    localaHd2.bb(localanG2);
    localanG2.brn();
    dRq localdRq8 = dRq.checkOut();
    localdRq8.setElementMap(localcpa);
    localdRq8.setPrefSize(new Or(10, 0));
    localdRq8.setStyle("popup");
    localanG2.bb(localdRq8);
    localdRq8.brn();
    cWk localcWk3 = new cWk();
    localcWk3.aJ();
    localcWk3.setElementMap(localcpa);
    localcWk3.setStyle("white");
    localcWk3.setEnableShrinking(false);
    String str5 = "%webShop.search2%";
    str5 = str5.replace("%webShop.search2%", cBQ.cxL().mL("webShop.search2"));
    localcWk3.setText(str5);
    localdRq8.bb(localcWk3);
    localcWk3.brn();
    cWk localcWk4 = localcWk3;
    Jg localJg4 = localcWk4.getAppearance();
    localJg4.setElementMap(localcpa);
    ((cwJ)localJg4).setAlignment(aFG.eck);
    localcWk3.bb(localJg4);
    localJg4.brn();
    localJg4.rV();
    localcWk3.rV();
    localdRq8.rV();
    localanG2.rV();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setSize(new Or(-2, -2));
    localcwP4.setAlign(ajb.dif);
    localaHd2.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    localaHd2.rV();
    czv localczv2 = new czv();
    localczv2.aJ();
    localczv2.setElementMap(localcpa);
    localczv2.setNonBlocking(true);
    localczv2.setStyle("webShopItemCard");
    localdRq7.bb(localczv2);
    localczv2.brn();
    cwP localcwP5 = new cwP();
    localcwP5.aJ();
    localcwP5.setElementMap(localcpa);
    localcwP5.setSize(new Or(-2, -2));
    localcwP5.setAlign(ajb.dhT);
    localcwP5.setYOffset(25);
    localcwP5.setXOffset(5);
    localczv2.bb(localcwP5);
    localcwP5.brn();
    localcwP5.rV();
    localczv2.rV();
    localdRq7.rV();
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa);
    localdRq9.setExpandable(false);
    localdRq2.bb(localdRq9);
    localdRq9.brn();
    dRq localdRq10 = localdRq9;
    Jg localJg5 = localdRq10.getAppearance();
    localJg5.setElementMap(localcpa);
    localdRq9.bb(localJg5);
    localJg5.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(10, 0, 0, 0));
    localJg5.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg5.rV();
    czO localczO3 = new czO();
    localczO3.aJ();
    localczO3.setAdaptToContentSize(true);
    localdRq9.bb(localczO3);
    localczO3.brn();
    localczO3.rV();
    aHd localaHd3 = new aHd();
    localaHd3.aJ();
    localaHd3.setElementMap(localcpa);
    localaHd3.setGroupId("searchRadio");
    localaHd3.setValue("2");
    localaHd3.setStyle("bigLeftWindow");
    cCu localcCu3 = new cCu();
    localcCu3.hg("popup(guildRanksButtonPopup)");
    localaHd3.setOnPopupDisplay(localcCu3);
    jL localjL3 = new jL();
    localjL3.hg("closePopup");
    localaHd3.setOnPopupHide(localjL3);
    bvO localbvO3 = new bvO();
    localbvO3.hg("wakfu.webShop:search3(session)");
    localaHd3.setOnSelectionChange(localbvO3);
    localdRq9.bb(localaHd3);
    localaHd3.brn();
    String str6 = "guildRanksButtonPopup";
    anG localanG3 = new anG();
    localanG3.aJ();
    localanG3.setElementMap(localcpa);
    if ((localcpa != null) && (str6 != null))
      localcpa.a(str6, localanG3);
    localanG3.setAlign(aFG.ech);
    localanG3.setHotSpotPosition(aFG.ecn);
    localaHd3.bb(localanG3);
    localanG3.brn();
    dRq localdRq11 = dRq.checkOut();
    localdRq11.setElementMap(localcpa);
    localdRq11.setPrefSize(new Or(10, 0));
    localdRq11.setStyle("popup");
    localanG3.bb(localdRq11);
    localdRq11.brn();
    cWk localcWk5 = new cWk();
    localcWk5.aJ();
    localcWk5.setElementMap(localcpa);
    localcWk5.setStyle("white");
    localcWk5.setEnableShrinking(false);
    String str7 = "%webShop.search3%";
    str7 = str7.replace("%webShop.search3%", cBQ.cxL().mL("webShop.search3"));
    localcWk5.setText(str7);
    localdRq11.bb(localcWk5);
    localcWk5.brn();
    cWk localcWk6 = localcWk5;
    Jg localJg6 = localcWk6.getAppearance();
    localJg6.setElementMap(localcpa);
    ((cwJ)localJg6).setAlignment(aFG.eck);
    localcWk5.bb(localJg6);
    localJg6.brn();
    localJg6.rV();
    localcWk5.rV();
    localdRq11.rV();
    localanG3.rV();
    cwP localcwP6 = new cwP();
    localcwP6.aJ();
    localcwP6.setElementMap(localcpa);
    localcwP6.setSize(new Or(-2, -2));
    localcwP6.setAlign(ajb.dif);
    localaHd3.bb(localcwP6);
    localcwP6.brn();
    localcwP6.rV();
    localaHd3.rV();
    czv localczv3 = new czv();
    localczv3.aJ();
    localczv3.setElementMap(localcpa);
    localczv3.setNonBlocking(true);
    localczv3.setStyle("webShopHot");
    localdRq9.bb(localczv3);
    localczv3.brn();
    cwP localcwP7 = new cwP();
    localcwP7.aJ();
    localcwP7.setElementMap(localcpa);
    localcwP7.setSize(new Or(-2, -2));
    localcwP7.setAlign(ajb.dhT);
    localcwP7.setXOffset(1);
    localcwP7.setYOffset(25);
    localczv3.bb(localcwP7);
    localcwP7.brn();
    localcwP7.rV();
    localczv3.rV();
    localdRq9.rV();
    dRq localdRq12 = dRq.checkOut();
    localdRq12.setElementMap(localcpa);
    localdRq12.setExpandable(false);
    localdRq2.bb(localdRq12);
    localdRq12.brn();
    dRq localdRq13 = localdRq12;
    Jg localJg7 = localdRq13.getAppearance();
    localJg7.setElementMap(localcpa);
    localdRq12.bb(localJg7);
    localJg7.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(10, 0, 0, 0));
    localJg7.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg7.rV();
    czO localczO4 = new czO();
    localczO4.aJ();
    localczO4.setAdaptToContentSize(true);
    localdRq12.bb(localczO4);
    localczO4.brn();
    localczO4.rV();
    aHd localaHd4 = new aHd();
    localaHd4.aJ();
    localaHd4.setElementMap(localcpa);
    localaHd4.setGroupId("searchRadio");
    localaHd4.setValue("3");
    localaHd4.setStyle("bigLeftWindow");
    cCu localcCu4 = new cCu();
    localcCu4.hg("popup(guildImprovementButtonPopup)");
    localaHd4.setOnPopupDisplay(localcCu4);
    jL localjL4 = new jL();
    localjL4.hg("closePopup");
    localaHd4.setOnPopupHide(localjL4);
    bvO localbvO4 = new bvO();
    localbvO4.hg("wakfu.webShop:search4(session)");
    localaHd4.setOnSelectionChange(localbvO4);
    localdRq12.bb(localaHd4);
    localaHd4.brn();
    String str8 = "guildImprovementButtonPopup";
    anG localanG4 = new anG();
    localanG4.aJ();
    localanG4.setElementMap(localcpa);
    if ((localcpa != null) && (str8 != null))
      localcpa.a(str8, localanG4);
    localanG4.setAlign(aFG.ech);
    localanG4.setHotSpotPosition(aFG.ecn);
    localaHd4.bb(localanG4);
    localanG4.brn();
    dRq localdRq14 = dRq.checkOut();
    localdRq14.setElementMap(localcpa);
    localdRq14.setPrefSize(new Or(10, 0));
    localdRq14.setStyle("popup");
    localanG4.bb(localdRq14);
    localdRq14.brn();
    cWk localcWk7 = new cWk();
    localcWk7.aJ();
    localcWk7.setElementMap(localcpa);
    localcWk7.setStyle("white");
    localcWk7.setEnableShrinking(false);
    String str9 = "%webShop.search3%";
    str9 = str9.replace("%webShop.search3%", cBQ.cxL().mL("webShop.search3"));
    localcWk7.setText(str9);
    localdRq14.bb(localcWk7);
    localcWk7.brn();
    cWk localcWk8 = localcWk7;
    Jg localJg8 = localcWk8.getAppearance();
    localJg8.setElementMap(localcpa);
    ((cwJ)localJg8).setAlignment(aFG.eck);
    localcWk7.bb(localJg8);
    localJg8.brn();
    localJg8.rV();
    localcWk7.rV();
    localdRq14.rV();
    localanG4.rV();
    cwP localcwP8 = new cwP();
    localcwP8.aJ();
    localcwP8.setElementMap(localcpa);
    localcwP8.setSize(new Or(-2, -2));
    localcwP8.setAlign(ajb.dif);
    localaHd4.bb(localcwP8);
    localcwP8.brn();
    localcwP8.rV();
    localaHd4.rV();
    czv localczv4 = new czv();
    localczv4.aJ();
    localczv4.setElementMap(localcpa);
    localczv4.setNonBlocking(true);
    localczv4.setStyle("webShopLimited");
    localdRq12.bb(localczv4);
    localczv4.brn();
    cwP localcwP9 = new cwP();
    localcwP9.aJ();
    localcwP9.setElementMap(localcpa);
    localcwP9.setSize(new Or(-2, -2));
    localcwP9.setAlign(ajb.dhT);
    localcwP9.setXOffset(1);
    localcwP9.setYOffset(15);
    localczv4.bb(localcwP9);
    localcwP9.brn();
    localcwP9.rV();
    localczv4.rV();
    localdRq12.rV();
    localdRq2.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj m(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    biy localbiy = new biy();
    localbiy.aJ();
    localbiy.setElementMap(localcpa);
    localbiy.setStyle("close");
    localbiy.setExpandable(false);
    csA localcsA = new csA();
    localcsA.hg("unloadDialog");
    localbiy.setOnClick(localcsA);
    parambdj.bb(localbiy);
    localbiy.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(-2, -2));
    localcwP.setAlign(ajb.dhV);
    localcwP.setXOffset(-18);
    localcwP.setYOffset(-12);
    localbiy.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localbiy.rV();
    return localbiy;
  }

  public bdj n(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(-2, -2));
    localcwP.setAlign(ajb.dia);
    localcwP.setResizeOnce(true);
    parambdj.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    return localcwP;
  }
}