import java.awt.Insets;
import java.util.Stack;

public class bjl
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setStyle("popup");
    localdRq1.setPrefSize(new Or(200, 50));
    localdRq1.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setResizeOnce(true);
    localdRq1.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    aId localaId = aId.checkOut();
    localaId.setAlign(aFG.ech);
    localaId.setHorizontal(false);
    localdRq1.bb(localaId);
    localaId.brn();
    localaId.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    bTm localbTm = new bTm();
    localbTm.aJ();
    localdRq2.bb(localbTm);
    localbTm.brn();
    localbTm.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("BigTitle");
    localcaF1.setMinWidth(170);
    localcaF1.setMaxWidth(170);
    localdRq2.bb(localcaF1);
    localcaF1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("text");
    localNK1.setName("selectedNation");
    localNK1.setField("name");
    localcaF1.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    caF localcaF2 = localcaF1;
    Jg localJg1 = localcaF2.getAppearance();
    localJg1.setElementMap(localcpa);
    ((cwJ)localJg1).setAlignment(aFG.ecj);
    localcaF1.bb(localJg1);
    localJg1.brn();
    localJg1.rV();
    cba localcba1 = cba.checkOut();
    localcba1.setElementMap(localcpa);
    localcba1.setData(cFu.izV);
    localcaF1.bb(localcba1);
    localcba1.brn();
    localcba1.rV();
    localcaF1.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq2.bb(localdRq3);
    localdRq3.brn();
    cba localcba2 = cba.checkOut();
    localcba2.setElementMap(localcpa);
    localcba2.setData(cFu.izU);
    localdRq3.bb(localcba2);
    localcba2.brn();
    localcba2.rV();
    biy localbiy1 = new biy();
    localbiy1.aJ();
    localbiy1.setElementMap(localcpa);
    localbiy1.setStyle("smallValid");
    csA localcsA1 = new csA();
    localcsA1.hg("wakfu.nationChoice:validNationSelection");
    localbiy1.setOnClick(localcsA1);
    localdRq3.bb(localbiy1);
    localbiy1.brn();
    localbiy1.rV();
    biy localbiy2 = new biy();
    localbiy2.aJ();
    localbiy2.setElementMap(localcpa);
    localbiy2.setStyle("smallCancel");
    csA localcsA2 = new csA();
    localcsA2.hg("wakfu.nationChoice:cancelNationSelection");
    localbiy2.setOnClick(localcsA2);
    localdRq3.bb(localbiy2);
    localbiy2.brn();
    biy localbiy3 = localbiy2;
    Jg localJg2 = localbiy3.getAppearance();
    localJg2.setElementMap(localcpa);
    localbiy2.bb(localJg2);
    localJg2.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 5, 0, 0));
    localJg2.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg2.rV();
    localbiy2.rV();
    localdRq3.rV();
    localdRq2.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setExpandable(false);
    localdRq4.setStyle("lineSeparator");
    localdRq4.setPrefSize(new Or(0, 7));
    localdRq1.bb(localdRq4);
    localdRq4.brn();
    dRq localdRq5 = localdRq4;
    Jg localJg3 = localdRq5.getAppearance();
    localJg3.setElementMap(localcpa);
    localdRq4.bb(localJg3);
    localJg3.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(5, 0, 2, 0));
    localJg3.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg3.rV();
    localdRq4.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("white");
    localcWk1.setMinWidth(150);
    localcWk1.setMaxWidth(150);
    localdRq1.bb(localcWk1);
    localcWk1.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setAttribute("text");
    localNK2.setName("selectedNation");
    localNK2.setField("description");
    localcWk1.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    cWk localcWk2 = localcWk1;
    Jg localJg4 = localcWk2.getAppearance();
    localJg4.setElementMap(localcpa);
    ((cwJ)localJg4).setAlignment(aFG.eck);
    localcWk1.bb(localJg4);
    localJg4.brn();
    localJg4.rV();
    localcWk1.rV();
    localdRq1.rV();
    return localdRq1;
  }
}