import java.awt.Insets;
import java.util.Stack;

public class dii
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    String str1 = "characterSheetAptitudesWindow";
    bpn localbpn = new bpn();
    localbpn.aJ();
    localbpn.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localbpn);
    localbpn.brn();
    czO localczO1 = new czO();
    localczO1.aJ();
    localczO1.setAdaptToContentSize(true);
    localbpn.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localbpn.bb(localdRq1);
    localdRq1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    localdRq1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setStyle("windowNew");
    localbpn.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(10, 5, 12, 5));
    localJg1.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    localJg1.rV();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localdRq2.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localaId1.setAlign(aFG.ech);
    localdRq2.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dqa localdqa1 = new dqa();
    localdqa1.aJ();
    localdqa1.setElementMap(localcpa);
    localdqa1.setExpandable(false);
    localdRq2.bb(localdqa1);
    localdqa1.brn();
    dqa localdqa2 = localdqa1;
    Jg localJg2 = localdqa2.getAppearance();
    localJg2.setElementMap(localcpa);
    localdqa1.bb(localJg2);
    localJg2.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 10, 0, 10));
    localJg2.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg2.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setStyle("titleBar");
    localdqa1.bb(localdRq4);
    localdRq4.brn();
    dRq localdRq5 = localdRq4;
    Jg localJg3 = localdRq5.getAppearance();
    localJg3.setElementMap(localcpa);
    localdRq4.bb(localJg3);
    localJg3.brn();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(2, 20, 3, 20));
    localJg3.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    localJg3.rV();
    aId localaId2 = aId.checkOut();
    localaId2.setAlign(aFG.eck);
    localdRq4.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    dRq localdRq6 = localdRq4;
    Jg localJg4 = localdRq6.getAppearance();
    localJg4.setElementMap(localcpa);
    localdRq4.bb(localJg4);
    localJg4.brn();
    cuR localcuR3 = new cuR();
    localcuR3.aJ();
    localcuR3.setElementMap(localcpa);
    localcuR3.setInsets(new Insets(0, 10, 0, 20));
    localJg4.bb(localcuR3);
    localcuR3.brn();
    localcuR3.rV();
    localJg4.rV();
    czO localczO2 = new czO();
    localczO2.aJ();
    localczO2.setAdaptToContentSize(true);
    localdRq4.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localdRq7.setExpandable(true);
    localdRq4.bb(localdRq7);
    localdRq7.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setSize(new Or(100.0F, 100.0F));
    localdRq7.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    aId localaId3 = aId.checkOut();
    localaId3.setAlign(aFG.ecj);
    localdRq7.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("StyledBold16White");
    String str2 = "%abilities%";
    str2 = str2.replace("%abilities%", cBQ.cxL().mL("abilities"));
    localcaF1.setText(str2);
    localcaF1.setNonBlocking(true);
    localcaF1.setExpandable(false);
    localdRq7.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg5 = localcaF2.getAppearance();
    localJg5.setElementMap(localcpa);
    ((cwJ)localJg5).setAlign(aFG.ecj);
    localcaF1.bb(localJg5);
    localJg5.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 0, 0, 20));
    localJg5.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg5.rV();
    localcaF1.rV();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setStyle("questionMark");
    localczv.setExpandable(false);
    cCu localcCu1 = new cCu();
    localcCu1.hg("popup(descCaracRestatPopup)");
    localczv.setOnPopupDisplay(localcCu1);
    jL localjL1 = new jL();
    localjL1.hg("closePopup");
    localczv.setOnPopupHide(localjL1);
    localdRq7.bb(localczv);
    localczv.brn();
    String str3 = "descCaracRestatPopup";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa);
    if ((localcpa != null) && (str3 != null))
      localcpa.a(str3, localanG);
    localanG.setAlign(aFG.ecn);
    localanG.setHotSpotPosition(aFG.ech);
    localczv.bb(localanG);
    localanG.brn();
    dRq localdRq8 = dRq.checkOut();
    localdRq8.setElementMap(localcpa);
    localdRq8.setPrefSize(new Or(10, 0));
    localdRq8.setStyle("popup");
    localanG.bb(localdRq8);
    localdRq8.brn();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("white");
    String str4 = "%tooltip.Restat%";
    str4 = str4.replace("%tooltip.Restat%", cBQ.cxL().mL("tooltip.Restat"));
    localcWk1.setText(str4);
    localcWk1.setMinWidth(1);
    localcWk1.setMaxWidth(250);
    localdRq8.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg6 = localcWk2.getAppearance();
    localJg6.setElementMap(localcpa);
    ((cwJ)localJg6).setAlignment(aFG.ecj);
    localcWk1.bb(localJg6);
    localJg6.brn();
    localJg6.rV();
    localcWk1.rV();
    localdRq8.rV();
    localanG.rV();
    localczv.rV();
    localdRq7.rV();
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa);
    localdRq9.setStyle("flat");
    localdRq9.setPrefSize(new Or(0, 0));
    localdRq4.bb(localdRq9);
    localdRq9.brn();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setSize(new Or(-2, -2));
    localcwP4.setAlign(ajb.dia);
    localcwP4.setXOffset(0);
    localdRq9.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    dRq localdRq10 = localdRq9;
    Jg localJg7 = localdRq10.getAppearance();
    localJg7.setElementMap(localcpa);
    localdRq9.bb(localJg7);
    localJg7.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(3, 0, 5, 3));
    localJg7.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg7.rV();
    dRq localdRq11 = dRq.checkOut();
    localdRq11.setElementMap(localcpa);
    localdRq11.setExpandable(false);
    localdRq9.bb(localdRq11);
    localdRq11.brn();
    String str5 = "commonAptitudeButtonContainer";
    dRq localdRq12 = dRq.checkOut();
    localdRq12.setElementMap(localcpa);
    if ((localcpa != null) && (str5 != null))
      localcpa.a(str5, localdRq12);
    localdRq12.setVisible(false);
    localdRq11.bb(localdRq12);
    localdRq12.brn();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa);
    localdpm1.setAlign(aFG.ech);
    localdRq12.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    String str6 = "cancelCommonAptitudePoints";
    biy localbiy1 = new biy();
    localbiy1.aJ();
    localbiy1.setElementMap(localcpa);
    if ((localcpa != null) && (str6 != null))
      localcpa.a(str6, localbiy1);
    localbiy1.setStyle("smallCancel");
    csA localcsA1 = new csA();
    localcsA1.hg("wakfu.characterSheet:cancelCommonAptitudePoints(commonAptitudeButtonContainer,validateCommonAptitudePoints)");
    localbiy1.setOnClick(localcsA1);
    cCu localcCu2 = new cCu();
    localcCu2.hg("popup(cancelAptitudePointsPopup,cancelCommonAptitudePoints)");
    localbiy1.setOnPopupDisplay(localcCu2);
    jL localjL2 = new jL();
    localjL2.hg("closePopup");
    localbiy1.setOnPopupHide(localjL2);
    localdRq12.bb(localbiy1);
    localbiy1.brn();
    biy localbiy2 = localbiy1;
    Jg localJg8 = localbiy2.getAppearance();
    localJg8.setElementMap(localcpa);
    localbiy1.bb(localJg8);
    localJg8.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(0, 0, 0, 5));
    localJg8.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg8.rV();
    localbiy1.rV();
    String str7 = "validateCommonAptitudePoints";
    biy localbiy3 = new biy();
    localbiy3.aJ();
    localbiy3.setElementMap(localcpa);
    if ((localcpa != null) && (str7 != null))
      localcpa.a(str7, localbiy3);
    localbiy3.setStyle("smallValid");
    csA localcsA2 = new csA();
    localcsA2.hg("wakfu.characterSheet:validateCommonAptitudePoints(commonAptitudeButtonContainer,validateCommonAptitudePoints)");
    localbiy3.setOnClick(localcsA2);
    cCu localcCu3 = new cCu();
    localcCu3.hg("popup(validateAptitudePointsPopup,validateCommonAptitudePoints)");
    localbiy3.setOnPopupDisplay(localcCu3);
    jL localjL3 = new jL();
    localjL3.hg("closePopup");
    localbiy3.setOnPopupHide(localjL3);
    localdRq12.bb(localbiy3);
    localbiy3.brn();
    localbiy3.rV();
    localdRq12.rV();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setStyle("bold");
    localcaF3.setNonBlocking(true);
    String str8 = "%available.aptitude.points%";
    str8 = str8.replace("%available.aptitude.points%", cBQ.cxL().mL("available.aptitude.points"));
    localcaF3.setText(str8);
    localdRq11.bb(localcaF3);
    localcaF3.brn();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa);
    localdpm2.setAlign(aFG.eck);
    localcaF3.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    caF localcaF4 = localcaF3;
    Jg localJg9 = localcaF4.getAppearance();
    localJg9.setElementMap(localcpa);
    localcaF3.bb(localJg9);
    localJg9.brn();
    bmv localbmv5 = bmv.checkOut();
    localbmv5.setElementMap(localcpa);
    localbmv5.setInsets(new Insets(0, 3, 0, 3));
    localJg9.bb(localbmv5);
    localbmv5.brn();
    localbmv5.rV();
    localJg9.rV();
    localcaF3.rV();
    dRq localdRq13 = dRq.checkOut();
    localdRq13.setElementMap(localcpa);
    localdRq13.setStyle("darkBackgrounded");
    localdRq13.setExpandable(false);
    localdRq13.setPrefSize(new Or(35, 0));
    localdRq11.bb(localdRq13);
    localdRq13.brn();
    dpm localdpm3 = new dpm();
    localdpm3.aJ();
    localdpm3.setElementMap(localcpa);
    localdpm3.setAlign(aFG.eck);
    localdRq13.bb(localdpm3);
    localdpm3.brn();
    localdpm3.rV();
    caF localcaF5 = new caF();
    localcaF5.aJ();
    localcaF5.setElementMap(localcpa);
    localcaF5.setStyle("whiteTitle");
    localcaF5.setNonBlocking(true);
    localdRq13.bb(localcaF5);
    localcaF5.brn();
    caF localcaF6 = localcaF5;
    Jg localJg10 = localcaF6.getAppearance();
    localJg10.setElementMap(localcpa);
    ((cwJ)localJg10).setAlign(aFG.eck);
    localcaF5.bb(localJg10);
    localJg10.brn();
    localJg10.rV();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setName("localPlayer");
    localNK1.setAttribute("text");
    localNK1.setField("availableCommonPoints");
    localcaF5.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    localcaF5.rV();
    localdRq13.rV();
    localdRq11.rV();
    localdRq9.rV();
    localdRq4.rV();
    localdqa1.rV();
    dRq localdRq14 = dRq.checkOut();
    localdRq14.setElementMap(localcpa);
    localdRq2.bb(localdRq14);
    localdRq14.brn();
    dRq localdRq15 = localdRq14;
    Jg localJg11 = localdRq15.getAppearance();
    localJg11.setElementMap(localcpa);
    localdRq14.bb(localJg11);
    localJg11.brn();
    bmv localbmv6 = bmv.checkOut();
    localbmv6.setElementMap(localcpa);
    localbmv6.setInsets(new Insets(0, 12, 0, 12));
    localJg11.bb(localbmv6);
    localbmv6.brn();
    localbmv6.rV();
    localJg11.rV();
    String str9 = "windowContentContainer";
    dRq localdRq16 = dRq.checkOut();
    localdRq16.setElementMap(localcpa);
    if ((localcpa != null) && (str9 != null))
      localcpa.a(str9, localdRq16);
    localdRq16.setPrefSize(new Or(450, 0));
    localdRq14.bb(localdRq16);
    localdRq16.brn();
    aId localaId4 = aId.checkOut();
    localaId4.setHorizontal(false);
    localdRq16.bb(localaId4);
    localaId4.brn();
    localaId4.rV();
    dRq localdRq17 = localdRq16;
    Jg localJg12 = localdRq17.getAppearance();
    localJg12.setElementMap(localcpa);
    localdRq16.bb(localJg12);
    localJg12.brn();
    cuR localcuR4 = new cuR();
    localcuR4.aJ();
    localcuR4.setElementMap(localcpa);
    localcuR4.setInsets(new Insets(0, 0, 0, 0));
    localJg12.bb(localcuR4);
    localcuR4.brn();
    localcuR4.rV();
    localJg12.rV();
    aId localaId5 = aId.checkOut();
    localaId5.setAlign(aFG.ech);
    localaId5.setHorizontal(false);
    localdRq16.bb(localaId5);
    localaId5.brn();
    localaId5.rV();
    ccG localccG1 = new ccG();
    localccG1.aJ();
    localccG1.setElementMap(localcpa);
    localccG1.setCellSize(new Or(50.0F, 37));
    localccG1.setHorizontal(false);
    localccG1.setExpandable(false);
    localccG1.setAutoIdealSize(true);
    localccG1.setIdealSizeMinColumns(2);
    localccG1.setIdealSizeMaxColumns(2);
    anx localanx = new anx();
    localanx.hg("wakfu.characterSheet:overAptitude");
    localccG1.setOnItemOver(localanx);
    cCu localcCu4 = new cCu();
    localcCu4.hg("popup(aptitudePopup,characterSheetAptitudesWindow)");
    localccG1.setOnPopupDisplay(localcCu4);
    jL localjL4 = new jL();
    localjL4.hg("closePopup");
    localccG1.setOnPopupHide(localjL4);
    localdRq16.bb(localccG1);
    localccG1.brn();
    ccG localccG2 = localccG1;
    Jg localJg13 = localccG2.getAppearance();
    localJg13.setElementMap(localcpa);
    localccG1.bb(localJg13);
    localJg13.brn();
    bmv localbmv7 = bmv.checkOut();
    localbmv7.setElementMap(localcpa);
    localbmv7.setInsets(new Insets(0, 0, 5, 0));
    localJg13.bb(localbmv7);
    localbmv7.brn();
    localbmv7.rV();
    localJg13.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("localPlayer");
    localNK2.setAttribute("content");
    localNK2.setField("commonAptitudes");
    localccG1.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    eR localeR = new eR();
    localeR.aJ();
    localeR.setElementMap(localcpa);
    localccG1.bb(localeR);
    localeR.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localeR.bb(localanQ);
    localanQ.brn();
    bxx localbxx = new bxx();
    localbxx.aJ();
    localbxx.setElementMap(localcpa);
    localanQ.bb(localbxx);
    localbxx.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localbxx.bb(localanE);
    localanE.brn();
    localanE.rV();
    localbxx.rV();
    localanQ.rV();
    dRq localdRq18 = dRq.checkOut();
    localdRq18.setElementMap(localcpa);
    localeR.bb(localdRq18);
    localdRq18.brn();
    String str10 = "aptitude";
    avo localavo = new avo();
    localavo.aJ();
    localavo.setElementMap(localcpa);
    if ((localcpa != null) && (str10 != null))
      localcpa.a(str10, localavo);
    localdRq18.bb(localavo);
    localavo.brn();
    a(localavo);
    localavo.rV();
    b(localdRq18);
    d(localdRq18);
    e(localdRq18);
    f(localdRq18);
    g(localdRq18);
    localdRq18.rV();
    localeR.rV();
    localccG1.rV();
    h(localdRq16);
    i(localdRq16);
    localdRq16.rV();
    localdRq14.rV();
    localdRq2.rV();
    j(localbpn);
    k(localbpn);
    l(localbpn);
    m(localbpn);
    n(localbpn);
    o(localbpn);
    localbpn.rV();
    return localbpn;
  }

  public bdj a(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    aaE localaaE = new aaE();
    localaaE.aJ();
    localaaE.setElementMap(localcpa);
    localaaE.setAttribute("value");
    parambdj.bb(localaaE);
    localaaE.brn();
    localaaE.rV();
    return localaaE;
  }

  public bdj b(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dOc localdOc = (dOc)parambdj;
    Jg localJg = localdOc.getAppearance();
    localJg.setElementMap(localcpa);
    parambdj.bb(localJg);
    localJg.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(0, 0, 0, 5));
    localJg.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg.rV();
    return localJg;
  }

  public bdj d(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    czO localczO = new czO();
    localczO.aJ();
    parambdj.bb(localczO);
    localczO.brn();
    localczO.rV();
    return null;
  }

  public bdj e(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setStyle("darkBackgrounded");
    localdRq1.setNonBlocking(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    dRq localdRq2 = localdRq1;
    Jg localJg = localdRq2.getAppearance();
    localJg.setElementMap(localcpa);
    localJg.setModulationColor(new bNa(1.0F, 1.0F, 1.0F, 0.7F));
    localdRq1.bb(localJg);
    localJg.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(0, 5, 0, 0));
    localJg.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg.rV();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setAlign(ajb.dhZ);
    localcwP.setSize(new Or(100.0F, 25));
    localdRq1.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj f(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq = dRq.checkOut();
    localdRq.setElementMap(localcpa);
    localdRq.setStyle("white2");
    parambdj.bb(localdRq);
    localdRq.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setAlign(ajb.dhY);
    localdRq.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    String str = "aptitudeIcon";
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    if ((localcpa != null) && (str != null))
      localcpa.a(str, localczv1);
    localczv1.setNonBlocking(true);
    localczv1.setExpandable(false);
    localczv1.setDisplaySize(new Or(29, 29));
    localdRq.bb(localczv1);
    localczv1.brn();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.eck);
    localczv1.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    czv localczv2 = localczv1;
    Jg localJg = localczv2.getAppearance();
    localJg.setElementMap(localcpa);
    localczv1.bb(localJg);
    localJg.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(4, 4, 4, 4));
    localJg.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg.rV();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv1.bb(localaAR);
    localaAR.brn();
    aaE localaaE = new aaE();
    localaaE.aJ();
    localaaE.setElementMap(localcpa);
    localaaE.setAttribute("texture");
    localaaE.setField("iconUrl");
    localaAR.bb(localaaE);
    localaaE.brn();
    localaaE.rV();
    localaAR.rV();
    localczv1.rV();
    localdRq.rV();
    return localdRq;
  }

  public bdj g(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setAlign(ajb.dhY);
    localcwP1.setSize(new Or(100.0F, -2));
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    dRq localdRq2 = localdRq1;
    Jg localJg1 = localdRq2.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq1.bb(localJg1);
    localJg1.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(0, 40, 0, 3));
    localJg1.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg1.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("white");
    localcaF1.setNonBlocking(true);
    localdRq1.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg2 = localcaF2.getAppearance();
    localJg2.setElementMap(localcpa);
    ((cwJ)localJg2).setAlignment(aFG.ecj);
    localcaF1.bb(localJg2);
    localJg2.brn();
    localJg2.rV();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("text");
    localaaE1.setField("name");
    localcaF1.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    localcaF1.rV();
    biy localbiy1 = new biy();
    localbiy1.aJ();
    localbiy1.setElementMap(localcpa);
    localbiy1.setStyle("remove");
    localbiy1.setExpandable(false);
    aMB localaMB1 = new aMB();
    localaMB1.hg("wakfu.characterSheet:decreaseAptitude(aptitude,commonAptitudeButtonContainer,validateCommonAptitudePoints)");
    localbiy1.setOnMousePress(localaMB1);
    localdRq1.bb(localbiy1);
    localbiy1.brn();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa);
    localdpm1.setAlign(aFG.eck);
    localbiy1.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("enabled");
    localaaE2.setField("canBeDecreased");
    localbiy1.bb(localaaE2);
    localaaE2.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localaaE2.bb(localanQ1);
    localanQ1.brn();
    bJJ localbJJ1 = new bJJ();
    localbJJ1.aJ();
    localbJJ1.setElementMap(localcpa);
    localanQ1.bb(localbJJ1);
    localbJJ1.brn();
    cOk localcOk1 = new cOk();
    localcOk1.aJ();
    localcOk1.setElementMap(localcpa);
    localbJJ1.bb(localcOk1);
    localcOk1.brn();
    localcOk1.rV();
    bqW localbqW1 = new bqW();
    localbqW1.aJ();
    localbqW1.setElementMap(localcpa);
    localbJJ1.bb(localbqW1);
    localbqW1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setName("isInFight");
    localNK1.setAttribute("comparedValue");
    localbqW1.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    localbqW1.rV();
    localbJJ1.rV();
    localanQ1.rV();
    localaaE2.rV();
    biy localbiy2 = localbiy1;
    Jg localJg3 = localbiy2.getAppearance();
    localJg3.setElementMap(localcpa);
    localbiy1.bb(localJg3);
    localJg3.brn();
    aaE localaaE3 = new aaE();
    localaaE3.aJ();
    localaaE3.setElementMap(localcpa);
    localaaE3.setAttribute("modulationColor");
    localaaE3.setField("canBeDecreased");
    localJg3.bb(localaaE3);
    localaaE3.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localanQ2.setValue("1,1,1");
    localanQ2.setElseValue("1,1,1,0.5");
    localaaE3.bb(localanQ2);
    localanQ2.brn();
    bJJ localbJJ2 = new bJJ();
    localbJJ2.aJ();
    localbJJ2.setElementMap(localcpa);
    localanQ2.bb(localbJJ2);
    localbJJ2.brn();
    cOk localcOk2 = new cOk();
    localcOk2.aJ();
    localcOk2.setElementMap(localcpa);
    localbJJ2.bb(localcOk2);
    localcOk2.brn();
    localcOk2.rV();
    bqW localbqW2 = new bqW();
    localbqW2.aJ();
    localbqW2.setElementMap(localcpa);
    localbJJ2.bb(localbqW2);
    localbqW2.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("isInFight");
    localNK2.setAttribute("comparedValue");
    localbqW2.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localbqW2.rV();
    localbJJ2.rV();
    localanQ2.rV();
    localaaE3.rV();
    localJg3.rV();
    localbiy1.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("defaultBold14");
    localcWk1.setPrefSize(new Or(15, 0));
    localcWk1.setExpandable(false);
    localcWk1.setMultiline(false);
    localcWk1.setNonBlocking(true);
    localdRq1.bb(localcWk1);
    localcWk1.brn();
    aaE localaaE4 = new aaE();
    localaaE4.aJ();
    localaaE4.setElementMap(localcpa);
    localaaE4.setAttribute("text");
    localaaE4.setField("levelWithColor");
    localcWk1.bb(localaaE4);
    localaaE4.brn();
    localaaE4.rV();
    cWk localcWk2 = localcWk1;
    Jg localJg4 = localcWk2.getAppearance();
    localJg4.setElementMap(localcpa);
    ((cwJ)localJg4).setAlign(aFG.eck);
    localcWk1.bb(localJg4);
    localJg4.brn();
    cAf localcAf = cAf.checkOut();
    localcAf.setElementMap(localcpa);
    localcAf.setName("text");
    localcAf.setColor(new bNa(0.55F, 0.85F, 88.0F, 1.0F));
    localJg4.bb(localcAf);
    localcAf.brn();
    localcAf.rV();
    localJg4.rV();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.dia);
    localcwP2.setXOffset(-20);
    localcWk1.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    localcWk1.rV();
    biy localbiy3 = new biy();
    localbiy3.aJ();
    localbiy3.setElementMap(localcpa);
    localbiy3.setStyle("add");
    localbiy3.setExpandable(false);
    aMB localaMB2 = new aMB();
    localaMB2.hg("wakfu.characterSheet:improveAptitude(aptitude,commonAptitudeButtonContainer,validateCommonAptitudePoints)");
    localbiy3.setOnMousePress(localaMB2);
    localdRq1.bb(localbiy3);
    localbiy3.brn();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa);
    localdpm2.setAlign(aFG.eck);
    localbiy3.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    aaE localaaE5 = new aaE();
    localaaE5.aJ();
    localaaE5.setElementMap(localcpa);
    localaaE5.setAttribute("enabled");
    localaaE5.setField("canBeIncreased");
    localbiy3.bb(localaaE5);
    localaaE5.brn();
    anQ localanQ3 = new anQ();
    localanQ3.aJ();
    localanQ3.setElementMap(localcpa);
    localaaE5.bb(localanQ3);
    localanQ3.brn();
    bJJ localbJJ3 = new bJJ();
    localbJJ3.aJ();
    localbJJ3.setElementMap(localcpa);
    localanQ3.bb(localbJJ3);
    localbJJ3.brn();
    cOk localcOk3 = new cOk();
    localcOk3.aJ();
    localcOk3.setElementMap(localcpa);
    localbJJ3.bb(localcOk3);
    localcOk3.brn();
    localcOk3.rV();
    bqW localbqW3 = new bqW();
    localbqW3.aJ();
    localbqW3.setElementMap(localcpa);
    localbJJ3.bb(localbqW3);
    localbqW3.brn();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setName("isInFight");
    localNK3.setAttribute("comparedValue");
    localbqW3.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    localbqW3.rV();
    localbJJ3.rV();
    localanQ3.rV();
    localaaE5.rV();
    biy localbiy4 = localbiy3;
    Jg localJg5 = localbiy4.getAppearance();
    localJg5.setElementMap(localcpa);
    localbiy3.bb(localJg5);
    localJg5.brn();
    aaE localaaE6 = new aaE();
    localaaE6.aJ();
    localaaE6.setElementMap(localcpa);
    localaaE6.setAttribute("modulationColor");
    localaaE6.setField("canBeIncreased");
    localJg5.bb(localaaE6);
    localaaE6.brn();
    anQ localanQ4 = new anQ();
    localanQ4.aJ();
    localanQ4.setElementMap(localcpa);
    localanQ4.setValue("1,1,1");
    localanQ4.setElseValue("1,1,1,0.5");
    localaaE6.bb(localanQ4);
    localanQ4.brn();
    bJJ localbJJ4 = new bJJ();
    localbJJ4.aJ();
    localbJJ4.setElementMap(localcpa);
    localanQ4.bb(localbJJ4);
    localbJJ4.brn();
    cOk localcOk4 = new cOk();
    localcOk4.aJ();
    localcOk4.setElementMap(localcpa);
    localbJJ4.bb(localcOk4);
    localcOk4.brn();
    localcOk4.rV();
    bqW localbqW4 = new bqW();
    localbqW4.aJ();
    localbqW4.setElementMap(localcpa);
    localbJJ4.bb(localbqW4);
    localbqW4.brn();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa);
    localNK4.setName("isInFight");
    localNK4.setAttribute("comparedValue");
    localbqW4.bb(localNK4);
    localNK4.brn();
    localNK4.rV();
    localbqW4.rV();
    localbJJ4.rV();
    localanQ4.rV();
    localaaE6.rV();
    localJg5.rV();
    localbiy3.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj h(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setName("localPlayer");
    localNK1.setAttribute("visible");
    localNK1.setField("breedAptitudes");
    localdRq1.bb(localNK1);
    localNK1.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localNK1.bb(localanQ);
    localanQ.brn();
    dFV localdFV = new dFV();
    localdFV.aJ();
    localdFV.setElementMap(localcpa);
    localdFV.setKey("size");
    localanQ.bb(localdFV);
    localdFV.brn();
    jA localjA = new jA();
    localjA.aJ();
    localjA.setElementMap(localcpa);
    localjA.setValue("0");
    localdFV.bb(localjA);
    localjA.brn();
    localjA.rV();
    localdFV.rV();
    localanQ.rV();
    localNK1.rV();
    czO localczO = new czO();
    localczO.aJ();
    localczO.setAdaptToContentSize(true);
    localdRq1.bb(localczO);
    localczO.brn();
    localczO.rV();
    String str1 = "breedAptitudeTitle";
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localdRq2);
    localdRq2.setStyle("titleBar");
    localdRq2.setExpandable(false);
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localdRq2.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 0, 0, 0));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    cuR localcuR = new cuR();
    localcuR.aJ();
    localcuR.setElementMap(localcpa);
    localcuR.setInsets(new Insets(0, 10, 3, 20));
    localJg1.bb(localcuR);
    localcuR.brn();
    localcuR.rV();
    localJg1.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("StyledBold16White");
    String str2 = "%breed.aptitudes%";
    str2 = str2.replace("%breed.aptitudes%", cBQ.cxL().mL("breed.aptitudes"));
    localcaF1.setText(str2);
    localcaF1.setNonBlocking(true);
    localcaF1.setExpandable(true);
    localdRq2.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg2 = localcaF2.getAppearance();
    localJg2.setElementMap(localcpa);
    ((cwJ)localJg2).setAlign(aFG.ecj);
    localcaF1.bb(localJg2);
    localJg2.brn();
    localJg2.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("localPlayer");
    localNK2.setAttribute("text");
    localNK2.setField("breedAptitudesTitle");
    localcaF1.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localcaF1.rV();
    localdRq2.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setStyle("flat");
    localdRq4.setPrefSize(new Or(0, 0));
    localdRq1.bb(localdRq4);
    localdRq4.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setSize(new Or(-2, -2));
    localcwP2.setAlign(ajb.dia);
    localcwP2.setXOffset(0);
    localdRq4.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    dRq localdRq5 = localdRq4;
    Jg localJg3 = localdRq5.getAppearance();
    localJg3.setElementMap(localcpa);
    localdRq4.bb(localJg3);
    localJg3.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(3, 0, 5, 20));
    localJg3.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg3.rV();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq6.setExpandable(false);
    localdRq4.bb(localdRq6);
    localdRq6.brn();
    String str3 = "spellAptitudeButtonContainer";
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    if ((localcpa != null) && (str3 != null))
      localcpa.a(str3, localdRq7);
    localdRq7.setVisible(false);
    localdRq6.bb(localdRq7);
    localdRq7.brn();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa);
    localdpm1.setAlign(aFG.ech);
    localdRq7.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    String str4 = "cancelSpellAptitudePoints";
    biy localbiy1 = new biy();
    localbiy1.aJ();
    localbiy1.setElementMap(localcpa);
    if ((localcpa != null) && (str4 != null))
      localcpa.a(str4, localbiy1);
    localbiy1.setStyle("smallCancel");
    csA localcsA1 = new csA();
    localcsA1.hg("wakfu.characterSheet:cancelSpellAptitudePoints(spellAptitudeButtonContainer,validateSpellAptitudePoints)");
    localbiy1.setOnClick(localcsA1);
    cCu localcCu1 = new cCu();
    localcCu1.hg("popup(cancelAptitudePointsPopup,cancelSpellAptitudePoints)");
    localbiy1.setOnPopupDisplay(localcCu1);
    jL localjL1 = new jL();
    localjL1.hg("closePopup");
    localbiy1.setOnPopupHide(localjL1);
    localdRq7.bb(localbiy1);
    localbiy1.brn();
    biy localbiy2 = localbiy1;
    Jg localJg4 = localbiy2.getAppearance();
    localJg4.setElementMap(localcpa);
    localbiy1.bb(localJg4);
    localJg4.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 0, 0, 5));
    localJg4.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg4.rV();
    localbiy1.rV();
    String str5 = "validateSpellAptitudePoints";
    biy localbiy3 = new biy();
    localbiy3.aJ();
    localbiy3.setElementMap(localcpa);
    if ((localcpa != null) && (str5 != null))
      localcpa.a(str5, localbiy3);
    localbiy3.setStyle("smallValid");
    csA localcsA2 = new csA();
    localcsA2.hg("wakfu.characterSheet:validateSpellAptitudePoints(spellAptitudeButtonContainer,validateSpellAptitudePoints)");
    localbiy3.setOnClick(localcsA2);
    cCu localcCu2 = new cCu();
    localcCu2.hg("popup(validateAptitudePointsPopup,validateSpellAptitudePoints)");
    localbiy3.setOnPopupDisplay(localcCu2);
    jL localjL2 = new jL();
    localjL2.hg("closePopup");
    localbiy3.setOnPopupHide(localjL2);
    localdRq7.bb(localbiy3);
    localbiy3.brn();
    localbiy3.rV();
    localdRq7.rV();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setStyle("bold");
    localcaF3.setNonBlocking(true);
    String str6 = "%available.aptitude.points%";
    str6 = str6.replace("%available.aptitude.points%", cBQ.cxL().mL("available.aptitude.points"));
    localcaF3.setText(str6);
    localdRq6.bb(localcaF3);
    localcaF3.brn();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa);
    localdpm2.setAlign(aFG.eck);
    localcaF3.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    caF localcaF4 = localcaF3;
    Jg localJg5 = localcaF4.getAppearance();
    localJg5.setElementMap(localcpa);
    localcaF3.bb(localJg5);
    localJg5.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(0, 3, 0, 3));
    localJg5.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg5.rV();
    localcaF3.rV();
    dRq localdRq8 = dRq.checkOut();
    localdRq8.setElementMap(localcpa);
    localdRq8.setStyle("darkBackgrounded");
    localdRq8.setExpandable(false);
    localdRq8.setPrefSize(new Or(35, 0));
    localdRq6.bb(localdRq8);
    localdRq8.brn();
    dpm localdpm3 = new dpm();
    localdpm3.aJ();
    localdpm3.setElementMap(localcpa);
    localdpm3.setAlign(aFG.eck);
    localdRq8.bb(localdpm3);
    localdpm3.brn();
    localdpm3.rV();
    caF localcaF5 = new caF();
    localcaF5.aJ();
    localcaF5.setElementMap(localcpa);
    localcaF5.setStyle("whiteTitle");
    localcaF5.setNonBlocking(true);
    localdRq8.bb(localcaF5);
    localcaF5.brn();
    caF localcaF6 = localcaF5;
    Jg localJg6 = localcaF6.getAppearance();
    localJg6.setElementMap(localcpa);
    ((cwJ)localJg6).setAlign(aFG.eck);
    localcaF5.bb(localJg6);
    localJg6.brn();
    localJg6.rV();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setName("localPlayer");
    localNK3.setAttribute("text");
    localNK3.setField("availableAptitudePoints");
    localcaF5.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    localcaF5.rV();
    localdRq8.rV();
    localdRq6.rV();
    localdRq4.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj i(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    ccG localccG1 = new ccG();
    localccG1.aJ();
    localccG1.setElementMap(localcpa);
    localccG1.setCellSize(new Or(50.0F, 37));
    localccG1.setHorizontal(false);
    localccG1.setExpandable(false);
    localccG1.setAutoIdealSize(true);
    localccG1.setIdealSizeMinColumns(2);
    localccG1.setIdealSizeMaxColumns(2);
    anx localanx = new anx();
    localanx.hg("wakfu.characterSheet:overAptitude");
    localccG1.setOnItemOver(localanx);
    cCu localcCu = new cCu();
    localcCu.hg("popup(aptitudePopup,breedAptitudeTitle)");
    localccG1.setOnPopupDisplay(localcCu);
    jL localjL = new jL();
    localjL.hg("closePopup");
    localccG1.setOnPopupHide(localjL);
    parambdj.bb(localccG1);
    localccG1.brn();
    ccG localccG2 = localccG1;
    Jg localJg1 = localccG2.getAppearance();
    localJg1.setElementMap(localcpa);
    localccG1.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 0, 5, 0));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setName("localPlayer");
    localNK1.setAttribute("content");
    localNK1.setField("breedAptitudes");
    localccG1.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    eR localeR = new eR();
    localeR.aJ();
    localeR.setElementMap(localcpa);
    localccG1.bb(localeR);
    localeR.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localeR.bb(localanQ1);
    localanQ1.brn();
    bxx localbxx = new bxx();
    localbxx.aJ();
    localbxx.setElementMap(localcpa);
    localanQ1.bb(localbxx);
    localbxx.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localbxx.bb(localanE);
    localanE.brn();
    localanE.rV();
    localbxx.rV();
    localanQ1.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localeR.bb(localdRq1);
    localdRq1.brn();
    String str1 = "aptitude";
    avo localavo = new avo();
    localavo.aJ();
    localavo.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localavo);
    localdRq1.bb(localavo);
    localavo.brn();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("value");
    localavo.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    localavo.rV();
    dRq localdRq2 = localdRq1;
    Jg localJg2 = localdRq2.getAppearance();
    localJg2.setElementMap(localcpa);
    localdRq1.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 0, 0, 5));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    czO localczO = new czO();
    localczO.aJ();
    localdRq1.bb(localczO);
    localczO.brn();
    localczO.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq3.setStyle("darkBackgrounded");
    localdRq3.setNonBlocking(false);
    csA localcsA = new csA();
    localcsA.hg("wakfu.characterSheet:selectAptitude(aptitude)");
    localdRq3.setOnClick(localcsA);
    localdRq1.bb(localdRq3);
    localdRq3.brn();
    dRq localdRq4 = localdRq3;
    Jg localJg3 = localdRq4.getAppearance();
    localJg3.setElementMap(localcpa);
    localJg3.setModulationColor(new bNa(1.0F, 1.0F, 1.0F, 0.7F));
    localdRq3.bb(localJg3);
    localJg3.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 5, 0, 0));
    localJg3.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg3.rV();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setAlign(ajb.dhZ);
    localcwP1.setSize(new Or(100.0F, 25));
    localdRq3.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    localdRq3.rV();
    dRq localdRq5 = dRq.checkOut();
    localdRq5.setElementMap(localcpa);
    localdRq5.setStyle("white2");
    localdRq1.bb(localdRq5);
    localdRq5.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.dhY);
    localdRq5.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    String str2 = "aptitudeIcon";
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localczv1);
    localczv1.setNonBlocking(true);
    localczv1.setExpandable(false);
    localczv1.setDisplaySize(new Or(29, 29));
    localdRq5.bb(localczv1);
    localczv1.brn();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa);
    localdpm1.setAlign(aFG.eck);
    localczv1.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    czv localczv2 = localczv1;
    Jg localJg4 = localczv2.getAppearance();
    localJg4.setElementMap(localcpa);
    localczv1.bb(localJg4);
    localJg4.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(4, 4, 4, 4));
    localJg4.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg4.rV();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv1.bb(localaAR);
    localaAR.brn();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("texture");
    localaaE2.setField("iconUrl");
    localaAR.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    localaAR.rV();
    localczv1.rV();
    localdRq5.rV();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq1.bb(localdRq6);
    localdRq6.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setAlign(ajb.dhY);
    localcwP3.setSize(new Or(100.0F, -2));
    localdRq6.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    dRq localdRq7 = localdRq6;
    Jg localJg5 = localdRq7.getAppearance();
    localJg5.setElementMap(localcpa);
    localdRq6.bb(localJg5);
    localJg5.brn();
    bmv localbmv5 = bmv.checkOut();
    localbmv5.setElementMap(localcpa);
    localbmv5.setInsets(new Insets(0, 40, 0, 3));
    localJg5.bb(localbmv5);
    localbmv5.brn();
    localbmv5.rV();
    localJg5.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("white");
    localcaF1.setNonBlocking(true);
    localcaF1.setMinWidth(1);
    localcaF1.setMaxWidth(1);
    localdRq6.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg6 = localcaF2.getAppearance();
    localJg6.setElementMap(localcpa);
    ((cwJ)localJg6).setAlignment(aFG.ecj);
    localcaF1.bb(localJg6);
    localJg6.brn();
    localJg6.rV();
    aaE localaaE3 = new aaE();
    localaaE3.aJ();
    localaaE3.setElementMap(localcpa);
    localaaE3.setAttribute("text");
    localaaE3.setField("name");
    localcaF1.bb(localaaE3);
    localaaE3.brn();
    localaaE3.rV();
    localcaF1.rV();
    biy localbiy1 = new biy();
    localbiy1.aJ();
    localbiy1.setElementMap(localcpa);
    localbiy1.setStyle("remove");
    localbiy1.setExpandable(false);
    aMB localaMB1 = new aMB();
    localaMB1.hg("wakfu.characterSheet:decreaseAptitude(aptitude,spellAptitudeButtonContainer,validateSpellAptitudePoints)");
    localbiy1.setOnMousePress(localaMB1);
    localdRq6.bb(localbiy1);
    localbiy1.brn();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa);
    localdpm2.setAlign(aFG.eck);
    localbiy1.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    aaE localaaE4 = new aaE();
    localaaE4.aJ();
    localaaE4.setElementMap(localcpa);
    localaaE4.setAttribute("enabled");
    localaaE4.setField("canBeDecreased");
    localbiy1.bb(localaaE4);
    localaaE4.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localaaE4.bb(localanQ2);
    localanQ2.brn();
    bJJ localbJJ1 = new bJJ();
    localbJJ1.aJ();
    localbJJ1.setElementMap(localcpa);
    localanQ2.bb(localbJJ1);
    localbJJ1.brn();
    cOk localcOk1 = new cOk();
    localcOk1.aJ();
    localcOk1.setElementMap(localcpa);
    localbJJ1.bb(localcOk1);
    localcOk1.brn();
    localcOk1.rV();
    bqW localbqW1 = new bqW();
    localbqW1.aJ();
    localbqW1.setElementMap(localcpa);
    localbJJ1.bb(localbqW1);
    localbqW1.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("isInFight");
    localNK2.setAttribute("comparedValue");
    localbqW1.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localbqW1.rV();
    localbJJ1.rV();
    localanQ2.rV();
    localaaE4.rV();
    biy localbiy2 = localbiy1;
    Jg localJg7 = localbiy2.getAppearance();
    localJg7.setElementMap(localcpa);
    localbiy1.bb(localJg7);
    localJg7.brn();
    aaE localaaE5 = new aaE();
    localaaE5.aJ();
    localaaE5.setElementMap(localcpa);
    localaaE5.setAttribute("modulationColor");
    localaaE5.setField("canBeDecreased");
    localJg7.bb(localaaE5);
    localaaE5.brn();
    anQ localanQ3 = new anQ();
    localanQ3.aJ();
    localanQ3.setElementMap(localcpa);
    localanQ3.setValue("1,1,1");
    localanQ3.setElseValue("1,1,1,0.5");
    localaaE5.bb(localanQ3);
    localanQ3.brn();
    bJJ localbJJ2 = new bJJ();
    localbJJ2.aJ();
    localbJJ2.setElementMap(localcpa);
    localanQ3.bb(localbJJ2);
    localbJJ2.brn();
    cOk localcOk2 = new cOk();
    localcOk2.aJ();
    localcOk2.setElementMap(localcpa);
    localbJJ2.bb(localcOk2);
    localcOk2.brn();
    localcOk2.rV();
    bqW localbqW2 = new bqW();
    localbqW2.aJ();
    localbqW2.setElementMap(localcpa);
    localbJJ2.bb(localbqW2);
    localbqW2.brn();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setName("isInFight");
    localNK3.setAttribute("comparedValue");
    localbqW2.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    localbqW2.rV();
    localbJJ2.rV();
    localanQ3.rV();
    localaaE5.rV();
    localJg7.rV();
    localbiy1.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("defaultBold14");
    localcWk1.setPrefSize(new Or(15, 0));
    localcWk1.setExpandable(false);
    localcWk1.setMultiline(false);
    localcWk1.setNonBlocking(true);
    localdRq6.bb(localcWk1);
    localcWk1.brn();
    aaE localaaE6 = new aaE();
    localaaE6.aJ();
    localaaE6.setElementMap(localcpa);
    localaaE6.setAttribute("text");
    localaaE6.setField("levelWithColor");
    localcWk1.bb(localaaE6);
    localaaE6.brn();
    localaaE6.rV();
    cWk localcWk2 = localcWk1;
    Jg localJg8 = localcWk2.getAppearance();
    localJg8.setElementMap(localcpa);
    ((cwJ)localJg8).setAlign(aFG.eck);
    localcWk1.bb(localJg8);
    localJg8.brn();
    cAf localcAf = cAf.checkOut();
    localcAf.setElementMap(localcpa);
    localcAf.setName("text");
    localcAf.setColor(new bNa(0.55F, 0.85F, 88.0F, 1.0F));
    localJg8.bb(localcAf);
    localcAf.brn();
    localcAf.rV();
    localJg8.rV();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setAlign(ajb.dia);
    localcwP4.setXOffset(-20);
    localcWk1.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    localcWk1.rV();
    biy localbiy3 = new biy();
    localbiy3.aJ();
    localbiy3.setElementMap(localcpa);
    localbiy3.setStyle("add");
    localbiy3.setExpandable(false);
    aMB localaMB2 = new aMB();
    localaMB2.hg("wakfu.characterSheet:improveAptitude(aptitude,spellAptitudeButtonContainer,validateSpellAptitudePoints)");
    localbiy3.setOnMousePress(localaMB2);
    localdRq6.bb(localbiy3);
    localbiy3.brn();
    dpm localdpm3 = new dpm();
    localdpm3.aJ();
    localdpm3.setElementMap(localcpa);
    localdpm3.setAlign(aFG.eck);
    localbiy3.bb(localdpm3);
    localdpm3.brn();
    localdpm3.rV();
    aaE localaaE7 = new aaE();
    localaaE7.aJ();
    localaaE7.setElementMap(localcpa);
    localaaE7.setAttribute("enabled");
    localaaE7.setField("canBeIncreased");
    localbiy3.bb(localaaE7);
    localaaE7.brn();
    anQ localanQ4 = new anQ();
    localanQ4.aJ();
    localanQ4.setElementMap(localcpa);
    localaaE7.bb(localanQ4);
    localanQ4.brn();
    bJJ localbJJ3 = new bJJ();
    localbJJ3.aJ();
    localbJJ3.setElementMap(localcpa);
    localanQ4.bb(localbJJ3);
    localbJJ3.brn();
    cOk localcOk3 = new cOk();
    localcOk3.aJ();
    localcOk3.setElementMap(localcpa);
    localbJJ3.bb(localcOk3);
    localcOk3.brn();
    localcOk3.rV();
    bqW localbqW3 = new bqW();
    localbqW3.aJ();
    localbqW3.setElementMap(localcpa);
    localbJJ3.bb(localbqW3);
    localbqW3.brn();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa);
    localNK4.setName("isInFight");
    localNK4.setAttribute("comparedValue");
    localbqW3.bb(localNK4);
    localNK4.brn();
    localNK4.rV();
    localbqW3.rV();
    localbJJ3.rV();
    localanQ4.rV();
    localaaE7.rV();
    biy localbiy4 = localbiy3;
    Jg localJg9 = localbiy4.getAppearance();
    localJg9.setElementMap(localcpa);
    localbiy3.bb(localJg9);
    localJg9.brn();
    aaE localaaE8 = new aaE();
    localaaE8.aJ();
    localaaE8.setElementMap(localcpa);
    localaaE8.setAttribute("modulationColor");
    localaaE8.setField("canBeIncreased");
    localJg9.bb(localaaE8);
    localaaE8.brn();
    anQ localanQ5 = new anQ();
    localanQ5.aJ();
    localanQ5.setElementMap(localcpa);
    localanQ5.setValue("1,1,1");
    localanQ5.setElseValue("1,1,1,0.5");
    localaaE8.bb(localanQ5);
    localanQ5.brn();
    bJJ localbJJ4 = new bJJ();
    localbJJ4.aJ();
    localbJJ4.setElementMap(localcpa);
    localanQ5.bb(localbJJ4);
    localbJJ4.brn();
    cOk localcOk4 = new cOk();
    localcOk4.aJ();
    localcOk4.setElementMap(localcpa);
    localbJJ4.bb(localcOk4);
    localcOk4.brn();
    localcOk4.rV();
    bqW localbqW4 = new bqW();
    localbqW4.aJ();
    localbqW4.setElementMap(localcpa);
    localbJJ4.bb(localbqW4);
    localbqW4.brn();
    NK localNK5 = NK.checkOut();
    localNK5.setElementMap(localcpa);
    localNK5.setName("isInFight");
    localNK5.setAttribute("comparedValue");
    localbqW4.bb(localNK5);
    localNK5.brn();
    localNK5.rV();
    localbqW4.rV();
    localbJJ4.rV();
    localanQ5.rV();
    localaaE8.rV();
    localJg9.rV();
    localbiy3.rV();
    localdRq6.rV();
    localdRq1.rV();
    localeR.rV();
    localccG1.rV();
    return localccG1;
  }

  public bdj j(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq = dRq.checkOut();
    localdRq.setElementMap(localcpa);
    parambdj.bb(localdRq);
    localdRq.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(100.0F, 100.0F));
    localdRq.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localdRq.rV();
    return localdRq;
  }

  public bdj k(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    String str = "closeCharacterSheetDialog";
    biy localbiy = new biy();
    localbiy.aJ();
    localbiy.setElementMap(localcpa);
    if ((localcpa != null) && (str != null))
      localcpa.a(str, localbiy);
    localbiy.setStyle("close");
    localbiy.setExpandable(false);
    csA localcsA = new csA();
    localcsA.hg("wakfu.characterSheet:openCloseAptitudes");
    localbiy.setOnClick(localcsA);
    parambdj.bb(localbiy);
    localbiy.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(-2, -2));
    localcwP.setAlign(ajb.dhV);
    localcwP.setXOffset(-18);
    localcwP.setYOffset(-12);
    localbiy.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localbiy.rV();
    return localbiy;
  }

  public bdj l(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(-2, -2));
    localcwP.setAlign(ajb.dia);
    localcwP.setInitValue(true);
    localcwP.setXOffset(-40);
    parambdj.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    return localcwP;
  }

  public bdj m(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    String str1 = "cancelAptitudePointsPopup";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localanG);
    localanG.setAlign(aFG.ech);
    localanG.setHotSpotPosition(aFG.ecn);
    parambdj.bb(localanG);
    localanG.brn();
    dRq localdRq = dRq.checkOut();
    localdRq.setElementMap(localcpa);
    localdRq.setPrefSize(new Or(10, 0));
    localdRq.setStyle("popup");
    localanG.bb(localdRq);
    localdRq.brn();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("PopupInformation");
    String str2 = "%cancel%";
    str2 = str2.replace("%cancel%", cBQ.cxL().mL("cancel"));
    localcaF1.setText(str2);
    localdRq.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg = localcaF2.getAppearance();
    localJg.setElementMap(localcpa);
    ((cwJ)localJg).setAlignment(aFG.ecj);
    localcaF1.bb(localJg);
    localJg.brn();
    localJg.rV();
    localcaF1.rV();
    localdRq.rV();
    localanG.rV();
    return localanG;
  }

  public bdj n(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    String str1 = "validateAptitudePointsPopup";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localanG);
    localanG.setAlign(aFG.ech);
    localanG.setHotSpotPosition(aFG.ecn);
    parambdj.bb(localanG);
    localanG.brn();
    dRq localdRq = dRq.checkOut();
    localdRq.setElementMap(localcpa);
    localdRq.setPrefSize(new Or(10, 0));
    localdRq.setStyle("popup");
    localanG.bb(localdRq);
    localdRq.brn();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("PopupInformation");
    String str2 = "%valid%";
    str2 = str2.replace("%valid%", cBQ.cxL().mL("valid"));
    localcaF1.setText(str2);
    localdRq.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg = localcaF2.getAppearance();
    localJg.setElementMap(localcpa);
    ((cwJ)localJg).setAlignment(aFG.ecj);
    localcaF1.bb(localJg);
    localJg.brn();
    localJg.rV();
    localcaF1.rV();
    localdRq.rV();
    localanG.rV();
    return localanG;
  }

  public bdj o(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    String str = "aptitudePopup";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa);
    if ((localcpa != null) && (str != null))
      localcpa.a(str, localanG);
    localanG.setAlign(aFG.eci);
    localanG.setHotSpotPosition(aFG.ecg);
    localanG.setHideOnClick(false);
    parambdj.bb(localanG);
    localanG.brn();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setPrefSize(new Or(10, 0));
    localdRq1.setStyle("popup");
    localanG.bb(localdRq1);
    localdRq1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setName("describedAptitude");
    localNK1.setAttribute("visible");
    localdRq1.bb(localNK1);
    localNK1.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localNK1.bb(localanQ);
    localanQ.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localanQ.bb(localanE);
    localanE.brn();
    localanE.rV();
    localanQ.rV();
    localNK1.rV();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(false);
    localaId.setAlign(aFG.ech);
    localdRq1.bb(localaId);
    localaId.brn();
    localaId.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setExpandable(false);
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.ecj);
    localdRq2.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("bigTitle");
    localcWk1.setMinWidth(250);
    localcWk1.setExpandable(false);
    localdRq2.bb(localcWk1);
    localcWk1.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("describedAptitude");
    localNK2.setAttribute("text");
    localNK2.setField("nameAndLevel");
    localcWk1.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    cWk localcWk2 = localcWk1;
    Jg localJg1 = localcWk2.getAppearance();
    localJg1.setElementMap(localcpa);
    localcWk1.bb(localJg1);
    localJg1.brn();
    cAf localcAf = cAf.checkOut();
    localcAf.setElementMap(localcpa);
    localcAf.setColor(new bNa(1.0F, 1.0F, 1.0F, 1.0F));
    localJg1.bb(localcAf);
    localcAf.brn();
    localcAf.rV();
    localJg1.rV();
    localcWk1.rV();
    localdRq2.rV();
    cWk localcWk3 = new cWk();
    localcWk3.aJ();
    localcWk3.setElementMap(localcpa);
    localcWk3.setMinWidth(250);
    localcWk3.setStyle("white11");
    localdRq1.bb(localcWk3);
    localcWk3.brn();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setName("describedAptitude");
    localNK3.setAttribute("text");
    localNK3.setField("description");
    localcWk3.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    cWk localcWk4 = localcWk3;
    Jg localJg2 = localcWk4.getAppearance();
    localJg2.setElementMap(localcpa);
    localcWk3.bb(localJg2);
    localJg2.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(5, 0, 0, 0));
    localJg2.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg2.rV();
    localcWk3.rV();
    localdRq1.rV();
    localanG.rV();
    return localanG;
  }
}