import java.util.Stack;

public class bPs
  implements aTK
{
  private uk W;
  private Stack X = new Stack();

  public void a(cpa paramcpa, uk paramuk, dOc paramdOc)
  {
    this.W = paramuk;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    dOc localdOc = paramdOc;
    Jg localJg = localdOc.getAppearance();
    localJg.setElementMap(localcpa);
    paramdOc.bb(localJg);
    localJg.brn();
    String str = "OrangeArrowBackground";
    Cx localCx = new Cx();
    localCx.aJ();
    localCx.setElementMap(localcpa);
    if ((localcpa != null) && (str != null))
      localcpa.a(str, localCx);
    localJg.bb(localCx);
    localCx.brn();
    aAR localaAR1 = aAR.checkOut();
    localaAR1.setElementMap(localcpa);
    localaAR1.setHeight(43);
    localaAR1.setPosition(ajb.dhR);
    localaAR1.setWidth(0);
    localaAR1.setX(0);
    localaAR1.setY(0);
    localCx.bb(localaAR1);
    localaAR1.brn();
    localaAR1.rV();
    aAR localaAR2 = aAR.checkOut();
    localaAR2.setElementMap(localcpa);
    localaAR2.setPosition(ajb.dhT);
    localaAR2.setX(250);
    localaAR2.setY(165);
    localaAR2.setWidth(1);
    localaAR2.setHeight(43);
    localaAR2.setTexture(this.W.aH("guild_0.tga"));
    localCx.bb(localaAR2);
    localaAR2.brn();
    localaAR2.rV();
    aAR localaAR3 = aAR.checkOut();
    localaAR3.setElementMap(localcpa);
    localaAR3.setFlipHorizontaly(true);
    localaAR3.setPosition(ajb.dhV);
    localaAR3.setX(195);
    localaAR3.setY(95);
    localaAR3.setWidth(40);
    localaAR3.setHeight(43);
    localaAR3.setTexture(this.W.aH("guild_0.tga"));
    localCx.bb(localaAR3);
    localaAR3.brn();
    localaAR3.rV();
    aAR localaAR4 = aAR.checkOut();
    localaAR4.setElementMap(localcpa);
    localaAR4.setHeight(0);
    localaAR4.setPosition(ajb.dia);
    localaAR4.setWidth(40);
    localaAR4.setX(0);
    localaAR4.setY(0);
    localCx.bb(localaAR4);
    localaAR4.brn();
    localaAR4.rV();
    aAR localaAR5 = aAR.checkOut();
    localaAR5.setElementMap(localcpa);
    localaAR5.setHeight(0);
    localaAR5.setPosition(ajb.dih);
    localaAR5.setWidth(40);
    localaAR5.setX(0);
    localaAR5.setY(0);
    localCx.bb(localaAR5);
    localaAR5.brn();
    localaAR5.rV();
    aAR localaAR6 = aAR.checkOut();
    localaAR6.setElementMap(localcpa);
    localaAR6.setHeight(0);
    localaAR6.setPosition(ajb.dif);
    localaAR6.setWidth(1);
    localaAR6.setX(0);
    localaAR6.setY(0);
    localCx.bb(localaAR6);
    localaAR6.brn();
    localaAR6.rV();
    aAR localaAR7 = aAR.checkOut();
    localaAR7.setElementMap(localcpa);
    localaAR7.setHeight(0);
    localaAR7.setPosition(ajb.did);
    localaAR7.setWidth(0);
    localaAR7.setX(0);
    localaAR7.setY(0);
    localCx.bb(localaAR7);
    localaAR7.brn();
    localaAR7.rV();
    aAR localaAR8 = aAR.checkOut();
    localaAR8.setElementMap(localcpa);
    localaAR8.setHeight(0);
    localaAR8.setPosition(ajb.dhY);
    localaAR8.setWidth(0);
    localaAR8.setX(0);
    localaAR8.setY(0);
    localCx.bb(localaAR8);
    localaAR8.brn();
    localaAR8.rV();
    aAR localaAR9 = aAR.checkOut();
    localaAR9.setElementMap(localcpa);
    localaAR9.setPosition(ajb.dhZ);
    localaAR9.setX(250);
    localaAR9.setY(211);
    localaAR9.setWidth(1);
    localaAR9.setHeight(43);
    localaAR9.setTexture(this.W.aH("guild_0.tga"));
    localCx.bb(localaAR9);
    localaAR9.brn();
    localaAR9.rV();
    localCx.rV();
    localJg.rV();
  }
}