import java.awt.Insets;
import java.util.Stack;

public class bNv
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setAlign(ajb.dhZ);
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    czO localczO1 = new czO();
    localczO1.aJ();
    localczO1.setAdaptToContentSize(true);
    localdRq1.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    String str1 = "background";
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localczv1);
    localdRq1.bb(localczv1);
    localczv1.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.dhZ);
    localcwP2.setSize(new Or(450, 612));
    localczv1.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv1.bb(localaAR);
    localaAR.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("texture");
    localNK1.setName("dungeonLadderBackgroundImage");
    localaAR.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    localaAR.rV();
    localczv1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setAlign(ajb.dhZ);
    localdRq2.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    aId localaId1 = aId.checkOut();
    localdRq2.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq2.bb(localdRq3);
    localdRq3.brn();
    dRq localdRq4 = localdRq3;
    Jg localJg1 = localdRq4.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq3.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(10, 25, 25, 25));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    aId localaId2 = aId.checkOut();
    localaId2.setHorizontal(false);
    localaId2.setAlign(aFG.ech);
    localdRq3.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    dRq localdRq5 = dRq.checkOut();
    localdRq5.setElementMap(localcpa);
    localdRq5.setExpandable(false);
    localdRq3.bb(localdRq5);
    localdRq5.brn();
    czO localczO2 = new czO();
    localczO2.aJ();
    localczO2.setAdaptToContentSize(true);
    localdRq5.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    czv localczv2 = new czv();
    localczv2.aJ();
    localczv2.setElementMap(localcpa);
    localczv2.setStyle("SplashTitle");
    localdRq5.bb(localczv2);
    localczv2.brn();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setAlign(ajb.dhZ);
    localcwP4.setSize(new Or(100.0F, 100.0F));
    localczv2.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    localczv2.rV();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq6.setExpandable(false);
    localdRq5.bb(localdRq6);
    localdRq6.brn();
    cwP localcwP5 = new cwP();
    localcwP5.aJ();
    localcwP5.setElementMap(localcpa);
    localcwP5.setAlign(ajb.dhZ);
    localdRq6.bb(localcwP5);
    localcwP5.brn();
    localcwP5.rV();
    czO localczO3 = new czO();
    localczO3.aJ();
    localczO3.setAdaptToContentSize(true);
    localdRq6.bb(localczO3);
    localczO3.brn();
    localczO3.rV();
    czv localczv3 = new czv();
    localczv3.aJ();
    localczv3.setElementMap(localcpa);
    localczv3.setStyle("TitleDecoratorLeft");
    localdRq6.bb(localczv3);
    localczv3.brn();
    cwP localcwP6 = new cwP();
    localcwP6.aJ();
    localcwP6.setElementMap(localcpa);
    localcwP6.setAlign(ajb.dhY);
    localczv3.bb(localcwP6);
    localcwP6.brn();
    localcwP6.rV();
    localczv3.rV();
    czv localczv4 = new czv();
    localczv4.aJ();
    localczv4.setElementMap(localcpa);
    localczv4.setStyle("TitleDecoratorRight");
    localdRq6.bb(localczv4);
    localczv4.brn();
    cwP localcwP7 = new cwP();
    localcwP7.aJ();
    localcwP7.setElementMap(localcpa);
    localcwP7.setAlign(ajb.dia);
    localczv4.bb(localcwP7);
    localcwP7.brn();
    localcwP7.rV();
    localczv4.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("StyledBold16Dark");
    localcWk1.setMaxWidth(300);
    String str2 = "%guild.ladder%";
    str2 = str2.replace("%guild.ladder%", cBQ.cxL().mL("guild.ladder"));
    localcWk1.setText(str2);
    localdRq6.bb(localcWk1);
    localcWk1.brn();
    cwP localcwP8 = new cwP();
    localcwP8.aJ();
    localcwP8.setElementMap(localcpa);
    localcwP8.setAlign(ajb.dhZ);
    localcwP8.setYOffset(12);
    localcwP8.setSize(new Or(100.0F, -2));
    localcWk1.bb(localcwP8);
    localcwP8.brn();
    localcwP8.rV();
    cWk localcWk2 = localcWk1;
    Jg localJg2 = localcWk2.getAppearance();
    localJg2.setElementMap(localcpa);
    ((cwJ)localJg2).setAlignment(aFG.eck);
    localcWk1.bb(localJg2);
    localJg2.brn();
    cuR localcuR = new cuR();
    localcuR.aJ();
    localcuR.setElementMap(localcpa);
    localcuR.setInsets(new Insets(0, 50, 0, 50));
    localJg2.bb(localcuR);
    localcuR.brn();
    localcuR.rV();
    localJg2.rV();
    localcWk1.rV();
    localdRq6.rV();
    localdRq5.rV();
    String str3 = "ladderTable";
    aXE localaXE = new aXE();
    localaXE.aJ();
    localaXE.setElementMap(localcpa);
    if ((localcpa != null) && (str3 != null))
      localcpa.a(str3, localaXE);
    localaXE.setCellHeight(45);
    localaXE.setMinRows(9);
    localaXE.setMaxRows(9);
    localaXE.setExpandable(false);
    localaXE.setStyle("dark");
    localaXE.setSelectionable(false);
    localdRq3.bb(localaXE);
    localaXE.brn();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.ech);
    localaXE.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setAttribute("content");
    localNK2.setName("guildLadder");
    localNK2.setField("currentList");
    localaXE.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    bSJ localbSJ1 = new bSJ();
    localbSJ1.aJ();
    localbSJ1.setElementMap(localcpa);
    localbSJ1.setCellWidth(40);
    String str4 = "%rank%";
    str4 = str4.replace("%rank%", cBQ.cxL().mL("rank"));
    localbSJ1.setName(str4);
    localbSJ1.setColumnId("rank");
    localbSJ1.setSortable(false);
    localaXE.bb(localbSJ1);
    localbSJ1.brn();
    eR localeR1 = new eR();
    localeR1.aJ();
    localeR1.setElementMap(localcpa);
    localbSJ1.bb(localeR1);
    localeR1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localeR1.bb(localanQ1);
    localanQ1.brn();
    bxx localbxx1 = new bxx();
    localbxx1.aJ();
    localbxx1.setElementMap(localcpa);
    localanQ1.bb(localbxx1);
    localbxx1.brn();
    anE localanE1 = new anE();
    localanE1.aJ();
    localanE1.setElementMap(localcpa);
    localbxx1.bb(localanE1);
    localanE1.brn();
    localanE1.rV();
    localbxx1.rV();
    localanQ1.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localdRq7.setExpandable(false);
    localdRq7.setPrefSize(new Or(40, 0));
    cCu localcCu1 = new cCu();
    localcCu1.hg("popup(descriptionPopup)");
    localdRq7.setOnPopupDisplay(localcCu1);
    localdRq7.setNonBlocking(false);
    jL localjL1 = new jL();
    localjL1.hg("closePopup");
    localdRq7.setOnPopupHide(localjL1);
    localeR1.bb(localdRq7);
    localdRq7.brn();
    String str5 = "descriptionPopup";
    anG localanG1 = new anG();
    localanG1.aJ();
    localanG1.setElementMap(localcpa);
    if ((localcpa != null) && (str5 != null))
      localcpa.a(str5, localanG1);
    localanG1.setAlign(aFG.ech);
    localanG1.setHotSpotPosition(aFG.ecn);
    localdRq7.bb(localanG1);
    localanG1.brn();
    dRq localdRq8 = dRq.checkOut();
    localdRq8.setElementMap(localcpa);
    localdRq8.setPrefSize(new Or(10, 0));
    localdRq8.setStyle("popup");
    localanG1.bb(localdRq8);
    localdRq8.brn();
    aId localaId3 = aId.checkOut();
    localaId3.setHorizontal(false);
    localaId3.setAlign(aFG.ech);
    localdRq8.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("visible");
    localaaE1.setField("description");
    localdRq8.bb(localaaE1);
    localaaE1.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localaaE1.bb(localanQ2);
    localanQ2.brn();
    anE localanE2 = new anE();
    localanE2.aJ();
    localanE2.setElementMap(localcpa);
    localanQ2.bb(localanE2);
    localanE2.brn();
    localanE2.rV();
    localanQ2.rV();
    localaaE1.rV();
    cWk localcWk3 = new cWk();
    localcWk3.aJ();
    localcWk3.setElementMap(localcpa);
    localcWk3.setStyle("PopupInformation");
    localcWk3.setMultiline(true);
    localcWk3.setMinWidth(300);
    localdRq8.bb(localcWk3);
    localcWk3.brn();
    cWk localcWk4 = localcWk3;
    Jg localJg3 = localcWk4.getAppearance();
    localJg3.setElementMap(localcpa);
    ((cwJ)localJg3).setAlignment(aFG.ecj);
    localcWk3.bb(localJg3);
    localJg3.brn();
    localJg3.rV();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("text");
    localaaE2.setField("description");
    localcWk3.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    localcWk3.rV();
    localdRq8.rV();
    localanG1.rV();
    aId localaId4 = aId.checkOut();
    localaId4.setAlign(aFG.eck);
    localdRq7.bb(localaId4);
    localaId4.brn();
    localaId4.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("blackBold");
    localcaF1.setNonBlocking(true);
    localcaF1.setMinWidth(20);
    localcaF1.setMaxWidth(20);
    localcaF1.setExpandable(false);
    localcaF1.setEnableAutoZoomShrink(true);
    localdRq7.bb(localcaF1);
    localcaF1.brn();
    aaE localaaE3 = new aaE();
    localaaE3.aJ();
    localaaE3.setElementMap(localcpa);
    localaaE3.setAttribute("text");
    localaaE3.setField("rank");
    localcaF1.bb(localaaE3);
    localaaE3.brn();
    localaaE3.rV();
    caF localcaF2 = localcaF1;
    Jg localJg4 = localcaF2.getAppearance();
    localJg4.setElementMap(localcpa);
    localcaF1.bb(localJg4);
    localJg4.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 3, 0, 0));
    localJg4.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg4.rV();
    localcaF1.rV();
    localdRq7.rV();
    localeR1.rV();
    eR localeR2 = new eR();
    localeR2.aJ();
    localeR2.setElementMap(localcpa);
    localbSJ1.bb(localeR2);
    localeR2.brn();
    anQ localanQ3 = new anQ();
    localanQ3.aJ();
    localanQ3.setElementMap(localcpa);
    localeR2.bb(localanQ3);
    localanQ3.brn();
    bxx localbxx2 = new bxx();
    localbxx2.aJ();
    localbxx2.setElementMap(localcpa);
    localanQ3.bb(localbxx2);
    localbxx2.brn();
    aIB localaIB = new aIB();
    localaIB.aJ();
    localaIB.setElementMap(localcpa);
    localbxx2.bb(localaIB);
    localaIB.brn();
    localaIB.rV();
    localbxx2.rV();
    localanQ3.rV();
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa);
    localdRq9.setPrefSize(new Or(40, 0));
    localeR2.bb(localdRq9);
    localdRq9.brn();
    localdRq9.rV();
    localeR2.rV();
    localbSJ1.rV();
    bSJ localbSJ2 = new bSJ();
    localbSJ2.aJ();
    localbSJ2.setElementMap(localcpa);
    localbSJ2.setCellWidth(145);
    String str6 = "%guild.name%";
    str6 = str6.replace("%guild.name%", cBQ.cxL().mL("guild.name"));
    localbSJ2.setName(str6);
    localbSJ2.setColumnId("name");
    localbSJ2.setSortable(false);
    localaXE.bb(localbSJ2);
    localbSJ2.brn();
    eR localeR3 = new eR();
    localeR3.aJ();
    localeR3.setElementMap(localcpa);
    localbSJ2.bb(localeR3);
    localeR3.brn();
    anQ localanQ4 = new anQ();
    localanQ4.aJ();
    localanQ4.setElementMap(localcpa);
    localeR3.bb(localanQ4);
    localanQ4.brn();
    bxx localbxx3 = new bxx();
    localbxx3.aJ();
    localbxx3.setElementMap(localcpa);
    localanQ4.bb(localbxx3);
    localbxx3.brn();
    anE localanE3 = new anE();
    localanE3.aJ();
    localanE3.setElementMap(localcpa);
    localbxx3.bb(localanE3);
    localanE3.brn();
    localanE3.rV();
    localbxx3.rV();
    localanQ4.rV();
    String str7 = "zone";
    avo localavo = new avo();
    localavo.aJ();
    localavo.setElementMap(localcpa);
    if ((localcpa != null) && (str7 != null))
      localcpa.a(str7, localavo);
    localeR3.bb(localavo);
    localavo.brn();
    aaE localaaE4 = new aaE();
    localaaE4.aJ();
    localaaE4.setElementMap(localcpa);
    localaaE4.setAttribute("value");
    localavo.bb(localaaE4);
    localaaE4.brn();
    localaaE4.rV();
    localavo.rV();
    dRq localdRq10 = dRq.checkOut();
    localdRq10.setElementMap(localcpa);
    cCu localcCu2 = new cCu();
    localcCu2.hg("popup(descriptionPopup)");
    localdRq10.setOnPopupDisplay(localcCu2);
    localdRq10.setNonBlocking(false);
    jL localjL2 = new jL();
    localjL2.hg("closePopup");
    localdRq10.setOnPopupHide(localjL2);
    localdRq10.setPrefSize(new Or(0, 40));
    localeR3.bb(localdRq10);
    localdRq10.brn();
    String str8 = "descriptionPopup";
    anG localanG2 = new anG();
    localanG2.aJ();
    localanG2.setElementMap(localcpa);
    if ((localcpa != null) && (str8 != null))
      localcpa.a(str8, localanG2);
    localanG2.setAlign(aFG.ech);
    localanG2.setHotSpotPosition(aFG.ecn);
    localdRq10.bb(localanG2);
    localanG2.brn();
    dRq localdRq11 = dRq.checkOut();
    localdRq11.setElementMap(localcpa);
    localdRq11.setPrefSize(new Or(10, 0));
    localdRq11.setStyle("popup");
    localanG2.bb(localdRq11);
    localdRq11.brn();
    aId localaId5 = aId.checkOut();
    localaId5.setHorizontal(false);
    localaId5.setAlign(aFG.ech);
    localdRq11.bb(localaId5);
    localaId5.brn();
    localaId5.rV();
    aaE localaaE5 = new aaE();
    localaaE5.aJ();
    localaaE5.setElementMap(localcpa);
    localaaE5.setAttribute("visible");
    localaaE5.setField("description");
    localdRq11.bb(localaaE5);
    localaaE5.brn();
    anQ localanQ5 = new anQ();
    localanQ5.aJ();
    localanQ5.setElementMap(localcpa);
    localaaE5.bb(localanQ5);
    localanQ5.brn();
    a(localanQ5);
    localanQ5.rV();
    localaaE5.rV();
    b(localdRq11);
    localdRq11.rV();
    localanG2.rV();
    d(localdRq10);
    e(localdRq10);
    f(localdRq10);
    g(localdRq10);
    localdRq10.rV();
    localeR3.rV();
    h(localbSJ2);
    localbSJ2.rV();
    i(localaXE);
    j(localaXE);
    k(localaXE);
    localaXE.rV();
    l(localdRq3);
    localdRq3.rV();
    localdRq2.rV();
    m(localdRq1);
    localdRq1.rV();
    return localdRq1;
  }

  public bdj a(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    parambdj.bb(localanE);
    localanE.brn();
    localanE.rV();
    return localanE;
  }

  public bdj b(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq = dRq.checkOut();
    localdRq.setElementMap(localcpa);
    localdRq.setExpandable(false);
    parambdj.bb(localdRq);
    localdRq.brn();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(false);
    localaId.setAlign(aFG.ech);
    localdRq.bb(localaId);
    localaId.brn();
    localaId.rV();
    caF localcaF = new caF();
    localcaF.aJ();
    localcaF.setElementMap(localcpa);
    localcaF.setStyle("PopupInformation");
    String str = "%description%%colon%";
    str = str.replace("%description%", cBQ.cxL().mL("description"));
    str = str.replace("%colon%", cBQ.cxL().mL("colon"));
    localcaF.setText(str);
    localcaF.setExpandable(false);
    localdRq.bb(localcaF);
    localcaF.brn();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.ecj);
    localcaF.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    localcaF.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("PopupInformation");
    localcWk1.setMultiline(true);
    localcWk1.setMinWidth(300);
    localdRq.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg = localcWk2.getAppearance();
    localJg.setElementMap(localcpa);
    ((cwJ)localJg).setAlignment(aFG.ecj);
    localcWk1.bb(localJg);
    localJg.brn();
    localJg.rV();
    aaE localaaE = new aaE();
    localaaE.aJ();
    localaaE.setElementMap(localcpa);
    localaaE.setAttribute("text");
    localaaE.setField("description");
    localcWk1.bb(localaaE);
    localaaE.brn();
    localaaE.rV();
    localcWk1.rV();
    localdRq.rV();
    return localdRq;
  }

  public bdj d(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    aId localaId = aId.checkOut();
    localaId.setAlign(aFG.ecj);
    parambdj.bb(localaId);
    localaId.brn();
    localaId.rV();
    return null;
  }

  public bdj e(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dOc localdOc = (dOc)parambdj;
    Jg localJg = localdOc.getAppearance();
    localJg.setElementMap(localcpa);
    parambdj.bb(localJg);
    localJg.brn();
    ams localams = new ams();
    localams.aJ();
    localams.setElementMap(localcpa);
    localams.setInsets(new Insets(0, 1, 0, 0));
    localams.setColor(new bNa(0.94F, 0.86F, 0.66F, 0.8F));
    localJg.bb(localams);
    localams.brn();
    localams.rV();
    cuR localcuR = new cuR();
    localcuR.aJ();
    localcuR.setElementMap(localcpa);
    localcuR.setInsets(new Insets(0, 1, 0, 0));
    localJg.bb(localcuR);
    localcuR.brn();
    localcuR.rV();
    localJg.rV();
    return localJg;
  }

  public bdj f(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setNeedsScissor(true);
    localdRq1.setExpandable(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    czO localczO = new czO();
    localczO.aJ();
    localczO.setAdaptToContentSize(true);
    localdRq1.bb(localczO);
    localczO.brn();
    localczO.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setNeedsScissor(true);
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setAlign(ajb.dhZ);
    localcwP.setSize(new Or(35, 36));
    localdRq2.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setDisplaySize(new Or(36, 36));
    localczv.setExpandable(false);
    localczv.setNonBlocking(true);
    localdRq2.bb(localczv);
    localczv.brn();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv.bb(localaAR);
    localaAR.brn();
    aaE localaaE = new aaE();
    localaaE.aJ();
    localaaE.setElementMap(localcpa);
    localaaE.setAttribute("texture");
    localaaE.setField("blazon");
    localaAR.bb(localaaE);
    localaaE.brn();
    localaaE.rV();
    localaAR.rV();
    localczv.rV();
    localdRq2.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj g(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq = dRq.checkOut();
    localdRq.setElementMap(localcpa);
    parambdj.bb(localdRq);
    localdRq.brn();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(false);
    localaId.setAlign(aFG.ech);
    localdRq.bb(localaId);
    localaId.brn();
    localaId.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("blackBold");
    localcWk1.setMinWidth(1);
    localcWk1.setMaxWidth(100);
    localcWk1.setNonBlocking(true);
    localcWk1.setExpandable(false);
    localcWk1.setEnableAutoZoomShrink(true);
    localdRq.bb(localcWk1);
    localcWk1.brn();
    aaE localaaE = new aaE();
    localaaE.aJ();
    localaaE.setElementMap(localcpa);
    localaaE.setAttribute("text");
    localaaE.setField("name");
    localcWk1.bb(localaaE);
    localaaE.brn();
    localaaE.rV();
    cWk localcWk2 = localcWk1;
    Jg localJg = localcWk2.getAppearance();
    localJg.setElementMap(localcpa);
    localcWk1.bb(localJg);
    localJg.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(5, 2, 0, 0));
    localJg.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg.rV();
    localcWk1.rV();
    localdRq.rV();
    return localdRq;
  }

  public bdj h(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    eR localeR = new eR();
    localeR.aJ();
    localeR.setElementMap(localcpa);
    parambdj.bb(localeR);
    localeR.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localeR.bb(localanQ);
    localanQ.brn();
    bxx localbxx = new bxx();
    localbxx.aJ();
    localbxx.setElementMap(localcpa);
    localanQ.bb(localbxx);
    localbxx.brn();
    aIB localaIB = new aIB();
    localaIB.aJ();
    localaIB.setElementMap(localcpa);
    localbxx.bb(localaIB);
    localaIB.brn();
    localaIB.rV();
    localbxx.rV();
    localanQ.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setPrefSize(new Or(145, 0));
    localeR.bb(localdRq1);
    localdRq1.brn();
    dRq localdRq2 = localdRq1;
    Jg localJg = localdRq2.getAppearance();
    localJg.setElementMap(localcpa);
    localdRq1.bb(localJg);
    localJg.brn();
    ams localams = new ams();
    localams.aJ();
    localams.setElementMap(localcpa);
    localams.setInsets(new Insets(0, 1, 0, 0));
    localams.setColor(new bNa(0.94F, 0.86F, 0.66F, 0.8F));
    localJg.bb(localams);
    localams.brn();
    localams.rV();
    localJg.rV();
    localdRq1.rV();
    localeR.rV();
    return localeR;
  }

  public bdj i(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    bSJ localbSJ = new bSJ();
    localbSJ.aJ();
    localbSJ.setElementMap(localcpa);
    localbSJ.setCellWidth(50);
    String str1 = "%level%";
    str1 = str1.replace("%level%", cBQ.cxL().mL("level"));
    localbSJ.setName(str1);
    localbSJ.setColumnId("level");
    parambdj.bb(localbSJ);
    localbSJ.brn();
    eR localeR1 = new eR();
    localeR1.aJ();
    localeR1.setElementMap(localcpa);
    localbSJ.bb(localeR1);
    localeR1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localeR1.bb(localanQ1);
    localanQ1.brn();
    bxx localbxx1 = new bxx();
    localbxx1.aJ();
    localbxx1.setElementMap(localcpa);
    localanQ1.bb(localbxx1);
    localbxx1.brn();
    anE localanE1 = new anE();
    localanE1.aJ();
    localanE1.setElementMap(localcpa);
    localbxx1.bb(localanE1);
    localanE1.brn();
    localanE1.rV();
    localbxx1.rV();
    localanQ1.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    localdRq1.setPrefSize(new Or(50, 0));
    cCu localcCu = new cCu();
    localcCu.hg("popup(descriptionPopup)");
    localdRq1.setOnPopupDisplay(localcCu);
    localdRq1.setNonBlocking(false);
    jL localjL = new jL();
    localjL.hg("closePopup");
    localdRq1.setOnPopupHide(localjL);
    localeR1.bb(localdRq1);
    localdRq1.brn();
    String str2 = "descriptionPopup";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localanG);
    localanG.setAlign(aFG.ech);
    localanG.setHotSpotPosition(aFG.ecn);
    localdRq1.bb(localanG);
    localanG.brn();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setPrefSize(new Or(10, 0));
    localdRq2.setStyle("popup");
    localanG.bb(localdRq2);
    localdRq2.brn();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localaId1.setAlign(aFG.ech);
    localdRq2.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("visible");
    localaaE1.setField("description");
    localdRq2.bb(localaaE1);
    localaaE1.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localaaE1.bb(localanQ2);
    localanQ2.brn();
    anE localanE2 = new anE();
    localanE2.aJ();
    localanE2.setElementMap(localcpa);
    localanQ2.bb(localanE2);
    localanE2.brn();
    localanE2.rV();
    localanQ2.rV();
    localaaE1.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq3.setExpandable(false);
    localdRq2.bb(localdRq3);
    localdRq3.brn();
    aId localaId2 = aId.checkOut();
    localaId2.setHorizontal(false);
    localaId2.setAlign(aFG.ech);
    localdRq3.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("PopupInformation");
    String str3 = "%description%%colon%";
    str3 = str3.replace("%description%", cBQ.cxL().mL("description"));
    str3 = str3.replace("%colon%", cBQ.cxL().mL("colon"));
    localcaF1.setText(str3);
    localcaF1.setExpandable(false);
    localdRq3.bb(localcaF1);
    localcaF1.brn();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.ecj);
    localcaF1.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    localcaF1.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("PopupInformation");
    localcWk1.setMultiline(true);
    localcWk1.setMinWidth(300);
    localdRq3.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg1 = localcWk2.getAppearance();
    localJg1.setElementMap(localcpa);
    ((cwJ)localJg1).setAlignment(aFG.ecj);
    localcWk1.bb(localJg1);
    localJg1.brn();
    localJg1.rV();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("text");
    localaaE2.setField("description");
    localcWk1.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    localcWk1.rV();
    localdRq3.rV();
    localdRq2.rV();
    localanG.rV();
    dRq localdRq4 = localdRq1;
    Jg localJg2 = localdRq4.getAppearance();
    localJg2.setElementMap(localcpa);
    localdRq1.bb(localJg2);
    localJg2.brn();
    ams localams1 = new ams();
    localams1.aJ();
    localams1.setElementMap(localcpa);
    localams1.setInsets(new Insets(0, 1, 0, 0));
    localams1.setColor(new bNa(0.94F, 0.86F, 0.66F, 0.8F));
    localJg2.bb(localams1);
    localams1.brn();
    localams1.rV();
    localJg2.rV();
    aId localaId3 = aId.checkOut();
    localaId3.setAlign(aFG.eck);
    localdRq1.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    caF localcaF2 = new caF();
    localcaF2.aJ();
    localcaF2.setElementMap(localcpa);
    localcaF2.setStyle("blackBold");
    localcaF2.setNonBlocking(true);
    localcaF2.setMinWidth(30);
    localcaF2.setMaxWidth(30);
    localcaF2.setExpandable(false);
    localcaF2.setEnableAutoZoomShrink(true);
    localdRq1.bb(localcaF2);
    localcaF2.brn();
    aaE localaaE3 = new aaE();
    localaaE3.aJ();
    localaaE3.setElementMap(localcpa);
    localaaE3.setAttribute("text");
    localaaE3.setField("level");
    localcaF2.bb(localaaE3);
    localaaE3.brn();
    localaaE3.rV();
    caF localcaF3 = localcaF2;
    Jg localJg3 = localcaF3.getAppearance();
    localJg3.setElementMap(localcpa);
    localcaF2.bb(localJg3);
    localJg3.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(0, 3, 0, 0));
    localJg3.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg3.rV();
    localcaF2.rV();
    localdRq1.rV();
    localeR1.rV();
    eR localeR2 = new eR();
    localeR2.aJ();
    localeR2.setElementMap(localcpa);
    localbSJ.bb(localeR2);
    localeR2.brn();
    anQ localanQ3 = new anQ();
    localanQ3.aJ();
    localanQ3.setElementMap(localcpa);
    localeR2.bb(localanQ3);
    localanQ3.brn();
    bxx localbxx2 = new bxx();
    localbxx2.aJ();
    localbxx2.setElementMap(localcpa);
    localanQ3.bb(localbxx2);
    localbxx2.brn();
    aIB localaIB = new aIB();
    localaIB.aJ();
    localaIB.setElementMap(localcpa);
    localbxx2.bb(localaIB);
    localaIB.brn();
    localaIB.rV();
    localbxx2.rV();
    localanQ3.rV();
    dRq localdRq5 = dRq.checkOut();
    localdRq5.setElementMap(localcpa);
    localdRq5.setPrefSize(new Or(40, 0));
    localeR2.bb(localdRq5);
    localdRq5.brn();
    dRq localdRq6 = localdRq5;
    Jg localJg4 = localdRq6.getAppearance();
    localJg4.setElementMap(localcpa);
    localdRq5.bb(localJg4);
    localJg4.brn();
    ams localams2 = new ams();
    localams2.aJ();
    localams2.setElementMap(localcpa);
    localams2.setInsets(new Insets(0, 1, 0, 0));
    localams2.setColor(new bNa(0.94F, 0.86F, 0.66F, 0.8F));
    localJg4.bb(localams2);
    localams2.brn();
    localams2.rV();
    localJg4.rV();
    localdRq5.rV();
    localeR2.rV();
    localbSJ.rV();
    return localbSJ;
  }

  public bdj j(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    bSJ localbSJ = new bSJ();
    localbSJ.aJ();
    localbSJ.setElementMap(localcpa);
    localbSJ.setCellWidth(85);
    String str1 = "%guild.guildPoints%";
    str1 = str1.replace("%guild.guildPoints%", cBQ.cxL().mL("guild.guildPoints"));
    localbSJ.setName(str1);
    localbSJ.setColumnId("guildPoints");
    parambdj.bb(localbSJ);
    localbSJ.brn();
    eR localeR1 = new eR();
    localeR1.aJ();
    localeR1.setElementMap(localcpa);
    localbSJ.bb(localeR1);
    localeR1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localeR1.bb(localanQ1);
    localanQ1.brn();
    bxx localbxx1 = new bxx();
    localbxx1.aJ();
    localbxx1.setElementMap(localcpa);
    localanQ1.bb(localbxx1);
    localbxx1.brn();
    anE localanE1 = new anE();
    localanE1.aJ();
    localanE1.setElementMap(localcpa);
    localbxx1.bb(localanE1);
    localanE1.brn();
    localanE1.rV();
    localbxx1.rV();
    localanQ1.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    localdRq1.setPrefSize(new Or(85, 0));
    cCu localcCu = new cCu();
    localcCu.hg("popup(descriptionPopup)");
    localdRq1.setOnPopupDisplay(localcCu);
    localdRq1.setNonBlocking(false);
    jL localjL = new jL();
    localjL.hg("closePopup");
    localdRq1.setOnPopupHide(localjL);
    localeR1.bb(localdRq1);
    localdRq1.brn();
    String str2 = "descriptionPopup";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localanG);
    localanG.setAlign(aFG.ech);
    localanG.setHotSpotPosition(aFG.ecn);
    localdRq1.bb(localanG);
    localanG.brn();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setPrefSize(new Or(10, 0));
    localdRq2.setStyle("popup");
    localanG.bb(localdRq2);
    localdRq2.brn();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localaId1.setAlign(aFG.ech);
    localdRq2.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("visible");
    localaaE1.setField("description");
    localdRq2.bb(localaaE1);
    localaaE1.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localaaE1.bb(localanQ2);
    localanQ2.brn();
    anE localanE2 = new anE();
    localanE2.aJ();
    localanE2.setElementMap(localcpa);
    localanQ2.bb(localanE2);
    localanE2.brn();
    localanE2.rV();
    localanQ2.rV();
    localaaE1.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq3.setExpandable(false);
    localdRq2.bb(localdRq3);
    localdRq3.brn();
    aId localaId2 = aId.checkOut();
    localaId2.setHorizontal(false);
    localaId2.setAlign(aFG.ech);
    localdRq3.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("PopupInformation");
    String str3 = "%description%%colon%";
    str3 = str3.replace("%description%", cBQ.cxL().mL("description"));
    str3 = str3.replace("%colon%", cBQ.cxL().mL("colon"));
    localcaF1.setText(str3);
    localcaF1.setExpandable(false);
    localdRq3.bb(localcaF1);
    localcaF1.brn();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.ecj);
    localcaF1.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    localcaF1.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("PopupInformation");
    localcWk1.setMultiline(true);
    localcWk1.setMinWidth(300);
    localdRq3.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg1 = localcWk2.getAppearance();
    localJg1.setElementMap(localcpa);
    ((cwJ)localJg1).setAlignment(aFG.ecj);
    localcWk1.bb(localJg1);
    localJg1.brn();
    localJg1.rV();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("text");
    localaaE2.setField("description");
    localcWk1.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    localcWk1.rV();
    localdRq3.rV();
    localdRq2.rV();
    localanG.rV();
    dRq localdRq4 = localdRq1;
    Jg localJg2 = localdRq4.getAppearance();
    localJg2.setElementMap(localcpa);
    localdRq1.bb(localJg2);
    localJg2.brn();
    ams localams1 = new ams();
    localams1.aJ();
    localams1.setElementMap(localcpa);
    localams1.setInsets(new Insets(0, 1, 0, 0));
    localams1.setColor(new bNa(0.94F, 0.86F, 0.66F, 0.8F));
    localJg2.bb(localams1);
    localams1.brn();
    localams1.rV();
    localJg2.rV();
    aId localaId3 = aId.checkOut();
    localaId3.setAlign(aFG.eck);
    localdRq1.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    caF localcaF2 = new caF();
    localcaF2.aJ();
    localcaF2.setElementMap(localcpa);
    localcaF2.setStyle("blackBold");
    localcaF2.setNonBlocking(true);
    localcaF2.setMinWidth(70);
    localcaF2.setMaxWidth(70);
    localcaF2.setExpandable(false);
    localcaF2.setEnableAutoZoomShrink(true);
    localdRq1.bb(localcaF2);
    localcaF2.brn();
    aaE localaaE3 = new aaE();
    localaaE3.aJ();
    localaaE3.setElementMap(localcpa);
    localaaE3.setAttribute("text");
    localaaE3.setField("guildPoints");
    localcaF2.bb(localaaE3);
    localaaE3.brn();
    localaaE3.rV();
    caF localcaF3 = localcaF2;
    Jg localJg3 = localcaF3.getAppearance();
    localJg3.setElementMap(localcpa);
    localcaF2.bb(localJg3);
    localJg3.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(0, 3, 0, 0));
    localJg3.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg3.rV();
    localcaF2.rV();
    localdRq1.rV();
    localeR1.rV();
    eR localeR2 = new eR();
    localeR2.aJ();
    localeR2.setElementMap(localcpa);
    localbSJ.bb(localeR2);
    localeR2.brn();
    anQ localanQ3 = new anQ();
    localanQ3.aJ();
    localanQ3.setElementMap(localcpa);
    localeR2.bb(localanQ3);
    localanQ3.brn();
    bxx localbxx2 = new bxx();
    localbxx2.aJ();
    localbxx2.setElementMap(localcpa);
    localanQ3.bb(localbxx2);
    localbxx2.brn();
    aIB localaIB = new aIB();
    localaIB.aJ();
    localaIB.setElementMap(localcpa);
    localbxx2.bb(localaIB);
    localaIB.brn();
    localaIB.rV();
    localbxx2.rV();
    localanQ3.rV();
    dRq localdRq5 = dRq.checkOut();
    localdRq5.setElementMap(localcpa);
    localdRq5.setPrefSize(new Or(70, 0));
    localeR2.bb(localdRq5);
    localdRq5.brn();
    dRq localdRq6 = localdRq5;
    Jg localJg4 = localdRq6.getAppearance();
    localJg4.setElementMap(localcpa);
    localdRq5.bb(localJg4);
    localJg4.brn();
    ams localams2 = new ams();
    localams2.aJ();
    localams2.setElementMap(localcpa);
    localams2.setInsets(new Insets(0, 1, 0, 0));
    localams2.setColor(new bNa(0.94F, 0.86F, 0.66F, 0.8F));
    localJg4.bb(localams2);
    localams2.brn();
    localams2.rV();
    localJg4.rV();
    localdRq5.rV();
    localeR2.rV();
    localbSJ.rV();
    return localbSJ;
  }

  public bdj k(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    bSJ localbSJ = new bSJ();
    localbSJ.aJ();
    localbSJ.setElementMap(localcpa);
    localbSJ.setCellWidth(80);
    String str1 = "%conquest%";
    str1 = str1.replace("%conquest%", cBQ.cxL().mL("conquest"));
    localbSJ.setName(str1);
    localbSJ.setColumnId("conquestPoints");
    parambdj.bb(localbSJ);
    localbSJ.brn();
    eR localeR1 = new eR();
    localeR1.aJ();
    localeR1.setElementMap(localcpa);
    localbSJ.bb(localeR1);
    localeR1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localeR1.bb(localanQ1);
    localanQ1.brn();
    bxx localbxx1 = new bxx();
    localbxx1.aJ();
    localbxx1.setElementMap(localcpa);
    localanQ1.bb(localbxx1);
    localbxx1.brn();
    anE localanE1 = new anE();
    localanE1.aJ();
    localanE1.setElementMap(localcpa);
    localbxx1.bb(localanE1);
    localanE1.brn();
    localanE1.rV();
    localbxx1.rV();
    localanQ1.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    localdRq1.setPrefSize(new Or(80, 0));
    cCu localcCu = new cCu();
    localcCu.hg("popup(descriptionPopup)");
    localdRq1.setOnPopupDisplay(localcCu);
    localdRq1.setNonBlocking(false);
    jL localjL = new jL();
    localjL.hg("closePopup");
    localdRq1.setOnPopupHide(localjL);
    localeR1.bb(localdRq1);
    localdRq1.brn();
    String str2 = "descriptionPopup";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localanG);
    localanG.setAlign(aFG.ech);
    localanG.setHotSpotPosition(aFG.ecn);
    localdRq1.bb(localanG);
    localanG.brn();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setPrefSize(new Or(10, 0));
    localdRq2.setStyle("popup");
    localanG.bb(localdRq2);
    localdRq2.brn();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localaId1.setAlign(aFG.ech);
    localdRq2.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("visible");
    localaaE1.setField("description");
    localdRq2.bb(localaaE1);
    localaaE1.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localaaE1.bb(localanQ2);
    localanQ2.brn();
    anE localanE2 = new anE();
    localanE2.aJ();
    localanE2.setElementMap(localcpa);
    localanQ2.bb(localanE2);
    localanE2.brn();
    localanE2.rV();
    localanQ2.rV();
    localaaE1.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq3.setExpandable(false);
    localdRq2.bb(localdRq3);
    localdRq3.brn();
    aId localaId2 = aId.checkOut();
    localaId2.setHorizontal(false);
    localaId2.setAlign(aFG.ech);
    localdRq3.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("PopupInformation");
    String str3 = "%description%%colon%";
    str3 = str3.replace("%description%", cBQ.cxL().mL("description"));
    str3 = str3.replace("%colon%", cBQ.cxL().mL("colon"));
    localcaF1.setText(str3);
    localcaF1.setExpandable(false);
    localdRq3.bb(localcaF1);
    localcaF1.brn();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.ecj);
    localcaF1.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    localcaF1.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("PopupInformation");
    localcWk1.setMultiline(true);
    localcWk1.setMinWidth(300);
    localdRq3.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg1 = localcWk2.getAppearance();
    localJg1.setElementMap(localcpa);
    ((cwJ)localJg1).setAlignment(aFG.ecj);
    localcWk1.bb(localJg1);
    localJg1.brn();
    localJg1.rV();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("text");
    localaaE2.setField("description");
    localcWk1.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    localcWk1.rV();
    localdRq3.rV();
    localdRq2.rV();
    localanG.rV();
    dRq localdRq4 = localdRq1;
    Jg localJg2 = localdRq4.getAppearance();
    localJg2.setElementMap(localcpa);
    localdRq1.bb(localJg2);
    localJg2.brn();
    ams localams1 = new ams();
    localams1.aJ();
    localams1.setElementMap(localcpa);
    localams1.setInsets(new Insets(0, 1, 0, 0));
    localams1.setColor(new bNa(0.94F, 0.86F, 0.66F, 0.8F));
    localJg2.bb(localams1);
    localams1.brn();
    localams1.rV();
    localJg2.rV();
    aId localaId3 = aId.checkOut();
    localaId3.setAlign(aFG.eck);
    localdRq1.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    caF localcaF2 = new caF();
    localcaF2.aJ();
    localcaF2.setElementMap(localcpa);
    localcaF2.setStyle("blackBold");
    localcaF2.setNonBlocking(true);
    localcaF2.setMinWidth(60);
    localcaF2.setMaxWidth(60);
    localcaF2.setExpandable(false);
    localcaF2.setEnableAutoZoomShrink(true);
    localdRq1.bb(localcaF2);
    localcaF2.brn();
    aaE localaaE3 = new aaE();
    localaaE3.aJ();
    localaaE3.setElementMap(localcpa);
    localaaE3.setAttribute("text");
    localaaE3.setField("conquestPoints");
    localcaF2.bb(localaaE3);
    localaaE3.brn();
    localaaE3.rV();
    caF localcaF3 = localcaF2;
    Jg localJg3 = localcaF3.getAppearance();
    localJg3.setElementMap(localcpa);
    localcaF2.bb(localJg3);
    localJg3.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(0, 3, 0, 0));
    localJg3.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg3.rV();
    localcaF2.rV();
    localdRq1.rV();
    localeR1.rV();
    eR localeR2 = new eR();
    localeR2.aJ();
    localeR2.setElementMap(localcpa);
    localbSJ.bb(localeR2);
    localeR2.brn();
    anQ localanQ3 = new anQ();
    localanQ3.aJ();
    localanQ3.setElementMap(localcpa);
    localeR2.bb(localanQ3);
    localanQ3.brn();
    bxx localbxx2 = new bxx();
    localbxx2.aJ();
    localbxx2.setElementMap(localcpa);
    localanQ3.bb(localbxx2);
    localbxx2.brn();
    aIB localaIB = new aIB();
    localaIB.aJ();
    localaIB.setElementMap(localcpa);
    localbxx2.bb(localaIB);
    localaIB.brn();
    localaIB.rV();
    localbxx2.rV();
    localanQ3.rV();
    dRq localdRq5 = dRq.checkOut();
    localdRq5.setElementMap(localcpa);
    localdRq5.setPrefSize(new Or(60, 0));
    localeR2.bb(localdRq5);
    localdRq5.brn();
    dRq localdRq6 = localdRq5;
    Jg localJg4 = localdRq6.getAppearance();
    localJg4.setElementMap(localcpa);
    localdRq5.bb(localJg4);
    localJg4.brn();
    ams localams2 = new ams();
    localams2.aJ();
    localams2.setElementMap(localcpa);
    localams2.setInsets(new Insets(0, 1, 0, 0));
    localams2.setColor(new bNa(0.94F, 0.86F, 0.66F, 0.8F));
    localJg4.bb(localams2);
    localams2.brn();
    localams2.rV();
    localJg4.rV();
    localdRq5.rV();
    localeR2.rV();
    localbSJ.rV();
    return localbSJ;
  }

  public bdj l(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    aId localaId1 = aId.checkOut();
    localaId1.setAlign(aFG.eck);
    localdRq1.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dRq localdRq2 = localdRq1;
    Jg localJg = localdRq2.getAppearance();
    localJg.setElementMap(localcpa);
    localdRq1.bb(localJg);
    localJg.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(0, 10, 0, 10));
    localJg.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg.rV();
    biy localbiy1 = new biy();
    localbiy1.aJ();
    localbiy1.setElementMap(localcpa);
    localbiy1.setExpandable(false);
    localbiy1.setStyle("CharacterCreationLeftArrow");
    csA localcsA1 = new csA();
    localcsA1.hg("wakfu.guildLadder:previousPage");
    localbiy1.setOnClick(localcsA1);
    localdRq1.bb(localbiy1);
    localbiy1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("enabled");
    localNK1.setName("guildLadder");
    localNK1.setField("currentPage");
    localbiy1.bb(localNK1);
    localNK1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localNK1.bb(localanQ1);
    localanQ1.brn();
    dDu localdDu1 = new dDu();
    localdDu1.aJ();
    localdDu1.setElementMap(localcpa);
    localanQ1.bb(localdDu1);
    localdDu1.brn();
    bSP localbSP1 = new bSP();
    localbSP1.aJ();
    localbSP1.setElementMap(localcpa);
    localbSP1.setValue("1");
    localdDu1.bb(localbSP1);
    localbSP1.brn();
    localbSP1.rV();
    localdDu1.rV();
    localanQ1.rV();
    localNK1.rV();
    localbiy1.rV();
    dAS localdAS1 = new dAS();
    localdAS1.aJ();
    localdAS1.setElementMap(localcpa);
    localdRq1.bb(localdAS1);
    localdAS1.brn();
    localdAS1.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq3.setExpandable(false);
    localdRq1.bb(localdRq3);
    localdRq3.brn();
    aId localaId2 = aId.checkOut();
    localaId2.setAlign(aFG.eck);
    localdRq3.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("StyledBold16Dark");
    localcWk1.setExpandable(false);
    localdRq3.bb(localcWk1);
    localcWk1.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setAttribute("text");
    localNK2.setName("guildLadder");
    localNK2.setField("currentPage");
    localcWk1.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localcWk1.rV();
    cWk localcWk2 = new cWk();
    localcWk2.aJ();
    localcWk2.setElementMap(localcpa);
    localcWk2.setStyle("StyledBold16Dark");
    localcWk2.setText("/");
    localcWk2.setExpandable(false);
    localdRq3.bb(localcWk2);
    localcWk2.brn();
    localcWk2.rV();
    cWk localcWk3 = new cWk();
    localcWk3.aJ();
    localcWk3.setElementMap(localcpa);
    localcWk3.setStyle("StyledBold16Dark");
    localcWk3.setExpandable(false);
    localdRq3.bb(localcWk3);
    localcWk3.brn();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setAttribute("text");
    localNK3.setName("guildLadder");
    localNK3.setField("totalPage");
    localcWk3.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    localcWk3.rV();
    localdRq3.rV();
    dAS localdAS2 = new dAS();
    localdAS2.aJ();
    localdAS2.setElementMap(localcpa);
    localdRq1.bb(localdAS2);
    localdAS2.brn();
    localdAS2.rV();
    biy localbiy2 = new biy();
    localbiy2.aJ();
    localbiy2.setElementMap(localcpa);
    localbiy2.setExpandable(false);
    localbiy2.setStyle("CharacterCreationRightArrow");
    csA localcsA2 = new csA();
    localcsA2.hg("wakfu.guildLadder:nextPage");
    localbiy2.setOnClick(localcsA2);
    localdRq1.bb(localbiy2);
    localbiy2.brn();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa);
    localNK4.setAttribute("enabled");
    localNK4.setName("guildLadder");
    localNK4.setField("currentPage");
    localbiy2.bb(localNK4);
    localNK4.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localNK4.bb(localanQ2);
    localanQ2.brn();
    dDu localdDu2 = new dDu();
    localdDu2.aJ();
    localdDu2.setElementMap(localcpa);
    localanQ2.bb(localdDu2);
    localdDu2.brn();
    bSP localbSP2 = new bSP();
    localbSP2.aJ();
    localbSP2.setElementMap(localcpa);
    localdDu2.bb(localbSP2);
    localbSP2.brn();
    NK localNK5 = NK.checkOut();
    localNK5.setElementMap(localcpa);
    localNK5.setAttribute("value");
    localNK5.setName("guildLadder");
    localNK5.setField("totalPage");
    localbSP2.bb(localNK5);
    localNK5.brn();
    localNK5.rV();
    localbSP2.rV();
    localdDu2.rV();
    localanQ2.rV();
    localNK4.rV();
    localbiy2.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj m(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    String str = "closeButton";
    biy localbiy1 = new biy();
    localbiy1.aJ();
    localbiy1.setElementMap(localcpa);
    if ((localcpa != null) && (str != null))
      localcpa.a(str, localbiy1);
    localbiy1.setStyle("backgroundDisplayClose");
    csA localcsA = new csA();
    localcsA.hg("unloadDialog");
    localbiy1.setOnClick(localcsA);
    parambdj.bb(localbiy1);
    localbiy1.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setAlign(ajb.dhV);
    localbiy1.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    biy localbiy2 = localbiy1;
    Jg localJg = localbiy2.getAppearance();
    localJg.setElementMap(localcpa);
    localbiy1.bb(localJg);
    localJg.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(10, 0, 0, 20));
    localJg.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg.rV();
    localbiy1.rV();
    return localbiy1;
  }
}