import java.awt.Insets;
import java.util.Stack;

public class dtS
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setStyle("passport");
    localdRq1.setNonBlocking(false);
    localdRq1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(663, 450));
    localcwP1.setAlign(ajb.dhZ);
    localcwP1.setInitValue(true);
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    czO localczO1 = new czO();
    localczO1.aJ();
    localdRq1.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    biy localbiy = new biy();
    localbiy.aJ();
    localbiy.setElementMap(localcpa);
    localbiy.setStyle("backgroundDisplayClose");
    csA localcsA = new csA();
    localcsA.hg("unloadDialog");
    localbiy.setOnClick(localcsA);
    localdRq1.bb(localbiy);
    localbiy.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.dhV);
    localcwP2.setXOffset(-40);
    localcwP2.setYOffset(-35);
    localbiy.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    localbiy.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setSize(new Or(50.0F, 100.0F));
    localcwP3.setAlign(ajb.dhY);
    localdRq2.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    czO localczO2 = new czO();
    localczO2.aJ();
    localdRq2.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localdRq2.bb(localczv1);
    localczv1.brn();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setSize(new Or(107, 99));
    localcwP4.setAlign(ajb.dhR);
    localcwP4.setYOffset(-155);
    localcwP4.setXOffset(40);
    localczv1.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setName("localPlayer");
    localNK1.setAttribute("visible");
    localNK1.setField("nation/isPassportActive");
    localczv1.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    czv localczv2 = localczv1;
    Jg localJg1 = localczv2.getAppearance();
    localJg1.setElementMap(localcpa);
    localczv1.bb(localJg1);
    localJg1.brn();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localJg1.bb(localaAR);
    localaAR.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("localPlayer");
    localNK2.setAttribute("texture");
    localNK2.setField("nation/passportStampIconUrl");
    localaAR.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localaAR.rV();
    localJg1.rV();
    localczv1.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("whiteTitle");
    localdRq2.bb(localcaF1);
    localcaF1.brn();
    cwP localcwP5 = new cwP();
    localcwP5.aJ();
    localcwP5.setElementMap(localcpa);
    localcwP5.setSize(new Or(190, 30));
    localcwP5.setAlign(ajb.dhV);
    localcwP5.setYOffset(-58);
    localcwP5.setXOffset(-10);
    localcaF1.bb(localcwP5);
    localcwP5.brn();
    localcwP5.rV();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setName("localPlayer");
    localNK3.setAttribute("text");
    localNK3.setField("name");
    localcaF1.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    caF localcaF2 = localcaF1;
    Jg localJg2 = localcaF2.getAppearance();
    localJg2.setElementMap(localcpa);
    localcaF1.bb(localJg2);
    localJg2.brn();
    cAf localcAf = cAf.checkOut();
    localcAf.setElementMap(localcpa);
    localcAf.setName("text");
    localcAf.setColor(new bNa(1.0F, 0.9F, 0.75F, 1.0F));
    localJg2.bb(localcAf);
    localcAf.brn();
    localcAf.rV();
    localJg2.rV();
    localcaF1.rV();
    ddG localddG1 = new ddG();
    localddG1.aJ();
    localddG1.setElementMap(localcpa);
    localddG1.setStyle("yellow");
    localddG1.setPrefSize(new Or(180, 0));
    localddG1.setExpandable(false);
    dTZ localdTZ = new dTZ();
    localdTZ.hg("wakfu.passport:selectTitle");
    localddG1.setOnListSelectionChange(localdTZ);
    localdRq2.bb(localddG1);
    localddG1.brn();
    cwP localcwP6 = new cwP();
    localcwP6.aJ();
    localcwP6.setElementMap(localcpa);
    localcwP6.setSize(new Or(180, -2));
    localcwP6.setAlign(ajb.dhV);
    localcwP6.setXOffset(-10);
    localcwP6.setYOffset(-90);
    localddG1.bb(localcwP6);
    localcwP6.brn();
    localcwP6.rV();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa);
    localNK4.setAttribute("content");
    localNK4.setName("localPlayer");
    localNK4.setField("availableTitles");
    localddG1.bb(localNK4);
    localNK4.brn();
    localNK4.rV();
    NK localNK5 = NK.checkOut();
    localNK5.setElementMap(localcpa);
    localNK5.setAttribute("selectedValue");
    localNK5.setName("localPlayer");
    localNK5.setField("currentTitleObject");
    localddG1.bb(localNK5);
    localNK5.brn();
    localNK5.rV();
    ddG localddG2 = localddG1;
    Jg localJg3 = localddG2.getAppearance();
    localJg3.setElementMap(localcpa);
    localddG1.bb(localJg3);
    localJg3.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 0, 0, 0));
    localJg3.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg3.rV();
    axU localaxU = new axU();
    localaxU.aJ();
    localaxU.setElementMap(localcpa);
    localddG1.bb(localaxU);
    localaxU.brn();
    eR localeR1 = new eR();
    localeR1.aJ();
    localeR1.setElementMap(localcpa);
    localaxU.bb(localeR1);
    localeR1.brn();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setPrefSize(new Or(140, 0));
    localcaF3.setExpandable(false);
    localcaF3.setNonBlocking(true);
    localcaF3.setStyle("smalltitle");
    localcaF3.setMinWidth(1);
    localcaF3.setMaxWidth(140);
    localcaF3.setEnableAutoZoomShrink(true);
    localeR1.bb(localcaF3);
    localcaF3.brn();
    caF localcaF4 = localcaF3;
    Jg localJg4 = localcaF4.getAppearance();
    localJg4.setElementMap(localcpa);
    ((cwJ)localJg4).setAlign(aFG.eck);
    localcaF3.bb(localJg4);
    localJg4.brn();
    localJg4.rV();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("text");
    localaaE1.setField("description");
    localcaF3.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    localcaF3.rV();
    localeR1.rV();
    localaxU.rV();
    ccG localccG = new ccG();
    localccG.aJ();
    localccG.setElementMap(localcpa);
    localccG.setHorizontal(false);
    localccG.setCellSize(new Or(350, 16));
    localccG.setPrefSize(new Or(365, 160));
    localddG1.bb(localccG);
    localccG.brn();
    eR localeR2 = new eR();
    localeR2.aJ();
    localeR2.setElementMap(localcpa);
    localccG.bb(localeR2);
    localeR2.brn();
    caF localcaF5 = new caF();
    localcaF5.aJ();
    localcaF5.setElementMap(localcpa);
    localcaF5.setStyle("smallTitle");
    localcaF5.setNonBlocking(true);
    localeR2.bb(localcaF5);
    localcaF5.brn();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("text");
    localaaE2.setField("description");
    localcaF5.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    caF localcaF6 = localcaF5;
    Jg localJg5 = localcaF6.getAppearance();
    localJg5.setElementMap(localcpa);
    localcaF5.bb(localJg5);
    localJg5.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 10, 0, 0));
    localJg5.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg5.rV();
    localcaF5.rV();
    localeR2.rV();
    localccG.rV();
    localddG1.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq3.setNeedsScissor(true);
    localdRq2.bb(localdRq3);
    localdRq3.brn();
    cwP localcwP7 = new cwP();
    localcwP7.aJ();
    localcwP7.setElementMap(localcpa);
    localcwP7.setSize(new Or(65, 80));
    localcwP7.setAlign(ajb.dhR);
    localcwP7.setYOffset(-55);
    localcwP7.setXOffset(58);
    localdRq3.bb(localcwP7);
    localcwP7.brn();
    localcwP7.rV();
    String str1 = "localPlayerDisplay";
    auC localauC = new auC();
    localauC.aJ();
    localauC.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localauC);
    localauC.setPrefSize(new Or(100, 0));
    localauC.setOffsetY(-120.0F);
    localauC.setOffsetX(-15.0F);
    localauC.setScale(2.2F);
    localauC.setAnimName("AnimStatique");
    localauC.setDirection(2);
    localdRq3.bb(localauC);
    localauC.brn();
    NK localNK6 = NK.checkOut();
    localNK6.setElementMap(localcpa);
    localNK6.setName("localPlayer");
    localNK6.setAttribute("animatedElement");
    localNK6.setField("actorDescriptorLibrary");
    localauC.bb(localNK6);
    localNK6.brn();
    localNK6.rV();
    NK localNK7 = NK.checkOut();
    localNK7.setElementMap(localcpa);
    localNK7.setName("localPlayer");
    localNK7.setAttribute("equipment");
    localNK7.setField("actorEquipment");
    localauC.bb(localNK7);
    localNK7.brn();
    localNK7.rV();
    localauC.rV();
    localdRq3.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq2.bb(localdRq4);
    localdRq4.brn();
    cwP localcwP8 = new cwP();
    localcwP8.aJ();
    localcwP8.setElementMap(localcpa);
    localcwP8.setSize(new Or(100.0F, 120));
    localcwP8.setAlign(ajb.dhT);
    localcwP8.setYOffset(-155);
    localdRq4.bb(localcwP8);
    localcwP8.brn();
    localcwP8.rV();
    dRq localdRq5 = localdRq4;
    Jg localJg6 = localdRq5.getAppearance();
    localJg6.setElementMap(localcpa);
    localdRq4.bb(localJg6);
    localJg6.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 145, 0, 10));
    localJg6.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg6.rV();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(false);
    localaId.setAlign(aFG.ech);
    localdRq4.bb(localaId);
    localaId.brn();
    localaId.rV();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq6.setExpandable(false);
    localdRq4.bb(localdRq6);
    localdRq6.brn();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("StyledBoldDark12");
    localdRq6.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg7 = localcWk2.getAppearance();
    localJg7.setElementMap(localcpa);
    localcWk1.bb(localJg7);
    localJg7.brn();
    NK localNK8 = NK.checkOut();
    localNK8.setElementMap(localcpa);
    localNK8.setName("localPlayer");
    localNK8.setAttribute("textColor");
    localNK8.setField("nation/nationColor");
    localJg7.bb(localNK8);
    localNK8.brn();
    localNK8.rV();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(0, 0, 2, 0));
    localJg7.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg7.rV();
    NK localNK9 = NK.checkOut();
    localNK9.setElementMap(localcpa);
    localNK9.setName("localPlayer");
    localNK9.setAttribute("text");
    localNK9.setField("nation/nationName");
    localcWk1.bb(localNK9);
    localNK9.brn();
    localNK9.rV();
    localcWk1.rV();
    czv localczv3 = new czv();
    localczv3.aJ();
    localczv3.setElementMap(localcpa);
    localczv3.setStyle("questionMark");
    localczv3.setExpandable(false);
    cCu localcCu = new cCu();
    localcCu.hg("popup(descNationChangePopup)");
    localczv3.setOnPopupDisplay(localcCu);
    jL localjL = new jL();
    localjL.hg("closePopup");
    localczv3.setOnPopupHide(localjL);
    localdRq6.bb(localczv3);
    localczv3.brn();
    String str2 = "descNationChangePopup";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localanG);
    localanG.setAlign(aFG.ecl);
    localanG.setHotSpotPosition(aFG.ecj);
    localczv3.bb(localanG);
    localanG.brn();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localdRq7.setPrefSize(new Or(10, 0));
    localdRq7.setStyle("popup");
    localanG.bb(localdRq7);
    localdRq7.brn();
    cWk localcWk3 = new cWk();
    localcWk3.aJ();
    localcWk3.setElementMap(localcpa);
    localcWk3.setStyle("white");
    String str3 = "%passport.ChangeTooltip%";
    str3 = str3.replace("%passport.ChangeTooltip%", cBQ.cxL().mL("passport.ChangeTooltip"));
    localcWk3.setText(str3);
    localcWk3.setMinWidth(1);
    localcWk3.setMaxWidth(250);
    localdRq7.bb(localcWk3);
    localcWk3.brn();
    cWk localcWk4 = localcWk3;
    Jg localJg8 = localcWk4.getAppearance();
    localJg8.setElementMap(localcpa);
    ((cwJ)localJg8).setAlignment(aFG.ecj);
    localcWk3.bb(localJg8);
    localJg8.brn();
    localJg8.rV();
    localcWk3.rV();
    localdRq7.rV();
    localanG.rV();
    czv localczv4 = localczv3;
    Jg localJg9 = localczv4.getAppearance();
    localJg9.setElementMap(localcpa);
    localczv3.bb(localJg9);
    localJg9.brn();
    bmv localbmv5 = bmv.checkOut();
    localbmv5.setElementMap(localcpa);
    localbmv5.setInsets(new Insets(0, 0, 0, 10));
    localJg9.bb(localbmv5);
    localbmv5.brn();
    localbmv5.rV();
    localJg9.rV();
    localczv3.rV();
    localdRq6.rV();
    caF localcaF7 = new caF();
    localcaF7.aJ();
    localcaF7.setElementMap(localcpa);
    localcaF7.setStyle("smallTitle");
    localcaF7.setExpandable(false);
    String str4 = "%nation.rank%";
    str4 = str4.replace("%nation.rank%", cBQ.cxL().mL("nation.rank"));
    localcaF7.setText(str4);
    localdRq4.bb(localcaF7);
    localcaF7.brn();
    localcaF7.rV();
    czv localczv5 = new czv();
    localczv5.aJ();
    localczv5.setElementMap(localcpa);
    localczv5.setStyle("TiledScrollBottom");
    localczv5.setExpandable(false);
    localczv5.setDisplaySize(new Or(180, 4));
    localdRq4.bb(localczv5);
    localczv5.brn();
    localczv5.rV();
    cWk localcWk5 = new cWk();
    localcWk5.aJ();
    localcWk5.setElementMap(localcpa);
    localcWk5.setStyle("StyledBold12");
    localcWk5.setExpandable(false);
    localdRq4.bb(localcWk5);
    localcWk5.brn();
    NK localNK10 = NK.checkOut();
    localNK10.setElementMap(localcpa);
    localNK10.setName("localPlayer");
    localNK10.setAttribute("text");
    localNK10.setField("nation/nationRankDescription");
    localcWk5.bb(localNK10);
    localNK10.brn();
    localNK10.rV();
    localcWk5.rV();
    localdRq4.rV();
    czv localczv6 = new czv();
    localczv6.aJ();
    localczv6.setElementMap(localcpa);
    localdRq2.bb(localczv6);
    localczv6.brn();
    cwP localcwP9 = new cwP();
    localcwP9.aJ();
    localcwP9.setElementMap(localcpa);
    localcwP9.setSize(new Or(-2, -2));
    localcwP9.setAlign(ajb.dhR);
    localcwP9.setYOffset(-120);
    localcwP9.setXOffset(100);
    localczv6.bb(localcwP9);
    localcwP9.brn();
    localcwP9.rV();
    a(localczv6);
    localczv6.rV();
    b(localdRq2);
    localdRq2.rV();
    d(localdRq1);
    localdRq1.rV();
    return localdRq1;
  }

  public bdj a(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setName("localPlayer");
    localNK.setAttribute("style");
    localNK.setField("nation/isPassportActive");
    parambdj.bb(localNK);
    localNK.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localanQ.setValue("passportValid");
    localanQ.setElseValue("passportInvalid");
    localNK.bb(localanQ);
    localanQ.brn();
    cOk localcOk = new cOk();
    localcOk.aJ();
    localcOk.setElementMap(localcpa);
    localanQ.bb(localcOk);
    localcOk.brn();
    localcOk.rV();
    localanQ.rV();
    localNK.rV();
    return localNK;
  }

  public bdj b(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(100.0F, 140));
    localcwP.setAlign(ajb.dhT);
    localcwP.setYOffset(-255);
    localdRq1.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    dRq localdRq2 = localdRq1;
    Jg localJg1 = localdRq2.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq1.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 50, 0, 10));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localaId1.setAlign(aFG.ech);
    localdRq1.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq3.setExpandable(false);
    localdRq1.bb(localdRq3);
    localdRq3.brn();
    aId localaId2 = aId.checkOut();
    localaId2.setAlign(aFG.ecj);
    localdRq3.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("smallTitle");
    localcaF1.setExpandable(false);
    String str1 = "%citizen.score%";
    str1 = str1.replace("%citizen.score%", cBQ.cxL().mL("citizen.score"));
    localcaF1.setText(str1);
    localdRq3.bb(localcaF1);
    localcaF1.brn();
    localcaF1.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("StyledBold12");
    localcWk1.setExpandable(false);
    localdRq3.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg2 = localcWk2.getAppearance();
    localJg2.setElementMap(localcpa);
    localcWk1.bb(localJg2);
    localJg2.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setName("localPlayer");
    localNK1.setAttribute("textColor");
    localNK1.setField("nation/nationColor");
    localJg2.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    localJg2.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setField("nation/nativeNationCitizenScore");
    localNK2.setName("localPlayer");
    localNK2.setAttribute("visible");
    localcWk1.bb(localNK2);
    localNK2.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localNK2.bb(localanQ1);
    localanQ1.brn();
    anE localanE1 = new anE();
    localanE1.aJ();
    localanE1.setElementMap(localcpa);
    localanQ1.bb(localanE1);
    localanE1.brn();
    localanE1.rV();
    localanQ1.rV();
    localNK2.rV();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setField("nation/nativeNationCitizenScore/score");
    localNK3.setName("localPlayer");
    localNK3.setAttribute("text");
    localcWk1.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    localcWk1.rV();
    dAS localdAS = new dAS();
    localdAS.aJ();
    localdAS.setElementMap(localcpa);
    localdRq3.bb(localdAS);
    localdAS.brn();
    localdAS.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setStyle("questionMark");
    localczv1.setExpandable(false);
    cCu localcCu = new cCu();
    localcCu.hg("popup(descCitizenPointsPopup)");
    localczv1.setOnPopupDisplay(localcCu);
    jL localjL = new jL();
    localjL.hg("closePopup");
    localczv1.setOnPopupHide(localjL);
    localdRq3.bb(localczv1);
    localczv1.brn();
    String str2 = "descCitizenPointsPopup";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localanG);
    localanG.setAlign(aFG.ech);
    localanG.setHotSpotPosition(aFG.ecn);
    localczv1.bb(localanG);
    localanG.brn();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setPrefSize(new Or(10, 0));
    localdRq4.setStyle("popup");
    localanG.bb(localdRq4);
    localdRq4.brn();
    cWk localcWk3 = new cWk();
    localcWk3.aJ();
    localcWk3.setElementMap(localcpa);
    localcWk3.setStyle("white");
    String str3 = "%nation.citizenship.points.explaination%";
    str3 = str3.replace("%nation.citizenship.points.explaination%", cBQ.cxL().mL("nation.citizenship.points.explaination"));
    localcWk3.setText(str3);
    localcWk3.setMinWidth(1);
    localcWk3.setMaxWidth(250);
    localdRq4.bb(localcWk3);
    localcWk3.brn();
    cWk localcWk4 = localcWk3;
    Jg localJg3 = localcWk4.getAppearance();
    localJg3.setElementMap(localcpa);
    ((cwJ)localJg3).setAlignment(aFG.ecj);
    localcWk3.bb(localJg3);
    localJg3.brn();
    localJg3.rV();
    localcWk3.rV();
    localdRq4.rV();
    localanG.rV();
    czv localczv2 = localczv1;
    Jg localJg4 = localczv2.getAppearance();
    localJg4.setElementMap(localcpa);
    localczv1.bb(localJg4);
    localJg4.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 0, 0, 10));
    localJg4.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg4.rV();
    localczv1.rV();
    localdRq3.rV();
    czv localczv3 = new czv();
    localczv3.aJ();
    localczv3.setElementMap(localcpa);
    localczv3.setStyle("TiledScrollBottom");
    localczv3.setExpandable(false);
    localczv3.setDisplaySize(new Or(280, 4));
    localdRq1.bb(localczv3);
    localczv3.brn();
    localczv3.rV();
    dRq localdRq5 = dRq.checkOut();
    localdRq5.setElementMap(localcpa);
    localdRq5.setExpandable(false);
    localdRq1.bb(localdRq5);
    localdRq5.brn();
    dRq localdRq6 = localdRq5;
    Jg localJg5 = localdRq6.getAppearance();
    localJg5.setElementMap(localcpa);
    localdRq5.bb(localJg5);
    localJg5.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(5, 0, 0, 0));
    localJg5.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg5.rV();
    aId localaId3 = aId.checkOut();
    localaId3.setAlign(aFG.ecj);
    localdRq5.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    caF localcaF2 = new caF();
    localcaF2.aJ();
    localcaF2.setElementMap(localcpa);
    localcaF2.setStyle("smallTitle");
    localcaF2.setExpandable(false);
    String str4 = "%citizen.status%";
    str4 = str4.replace("%citizen.status%", cBQ.cxL().mL("citizen.status"));
    localcaF2.setText(str4);
    localdRq5.bb(localcaF2);
    localcaF2.brn();
    localcaF2.rV();
    cWk localcWk5 = new cWk();
    localcWk5.aJ();
    localcWk5.setElementMap(localcpa);
    localcWk5.setStyle("StyledBold12");
    localdRq5.bb(localcWk5);
    localcWk5.brn();
    cWk localcWk6 = localcWk5;
    Jg localJg6 = localcWk6.getAppearance();
    localJg6.setElementMap(localcpa);
    localcWk5.bb(localJg6);
    localJg6.brn();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa);
    localNK4.setName("localPlayer");
    localNK4.setAttribute("textColor");
    localNK4.setField("nation/nationColor");
    localJg6.bb(localNK4);
    localNK4.brn();
    localNK4.rV();
    localJg6.rV();
    NK localNK5 = NK.checkOut();
    localNK5.setElementMap(localcpa);
    localNK5.setField("nation/nativeNationCitizenScore");
    localNK5.setName("localPlayer");
    localNK5.setAttribute("visible");
    localcWk5.bb(localNK5);
    localNK5.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localNK5.bb(localanQ2);
    localanQ2.brn();
    anE localanE2 = new anE();
    localanE2.aJ();
    localanE2.setElementMap(localcpa);
    localanQ2.bb(localanE2);
    localanE2.brn();
    localanE2.rV();
    localanQ2.rV();
    localNK5.rV();
    NK localNK6 = NK.checkOut();
    localNK6.setElementMap(localcpa);
    localNK6.setField("nation/nativeNationCitizenScore/rankDescription");
    localNK6.setName("localPlayer");
    localNK6.setAttribute("text");
    localcWk5.bb(localNK6);
    localNK6.brn();
    localNK6.rV();
    localcWk5.rV();
    localdRq5.rV();
    czv localczv4 = new czv();
    localczv4.aJ();
    localczv4.setElementMap(localcpa);
    localczv4.setStyle("TiledScrollBottom");
    localczv4.setExpandable(false);
    localczv4.setDisplaySize(new Or(280, 4));
    localdRq1.bb(localczv4);
    localczv4.brn();
    localczv4.rV();
    ccG localccG = new ccG();
    localccG.aJ();
    localccG.setElementMap(localcpa);
    localccG.setCellSize(new Or(100.0F, 14));
    localccG.setHorizontal(false);
    localccG.setAutoIdealSize(true);
    localccG.setIdealSizeMinColumns(1);
    localccG.setIdealSizeMaxColumns(1);
    localccG.setIdealSizeMinRows(1);
    localccG.setIdealSizeMaxRows(8);
    localdRq1.bb(localccG);
    localccG.brn();
    eR localeR = new eR();
    localeR.aJ();
    localeR.setElementMap(localcpa);
    localccG.bb(localeR);
    localeR.brn();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localeR.bb(localdRq7);
    localdRq7.brn();
    aId localaId4 = aId.checkOut();
    localaId4.setHorizontal(false);
    localdRq7.bb(localaId4);
    localaId4.brn();
    localaId4.rV();
    cWk localcWk7 = new cWk();
    localcWk7.aJ();
    localcWk7.setElementMap(localcpa);
    localcWk7.setStyle("StyledBold12");
    localdRq7.bb(localcWk7);
    localcWk7.brn();
    aaE localaaE = new aaE();
    localaaE.aJ();
    localaaE.setElementMap(localcpa);
    localaaE.setAttribute("text");
    localaaE.setField("name");
    localcWk7.bb(localaaE);
    localaaE.brn();
    localaaE.rV();
    localcWk7.rV();
    czv localczv5 = new czv();
    localczv5.aJ();
    localczv5.setElementMap(localcpa);
    localczv5.setStyle("TiledScrollBottom");
    localczv5.setExpandable(false);
    localczv5.setDisplaySize(new Or(280, 1));
    localdRq7.bb(localczv5);
    localczv5.brn();
    localczv5.rV();
    localdRq7.rV();
    localeR.rV();
    localccG.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj d(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(50.0F, 100.0F));
    localcwP1.setAlign(ajb.dia);
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(false);
    localaId.setAlign(aFG.ech);
    localdRq1.bb(localaId);
    localaId.brn();
    localaId.rV();
    dRq localdRq2 = localdRq1;
    Jg localJg1 = localdRq2.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq1.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(63, 10, 25, 35));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq3.setExpandable(false);
    localdRq1.bb(localdRq3);
    localdRq3.brn();
    dRq localdRq4 = localdRq3;
    Jg localJg2 = localdRq4.getAppearance();
    localJg2.setElementMap(localcpa);
    localdRq3.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 10, 10, 0));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("whiteTitle");
    String str1 = "%nation.bonus%";
    str1 = str1.replace("%nation.bonus%", cBQ.cxL().mL("nation.bonus"));
    localcaF1.setText(str1);
    localdRq3.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg3 = localcaF2.getAppearance();
    localJg3.setElementMap(localcpa);
    localcaF1.bb(localJg3);
    localJg3.brn();
    cAf localcAf1 = cAf.checkOut();
    localcAf1.setElementMap(localcpa);
    localcAf1.setName("text");
    localcAf1.setColor(new bNa(1.0F, 0.9F, 0.75F, 1.0F));
    localJg3.bb(localcAf1);
    localcAf1.brn();
    localcAf1.rV();
    localJg3.rV();
    localcaF1.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setStyle("questionMark");
    localczv1.setExpandable(false);
    cCu localcCu1 = new cCu();
    localcCu1.hg("popup(descNationBuffsPopup)");
    localczv1.setOnPopupDisplay(localcCu1);
    jL localjL1 = new jL();
    localjL1.hg("closePopup");
    localczv1.setOnPopupHide(localjL1);
    localdRq3.bb(localczv1);
    localczv1.brn();
    String str2 = "descNationBuffsPopup";
    anG localanG1 = new anG();
    localanG1.aJ();
    localanG1.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localanG1);
    localanG1.setAlign(aFG.ech);
    localanG1.setHotSpotPosition(aFG.ecn);
    localczv1.bb(localanG1);
    localanG1.brn();
    dRq localdRq5 = dRq.checkOut();
    localdRq5.setElementMap(localcpa);
    localdRq5.setPrefSize(new Or(10, 0));
    localdRq5.setStyle("popup");
    localanG1.bb(localdRq5);
    localdRq5.brn();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("white");
    String str3 = "%nation.buffs.explaination%";
    str3 = str3.replace("%nation.buffs.explaination%", cBQ.cxL().mL("nation.buffs.explaination"));
    localcWk1.setText(str3);
    localcWk1.setMinWidth(1);
    localcWk1.setMaxWidth(250);
    localdRq5.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg4 = localcWk2.getAppearance();
    localJg4.setElementMap(localcpa);
    ((cwJ)localJg4).setAlignment(aFG.ecj);
    localcWk1.bb(localJg4);
    localJg4.brn();
    localJg4.rV();
    localcWk1.rV();
    localdRq5.rV();
    localanG1.rV();
    czv localczv2 = localczv1;
    Jg localJg5 = localczv2.getAppearance();
    localJg5.setElementMap(localcpa);
    localczv1.bb(localJg5);
    localJg5.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 0, 0, 30));
    localJg5.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg5.rV();
    localczv1.rV();
    localdRq3.rV();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq6.setStyle("encyclopediaSplashTitle");
    localdRq6.setExpandable(false);
    localdRq6.setVisible(false);
    localdRq1.bb(localdRq6);
    localdRq6.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setName("passportViewMode");
    localNK1.setAttribute("visible");
    localdRq6.bb(localNK1);
    localNK1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localNK1.bb(localanQ1);
    localanQ1.brn();
    boQ localboQ = new boQ();
    localboQ.aJ();
    localboQ.setElementMap(localcpa);
    localanQ1.bb(localboQ);
    localboQ.brn();
    bSP localbSP1 = new bSP();
    localbSP1.aJ();
    localbSP1.setElementMap(localcpa);
    localbSP1.setValue("0");
    localboQ.bb(localbSP1);
    localbSP1.brn();
    localbSP1.rV();
    bSP localbSP2 = new bSP();
    localbSP2.aJ();
    localbSP2.setElementMap(localcpa);
    localbSP2.setValue("1");
    localboQ.bb(localbSP2);
    localbSP2.brn();
    localbSP2.rV();
    localboQ.rV();
    localanQ1.rV();
    localNK1.rV();
    dRq localdRq7 = localdRq6;
    Jg localJg6 = localdRq7.getAppearance();
    localJg6.setElementMap(localcpa);
    localdRq6.bb(localJg6);
    localJg6.brn();
    cuR localcuR = new cuR();
    localcuR.aJ();
    localcuR.setElementMap(localcpa);
    localcuR.setInsets(new Insets(6, 10, 7, 10));
    localJg6.bb(localcuR);
    localcuR.brn();
    localcuR.rV();
    localJg6.rV();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setStyle("smallTitle");
    String str4 = "%protector.buffs.mdc.title%";
    str4 = str4.replace("%protector.buffs.mdc.title%", cBQ.cxL().mL("protector.buffs.mdc.title"));
    localcaF3.setText(str4);
    localdRq6.bb(localcaF3);
    localcaF3.brn();
    caF localcaF4 = localcaF3;
    Jg localJg7 = localcaF4.getAppearance();
    localJg7.setElementMap(localcpa);
    localcaF3.bb(localJg7);
    localJg7.brn();
    cAf localcAf2 = cAf.checkOut();
    localcAf2.setElementMap(localcpa);
    localcAf2.setColor(new bNa(1.0F, 1.0F, 1.0F, 1.0F));
    localcAf2.setName("text");
    localJg7.bb(localcAf2);
    localcAf2.brn();
    localcAf2.rV();
    localJg7.rV();
    localcaF3.rV();
    czv localczv3 = new czv();
    localczv3.aJ();
    localczv3.setElementMap(localcpa);
    localczv3.setStyle("questionMark");
    localczv3.setExpandable(false);
    cCu localcCu2 = new cCu();
    localcCu2.hg("popup(descBuffsPopup)");
    localczv3.setOnPopupDisplay(localcCu2);
    jL localjL2 = new jL();
    localjL2.hg("closePopup");
    localczv3.setOnPopupHide(localjL2);
    localdRq6.bb(localczv3);
    localczv3.brn();
    String str5 = "descBuffsPopup";
    anG localanG2 = new anG();
    localanG2.aJ();
    localanG2.setElementMap(localcpa);
    if ((localcpa != null) && (str5 != null))
      localcpa.a(str5, localanG2);
    localanG2.setAlign(aFG.ech);
    localanG2.setHotSpotPosition(aFG.ecn);
    localczv3.bb(localanG2);
    localanG2.brn();
    dRq localdRq8 = dRq.checkOut();
    localdRq8.setElementMap(localcpa);
    localdRq8.setPrefSize(new Or(10, 0));
    localdRq8.setStyle("popup");
    localanG2.bb(localdRq8);
    localdRq8.brn();
    cWk localcWk3 = new cWk();
    localcWk3.aJ();
    localcWk3.setElementMap(localcpa);
    localcWk3.setStyle("white");
    String str6 = "%protector.buffs.mdc.explaination%";
    str6 = str6.replace("%protector.buffs.mdc.explaination%", cBQ.cxL().mL("protector.buffs.mdc.explaination"));
    localcWk3.setText(str6);
    localcWk3.setMinWidth(1);
    localcWk3.setMaxWidth(250);
    localdRq8.bb(localcWk3);
    localcWk3.brn();
    cWk localcWk4 = localcWk3;
    Jg localJg8 = localcWk4.getAppearance();
    localJg8.setElementMap(localcpa);
    ((cwJ)localJg8).setAlignment(aFG.ecj);
    localcWk3.bb(localJg8);
    localJg8.brn();
    localJg8.rV();
    localcWk3.rV();
    localdRq8.rV();
    localanG2.rV();
    czv localczv4 = localczv3;
    Jg localJg9 = localczv4.getAppearance();
    localJg9.setElementMap(localcpa);
    localczv3.bb(localJg9);
    localJg9.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(0, 0, 0, 10));
    localJg9.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg9.rV();
    localczv3.rV();
    localdRq6.rV();
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa);
    localdRq9.setExpandable(false);
    localdRq9.setVisible(false);
    localdRq1.bb(localdRq9);
    localdRq9.brn();
    dRq localdRq10 = localdRq9;
    Jg localJg10 = localdRq10.getAppearance();
    localJg10.setElementMap(localcpa);
    localdRq9.bb(localJg10);
    localJg10.brn();
    bmv localbmv5 = bmv.checkOut();
    localbmv5.setElementMap(localcpa);
    localbmv5.setInsets(new Insets(0, 10, 0, 0));
    localJg10.bb(localbmv5);
    localbmv5.brn();
    localbmv5.rV();
    localJg10.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("passportViewMode");
    localNK2.setAttribute("visible");
    localdRq9.bb(localNK2);
    localNK2.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localNK2.bb(localanQ2);
    localanQ2.brn();
    bSP localbSP3 = new bSP();
    localbSP3.aJ();
    localbSP3.setElementMap(localcpa);
    localbSP3.setValue("0");
    localanQ2.bb(localbSP3);
    localbSP3.brn();
    localbSP3.rV();
    localanQ2.rV();
    localNK2.rV();
    czO localczO = new czO();
    localczO.aJ();
    localczO.setAdaptToContentSize(true);
    localdRq9.bb(localczO);
    localczO.brn();
    localczO.rV();
    ccG localccG = new ccG();
    localccG.aJ();
    localccG.setElementMap(localcpa);
    localccG.setCellSize(new Or(100.0F, 21));
    localccG.setAutoIdealSize(true);
    localccG.setIdealSizeMinRows(5);
    localccG.setIdealSizeMaxRows(5);
    localccG.setScrollBar(false);
    localccG.setExpandable(false);
    localdRq9.bb(localccG);
    localccG.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localccG.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setName("nation");
    localNK3.setAttribute("content");
    localNK3.setField("protectorBuffsRegular");
    localccG.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    eR localeR1 = new eR();
    localeR1.aJ();
    localeR1.setElementMap(localcpa);
    localccG.bb(localeR1);
    localeR1.brn();
    anQ localanQ3 = new anQ();
    localanQ3.aJ();
    localanQ3.setElementMap(localcpa);
    localeR1.bb(localanQ3);
    localanQ3.brn();
    bxx localbxx1 = new bxx();
    localbxx1.aJ();
    localbxx1.setElementMap(localcpa);
    localanQ3.bb(localbxx1);
    localbxx1.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localbxx1.bb(localanE);
    localanE.brn();
    localanE.rV();
    localbxx1.rV();
    localanQ3.rV();
    dRq localdRq11 = dRq.checkOut();
    localdRq11.setElementMap(localcpa);
    localeR1.bb(localdRq11);
    localdRq11.brn();
    dRq localdRq12 = localdRq11;
    Jg localJg11 = localdRq12.getAppearance();
    localJg11.setElementMap(localcpa);
    localdRq11.bb(localJg11);
    localJg11.brn();
    bmv localbmv6 = bmv.checkOut();
    localbmv6.setElementMap(localcpa);
    localbmv6.setInsets(new Insets(0, 0, 1, 0));
    localJg11.bb(localbmv6);
    localbmv6.brn();
    localbmv6.rV();
    localJg11.rV();
    czv localczv5 = new czv();
    localczv5.aJ();
    localczv5.setElementMap(localcpa);
    localczv5.setExpandable(false);
    localdRq11.bb(localczv5);
    localczv5.brn();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("style");
    localaaE1.setField("style");
    localczv5.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    czv localczv6 = localczv5;
    Jg localJg12 = localczv6.getAppearance();
    localJg12.setElementMap(localcpa);
    localczv5.bb(localJg12);
    localJg12.brn();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("modulationColor");
    localaaE2.setField("enabled");
    localJg12.bb(localaaE2);
    localaaE2.brn();
    anQ localanQ4 = new anQ();
    localanQ4.aJ();
    localanQ4.setElementMap(localcpa);
    localanQ4.setValue("1,1,1,1");
    localanQ4.setElseValue("1,1,1,0.3");
    localaaE2.bb(localanQ4);
    localanQ4.brn();
    cOk localcOk1 = new cOk();
    localcOk1.aJ();
    localcOk1.setElementMap(localcpa);
    localanQ4.bb(localcOk1);
    localcOk1.brn();
    localcOk1.rV();
    localanQ4.rV();
    localaaE2.rV();
    localJg12.rV();
    localczv5.rV();
    cWk localcWk5 = new cWk();
    localcWk5.aJ();
    localcWk5.setElementMap(localcpa);
    localcWk5.setStyle("StyledBold");
    localdRq11.bb(localcWk5);
    localcWk5.brn();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.eck);
    localcWk5.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    cWk localcWk6 = localcWk5;
    Jg localJg13 = localcWk6.getAppearance();
    localJg13.setElementMap(localcpa);
    localcWk5.bb(localJg13);
    localJg13.brn();
    bmv localbmv7 = bmv.checkOut();
    localbmv7.setElementMap(localcpa);
    localbmv7.setInsets(new Insets(0, 5, 0, 0));
    localJg13.bb(localbmv7);
    localbmv7.brn();
    localbmv7.rV();
    aaE localaaE3 = new aaE();
    localaaE3.aJ();
    localaaE3.setElementMap(localcpa);
    localaaE3.setAttribute("modulationColor");
    localaaE3.setField("enabled");
    localJg13.bb(localaaE3);
    localaaE3.brn();
    anQ localanQ5 = new anQ();
    localanQ5.aJ();
    localanQ5.setElementMap(localcpa);
    localanQ5.setValue("1,1,1,0.8");
    localanQ5.setElseValue("1,1,1,0.3");
    localaaE3.bb(localanQ5);
    localanQ5.brn();
    cOk localcOk2 = new cOk();
    localcOk2.aJ();
    localcOk2.setElementMap(localcpa);
    localanQ5.bb(localcOk2);
    localcOk2.brn();
    localcOk2.rV();
    localanQ5.rV();
    localaaE3.rV();
    localJg13.rV();
    aaE localaaE4 = new aaE();
    localaaE4.aJ();
    localaaE4.setElementMap(localcpa);
    localaaE4.setAttribute("text");
    localaaE4.setField("effect");
    localcWk5.bb(localaaE4);
    localaaE4.brn();
    localaaE4.rV();
    localcWk5.rV();
    localdRq11.rV();
    localeR1.rV();
    eR localeR2 = new eR();
    localeR2.aJ();
    localeR2.setElementMap(localcpa);
    localccG.bb(localeR2);
    localeR2.brn();
    anQ localanQ6 = new anQ();
    localanQ6.aJ();
    localanQ6.setElementMap(localcpa);
    localeR2.bb(localanQ6);
    localanQ6.brn();
    bxx localbxx2 = new bxx();
    localbxx2.aJ();
    localbxx2.setElementMap(localcpa);
    localanQ6.bb(localbxx2);
    localbxx2.brn();
    e(localbxx2);
    localbxx2.rV();
    localanQ6.rV();
    localeR2.rV();
    localccG.rV();
    f(localdRq9);
    localdRq9.rV();
    g(localdRq1);
    localdRq1.rV();
    return localdRq1;
  }

  public bdj e(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    aIB localaIB = new aIB();
    localaIB.aJ();
    localaIB.setElementMap(localcpa);
    parambdj.bb(localaIB);
    localaIB.brn();
    localaIB.rV();
    return localaIB;
  }

  public bdj f(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    biy localbiy1 = new biy();
    localbiy1.aJ();
    localbiy1.setElementMap(localcpa);
    csA localcsA = new csA();
    localcsA.hg("wakfu.passport:setViewMode(1)");
    localbiy1.setOnClick(localcsA);
    localbiy1.setStyle("yellowSmall");
    localbiy1.setText("...");
    localbiy1.setVisible(false);
    parambdj.bb(localbiy1);
    localbiy1.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(-2, -2));
    localcwP.setAlign(ajb.dih);
    localcwP.setXOffset(-8);
    localbiy1.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    biy localbiy2 = localbiy1;
    Jg localJg = localbiy2.getAppearance();
    localJg.setElementMap(localcpa);
    localbiy1.bb(localJg);
    localJg.brn();
    cuR localcuR = new cuR();
    localcuR.aJ();
    localcuR.setElementMap(localcpa);
    localcuR.setInsets(new Insets(3, 7, 3, 7));
    localJg.bb(localcuR);
    localcuR.brn();
    localcuR.rV();
    localJg.rV();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setName("nation");
    localNK.setAttribute("visible");
    localNK.setField("protectorNumBuffsRegular");
    localbiy1.bb(localNK);
    localNK.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localNK.bb(localanQ);
    localanQ.brn();
    aEJ localaEJ = new aEJ();
    localaEJ.aJ();
    localaEJ.setElementMap(localcpa);
    localaEJ.setValue("5");
    localanQ.bb(localaEJ);
    localaEJ.brn();
    localaEJ.rV();
    localanQ.rV();
    localNK.rV();
    localbiy1.rV();
    return localbiy1;
  }

  public bdj g(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    localdRq1.setVisible(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setName("passportViewMode");
    localNK1.setAttribute("visible");
    localdRq1.bb(localNK1);
    localNK1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localNK1.bb(localanQ1);
    localanQ1.brn();
    bSP localbSP = new bSP();
    localbSP.aJ();
    localbSP.setElementMap(localcpa);
    localbSP.setValue("1");
    localanQ1.bb(localbSP);
    localbSP.brn();
    localbSP.rV();
    localanQ1.rV();
    localNK1.rV();
    czO localczO = new czO();
    localczO.aJ();
    localczO.setAdaptToContentSize(true);
    localdRq1.bb(localczO);
    localczO.brn();
    localczO.rV();
    ccG localccG1 = new ccG();
    localccG1.aJ();
    localccG1.setElementMap(localcpa);
    localccG1.setCellSize(new Or(100.0F, 21));
    localccG1.setAutoIdealSize(true);
    localccG1.setIdealSizeMinRows(13);
    localccG1.setIdealSizeMaxRows(13);
    localccG1.setExpandable(false);
    localdRq1.bb(localccG1);
    localccG1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localccG1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    ccG localccG2 = localccG1;
    Jg localJg1 = localccG2.getAppearance();
    localJg1.setElementMap(localcpa);
    localccG1.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 10, 0, 0));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("nation");
    localNK2.setAttribute("content");
    localNK2.setField("protectorBuffsRegular");
    localccG1.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    eR localeR1 = new eR();
    localeR1.aJ();
    localeR1.setElementMap(localcpa);
    localccG1.bb(localeR1);
    localeR1.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localeR1.bb(localanQ2);
    localanQ2.brn();
    bxx localbxx1 = new bxx();
    localbxx1.aJ();
    localbxx1.setElementMap(localcpa);
    localanQ2.bb(localbxx1);
    localbxx1.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localbxx1.bb(localanE);
    localanE.brn();
    localanE.rV();
    localbxx1.rV();
    localanQ2.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localeR1.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg2 = localdRq3.getAppearance();
    localJg2.setElementMap(localcpa);
    localdRq2.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 0, 1, 0));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setExpandable(false);
    localdRq2.bb(localczv1);
    localczv1.brn();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("style");
    localaaE1.setField("style");
    localczv1.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    czv localczv2 = localczv1;
    Jg localJg3 = localczv2.getAppearance();
    localJg3.setElementMap(localcpa);
    localczv1.bb(localJg3);
    localJg3.brn();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("modulationColor");
    localaaE2.setField("enabled");
    localJg3.bb(localaaE2);
    localaaE2.brn();
    anQ localanQ3 = new anQ();
    localanQ3.aJ();
    localanQ3.setElementMap(localcpa);
    localanQ3.setValue("1,1,1,1");
    localanQ3.setElseValue("1,1,1,0.3");
    localaaE2.bb(localanQ3);
    localanQ3.brn();
    cOk localcOk1 = new cOk();
    localcOk1.aJ();
    localcOk1.setElementMap(localcpa);
    localanQ3.bb(localcOk1);
    localcOk1.brn();
    localcOk1.rV();
    localanQ3.rV();
    localaaE2.rV();
    localJg3.rV();
    localczv1.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("StyledBold");
    localdRq2.bb(localcWk1);
    localcWk1.brn();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.eck);
    localcWk1.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    cWk localcWk2 = localcWk1;
    Jg localJg4 = localcWk2.getAppearance();
    localJg4.setElementMap(localcpa);
    localcWk1.bb(localJg4);
    localJg4.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 5, 0, 0));
    localJg4.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    aaE localaaE3 = new aaE();
    localaaE3.aJ();
    localaaE3.setElementMap(localcpa);
    localaaE3.setAttribute("modulationColor");
    localaaE3.setField("enabled");
    localJg4.bb(localaaE3);
    localaaE3.brn();
    anQ localanQ4 = new anQ();
    localanQ4.aJ();
    localanQ4.setElementMap(localcpa);
    localanQ4.setValue("1,1,1,0.8");
    localanQ4.setElseValue("1,1,1,0.3");
    localaaE3.bb(localanQ4);
    localanQ4.brn();
    cOk localcOk2 = new cOk();
    localcOk2.aJ();
    localcOk2.setElementMap(localcpa);
    localanQ4.bb(localcOk2);
    localcOk2.brn();
    localcOk2.rV();
    localanQ4.rV();
    localaaE3.rV();
    localJg4.rV();
    aaE localaaE4 = new aaE();
    localaaE4.aJ();
    localaaE4.setElementMap(localcpa);
    localaaE4.setAttribute("text");
    localaaE4.setField("effect");
    localcWk1.bb(localaaE4);
    localaaE4.brn();
    localaaE4.rV();
    localcWk1.rV();
    localdRq2.rV();
    localeR1.rV();
    eR localeR2 = new eR();
    localeR2.aJ();
    localeR2.setElementMap(localcpa);
    localccG1.bb(localeR2);
    localeR2.brn();
    anQ localanQ5 = new anQ();
    localanQ5.aJ();
    localanQ5.setElementMap(localcpa);
    localeR2.bb(localanQ5);
    localanQ5.brn();
    bxx localbxx2 = new bxx();
    localbxx2.aJ();
    localbxx2.setElementMap(localcpa);
    localanQ5.bb(localbxx2);
    localbxx2.brn();
    aIB localaIB = new aIB();
    localaIB.aJ();
    localaIB.setElementMap(localcpa);
    localbxx2.bb(localaIB);
    localaIB.brn();
    localaIB.rV();
    localbxx2.rV();
    localanQ5.rV();
    localeR2.rV();
    localccG1.rV();
    biy localbiy1 = new biy();
    localbiy1.aJ();
    localbiy1.setElementMap(localcpa);
    csA localcsA = new csA();
    localcsA.hg("wakfu.passport:setViewMode(0)");
    localbiy1.setOnClick(localcsA);
    localbiy1.setStyle("yellowSmall");
    localbiy1.setText("...");
    localbiy1.setVisible(false);
    localdRq1.bb(localbiy1);
    localbiy1.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setSize(new Or(-2, -2));
    localcwP2.setAlign(ajb.dih);
    localcwP2.setXOffset(-8);
    localbiy1.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    biy localbiy2 = localbiy1;
    Jg localJg5 = localbiy2.getAppearance();
    localJg5.setElementMap(localcpa);
    localbiy1.bb(localJg5);
    localJg5.brn();
    cuR localcuR = new cuR();
    localcuR.aJ();
    localcuR.setElementMap(localcpa);
    localcuR.setInsets(new Insets(3, 7, 3, 7));
    localJg5.bb(localcuR);
    localcuR.brn();
    localcuR.rV();
    localJg5.rV();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setName("nation");
    localNK3.setAttribute("visible");
    localNK3.setField("protectorNumBuffsRegular");
    localbiy1.bb(localNK3);
    localNK3.brn();
    anQ localanQ6 = new anQ();
    localanQ6.aJ();
    localanQ6.setElementMap(localcpa);
    localNK3.bb(localanQ6);
    localanQ6.brn();
    aEJ localaEJ = new aEJ();
    localaEJ.aJ();
    localaEJ.setElementMap(localcpa);
    localaEJ.setValue("5");
    localanQ6.bb(localaEJ);
    localaEJ.brn();
    localaEJ.rV();
    localanQ6.rV();
    localNK3.rV();
    localbiy1.rV();
    localdRq1.rV();
    return localdRq1;
  }
}