import java.awt.Insets;
import java.util.Stack;

public class mr
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    bpn localbpn = new bpn();
    localbpn.aJ();
    localbpn.setElementMap(localcpa);
    localbpn.setMovable(true);
    localbpn.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setAlign(ajb.dhY);
    localcwP.setXOffset(20);
    localcwP.setInitValue(true);
    localbpn.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    String str1 = "challengeInputContainer";
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localdRq1);
    localdRq1.setNonBlocking(true);
    localdRq1.setStyle("spellInventory");
    localdRq1.setPack(true);
    localbpn.bb(localdRq1);
    localdRq1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("visible");
    localNK1.setName("waitingForInputChallenge");
    localdRq1.bb(localNK1);
    localNK1.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localNK1.bb(localanQ);
    localanQ.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localanQ.bb(localanE);
    localanE.brn();
    localanE.rV();
    localanQ.rV();
    localNK1.rV();
    String str2 = "challenge";
    avo localavo = new avo();
    localavo.aJ();
    localavo.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localavo);
    localdRq1.bb(localavo);
    localavo.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setAttribute("value");
    localNK2.setName("waitingForInputChallenge");
    localavo.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localavo.rV();
    dqa localdqa1 = new dqa();
    localdqa1.aJ();
    localdqa1.setElementMap(localcpa);
    localdRq1.bb(localdqa1);
    localdqa1.brn();
    dqa localdqa2 = localdqa1;
    Jg localJg1 = localdqa2.getAppearance();
    localJg1.setElementMap(localcpa);
    localdqa1.bb(localJg1);
    localJg1.brn();
    cuR localcuR = new cuR();
    localcuR.aJ();
    localcuR.setElementMap(localcpa);
    localcuR.setInsets(new Insets(10, 10, 10, 10));
    localJg1.bb(localcuR);
    localcuR.brn();
    localcuR.rV();
    localJg1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdqa1.bb(localdRq2);
    localdRq2.brn();
    bTm localbTm = new bTm();
    localbTm.aJ();
    localdRq2.bb(localbTm);
    localbTm.brn();
    caF localcaF = new caF();
    localcaF.aJ();
    localcaF.setElementMap(localcpa);
    localcaF.setNonBlocking(true);
    String str3 = "%challenge.question%";
    str3 = str3.replace("%challenge.question%", cBQ.cxL().mL("challenge.question"));
    localcaF.setText(str3);
    localcaF.setStyle("white");
    localbTm.bb(localcaF);
    localcaF.brn();
    cba localcba1 = cba.checkOut();
    localcba1.setElementMap(localcpa);
    localcba1.setData(cFu.izS);
    localcaF.bb(localcba1);
    localcba1.brn();
    localcba1.rV();
    localcaF.rV();
    String str4 = "textEditor";
    aTp localaTp1 = new aTp();
    localaTp1.aJ();
    localaTp1.setElementMap(localcpa);
    if ((localcpa != null) && (str4 != null))
      localcpa.a(str4, localaTp1);
    localaTp1.setStyle("dark");
    localaTp1.setPrefSize(new Or(80, 0));
    localaTp1.setMaxChars(10);
    localaTp1.setRestrict("[0-9]+");
    localaTp1.setFocused(true);
    aOn localaOn = new aOn();
    localaOn.hg("wakfu.challenge:parseInput(challengeInputContainer,challenge)");
    localaTp1.setOnKeyPress(localaOn);
    localbTm.bb(localaTp1);
    localaTp1.brn();
    cba localcba2 = cba.checkOut();
    localcba2.setElementMap(localcpa);
    localcba2.setData(cFu.izR);
    localaTp1.bb(localcba2);
    localcba2.brn();
    localcba2.rV();
    aTp localaTp2 = localaTp1;
    Jg localJg2 = localaTp2.getAppearance();
    localJg2.setElementMap(localcpa);
    ((cwJ)localJg2).setAlign(aFG.ecl);
    localaTp1.bb(localJg2);
    localJg2.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(8, 5, 5, 0));
    localJg2.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg2.rV();
    localaTp1.rV();
    biy localbiy1 = new biy();
    localbiy1.aJ();
    localbiy1.setElementMap(localcpa);
    localbiy1.setStyle("smallValid");
    csA localcsA = new csA();
    localcsA.hg("wakfu.challenge:parseInput(challengeInputContainer,challenge)");
    localbiy1.setOnClick(localcsA);
    localbTm.bb(localbiy1);
    localbiy1.brn();
    cba localcba3 = cba.checkOut();
    localcba3.setElementMap(localcpa);
    localcba3.setData(cFu.izU);
    localbiy1.bb(localcba3);
    localcba3.brn();
    localcba3.rV();
    biy localbiy2 = localbiy1;
    Jg localJg3 = localbiy2.getAppearance();
    localJg3.setElementMap(localcpa);
    localbiy1.bb(localJg3);
    localJg3.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(3, 5, 0, 5));
    localJg3.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg3.rV();
    localbiy1.rV();
    localbTm.rV();
    localdRq2.rV();
    localdqa1.rV();
    localdRq1.rV();
    localbpn.rV();
    return localbpn;
  }
}