import java.awt.Insets;
import java.util.Stack;

public class crW
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa1 = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa1);
    localdRq1.setNonBlocking(false);
    localdRq1.setPack(true);
    localdRq1.brn();
    czO localczO1 = new czO();
    localczO1.aJ();
    localczO1.setAdaptToContentSize(true);
    localdRq1.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    String str = "itemDetailPopup";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa1);
    if ((localcpa1 != null) && (str != null))
      localcpa1.a(str, localanG);
    localanG.setAlign(aFG.eci);
    localanG.setHotSpotPosition(aFG.ecg);
    localdRq1.bb(localanG);
    localanG.brn();
    cpa localcpa2 = localcpa1;
    localcpa1 = this.Y.nd((localcpa1 != null ? localcpa1.getId() : "") + ".itemDetailPopupInc");
    localcpa1.d(localcpa2);
    this.X.push(localcpa1);
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa1);
    localanG.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa1);
    localdRq3.setVisible(false);
    localdRq2.bb(localdRq3);
    localdRq3.brn();
    aId localaId1 = aId.checkOut();
    localdRq3.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa1);
    localNK1.setName("itemPopupDetail");
    localNK1.setAttribute("visible");
    localdRq3.bb(localNK1);
    localNK1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa1);
    localNK1.bb(localanQ1);
    localanQ1.brn();
    anE localanE1 = new anE();
    localanE1.aJ();
    localanE1.setElementMap(localcpa1);
    localanQ1.bb(localanE1);
    localanE1.brn();
    localanE1.rV();
    localanQ1.rV();
    localNK1.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa1);
    localdRq4.setExpandable(false);
    localdRq4.setPrefSize(new Or(250, 0));
    localdRq4.setStyle("popup");
    localdRq3.bb(localdRq4);
    localdRq4.brn();
    dRq localdRq5 = localdRq4;
    Jg localJg1 = localdRq5.getAppearance();
    localJg1.setElementMap(localcpa1);
    localdRq4.bb(localJg1);
    localJg1.brn();
    localJg1.rV();
    aId localaId2 = aId.checkOut();
    localaId2.setAlign(aFG.ech);
    localaId2.setHorizontal(false);
    localdRq4.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa1);
    localcWk1.setStyle("DefaultBold14White");
    localcWk1.setExpandable(false);
    localcWk1.setMinWidth(210);
    localdRq4.bb(localcWk1);
    localcWk1.brn();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa1);
    localdpm1.setAlign(aFG.ecj);
    localcWk1.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa1);
    localNK2.setName("itemPopupDetail");
    localNK2.setAttribute("text");
    localNK2.setField("nameWithRarity");
    localcWk1.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localcWk1.rV();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa1);
    localdRq6.setExpandable(false);
    localdRq4.bb(localdRq6);
    localdRq6.brn();
    aId localaId3 = aId.checkOut();
    localdRq6.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa1);
    localdRq7.setExpandable(false);
    localdRq6.bb(localdRq7);
    localdRq7.brn();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa1);
    localdpm2.setAlign(aFG.ech);
    localdRq7.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    czO localczO2 = new czO();
    localczO2.aJ();
    localczO2.setAdaptToContentSize(true);
    localdRq7.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    dRq localdRq8 = localdRq7;
    Jg localJg2 = localdRq8.getAppearance();
    localJg2.setElementMap(localcpa1);
    localdRq7.bb(localJg2);
    localJg2.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa1);
    localbmv1.setInsets(new Insets(0, 0, 0, 2));
    localJg2.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg2.rV();
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa1);
    localdRq9.setStyle("caracs");
    localdRq7.bb(localdRq9);
    localdRq9.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa1);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localdRq9.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    localdRq9.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa1);
    localczv1.setDisplaySize(new Or(64, 64));
    localdRq7.bb(localczv1);
    localczv1.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa1);
    localcwP2.setAlign(ajb.dhZ);
    localcwP2.setSize(new Or(-2, -2));
    localczv1.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa1);
    localczv1.bb(localaAR);
    localaAR.brn();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa1);
    localNK3.setName("itemPopupDetail");
    localNK3.setAttribute("texture");
    localNK3.setField("iconUrl");
    localaAR.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    localaAR.rV();
    localczv1.rV();
    localdRq7.rV();
    dRq localdRq10 = dRq.checkOut();
    localdRq10.setElementMap(localcpa1);
    localdRq6.bb(localdRq10);
    localdRq10.brn();
    dRq localdRq11 = localdRq10;
    Jg localJg3 = localdRq11.getAppearance();
    localJg3.setElementMap(localcpa1);
    localdRq10.bb(localJg3);
    localJg3.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa1);
    localbmv2.setInsets(new Insets(0, 0, 0, 0));
    localJg3.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg3.rV();
    aId localaId4 = aId.checkOut();
    localaId4.setHorizontal(false);
    localaId4.setAlign(aFG.ech);
    localdRq10.bb(localaId4);
    localaId4.brn();
    localaId4.rV();
    cWk localcWk2 = new cWk();
    localcWk2.aJ();
    localcWk2.setElementMap(localcpa1);
    localcWk2.setStyle("11light");
    localcWk2.setExpandable(false);
    localdRq10.bb(localcWk2);
    localcWk2.brn();
    dpm localdpm3 = new dpm();
    localdpm3.aJ();
    localdpm3.setElementMap(localcpa1);
    localdpm3.setAlign(aFG.ecl);
    localcWk2.bb(localdpm3);
    localdpm3.brn();
    localdpm3.rV();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa1);
    localNK4.setName("itemPopupDetail");
    localNK4.setAttribute("text");
    localNK4.setField("levelDescription");
    localcWk2.bb(localNK4);
    localNK4.brn();
    localNK4.rV();
    localcWk2.rV();
    cWk localcWk3 = new cWk();
    localcWk3.aJ();
    localcWk3.setElementMap(localcpa1);
    localcWk3.setStyle("white11");
    localcWk3.setMultiline(false);
    localcWk3.setExpandable(false);
    localdRq10.bb(localcWk3);
    localcWk3.brn();
    dpm localdpm4 = new dpm();
    localdpm4.aJ();
    localdpm4.setElementMap(localcpa1);
    localdpm4.setAlign(aFG.ecj);
    localcWk3.bb(localdpm4);
    localdpm4.brn();
    localdpm4.rV();
    NK localNK5 = NK.checkOut();
    localNK5.setElementMap(localcpa1);
    localNK5.setAttribute("text");
    localNK5.setName("itemPopupDetail");
    localNK5.setField("type");
    localcWk3.bb(localNK5);
    localNK5.brn();
    localNK5.rV();
    localcWk3.rV();
    dRq localdRq12 = dRq.checkOut();
    localdRq12.setElementMap(localcpa1);
    localdRq12.setExpandable(false);
    localdRq10.bb(localdRq12);
    localdRq12.brn();
    dpm localdpm5 = new dpm();
    localdpm5.aJ();
    localdpm5.setElementMap(localcpa1);
    localdpm5.setAlign(aFG.ecl);
    localdRq12.bb(localdpm5);
    localdpm5.brn();
    localdpm5.rV();
    NK localNK6 = NK.checkOut();
    localNK6.setElementMap(localcpa1);
    localNK6.setName("itemPopupDetail");
    localNK6.setAttribute("visible");
    localNK6.setField("ap");
    localdRq12.bb(localNK6);
    localNK6.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa1);
    localNK6.bb(localanQ2);
    localanQ2.brn();
    bJJ localbJJ = new bJJ();
    localbJJ.aJ();
    localbJJ.setElementMap(localcpa1);
    localanQ2.bb(localbJJ);
    localbJJ.brn();
    jA localjA = new jA();
    localjA.aJ();
    localjA.setElementMap(localcpa1);
    localjA.setValue("0");
    localbJJ.bb(localjA);
    localjA.brn();
    localjA.rV();
    cOk localcOk = new cOk();
    localcOk.aJ();
    localcOk.setElementMap(localcpa1);
    localbJJ.bb(localcOk);
    localcOk.brn();
    NK localNK7 = NK.checkOut();
    localNK7.setElementMap(localcpa1);
    localNK7.setName("itemPopupDetail");
    localNK7.setAttribute("comparedValue");
    localNK7.setField("usableInFight");
    localcOk.bb(localNK7);
    localNK7.brn();
    localNK7.rV();
    localcOk.rV();
    localbJJ.rV();
    localanQ2.rV();
    localNK6.rV();
    dRq localdRq13 = dRq.checkOut();
    localdRq13.setElementMap(localcpa1);
    localdRq13.setExpandable(false);
    localdRq12.bb(localdRq13);
    localdRq13.brn();
    dpm localdpm6 = new dpm();
    localdpm6.aJ();
    localdpm6.setElementMap(localcpa1);
    localdpm6.setAlign(aFG.ecl);
    localdRq13.bb(localdpm6);
    localdpm6.brn();
    localdpm6.rV();
    aId localaId5 = aId.checkOut();
    localaId5.setHgap((short)2);
    localdRq13.bb(localaId5);
    localaId5.brn();
    localaId5.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa1);
    localcaF1.setStyle("11Light");
    localdRq13.bb(localcaF1);
    localcaF1.brn();
    NK localNK8 = NK.checkOut();
    localNK8.setElementMap(localcpa1);
    localNK8.setName("itemPopupDetail");
    localNK8.setAttribute("text");
    localNK8.setField("ap");
    localcaF1.bb(localNK8);
    localNK8.brn();
    localNK8.rV();
    localcaF1.rV();
    czv localczv2 = new czv();
    localczv2.aJ();
    localczv2.setElementMap(localcpa1);
    localczv2.setStyle("iconAP");
    localczv2.setExpandable(false);
    localdRq13.bb(localczv2);
    localczv2.brn();
    localczv2.rV();
    localdRq13.rV();
    localdRq12.rV();
    dRq localdRq14 = dRq.checkOut();
    localdRq14.setElementMap(localcpa1);
    localdRq14.setExpandable(false);
    localdRq10.bb(localdRq14);
    localdRq14.brn();
    dpm localdpm7 = new dpm();
    localdpm7.aJ();
    localdpm7.setElementMap(localcpa1);
    localdpm7.setAlign(aFG.ecl);
    localdRq14.bb(localdpm7);
    localdpm7.brn();
    localdpm7.rV();
    NK localNK9 = NK.checkOut();
    localNK9.setElementMap(localcpa1);
    localNK9.setName("itemPopupDetail");
    localNK9.setAttribute("visible");
    localNK9.setField("range");
    localdRq14.bb(localNK9);
    localNK9.brn();
    anQ localanQ3 = new anQ();
    localanQ3.aJ();
    localanQ3.setElementMap(localcpa1);
    localNK9.bb(localanQ3);
    localanQ3.brn();
    anE localanE2 = new anE();
    localanE2.aJ();
    localanE2.setElementMap(localcpa1);
    localanQ3.bb(localanE2);
    localanE2.brn();
    localanE2.rV();
    localanQ3.rV();
    localNK9.rV();
    dRq localdRq15 = dRq.checkOut();
    localdRq15.setElementMap(localcpa1);
    localdRq15.setExpandable(false);
    localdRq14.bb(localdRq15);
    localdRq15.brn();
    dpm localdpm8 = new dpm();
    localdpm8.aJ();
    localdpm8.setElementMap(localcpa1);
    localdpm8.setAlign(aFG.ecl);
    localdRq15.bb(localdpm8);
    localdpm8.brn();
    localdpm8.rV();
    aId localaId6 = aId.checkOut();
    localaId6.setHgap((short)2);
    localdRq15.bb(localaId6);
    localaId6.brn();
    localaId6.rV();
    caF localcaF2 = new caF();
    localcaF2.aJ();
    localcaF2.setElementMap(localcpa1);
    localcaF2.setStyle("11Light");
    localdRq15.bb(localcaF2);
    localcaF2.brn();
    NK localNK10 = NK.checkOut();
    localNK10.setElementMap(localcpa1);
    localNK10.setName("itemPopupDetail");
    localNK10.setAttribute("text");
    localNK10.setField("range");
    localcaF2.bb(localNK10);
    localNK10.brn();
    localNK10.rV();
    localcaF2.rV();
    czv localczv3 = new czv();
    localczv3.aJ();
    localczv3.setElementMap(localcpa1);
    localczv3.setStyle("rangeIcon");
    localczv3.setExpandable(false);
    localdRq15.bb(localczv3);
    localczv3.brn();
    localczv3.rV();
    localdRq15.rV();
    localdRq14.rV();
    localdRq10.rV();
    localdRq6.rV();
    dRq localdRq16 = dRq.checkOut();
    localdRq16.setElementMap(localcpa1);
    localdRq16.setExpandable(false);
    localdRq4.bb(localdRq16);
    localdRq16.brn();
    aId localaId7 = aId.checkOut();
    localaId7.setHorizontal(false);
    localdRq16.bb(localaId7);
    localaId7.brn();
    localaId7.rV();
    NK localNK11 = NK.checkOut();
    localNK11.setElementMap(localcpa1);
    localNK11.setAttribute("visible");
    localNK11.setName("itemPopupDetail");
    localNK11.setField("description");
    localdRq16.bb(localNK11);
    localNK11.brn();
    anQ localanQ4 = new anQ();
    localanQ4.aJ();
    localanQ4.setElementMap(localcpa1);
    localNK11.bb(localanQ4);
    localanQ4.brn();
    anE localanE3 = new anE();
    localanE3.aJ();
    localanE3.setElementMap(localcpa1);
    localanQ4.bb(localanE3);
    localanE3.brn();
    localanE3.rV();
    localanQ4.rV();
    localNK11.rV();
    dRq localdRq17 = dRq.checkOut();
    localdRq17.setElementMap(localcpa1);
    localdRq17.setExpandable(false);
    localdRq17.setStyle("lineSeparator2");
    localdRq17.setPrefSize(new Or(50, 1));
    localdRq16.bb(localdRq17);
    localdRq17.brn();
    dRq localdRq18 = localdRq17;
    Jg localJg4 = localdRq18.getAppearance();
    localJg4.setElementMap(localcpa1);
    localdRq17.bb(localJg4);
    localJg4.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa1);
    localbmv3.setInsets(new Insets(5, 20, 5, 20));
    localJg4.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg4.rV();
    localdRq17.rV();
    cWk localcWk4 = new cWk();
    localcWk4.aJ();
    localcWk4.setElementMap(localcpa1);
    localcWk4.setStyle("narrow12");
    localcWk4.setMinWidth(1);
    localcWk4.setMaxWidth(250);
    localcWk4.setExpandable(false);
    localdRq16.bb(localcWk4);
    localcWk4.brn();
    cWk localcWk5 = localcWk4;
    Jg localJg5 = localcWk5.getAppearance();
    localJg5.setElementMap(localcpa1);
    localcWk4.bb(localJg5);
    localJg5.brn();
    cAf localcAf = cAf.checkOut();
    localcAf.setElementMap(localcpa1);
    localcAf.setColor(new bNa(0.98F, 0.77F, 0.0F, 1.0F));
    localJg5.bb(localcAf);
    localcAf.brn();
    localcAf.rV();
    localJg5.rV();
    NK localNK12 = NK.checkOut();
    localNK12.setElementMap(localcpa1);
    localNK12.setName("itemPopupDetail");
    localNK12.setAttribute("text");
    localNK12.setField("description");
    localcWk4.bb(localNK12);
    localNK12.brn();
    localNK12.rV();
    localcWk4.rV();
    localdRq16.rV();
    a(localdRq4);
    b(localdRq4);
    d(localdRq4);
    e(localdRq4);
    f(localdRq4);
    localdRq4.rV();
    localdRq3.rV();
    localdRq2.rV();
    this.X.pop();
    localcpa1 = (cpa)this.X.peek();
    localanG.rV();
    g(localdRq1);
    m(localdRq1);
    localdRq1.rV();
    return localdRq1;
  }

  public bdj a(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("visible");
    localNK1.setName("itemPopupDetail");
    localNK1.setField("requirement");
    localdRq1.bb(localNK1);
    localNK1.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localNK1.bb(localanQ);
    localanQ.brn();
    jA localjA = new jA();
    localjA.aJ();
    localjA.setElementMap(localcpa);
    localjA.setValue("");
    localanQ.bb(localjA);
    localjA.brn();
    localjA.rV();
    localanQ.rV();
    localNK1.rV();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(false);
    localdRq1.bb(localaId);
    localaId.brn();
    localaId.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setExpandable(false);
    localdRq2.setStyle("lineSeparator2");
    localdRq2.setPrefSize(new Or(50, 1));
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(5, 20, 5, 20));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    localdRq2.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setExpandable(false);
    localcWk1.setStyle("white11");
    localcWk1.setMinWidth(250);
    localdRq1.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg2 = localcWk2.getAppearance();
    localJg2.setElementMap(localcpa);
    localcWk1.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 0, 0, 0));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("itemPopupDetail");
    localNK2.setAttribute("text");
    localNK2.setField("requirement");
    localcWk1.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localcWk1.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj b(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("visible");
    localNK1.setName("itemPopupDetail");
    localNK1.setField("useRequirement");
    localdRq1.bb(localNK1);
    localNK1.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localNK1.bb(localanQ);
    localanQ.brn();
    jA localjA = new jA();
    localjA.aJ();
    localjA.setElementMap(localcpa);
    localjA.setValue("");
    localanQ.bb(localjA);
    localjA.brn();
    localjA.rV();
    localanQ.rV();
    localNK1.rV();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(false);
    localdRq1.bb(localaId);
    localaId.brn();
    localaId.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setExpandable(false);
    localdRq2.setStyle("lineSeparator2");
    localdRq2.setPrefSize(new Or(50, 1));
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(5, 20, 5, 20));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    localdRq2.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setExpandable(false);
    String str = "%use.requirements%";
    str = str.replace("%use.requirements%", cBQ.cxL().mL("use.requirements"));
    localcaF1.setText(str);
    localcaF1.setStyle("11BoldLight");
    localcaF1.setNonBlocking(true);
    localdRq1.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg2 = localcaF2.getAppearance();
    localJg2.setElementMap(localcpa);
    localcaF1.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 5, 5, 0));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    localcaF1.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setExpandable(false);
    localcWk1.setStyle("white11");
    localcWk1.setMinWidth(1);
    localcWk1.setMaxWidth(250);
    localcWk1.setNonBlocking(true);
    localdRq1.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg3 = localcWk2.getAppearance();
    localJg3.setElementMap(localcpa);
    localcWk1.bb(localJg3);
    localJg3.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 20, 0, 0));
    localJg3.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg3.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("itemPopupDetail");
    localNK2.setAttribute("text");
    localNK2.setField("useRequirement");
    localcWk1.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localcWk1.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj d(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("visible");
    localNK1.setName("itemPopupDetail");
    localNK1.setField("hasCaracteristic");
    localdRq1.bb(localNK1);
    localNK1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localNK1.bb(localanQ1);
    localanQ1.brn();
    cOk localcOk = new cOk();
    localcOk.aJ();
    localcOk.setElementMap(localcpa);
    localanQ1.bb(localcOk);
    localcOk.brn();
    localcOk.rV();
    localanQ1.rV();
    localNK1.rV();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(false);
    localdRq1.bb(localaId);
    localaId.brn();
    localaId.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setExpandable(false);
    localdRq2.setStyle("lineSeparator2");
    localdRq2.setPrefSize(new Or(0, 1));
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(5, 20, 5, 20));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    localdRq2.rV();
    at localat = new at();
    localat.aJ();
    localat.setElementMap(localcpa);
    localat.setHorizontal(false);
    localdRq1.bb(localat);
    localat.brn();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.ecj);
    localat.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("itemPopupDetail");
    localNK2.setAttribute("content");
    localNK2.setField("caracteristic");
    localat.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    eR localeR = new eR();
    localeR.aJ();
    localeR.setElementMap(localcpa);
    localat.bb(localeR);
    localeR.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localeR.bb(localanQ2);
    localanQ2.brn();
    bxx localbxx = new bxx();
    localbxx.aJ();
    localbxx.setElementMap(localcpa);
    localanQ2.bb(localbxx);
    localbxx.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localbxx.bb(localanE);
    localanE.brn();
    localanE.rV();
    localbxx.rV();
    localanQ2.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localeR.bb(localdRq4);
    localdRq4.brn();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("white11");
    localcWk1.setMultiline(false);
    localcWk1.setMinWidth(250);
    localcWk1.setMaxWidth(250);
    localcWk1.setExpandable(false);
    localdRq4.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg2 = localcWk2.getAppearance();
    localJg2.setElementMap(localcpa);
    localcWk1.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 5, 0, 0));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    aaE localaaE = new aaE();
    localaaE.aJ();
    localaaE.setElementMap(localcpa);
    localaaE.setAttribute("text");
    localcWk1.bb(localaaE);
    localaaE.brn();
    localaaE.rV();
    localcWk1.rV();
    localdRq4.rV();
    localeR.rV();
    localat.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj e(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("visible");
    localNK1.setName("itemPopupDetail");
    localNK1.setField("effect");
    localdRq1.bb(localNK1);
    localNK1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localNK1.bb(localanQ1);
    localanQ1.brn();
    anE localanE1 = new anE();
    localanE1.aJ();
    localanE1.setElementMap(localcpa);
    localanQ1.bb(localanE1);
    localanE1.brn();
    localanE1.rV();
    localanQ1.rV();
    localNK1.rV();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(false);
    localdRq1.bb(localaId);
    localaId.brn();
    localaId.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setExpandable(false);
    localdRq2.setStyle("lineSeparator2");
    localdRq2.setPrefSize(new Or(50, 1));
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(5, 20, 5, 20));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    localdRq2.rV();
    at localat = new at();
    localat.aJ();
    localat.setElementMap(localcpa);
    localat.setHorizontal(false);
    localdRq1.bb(localat);
    localat.brn();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.ecj);
    localat.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    eR localeR = new eR();
    localeR.aJ();
    localeR.setElementMap(localcpa);
    localat.bb(localeR);
    localeR.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localeR.bb(localanQ2);
    localanQ2.brn();
    bxx localbxx = new bxx();
    localbxx.aJ();
    localbxx.setElementMap(localcpa);
    localanQ2.bb(localbxx);
    localbxx.brn();
    anE localanE2 = new anE();
    localanE2.aJ();
    localanE2.setElementMap(localcpa);
    localbxx.bb(localanE2);
    localanE2.brn();
    localanE2.rV();
    localbxx.rV();
    localanQ2.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localeR.bb(localdRq4);
    localdRq4.brn();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("white11");
    localcWk1.setMultiline(false);
    localcWk1.setMinWidth(250);
    localcWk1.setMaxWidth(250);
    localcWk1.setExpandable(false);
    localdRq4.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg2 = localcWk2.getAppearance();
    localJg2.setElementMap(localcpa);
    localcWk1.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 5, 0, 0));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    aaE localaaE = new aaE();
    localaaE.aJ();
    localaaE.setElementMap(localcpa);
    localaaE.setAttribute("text");
    localcWk1.bb(localaaE);
    localaaE.brn();
    localaaE.rV();
    localcWk1.rV();
    localdRq4.rV();
    localeR.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("itemPopupDetail");
    localNK2.setAttribute("content");
    localNK2.setField("effectDetails");
    localat.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localat.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj f(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("visible");
    localNK1.setName("itemPopupDetail");
    localNK1.setField("storingCapacity");
    localdRq1.bb(localNK1);
    localNK1.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localNK1.bb(localanQ);
    localanQ.brn();
    aEJ localaEJ = new aEJ();
    localaEJ.aJ();
    localaEJ.setElementMap(localcpa);
    localaEJ.setValue("0");
    localanQ.bb(localaEJ);
    localaEJ.brn();
    localaEJ.rV();
    localanQ.rV();
    localNK1.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localdRq1.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setExpandable(false);
    localdRq2.setStyle("lineSeparator2");
    localdRq2.setPrefSize(new Or(50, 1));
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(5, 20, 5, 20));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    localdRq2.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq1.bb(localdRq4);
    localdRq4.brn();
    aId localaId2 = aId.checkOut();
    localaId2.setAlign(aFG.ecj);
    localdRq4.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("whiteBold");
    localcaF1.setNonBlocking(true);
    String str1 = "%capacity%";
    str1 = str1.replace("%capacity%", cBQ.cxL().mL("capacity"));
    localcaF1.setText(str1);
    localcaF1.setExpandable(false);
    localdRq4.bb(localcaF1);
    localcaF1.brn();
    cba localcba1 = cba.checkOut();
    localcba1.setElementMap(localcpa);
    localcba1.setData(cFu.izT);
    localcaF1.bb(localcba1);
    localcba1.brn();
    localcba1.rV();
    caF localcaF2 = localcaF1;
    Jg localJg2 = localcaF2.getAppearance();
    localJg2.setElementMap(localcpa);
    localcaF1.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 5, 0, 0));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    localcaF1.rV();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setStyle("white");
    localcaF3.setNonBlocking(true);
    String str2 = "%capacity%";
    str2 = str2.replace("%capacity%", cBQ.cxL().mL("capacity"));
    localcaF3.setText(str2);
    localcaF3.setExpandable(false);
    localdRq4.bb(localcaF3);
    localcaF3.brn();
    cba localcba2 = cba.checkOut();
    localcba2.setElementMap(localcpa);
    localcba2.setData(cFu.izT);
    localcaF3.bb(localcba2);
    localcba2.brn();
    localcba2.rV();
    caF localcaF4 = localcaF3;
    Jg localJg3 = localcaF4.getAppearance();
    localJg3.setElementMap(localcpa);
    localcaF3.bb(localJg3);
    localJg3.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 5, 0, 0));
    localJg3.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg3.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setAttribute("text");
    localNK2.setName("itemPopupDetail");
    localNK2.setField("storingCapacity");
    localcaF3.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localcaF3.rV();
    localdRq4.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj g(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    czO localczO1 = new czO();
    localczO1.aJ();
    localczO1.setAdaptToContentSize(true);
    localdRq1.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setStyle("challengeCurrent");
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localcwP2.setAlign(ajb.dif);
    localdRq2.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(100, 0, 0, 0));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(15, 32, 28, 32));
    localJg1.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    localJg1.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localdRq2.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq2.bb(localdRq4);
    localdRq4.brn();
    aId localaId2 = aId.checkOut();
    localaId2.setHorizontal(false);
    localdRq4.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("darkBold");
    localcWk1.setExpandable(false);
    localcWk1.setMinWidth(1);
    localcWk1.setMaxWidth(200);
    localdRq4.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg2 = localcWk2.getAppearance();
    localJg2.setElementMap(localcpa);
    localcWk1.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(5, 20, 5, 0));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.ecj);
    localcWk1.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("text");
    localNK1.setLocal(true);
    localNK1.setName("shukruteReward");
    localNK1.setField("description");
    localcWk1.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setAttribute("visible");
    localNK2.setLocal(true);
    localNK2.setName("shukruteReward");
    localNK2.setField("description");
    localcWk1.bb(localNK2);
    localNK2.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localNK2.bb(localanQ1);
    localanQ1.brn();
    anE localanE1 = new anE();
    localanE1.aJ();
    localanE1.setElementMap(localcpa);
    localanQ1.bb(localanE1);
    localanE1.brn();
    localanE1.rV();
    localanQ1.rV();
    localNK2.rV();
    localcWk1.rV();
    String str1 = "rewardsContainer";
    dRq localdRq5 = dRq.checkOut();
    localdRq5.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localdRq5);
    localdRq4.bb(localdRq5);
    localdRq5.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setSize(new Or(100.0F, 100.0F));
    localcwP3.setAlign(ajb.dhT);
    localdRq5.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    String str2 = "firstRankReward";
    avo localavo1 = new avo();
    localavo1.aJ();
    localavo1.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localavo1);
    localdRq5.bb(localavo1);
    localavo1.brn();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setAttribute("value");
    localNK3.setLocal(true);
    localNK3.setName("shukruteReward");
    localNK3.setField("firstRankReward/item");
    localavo1.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    localavo1.rV();
    String str3 = "secondRankReward";
    avo localavo2 = new avo();
    localavo2.aJ();
    localavo2.setElementMap(localcpa);
    if ((localcpa != null) && (str3 != null))
      localcpa.a(str3, localavo2);
    localdRq5.bb(localavo2);
    localavo2.brn();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa);
    localNK4.setAttribute("value");
    localNK4.setLocal(true);
    localNK4.setName("shukruteReward");
    localNK4.setField("secondRankReward/item");
    localavo2.bb(localNK4);
    localNK4.brn();
    localNK4.rV();
    localavo2.rV();
    String str4 = "thirdRankReward";
    avo localavo3 = new avo();
    localavo3.aJ();
    localavo3.setElementMap(localcpa);
    if ((localcpa != null) && (str4 != null))
      localcpa.a(str4, localavo3);
    localdRq5.bb(localavo3);
    localavo3.brn();
    NK localNK5 = NK.checkOut();
    localNK5.setElementMap(localcpa);
    localNK5.setAttribute("value");
    localNK5.setLocal(true);
    localNK5.setName("shukruteReward");
    localNK5.setField("thirdRankReward/item");
    localavo3.bb(localNK5);
    localNK5.brn();
    localNK5.rV();
    localavo3.rV();
    dRq localdRq6 = localdRq5;
    Jg localJg3 = localdRq6.getAppearance();
    localJg3.setElementMap(localcpa);
    localdRq5.bb(localJg3);
    localJg3.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 10, 0, 10));
    localJg3.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg3.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localdRq5.bb(localdRq7);
    localdRq7.brn();
    NK localNK6 = NK.checkOut();
    localNK6.setElementMap(localcpa);
    localNK6.setLocal(true);
    localNK6.setAttribute("visible");
    localNK6.setName("shukruteReward");
    localNK6.setField("firstRankReward");
    localdRq7.bb(localNK6);
    localNK6.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localNK6.bb(localanQ2);
    localanQ2.brn();
    anE localanE2 = new anE();
    localanE2.aJ();
    localanE2.setElementMap(localcpa);
    localanQ2.bb(localanE2);
    localanE2.brn();
    localanE2.rV();
    localanQ2.rV();
    localNK6.rV();
    czO localczO2 = new czO();
    localczO2.aJ();
    localczO2.setAdaptToContentSize(true);
    localdRq7.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    dRq localdRq8 = dRq.checkOut();
    localdRq8.setElementMap(localcpa);
    localdRq8.setExpandable(false);
    localdRq8.setPrefSize(new Or(43, 43));
    localdRq8.setStyle("challengeRewardContainer");
    cCu localcCu1 = new cCu();
    localcCu1.hg("wakfu.popupInfos:showPopup(firstRankReward,itemDetailPopup,rewardsContainer)");
    localdRq8.setOnPopupDisplay(localcCu1);
    jL localjL1 = new jL();
    localjL1.hg("closePopup");
    localdRq8.setOnPopupHide(localjL1);
    localdRq8.setNonBlocking(false);
    localdRq7.bb(localdRq8);
    localdRq8.brn();
    dRq localdRq9 = localdRq8;
    Jg localJg4 = localdRq9.getAppearance();
    localJg4.setElementMap(localcpa);
    localJg4.setModulationColor(new bNa(1.0F, 0.95F, 0.1F, 1.0F));
    localdRq8.bb(localJg4);
    localJg4.brn();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(10, 10, 10, 10));
    localJg4.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(0, 0, 7, 0));
    localJg4.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg4.rV();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setSize(new Or(-2, -2));
    localcwP4.setAlign(ajb.dhZ);
    localdRq8.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    dRq localdRq10 = dRq.checkOut();
    localdRq10.setElementMap(localcpa);
    localdRq8.bb(localdRq10);
    localdRq10.brn();
    czO localczO3 = new czO();
    localczO3.aJ();
    localczO3.setAdaptToContentSize(true);
    localdRq10.bb(localczO3);
    localczO3.brn();
    localczO3.rV();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setExpandable(false);
    localczv.setDisplaySize(new Or(32, 32));
    localdRq10.bb(localczv);
    localczv.brn();
    cwP localcwP5 = new cwP();
    localcwP5.aJ();
    localcwP5.setElementMap(localcpa);
    localcwP5.setSize(new Or(100.0F, 100.0F));
    localczv.bb(localcwP5);
    localcwP5.brn();
    localcwP5.rV();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv.bb(localaAR);
    localaAR.brn();
    NK localNK7 = NK.checkOut();
    localNK7.setElementMap(localcpa);
    localNK7.setLocal(true);
    localNK7.setAttribute("texture");
    localNK7.setName("shukruteReward");
    localNK7.setField("firstRankReward/item/iconUrl");
    localaAR.bb(localNK7);
    localNK7.brn();
    localNK7.rV();
    localaAR.rV();
    localczv.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setNonBlocking(true);
    localcaF1.setStyle("White10Bordered");
    localdRq10.bb(localcaF1);
    localcaF1.brn();
    NK localNK8 = NK.checkOut();
    localNK8.setElementMap(localcpa);
    localNK8.setLocal(true);
    localNK8.setAttribute("visible");
    localNK8.setName("shukruteReward");
    localNK8.setField("firstRankReward/quantity");
    localcaF1.bb(localNK8);
    localNK8.brn();
    anQ localanQ3 = new anQ();
    localanQ3.aJ();
    localanQ3.setElementMap(localcpa);
    localNK8.bb(localanQ3);
    localanQ3.brn();
    aEJ localaEJ = new aEJ();
    localaEJ.aJ();
    localaEJ.setElementMap(localcpa);
    localaEJ.setValue("1");
    localanQ3.bb(localaEJ);
    localaEJ.brn();
    localaEJ.rV();
    localanQ3.rV();
    localNK8.rV();
    cwP localcwP6 = new cwP();
    localcwP6.aJ();
    localcwP6.setElementMap(localcpa);
    localcwP6.setAlign(ajb.did);
    localcaF1.bb(localcwP6);
    localcwP6.brn();
    localcwP6.rV();
    caF localcaF2 = localcaF1;
    Jg localJg5 = localcaF2.getAppearance();
    localJg5.setElementMap(localcpa);
    localcaF1.bb(localJg5);
    localJg5.brn();
    bmv localbmv5 = bmv.checkOut();
    localbmv5.setElementMap(localcpa);
    localbmv5.setInsets(new Insets(0, 6, 6, 0));
    localJg5.bb(localbmv5);
    localbmv5.brn();
    localbmv5.rV();
    localJg5.rV();
    NK localNK9 = NK.checkOut();
    localNK9.setElementMap(localcpa);
    localNK9.setLocal(true);
    localNK9.setAttribute("text");
    localNK9.setName("shukruteReward");
    localNK9.setField("firstRankReward/quantity");
    localcaF1.bb(localNK9);
    localNK9.brn();
    localNK9.rV();
    localcaF1.rV();
    localdRq10.rV();
    localdRq8.rV();
    dRq localdRq11 = dRq.checkOut();
    localdRq11.setElementMap(localcpa);
    localdRq11.setStyle("encyclopediaSplashTitle");
    localdRq7.bb(localdRq11);
    localdRq11.brn();
    cwP localcwP7 = new cwP();
    localcwP7.aJ();
    localcwP7.setElementMap(localcpa);
    localcwP7.setSize(new Or(-2, -2));
    localcwP7.setAlign(ajb.dif);
    localdRq11.bb(localcwP7);
    localcwP7.brn();
    localcwP7.rV();
    dRq localdRq12 = localdRq11;
    Jg localJg6 = localdRq12.getAppearance();
    localJg6.setElementMap(localcpa);
    localdRq11.bb(localJg6);
    localJg6.brn();
    bmv localbmv6 = bmv.checkOut();
    localbmv6.setElementMap(localcpa);
    localbmv6.setInsets(new Insets(0, 10, 0, 0));
    localJg6.bb(localbmv6);
    localbmv6.brn();
    localbmv6.rV();
    cuR localcuR3 = new cuR();
    localcuR3.aJ();
    localcuR3.setElementMap(localcpa);
    localcuR3.setInsets(new Insets(5, 5, 7, 5));
    localJg6.bb(localcuR3);
    localcuR3.brn();
    localcuR3.rV();
    localJg6.rV();
    cWk localcWk3 = new cWk();
    localcWk3.aJ();
    localcWk3.setElementMap(localcpa);
    localcWk3.setStyle("whiteBold");
    String str5 = "%rank.1%";
    str5 = str5.replace("%rank.1%", cBQ.cxL().mL("rank.1"));
    localcWk3.setText(str5);
    localdRq11.bb(localcWk3);
    localcWk3.brn();
    NK localNK10 = NK.checkOut();
    localNK10.setElementMap(localcpa);
    localNK10.setLocal(true);
    localNK10.setAttribute("text");
    localNK10.setName("shukruteReward");
    localNK10.setField("firstRankReward/text");
    localcWk3.bb(localNK10);
    localNK10.brn();
    localNK10.rV();
    localcWk3.rV();
    localdRq11.rV();
    localdRq7.rV();
    dRq localdRq13 = dRq.checkOut();
    localdRq13.setElementMap(localcpa);
    localdRq5.bb(localdRq13);
    localdRq13.brn();
    NK localNK11 = NK.checkOut();
    localNK11.setElementMap(localcpa);
    localNK11.setLocal(true);
    localNK11.setAttribute("visible");
    localNK11.setName("shukruteReward");
    localNK11.setField("secondRankReward");
    localdRq13.bb(localNK11);
    localNK11.brn();
    anQ localanQ4 = new anQ();
    localanQ4.aJ();
    localanQ4.setElementMap(localcpa);
    localNK11.bb(localanQ4);
    localanQ4.brn();
    anE localanE3 = new anE();
    localanE3.aJ();
    localanE3.setElementMap(localcpa);
    localanQ4.bb(localanE3);
    localanE3.brn();
    localanE3.rV();
    localanQ4.rV();
    localNK11.rV();
    czO localczO4 = new czO();
    localczO4.aJ();
    localczO4.setAdaptToContentSize(true);
    localdRq13.bb(localczO4);
    localczO4.brn();
    localczO4.rV();
    dRq localdRq14 = dRq.checkOut();
    localdRq14.setElementMap(localcpa);
    localdRq14.setExpandable(false);
    localdRq14.setPrefSize(new Or(43, 43));
    localdRq14.setStyle("challengeRewardContainer");
    cCu localcCu2 = new cCu();
    localcCu2.hg("wakfu.popupInfos:showPopup(secondRankReward,itemDetailPopup,rewardsContainer)");
    localdRq14.setOnPopupDisplay(localcCu2);
    jL localjL2 = new jL();
    localjL2.hg("closePopup");
    localdRq14.setOnPopupHide(localjL2);
    localdRq14.setNonBlocking(false);
    localdRq13.bb(localdRq14);
    localdRq14.brn();
    dRq localdRq15 = localdRq14;
    Jg localJg7 = localdRq15.getAppearance();
    localJg7.setElementMap(localcpa);
    localJg7.setModulationColor(new bNa(0.4F, 0.34F, 0.23F, 1.0F));
    localdRq14.bb(localJg7);
    localJg7.brn();
    cuR localcuR4 = new cuR();
    localcuR4.aJ();
    localcuR4.setElementMap(localcpa);
    localcuR4.setInsets(new Insets(10, 10, 10, 10));
    localJg7.bb(localcuR4);
    localcuR4.brn();
    localcuR4.rV();
    bmv localbmv7 = bmv.checkOut();
    localbmv7.setElementMap(localcpa);
    localbmv7.setInsets(new Insets(0, 0, 7, 0));
    localJg7.bb(localbmv7);
    localbmv7.brn();
    localbmv7.rV();
    localJg7.rV();
    cwP localcwP8 = new cwP();
    localcwP8.aJ();
    localcwP8.setElementMap(localcpa);
    localcwP8.setSize(new Or(-2, -2));
    localcwP8.setAlign(ajb.dhZ);
    localdRq14.bb(localcwP8);
    localcwP8.brn();
    localcwP8.rV();
    h(localdRq14);
    i(localdRq14);
    localdRq14.rV();
    j(localdRq13);
    localdRq13.rV();
    k(localdRq5);
    localdRq5.rV();
    localdRq4.rV();
    localdRq2.rV();
    l(localdRq1);
    localdRq1.rV();
    return localdRq1;
  }

  public bdj h(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(false);
    parambdj.bb(localaId);
    localaId.brn();
    localaId.rV();
    return null;
  }

  public bdj i(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq = dRq.checkOut();
    localdRq.setElementMap(localcpa);
    parambdj.bb(localdRq);
    localdRq.brn();
    czO localczO = new czO();
    localczO.aJ();
    localczO.setAdaptToContentSize(true);
    localdRq.bb(localczO);
    localczO.brn();
    localczO.rV();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setExpandable(false);
    localczv.setDisplaySize(new Or(32, 32));
    localdRq.bb(localczv);
    localczv.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localczv.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv.bb(localaAR);
    localaAR.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setLocal(true);
    localNK1.setAttribute("texture");
    localNK1.setName("shukruteReward");
    localNK1.setField("secondRankReward/item/iconUrl");
    localaAR.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    localaAR.rV();
    localczv.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setNonBlocking(true);
    localcaF1.setStyle("White10Bordered");
    localdRq.bb(localcaF1);
    localcaF1.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setLocal(true);
    localNK2.setAttribute("visible");
    localNK2.setName("shukruteReward");
    localNK2.setField("secondRankReward/quantity");
    localcaF1.bb(localNK2);
    localNK2.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localNK2.bb(localanQ);
    localanQ.brn();
    aEJ localaEJ = new aEJ();
    localaEJ.aJ();
    localaEJ.setElementMap(localcpa);
    localaEJ.setValue("1");
    localanQ.bb(localaEJ);
    localaEJ.brn();
    localaEJ.rV();
    localanQ.rV();
    localNK2.rV();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.did);
    localcaF1.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    caF localcaF2 = localcaF1;
    Jg localJg = localcaF2.getAppearance();
    localJg.setElementMap(localcpa);
    localcaF1.bb(localJg);
    localJg.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(0, 6, 6, 0));
    localJg.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg.rV();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setLocal(true);
    localNK3.setAttribute("text");
    localNK3.setName("shukruteReward");
    localNK3.setField("secondRankReward/quantity");
    localcaF1.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    localcaF1.rV();
    localdRq.rV();
    return localdRq;
  }

  public bdj j(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setStyle("encyclopediaSplashTitle");
    parambdj.bb(localdRq1);
    localdRq1.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(-2, -2));
    localcwP.setAlign(ajb.dif);
    localdRq1.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    dRq localdRq2 = localdRq1;
    Jg localJg = localdRq2.getAppearance();
    localJg.setElementMap(localcpa);
    localdRq1.bb(localJg);
    localJg.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(0, 10, 0, 0));
    localJg.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    cuR localcuR = new cuR();
    localcuR.aJ();
    localcuR.setElementMap(localcpa);
    localcuR.setInsets(new Insets(5, 5, 7, 5));
    localJg.bb(localcuR);
    localcuR.brn();
    localcuR.rV();
    localJg.rV();
    cWk localcWk = new cWk();
    localcWk.aJ();
    localcWk.setElementMap(localcpa);
    localcWk.setStyle("whiteBold");
    String str = "%rank.2%";
    str = str.replace("%rank.2%", cBQ.cxL().mL("rank.2"));
    localcWk.setText(str);
    localdRq1.bb(localcWk);
    localcWk.brn();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setLocal(true);
    localNK.setAttribute("text");
    localNK.setName("shukruteReward");
    localNK.setField("secondRankReward/text");
    localcWk.bb(localNK);
    localNK.brn();
    localNK.rV();
    localcWk.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj k(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setLocal(true);
    localNK1.setAttribute("visible");
    localNK1.setName("shukruteReward");
    localNK1.setField("thirdRankReward");
    localdRq1.bb(localNK1);
    localNK1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localNK1.bb(localanQ1);
    localanQ1.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localanQ1.bb(localanE);
    localanE.brn();
    localanE.rV();
    localanQ1.rV();
    localNK1.rV();
    czO localczO1 = new czO();
    localczO1.aJ();
    localczO1.setAdaptToContentSize(true);
    localdRq1.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setExpandable(false);
    localdRq2.setPrefSize(new Or(43, 43));
    localdRq2.setStyle("challengeRewardContainer");
    cCu localcCu = new cCu();
    localcCu.hg("wakfu.popupInfos:showPopup(thirdRankReward,itemDetailPopup,rewardsContainer)");
    localdRq2.setOnPopupDisplay(localcCu);
    jL localjL = new jL();
    localjL.hg("closePopup");
    localdRq2.setOnPopupHide(localjL);
    localdRq2.setNonBlocking(false);
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localJg1.setModulationColor(new bNa(0.4F, 0.34F, 0.23F, 1.0F));
    localdRq2.bb(localJg1);
    localJg1.brn();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(10, 10, 10, 10));
    localJg1.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 0, 7, 0));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(-2, -2));
    localcwP1.setAlign(ajb.dhZ);
    localdRq2.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(false);
    localdRq2.bb(localaId);
    localaId.brn();
    localaId.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq2.bb(localdRq4);
    localdRq4.brn();
    czO localczO2 = new czO();
    localczO2.aJ();
    localczO2.setAdaptToContentSize(true);
    localdRq4.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setExpandable(false);
    localczv.setDisplaySize(new Or(32, 32));
    localdRq4.bb(localczv);
    localczv.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localczv.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv.bb(localaAR);
    localaAR.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setLocal(true);
    localNK2.setAttribute("texture");
    localNK2.setName("shukruteReward");
    localNK2.setField("thirdRankReward/item/iconUrl");
    localaAR.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localaAR.rV();
    localczv.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setNonBlocking(true);
    localcaF1.setStyle("White10Bordered");
    localdRq4.bb(localcaF1);
    localcaF1.brn();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setLocal(true);
    localNK3.setAttribute("visible");
    localNK3.setName("shukruteReward");
    localNK3.setField("thirdRankReward/quantity");
    localcaF1.bb(localNK3);
    localNK3.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localNK3.bb(localanQ2);
    localanQ2.brn();
    aEJ localaEJ = new aEJ();
    localaEJ.aJ();
    localaEJ.setElementMap(localcpa);
    localaEJ.setValue("1");
    localanQ2.bb(localaEJ);
    localaEJ.brn();
    localaEJ.rV();
    localanQ2.rV();
    localNK3.rV();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setAlign(ajb.did);
    localcaF1.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    caF localcaF2 = localcaF1;
    Jg localJg2 = localcaF2.getAppearance();
    localJg2.setElementMap(localcpa);
    localcaF1.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 6, 6, 0));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa);
    localNK4.setLocal(true);
    localNK4.setAttribute("text");
    localNK4.setName("shukruteReward");
    localNK4.setField("thirdRankReward/quantity");
    localcaF1.bb(localNK4);
    localNK4.brn();
    localNK4.rV();
    localcaF1.rV();
    localdRq4.rV();
    localdRq2.rV();
    dRq localdRq5 = dRq.checkOut();
    localdRq5.setElementMap(localcpa);
    localdRq5.setStyle("encyclopediaSplashTitle");
    localdRq1.bb(localdRq5);
    localdRq5.brn();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setSize(new Or(-2, -2));
    localcwP4.setAlign(ajb.dif);
    localdRq5.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    dRq localdRq6 = localdRq5;
    Jg localJg3 = localdRq6.getAppearance();
    localJg3.setElementMap(localcpa);
    localdRq5.bb(localJg3);
    localJg3.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 10, 0, 0));
    localJg3.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(5, 5, 7, 5));
    localJg3.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    localJg3.rV();
    cWk localcWk = new cWk();
    localcWk.aJ();
    localcWk.setElementMap(localcpa);
    localcWk.setStyle("whiteBold");
    String str = "%rank.3%";
    str = str.replace("%rank.3%", cBQ.cxL().mL("rank.3"));
    localcWk.setText(str);
    localdRq5.bb(localcWk);
    localcWk.brn();
    NK localNK5 = NK.checkOut();
    localNK5.setElementMap(localcpa);
    localNK5.setLocal(true);
    localNK5.setAttribute("text");
    localNK5.setName("shukruteReward");
    localNK5.setField("thirdRankReward/text");
    localcWk.bb(localNK5);
    localNK5.brn();
    localNK5.rV();
    localcWk.rV();
    localdRq5.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj l(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setStyle("AchievementUnlockedSplash");
    parambdj.bb(localdRq1);
    localdRq1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(311, 135));
    localcwP1.setAlign(ajb.dhT);
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    czO localczO = new czO();
    localczO.aJ();
    localdRq1.bb(localczO);
    localczO.brn();
    localczO.rV();
    dRq localdRq2 = localdRq1;
    Jg localJg1 = localdRq2.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq1.bb(localJg1);
    localJg1.brn();
    localJg1.rV();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setStyle("challengeBigIcon");
    localdRq1.bb(localczv);
    localczv.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setSize(new Or(-2, -2));
    localcwP2.setAlign(ajb.dhR);
    localcwP2.setXOffset(20);
    localcwP2.setYOffset(-23);
    localczv.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    localczv.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setExpandable(false);
    String str = "%shukrute.rewards%";
    str = str.replace("%shukrute.rewards%", cBQ.cxL().mL("shukrute.rewards"));
    localcaF1.setText(str);
    localcaF1.setStyle("title");
    localcaF1.setNonBlocking(true);
    localdRq1.bb(localcaF1);
    localcaF1.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setSize(new Or(230, -2));
    localcwP3.setAlign(ajb.dhR);
    localcwP3.setXOffset(70);
    localcwP3.setYOffset(-50);
    localcaF1.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    caF localcaF2 = localcaF1;
    Jg localJg2 = localcaF2.getAppearance();
    localJg2.setElementMap(localcpa);
    ((cwJ)localJg2).setAlign(aFG.ecj);
    localcaF1.bb(localJg2);
    localJg2.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(0, 0, 0, 0));
    localJg2.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    cAf localcAf = cAf.checkOut();
    localcAf.setElementMap(localcpa);
    localcAf.setName("text");
    localcAf.setColor(new bNa(0.75F, 1.0F, 0.55F, 1.0F));
    localJg2.bb(localcAf);
    localcAf.brn();
    localcAf.rV();
    localJg2.rV();
    localcaF1.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("StyledBoldWhite12");
    localcWk1.setText("");
    localcWk1.setMinWidth(1);
    localcWk1.setMaxWidth(250);
    localcWk1.setNonBlocking(true);
    localdRq1.bb(localcWk1);
    localcWk1.brn();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setSize(new Or(250, -2));
    localcwP4.setAlign(ajb.dhT);
    localcwP4.setYOffset(-77);
    localcWk1.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    cWk localcWk2 = localcWk1;
    Jg localJg3 = localcWk2.getAppearance();
    localJg3.setElementMap(localcpa);
    ((cwJ)localJg3).setAlign(aFG.eck);
    localcWk1.bb(localJg3);
    localJg3.brn();
    localJg3.rV();
    localcWk1.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj m(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    biy localbiy1 = new biy();
    localbiy1.aJ();
    localbiy1.setElementMap(localcpa);
    localbiy1.setStyle("close");
    localbiy1.setExpandable(false);
    csA localcsA = new csA();
    localcsA.hg("wakfu.shukrute:closeDialog");
    localbiy1.setOnClick(localcsA);
    parambdj.bb(localbiy1);
    localbiy1.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setAlign(ajb.dhV);
    localcwP.setYOffset(-42);
    localcwP.setXOffset(-19);
    localbiy1.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    biy localbiy2 = localbiy1;
    Jg localJg = localbiy2.getAppearance();
    localJg.setElementMap(localcpa);
    localbiy1.bb(localJg);
    localJg.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(10, 0, 0, 10));
    localJg.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg.rV();
    localbiy1.rV();
    return localbiy1;
  }
}