import java.util.Stack;

public class Id
  implements aTK
{
  private uk W;
  private Stack X = new Stack();

  public void a(cpa paramcpa, uk paramuk, dOc paramdOc)
  {
    this.W = paramuk;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    dOc localdOc = paramdOc;
    Jg localJg = localdOc.getAppearance();
    localJg.setElementMap(localcpa);
    paramdOc.bb(localJg);
    localJg.brn();
    Cx localCx = new Cx();
    localCx.aJ();
    localCx.setElementMap(localcpa);
    localJg.bb(localCx);
    localCx.brn();
    aAR localaAR1 = aAR.checkOut();
    localaAR1.setElementMap(localcpa);
    localaAR1.setPosition(ajb.dhR);
    localaAR1.setX(916);
    localaAR1.setY(892);
    localaAR1.setWidth(24);
    localaAR1.setHeight(130);
    localaAR1.setTexture(this.W.aH("preWorld_0.tga"));
    localCx.bb(localaAR1);
    localaAR1.brn();
    localaAR1.rV();
    aAR localaAR2 = aAR.checkOut();
    localaAR2.setElementMap(localcpa);
    localaAR2.setPosition(ajb.dhT);
    localaAR2.setX(423);
    localaAR2.setY(507);
    localaAR2.setWidth(253);
    localaAR2.setHeight(130);
    localaAR2.setTexture(this.W.aH("preWorld_2.tga"));
    localCx.bb(localaAR2);
    localaAR2.brn();
    localaAR2.rV();
    aAR localaAR3 = aAR.checkOut();
    localaAR3.setElementMap(localcpa);
    localaAR3.setPosition(ajb.dhV);
    localaAR3.setX(943);
    localaAR3.setY(892);
    localaAR3.setWidth(24);
    localaAR3.setHeight(130);
    localaAR3.setTexture(this.W.aH("preWorld_0.tga"));
    localCx.bb(localaAR3);
    localaAR3.brn();
    localaAR3.rV();
    aAR localaAR4 = aAR.checkOut();
    localaAR4.setElementMap(localcpa);
    localaAR4.setPosition(ajb.dhY);
    localaAR4.setX(951);
    localaAR4.setY(242);
    localaAR4.setWidth(24);
    localaAR4.setHeight(68);
    localaAR4.setTexture(this.W.aH("preWorld_0.tga"));
    localCx.bb(localaAR4);
    localaAR4.brn();
    localaAR4.rV();
    aAR localaAR5 = aAR.checkOut();
    localaAR5.setElementMap(localcpa);
    localaAR5.setPosition(ajb.dia);
    localaAR5.setX(924);
    localaAR5.setY(242);
    localaAR5.setWidth(24);
    localaAR5.setHeight(68);
    localaAR5.setTexture(this.W.aH("preWorld_0.tga"));
    localCx.bb(localaAR5);
    localaAR5.brn();
    localaAR5.rV();
    aAR localaAR6 = aAR.checkOut();
    localaAR6.setElementMap(localcpa);
    localaAR6.setPosition(ajb.did);
    localaAR6.setX(978);
    localaAR6.setY(244);
    localaAR6.setWidth(24);
    localaAR6.setHeight(66);
    localaAR6.setTexture(this.W.aH("preWorld_0.tga"));
    localCx.bb(localaAR6);
    localaAR6.brn();
    localaAR6.rV();
    aAR localaAR7 = aAR.checkOut();
    localaAR7.setElementMap(localcpa);
    localaAR7.setPosition(ajb.dif);
    localaAR7.setX(258);
    localaAR7.setY(184);
    localaAR7.setWidth(253);
    localaAR7.setHeight(66);
    localaAR7.setTexture(this.W.aH("preWorld_2.tga"));
    localCx.bb(localaAR7);
    localaAR7.brn();
    localaAR7.rV();
    aAR localaAR8 = aAR.checkOut();
    localaAR8.setElementMap(localcpa);
    localaAR8.setPosition(ajb.dih);
    localaAR8.setX(213);
    localaAR8.setY(243);
    localaAR8.setWidth(24);
    localaAR8.setHeight(66);
    localaAR8.setTexture(this.W.aH("preWorld_0.tga"));
    localCx.bb(localaAR8);
    localaAR8.brn();
    localaAR8.rV();
    localCx.rV();
    aen localaen = aen.checkOut();
    localaen.setElementMap(localcpa);
    localaen.setScaled(true);
    localJg.bb(localaen);
    localaen.brn();
    aAR localaAR9 = aAR.checkOut();
    localaAR9.setElementMap(localcpa);
    localaAR9.setPosition(ajb.dhZ);
    localaAR9.setX(2);
    localaAR9.setY(182);
    localaAR9.setWidth(253);
    localaAR9.setHeight(68);
    localaAR9.setTexture(this.W.aH("preWorld_2.tga"));
    localaen.bb(localaAR9);
    localaAR9.brn();
    localaAR9.rV();
    localaen.rV();
    localJg.rV();
  }
}