import java.awt.Insets;
import java.util.Stack;

public class dJX
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    bpn localbpn = new bpn();
    localbpn.aJ();
    localbpn.setElementMap(localcpa);
    localbpn.setStyle("chat");
    localbpn.setNonBlocking(true);
    localbpn.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setAlign(ajb.dia);
    localcwP1.setInitValue(true);
    localcwP1.setXOffset(-10);
    localbpn.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setStyle("popup");
    localdRq1.setPrefSize(new Or(180, 100));
    localdRq1.setNonBlocking(true);
    localbpn.bb(localdRq1);
    localdRq1.brn();
    czO localczO = new czO();
    localczO.aJ();
    localczO.setAdaptToContentSize(true);
    localdRq1.bb(localczO);
    localczO.brn();
    localczO.rV();
    dRq localdRq2 = localdRq1;
    Jg localJg1 = localdRq2.getAppearance();
    localJg1.setElementMap(localcpa);
    localJg1.setModulationColor(new bNa(1.0F, 1.0F, 1.0F, 0.5F));
    localdRq1.bb(localJg1);
    localJg1.brn();
    localJg1.rV();
    dqa localdqa = new dqa();
    localdqa.aJ();
    localdqa.setElementMap(localcpa);
    localdqa.setNonBlocking(true);
    localdRq1.bb(localdqa);
    localdqa.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localdqa.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    bbp localbbp = new bbp();
    localbbp.aJ();
    localbbp.setElementMap(localcpa);
    localbbp.setNonBlocking(true);
    localbbp.setPrefSize(new Or(150, 100));
    localdqa.bb(localbbp);
    localbbp.brn();
    cWk localcWk = new cWk();
    localcWk.aJ();
    localcWk.setElementMap(localcpa);
    localcWk.setEnableOnlySelectablePartInteraction(true);
    localcWk.setStyle("white14Bordered");
    localcWk.setNonBlocking(false);
    localcWk.setVerticalAlignment(aFE.ecb);
    csA localcsA = new csA();
    localcsA.hg("wakfu.chat:processLinkAction(chatView)");
    localcWk.setOnClick(localcsA);
    bDy localbDy = new bDy();
    localbDy.hg("wakfu.chat:processLinkAction(chatView)");
    localcWk.setOnMouseEnter(localbDy);
    DY localDY = new DY();
    localDY.hg("wakfu.chat:onMouseExitSelectableText");
    localcWk.setOnMouseExit(localDY);
    localcWk.setPrefSize(new Or(0, 100));
    localbbp.bb(localcWk);
    localcWk.brn();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setLocal(true);
    localNK.setName("chat");
    localNK.setField("currentView/history");
    localNK.setAttribute("text");
    localcWk.bb(localNK);
    localNK.brn();
    localNK.rV();
    localcWk.rV();
    localbbp.rV();
    localdqa.rV();
    WV localWV1 = new WV();
    localWV1.aJ();
    localWV1.setElementMap(localcpa);
    localWV1.setPointAlign(aFG.ech);
    localWV1.setPrefSize(new Or(0, 15));
    localdRq1.bb(localWV1);
    localWV1.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setAlign(ajb.dhT);
    localcwP3.setSize(new Or(100.0F, -2));
    localcwP3.setYOffset(5);
    localWV1.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    WV localWV2 = localWV1;
    Jg localJg2 = localWV2.getAppearance();
    localJg2.setElementMap(localcpa);
    localWV1.bb(localJg2);
    localJg2.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 15, 0, 15));
    localJg2.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg2.rV();
    localWV1.rV();
    WV localWV3 = new WV();
    localWV3.aJ();
    localWV3.setElementMap(localcpa);
    localWV3.setPointAlign(aFG.ecn);
    localWV3.setPrefSize(new Or(0, 15));
    localdRq1.bb(localWV3);
    localWV3.brn();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setAlign(ajb.dif);
    localcwP4.setSize(new Or(100.0F, -2));
    localcwP4.setYOffset(-5);
    localWV3.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    WV localWV4 = localWV3;
    Jg localJg3 = localWV4.getAppearance();
    localJg3.setElementMap(localcpa);
    localWV3.bb(localJg3);
    localJg3.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 15, 0, 15));
    localJg3.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg3.rV();
    localWV3.rV();
    WV localWV5 = new WV();
    localWV5.aJ();
    localWV5.setElementMap(localcpa);
    localWV5.setPointAlign(aFG.ecl);
    localWV5.setPrefSize(new Or(10, 0));
    localdRq1.bb(localWV5);
    localWV5.brn();
    cwP localcwP5 = new cwP();
    localcwP5.aJ();
    localcwP5.setElementMap(localcpa);
    localcwP5.setAlign(ajb.dia);
    localcwP5.setSize(new Or(-2, 100.0F));
    localcwP5.setXOffset(10);
    localWV5.bb(localcwP5);
    localcwP5.brn();
    localcwP5.rV();
    localWV5.rV();
    WV localWV6 = new WV();
    localWV6.aJ();
    localWV6.setElementMap(localcpa);
    localWV6.setPointAlign(aFG.ecj);
    localWV6.setPrefSize(new Or(15, 0));
    localdRq1.bb(localWV6);
    localWV6.brn();
    cwP localcwP6 = new cwP();
    localcwP6.aJ();
    localcwP6.setElementMap(localcpa);
    localcwP6.setAlign(ajb.dhY);
    localcwP6.setSize(new Or(-2, 100.0F));
    localcwP6.setXOffset(-5);
    localWV6.bb(localcwP6);
    localcwP6.brn();
    localcwP6.rV();
    localWV6.rV();
    WV localWV7 = new WV();
    localWV7.aJ();
    localWV7.setElementMap(localcpa);
    localWV7.setPointAlign(aFG.eci);
    localWV7.setPrefSize(new Or(15, 15));
    localdRq1.bb(localWV7);
    localWV7.brn();
    cwP localcwP7 = new cwP();
    localcwP7.aJ();
    localcwP7.setElementMap(localcpa);
    localcwP7.setAlign(ajb.dhV);
    localcwP7.setSize(new Or(-2, -2));
    localcwP7.setYOffset(5);
    localcwP7.setXOffset(5);
    localWV7.bb(localcwP7);
    localcwP7.brn();
    localcwP7.rV();
    localWV7.rV();
    WV localWV8 = new WV();
    localWV8.aJ();
    localWV8.setElementMap(localcpa);
    localWV8.setPointAlign(aFG.ecg);
    localWV8.setPrefSize(new Or(15, 15));
    localdRq1.bb(localWV8);
    localWV8.brn();
    cwP localcwP8 = new cwP();
    localcwP8.aJ();
    localcwP8.setElementMap(localcpa);
    localcwP8.setAlign(ajb.dhR);
    localcwP8.setSize(new Or(-2, -2));
    localcwP8.setYOffset(5);
    localcwP8.setXOffset(-5);
    localWV8.bb(localcwP8);
    localcwP8.brn();
    localcwP8.rV();
    localWV8.rV();
    WV localWV9 = new WV();
    localWV9.aJ();
    localWV9.setElementMap(localcpa);
    localWV9.setPointAlign(aFG.eco);
    localWV9.setPrefSize(new Or(15, 15));
    localdRq1.bb(localWV9);
    localWV9.brn();
    cwP localcwP9 = new cwP();
    localcwP9.aJ();
    localcwP9.setElementMap(localcpa);
    localcwP9.setAlign(ajb.dih);
    localcwP9.setSize(new Or(-2, -2));
    localcwP9.setYOffset(-5);
    localcwP9.setXOffset(5);
    localWV9.bb(localcwP9);
    localcwP9.brn();
    localcwP9.rV();
    localWV9.rV();
    WV localWV10 = new WV();
    localWV10.aJ();
    localWV10.setElementMap(localcpa);
    localWV10.setPointAlign(aFG.ecm);
    localWV10.setPrefSize(new Or(15, 15));
    localdRq1.bb(localWV10);
    localWV10.brn();
    cwP localcwP10 = new cwP();
    localcwP10.aJ();
    localcwP10.setElementMap(localcpa);
    localcwP10.setAlign(ajb.did);
    localcwP10.setSize(new Or(-2, -2));
    localcwP10.setYOffset(-5);
    localcwP10.setXOffset(-5);
    localWV10.bb(localcwP10);
    localcwP10.brn();
    localcwP10.rV();
    localWV10.rV();
    localdRq1.rV();
    localbpn.rV();
    return localbpn;
  }
}