import java.awt.Insets;
import java.util.Stack;

public class cDC
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    dxn localdxn = new dxn();
    localdxn.aJ();
    localdxn.setElementMap(localcpa);
    localdxn.setYOffset(0);
    localdxn.setXOffset(0);
    localdxn.setPack(true);
    localdxn.setAlign(aFG.ech);
    localdxn.setNonBlocking(true);
    localdxn.brn();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setNonBlocking(true);
    localdxn.bb(localdRq1);
    localdRq1.brn();
    aId localaId = aId.checkOut();
    localdRq1.bb(localaId);
    localaId.brn();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setStyle("characterBookBar");
    localdRq2.setPrefSize(new Or(14, 18));
    localdRq2.setNonBlocking(true);
    localaId.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(8, 0, 7, 0));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setLocal(true);
    localNK1.setName("collectInProgress");
    localNK1.setField("slots");
    localNK1.setAttribute("visible");
    localdRq2.bb(localNK1);
    localNK1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localNK1.bb(localanQ1);
    localanQ1.brn();
    dDu localdDu = new dDu();
    localdDu.aJ();
    localdDu.setElementMap(localcpa);
    localanQ1.bb(localdDu);
    localdDu.brn();
    bSP localbSP = new bSP();
    localbSP.aJ();
    localbSP.setElementMap(localcpa);
    localbSP.setValue("0");
    localdDu.bb(localbSP);
    localbSP.brn();
    localbSP.rV();
    localdDu.rV();
    localanQ1.rV();
    localNK1.rV();
    aEY localaEY1 = new aEY();
    localaEY1.aJ();
    localaEY1.setElementMap(localcpa);
    localaEY1.setStyle("CollectNumberCharacters");
    localaEY1.setNonBlocking(true);
    localdRq2.bb(localaEY1);
    localaEY1.brn();
    aEY localaEY2 = localaEY1;
    Jg localJg2 = localaEY2.getAppearance();
    localJg2.setElementMap(localcpa);
    localaEY1.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 2, 0, 0));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setLocal(true);
    localNK2.setName("collectInProgress");
    localNK2.setField("slots");
    localNK2.setAttribute("repeatNumber");
    localaEY1.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localaEY1.rV();
    aEY localaEY3 = new aEY();
    localaEY3.aJ();
    localaEY3.setElementMap(localcpa);
    localaEY3.setStyle("waitOthers");
    localaEY3.setNonBlocking(true);
    localaEY3.setPrefSize(new Or(10, 18));
    localdRq2.bb(localaEY3);
    localaEY3.brn();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setLocal(true);
    localNK3.setName("collectInProgress");
    localNK3.setField("wait");
    localNK3.setAttribute("visible");
    localaEY3.bb(localNK3);
    localNK3.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localNK3.bb(localanQ2);
    localanQ2.brn();
    cOk localcOk = new cOk();
    localcOk.aJ();
    localcOk.setElementMap(localcpa);
    localanQ2.bb(localcOk);
    localcOk.brn();
    localcOk.rV();
    localanQ2.rV();
    localNK3.rV();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa);
    localNK4.setLocal(true);
    localNK4.setName("collectInProgress");
    localNK4.setField("drawNumber");
    localNK4.setAttribute("repeatNumber");
    localaEY3.bb(localNK4);
    localNK4.brn();
    localNK4.rV();
    localaEY3.rV();
    localdRq2.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setPrefSize(new Or(120, 40));
    localdRq4.setNonBlocking(true);
    localaId.bb(localdRq4);
    localdRq4.brn();
    czO localczO1 = new czO();
    localczO1.aJ();
    localdRq4.bb(localczO1);
    localczO1.brn();
    dRq localdRq5 = dRq.checkOut();
    localdRq5.setElementMap(localcpa);
    localdRq5.setStyle("ProgressBarCollect");
    localdRq5.setPrefSize(new Or(100, 40));
    localdRq5.setNonBlocking(true);
    localczO1.bb(localdRq5);
    localdRq5.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setX(0);
    localcwP1.setY(0);
    localcwP1.setSize(new Or(120, 40));
    localdRq5.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    localdRq5.rV();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq6.setPrefSize(new Or(16, 16));
    localdRq6.setNonBlocking(true);
    localczO1.bb(localdRq6);
    localdRq6.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setX(9);
    localcwP2.setY(11);
    localcwP2.setSize(new Or(16, 16));
    localdRq6.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setDisplaySize(new Or(16, 16));
    localczv.setScaled(true);
    localczv.setNonBlocking(true);
    localdRq6.bb(localczv);
    localczv.brn();
    NK localNK5 = NK.checkOut();
    localNK5.setElementMap(localcpa);
    localNK5.setAttribute("style");
    localNK5.setLocal(true);
    localNK5.setField("iconskill");
    localNK5.setName("collectInProgress");
    localczv.bb(localNK5);
    localNK5.brn();
    localNK5.rV();
    localczv.rV();
    localdRq6.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localdRq7.setExpandable(false);
    localczO1.bb(localdRq7);
    localdRq7.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setX(27);
    localcwP3.setY(0);
    localcwP3.setSize(new Or(82, 40));
    localdRq7.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    dRq localdRq8 = localdRq7;
    Jg localJg3 = localdRq8.getAppearance();
    localJg3.setElementMap(localcpa);
    localdRq7.bb(localJg3);
    localJg3.brn();
    cuR localcuR = new cuR();
    localcuR.aJ();
    localcuR.setElementMap(localcpa);
    localcuR.setInsets(new Insets(0, 5, 0, 0));
    localJg3.bb(localcuR);
    localcuR.brn();
    localcuR.rV();
    localJg3.rV();
    czO localczO2 = new czO();
    localczO2.aJ();
    localczO2.setAdaptToContentSize(true);
    localdRq7.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    String str1 = "progressBarWait";
    alP localalP1 = new alP();
    localalP1.aJ();
    localalP1.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localalP1);
    localalP1.setStyle("XP2");
    localalP1.setNonBlocking(true);
    localdRq7.bb(localalP1);
    localalP1.brn();
    alP localalP2 = localalP1;
    Jg localJg4 = localalP2.getAppearance();
    localJg4.setElementMap(localcpa);
    localalP1.bb(localJg4);
    localJg4.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(1, 1, 1, 1));
    localJg4.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    cAf localcAf = cAf.checkOut();
    localcAf.setElementMap(localcpa);
    localcAf.setName("progressBar");
    localcAf.setColor(new bNa(0.8F, 0.1F, 0.1F, 1.0F));
    localJg4.bb(localcAf);
    localcAf.brn();
    localcAf.rV();
    localJg4.rV();
    NK localNK6 = NK.checkOut();
    localNK6.setElementMap(localcpa);
    localNK6.setLocal(true);
    localNK6.setName("collectInProgress");
    localNK6.setField("wait");
    localNK6.setAttribute("visible");
    localalP1.bb(localNK6);
    localNK6.brn();
    localNK6.rV();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setSize(new Or(100.0F, 15));
    localcwP4.setAlign(ajb.dhZ);
    localcwP4.setYOffset(-1);
    localalP1.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    localalP1.rV();
    String str2 = "progressBar";
    alP localalP3 = new alP();
    localalP3.aJ();
    localalP3.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localalP3);
    localalP3.setStyle("XP2");
    localalP3.setNonBlocking(true);
    localdRq7.bb(localalP3);
    localalP3.brn();
    alP localalP4 = localalP3;
    Jg localJg5 = localalP4.getAppearance();
    localJg5.setElementMap(localcpa);
    localalP3.bb(localJg5);
    localJg5.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(1, 1, 1, 1));
    localJg5.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg5.rV();
    NK localNK7 = NK.checkOut();
    localNK7.setElementMap(localcpa);
    localNK7.setLocal(true);
    localNK7.setName("collectInProgress");
    localNK7.setField("wait");
    localNK7.setAttribute("visible");
    localalP3.bb(localNK7);
    localNK7.brn();
    anQ localanQ3 = new anQ();
    localanQ3.aJ();
    localanQ3.setElementMap(localcpa);
    localNK7.bb(localanQ3);
    localanQ3.brn();
    bqW localbqW = new bqW();
    localbqW.aJ();
    localbqW.setElementMap(localcpa);
    localanQ3.bb(localbqW);
    localbqW.brn();
    localbqW.rV();
    localanQ3.rV();
    localNK7.rV();
    cwP localcwP5 = new cwP();
    localcwP5.aJ();
    localcwP5.setElementMap(localcpa);
    localcwP5.setSize(new Or(100.0F, 15));
    localcwP5.setAlign(ajb.dhZ);
    localcwP5.setYOffset(-1);
    localalP3.bb(localcwP5);
    localcwP5.brn();
    localcwP5.rV();
    localalP3.rV();
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa);
    localdRq9.setStyle("ProgressBar");
    localdRq9.setNonBlocking(true);
    localdRq7.bb(localdRq9);
    localdRq9.brn();
    cwP localcwP6 = new cwP();
    localcwP6.aJ();
    localcwP6.setElementMap(localcpa);
    localcwP6.setSize(new Or(100.0F, 15));
    localcwP6.setAlign(ajb.dhZ);
    localcwP6.setYOffset(-1);
    localdRq9.bb(localcwP6);
    localcwP6.brn();
    localcwP6.rV();
    localdRq9.rV();
    localdRq7.rV();
    localczO1.rV();
    localdRq4.rV();
    localaId.rV();
    localdRq1.rV();
    localdxn.rV();
    return localdxn;
  }
}