import java.awt.Insets;
import java.util.Stack;

public class aCb
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    String str1 = "dimensionalBagWindow";
    bpn localbpn = new bpn();
    localbpn.aJ();
    localbpn.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localbpn);
    localbpn.setPack(true);
    localbpn.brn();
    czO localczO1 = new czO();
    localczO1.aJ();
    localczO1.setAdaptToContentSize(true);
    localbpn.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localbpn.bb(localdRq1);
    localdRq1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    localdRq1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setStyle("windowNew");
    localbpn.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(10, 5, 12, 5));
    localJg1.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    localJg1.rV();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localdRq2.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localaId1.setAlign(aFG.ech);
    localdRq2.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dqa localdqa1 = new dqa();
    localdqa1.aJ();
    localdqa1.setElementMap(localcpa);
    localdqa1.setExpandable(false);
    localdRq2.bb(localdqa1);
    localdqa1.brn();
    dqa localdqa2 = localdqa1;
    Jg localJg2 = localdqa2.getAppearance();
    localJg2.setElementMap(localcpa);
    localdqa1.bb(localJg2);
    localJg2.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 10, 0, 10));
    localJg2.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg2.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setStyle("titleBar");
    localdqa1.bb(localdRq4);
    localdRq4.brn();
    dRq localdRq5 = localdRq4;
    Jg localJg3 = localdRq5.getAppearance();
    localJg3.setElementMap(localcpa);
    localdRq4.bb(localJg3);
    localJg3.brn();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(2, 20, 3, 20));
    localJg3.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    localJg3.rV();
    aId localaId2 = aId.checkOut();
    localaId2.setAlign(aFG.ecj);
    localdRq4.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setExpandable(false);
    localczv1.setNonBlocking(true);
    localczv1.setDisplaySize(new Or(32, 32));
    localdRq4.bb(localczv1);
    localczv1.brn();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv1.bb(localaAR);
    localaAR.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setName("editableDimensionalBag");
    localNK1.setAttribute("texture");
    localNK1.setField("currentFlea/iconUrl");
    localaAR.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    localaAR.rV();
    localczv1.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("StyledBold16White");
    localcWk1.setPrefSize(new Or(0, 18));
    localcWk1.setMaxWidth(340);
    localcWk1.setExpandable(false);
    localcWk1.setNonBlocking(true);
    localdRq4.bb(localcWk1);
    localcWk1.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("editableDimensionalBag");
    localNK2.setAttribute("text");
    localNK2.setField("currentFlea/fleaTitle");
    localcWk1.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    cWk localcWk2 = localcWk1;
    Jg localJg4 = localcWk2.getAppearance();
    localJg4.setElementMap(localcpa);
    localcWk1.bb(localJg4);
    localJg4.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 5, 0, 0));
    localJg4.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg4.rV();
    localcWk1.rV();
    czv localczv2 = new czv();
    localczv2.aJ();
    localczv2.setElementMap(localcpa);
    localczv2.setStyle("fleaMarketRegistered");
    localczv2.setExpandable(false);
    cCu localcCu1 = new cCu();
    localcCu1.hg("popup(registeredToMarketPopup)");
    localczv2.setOnPopupDisplay(localcCu1);
    jL localjL1 = new jL();
    localjL1.hg("closePopup");
    localczv2.setOnPopupHide(localjL1);
    localdRq4.bb(localczv2);
    localczv2.brn();
    String str2 = "registeredToMarketPopup";
    anG localanG1 = new anG();
    localanG1.aJ();
    localanG1.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localanG1);
    localanG1.setAlign(aFG.ech);
    localanG1.setHotSpotPosition(aFG.ecn);
    localczv2.bb(localanG1);
    localanG1.brn();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq6.setPrefSize(new Or(10, 0));
    localdRq6.setStyle("popup");
    localanG1.bb(localdRq6);
    localdRq6.brn();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("PopupInformation");
    String str3 = "%market.registered%";
    str3 = str3.replace("%market.registered%", cBQ.cxL().mL("market.registered"));
    localcaF1.setText(str3);
    localdRq6.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg5 = localcaF2.getAppearance();
    localJg5.setElementMap(localcpa);
    ((cwJ)localJg5).setAlignment(aFG.ecj);
    localcaF1.bb(localJg5);
    localJg5.brn();
    localJg5.rV();
    localcaF1.rV();
    localdRq6.rV();
    localanG1.rV();
    czv localczv3 = localczv2;
    Jg localJg6 = localczv3.getAppearance();
    localJg6.setElementMap(localcpa);
    localczv2.bb(localJg6);
    localJg6.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 0, 0, 5));
    localJg6.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg6.rV();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setName("editableDimensionalBag");
    localNK3.setAttribute("visible");
    localNK3.setField("currentFlea/fleaMarketRegistered");
    localczv2.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    localczv2.rV();
    localdRq4.rV();
    localdqa1.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localdRq2.bb(localdRq7);
    localdRq7.brn();
    dRq localdRq8 = localdRq7;
    Jg localJg7 = localdRq8.getAppearance();
    localJg7.setElementMap(localcpa);
    localdRq7.bb(localJg7);
    localJg7.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(0, 12, 0, 12));
    localJg7.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg7.rV();
    String str4 = "windowContentContainer";
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa);
    if ((localcpa != null) && (str4 != null))
      localcpa.a(str4, localdRq9);
    localdRq7.bb(localdRq9);
    localdRq9.brn();
    aId localaId3 = aId.checkOut();
    localaId3.setAlign(aFG.ech);
    localaId3.setHorizontal(false);
    localdRq9.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    cWk localcWk3 = new cWk();
    localcWk3.aJ();
    localcWk3.setElementMap(localcpa);
    localcWk3.setExpandable(false);
    localdRq9.bb(localcWk3);
    localcWk3.brn();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa);
    localNK4.setAttribute("text");
    localNK4.setField("currentFlea/bagType");
    localNK4.setName("editableDimensionalBag");
    localcWk3.bb(localNK4);
    localNK4.brn();
    localNK4.rV();
    NK localNK5 = NK.checkOut();
    localNK5.setElementMap(localcpa);
    localNK5.setAttribute("visible");
    localNK5.setField("currentFlea/bagType");
    localNK5.setName("editableDimensionalBag");
    localcWk3.bb(localNK5);
    localNK5.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localNK5.bb(localanQ1);
    localanQ1.brn();
    anE localanE1 = new anE();
    localanE1.aJ();
    localanE1.setElementMap(localcpa);
    localanQ1.bb(localanE1);
    localanE1.brn();
    localanE1.rV();
    localanQ1.rV();
    localNK5.rV();
    localcWk3.rV();
    String str5 = "fleaList";
    ccG localccG = new ccG();
    localccG.aJ();
    localccG.setElementMap(localcpa);
    if ((localcpa != null) && (str5 != null))
      localcpa.a(str5, localccG);
    localccG.setNonBlocking(false);
    localccG.setHorizontal(false);
    localccG.setCellSize(new Or(100.0F, 45));
    localccG.setPrefSize(new Or(300, 0));
    localccG.setAutoIdealSize(true);
    localccG.setIdealSizeMinColumns(1);
    localccG.setIdealSizeMaxColumns(1);
    localccG.setIdealSizeMinRows(1);
    localccG.setIdealSizeMaxRows(10);
    localdRq9.bb(localccG);
    localccG.brn();
    NK localNK6 = NK.checkOut();
    localNK6.setElementMap(localcpa);
    localNK6.setName("editableDimensionalBag");
    localNK6.setAttribute("content");
    localNK6.setField("currentFlea/browsingBagInventory");
    localccG.bb(localNK6);
    localNK6.brn();
    localNK6.rV();
    eR localeR = new eR();
    localeR.aJ();
    localeR.setElementMap(localcpa);
    aqC localaqC = new aqC();
    localaqC.hg("wakfu:openItemDetailWindow(dimensionalBagWindow)");
    localeR.setOnItemClick(localaqC);
    localccG.bb(localeR);
    localeR.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localeR.bb(localanQ2);
    localanQ2.brn();
    bJJ localbJJ = new bJJ();
    localbJJ.aJ();
    localbJJ.setElementMap(localcpa);
    localanQ2.bb(localbJJ);
    localbJJ.brn();
    bxx localbxx = new bxx();
    localbxx.aJ();
    localbxx.setElementMap(localcpa);
    localbJJ.bb(localbxx);
    localbxx.brn();
    anE localanE2 = new anE();
    localanE2.aJ();
    localanE2.setElementMap(localcpa);
    localbxx.bb(localanE2);
    localanE2.brn();
    localanE2.rV();
    localbxx.rV();
    dlQ localdlQ = new dlQ();
    localdlQ.aJ();
    localdlQ.setElementMap(localcpa);
    localdlQ.setKey("evenIndex");
    localbJJ.bb(localdlQ);
    localdlQ.brn();
    cOk localcOk = new cOk();
    localcOk.aJ();
    localcOk.setElementMap(localcpa);
    localdlQ.bb(localcOk);
    localcOk.brn();
    localcOk.rV();
    localdlQ.rV();
    localbJJ.rV();
    localanQ2.rV();
    String str6 = "fleaItem";
    avo localavo = new avo();
    localavo.aJ();
    localavo.setElementMap(localcpa);
    if ((localcpa != null) && (str6 != null))
      localcpa.a(str6, localavo);
    localeR.bb(localavo);
    localavo.brn();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("value");
    localavo.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    localavo.rV();
    dRq localdRq10 = dRq.checkOut();
    localdRq10.setElementMap(localcpa);
    localdRq10.setNonBlocking(false);
    cCu localcCu2 = new cCu();
    localcCu2.hg("popup(itemDescPopup)");
    localdRq10.setOnPopupDisplay(localcCu2);
    jL localjL2 = new jL();
    localjL2.hg("closePopup");
    localdRq10.setOnPopupHide(localjL2);
    localeR.bb(localdRq10);
    localdRq10.brn();
    String str7 = "itemDescPopup";
    anG localanG2 = new anG();
    localanG2.aJ();
    localanG2.setElementMap(localcpa);
    if ((localcpa != null) && (str7 != null))
      localcpa.a(str7, localanG2);
    localanG2.setAlign(aFG.ecg);
    localanG2.setHotSpotPosition(aFG.ecm);
    localdRq10.bb(localanG2);
    localanG2.brn();
    dRq localdRq11 = dRq.checkOut();
    localdRq11.setElementMap(localcpa);
    localdRq11.setStyle("popup");
    localanG2.bb(localdRq11);
    localdRq11.brn();
    aId localaId4 = aId.checkOut();
    localaId4.setHorizontal(false);
    localdRq11.bb(localaId4);
    localaId4.brn();
    localaId4.rV();
    cWk localcWk4 = new cWk();
    localcWk4.aJ();
    localcWk4.setElementMap(localcpa);
    localcWk4.setStyle("whiteBold");
    localcWk4.setMinWidth(1);
    localcWk4.setMaxWidth(250);
    localdRq11.bb(localcWk4);
    localcWk4.brn();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("text");
    localaaE2.setField("name");
    localcWk4.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    localcWk4.rV();
    cWk localcWk5 = new cWk();
    localcWk5.aJ();
    localcWk5.setElementMap(localcpa);
    localcWk5.setMinWidth(1);
    localcWk5.setMaxWidth(250);
    String str8 = "%rightClickToShowDetailWindow%";
    str8 = str8.replace("%rightClickToShowDetailWindow%", cBQ.cxL().mL("rightClickToShowDetailWindow"));
    localcWk5.setText(str8);
    localdRq11.bb(localcWk5);
    localcWk5.brn();
    cWk localcWk6 = localcWk5;
    Jg localJg8 = localcWk6.getAppearance();
    localJg8.setElementMap(localcpa);
    localcWk5.bb(localJg8);
    localJg8.brn();
    cAf localcAf = cAf.checkOut();
    localcAf.setElementMap(localcpa);
    localcAf.setColor(new bNa(0.7F, 0.7F, 0.7F, 1.0F));
    localJg8.bb(localcAf);
    localcAf.brn();
    localcAf.rV();
    localJg8.rV();
    localcWk5.rV();
    localdRq11.rV();
    localanG2.rV();
    dRq localdRq12 = localdRq10;
    Jg localJg9 = localdRq12.getAppearance();
    localJg9.setElementMap(localcpa);
    localdRq10.bb(localJg9);
    localJg9.brn();
    jO localjO = new jO();
    localjO.aJ();
    localjO.setElementMap(localcpa);
    localjO.setColor(new bNa(0.43F, 0.47F, 0.47F, 1.0F));
    localJg9.bb(localjO);
    localjO.brn();
    localjO.rV();
    localJg9.rV();
    aId localaId5 = aId.checkOut();
    localaId5.setHorizontal(false);
    localdRq10.bb(localaId5);
    localaId5.brn();
    localaId5.rV();
    dRq localdRq13 = dRq.checkOut();
    localdRq13.setElementMap(localcpa);
    localdRq10.bb(localdRq13);
    localdRq13.brn();
    bXx localbXx = new bXx();
    localbXx.aJ();
    localbXx.setElementMap(localcpa);
    bQa localbQa = new bQa();
    localbQa.hg("wakfu.dimensionalBagFlea:dropItem()");
    localbXx.setOnDrop(localbQa);
    localbXx.setExpandable(false);
    localbXx.setDragEnabled(false);
    localdRq13.bb(localbXx);
    localbXx.brn();
    dRq localdRq14 = dRq.checkOut();
    localdRq14.setElementMap(localcpa);
    localbXx.bb(localdRq14);
    localdRq14.brn();
    czO localczO2 = new czO();
    localczO2.aJ();
    localczO2.setAdaptToContentSize(true);
    localdRq14.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    dRq localdRq15 = dRq.checkOut();
    localdRq15.setElementMap(localcpa);
    localdRq15.setNonBlocking(true);
    localdRq15.setStyle("itemBackground");
    localdRq15.setPrefSize(new Or(38, 38));
    localdRq14.bb(localdRq15);
    localdRq15.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setAlign(ajb.dhZ);
    localdRq15.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    a(localdRq15);
    b(localdRq15);
    localdRq15.rV();
    d(localdRq14);
    e(localdRq14);
    localdRq14.rV();
    localbXx.rV();
    f(localdRq13);
    g(localdRq13);
    localdRq13.rV();
    h(localdRq10);
    localdRq10.rV();
    localeR.rV();
    i(localccG);
    k(localccG);
    l(localccG);
    localccG.rV();
    localdRq9.rV();
    localdRq7.rV();
    localdRq2.rV();
    m(localbpn);
    n(localbpn);
    o(localbpn);
    p(localbpn);
    localbpn.rV();
    return localbpn;
  }

  public bdj a(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    czO localczO = new czO();
    localczO.aJ();
    parambdj.bb(localczO);
    localczO.brn();
    localczO.rV();
    return null;
  }

  public bdj b(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setNonBlocking(true);
    localczv.setDisplaySize(new Or(32, 32));
    parambdj.bb(localczv);
    localczv.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setAlign(ajb.dhZ);
    localczv.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv.bb(localaAR);
    localaAR.brn();
    aaE localaaE = new aaE();
    localaaE.aJ();
    localaaE.setElementMap(localcpa);
    localaaE.setAttribute("texture");
    localaaE.setField("iconUrl");
    localaAR.bb(localaaE);
    localaaE.brn();
    localaaE.rV();
    localaAR.rV();
    localczv.rV();
    return localczv;
  }

  public bdj d(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq = dRq.checkOut();
    localdRq.setElementMap(localcpa);
    localdRq.setNonBlocking(true);
    localdRq.setStyle("ItemBackgroundPerfectVariant");
    parambdj.bb(localdRq);
    localdRq.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setAlign(ajb.dhZ);
    localcwP.setSize(new Or(38, 38));
    localdRq.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    aaE localaaE = new aaE();
    localaaE.aJ();
    localaaE.setElementMap(localcpa);
    localaaE.setAttribute("visible");
    localaaE.setField("isPerfect");
    localdRq.bb(localaaE);
    localaaE.brn();
    localaaE.rV();
    localdRq.rV();
    return localdRq;
  }

  public bdj e(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("White10Bordered");
    localcaF1.setNonBlocking(true);
    parambdj.bb(localcaF1);
    localcaF1.brn();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("visible");
    localaaE1.setField("quantity");
    localcaF1.bb(localaaE1);
    localaaE1.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localaaE1.bb(localanQ);
    localanQ.brn();
    aEJ localaEJ = new aEJ();
    localaEJ.aJ();
    localaEJ.setElementMap(localcpa);
    localaEJ.setValue("1");
    localanQ.bb(localaEJ);
    localaEJ.brn();
    localaEJ.rV();
    localanQ.rV();
    localaaE1.rV();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("text");
    localaaE2.setField("quantity");
    localcaF1.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setAlign(ajb.did);
    localcaF1.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    caF localcaF2 = localcaF1;
    Jg localJg = localcaF2.getAppearance();
    localJg.setElementMap(localcpa);
    localcaF1.bb(localJg);
    localJg.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(0, 5, 0, 0));
    localJg.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg.rV();
    localcaF1.rV();
    return localcaF1;
  }

  public bdj f(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    String str = "itemListContainer";
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    if ((localcpa != null) && (str != null))
      localcpa.a(str, localdRq1);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    dRq localdRq2 = localdRq1;
    Jg localJg1 = localdRq2.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq1.bb(localJg1);
    localJg1.brn();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(3, 5, 3, 5));
    localJg1.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 0, 0, 0));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(false);
    localdRq1.bb(localaId);
    localaId.brn();
    localaId.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("whiteBold");
    localcaF1.setMaxWidth(230);
    localdRq1.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg2 = localcaF2.getAppearance();
    localJg2.setElementMap(localcpa);
    localcaF1.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 0, 3, 0));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.ecj);
    localcaF1.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("text");
    localaaE1.setField("name");
    localcaF1.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    localcaF1.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq1.bb(localdRq3);
    localdRq3.brn();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setStyle("backgroundPopupLight");
    localdRq4.setExpandable(false);
    localdRq4.setPrefSize(new Or(50, 0));
    localdRq3.bb(localdRq4);
    localdRq4.brn();
    dRq localdRq5 = localdRq4;
    Jg localJg3 = localdRq5.getAppearance();
    localJg3.setElementMap(localcpa);
    localJg3.setModulationColor(new bNa(1.0F, 1.0F, 1.0F, 0.8F));
    localdRq4.bb(localJg3);
    localJg3.brn();
    localJg3.rV();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setStyle("whiteBold");
    localcaF3.setExpandable(false);
    localdRq4.bb(localcaF3);
    localcaF3.brn();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("text");
    localaaE2.setField("packType");
    localcaF3.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    localcaF3.rV();
    localdRq4.rV();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq6.setStyle("backgroundPopupLight");
    localdRq6.setPrefSize(new Or(75, 0));
    localdRq3.bb(localdRq6);
    localdRq6.brn();
    dRq localdRq7 = localdRq6;
    Jg localJg4 = localdRq7.getAppearance();
    localJg4.setElementMap(localcpa);
    localJg4.setModulationColor(new bNa(1.0F, 1.0F, 1.0F, 0.8F));
    localdRq6.bb(localJg4);
    localJg4.brn();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(0, 5, 0, 5));
    localJg4.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 50, 0, 0));
    localJg4.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg4.rV();
    caF localcaF4 = new caF();
    localcaF4.aJ();
    localcaF4.setElementMap(localcpa);
    localcaF4.setStyle("whiteBold");
    localdRq6.bb(localcaF4);
    localcaF4.brn();
    caF localcaF5 = localcaF4;
    Jg localJg5 = localcaF5.getAppearance();
    localJg5.setElementMap(localcpa);
    ((cwJ)localJg5).setAlign(aFG.ecl);
    localcaF4.bb(localJg5);
    localJg5.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(0, 0, 0, 2));
    localJg5.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg5.rV();
    aaE localaaE3 = new aaE();
    localaaE3.aJ();
    localaaE3.setElementMap(localcpa);
    localaaE3.setAttribute("text");
    localaaE3.setField("formatedPrice");
    localcaF4.bb(localaaE3);
    localaaE3.brn();
    localaaE3.rV();
    localcaF4.rV();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setStyle("kamas");
    localczv.setExpandable(false);
    localdRq6.bb(localczv);
    localczv.brn();
    localczv.rV();
    localdRq6.rV();
    localdRq3.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj g(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    String str = "removeItemButton";
    biy localbiy1 = new biy();
    localbiy1.aJ();
    localbiy1.setElementMap(localcpa);
    if ((localcpa != null) && (str != null))
      localcpa.a(str, localbiy1);
    localbiy1.setStyle("smallDeleteYellow");
    localbiy1.setExpandable(false);
    csA localcsA = new csA();
    localcsA.hg("wakfu.dimensionalBagFlea:removeMarketItem(fleaItem)");
    localbiy1.setOnClick(localcsA);
    cCu localcCu = new cCu();
    localcCu.hg("popup(descRemovePopup,removeItemButton)");
    localbiy1.setOnPopupDisplay(localcCu);
    jL localjL = new jL();
    localjL.hg("closePopup");
    localbiy1.setOnPopupHide(localjL);
    parambdj.bb(localbiy1);
    localbiy1.brn();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.ech);
    localbiy1.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    biy localbiy2 = localbiy1;
    Jg localJg = localbiy2.getAppearance();
    localJg.setElementMap(localcpa);
    localbiy1.bb(localJg);
    localJg.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(3, 0, 0, 3));
    localJg.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg.rV();
    localbiy1.rV();
    return localbiy1;
  }

  public bdj h(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setNonBlocking(false);
    localdRq1.setPrefSize(new Or(100.0F, 5));
    localdRq1.setExpandable(false);
    bDy localbDy = new bDy();
    localbDy.hg("wakfu.dimensionalBagFlea:onMouseEnterIntersection(background)");
    localdRq1.setOnMouseEnter(localbDy);
    DY localDY = new DY();
    localDY.hg("wakfu.dimensionalBagFlea:onMouseExitIntersection(background)");
    localdRq1.setOnMouseExit(localDY);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    dRq localdRq2 = localdRq1;
    Jg localJg = localdRq2.getAppearance();
    localJg.setElementMap(localcpa);
    localdRq1.bb(localJg);
    localJg.brn();
    String str = "background";
    jO localjO = new jO();
    localjO.aJ();
    localjO.setElementMap(localcpa);
    if ((localcpa != null) && (str != null))
      localcpa.a(str, localjO);
    localjO.setColor(new bNa(0.0F, 0.0F, 0.0F, 0.0F));
    localJg.bb(localjO);
    localjO.brn();
    localjO.rV();
    localJg.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj i(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    eR localeR = new eR();
    localeR.aJ();
    localeR.setElementMap(localcpa);
    aqC localaqC = new aqC();
    localaqC.hg("wakfu:openItemDetailWindow(dimensionalBagWindow)");
    localeR.setOnItemClick(localaqC);
    parambdj.bb(localeR);
    localeR.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localeR.bb(localanQ1);
    localanQ1.brn();
    bJJ localbJJ = new bJJ();
    localbJJ.aJ();
    localbJJ.setElementMap(localcpa);
    localanQ1.bb(localbJJ);
    localbJJ.brn();
    bxx localbxx = new bxx();
    localbxx.aJ();
    localbxx.setElementMap(localcpa);
    localbJJ.bb(localbxx);
    localbxx.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localbxx.bb(localanE);
    localanE.brn();
    localanE.rV();
    localbxx.rV();
    localbJJ.rV();
    localanQ1.rV();
    String str1 = "fleaItem";
    avo localavo = new avo();
    localavo.aJ();
    localavo.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localavo);
    localeR.bb(localavo);
    localavo.brn();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("value");
    localavo.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    localavo.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setNonBlocking(false);
    cCu localcCu1 = new cCu();
    localcCu1.hg("popup(itemDescPopup)");
    localdRq1.setOnPopupDisplay(localcCu1);
    jL localjL1 = new jL();
    localjL1.hg("closePopup");
    localdRq1.setOnPopupHide(localjL1);
    localeR.bb(localdRq1);
    localdRq1.brn();
    String str2 = "itemDescPopup";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localanG);
    localanG.setAlign(aFG.ecg);
    localanG.setHotSpotPosition(aFG.ecm);
    localdRq1.bb(localanG);
    localanG.brn();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setStyle("popup");
    localanG.bb(localdRq2);
    localdRq2.brn();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localdRq2.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("whiteBold");
    localcWk1.setMinWidth(1);
    localcWk1.setMaxWidth(250);
    localdRq2.bb(localcWk1);
    localcWk1.brn();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("text");
    localaaE2.setField("name");
    localcWk1.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    localcWk1.rV();
    cWk localcWk2 = new cWk();
    localcWk2.aJ();
    localcWk2.setElementMap(localcpa);
    localcWk2.setMinWidth(1);
    localcWk2.setMaxWidth(250);
    String str3 = "%rightClickToShowDetailWindow%";
    str3 = str3.replace("%rightClickToShowDetailWindow%", cBQ.cxL().mL("rightClickToShowDetailWindow"));
    localcWk2.setText(str3);
    localdRq2.bb(localcWk2);
    localcWk2.brn();
    cWk localcWk3 = localcWk2;
    Jg localJg1 = localcWk3.getAppearance();
    localJg1.setElementMap(localcpa);
    localcWk2.bb(localJg1);
    localJg1.brn();
    cAf localcAf = cAf.checkOut();
    localcAf.setElementMap(localcpa);
    localcAf.setColor(new bNa(0.7F, 0.7F, 0.7F, 1.0F));
    localJg1.bb(localcAf);
    localcAf.brn();
    localcAf.rV();
    localJg1.rV();
    localcWk2.rV();
    localdRq2.rV();
    localanG.rV();
    dRq localdRq3 = localdRq1;
    Jg localJg2 = localdRq3.getAppearance();
    localJg2.setElementMap(localcpa);
    localdRq1.bb(localJg2);
    localJg2.brn();
    jO localjO = new jO();
    localjO.aJ();
    localjO.setElementMap(localcpa);
    localjO.setColor(new bNa(0.55F, 0.57F, 0.57F, 1.0F));
    localJg2.bb(localjO);
    localjO.brn();
    localjO.rV();
    localJg2.rV();
    aId localaId2 = aId.checkOut();
    localaId2.setHorizontal(false);
    localdRq1.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq1.bb(localdRq4);
    localdRq4.brn();
    bXx localbXx = new bXx();
    localbXx.aJ();
    localbXx.setElementMap(localcpa);
    bQa localbQa = new bQa();
    localbQa.hg("wakfu.dimensionalBagFlea:dropItem()");
    localbXx.setOnDrop(localbQa);
    localbXx.setDragEnabled(false);
    localbXx.setExpandable(false);
    localdRq4.bb(localbXx);
    localbXx.brn();
    dRq localdRq5 = dRq.checkOut();
    localdRq5.setElementMap(localcpa);
    localbXx.bb(localdRq5);
    localdRq5.brn();
    czO localczO1 = new czO();
    localczO1.aJ();
    localczO1.setAdaptToContentSize(true);
    localdRq5.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq6.setNonBlocking(true);
    localdRq6.setStyle("itemBackground");
    localdRq6.setPrefSize(new Or(38, 38));
    localdRq5.bb(localdRq6);
    localdRq6.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setAlign(ajb.dhZ);
    localdRq6.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    czO localczO2 = new czO();
    localczO2.aJ();
    localdRq6.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setNonBlocking(true);
    localczv1.setDisplaySize(new Or(32, 32));
    localdRq6.bb(localczv1);
    localczv1.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.dhZ);
    localczv1.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv1.bb(localaAR);
    localaAR.brn();
    aaE localaaE3 = new aaE();
    localaaE3.aJ();
    localaaE3.setElementMap(localcpa);
    localaaE3.setAttribute("texture");
    localaaE3.setField("iconUrl");
    localaAR.bb(localaaE3);
    localaaE3.brn();
    localaaE3.rV();
    localaAR.rV();
    localczv1.rV();
    localdRq6.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localdRq7.setNonBlocking(true);
    localdRq7.setStyle("ItemBackgroundPerfectVariant");
    localdRq5.bb(localdRq7);
    localdRq7.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setAlign(ajb.dhZ);
    localcwP3.setSize(new Or(38, 38));
    localdRq7.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    aaE localaaE4 = new aaE();
    localaaE4.aJ();
    localaaE4.setElementMap(localcpa);
    localaaE4.setAttribute("visible");
    localaaE4.setField("isPerfect");
    localdRq7.bb(localaaE4);
    localaaE4.brn();
    localaaE4.rV();
    localdRq7.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("White10Bordered");
    localcaF1.setNonBlocking(true);
    localdRq5.bb(localcaF1);
    localcaF1.brn();
    aaE localaaE5 = new aaE();
    localaaE5.aJ();
    localaaE5.setElementMap(localcpa);
    localaaE5.setAttribute("visible");
    localaaE5.setField("quantity");
    localcaF1.bb(localaaE5);
    localaaE5.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localaaE5.bb(localanQ2);
    localanQ2.brn();
    aEJ localaEJ = new aEJ();
    localaEJ.aJ();
    localaEJ.setElementMap(localcpa);
    localaEJ.setValue("1");
    localanQ2.bb(localaEJ);
    localaEJ.brn();
    localaEJ.rV();
    localanQ2.rV();
    localaaE5.rV();
    aaE localaaE6 = new aaE();
    localaaE6.aJ();
    localaaE6.setElementMap(localcpa);
    localaaE6.setAttribute("text");
    localaaE6.setField("quantity");
    localcaF1.bb(localaaE6);
    localaaE6.brn();
    localaaE6.rV();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setAlign(ajb.did);
    localcaF1.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    caF localcaF2 = localcaF1;
    Jg localJg3 = localcaF2.getAppearance();
    localJg3.setElementMap(localcpa);
    localcaF1.bb(localJg3);
    localJg3.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 5, 0, 0));
    localJg3.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg3.rV();
    localcaF1.rV();
    localdRq5.rV();
    localbXx.rV();
    String str4 = "itemListContainer";
    dRq localdRq8 = dRq.checkOut();
    localdRq8.setElementMap(localcpa);
    if ((localcpa != null) && (str4 != null))
      localcpa.a(str4, localdRq8);
    localdRq4.bb(localdRq8);
    localdRq8.brn();
    dRq localdRq9 = localdRq8;
    Jg localJg4 = localdRq9.getAppearance();
    localJg4.setElementMap(localcpa);
    localdRq8.bb(localJg4);
    localJg4.brn();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(3, 5, 3, 5));
    localJg4.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 0, 0, 0));
    localJg4.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg4.rV();
    aId localaId3 = aId.checkOut();
    localaId3.setHorizontal(false);
    localdRq8.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setStyle("whiteBold");
    localcaF3.setMaxWidth(230);
    localdRq8.bb(localcaF3);
    localcaF3.brn();
    caF localcaF4 = localcaF3;
    Jg localJg5 = localcaF4.getAppearance();
    localJg5.setElementMap(localcpa);
    localcaF3.bb(localJg5);
    localJg5.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 0, 3, 0));
    localJg5.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg5.rV();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa);
    localdpm1.setAlign(aFG.ecj);
    localcaF3.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    aaE localaaE7 = new aaE();
    localaaE7.aJ();
    localaaE7.setElementMap(localcpa);
    localaaE7.setAttribute("text");
    localaaE7.setField("name");
    localcaF3.bb(localaaE7);
    localaaE7.brn();
    localaaE7.rV();
    localcaF3.rV();
    dRq localdRq10 = dRq.checkOut();
    localdRq10.setElementMap(localcpa);
    localdRq8.bb(localdRq10);
    localdRq10.brn();
    dRq localdRq11 = dRq.checkOut();
    localdRq11.setElementMap(localcpa);
    localdRq11.setStyle("backgroundPopupLight");
    localdRq11.setExpandable(false);
    localdRq11.setPrefSize(new Or(50, 0));
    localdRq10.bb(localdRq11);
    localdRq11.brn();
    dRq localdRq12 = localdRq11;
    Jg localJg6 = localdRq12.getAppearance();
    localJg6.setElementMap(localcpa);
    localJg6.setModulationColor(new bNa(1.0F, 1.0F, 1.0F, 0.8F));
    localdRq11.bb(localJg6);
    localJg6.brn();
    localJg6.rV();
    caF localcaF5 = new caF();
    localcaF5.aJ();
    localcaF5.setElementMap(localcpa);
    localcaF5.setStyle("whiteBold");
    localcaF5.setExpandable(false);
    localdRq11.bb(localcaF5);
    localcaF5.brn();
    aaE localaaE8 = new aaE();
    localaaE8.aJ();
    localaaE8.setElementMap(localcpa);
    localaaE8.setAttribute("text");
    localaaE8.setField("packType");
    localcaF5.bb(localaaE8);
    localaaE8.brn();
    localaaE8.rV();
    localcaF5.rV();
    localdRq11.rV();
    dRq localdRq13 = dRq.checkOut();
    localdRq13.setElementMap(localcpa);
    localdRq13.setStyle("backgroundPopupLight");
    localdRq13.setPrefSize(new Or(75, 0));
    localdRq10.bb(localdRq13);
    localdRq13.brn();
    dRq localdRq14 = localdRq13;
    Jg localJg7 = localdRq14.getAppearance();
    localJg7.setElementMap(localcpa);
    localJg7.setModulationColor(new bNa(1.0F, 1.0F, 1.0F, 0.8F));
    localdRq13.bb(localJg7);
    localJg7.brn();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(0, 5, 0, 5));
    localJg7.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(0, 50, 0, 0));
    localJg7.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg7.rV();
    caF localcaF6 = new caF();
    localcaF6.aJ();
    localcaF6.setElementMap(localcpa);
    localcaF6.setStyle("whiteBold");
    localdRq13.bb(localcaF6);
    localcaF6.brn();
    caF localcaF7 = localcaF6;
    Jg localJg8 = localcaF7.getAppearance();
    localJg8.setElementMap(localcpa);
    ((cwJ)localJg8).setAlign(aFG.ecl);
    localcaF6.bb(localJg8);
    localJg8.brn();
    bmv localbmv5 = bmv.checkOut();
    localbmv5.setElementMap(localcpa);
    localbmv5.setInsets(new Insets(0, 0, 0, 2));
    localJg8.bb(localbmv5);
    localbmv5.brn();
    localbmv5.rV();
    localJg8.rV();
    aaE localaaE9 = new aaE();
    localaaE9.aJ();
    localaaE9.setElementMap(localcpa);
    localaaE9.setAttribute("text");
    localaaE9.setField("formatedPrice");
    localcaF6.bb(localaaE9);
    localaaE9.brn();
    localaaE9.rV();
    localcaF6.rV();
    czv localczv2 = new czv();
    localczv2.aJ();
    localczv2.setElementMap(localcpa);
    localczv2.setStyle("kamas");
    localczv2.setExpandable(false);
    localdRq13.bb(localczv2);
    localczv2.brn();
    localczv2.rV();
    localdRq13.rV();
    localdRq10.rV();
    localdRq8.rV();
    String str5 = "removeItemButton";
    biy localbiy1 = new biy();
    localbiy1.aJ();
    localbiy1.setElementMap(localcpa);
    if ((localcpa != null) && (str5 != null))
      localcpa.a(str5, localbiy1);
    localbiy1.setStyle("smallDeleteYellow");
    localbiy1.setExpandable(false);
    csA localcsA = new csA();
    localcsA.hg("wakfu.dimensionalBagFlea:removeMarketItem(fleaItem)");
    localbiy1.setOnClick(localcsA);
    cCu localcCu2 = new cCu();
    localcCu2.hg("popup(descRemovePopup,removeItemButton)");
    localbiy1.setOnPopupDisplay(localcCu2);
    jL localjL2 = new jL();
    localjL2.hg("closePopup");
    localbiy1.setOnPopupHide(localjL2);
    localdRq4.bb(localbiy1);
    localbiy1.brn();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa);
    localdpm2.setAlign(aFG.ech);
    localbiy1.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    biy localbiy2 = localbiy1;
    Jg localJg9 = localbiy2.getAppearance();
    localJg9.setElementMap(localcpa);
    localbiy1.bb(localJg9);
    localJg9.brn();
    bmv localbmv6 = bmv.checkOut();
    localbmv6.setElementMap(localcpa);
    localbmv6.setInsets(new Insets(3, 0, 0, 3));
    localJg9.bb(localbmv6);
    localbmv6.brn();
    localbmv6.rV();
    localJg9.rV();
    localbiy1.rV();
    localdRq4.rV();
    dRq localdRq15 = dRq.checkOut();
    localdRq15.setElementMap(localcpa);
    localdRq15.setNonBlocking(false);
    localdRq15.setPrefSize(new Or(100.0F, 5));
    localdRq15.setExpandable(false);
    bDy localbDy = new bDy();
    localbDy.hg("wakfu.dimensionalBagFlea:onMouseEnterIntersection(background)");
    localdRq15.setOnMouseEnter(localbDy);
    DY localDY = new DY();
    localDY.hg("wakfu.dimensionalBagFlea:onMouseExitIntersection(background)");
    localdRq15.setOnMouseExit(localDY);
    localdRq1.bb(localdRq15);
    localdRq15.brn();
    j(localdRq15);
    localdRq15.rV();
    localdRq1.rV();
    localeR.rV();
    return localeR;
  }

  public bdj j(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dOc localdOc = (dOc)parambdj;
    Jg localJg = localdOc.getAppearance();
    localJg.setElementMap(localcpa);
    parambdj.bb(localJg);
    localJg.brn();
    String str = "background";
    jO localjO = new jO();
    localjO.aJ();
    localjO.setElementMap(localcpa);
    if ((localcpa != null) && (str != null))
      localcpa.a(str, localjO);
    localjO.setColor(new bNa(0.0F, 0.0F, 0.0F, 0.0F));
    localJg.bb(localjO);
    localjO.brn();
    localjO.rV();
    localJg.rV();
    return localJg;
  }

  public bdj k(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    eR localeR = new eR();
    localeR.aJ();
    localeR.setElementMap(localcpa);
    parambdj.bb(localeR);
    localeR.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localeR.bb(localanQ);
    localanQ.brn();
    bJJ localbJJ = new bJJ();
    localbJJ.aJ();
    localbJJ.setElementMap(localcpa);
    localanQ.bb(localbJJ);
    localbJJ.brn();
    bxx localbxx = new bxx();
    localbxx.aJ();
    localbxx.setElementMap(localcpa);
    localbJJ.bb(localbxx);
    localbxx.brn();
    aIB localaIB = new aIB();
    localaIB.aJ();
    localaIB.setElementMap(localcpa);
    localbxx.bb(localaIB);
    localaIB.brn();
    localaIB.rV();
    localbxx.rV();
    dlQ localdlQ = new dlQ();
    localdlQ.aJ();
    localdlQ.setElementMap(localcpa);
    localdlQ.setKey("evenIndex");
    localbJJ.bb(localdlQ);
    localdlQ.brn();
    cOk localcOk = new cOk();
    localcOk.aJ();
    localcOk.setElementMap(localcpa);
    localdlQ.bb(localcOk);
    localcOk.brn();
    localcOk.rV();
    localdlQ.rV();
    localbJJ.rV();
    localanQ.rV();
    bXx localbXx1 = new bXx();
    localbXx1.aJ();
    localbXx1.setElementMap(localcpa);
    bQa localbQa = new bQa();
    localbQa.hg("wakfu.dimensionalBagFlea:dropItem()");
    localbXx1.setOnDrop(localbQa);
    localeR.bb(localbXx1);
    localbXx1.brn();
    bXx localbXx2 = localbXx1;
    Jg localJg = localbXx2.getAppearance();
    localJg.setElementMap(localcpa);
    localbXx1.bb(localJg);
    localJg.brn();
    jO localjO = new jO();
    localjO.aJ();
    localjO.setElementMap(localcpa);
    localjO.setColor(new bNa(0.43F, 0.47F, 0.47F, 1.0F));
    localJg.bb(localjO);
    localjO.brn();
    localjO.rV();
    cuR localcuR = new cuR();
    localcuR.aJ();
    localcuR.setElementMap(localcpa);
    localcuR.setInsets(new Insets(2, 0, 3, 0));
    localJg.bb(localcuR);
    localcuR.brn();
    localcuR.rV();
    localJg.rV();
    bTm localbTm = new bTm();
    localbTm.aJ();
    localbXx1.bb(localbTm);
    localbTm.brn();
    localbTm.rV();
    dRq localdRq = dRq.checkOut();
    localdRq.setElementMap(localcpa);
    localdRq.setStyle("itemBackground");
    localdRq.setPrefSize(new Or(38, 38));
    localbXx1.bb(localdRq);
    localdRq.brn();
    cba localcba = cba.checkOut();
    localcba.setElementMap(localcpa);
    localcba.setData(cFu.izV);
    localdRq.bb(localcba);
    localcba.brn();
    localcba.rV();
    localdRq.rV();
    localbXx1.rV();
    localeR.rV();
    return localeR;
  }

  public bdj l(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    eR localeR = new eR();
    localeR.aJ();
    localeR.setElementMap(localcpa);
    parambdj.bb(localeR);
    localeR.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localeR.bb(localanQ);
    localanQ.brn();
    bJJ localbJJ = new bJJ();
    localbJJ.aJ();
    localbJJ.setElementMap(localcpa);
    localanQ.bb(localbJJ);
    localbJJ.brn();
    bxx localbxx = new bxx();
    localbxx.aJ();
    localbxx.setElementMap(localcpa);
    localbJJ.bb(localbxx);
    localbxx.brn();
    aIB localaIB = new aIB();
    localaIB.aJ();
    localaIB.setElementMap(localcpa);
    localbxx.bb(localaIB);
    localaIB.brn();
    localaIB.rV();
    localbxx.rV();
    dlQ localdlQ = new dlQ();
    localdlQ.aJ();
    localdlQ.setElementMap(localcpa);
    localdlQ.setKey("oddIndex");
    localbJJ.bb(localdlQ);
    localdlQ.brn();
    cOk localcOk = new cOk();
    localcOk.aJ();
    localcOk.setElementMap(localcpa);
    localdlQ.bb(localcOk);
    localcOk.brn();
    localcOk.rV();
    localdlQ.rV();
    localbJJ.rV();
    localanQ.rV();
    bXx localbXx1 = new bXx();
    localbXx1.aJ();
    localbXx1.setElementMap(localcpa);
    bQa localbQa = new bQa();
    localbQa.hg("wakfu.dimensionalBagFlea:dropItem()");
    localbXx1.setOnDrop(localbQa);
    localeR.bb(localbXx1);
    localbXx1.brn();
    bXx localbXx2 = localbXx1;
    Jg localJg = localbXx2.getAppearance();
    localJg.setElementMap(localcpa);
    localbXx1.bb(localJg);
    localJg.brn();
    jO localjO = new jO();
    localjO.aJ();
    localjO.setElementMap(localcpa);
    localjO.setColor(new bNa(0.55F, 0.57F, 0.57F, 1.0F));
    localJg.bb(localjO);
    localjO.brn();
    localjO.rV();
    cuR localcuR = new cuR();
    localcuR.aJ();
    localcuR.setElementMap(localcpa);
    localcuR.setInsets(new Insets(2, 0, 3, 0));
    localJg.bb(localcuR);
    localcuR.brn();
    localcuR.rV();
    localJg.rV();
    bTm localbTm = new bTm();
    localbTm.aJ();
    localbXx1.bb(localbTm);
    localbTm.brn();
    localbTm.rV();
    dRq localdRq = dRq.checkOut();
    localdRq.setElementMap(localcpa);
    localdRq.setStyle("itemBackground");
    localdRq.setPrefSize(new Or(38, 38));
    localbXx1.bb(localdRq);
    localdRq.brn();
    cba localcba = cba.checkOut();
    localcba.setElementMap(localcpa);
    localcba.setData(cFu.izV);
    localdRq.bb(localcba);
    localcba.brn();
    localcba.rV();
    localdRq.rV();
    localbXx1.rV();
    localeR.rV();
    return localeR;
  }

  public bdj m(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq = dRq.checkOut();
    localdRq.setElementMap(localcpa);
    parambdj.bb(localdRq);
    localdRq.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(100.0F, 100.0F));
    localdRq.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localdRq.rV();
    return localdRq;
  }

  public bdj n(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    biy localbiy = new biy();
    localbiy.aJ();
    localbiy.setElementMap(localcpa);
    localbiy.setStyle("close");
    localbiy.setExpandable(false);
    csA localcsA = new csA();
    localcsA.hg("unloadDialog");
    localbiy.setOnClick(localcsA);
    parambdj.bb(localbiy);
    localbiy.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(-2, -2));
    localcwP.setAlign(ajb.dhV);
    localcwP.setXOffset(-18);
    localcwP.setYOffset(-12);
    localbiy.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localbiy.rV();
    return localbiy;
  }

  public bdj o(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(-2, -2));
    localcwP.setAlign(ajb.did);
    localcwP.setInitValue(true);
    localcwP.setXOffset(40);
    localcwP.setYOffset(150);
    parambdj.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    return localcwP;
  }

  public bdj p(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    String str1 = "descRemovePopup";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localanG);
    localanG.setAlign(aFG.ech);
    localanG.setHotSpotPosition(aFG.ecn);
    parambdj.bb(localanG);
    localanG.brn();
    dRq localdRq = dRq.checkOut();
    localdRq.setElementMap(localcpa);
    localdRq.setPrefSize(new Or(10, 0));
    localdRq.setStyle("popup");
    localanG.bb(localdRq);
    localdRq.brn();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("PopupInformation");
    String str2 = "%desc.removeItem%";
    str2 = str2.replace("%desc.removeItem%", cBQ.cxL().mL("desc.removeItem"));
    localcaF1.setText(str2);
    localdRq.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg = localcaF2.getAppearance();
    localJg.setElementMap(localcpa);
    ((cwJ)localJg).setAlignment(aFG.ecj);
    localcaF1.bb(localJg);
    localJg.brn();
    localJg.rV();
    localcaF1.rV();
    localdRq.rV();
    localanG.rV();
    return localanG;
  }
}