import java.awt.Insets;
import java.util.Stack;

public class dzt
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    String str1 = "window";
    bpn localbpn = new bpn();
    localbpn.aJ();
    localbpn.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localbpn);
    localbpn.setPack(true);
    localbpn.brn();
    czO localczO1 = new czO();
    localczO1.aJ();
    localczO1.setAdaptToContentSize(true);
    localbpn.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localbpn.bb(localdRq1);
    localdRq1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    localdRq1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setStyle("windowNew");
    localbpn.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(10, 5, 12, 5));
    localJg1.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    localJg1.rV();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localdRq2.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localaId1.setAlign(aFG.ech);
    localdRq2.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dqa localdqa1 = new dqa();
    localdqa1.aJ();
    localdqa1.setElementMap(localcpa);
    localdqa1.setExpandable(false);
    localdRq2.bb(localdqa1);
    localdqa1.brn();
    dqa localdqa2 = localdqa1;
    Jg localJg2 = localdqa2.getAppearance();
    localJg2.setElementMap(localcpa);
    localdqa1.bb(localJg2);
    localJg2.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 10, 0, 10));
    localJg2.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg2.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setStyle("titleBar");
    localdqa1.bb(localdRq4);
    localdRq4.brn();
    dRq localdRq5 = localdRq4;
    Jg localJg3 = localdRq5.getAppearance();
    localJg3.setElementMap(localcpa);
    localdRq4.bb(localJg3);
    localJg3.brn();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(2, 20, 3, 20));
    localJg3.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    localJg3.rV();
    aId localaId2 = aId.checkOut();
    localaId2.setHorizontal(false);
    localdRq4.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq6.setExpandable(false);
    localdRq4.bb(localdRq6);
    localdRq6.brn();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa);
    localdpm1.setAlign(aFG.eck);
    localdRq6.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("StyledBold16White");
    String str2 = "%playerGift.title%";
    str2 = str2.replace("%playerGift.title%", cBQ.cxL().mL("playerGift.title"));
    localcaF1.setText(str2);
    localcaF1.setNonBlocking(true);
    localdRq6.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg4 = localcaF2.getAppearance();
    localJg4.setElementMap(localcpa);
    ((cwJ)localJg4).setAlignment(aFG.eck);
    localcaF1.bb(localJg4);
    localJg4.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 0, 0, 5));
    localJg4.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg4.rV();
    localcaF1.rV();
    localdRq6.rV();
    localdRq4.rV();
    localdqa1.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localdRq2.bb(localdRq7);
    localdRq7.brn();
    dRq localdRq8 = localdRq7;
    Jg localJg5 = localdRq8.getAppearance();
    localJg5.setElementMap(localcpa);
    localdRq7.bb(localJg5);
    localJg5.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 12, 0, 12));
    localJg5.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg5.rV();
    String str3 = "windowContentContainer";
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa);
    if ((localcpa != null) && (str3 != null))
      localcpa.a(str3, localdRq9);
    localdRq7.bb(localdRq9);
    localdRq9.brn();
    czO localczO2 = new czO();
    localczO2.aJ();
    localczO2.setAdaptToContentSize(true);
    localdRq9.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    dRq localdRq10 = localdRq9;
    Jg localJg6 = localdRq10.getAppearance();
    localJg6.setElementMap(localcpa);
    localdRq9.bb(localJg6);
    localJg6.brn();
    cuR localcuR3 = new cuR();
    localcuR3.aJ();
    localcuR3.setElementMap(localcpa);
    localcuR3.setInsets(new Insets(0, 0, 0, 0));
    localJg6.bb(localcuR3);
    localcuR3.brn();
    localcuR3.rV();
    localJg6.rV();
    dRq localdRq11 = dRq.checkOut();
    localdRq11.setElementMap(localcpa);
    localdRq11.setStyle("ScrollString");
    localdRq9.bb(localdRq11);
    localdRq11.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setAlign(ajb.dia);
    localcwP3.setSize(new Or(10, 100.0F));
    localcwP3.setXOffset(-15);
    localdRq11.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    dRq localdRq12 = localdRq11;
    Jg localJg7 = localdRq12.getAppearance();
    localJg7.setElementMap(localcpa);
    localdRq11.bb(localJg7);
    localJg7.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(30, 0, 40, 0));
    localJg7.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg7.rV();
    localdRq11.rV();
    String str4 = "selectedCraft";
    avo localavo = new avo();
    localavo.aJ();
    localavo.setElementMap(localcpa);
    if ((localcpa != null) && (str4 != null))
      localcpa.a(str4, localavo);
    localdRq9.bb(localavo);
    localavo.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setLocal(true);
    localNK1.setName("craft");
    localNK1.setAttribute("value");
    localavo.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    localavo.rV();
    bbp localbbp1 = new bbp();
    localbbp1.aJ();
    localbbp1.setElementMap(localcpa);
    localbbp1.setStyle("Encyclopedia");
    localbbp1.setExpandable(false);
    localbbp1.setHorizontalScrollBarBehaviour(dOf.mfK);
    localbbp1.setVerticalScrollBarBehaviour(dOf.mfJ);
    localbbp1.setPageJumpRatio(0.3F);
    localdRq9.bb(localbbp1);
    localbbp1.brn();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setSize(new Or(100.0F, 100.0F));
    localcwP4.setAlign(ajb.dhZ);
    localbbp1.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    bbp localbbp2 = localbbp1;
    Jg localJg8 = localbbp2.getAppearance();
    localJg8.setElementMap(localcpa);
    localbbp1.bb(localJg8);
    localJg8.brn();
    bmv localbmv5 = bmv.checkOut();
    localbmv5.setElementMap(localcpa);
    localbmv5.setInsets(new Insets(17, 3, 20, 0));
    localJg8.bb(localbmv5);
    localbmv5.brn();
    localbmv5.rV();
    cuR localcuR4 = new cuR();
    localcuR4.aJ();
    localcuR4.setElementMap(localcpa);
    localcuR4.setInsets(new Insets(0, 18, 0, 4));
    localJg8.bb(localcuR4);
    localcuR4.brn();
    localcuR4.rV();
    localJg8.rV();
    dRq localdRq13 = dRq.checkOut();
    localdRq13.setElementMap(localcpa);
    localdRq13.setStyle("tiledScroll");
    localdRq13.setExpandable(false);
    localdRq13.setPrefSize(new Or(415, 0));
    localbbp1.bb(localdRq13);
    localdRq13.brn();
    cwP localcwP5 = new cwP();
    localcwP5.aJ();
    localcwP5.setElementMap(localcpa);
    localcwP5.setAlign(ajb.dhZ);
    localdRq13.bb(localcwP5);
    localcwP5.brn();
    localcwP5.rV();
    dRq localdRq14 = localdRq13;
    Jg localJg9 = localdRq14.getAppearance();
    localJg9.setElementMap(localcpa);
    localdRq13.bb(localJg9);
    localJg9.brn();
    cuR localcuR5 = new cuR();
    localcuR5.aJ();
    localcuR5.setElementMap(localcpa);
    localcuR5.setInsets(new Insets(10, 0, 10, 0));
    localJg9.bb(localcuR5);
    localcuR5.brn();
    localcuR5.rV();
    bmv localbmv6 = bmv.checkOut();
    localbmv6.setElementMap(localcpa);
    localbmv6.setInsets(new Insets(0, 0, 0, 10));
    localJg9.bb(localbmv6);
    localbmv6.brn();
    localbmv6.rV();
    localJg9.rV();
    aId localaId3 = aId.checkOut();
    localaId3.setHorizontal(false);
    localaId3.setAlign(aFG.ech);
    localdRq13.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    dRq localdRq15 = dRq.checkOut();
    localdRq15.setElementMap(localcpa);
    localdRq15.setExpandable(false);
    localdRq13.bb(localdRq15);
    localdRq15.brn();
    dRq localdRq16 = localdRq15;
    Jg localJg10 = localdRq16.getAppearance();
    localJg10.setElementMap(localcpa);
    localdRq15.bb(localJg10);
    localJg10.brn();
    bmv localbmv7 = bmv.checkOut();
    localbmv7.setElementMap(localcpa);
    localbmv7.setInsets(new Insets(0, 5, 0, 0));
    localJg10.bb(localbmv7);
    localbmv7.brn();
    localbmv7.rV();
    localJg10.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("playerGift");
    localNK2.setField("selectedPackage");
    localNK2.setAttribute("visible");
    localdRq15.bb(localNK2);
    localNK2.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localNK2.bb(localanQ1);
    localanQ1.brn();
    anE localanE1 = new anE();
    localanE1.aJ();
    localanE1.setElementMap(localcpa);
    localanQ1.bb(localanE1);
    localanE1.brn();
    localanE1.rV();
    localanQ1.rV();
    localNK2.rV();
    aId localaId4 = aId.checkOut();
    localaId4.setHorizontal(false);
    localdRq15.bb(localaId4);
    localaId4.brn();
    localaId4.rV();
    dRq localdRq17 = dRq.checkOut();
    localdRq17.setElementMap(localcpa);
    localdRq17.setExpandable(false);
    localdRq15.bb(localdRq17);
    localdRq17.brn();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa);
    localdpm2.setAlign(aFG.ecj);
    localdRq17.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    dRq localdRq18 = localdRq17;
    Jg localJg11 = localdRq18.getAppearance();
    localJg11.setElementMap(localcpa);
    localdRq17.bb(localJg11);
    localJg11.brn();
    bmv localbmv8 = bmv.checkOut();
    localbmv8.setElementMap(localcpa);
    localbmv8.setInsets(new Insets(0, 20, 0, 5));
    localJg11.bb(localbmv8);
    localbmv8.brn();
    localbmv8.rV();
    localJg11.rV();
    dRq localdRq19 = dRq.checkOut();
    localdRq19.setElementMap(localcpa);
    localdRq19.setStyle("encyclopediaSplash");
    localdRq19.setExpandable(false);
    localdRq19.setPrefSize(new Or(64, 64));
    localdRq17.bb(localdRq19);
    localdRq19.brn();
    dpm localdpm3 = new dpm();
    localdpm3.aJ();
    localdpm3.setElementMap(localcpa);
    localdpm3.setAlign(aFG.ech);
    localdRq19.bb(localdpm3);
    localdpm3.brn();
    localdpm3.rV();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setDisplaySize(new Or(48, 48));
    localczv.setExpandable(false);
    localdRq19.bb(localczv);
    localczv.brn();
    dpm localdpm4 = new dpm();
    localdpm4.aJ();
    localdpm4.setElementMap(localcpa);
    localdpm4.setAlign(aFG.eck);
    localczv.bb(localdpm4);
    localdpm4.brn();
    localdpm4.rV();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setName("playerGift");
    localNK3.setField("selectedPackage");
    localNK3.setAttribute("visible");
    localczv.bb(localNK3);
    localNK3.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localNK3.bb(localanQ2);
    localanQ2.brn();
    anE localanE2 = new anE();
    localanE2.aJ();
    localanE2.setElementMap(localcpa);
    localanQ2.bb(localanE2);
    localanE2.brn();
    localanE2.rV();
    localanQ2.rV();
    localNK3.rV();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv.bb(localaAR);
    localaAR.brn();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa);
    localNK4.setName("playerGift");
    localNK4.setField("selectedPackage/iconUrl");
    localNK4.setAttribute("texture");
    localaAR.bb(localNK4);
    localNK4.brn();
    localNK4.rV();
    localaAR.rV();
    localczv.rV();
    localdRq19.rV();
    dRq localdRq20 = dRq.checkOut();
    localdRq20.setElementMap(localcpa);
    localdRq20.setStyle("backgroundPopupLight");
    localdRq20.setExpandable(false);
    localdRq17.bb(localdRq20);
    localdRq20.brn();
    dpm localdpm5 = new dpm();
    localdpm5.aJ();
    localdpm5.setElementMap(localcpa);
    localdpm5.setAlign(aFG.ech);
    localdRq20.bb(localdpm5);
    localdpm5.brn();
    localdpm5.rV();
    dRq localdRq21 = localdRq20;
    Jg localJg12 = localdRq21.getAppearance();
    localJg12.setElementMap(localcpa);
    localJg12.setModulationColor(new bNa(1.0F, 0.0F, 0.0F, 0.7F));
    localdRq20.bb(localJg12);
    localJg12.brn();
    cuR localcuR6 = new cuR();
    localcuR6.aJ();
    localcuR6.setElementMap(localcpa);
    localcuR6.setInsets(new Insets(4, 4, 4, 4));
    localJg12.bb(localcuR6);
    localcuR6.brn();
    localcuR6.rV();
    localJg12.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("whiteBold11");
    localcWk1.setExpandable(false);
    localcWk1.setMinWidth(1);
    localcWk1.setMaxWidth(315);
    localcWk1.setText("Super cadeau de bienvenue qui poutre sa mère, la race de sa grand-mère");
    localdRq20.bb(localcWk1);
    localcWk1.brn();
    NK localNK5 = NK.checkOut();
    localNK5.setElementMap(localcpa);
    localNK5.setName("playerGift");
    localNK5.setField("selectedPackage/title");
    localNK5.setAttribute("text");
    localcWk1.bb(localNK5);
    localNK5.brn();
    localNK5.rV();
    cWk localcWk2 = localcWk1;
    Jg localJg13 = localcWk2.getAppearance();
    localJg13.setElementMap(localcpa);
    ((cwJ)localJg13).setAlign(aFG.ecj);
    localcWk1.bb(localJg13);
    localJg13.brn();
    cAf localcAf = cAf.checkOut();
    localcAf.setElementMap(localcpa);
    localcAf.setColor(new bNa(1.0F, 1.0F, 1.0F, 1.0F));
    localcAf.setName("text");
    localJg13.bb(localcAf);
    localcAf.brn();
    localcAf.rV();
    localJg13.rV();
    localcWk1.rV();
    localdRq20.rV();
    localdRq17.rV();
    cWk localcWk3 = new cWk();
    localcWk3.aJ();
    localcWk3.setElementMap(localcpa);
    localcWk3.setStyle("darkBold");
    localcWk3.setExpandable(false);
    localcWk3.setMinWidth(1);
    localcWk3.setMaxWidth(385);
    localcWk3.setText("Hé oui ! Ha ha ha ! Ce cadeau de bienvenue vous est offert par GIFI ! Encore un bijou de technologie qui nous libère des tracas du quotidien !! Il nous est présenté par Micheline... Merci Micheline, vous pouvez y aller.");
    localdRq15.bb(localcWk3);
    localcWk3.brn();
    a(localcWk3);
    b(localcWk3);
    d(localcWk3);
    localcWk3.rV();
    e(localdRq15);
    localdRq15.rV();
    localdRq13.rV();
    localbbp1.rV();
    f(localdRq9);
    localdRq9.rV();
    localdRq7.rV();
    g(localdRq2);
    localdRq2.rV();
    h(localbpn);
    i(localbpn);
    j(localbpn);
    localbpn.rV();
    return localbpn;
  }

  public bdj a(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dOc localdOc = (dOc)parambdj;
    Jg localJg = localdOc.getAppearance();
    localJg.setElementMap(localcpa);
    parambdj.bb(localJg);
    localJg.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(5, 20, 5, 0));
    localJg.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg.rV();
    return localJg;
  }

  public bdj b(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.ecj);
    parambdj.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    return localdpm;
  }

  public bdj d(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setName("playerGift");
    localNK.setField("selectedPackage/description");
    localNK.setAttribute("text");
    parambdj.bb(localNK);
    localNK.brn();
    localNK.rV();
    return localNK;
  }

  public bdj e(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    ccG localccG1 = new ccG();
    localccG1.aJ();
    localccG1.setElementMap(localcpa);
    localccG1.setCellSize(new Or(100.0F, 40));
    localccG1.setExpandable(false);
    localccG1.setAutoIdealSize(true);
    localccG1.setIdealSizeMinColumns(1);
    localccG1.setIdealSizeMaxColumns(1);
    parambdj.bb(localccG1);
    localccG1.brn();
    ccG localccG2 = localccG1;
    Jg localJg1 = localccG2.getAppearance();
    localJg1.setElementMap(localcpa);
    localccG1.bb(localJg1);
    localJg1.brn();
    cuR localcuR = new cuR();
    localcuR.aJ();
    localcuR.setElementMap(localcpa);
    localcuR.setInsets(new Insets(0, 10, 0, 10));
    localJg1.bb(localcuR);
    localcuR.brn();
    localcuR.rV();
    localJg1.rV();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setName("playerGift");
    localNK.setField("selectedPackage/gifts");
    localNK.setAttribute("content");
    localccG1.bb(localNK);
    localNK.brn();
    localNK.rV();
    eR localeR = new eR();
    localeR.aJ();
    localeR.setElementMap(localcpa);
    localccG1.bb(localeR);
    localeR.brn();
    String str1 = "gift";
    avo localavo1 = new avo();
    localavo1.aJ();
    localavo1.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localavo1);
    localeR.bb(localavo1);
    localavo1.brn();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("value");
    localavo1.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    localavo1.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    cCu localcCu1 = new cCu();
    localcCu1.hg("popup(itemDescPopup)");
    localdRq1.setOnPopupDisplay(localcCu1);
    jL localjL1 = new jL();
    localjL1.hg("closePopup");
    localdRq1.setOnPopupHide(localjL1);
    csA localcsA1 = new csA();
    localcsA1.hg("wakfu.playerGift:openItemDetails(gift,window)");
    localdRq1.setOnClick(localcsA1);
    localeR.bb(localdRq1);
    localdRq1.brn();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("nonBlocking");
    localaaE2.setField("allowControls");
    localdRq1.bb(localaaE2);
    localaaE2.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localaaE2.bb(localanQ);
    localanQ.brn();
    bqW localbqW = new bqW();
    localbqW.aJ();
    localbqW.setElementMap(localcpa);
    localanQ.bb(localbqW);
    localbqW.brn();
    localbqW.rV();
    localanQ.rV();
    localaaE2.rV();
    String str2 = "itemDescPopup";
    anG localanG1 = new anG();
    localanG1.aJ();
    localanG1.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localanG1);
    localanG1.setAlign(aFG.ech);
    localanG1.setHotSpotPosition(aFG.ecn);
    localdRq1.bb(localanG1);
    localanG1.brn();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setPrefSize(new Or(10, 0));
    localdRq2.setStyle("popup");
    localanG1.bb(localdRq2);
    localdRq2.brn();
    aaE localaaE3 = new aaE();
    localaaE3.aJ();
    localaaE3.setElementMap(localcpa);
    localaaE3.setAttribute("visible");
    localaaE3.setField("allowControls");
    localdRq2.bb(localaaE3);
    localaaE3.brn();
    localaaE3.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("PopupInformation");
    localcWk1.setExpandable(false);
    String str3 = "%rightClickToShowDetailWindow%";
    str3 = str3.replace("%rightClickToShowDetailWindow%", cBQ.cxL().mL("rightClickToShowDetailWindow"));
    localcWk1.setText(str3);
    localdRq2.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg2 = localcWk2.getAppearance();
    localJg2.setElementMap(localcpa);
    ((cwJ)localJg2).setAlignment(aFG.ecj);
    localcWk1.bb(localJg2);
    localJg2.brn();
    localJg2.rV();
    localcWk1.rV();
    localdRq2.rV();
    localanG1.rV();
    String str4 = "gift";
    avo localavo2 = new avo();
    localavo2.aJ();
    localavo2.setElementMap(localcpa);
    if ((localcpa != null) && (str4 != null))
      localcpa.a(str4, localavo2);
    localdRq1.bb(localavo2);
    localavo2.brn();
    aaE localaaE4 = new aaE();
    localaaE4.aJ();
    localaaE4.setElementMap(localcpa);
    localaaE4.setAttribute("value");
    localavo2.bb(localaaE4);
    localaaE4.brn();
    localaaE4.rV();
    localavo2.rV();
    czO localczO = new czO();
    localczO.aJ();
    localczO.setAdaptToContentSize(true);
    localdRq1.bb(localczO);
    localczO.brn();
    localczO.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq3.setStyle("TiledScrollCenter");
    localdRq3.setPrefSize(new Or(0, 48));
    localdRq1.bb(localdRq3);
    localdRq3.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setAlign(ajb.dhZ);
    localcwP1.setSize(new Or(100.0F, 48));
    localdRq3.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    localdRq3.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setStyle("TiledScrollTop");
    localczv1.setDisplaySize(new Or(200, 3));
    localdRq1.bb(localczv1);
    localczv1.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.dhR);
    localcwP2.setSize(new Or(100.0F, -2));
    localczv1.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    localczv1.rV();
    czv localczv2 = new czv();
    localczv2.aJ();
    localczv2.setElementMap(localcpa);
    localczv2.setStyle("TiledScrollBottom");
    localczv2.setDisplaySize(new Or(200, 3));
    localdRq1.bb(localczv2);
    localczv2.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setAlign(ajb.did);
    localcwP3.setSize(new Or(100.0F, -2));
    localczv2.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    localczv2.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq1.bb(localdRq4);
    localdRq4.brn();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setAlign(ajb.dhZ);
    localcwP4.setSize(new Or(100.0F, -2));
    localdRq4.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    dRq localdRq5 = dRq.checkOut();
    localdRq5.setElementMap(localcpa);
    localdRq5.setStyle("encyclopediaSplash");
    localdRq5.setExpandable(false);
    localdRq4.bb(localdRq5);
    localdRq5.brn();
    czv localczv3 = new czv();
    localczv3.aJ();
    localczv3.setElementMap(localcpa);
    localczv3.setDisplaySize(new Or(32, 32));
    localczv3.setExpandable(false);
    localdRq5.bb(localczv3);
    localczv3.brn();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv3.bb(localaAR);
    localaAR.brn();
    aaE localaaE5 = new aaE();
    localaaE5.aJ();
    localaaE5.setElementMap(localcpa);
    localaaE5.setAttribute("texture");
    localaaE5.setField("iconUrl");
    localaAR.bb(localaaE5);
    localaaE5.brn();
    localaaE5.rV();
    localaAR.rV();
    localczv3.rV();
    localdRq5.rV();
    cWk localcWk3 = new cWk();
    localcWk3.aJ();
    localcWk3.setElementMap(localcpa);
    localcWk3.setStyle("darkBold");
    localcWk3.setExpandable(false);
    localcWk3.setMinWidth(1);
    localcWk3.setMaxWidth(280);
    localdRq4.bb(localcWk3);
    localcWk3.brn();
    cWk localcWk4 = localcWk3;
    Jg localJg3 = localcWk4.getAppearance();
    localJg3.setElementMap(localcpa);
    ((cwJ)localJg3).setAlignment(aFG.ecj);
    localcWk3.bb(localJg3);
    localJg3.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(0, 15, 0, 0));
    localJg3.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg3.rV();
    aaE localaaE6 = new aaE();
    localaaE6.aJ();
    localaaE6.setElementMap(localcpa);
    localaaE6.setAttribute("text");
    localaaE6.setField("name");
    localcWk3.bb(localaaE6);
    localaaE6.brn();
    localaaE6.rV();
    localcWk3.rV();
    dAS localdAS = new dAS();
    localdAS.aJ();
    localdAS.setElementMap(localcpa);
    localdRq4.bb(localdAS);
    localdAS.brn();
    localdAS.rV();
    biy localbiy = new biy();
    localbiy.aJ();
    localbiy.setElementMap(localcpa);
    localbiy.setNetEnabledId("giftLock");
    localbiy.setStyle("mru34");
    localbiy.setExpandable(false);
    csA localcsA2 = new csA();
    localcsA2.hg("wakfu.playerGift:consumeOneGift(gift)");
    localbiy.setOnClick(localcsA2);
    cCu localcCu2 = new cCu();
    localcCu2.hg("popup(consumeOneDescPopup)");
    localbiy.setOnPopupDisplay(localcCu2);
    jL localjL2 = new jL();
    localjL2.hg("closePopup");
    localbiy.setOnPopupHide(localjL2);
    localdRq4.bb(localbiy);
    localbiy.brn();
    String str5 = "consumeOneDescPopup";
    anG localanG2 = new anG();
    localanG2.aJ();
    localanG2.setElementMap(localcpa);
    if ((localcpa != null) && (str5 != null))
      localcpa.a(str5, localanG2);
    localanG2.setAlign(aFG.ech);
    localanG2.setHotSpotPosition(aFG.ecn);
    localbiy.bb(localanG2);
    localanG2.brn();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq6.setPrefSize(new Or(10, 0));
    localdRq6.setStyle("popup");
    localanG2.bb(localdRq6);
    localdRq6.brn();
    cWk localcWk5 = new cWk();
    localcWk5.aJ();
    localcWk5.setElementMap(localcpa);
    localcWk5.setStyle("white");
    localcWk5.setEnableShrinking(false);
    String str6 = "%gift.consumeOne%";
    str6 = str6.replace("%gift.consumeOne%", cBQ.cxL().mL("gift.consumeOne"));
    localcWk5.setText(str6);
    localdRq6.bb(localcWk5);
    localcWk5.brn();
    cWk localcWk6 = localcWk5;
    Jg localJg4 = localcWk6.getAppearance();
    localJg4.setElementMap(localcpa);
    ((cwJ)localJg4).setAlignment(aFG.eck);
    localcWk5.bb(localJg4);
    localJg4.brn();
    localJg4.rV();
    localcWk5.rV();
    localdRq6.rV();
    localanG2.rV();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.eck);
    localbiy.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    aaE localaaE7 = new aaE();
    localaaE7.aJ();
    localaaE7.setElementMap(localcpa);
    localaaE7.setAttribute("enabled");
    localaaE7.setField("allowControls");
    localbiy.bb(localaaE7);
    localaaE7.brn();
    localaaE7.rV();
    localbiy.rV();
    localdRq4.rV();
    localdRq1.rV();
    localeR.rV();
    localccG1.rV();
    return localccG1;
  }

  public bdj f(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq = dRq.checkOut();
    localdRq.setElementMap(localcpa);
    localdRq.setStyle("EncyclopediaPane");
    localdRq.setNonBlocking(true);
    parambdj.bb(localdRq);
    localdRq.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setAlign(ajb.dhZ);
    localcwP.setSize(new Or(454, 565));
    localcwP.setXOffset(-10);
    localcwP.setYOffset(1);
    localdRq.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localdRq.rV();
    return localdRq;
  }

  public bdj g(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dOc localdOc = (dOc)parambdj;
    Jg localJg = localdOc.getAppearance();
    localJg.setElementMap(localcpa);
    parambdj.bb(localJg);
    localJg.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(0, 59, 0, 0));
    localJg.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    cuR localcuR = new cuR();
    localcuR.aJ();
    localcuR.setElementMap(localcpa);
    localcuR.setInsets(new Insets(10, 5, 12, 5));
    localJg.bb(localcuR);
    localcuR.brn();
    localcuR.rV();
    localJg.rV();
    return localJg;
  }

  public bdj h(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setAlign(aFG.ecj);
    localdRq1.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setExpandable(false);
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(40, 0, 0, 0));
    localJg1.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg1.rV();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.ech);
    localdRq2.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    aId localaId2 = aId.checkOut();
    localaId2.setHorizontal(false);
    localdRq2.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    biy localbiy1 = new biy();
    localbiy1.aJ();
    localbiy1.setElementMap(localcpa);
    localbiy1.setStyle("upWhiteArrow");
    localbiy1.setExpandable(false);
    csA localcsA1 = new csA();
    localcsA1.hg("wakfu.playerGift:packageListOffset(packageList,-1)");
    localbiy1.setOnClick(localcsA1);
    localdRq2.bb(localbiy1);
    localbiy1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setName("playerGift");
    localNK1.setField("numPackages");
    localNK1.setAttribute("visible");
    localbiy1.bb(localNK1);
    localNK1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localNK1.bb(localanQ1);
    localanQ1.brn();
    aEJ localaEJ1 = new aEJ();
    localaEJ1.aJ();
    localaEJ1.setElementMap(localcpa);
    localaEJ1.setValue("5");
    localanQ1.bb(localaEJ1);
    localaEJ1.brn();
    localaEJ1.rV();
    localanQ1.rV();
    localNK1.rV();
    localbiy1.rV();
    String str1 = "giftGroup";
    bmG localbmG = new bmG();
    localbmG.aJ();
    localbmG.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localbmG);
    localdRq2.bb(localbmG);
    localbmG.brn();
    localbmG.rV();
    String str2 = "packageList";
    ccG localccG = new ccG();
    localccG.aJ();
    localccG.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localccG);
    localccG.setSelectionable(false);
    localccG.setScrollMode(aQA.eNm);
    localccG.setHorizontal(false);
    localccG.setCellSize(new Or(69, 80));
    localccG.setNonBlocking(false);
    localccG.setAutoIdealSize(true);
    localccG.setIdealSizeMinRows(1);
    localccG.setIdealSizeMaxRows(5);
    localccG.setIdealSizeMinColumns(1);
    localccG.setIdealSizeMaxColumns(1);
    localccG.setScrollBar(false);
    localccG.setScrollOnMouseWheel(true);
    aqC localaqC = new aqC();
    localaqC.hg("wakfu.playerGift:selectGiftPackage");
    localccG.setOnItemClick(localaqC);
    localdRq2.bb(localccG);
    localccG.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("playerGift");
    localNK2.setField("giftPackages");
    localNK2.setAttribute("content");
    localccG.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    eR localeR = new eR();
    localeR.aJ();
    localeR.setElementMap(localcpa);
    localccG.bb(localeR);
    localeR.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localeR.bb(localanQ2);
    localanQ2.brn();
    bxx localbxx = new bxx();
    localbxx.aJ();
    localbxx.setElementMap(localcpa);
    localanQ2.bb(localbxx);
    localbxx.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localbxx.bb(localanE);
    localanE.brn();
    localanE.rV();
    localbxx.rV();
    localanQ2.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localeR.bb(localdRq4);
    localdRq4.brn();
    czO localczO = new czO();
    localczO.aJ();
    localczO.setAdaptToContentSize(true);
    localdRq4.bb(localczO);
    localczO.brn();
    localczO.rV();
    aHd localaHd = new aHd();
    localaHd.aJ();
    localaHd.setElementMap(localcpa);
    localaHd.setStyle("bigLeftWindow");
    localaHd.setGroupId("giftGroup");
    cCu localcCu = new cCu();
    localcCu.hg("popup(giftPkgDescPopup)");
    localaHd.setOnPopupDisplay(localcCu);
    jL localjL = new jL();
    localjL.hg("closePopup");
    localaHd.setOnPopupHide(localjL);
    localdRq4.bb(localaHd);
    localaHd.brn();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("selected");
    localaHd.bb(localaaE1);
    localaaE1.brn();
    anQ localanQ3 = new anQ();
    localanQ3.aJ();
    localanQ3.setElementMap(localcpa);
    localaaE1.bb(localanQ3);
    localanQ3.brn();
    bSP localbSP = new bSP();
    localbSP.aJ();
    localbSP.setElementMap(localcpa);
    localanQ3.bb(localbSP);
    localbSP.brn();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setName("playerGift");
    localNK3.setField("selectedPackage");
    localNK3.setAttribute("value");
    localbSP.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    localbSP.rV();
    localanQ3.rV();
    localaaE1.rV();
    String str3 = "giftPkgDescPopup";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa);
    if ((localcpa != null) && (str3 != null))
      localcpa.a(str3, localanG);
    localanG.setAlign(aFG.ech);
    localanG.setHotSpotPosition(aFG.ecn);
    localaHd.bb(localanG);
    localanG.brn();
    dRq localdRq5 = dRq.checkOut();
    localdRq5.setElementMap(localcpa);
    localdRq5.setPrefSize(new Or(10, 0));
    localdRq5.setStyle("popup");
    localanG.bb(localdRq5);
    localdRq5.brn();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("white");
    localcWk1.setEnableShrinking(false);
    localcWk1.setMinWidth(1);
    localcWk1.setMaxWidth(250);
    localdRq5.bb(localcWk1);
    localcWk1.brn();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("text");
    localaaE2.setField("title");
    localcWk1.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    cWk localcWk2 = localcWk1;
    Jg localJg2 = localcWk2.getAppearance();
    localJg2.setElementMap(localcpa);
    ((cwJ)localJg2).setAlignment(aFG.ecj);
    localcWk1.bb(localJg2);
    localJg2.brn();
    localJg2.rV();
    localcWk1.rV();
    localdRq5.rV();
    localanG.rV();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setSize(new Or(69, 58));
    localcwP2.setAlign(ajb.dif);
    localaHd.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    aaE localaaE3 = new aaE();
    localaaE3.aJ();
    localaaE3.setElementMap(localcpa);
    localaaE3.setAttribute("text");
    localaaE3.setField("title");
    localaHd.bb(localaaE3);
    localaaE3.brn();
    localaaE3.rV();
    localaHd.rV();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setDisplaySize(new Or(48, 48));
    localczv.setNonBlocking(true);
    localdRq4.bb(localczv);
    localczv.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setSize(new Or(-2, -2));
    localcwP3.setAlign(ajb.dhT);
    localcwP3.setXOffset(-1);
    localczv.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv.bb(localaAR);
    localaAR.brn();
    aaE localaaE4 = new aaE();
    localaaE4.aJ();
    localaaE4.setElementMap(localcpa);
    localaaE4.setAttribute("texture");
    localaaE4.setField("iconUrl");
    localaAR.bb(localaaE4);
    localaaE4.brn();
    localaaE4.rV();
    localaAR.rV();
    localczv.rV();
    localdRq4.rV();
    localeR.rV();
    localccG.rV();
    biy localbiy2 = new biy();
    localbiy2.aJ();
    localbiy2.setElementMap(localcpa);
    localbiy2.setStyle("downWhiteArrow");
    localbiy2.setExpandable(false);
    csA localcsA2 = new csA();
    localcsA2.hg("wakfu.playerGift:packageListOffset(packageList,1)");
    localbiy2.setOnClick(localcsA2);
    localdRq2.bb(localbiy2);
    localbiy2.brn();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa);
    localNK4.setName("playerGift");
    localNK4.setField("numPackages");
    localNK4.setAttribute("visible");
    localbiy2.bb(localNK4);
    localNK4.brn();
    anQ localanQ4 = new anQ();
    localanQ4.aJ();
    localanQ4.setElementMap(localcpa);
    localNK4.bb(localanQ4);
    localanQ4.brn();
    aEJ localaEJ2 = new aEJ();
    localaEJ2.aJ();
    localaEJ2.setElementMap(localcpa);
    localaEJ2.setValue("5");
    localanQ4.bb(localaEJ2);
    localaEJ2.brn();
    localaEJ2.rV();
    localanQ4.rV();
    localNK4.rV();
    localbiy2.rV();
    localdRq2.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj i(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    biy localbiy = new biy();
    localbiy.aJ();
    localbiy.setElementMap(localcpa);
    localbiy.setStyle("close");
    localbiy.setExpandable(false);
    csA localcsA = new csA();
    localcsA.hg("wakfu.playerGift:openCloseDialog");
    localbiy.setOnClick(localcsA);
    parambdj.bb(localbiy);
    localbiy.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(-2, -2));
    localcwP.setAlign(ajb.dhV);
    localcwP.setXOffset(-18);
    localcwP.setYOffset(-12);
    localbiy.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localbiy.rV();
    return localbiy;
  }

  public bdj j(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(-2, -2));
    localcwP.setAlign(ajb.dhZ);
    localcwP.setResizeOnce(true);
    parambdj.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    return localcwP;
  }
}