import java.awt.Insets;
import java.util.Stack;

public class cjL
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setAlign(ajb.dhR);
    localcwP1.setXOffset(-10);
    localcwP1.setYOffset(-120);
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localdRq1.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setExpandable(false);
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 0, 3, 0));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.ecj);
    localdRq2.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    czO localczO1 = new czO();
    localczO1.aJ();
    localczO1.setAdaptToContentSize(true);
    localdRq2.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    biy localbiy = new biy();
    localbiy.aJ();
    localbiy.setElementMap(localcpa);
    localbiy.setStyle("yellow");
    csA localcsA1 = new csA();
    localcsA1.hg("wakfu.partyList:minimizeMaximizeDialog(mainSubContainer,minimizeImage)");
    localbiy.setOnClick(localcsA1);
    localdRq2.bb(localbiy);
    localbiy.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.dhZ);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localbiy.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    localbiy.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq2.bb(localdRq4);
    localdRq4.brn();
    dRq localdRq5 = localdRq4;
    Jg localJg2 = localdRq5.getAppearance();
    localJg2.setElementMap(localcpa);
    localdRq4.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 13, 0, 5));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setAlign(ajb.dhZ);
    localcwP3.setSize(new Or(100.0F, 100.0F));
    localdRq4.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    String str1 = "minimizeImage";
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localczv1);
    localczv1.setStyle("yellowLeftArrow");
    localczv1.setNonBlocking(true);
    localdRq4.bb(localczv1);
    localczv1.brn();
    localczv1.rV();
    czv localczv2 = new czv();
    localczv2.aJ();
    localczv2.setElementMap(localcpa);
    localczv2.setStyle("contactsIcon");
    localczv2.setNonBlocking(true);
    localdRq4.bb(localczv2);
    localczv2.brn();
    czv localczv3 = localczv2;
    Jg localJg3 = localczv3.getAppearance();
    localJg3.setElementMap(localcpa);
    localczv2.bb(localJg3);
    localJg3.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 3, 0, 0));
    localJg3.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg3.rV();
    localczv2.rV();
    localdRq4.rV();
    localdRq2.rV();
    String str2 = "mainSubContainer";
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localdRq6);
    localdRq1.bb(localdRq6);
    localdRq6.brn();
    dRq localdRq7 = localdRq6;
    Jg localJg4 = localdRq7.getAppearance();
    localJg4.setElementMap(localcpa);
    localdRq6.bb(localJg4);
    localJg4.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(0, 10, 0, 0));
    localJg4.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg4.rV();
    aId localaId2 = aId.checkOut();
    localaId2.setHorizontal(false);
    localdRq6.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    at localat1 = new at();
    localat1.aJ();
    localat1.setElementMap(localcpa);
    localat1.setHorizontal(false);
    localat1.setInnerExpandable(false);
    localat1.setSelectionable(false);
    localdRq6.bb(localat1);
    localat1.brn();
    aId localaId3 = aId.checkOut();
    localaId3.setHorizontal(false);
    localaId3.setAlign(aFG.ech);
    localat1.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    at localat2 = localat1;
    Jg localJg5 = localat2.getAppearance();
    localJg5.setElementMap(localcpa);
    localat1.bb(localJg5);
    localJg5.brn();
    bmv localbmv5 = bmv.checkOut();
    localbmv5.setElementMap(localcpa);
    localbmv5.setInsets(new Insets(0, 0, 0, 5));
    localJg5.bb(localbmv5);
    localbmv5.brn();
    localbmv5.rV();
    localJg5.rV();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setName("partyList");
    localNK.setAttribute("content");
    localNK.setField("members");
    localat1.bb(localNK);
    localNK.brn();
    localNK.rV();
    eR localeR = new eR();
    localeR.aJ();
    localeR.setElementMap(localcpa);
    localat1.bb(localeR);
    localeR.brn();
    dRq localdRq8 = dRq.checkOut();
    localdRq8.setElementMap(localcpa);
    csA localcsA2 = new csA();
    localcsA2.hg("wakfu.partyList:onPlayerClick(member)");
    localdRq8.setOnClick(localcsA2);
    localdRq8.setPrefSize(new Or(43, 34));
    localeR.bb(localdRq8);
    localdRq8.brn();
    dRq localdRq9 = localdRq8;
    Jg localJg6 = localdRq9.getAppearance();
    localJg6.setElementMap(localcpa);
    localdRq8.bb(localJg6);
    localJg6.brn();
    bmv localbmv6 = bmv.checkOut();
    localbmv6.setElementMap(localcpa);
    localbmv6.setInsets(new Insets(0, 0, 2, 0));
    localJg6.bb(localbmv6);
    localbmv6.brn();
    localbmv6.rV();
    localJg6.rV();
    String str3 = "member";
    avo localavo = new avo();
    localavo.aJ();
    localavo.setElementMap(localcpa);
    if ((localcpa != null) && (str3 != null))
      localcpa.a(str3, localavo);
    localdRq8.bb(localavo);
    localavo.brn();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("value");
    localavo.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    localavo.rV();
    aId localaId4 = aId.checkOut();
    localaId4.setAlign(aFG.ecj);
    localdRq8.bb(localaId4);
    localaId4.brn();
    localaId4.rV();
    dRq localdRq10 = dRq.checkOut();
    localdRq10.setElementMap(localcpa);
    cCu localcCu = new cCu();
    localcCu.hg("popup(infoPopup)");
    localdRq10.setOnPopupDisplay(localcCu);
    jL localjL = new jL();
    localjL.hg("closePopup");
    localdRq10.setOnPopupHide(localjL);
    localdRq8.bb(localdRq10);
    localdRq10.brn();
    String str4 = "infoPopup";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa);
    if ((localcpa != null) && (str4 != null))
      localcpa.a(str4, localanG);
    localanG.setAlign(aFG.ecl);
    localanG.setHotSpotPosition(aFG.ecj);
    localdRq10.bb(localanG);
    localanG.brn();
    dRq localdRq11 = dRq.checkOut();
    localdRq11.setElementMap(localcpa);
    localdRq11.setPrefSize(new Or(10, 0));
    localdRq11.setStyle("popup");
    localanG.bb(localdRq11);
    localdRq11.brn();
    aId localaId5 = aId.checkOut();
    localaId5.setHorizontal(false);
    localdRq11.bb(localaId5);
    localaId5.brn();
    localaId5.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("popupInformation");
    localcaF1.setEnableShrinking(false);
    localdRq11.bb(localcaF1);
    localcaF1.brn();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("text");
    localaaE2.setField("name");
    localcaF1.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    localcaF1.rV();
    caF localcaF2 = new caF();
    localcaF2.aJ();
    localcaF2.setElementMap(localcpa);
    localcaF2.setStyle("popupInformation");
    localcaF2.setEnableShrinking(false);
    localdRq11.bb(localcaF2);
    localcaF2.brn();
    aaE localaaE3 = new aaE();
    localaaE3.aJ();
    localaaE3.setElementMap(localcpa);
    localaaE3.setAttribute("text");
    localaaE3.setField("level");
    localcaF2.bb(localaaE3);
    localaaE3.brn();
    localaaE3.rV();
    localcaF2.rV();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setStyle("popupInformation");
    localcaF3.setEnableShrinking(false);
    localdRq11.bb(localcaF3);
    localcaF3.brn();
    aaE localaaE4 = new aaE();
    localaaE4.aJ();
    localaaE4.setElementMap(localcpa);
    localaaE4.setAttribute("text");
    localaaE4.setField("hpDescription");
    localcaF3.bb(localaaE4);
    localaaE4.brn();
    localaaE4.rV();
    localcaF3.rV();
    localdRq11.rV();
    localanG.rV();
    czO localczO2 = new czO();
    localczO2.aJ();
    localczO2.setAdaptToContentSize(true);
    localdRq10.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    czv localczv4 = new czv();
    localczv4.aJ();
    localczv4.setElementMap(localcpa);
    localczv4.setDisplaySize(new Or(30, 30));
    localdRq10.bb(localczv4);
    localczv4.brn();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setSize(new Or(30, 30));
    localcwP4.setAlign(ajb.dhY);
    localcwP4.setXOffset(11);
    localczv4.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    czv localczv5 = localczv4;
    Jg localJg7 = localczv5.getAppearance();
    localJg7.setElementMap(localcpa);
    localczv4.bb(localJg7);
    localJg7.brn();
    jO localjO = new jO();
    localjO.aJ();
    localjO.setElementMap(localcpa);
    localjO.setColor(new bNa(0.93F, 0.93F, 0.9F, 1.0F));
    localJg7.bb(localjO);
    localjO.brn();
    localjO.rV();
    localJg7.rV();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv4.bb(localaAR);
    localaAR.brn();
    aaE localaaE5 = new aaE();
    localaaE5.aJ();
    localaaE5.setElementMap(localcpa);
    localaaE5.setField("iconUrl");
    localaaE5.setAttribute("texture");
    localaAR.bb(localaaE5);
    localaaE5.brn();
    localaaE5.rV();
    localaAR.rV();
    localczv4.rV();
    czv localczv6 = new czv();
    localczv6.aJ();
    localczv6.setElementMap(localcpa);
    localczv6.setStyle("partyMember");
    localdRq10.bb(localczv6);
    localczv6.brn();
    cwP localcwP5 = new cwP();
    localcwP5.aJ();
    localcwP5.setElementMap(localcpa);
    localcwP5.setSize(new Or(-2, -2));
    localcwP5.setAlign(ajb.dhY);
    localczv6.bb(localcwP5);
    localcwP5.brn();
    localcwP5.rV();
    czv localczv7 = localczv6;
    Jg localJg8 = localczv7.getAppearance();
    localJg8.setElementMap(localcpa);
    localczv6.bb(localJg8);
    localJg8.brn();
    bmv localbmv7 = bmv.checkOut();
    localbmv7.setElementMap(localcpa);
    localbmv7.setInsets(new Insets(0, 0, 0, 16));
    localJg8.bb(localbmv7);
    localbmv7.brn();
    localbmv7.rV();
    aaE localaaE6 = new aaE();
    localaaE6.aJ();
    localaaE6.setElementMap(localcpa);
    localaaE6.setAttribute("modulationColor");
    localaaE6.setField("isLeader");
    localJg8.bb(localaaE6);
    localaaE6.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localanQ.setValue("1,0.8,0.6");
    localanQ.setElseValue("1,1,1");
    localaaE6.bb(localanQ);
    localanQ.brn();
    cOk localcOk = new cOk();
    localcOk.aJ();
    localcOk.setElementMap(localcpa);
    localanQ.bb(localcOk);
    localcOk.brn();
    localcOk.rV();
    localanQ.rV();
    localaaE6.rV();
    localJg8.rV();
    localczv6.rV();
    dRq localdRq12 = dRq.checkOut();
    localdRq12.setElementMap(localcpa);
    localdRq12.setExpandable(false);
    localdRq12.setPrefSize(new Or(10, 28));
    localdRq10.bb(localdRq12);
    localdRq12.brn();
    cwP localcwP6 = new cwP();
    localcwP6.aJ();
    localcwP6.setElementMap(localcpa);
    localcwP6.setAlign(ajb.dhY);
    localcwP6.setXOffset(2);
    localdRq12.bb(localcwP6);
    localcwP6.brn();
    localcwP6.rV();
    czO localczO3 = new czO();
    localczO3.aJ();
    localczO3.setAdaptToContentSize(true);
    localdRq12.bb(localczO3);
    localczO3.brn();
    localczO3.rV();
    alP localalP = new alP();
    localalP.aJ();
    localalP.setElementMap(localcpa);
    localalP.setHorizontal(false);
    localalP.setMaxBound(1.0F);
    localalP.setValue(1.0F);
    localalP.setUseIncreaseProgressTween(false);
    localalP.setUseDecreaseProgressTween(false);
    localalP.setStyle("hp");
    localalP.setNonBlocking(false);
    localdRq12.bb(localalP);
    localalP.brn();
    cwP localcwP7 = new cwP();
    localcwP7.aJ();
    localcwP7.setElementMap(localcpa);
    localcwP7.setSize(new Or(7, 100.0F));
    localcwP7.setAlign(ajb.dhZ);
    localalP.bb(localcwP7);
    localcwP7.brn();
    localcwP7.rV();
    aaE localaaE7 = new aaE();
    localaaE7.aJ();
    localaaE7.setElementMap(localcpa);
    localaaE7.setAttribute("value");
    localaaE7.setField("hpPercentage");
    localalP.bb(localaaE7);
    localaaE7.brn();
    localaaE7.rV();
    localalP.rV();
    dRq localdRq13 = dRq.checkOut();
    localdRq13.setElementMap(localcpa);
    localdRq13.setStyle("verticalProgressBar");
    localdRq12.bb(localdRq13);
    localdRq13.brn();
    cwP localcwP8 = new cwP();
    localcwP8.aJ();
    localcwP8.setElementMap(localcpa);
    localcwP8.setSize(new Or(100.0F, 100.0F));
    localcwP8.setAlign(ajb.dhZ);
    localdRq13.bb(localcwP8);
    localcwP8.brn();
    localcwP8.rV();
    localdRq13.rV();
    localdRq12.rV();
    czv localczv8 = new czv();
    localczv8.aJ();
    localczv8.setElementMap(localcpa);
    localdRq10.bb(localczv8);
    localczv8.brn();
    cwP localcwP9 = new cwP();
    localcwP9.aJ();
    localcwP9.setElementMap(localcpa);
    localcwP9.setSize(new Or(-2, -2));
    localcwP9.setAlign(ajb.dih);
    localczv8.bb(localcwP9);
    localcwP9.brn();
    localcwP9.rV();
    aaE localaaE8 = new aaE();
    localaaE8.aJ();
    localaaE8.setElementMap(localcpa);
    localaaE8.setAttribute("style");
    localaaE8.setField("stateStyle");
    localczv8.bb(localaaE8);
    localaaE8.brn();
    localaaE8.rV();
    localczv8.rV();
    localdRq10.rV();
    localdRq8.rV();
    localeR.rV();
    localat1.rV();
    dRq localdRq14 = dRq.checkOut();
    localdRq14.setElementMap(localcpa);
    localdRq6.bb(localdRq14);
    localdRq14.brn();
    a(localdRq14);
    b(localdRq14);
    d(localdRq14);
    e(localdRq14);
    localdRq14.rV();
    f(localdRq6);
    localdRq6.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj a(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.ecj);
    parambdj.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    return localdpm;
  }

  public bdj b(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(true);
    parambdj.bb(localaId);
    localaId.brn();
    localaId.rV();
    return null;
  }

  public bdj d(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    czO localczO = new czO();
    localczO.aJ();
    localczO.setAdaptToContentSize(true);
    localdRq1.bb(localczO);
    localczO.brn();
    localczO.rV();
    biy localbiy1 = new biy();
    localbiy1.aJ();
    localbiy1.setElementMap(localcpa);
    localbiy1.setStyle("yellow");
    cCu localcCu = new cCu();
    localcCu.hg("popup(invitePopup)");
    localbiy1.setOnPopupDisplay(localcCu);
    jL localjL = new jL();
    localjL.hg("closePopup");
    localbiy1.setOnPopupHide(localjL);
    csA localcsA = new csA();
    localcsA.hg("wakfu.partyList:openInviteDialog");
    localbiy1.setOnClick(localcsA);
    localdRq1.bb(localbiy1);
    localbiy1.brn();
    String str1 = "invitePopup";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localanG);
    localanG.setAlign(aFG.ech);
    localanG.setHotSpotPosition(aFG.ecn);
    localbiy1.bb(localanG);
    localanG.brn();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setPrefSize(new Or(10, 0));
    localdRq2.setStyle("popup");
    localanG.bb(localdRq2);
    localdRq2.brn();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("white");
    String str2 = "%group.party.invite.action%";
    str2 = str2.replace("%group.party.invite.action%", cBQ.cxL().mL("group.party.invite.action"));
    localcWk1.setText(str2);
    localdRq2.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg1 = localcWk2.getAppearance();
    localJg1.setElementMap(localcpa);
    ((cwJ)localJg1).setAlignment(aFG.ecj);
    localcWk1.bb(localJg1);
    localJg1.brn();
    localJg1.rV();
    localcWk1.rV();
    localdRq2.rV();
    localanG.rV();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setAlign(ajb.dhZ);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localbiy1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    biy localbiy2 = localbiy1;
    Jg localJg2 = localbiy2.getAppearance();
    localJg2.setElementMap(localcpa);
    localbiy1.bb(localJg2);
    localJg2.brn();
    cuR localcuR = new cuR();
    localcuR.aJ();
    localcuR.setElementMap(localcpa);
    localcuR.setInsets(new Insets(2, 1, 2, 2));
    localJg2.bb(localcuR);
    localcuR.brn();
    localcuR.rV();
    localJg2.rV();
    localbiy1.rV();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setStyle("partyInviteIcon");
    localczv.setNonBlocking(true);
    localdRq1.bb(localczv);
    localczv.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.dhZ);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localczv.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    localczv.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj e(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    dRq localdRq2 = localdRq1;
    Jg localJg1 = localdRq2.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq1.bb(localJg1);
    localJg1.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(0, 2, 0, 0));
    localJg1.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg1.rV();
    czO localczO = new czO();
    localczO.aJ();
    localczO.setAdaptToContentSize(true);
    localdRq1.bb(localczO);
    localczO.brn();
    localczO.rV();
    biy localbiy1 = new biy();
    localbiy1.aJ();
    localbiy1.setElementMap(localcpa);
    localbiy1.setStyle("yellow");
    cCu localcCu = new cCu();
    localcCu.hg("popup(leavePopup)");
    localbiy1.setOnPopupDisplay(localcCu);
    jL localjL = new jL();
    localjL.hg("closePopup");
    localbiy1.setOnPopupHide(localjL);
    csA localcsA = new csA();
    localcsA.hg("wakfu.partyList:leaveParty");
    localbiy1.setOnClick(localcsA);
    localdRq1.bb(localbiy1);
    localbiy1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setName("isInFight");
    localNK1.setAttribute("enabled");
    localbiy1.bb(localNK1);
    localNK1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localNK1.bb(localanQ1);
    localanQ1.brn();
    bqW localbqW1 = new bqW();
    localbqW1.aJ();
    localbqW1.setElementMap(localcpa);
    localanQ1.bb(localbqW1);
    localbqW1.brn();
    localbqW1.rV();
    localanQ1.rV();
    localNK1.rV();
    String str1 = "leavePopup";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localanG);
    localanG.setAlign(aFG.ech);
    localanG.setHotSpotPosition(aFG.ecn);
    localbiy1.bb(localanG);
    localanG.brn();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq3.setPrefSize(new Or(10, 0));
    localdRq3.setStyle("popup");
    localanG.bb(localdRq3);
    localdRq3.brn();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("white");
    localdRq3.bb(localcWk1);
    localcWk1.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("isInFight");
    localNK2.setAttribute("text");
    localcWk1.bb(localNK2);
    localNK2.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    String str2 = "%group.party.leave.action%";
    str2 = str2.replace("%group.party.leave.action%", cBQ.cxL().mL("group.party.leave.action"));
    localanQ2.setValue(str2);
    String str3 = "%group.party.leave.action.impossibleInFight%";
    str3 = str3.replace("%group.party.leave.action.impossibleInFight%", cBQ.cxL().mL("group.party.leave.action.impossibleInFight"));
    localanQ2.setElseValue(str3);
    localNK2.bb(localanQ2);
    localanQ2.brn();
    bqW localbqW2 = new bqW();
    localbqW2.aJ();
    localbqW2.setElementMap(localcpa);
    localanQ2.bb(localbqW2);
    localbqW2.brn();
    localbqW2.rV();
    localanQ2.rV();
    localNK2.rV();
    cWk localcWk2 = localcWk1;
    Jg localJg2 = localcWk2.getAppearance();
    localJg2.setElementMap(localcpa);
    ((cwJ)localJg2).setAlignment(aFG.ecj);
    localcWk1.bb(localJg2);
    localJg2.brn();
    localJg2.rV();
    localcWk1.rV();
    localdRq3.rV();
    localanG.rV();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setAlign(ajb.dhZ);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localbiy1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    biy localbiy2 = localbiy1;
    Jg localJg3 = localbiy2.getAppearance();
    localJg3.setElementMap(localcpa);
    localbiy1.bb(localJg3);
    localJg3.brn();
    cuR localcuR = new cuR();
    localcuR.aJ();
    localcuR.setElementMap(localcpa);
    localcuR.setInsets(new Insets(2, 2, 2, 2));
    localJg3.bb(localcuR);
    localcuR.brn();
    localcuR.rV();
    localJg3.rV();
    localbiy1.rV();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setStyle("cancel");
    localczv.setDisplaySize(new Or(12, 12));
    localczv.setNonBlocking(true);
    localdRq1.bb(localczv);
    localczv.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.dhZ);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localczv.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    localczv.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj f(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    localdRq1.setPrefSize(new Or(43, 0));
    parambdj.bb(localdRq1);
    localdRq1.brn();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.ecl);
    localdRq1.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setAttribute("visible");
    localNK.setName("partyList");
    localNK.setField("members");
    localdRq1.bb(localNK);
    localNK.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localNK.bb(localanQ);
    localanQ.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localanQ.bb(localanE);
    localanE.brn();
    localanE.rV();
    localanQ.rV();
    localNK.rV();
    dRq localdRq2 = localdRq1;
    Jg localJg = localdRq2.getAppearance();
    localJg.setElementMap(localcpa);
    localdRq1.bb(localJg);
    localJg.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(0, 0, 5, 0));
    localJg.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg.rV();
    localdRq1.rV();
    return localdRq1;
  }
}