import java.awt.Insets;
import java.util.Stack;

public class dwf
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    bpn localbpn = new bpn();
    localbpn.aJ();
    localbpn.setElementMap(localcpa);
    localbpn.brn();
    czO localczO1 = new czO();
    localczO1.aJ();
    localczO1.setAdaptToContentSize(true);
    localbpn.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localbpn.bb(localdRq1);
    localdRq1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    localdRq1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setStyle("windowNew");
    localbpn.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(10, 5, 12, 5));
    localJg1.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    localJg1.rV();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localdRq2.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localaId1.setAlign(aFG.ech);
    localdRq2.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dqa localdqa1 = new dqa();
    localdqa1.aJ();
    localdqa1.setElementMap(localcpa);
    localdqa1.setExpandable(false);
    localdqa1.setEnabled(false);
    localdRq2.bb(localdqa1);
    localdqa1.brn();
    dqa localdqa2 = localdqa1;
    Jg localJg2 = localdqa2.getAppearance();
    localJg2.setElementMap(localcpa);
    localdqa1.bb(localJg2);
    localJg2.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 10, 0, 10));
    localJg2.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg2.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setStyle("titleBar");
    localdqa1.bb(localdRq4);
    localdRq4.brn();
    dRq localdRq5 = localdRq4;
    Jg localJg3 = localdRq5.getAppearance();
    localJg3.setElementMap(localcpa);
    localdRq4.bb(localJg3);
    localJg3.brn();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(2, 20, 3, 20));
    localJg3.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    localJg3.rV();
    aId localaId2 = aId.checkOut();
    localaId2.setHorizontal(false);
    localdRq4.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq6.setExpandable(false);
    localdRq4.bb(localdRq6);
    localdRq6.brn();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.eck);
    localdRq6.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("StyledBold16White");
    localcaF1.setNonBlocking(true);
    String str1 = "%guild.creation%";
    str1 = str1.replace("%guild.creation%", cBQ.cxL().mL("guild.creation"));
    localcaF1.setText(str1);
    localdRq6.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg4 = localcaF2.getAppearance();
    localJg4.setElementMap(localcpa);
    ((cwJ)localJg4).setAlign(aFG.eck);
    localcaF1.bb(localJg4);
    localJg4.brn();
    localJg4.rV();
    localcaF1.rV();
    localdRq6.rV();
    localdRq4.rV();
    localdqa1.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localdRq2.bb(localdRq7);
    localdRq7.brn();
    dRq localdRq8 = localdRq7;
    Jg localJg5 = localdRq8.getAppearance();
    localJg5.setElementMap(localcpa);
    localdRq7.bb(localJg5);
    localJg5.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 12, 0, 12));
    localJg5.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg5.rV();
    String str2 = "windowContentContainer";
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localdRq9);
    localdRq9.setPrefSize(new Or(0, 0));
    localdRq7.bb(localdRq9);
    localdRq9.brn();
    bTm localbTm = new bTm();
    localbTm.aJ();
    localdRq9.bb(localbTm);
    localbTm.brn();
    localbTm.rV();
    dRq localdRq10 = dRq.checkOut();
    localdRq10.setElementMap(localcpa);
    localdRq10.setStyle("flat");
    localdRq9.bb(localdRq10);
    localdRq10.brn();
    cba localcba1 = cba.checkOut();
    localcba1.setElementMap(localcpa);
    localcba1.setData(cFu.izS);
    localdRq10.bb(localcba1);
    localcba1.brn();
    localcba1.rV();
    dRq localdRq11 = localdRq10;
    Jg localJg6 = localdRq11.getAppearance();
    localJg6.setElementMap(localcpa);
    localdRq10.bb(localJg6);
    localJg6.brn();
    cuR localcuR3 = new cuR();
    localcuR3.aJ();
    localcuR3.setElementMap(localcpa);
    localcuR3.setInsets(new Insets(5, 5, 5, 5));
    localJg6.bb(localcuR3);
    localcuR3.brn();
    localcuR3.rV();
    localJg6.rV();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setStyle("styledDark12");
    localcaF3.setExpandable(false);
    String str3 = "%guild.name%";
    str3 = str3.replace("%guild.name%", cBQ.cxL().mL("guild.name"));
    localcaF3.setText(str3);
    localdRq10.bb(localcaF3);
    localcaF3.brn();
    caF localcaF4 = localcaF3;
    Jg localJg7 = localcaF4.getAppearance();
    localJg7.setElementMap(localcpa);
    localcaF3.bb(localJg7);
    localJg7.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 0, 0, 5));
    localJg7.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg7.rV();
    localcaF3.rV();
    String str4 = "guildName";
    aTp localaTp = new aTp();
    localaTp.aJ();
    localaTp.setElementMap(localcpa);
    if ((localcpa != null) && (str4 != null))
      localcpa.a(str4, localaTp);
    localaTp.setMaxChars(30);
    localdRq10.bb(localaTp);
    localaTp.brn();
    localaTp.rV();
    localdRq10.rV();
    dRq localdRq12 = dRq.checkOut();
    localdRq12.setElementMap(localcpa);
    localdRq12.setStyle("flat");
    localdRq9.bb(localdRq12);
    localdRq12.brn();
    dRq localdRq13 = localdRq12;
    Jg localJg8 = localdRq13.getAppearance();
    localJg8.setElementMap(localcpa);
    localdRq12.bb(localJg8);
    localJg8.brn();
    cuR localcuR4 = new cuR();
    localcuR4.aJ();
    localcuR4.setElementMap(localcpa);
    localcuR4.setInsets(new Insets(5, 5, 5, 5));
    localJg8.bb(localcuR4);
    localcuR4.brn();
    localcuR4.rV();
    localJg8.rV();
    cba localcba2 = cba.checkOut();
    localcba2.setElementMap(localcpa);
    localcba2.setData(cFu.izV);
    localdRq12.bb(localcba2);
    localcba2.brn();
    localcba2.rV();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setDisplaySize(new Or(64, 64));
    localdRq12.bb(localczv);
    localczv.brn();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv.bb(localaAR);
    localaAR.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setName("guildBannerTexture");
    localNK1.setAttribute("texture");
    localaAR.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    localaAR.rV();
    localczv.rV();
    localdRq12.rV();
    dRq localdRq14 = dRq.checkOut();
    localdRq14.setElementMap(localcpa);
    localdRq9.bb(localdRq14);
    localdRq14.brn();
    cba localcba3 = cba.checkOut();
    localcba3.setElementMap(localcpa);
    localcba3.setData(cFu.izR);
    localdRq14.bb(localcba3);
    localcba3.brn();
    localcba3.rV();
    aId localaId3 = aId.checkOut();
    localaId3.setHorizontal(false);
    localdRq14.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    String str5 = "styleChooserContainer";
    dRq localdRq15 = dRq.checkOut();
    localdRq15.setElementMap(localcpa);
    if ((localcpa != null) && (str5 != null))
      localcpa.a(str5, localdRq15);
    localdRq15.setStyle("flat");
    localdRq14.bb(localdRq15);
    localdRq15.brn();
    dRq localdRq16 = localdRq15;
    Jg localJg9 = localdRq16.getAppearance();
    localJg9.setElementMap(localcpa);
    localdRq15.bb(localJg9);
    localJg9.brn();
    cuR localcuR5 = new cuR();
    localcuR5.aJ();
    localcuR5.setElementMap(localcpa);
    localcuR5.setInsets(new Insets(5, 5, 5, 5));
    localJg9.bb(localcuR5);
    localcuR5.brn();
    localcuR5.rV();
    localJg9.rV();
    aId localaId4 = aId.checkOut();
    localaId4.setHorizontal(false);
    localaId4.setAlign(aFG.eck);
    localdRq15.bb(localaId4);
    localaId4.brn();
    localaId4.rV();
    dRq localdRq17 = dRq.checkOut();
    localdRq17.setElementMap(localcpa);
    localdRq17.setExpandable(false);
    localdRq15.bb(localdRq17);
    localdRq17.brn();
    aId localaId5 = aId.checkOut();
    localaId5.setHgap((short)5);
    localdRq17.bb(localaId5);
    localaId5.brn();
    localaId5.rV();
    biy localbiy1 = new biy();
    localbiy1.aJ();
    localbiy1.setElementMap(localcpa);
    localbiy1.setExpandable(false);
    localbiy1.setStyle("CharacterCreationLeftArrow");
    csA localcsA1 = new csA();
    localcsA1.hg("wakfu.guildBannerCreator:previousBackground");
    localbiy1.setOnClick(localcsA1);
    localdRq17.bb(localbiy1);
    localbiy1.brn();
    localbiy1.rV();
    caF localcaF5 = new caF();
    localcaF5.aJ();
    localcaF5.setElementMap(localcpa);
    localcaF5.setStyle("styledDark12");
    String str6 = "%guild.banner.background%";
    str6 = str6.replace("%guild.banner.background%", cBQ.cxL().mL("guild.banner.background"));
    localcaF5.setText(str6);
    localdRq17.bb(localcaF5);
    localcaF5.brn();
    caF localcaF6 = localcaF5;
    Jg localJg10 = localcaF6.getAppearance();
    localJg10.setElementMap(localcpa);
    ((cwJ)localJg10).setAlign(aFG.eck);
    localcaF5.bb(localJg10);
    localJg10.brn();
    localJg10.rV();
    localcaF5.rV();
    biy localbiy2 = new biy();
    localbiy2.aJ();
    localbiy2.setElementMap(localcpa);
    localbiy2.setExpandable(false);
    localbiy2.setStyle("CharacterCreationRightArrow");
    csA localcsA2 = new csA();
    localcsA2.hg("wakfu.guildBannerCreator:nextBackground");
    localbiy2.setOnClick(localcsA2);
    localdRq17.bb(localbiy2);
    localbiy2.brn();
    localbiy2.rV();
    dRq localdRq18 = dRq.checkOut();
    localdRq18.setElementMap(localcpa);
    localdRq18.setExpandable(false);
    localdRq17.bb(localdRq18);
    localdRq18.brn();
    dRq localdRq19 = localdRq18;
    Jg localJg11 = localdRq19.getAppearance();
    localJg11.setElementMap(localcpa);
    localdRq18.bb(localJg11);
    localJg11.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(5, 0, 0, 0));
    localJg11.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg11.rV();
    czO localczO2 = new czO();
    localczO2.aJ();
    localczO2.setAdaptToContentSize(true);
    localdRq18.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    dRq localdRq20 = dRq.checkOut();
    localdRq20.setElementMap(localcpa);
    localdRq20.setExpandable(false);
    localdRq20.setPrefSize(new Or(18, 13));
    localdRq18.bb(localdRq20);
    localdRq20.brn();
    dRq localdRq21 = localdRq20;
    Jg localJg12 = localdRq21.getAppearance();
    localJg12.setElementMap(localcpa);
    localdRq20.bb(localJg12);
    localJg12.brn();
    jO localjO = new jO();
    localjO.aJ();
    localjO.setElementMap(localcpa);
    localJg12.bb(localjO);
    localjO.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("guildBannerPrimaryColor");
    localNK2.setAttribute("color");
    localjO.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localjO.rV();
    localJg12.rV();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setAlign(ajb.dhZ);
    localcwP3.setSize(new Or(-2, -2));
    localdRq20.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    localdRq20.rV();
    aHd localaHd = new aHd();
    localaHd.aJ();
    localaHd.setElementMap(localcpa);
    localaHd.setStyle("guildCreationColor");
    csA localcsA3 = new csA();
    localcsA3.hg("wakfu.guildBannerCreator:setFirstPartBackgroundColorType(styleChooserContainer,colorPickerContainer)");
    localaHd.setOnClick(localcsA3);
    localdRq18.bb(localaHd);
    localaHd.brn();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setAlign(ajb.dhZ);
    localcwP4.setSize(new Or(-2, -2));
    localaHd.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    localaHd.rV();
    localdRq18.rV();
    localdRq17.rV();
    dRq localdRq22 = dRq.checkOut();
    localdRq22.setElementMap(localcpa);
    localdRq22.setExpandable(false);
    localdRq15.bb(localdRq22);
    localdRq22.brn();
    aId localaId6 = aId.checkOut();
    localaId6.setHgap((short)5);
    localdRq22.bb(localaId6);
    localaId6.brn();
    localaId6.rV();
    biy localbiy3 = new biy();
    localbiy3.aJ();
    localbiy3.setElementMap(localcpa);
    localbiy3.setExpandable(false);
    localbiy3.setStyle("CharacterCreationLeftArrow");
    csA localcsA4 = new csA();
    localcsA4.hg("wakfu.guildBannerCreator:previousForeground");
    localbiy3.setOnClick(localcsA4);
    localdRq22.bb(localbiy3);
    localbiy3.brn();
    localbiy3.rV();
    caF localcaF7 = new caF();
    localcaF7.aJ();
    localcaF7.setElementMap(localcpa);
    localcaF7.setStyle("styledDark12");
    String str7 = "%guild.banner.details%";
    str7 = str7.replace("%guild.banner.details%", cBQ.cxL().mL("guild.banner.details"));
    localcaF7.setText(str7);
    localdRq22.bb(localcaF7);
    localcaF7.brn();
    caF localcaF8 = localcaF7;
    Jg localJg13 = localcaF8.getAppearance();
    localJg13.setElementMap(localcpa);
    ((cwJ)localJg13).setAlign(aFG.eck);
    localcaF7.bb(localJg13);
    localJg13.brn();
    localJg13.rV();
    localcaF7.rV();
    biy localbiy4 = new biy();
    localbiy4.aJ();
    localbiy4.setElementMap(localcpa);
    localbiy4.setExpandable(false);
    localbiy4.setStyle("CharacterCreationRightArrow");
    csA localcsA5 = new csA();
    localcsA5.hg("wakfu.guildBannerCreator:nextForeground");
    localbiy4.setOnClick(localcsA5);
    localdRq22.bb(localbiy4);
    localbiy4.brn();
    localbiy4.rV();
    dRq localdRq23 = dRq.checkOut();
    localdRq23.setElementMap(localcpa);
    localdRq23.setExpandable(false);
    localdRq22.bb(localdRq23);
    localdRq23.brn();
    dRq localdRq24 = localdRq23;
    Jg localJg14 = localdRq24.getAppearance();
    localJg14.setElementMap(localcpa);
    localdRq23.bb(localJg14);
    localJg14.brn();
    bmv localbmv5 = bmv.checkOut();
    localbmv5.setElementMap(localcpa);
    localbmv5.setInsets(new Insets(5, 0, 0, 0));
    localJg14.bb(localbmv5);
    localbmv5.brn();
    localbmv5.rV();
    localJg14.rV();
    czO localczO3 = new czO();
    localczO3.aJ();
    localczO3.setAdaptToContentSize(true);
    localdRq23.bb(localczO3);
    localczO3.brn();
    localczO3.rV();
    a(localdRq23);
    b(localdRq23);
    localdRq23.rV();
    localdRq22.rV();
    localdRq15.rV();
    d(localdRq14);
    localdRq14.rV();
    e(localdRq9);
    localdRq9.rV();
    localdRq7.rV();
    localdRq2.rV();
    f(localbpn);
    g(localbpn);
    h(localbpn);
    localbpn.rV();
    return localbpn;
  }

  public bdj a(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    localdRq1.setPrefSize(new Or(18, 13));
    parambdj.bb(localdRq1);
    localdRq1.brn();
    dRq localdRq2 = localdRq1;
    Jg localJg = localdRq2.getAppearance();
    localJg.setElementMap(localcpa);
    localdRq1.bb(localJg);
    localJg.brn();
    jO localjO = new jO();
    localjO.aJ();
    localjO.setElementMap(localcpa);
    localJg.bb(localjO);
    localjO.brn();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setName("guildBannerSecondaryColor");
    localNK.setAttribute("color");
    localjO.bb(localNK);
    localNK.brn();
    localNK.rV();
    localjO.rV();
    localJg.rV();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setAlign(ajb.dhZ);
    localcwP.setSize(new Or(-2, -2));
    localdRq1.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj b(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    aHd localaHd = new aHd();
    localaHd.aJ();
    localaHd.setElementMap(localcpa);
    localaHd.setStyle("guildCreationColor");
    csA localcsA = new csA();
    localcsA.hg("wakfu.guildBannerCreator:setFirstPartForegroundColorType(styleChooserContainer,colorPickerContainer)");
    localaHd.setOnClick(localcsA);
    parambdj.bb(localaHd);
    localaHd.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setAlign(ajb.dhZ);
    localcwP.setSize(new Or(-2, -2));
    localaHd.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localaHd.rV();
    return localaHd;
  }

  public bdj d(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    String str = "colorPickerContainer";
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    if ((localcpa != null) && (str != null))
      localcpa.a(str, localdRq1);
    localdRq1.setVisible(false);
    localdRq1.setStyle("flat");
    parambdj.bb(localdRq1);
    localdRq1.brn();
    dRq localdRq2 = localdRq1;
    Jg localJg = localdRq2.getAppearance();
    localJg.setElementMap(localcpa);
    localdRq1.bb(localJg);
    localJg.brn();
    cuR localcuR = new cuR();
    localcuR.aJ();
    localcuR.setElementMap(localcpa);
    localcuR.setInsets(new Insets(5, 5, 5, 5));
    localJg.bb(localcuR);
    localcuR.brn();
    localcuR.rV();
    localJg.rV();
    aId localaId = aId.checkOut();
    localaId.setHgap((short)5);
    localdRq1.bb(localaId);
    localaId.brn();
    localaId.rV();
    cow localcow = new cow();
    localcow.aJ();
    localcow.setElementMap(localcpa);
    localcow.setNumByLines(4);
    localcow.setHorizontal(false);
    localcow.setExpandable(false);
    aqC localaqC = new aqC();
    localaqC.hg("wakfu.guildBannerCreator:selectColor");
    localcow.setOnItemClick(localaqC);
    localdRq1.bb(localcow);
    localcow.brn();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setName("guildBannerColors");
    localNK.setAttribute("colors");
    localcow.bb(localNK);
    localNK.brn();
    localNK.rV();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa);
    localdpm1.setAlign(aFG.eck);
    localcow.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    localcow.rV();
    biy localbiy = new biy();
    localbiy.aJ();
    localbiy.setElementMap(localcpa);
    localbiy.setStyle("smallValid");
    localbiy.setExpandable(false);
    csA localcsA = new csA();
    localcsA.hg("wakfu.guildBannerCreator:closeColorPicker(styleChooserContainer,colorPickerContainer)");
    localbiy.setOnClick(localcsA);
    localdRq1.bb(localbiy);
    localbiy.brn();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa);
    localdpm2.setAlign(aFG.eck);
    localbiy.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    localbiy.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj e(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    cba localcba = cba.checkOut();
    localcba.setElementMap(localcpa);
    localcba.setData(cFu.izT);
    localdRq1.bb(localcba);
    localcba.brn();
    localcba.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    czO localczO1 = new czO();
    localczO1.aJ();
    localczO1.setAdaptToContentSize(true);
    localdRq2.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    String str1 = "kamaButton";
    biy localbiy1 = new biy();
    localbiy1.aJ();
    localbiy1.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localbiy1);
    localbiy1.setStyle("flatBig");
    csA localcsA1 = new csA();
    localcsA1.hg("wakfu.guildBannerCreator:createGuild(guildName,true)");
    localbiy1.setOnClick(localcsA1);
    localdRq2.bb(localbiy1);
    localbiy1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localbiy1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setName("guildCreation.hasMoney");
    localNK1.setAttribute("enabled");
    localbiy1.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    biy localbiy2 = localbiy1;
    Jg localJg1 = localbiy2.getAppearance();
    localJg1.setElementMap(localcpa);
    localbiy1.bb(localJg1);
    localJg1.brn();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(5, 5, 5, 5));
    localJg1.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    localJg1.rV();
    localbiy1.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq2.bb(localdRq3);
    localdRq3.brn();
    dRq localdRq4 = localdRq3;
    Jg localJg2 = localdRq4.getAppearance();
    localJg2.setElementMap(localcpa);
    localdRq3.bb(localJg2);
    localJg2.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(5, 5, 5, 5));
    localJg2.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg2.rV();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.dhZ);
    localcwP2.setSize(new Or(-2, -2));
    localdRq3.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localdRq3.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("styledDark12");
    String str2 = "%guild.create%";
    str2 = str2.replace("%guild.create%", cBQ.cxL().mL("guild.create"));
    localcaF1.setText(str2);
    localcaF1.setNonBlocking(true);
    localdRq3.bb(localcaF1);
    localcaF1.brn();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa);
    localdpm1.setAlign(aFG.eck);
    localcaF1.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    localcaF1.rV();
    dRq localdRq5 = dRq.checkOut();
    localdRq5.setElementMap(localcpa);
    localdRq3.bb(localdRq5);
    localdRq5.brn();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa);
    localdpm2.setAlign(aFG.eck);
    localdRq5.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    caF localcaF2 = new caF();
    localcaF2.aJ();
    localcaF2.setElementMap(localcpa);
    localcaF2.setStyle("styledDark12");
    localcaF2.setNonBlocking(true);
    localdRq5.bb(localcaF2);
    localcaF2.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("guildCreation.feeDescription");
    localNK2.setAttribute("text");
    localcaF2.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localcaF2.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setStyle("kamas");
    localczv1.setExpandable(false);
    localczv1.setNonBlocking(true);
    localdRq5.bb(localczv1);
    localczv1.brn();
    localczv1.rV();
    localdRq5.rV();
    localdRq3.rV();
    localdRq2.rV();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq1.bb(localdRq6);
    localdRq6.brn();
    czO localczO2 = new czO();
    localczO2.aJ();
    localczO2.setAdaptToContentSize(true);
    localdRq6.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    String str3 = "objectButton";
    biy localbiy3 = new biy();
    localbiy3.aJ();
    localbiy3.setElementMap(localcpa);
    if ((localcpa != null) && (str3 != null))
      localcpa.a(str3, localbiy3);
    localbiy3.setStyle("flatBig");
    csA localcsA2 = new csA();
    localcsA2.hg("wakfu.guildBannerCreator:createGuild(guildName,false)");
    localbiy3.setOnClick(localcsA2);
    localdRq6.bb(localbiy3);
    localbiy3.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setSize(new Or(100.0F, 100.0F));
    localbiy3.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setName("guildCreation.hasItem");
    localNK3.setAttribute("enabled");
    localbiy3.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    biy localbiy4 = localbiy3;
    Jg localJg3 = localbiy4.getAppearance();
    localJg3.setElementMap(localcpa);
    localbiy3.bb(localJg3);
    localJg3.brn();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(5, 5, 5, 5));
    localJg3.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    localJg3.rV();
    localbiy3.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localdRq6.bb(localdRq7);
    localdRq7.brn();
    dRq localdRq8 = localdRq7;
    Jg localJg4 = localdRq8.getAppearance();
    localJg4.setElementMap(localcpa);
    localdRq7.bb(localJg4);
    localJg4.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(5, 5, 5, 5));
    localJg4.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg4.rV();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setAlign(ajb.dhZ);
    localcwP4.setSize(new Or(-2, -2));
    localdRq7.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    aId localaId2 = aId.checkOut();
    localaId2.setHorizontal(false);
    localdRq7.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setStyle("styledDark12");
    String str4 = "%guild.create%";
    str4 = str4.replace("%guild.create%", cBQ.cxL().mL("guild.create"));
    localcaF3.setText(str4);
    localcaF3.setNonBlocking(true);
    localdRq7.bb(localcaF3);
    localcaF3.brn();
    dpm localdpm3 = new dpm();
    localdpm3.aJ();
    localdpm3.setElementMap(localcpa);
    localdpm3.setAlign(aFG.eck);
    localcaF3.bb(localdpm3);
    localdpm3.brn();
    localdpm3.rV();
    localcaF3.rV();
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa);
    localdRq7.bb(localdRq9);
    localdRq9.brn();
    dpm localdpm4 = new dpm();
    localdpm4.aJ();
    localdpm4.setElementMap(localcpa);
    localdpm4.setAlign(aFG.eck);
    localdRq9.bb(localdpm4);
    localdpm4.brn();
    localdpm4.rV();
    czv localczv2 = new czv();
    localczv2.aJ();
    localczv2.setElementMap(localcpa);
    localczv2.setExpandable(false);
    localczv2.setNonBlocking(true);
    localczv2.setDisplaySize(new Or(16, 16));
    localdRq9.bb(localczv2);
    localczv2.brn();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv2.bb(localaAR);
    localaAR.brn();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa);
    localNK4.setName("guildCreation.itemDescription");
    localNK4.setAttribute("texture");
    localNK4.setField("iconUrl");
    localaAR.bb(localNK4);
    localNK4.brn();
    localNK4.rV();
    localaAR.rV();
    localczv2.rV();
    caF localcaF4 = new caF();
    localcaF4.aJ();
    localcaF4.setElementMap(localcpa);
    localcaF4.setStyle("styledDark12");
    localcaF4.setExpandable(false);
    localcaF4.setText("1x");
    localcaF4.setNonBlocking(true);
    localdRq9.bb(localcaF4);
    localcaF4.brn();
    localcaF4.rV();
    caF localcaF5 = new caF();
    localcaF5.aJ();
    localcaF5.setElementMap(localcpa);
    localcaF5.setStyle("styledDark12");
    localcaF5.setExpandable(false);
    localcaF5.setNonBlocking(true);
    localdRq9.bb(localcaF5);
    localcaF5.brn();
    NK localNK5 = NK.checkOut();
    localNK5.setElementMap(localcpa);
    localNK5.setName("guildCreation.itemDescription");
    localNK5.setAttribute("text");
    localNK5.setField("name");
    localcaF5.bb(localNK5);
    localNK5.brn();
    localNK5.rV();
    localcaF5.rV();
    localdRq9.rV();
    localdRq7.rV();
    localdRq6.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj f(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq = dRq.checkOut();
    localdRq.setElementMap(localcpa);
    parambdj.bb(localdRq);
    localdRq.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(100.0F, 100.0F));
    localdRq.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localdRq.rV();
    return localdRq;
  }

  public bdj g(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    biy localbiy = new biy();
    localbiy.aJ();
    localbiy.setElementMap(localcpa);
    localbiy.setStyle("close");
    localbiy.setExpandable(false);
    csA localcsA = new csA();
    localcsA.hg("wakfu.guildBannerCreator:closeDialog");
    localbiy.setOnClick(localcsA);
    parambdj.bb(localbiy);
    localbiy.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(-2, -2));
    localcwP.setAlign(ajb.dhV);
    localcwP.setXOffset(-18);
    localcwP.setYOffset(-12);
    localbiy.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localbiy.rV();
    return localbiy;
  }

  public bdj h(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setAlign(ajb.dhZ);
    localcwP.setYOffset(-100);
    parambdj.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    return localcwP;
  }
}