import java.awt.Insets;
import java.util.Stack;

public class aBI
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    bpn localbpn = new bpn();
    localbpn.aJ();
    localbpn.setElementMap(localcpa);
    localbpn.setPack(true);
    localbpn.brn();
    czO localczO1 = new czO();
    localczO1.aJ();
    localczO1.setAdaptToContentSize(true);
    localbpn.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localbpn.bb(localdRq1);
    localdRq1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    localdRq1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setStyle("windowNew");
    localbpn.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(10, 5, 12, 5));
    localJg1.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    localJg1.rV();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localdRq2.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localaId1.setAlign(aFG.ech);
    localdRq2.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dqa localdqa1 = new dqa();
    localdqa1.aJ();
    localdqa1.setElementMap(localcpa);
    localdqa1.setExpandable(false);
    localdRq2.bb(localdqa1);
    localdqa1.brn();
    dqa localdqa2 = localdqa1;
    Jg localJg2 = localdqa2.getAppearance();
    localJg2.setElementMap(localcpa);
    localdqa1.bb(localJg2);
    localJg2.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 10, 0, 10));
    localJg2.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg2.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setStyle("titleBar");
    localdqa1.bb(localdRq4);
    localdRq4.brn();
    dRq localdRq5 = localdRq4;
    Jg localJg3 = localdRq5.getAppearance();
    localJg3.setElementMap(localcpa);
    localdRq4.bb(localJg3);
    localJg3.brn();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(2, 20, 3, 20));
    localJg3.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    localJg3.rV();
    aId localaId2 = aId.checkOut();
    localaId2.setHorizontal(false);
    localdRq4.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq6.setExpandable(false);
    localdRq4.bb(localdRq6);
    localdRq6.brn();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa);
    localdpm1.setAlign(aFG.eck);
    localdRq6.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("StyledBold16White");
    localcaF1.setNonBlocking(true);
    String str1 = "%chat.contactList%";
    str1 = str1.replace("%chat.contactList%", cBQ.cxL().mL("chat.contactList"));
    localcaF1.setText(str1);
    localdRq6.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg4 = localcaF2.getAppearance();
    localJg4.setElementMap(localcpa);
    ((cwJ)localJg4).setAlignment(aFG.eck);
    localcaF1.bb(localJg4);
    localJg4.brn();
    localJg4.rV();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("text");
    localNK1.setName("collectMachine");
    localNK1.setField("name");
    localcaF1.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    localcaF1.rV();
    localdRq6.rV();
    localdRq4.rV();
    localdqa1.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localdRq2.bb(localdRq7);
    localdRq7.brn();
    dRq localdRq8 = localdRq7;
    Jg localJg5 = localdRq8.getAppearance();
    localJg5.setElementMap(localcpa);
    localdRq7.bb(localJg5);
    localJg5.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 12, 0, 12));
    localJg5.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg5.rV();
    String str2 = "windowContentContainer";
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localdRq9);
    localdRq7.bb(localdRq9);
    localdRq9.brn();
    dRq localdRq10 = dRq.checkOut();
    localdRq10.setElementMap(localcpa);
    localdRq9.bb(localdRq10);
    localdRq10.brn();
    aId localaId3 = aId.checkOut();
    localaId3.setAlign(aFG.ech);
    localaId3.setHorizontal(false);
    localdRq10.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    dRq localdRq11 = dRq.checkOut();
    localdRq11.setElementMap(localcpa);
    localdRq11.setExpandable(false);
    localdRq10.bb(localdRq11);
    localdRq11.brn();
    dRq localdRq12 = dRq.checkOut();
    localdRq12.setElementMap(localcpa);
    localdRq12.setExpandable(false);
    localdRq11.bb(localdRq12);
    localdRq12.brn();
    czO localczO2 = new czO();
    localczO2.aJ();
    localczO2.setAdaptToContentSize(true);
    localdRq12.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    dRq localdRq13 = dRq.checkOut();
    localdRq13.setElementMap(localcpa);
    localdRq12.bb(localdRq13);
    localdRq13.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setAlign(ajb.dhZ);
    localcwP3.setSize(new Or(100.0F, 100.0F));
    localdRq13.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    dRq localdRq14 = localdRq13;
    Jg localJg6 = localdRq14.getAppearance();
    localJg6.setElementMap(localcpa);
    localdRq13.bb(localJg6);
    localJg6.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 0, 0, 20));
    localJg6.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg6.rV();
    aId localaId4 = aId.checkOut();
    localaId4.setAlign(aFG.ech);
    localaId4.setHorizontal(false);
    localdRq13.bb(localaId4);
    localaId4.brn();
    localaId4.rV();
    dRq localdRq15 = dRq.checkOut();
    localdRq15.setElementMap(localcpa);
    localdRq15.setStyle("flat");
    localdRq15.setExpandable(false);
    localdRq13.bb(localdRq15);
    localdRq15.brn();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setStyle("bold");
    String str3 = "%inventory%";
    str3 = str3.replace("%inventory%", cBQ.cxL().mL("inventory"));
    localcaF3.setText(str3);
    localdRq15.bb(localcaF3);
    localcaF3.brn();
    caF localcaF4 = localcaF3;
    Jg localJg7 = localcaF4.getAppearance();
    localJg7.setElementMap(localcpa);
    ((cwJ)localJg7).setAlignment(aFG.eck);
    localcaF3.bb(localJg7);
    localJg7.brn();
    localJg7.rV();
    localcaF3.rV();
    localdRq15.rV();
    dRq localdRq16 = dRq.checkOut();
    localdRq16.setElementMap(localcpa);
    localdRq16.setStyle("white");
    localdRq13.bb(localdRq16);
    localdRq16.brn();
    dRq localdRq17 = localdRq16;
    Jg localJg8 = localdRq17.getAppearance();
    localJg8.setElementMap(localcpa);
    localJg8.setModulationColor(new bNa(0.73F, 0.77F, 0.79F, 1.0F));
    localdRq16.bb(localJg8);
    localJg8.brn();
    localJg8.rV();
    localdRq16.rV();
    localdRq13.rV();
    dRq localdRq18 = dRq.checkOut();
    localdRq18.setElementMap(localcpa);
    localdRq12.bb(localdRq18);
    localdRq18.brn();
    dRq localdRq19 = localdRq18;
    Jg localJg9 = localdRq19.getAppearance();
    localJg9.setElementMap(localcpa);
    localdRq18.bb(localJg9);
    localJg9.brn();
    cuR localcuR3 = new cuR();
    localcuR3.aJ();
    localcuR3.setElementMap(localcpa);
    localcuR3.setInsets(new Insets(22, 5, 0, 0));
    localJg9.bb(localcuR3);
    localcuR3.brn();
    localcuR3.rV();
    localJg9.rV();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setAlign(ajb.dhZ);
    localcwP4.setSize(new Or(100.0F, 100.0F));
    localdRq18.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    aId localaId5 = aId.checkOut();
    localaId5.setAlign(aFG.ech);
    localaId5.setHorizontal(false);
    localdRq18.bb(localaId5);
    localaId5.brn();
    localaId5.rV();
    dRq localdRq20 = dRq.checkOut();
    localdRq20.setElementMap(localcpa);
    localdRq20.setExpandable(false);
    localdRq18.bb(localdRq20);
    localdRq20.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("collectMachine");
    localNK2.setAttribute("visible");
    localNK2.setField("kama/maxQuantity");
    localdRq20.bb(localNK2);
    localNK2.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localNK2.bb(localanQ1);
    localanQ1.brn();
    dDu localdDu = new dDu();
    localdDu.aJ();
    localdDu.setElementMap(localcpa);
    localanQ1.bb(localdDu);
    localdDu.brn();
    bSP localbSP = new bSP();
    localbSP.aJ();
    localbSP.setElementMap(localcpa);
    localbSP.setValue("0");
    localdDu.bb(localbSP);
    localbSP.brn();
    localbSP.rV();
    localdDu.rV();
    localanQ1.rV();
    localNK2.rV();
    dRq localdRq21 = dRq.checkOut();
    localdRq21.setElementMap(localcpa);
    localdRq21.setExpandable(false);
    localdRq20.bb(localdRq21);
    localdRq21.brn();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa);
    localdpm2.setAlign(aFG.ecn);
    localdRq21.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    czO localczO3 = new czO();
    localczO3.aJ();
    localczO3.setAdaptToContentSize(true);
    localdRq21.bb(localczO3);
    localczO3.brn();
    localczO3.rV();
    dRq localdRq22 = dRq.checkOut();
    localdRq22.setElementMap(localcpa);
    localdRq22.setStyle("white");
    localdRq21.bb(localdRq22);
    localdRq22.brn();
    cwP localcwP5 = new cwP();
    localcwP5.aJ();
    localcwP5.setElementMap(localcpa);
    localcwP5.setAlign(ajb.dhZ);
    localcwP5.setSize(new Or(100.0F, 100.0F));
    localdRq22.bb(localcwP5);
    localcwP5.brn();
    localcwP5.rV();
    localdRq22.rV();
    dRq localdRq23 = dRq.checkOut();
    localdRq23.setElementMap(localcpa);
    localdRq21.bb(localdRq23);
    localdRq23.brn();
    dRq localdRq24 = localdRq23;
    Jg localJg10 = localdRq24.getAppearance();
    localJg10.setElementMap(localcpa);
    localdRq23.bb(localJg10);
    localJg10.brn();
    cuR localcuR4 = new cuR();
    localcuR4.aJ();
    localcuR4.setElementMap(localcpa);
    localcuR4.setInsets(new Insets(6, 5, 8, 10));
    localJg10.bb(localcuR4);
    localcuR4.brn();
    localcuR4.rV();
    localJg10.rV();
    cwP localcwP6 = new cwP();
    localcwP6.aJ();
    localcwP6.setElementMap(localcpa);
    localcwP6.setAlign(ajb.dhZ);
    localcwP6.setSize(new Or(100.0F, 100.0F));
    localdRq23.bb(localcwP6);
    localcwP6.brn();
    localcwP6.rV();
    aId localaId6 = aId.checkOut();
    localaId6.setAlign(aFG.ecj);
    localdRq23.bb(localaId6);
    localaId6.brn();
    localaId6.rV();
    dRq localdRq25 = dRq.checkOut();
    localdRq25.setElementMap(localcpa);
    localdRq25.setExpandable(false);
    localdRq23.bb(localdRq25);
    localdRq25.brn();
    aId localaId7 = aId.checkOut();
    localaId7.setAlign(aFG.ech);
    localaId7.setHorizontal(false);
    localdRq25.bb(localaId7);
    localaId7.brn();
    localaId7.rV();
    dRq localdRq26 = dRq.checkOut();
    localdRq26.setElementMap(localcpa);
    localdRq26.setExpandable(false);
    localdRq25.bb(localdRq26);
    localdRq26.brn();
    dpm localdpm3 = new dpm();
    localdpm3.aJ();
    localdpm3.setElementMap(localcpa);
    localdpm3.setAlign(aFG.eck);
    localdRq26.bb(localdpm3);
    localdpm3.brn();
    localdpm3.rV();
    czO localczO4 = new czO();
    localczO4.aJ();
    localczO4.setAdaptToContentSize(true);
    localdRq26.bb(localczO4);
    localczO4.brn();
    localczO4.rV();
    String str4 = "kama";
    avo localavo = new avo();
    localavo.aJ();
    localavo.setElementMap(localcpa);
    if ((localcpa != null) && (str4 != null))
      localcpa.a(str4, localavo);
    localdRq26.bb(localavo);
    localavo.brn();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setName("collectMachine");
    localNK3.setAttribute("value");
    localNK3.setField("kama");
    localavo.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    localavo.rV();
    String str5 = "kamaQuantityTextEditor";
    aTp localaTp1 = new aTp();
    localaTp1.aJ();
    localaTp1.setElementMap(localcpa);
    if ((localcpa != null) && (str5 != null))
      localcpa.a(str5, localaTp1);
    localaTp1.setPrefSize(new Or(50, 0));
    localaTp1.setAutoHorizontalScrolled(Boolean.valueOf(true));
    localaTp1.setRestrict("[0-9]");
    localaTp1.setMaxChars(10);
    dbp localdbp = new dbp();
    localdbp.hg("wakfu.collectMachine:keyType(kamaQuantityTextEditor,kama)");
    localaTp1.setOnKeyType(localdbp);
    localaTp1.setExpandable(false);
    localdRq26.bb(localaTp1);
    localaTp1.brn();
    cwP localcwP7 = new cwP();
    localcwP7.aJ();
    localcwP7.setElementMap(localcpa);
    localcwP7.setAlign(ajb.dhZ);
    localcwP7.setSize(new Or(100.0F, 100.0F));
    localaTp1.bb(localcwP7);
    localcwP7.brn();
    localcwP7.rV();
    aTp localaTp2 = localaTp1;
    Jg localJg11 = localaTp2.getAppearance();
    localJg11.setElementMap(localcpa);
    ((cwJ)localJg11).setAlignment(aFG.ecl);
    localaTp1.bb(localJg11);
    localJg11.brn();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa);
    localNK4.setName("collectMachine");
    localNK4.setAttribute("modulationColor");
    localNK4.setField("kama/editable");
    localJg11.bb(localNK4);
    localNK4.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localanQ2.setValue("0.7,0.7,0.7,1");
    localanQ2.setElseValue("1,1,1,1");
    localNK4.bb(localanQ2);
    localanQ2.brn();
    bqW localbqW = new bqW();
    localbqW.aJ();
    localbqW.setElementMap(localcpa);
    localanQ2.bb(localbqW);
    localbqW.brn();
    localbqW.rV();
    localanQ2.rV();
    localNK4.rV();
    localJg11.rV();
    NK localNK5 = NK.checkOut();
    localNK5.setElementMap(localcpa);
    localNK5.setName("collectMachine");
    localNK5.setAttribute("text");
    localNK5.setField("kama/currentPlayerQuantity");
    localaTp1.bb(localNK5);
    localNK5.brn();
    localNK5.rV();
    NK localNK6 = NK.checkOut();
    localNK6.setElementMap(localcpa);
    localNK6.setName("collectMachine");
    localNK6.setAttribute("editable");
    localNK6.setField("kama/editable");
    localaTp1.bb(localNK6);
    localNK6.brn();
    localNK6.rV();
    localaTp1.rV();
    dRq localdRq27 = dRq.checkOut();
    localdRq27.setElementMap(localcpa);
    localdRq27.setNonBlocking(false);
    localdRq26.bb(localdRq27);
    localdRq27.brn();
    a(localdRq27);
    b(localdRq27);
    localdRq27.rV();
    localdRq26.rV();
    d(localdRq25);
    localdRq25.rV();
    e(localdRq23);
    localdRq23.rV();
    localdRq21.rV();
    f(localdRq20);
    localdRq20.rV();
    g(localdRq18);
    localdRq18.rV();
    localdRq12.rV();
    i(localdRq11);
    localdRq11.rV();
    localdRq10.rV();
    localdRq9.rV();
    localdRq7.rV();
    localdRq2.rV();
    o(localbpn);
    p(localbpn);
    q(localbpn);
    localbpn.rV();
    return localbpn;
  }

  public bdj a(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setAlign(ajb.dhZ);
    localcwP.setSize(new Or(100.0F, 100.0F));
    parambdj.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    return localcwP;
  }

  public bdj b(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setName("collectMachine");
    localNK.setAttribute("visible");
    localNK.setField("kama/editable");
    parambdj.bb(localNK);
    localNK.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localNK.bb(localanQ);
    localanQ.brn();
    bqW localbqW = new bqW();
    localbqW.aJ();
    localbqW.setElementMap(localcpa);
    localanQ.bb(localbqW);
    localbqW.brn();
    localbqW.rV();
    localanQ.rV();
    localNK.rV();
    return localNK;
  }

  public bdj d(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    biy localbiy1 = new biy();
    localbiy1.aJ();
    localbiy1.setElementMap(localcpa);
    localbiy1.setStyle("YellowSmallBlue");
    String str = "%max%";
    str = str.replace("%max%", cBQ.cxL().mL("max"));
    localbiy1.setText(str);
    localbiy1.setExpandable(false);
    csA localcsA = new csA();
    localcsA.hg("wakfu.collectMachine:setContentToMax(kama)");
    localbiy1.setOnClick(localcsA);
    localbiy1.setPrefSize(new Or(0, 15));
    parambdj.bb(localbiy1);
    localbiy1.brn();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setAttribute("enabled");
    localNK.setName("collectMachine");
    localNK.setField("kama/canMax");
    localbiy1.bb(localNK);
    localNK.brn();
    localNK.rV();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.ecl);
    localbiy1.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    biy localbiy2 = localbiy1;
    Jg localJg = localbiy2.getAppearance();
    localJg.setElementMap(localcpa);
    localbiy1.bb(localJg);
    localJg.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(1, 0, 0, 0));
    localJg.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg.rV();
    localbiy1.rV();
    return localbiy1;
  }

  public bdj e(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    aId localaId1 = aId.checkOut();
    localaId1.setAlign(aFG.ech);
    localaId1.setHorizontal(false);
    localdRq1.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dRq localdRq2 = localdRq1;
    Jg localJg1 = localdRq2.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq1.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 5, 0, 0));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq3.setExpandable(false);
    localdRq1.bb(localdRq3);
    localdRq3.brn();
    aId localaId2 = aId.checkOut();
    localaId2.setAlign(aFG.ecj);
    localdRq3.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    dRq localdRq4 = localdRq3;
    Jg localJg2 = localdRq4.getAppearance();
    localJg2.setElementMap(localcpa);
    localdRq3.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(2, 0, 0, 0));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("bold");
    localcaF1.setText("/");
    localcaF1.setExpandable(false);
    localdRq3.bb(localcaF1);
    localcaF1.brn();
    localcaF1.rV();
    caF localcaF2 = new caF();
    localcaF2.aJ();
    localcaF2.setElementMap(localcpa);
    localcaF2.setStyle("bold");
    localcaF2.setExpandable(false);
    localcaF2.setPrefSize(new Or(75, 0));
    localdRq3.bb(localcaF2);
    localcaF2.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setName("collectMachine");
    localNK1.setAttribute("text");
    localNK1.setField("kama/totalPlayerQuantity");
    localcaF2.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    localcaF2.rV();
    localdRq3.rV();
    dRq localdRq5 = dRq.checkOut();
    localdRq5.setElementMap(localcpa);
    localdRq5.setExpandable(false);
    localdRq1.bb(localdRq5);
    localdRq5.brn();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.ecl);
    localdRq5.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    dRq localdRq6 = localdRq5;
    Jg localJg3 = localdRq6.getAppearance();
    localJg3.setElementMap(localcpa);
    localdRq5.bb(localJg3);
    localJg3.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(7, 0, 0, 0));
    localJg3.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg3.rV();
    czO localczO = new czO();
    localczO.aJ();
    localczO.setAdaptToContentSize(true);
    localdRq5.bb(localczO);
    localczO.brn();
    localczO.rV();
    biy localbiy1 = new biy();
    localbiy1.aJ();
    localbiy1.setElementMap(localcpa);
    localbiy1.setStyle("yellow");
    localbiy1.setExpandable(false);
    csA localcsA = new csA();
    localcsA.hg("wakfu.collectMachine:valid(kama)");
    localbiy1.setOnClick(localcsA);
    localdRq5.bb(localbiy1);
    localbiy1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setAlign(ajb.dhZ);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localbiy1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    biy localbiy2 = localbiy1;
    Jg localJg4 = localbiy2.getAppearance();
    localJg4.setElementMap(localcpa);
    localbiy1.bb(localJg4);
    localJg4.brn();
    cuR localcuR = new cuR();
    localcuR.aJ();
    localcuR.setElementMap(localcpa);
    localcuR.setInsets(new Insets(4, 3, 3, 4));
    localJg4.bb(localcuR);
    localcuR.brn();
    localcuR.rV();
    localJg4.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setAttribute("enabled");
    localNK2.setName("collectMachine");
    localNK2.setField("kama/valid");
    localbiy1.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localbiy1.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setStyle("apply");
    localczv1.setNonBlocking(true);
    localczv1.setDisplaySize(new Or(15, 15));
    localdRq5.bb(localczv1);
    localczv1.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.dhZ);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localczv1.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    czv localczv2 = localczv1;
    Jg localJg5 = localczv2.getAppearance();
    localJg5.setElementMap(localcpa);
    localczv1.bb(localJg5);
    localJg5.brn();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setAttribute("modulationColor");
    localNK3.setName("collectMachine");
    localNK3.setField("kama/valid");
    localJg5.bb(localNK3);
    localNK3.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localanQ.setValue("0.5,0.5,0.5,0.5");
    localanQ.setElseValue("1,1,1,1");
    localNK3.bb(localanQ);
    localanQ.brn();
    bqW localbqW = new bqW();
    localbqW.aJ();
    localbqW.setElementMap(localcpa);
    localanQ.bb(localbqW);
    localbqW.brn();
    localbqW.rV();
    localanQ.rV();
    localNK3.rV();
    localJg5.rV();
    localczv1.rV();
    localdRq5.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj f(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setStyle("CollectMachineLeftArrow");
    localczv.setExpandable(false);
    parambdj.bb(localczv);
    localczv.brn();
    localczv.rV();
    return localczv;
  }

  public bdj g(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    ccG localccG = new ccG();
    localccG.aJ();
    localccG.setElementMap(localcpa);
    localccG.setCellSize(new Or(200, 60));
    localccG.setExpandable(false);
    localccG.setHorizontal(false);
    localccG.setAutoIdealSize(true);
    localccG.setIdealSizeMaxColumns(1);
    localccG.setIdealSizeMinColumns(1);
    localccG.setSelectionTogglable(false);
    parambdj.bb(localccG);
    localccG.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setAlign(ajb.dhZ);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localccG.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setName("collectMachine");
    localNK.setAttribute("content");
    localNK.setField("content");
    localccG.bb(localNK);
    localNK.brn();
    localNK.rV();
    eR localeR = new eR();
    localeR.aJ();
    localeR.setElementMap(localcpa);
    localccG.bb(localeR);
    localeR.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localeR.bb(localanQ1);
    localanQ1.brn();
    bxx localbxx = new bxx();
    localbxx.aJ();
    localbxx.setElementMap(localcpa);
    localanQ1.bb(localbxx);
    localbxx.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localbxx.bb(localanE);
    localanE.brn();
    localanE.rV();
    localbxx.rV();
    localanQ1.rV();
    String str1 = "item";
    avo localavo = new avo();
    localavo.aJ();
    localavo.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localavo);
    localeR.bb(localavo);
    localavo.brn();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("value");
    localavo.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    localavo.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localeR.bb(localdRq1);
    localdRq1.brn();
    aId localaId1 = aId.checkOut();
    localaId1.setAlign(aFG.ecj);
    localdRq1.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setExpandable(false);
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    czO localczO1 = new czO();
    localczO1.aJ();
    localczO1.setAdaptToContentSize(true);
    localdRq2.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq3.setStyle("white");
    localdRq2.bb(localdRq3);
    localdRq3.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.dhZ);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localdRq3.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    localdRq3.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq2.bb(localdRq4);
    localdRq4.brn();
    dRq localdRq5 = localdRq4;
    Jg localJg1 = localdRq5.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq4.bb(localJg1);
    localJg1.brn();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(6, 5, 15, 10));
    localJg1.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    localJg1.rV();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setAlign(ajb.dhZ);
    localcwP3.setSize(new Or(100.0F, 100.0F));
    localdRq4.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    aId localaId2 = aId.checkOut();
    localaId2.setAlign(aFG.ecj);
    localdRq4.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq6.setExpandable(false);
    localdRq4.bb(localdRq6);
    localdRq6.brn();
    aId localaId3 = aId.checkOut();
    localaId3.setAlign(aFG.ech);
    localaId3.setHorizontal(false);
    localdRq6.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localdRq7.setExpandable(false);
    localdRq6.bb(localdRq7);
    localdRq7.brn();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa);
    localdpm1.setAlign(aFG.eck);
    localdRq7.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    czO localczO2 = new czO();
    localczO2.aJ();
    localczO2.setAdaptToContentSize(true);
    localdRq7.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    String str2 = "quantityTextEditor";
    aTp localaTp1 = new aTp();
    localaTp1.aJ();
    localaTp1.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localaTp1);
    localaTp1.setPrefSize(new Or(50, 0));
    localaTp1.setAutoHorizontalScrolled(Boolean.valueOf(true));
    localaTp1.setRestrict("[0-9]");
    localaTp1.setMaxChars(10);
    dbp localdbp = new dbp();
    localdbp.hg("wakfu.collectMachine:keyType(quantityTextEditor,item)");
    localaTp1.setOnKeyType(localdbp);
    localaTp1.setExpandable(false);
    localdRq7.bb(localaTp1);
    localaTp1.brn();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setAlign(ajb.dhZ);
    localcwP4.setSize(new Or(100.0F, 100.0F));
    localaTp1.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    aTp localaTp2 = localaTp1;
    Jg localJg2 = localaTp2.getAppearance();
    localJg2.setElementMap(localcpa);
    ((cwJ)localJg2).setAlignment(aFG.ecl);
    localaTp1.bb(localJg2);
    localJg2.brn();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("modulationColor");
    localaaE2.setField("editable");
    localJg2.bb(localaaE2);
    localaaE2.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localanQ2.setValue("0.7,0.7,0.7,1");
    localanQ2.setElseValue("1,1,1,1");
    localaaE2.bb(localanQ2);
    localanQ2.brn();
    bqW localbqW1 = new bqW();
    localbqW1.aJ();
    localbqW1.setElementMap(localcpa);
    localanQ2.bb(localbqW1);
    localbqW1.brn();
    localbqW1.rV();
    localanQ2.rV();
    localaaE2.rV();
    localJg2.rV();
    aaE localaaE3 = new aaE();
    localaaE3.aJ();
    localaaE3.setElementMap(localcpa);
    localaaE3.setAttribute("text");
    localaaE3.setField("currentPlayerQuantity");
    localaTp1.bb(localaaE3);
    localaaE3.brn();
    localaaE3.rV();
    aaE localaaE4 = new aaE();
    localaaE4.aJ();
    localaaE4.setElementMap(localcpa);
    localaaE4.setAttribute("editable");
    localaaE4.setField("editable");
    localaTp1.bb(localaaE4);
    localaaE4.brn();
    localaaE4.rV();
    localaTp1.rV();
    dRq localdRq8 = dRq.checkOut();
    localdRq8.setElementMap(localcpa);
    localdRq8.setNonBlocking(false);
    localdRq7.bb(localdRq8);
    localdRq8.brn();
    cwP localcwP5 = new cwP();
    localcwP5.aJ();
    localcwP5.setElementMap(localcpa);
    localcwP5.setAlign(ajb.dhZ);
    localcwP5.setSize(new Or(100.0F, 100.0F));
    localdRq8.bb(localcwP5);
    localcwP5.brn();
    localcwP5.rV();
    aaE localaaE5 = new aaE();
    localaaE5.aJ();
    localaaE5.setElementMap(localcpa);
    localaaE5.setAttribute("visible");
    localaaE5.setField("editable");
    localdRq8.bb(localaaE5);
    localaaE5.brn();
    anQ localanQ3 = new anQ();
    localanQ3.aJ();
    localanQ3.setElementMap(localcpa);
    localaaE5.bb(localanQ3);
    localanQ3.brn();
    bqW localbqW2 = new bqW();
    localbqW2.aJ();
    localbqW2.setElementMap(localcpa);
    localanQ3.bb(localbqW2);
    localbqW2.brn();
    localbqW2.rV();
    localanQ3.rV();
    localaaE5.rV();
    localdRq8.rV();
    localdRq7.rV();
    biy localbiy1 = new biy();
    localbiy1.aJ();
    localbiy1.setElementMap(localcpa);
    localbiy1.setStyle("YellowSmallBlue");
    String str3 = "%max%";
    str3 = str3.replace("%max%", cBQ.cxL().mL("max"));
    localbiy1.setText(str3);
    localbiy1.setExpandable(false);
    csA localcsA1 = new csA();
    localcsA1.hg("wakfu.collectMachine:setContentToMax(item)");
    localbiy1.setOnClick(localcsA1);
    localbiy1.setPrefSize(new Or(0, 15));
    localdRq6.bb(localbiy1);
    localbiy1.brn();
    aaE localaaE6 = new aaE();
    localaaE6.aJ();
    localaaE6.setElementMap(localcpa);
    localaaE6.setAttribute("enabled");
    localaaE6.setField("canMax");
    localbiy1.bb(localaaE6);
    localaaE6.brn();
    localaaE6.rV();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa);
    localdpm2.setAlign(aFG.ecl);
    localbiy1.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    biy localbiy2 = localbiy1;
    Jg localJg3 = localbiy2.getAppearance();
    localJg3.setElementMap(localcpa);
    localbiy1.bb(localJg3);
    localJg3.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(1, 0, 0, 0));
    localJg3.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg3.rV();
    localbiy1.rV();
    localdRq6.rV();
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa);
    localdRq9.setExpandable(false);
    localdRq4.bb(localdRq9);
    localdRq9.brn();
    aId localaId4 = aId.checkOut();
    localaId4.setAlign(aFG.ech);
    localaId4.setHorizontal(false);
    localdRq9.bb(localaId4);
    localaId4.brn();
    localaId4.rV();
    dRq localdRq10 = localdRq9;
    Jg localJg4 = localdRq10.getAppearance();
    localJg4.setElementMap(localcpa);
    localdRq9.bb(localJg4);
    localJg4.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 5, 0, 0));
    localJg4.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg4.rV();
    dRq localdRq11 = dRq.checkOut();
    localdRq11.setElementMap(localcpa);
    localdRq11.setExpandable(false);
    localdRq9.bb(localdRq11);
    localdRq11.brn();
    aId localaId5 = aId.checkOut();
    localaId5.setAlign(aFG.ecj);
    localdRq11.bb(localaId5);
    localaId5.brn();
    localaId5.rV();
    dRq localdRq12 = localdRq11;
    Jg localJg5 = localdRq12.getAppearance();
    localJg5.setElementMap(localcpa);
    localdRq11.bb(localJg5);
    localJg5.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(2, 0, 0, 0));
    localJg5.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg5.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("bold");
    localcaF1.setText("/");
    localcaF1.setExpandable(false);
    localdRq11.bb(localcaF1);
    localcaF1.brn();
    localcaF1.rV();
    caF localcaF2 = new caF();
    localcaF2.aJ();
    localcaF2.setElementMap(localcpa);
    localcaF2.setStyle("bold");
    localcaF2.setExpandable(false);
    localcaF2.setPrefSize(new Or(75, 0));
    localdRq11.bb(localcaF2);
    localcaF2.brn();
    aaE localaaE7 = new aaE();
    localaaE7.aJ();
    localaaE7.setElementMap(localcpa);
    localaaE7.setAttribute("text");
    localaaE7.setField("totalPlayerQuantity");
    localcaF2.bb(localaaE7);
    localaaE7.brn();
    localaaE7.rV();
    localcaF2.rV();
    localdRq11.rV();
    dRq localdRq13 = dRq.checkOut();
    localdRq13.setElementMap(localcpa);
    localdRq13.setExpandable(false);
    localdRq9.bb(localdRq13);
    localdRq13.brn();
    dpm localdpm3 = new dpm();
    localdpm3.aJ();
    localdpm3.setElementMap(localcpa);
    localdpm3.setAlign(aFG.ecl);
    localdRq13.bb(localdpm3);
    localdpm3.brn();
    localdpm3.rV();
    dRq localdRq14 = localdRq13;
    Jg localJg6 = localdRq14.getAppearance();
    localJg6.setElementMap(localcpa);
    localdRq13.bb(localJg6);
    localJg6.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(7, 0, 0, 0));
    localJg6.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg6.rV();
    czO localczO3 = new czO();
    localczO3.aJ();
    localczO3.setAdaptToContentSize(true);
    localdRq13.bb(localczO3);
    localczO3.brn();
    localczO3.rV();
    biy localbiy3 = new biy();
    localbiy3.aJ();
    localbiy3.setElementMap(localcpa);
    localbiy3.setStyle("yellow");
    localbiy3.setExpandable(false);
    csA localcsA2 = new csA();
    localcsA2.hg("wakfu.collectMachine:valid(item)");
    localbiy3.setOnClick(localcsA2);
    localdRq13.bb(localbiy3);
    localbiy3.brn();
    cwP localcwP6 = new cwP();
    localcwP6.aJ();
    localcwP6.setElementMap(localcpa);
    localcwP6.setAlign(ajb.dhZ);
    localcwP6.setSize(new Or(100.0F, 100.0F));
    localbiy3.bb(localcwP6);
    localcwP6.brn();
    localcwP6.rV();
    biy localbiy4 = localbiy3;
    Jg localJg7 = localbiy4.getAppearance();
    localJg7.setElementMap(localcpa);
    localbiy3.bb(localJg7);
    localJg7.brn();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(4, 3, 3, 4));
    localJg7.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    localJg7.rV();
    aaE localaaE8 = new aaE();
    localaaE8.aJ();
    localaaE8.setElementMap(localcpa);
    localaaE8.setAttribute("enabled");
    localaaE8.setField("valid");
    localbiy3.bb(localaaE8);
    localaaE8.brn();
    localaaE8.rV();
    localbiy3.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setStyle("apply");
    localczv1.setNonBlocking(true);
    localczv1.setDisplaySize(new Or(15, 15));
    localdRq13.bb(localczv1);
    localczv1.brn();
    cwP localcwP7 = new cwP();
    localcwP7.aJ();
    localcwP7.setElementMap(localcpa);
    localcwP7.setAlign(ajb.dhZ);
    localcwP7.setSize(new Or(100.0F, 100.0F));
    localczv1.bb(localcwP7);
    localcwP7.brn();
    localcwP7.rV();
    czv localczv2 = localczv1;
    Jg localJg8 = localczv2.getAppearance();
    localJg8.setElementMap(localcpa);
    localczv1.bb(localJg8);
    localJg8.brn();
    aaE localaaE9 = new aaE();
    localaaE9.aJ();
    localaaE9.setElementMap(localcpa);
    localaaE9.setAttribute("modulationColor");
    localaaE9.setField("valid");
    localJg8.bb(localaaE9);
    localaaE9.brn();
    anQ localanQ4 = new anQ();
    localanQ4.aJ();
    localanQ4.setElementMap(localcpa);
    localanQ4.setValue("0.5,0.5,0.5,0.5");
    localanQ4.setElseValue("1,1,1,1");
    localaaE9.bb(localanQ4);
    localanQ4.brn();
    bqW localbqW3 = new bqW();
    localbqW3.aJ();
    localbqW3.setElementMap(localcpa);
    localanQ4.bb(localbqW3);
    localbqW3.brn();
    localbqW3.rV();
    localanQ4.rV();
    localaaE9.rV();
    localJg8.rV();
    localczv1.rV();
    localdRq13.rV();
    localdRq9.rV();
    localdRq4.rV();
    localdRq2.rV();
    h(localdRq1);
    localdRq1.rV();
    localeR.rV();
    localccG.rV();
    return localccG;
  }

  public bdj h(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setStyle("CollectMachineLeftArrow");
    localczv.setExpandable(false);
    localczv.setPrefSize(new Or(40, 42));
    parambdj.bb(localczv);
    localczv.brn();
    localczv.rV();
    return localczv;
  }

  public bdj i(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    czO localczO1 = new czO();
    localczO1.aJ();
    localczO1.setAdaptToContentSize(true);
    localdRq1.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setAlign(ajb.dhZ);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localdRq2.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setAlign(aFG.ech);
    localaId1.setHorizontal(false);
    localdRq2.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq3.setStyle("flat");
    localdRq3.setExpandable(false);
    localdRq2.bb(localdRq3);
    localdRq3.brn();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("bold");
    String str1 = "%stock%";
    str1 = str1.replace("%stock%", cBQ.cxL().mL("stock"));
    localcaF1.setText(str1);
    localdRq3.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg1 = localcaF2.getAppearance();
    localJg1.setElementMap(localcpa);
    ((cwJ)localJg1).setAlignment(aFG.eck);
    localcaF1.bb(localJg1);
    localJg1.brn();
    localJg1.rV();
    localcaF1.rV();
    localdRq3.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setStyle("white");
    localdRq2.bb(localdRq4);
    localdRq4.brn();
    dRq localdRq5 = localdRq4;
    Jg localJg2 = localdRq5.getAppearance();
    localJg2.setElementMap(localcpa);
    localJg2.setModulationColor(new bNa(0.73F, 0.77F, 0.79F, 1.0F));
    localdRq4.bb(localJg2);
    localJg2.brn();
    localJg2.rV();
    localdRq4.rV();
    localdRq2.rV();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq1.bb(localdRq6);
    localdRq6.brn();
    dRq localdRq7 = localdRq6;
    Jg localJg3 = localdRq7.getAppearance();
    localJg3.setElementMap(localcpa);
    localdRq6.bb(localJg3);
    localJg3.brn();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(20, 5, 5, 5));
    localJg3.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    localJg3.rV();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.dhZ);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localdRq6.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    aId localaId2 = aId.checkOut();
    localaId2.setAlign(aFG.ech);
    localaId2.setHorizontal(false);
    localdRq6.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    dRq localdRq8 = dRq.checkOut();
    localdRq8.setElementMap(localcpa);
    localdRq8.setExpandable(false);
    localdRq6.bb(localdRq8);
    localdRq8.brn();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa);
    localdpm1.setAlign(aFG.ecj);
    localdRq8.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setName("collectMachine");
    localNK1.setAttribute("visible");
    localNK1.setField("kama/maxQuantity");
    localdRq8.bb(localNK1);
    localNK1.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localNK1.bb(localanQ);
    localanQ.brn();
    dDu localdDu = new dDu();
    localdDu.aJ();
    localdDu.setElementMap(localcpa);
    localanQ.bb(localdDu);
    localdDu.brn();
    bSP localbSP = new bSP();
    localbSP.aJ();
    localbSP.setElementMap(localcpa);
    localbSP.setValue("0");
    localdDu.bb(localbSP);
    localbSP.brn();
    localbSP.rV();
    localdDu.rV();
    localanQ.rV();
    localNK1.rV();
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa);
    localdRq9.setExpandable(false);
    localdRq8.bb(localdRq9);
    localdRq9.brn();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa);
    localdpm2.setAlign(aFG.ecn);
    localdRq9.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    dRq localdRq10 = localdRq9;
    Jg localJg4 = localdRq10.getAppearance();
    localJg4.setElementMap(localcpa);
    localdRq9.bb(localJg4);
    localJg4.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 0, 5, 0));
    localJg4.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg4.rV();
    dRq localdRq11 = dRq.checkOut();
    localdRq11.setElementMap(localcpa);
    localdRq9.bb(localdRq11);
    localdRq11.brn();
    String str2 = "item";
    avo localavo = new avo();
    localavo.aJ();
    localavo.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localavo);
    localdRq11.bb(localavo);
    localavo.brn();
    aaE localaaE = new aaE();
    localaaE.aJ();
    localaaE.setElementMap(localcpa);
    localaaE.setAttribute("value");
    localavo.bb(localaaE);
    localaaE.brn();
    localaaE.rV();
    localavo.rV();
    czO localczO2 = new czO();
    localczO2.aJ();
    localczO2.setAdaptToContentSize(true);
    localdRq11.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    dRq localdRq12 = dRq.checkOut();
    localdRq12.setElementMap(localcpa);
    localdRq12.setStyle("white");
    localdRq11.bb(localdRq12);
    localdRq12.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setAlign(ajb.dhZ);
    localcwP3.setSize(new Or(100.0F, 100.0F));
    localdRq12.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    dRq localdRq13 = localdRq12;
    Jg localJg5 = localdRq13.getAppearance();
    localJg5.setElementMap(localcpa);
    localdRq12.bb(localJg5);
    localJg5.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(2, 2, 2, 0));
    localJg5.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg5.rV();
    localdRq12.rV();
    dRq localdRq14 = dRq.checkOut();
    localdRq14.setElementMap(localcpa);
    localdRq14.setExpandable(false);
    localdRq11.bb(localdRq14);
    localdRq14.brn();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setAlign(ajb.dhZ);
    localcwP4.setSize(new Or(100.0F, 100.0F));
    localdRq14.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    aId localaId3 = aId.checkOut();
    localaId3.setAlign(aFG.ecj);
    localdRq14.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    dRq localdRq15 = dRq.checkOut();
    localdRq15.setElementMap(localcpa);
    localdRq15.setStyle("itemBackground");
    localdRq15.setExpandable(false);
    cCu localcCu = new cCu();
    localcCu.hg("popup(kamaPopup)");
    localdRq15.setOnPopupDisplay(localcCu);
    jL localjL = new jL();
    localjL.hg("closePopup");
    localdRq15.setOnPopupHide(localjL);
    localdRq15.setNonBlocking(false);
    localdRq14.bb(localdRq15);
    localdRq15.brn();
    String str3 = "kamaPopup";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa);
    if ((localcpa != null) && (str3 != null))
      localcpa.a(str3, localanG);
    localanG.setAlign(aFG.ech);
    localanG.setHotSpotPosition(aFG.ecn);
    localdRq15.bb(localanG);
    localanG.brn();
    dRq localdRq16 = dRq.checkOut();
    localdRq16.setElementMap(localcpa);
    localdRq16.setStyle("popup");
    localanG.bb(localdRq16);
    localdRq16.brn();
    cba localcba = cba.checkOut();
    localcba.setElementMap(localcpa);
    localcba.setData(cFu.izR);
    localdRq16.bb(localcba);
    localcba.brn();
    localcba.rV();
    aId localaId4 = aId.checkOut();
    localaId4.setHorizontal(false);
    localdRq16.bb(localaId4);
    localaId4.brn();
    localaId4.rV();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setStyle("whiteBold");
    localcaF3.setExpandable(false);
    String str4 = "%kamas%";
    str4 = str4.replace("%kamas%", cBQ.cxL().mL("kamas"));
    localcaF3.setText(str4);
    localdRq16.bb(localcaF3);
    localcaF3.brn();
    caF localcaF4 = localcaF3;
    Jg localJg6 = localcaF4.getAppearance();
    localJg6.setElementMap(localcpa);
    ((cwJ)localJg6).setAlignment(aFG.ecj);
    localcaF3.bb(localJg6);
    localJg6.brn();
    localJg6.rV();
    localcaF3.rV();
    localdRq16.rV();
    localanG.rV();
    czO localczO3 = new czO();
    localczO3.aJ();
    localczO3.setAdaptToContentSize(true);
    localdRq15.bb(localczO3);
    localczO3.brn();
    localczO3.rV();
    dRq localdRq17 = localdRq15;
    Jg localJg7 = localdRq17.getAppearance();
    localJg7.setElementMap(localcpa);
    localdRq15.bb(localJg7);
    localJg7.brn();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(5, 5, 5, 5));
    localJg7.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    localJg7.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setNonBlocking(true);
    localczv1.setDisplaySize(new Or(38, 38));
    localczv1.setStyle("coins");
    localdRq15.bb(localczv1);
    localczv1.brn();
    cwP localcwP5 = new cwP();
    localcwP5.aJ();
    localcwP5.setElementMap(localcpa);
    localcwP5.setAlign(ajb.dhZ);
    localczv1.bb(localcwP5);
    localcwP5.brn();
    localcwP5.rV();
    localczv1.rV();
    localdRq15.rV();
    dRq localdRq18 = dRq.checkOut();
    localdRq18.setElementMap(localcpa);
    localdRq18.setExpandable(false);
    localdRq18.setPrefSize(new Or(142, 0));
    localdRq14.bb(localdRq18);
    localdRq18.brn();
    aId localaId5 = aId.checkOut();
    localaId5.setAlign(aFG.eck);
    localaId5.setHorizontal(false);
    localdRq18.bb(localaId5);
    localaId5.brn();
    localaId5.rV();
    dRq localdRq19 = localdRq18;
    Jg localJg8 = localdRq19.getAppearance();
    localJg8.setElementMap(localcpa);
    localdRq18.bb(localJg8);
    localJg8.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 5, 0, 5));
    localJg8.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg8.rV();
    dRq localdRq20 = dRq.checkOut();
    localdRq20.setElementMap(localcpa);
    localdRq20.setExpandable(false);
    localdRq18.bb(localdRq20);
    localdRq20.brn();
    aId localaId6 = aId.checkOut();
    localaId6.setAlign(aFG.eck);
    localdRq20.bb(localaId6);
    localaId6.brn();
    localaId6.rV();
    caF localcaF5 = new caF();
    localcaF5.aJ();
    localcaF5.setElementMap(localcpa);
    localcaF5.setStyle("bold");
    localcaF5.setExpandable(false);
    localdRq20.bb(localcaF5);
    localcaF5.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("collectMachine");
    localNK2.setAttribute("text");
    localNK2.setField("kama/quantity");
    localcaF5.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localcaF5.rV();
    caF localcaF6 = new caF();
    localcaF6.aJ();
    localcaF6.setElementMap(localcpa);
    localcaF6.setStyle("bold");
    localcaF6.setExpandable(false);
    localcaF6.setText("/");
    localdRq20.bb(localcaF6);
    localcaF6.brn();
    localcaF6.rV();
    caF localcaF7 = new caF();
    localcaF7.aJ();
    localcaF7.setElementMap(localcpa);
    localcaF7.setStyle("bold");
    localcaF7.setExpandable(false);
    localdRq20.bb(localcaF7);
    localcaF7.brn();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setName("collectMachine");
    localNK3.setAttribute("text");
    localNK3.setField("kama/maxQuantity");
    localcaF7.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    localcaF7.rV();
    czv localczv2 = new czv();
    localczv2.aJ();
    localczv2.setElementMap(localcpa);
    localczv2.setStyle("kamas");
    localczv2.setExpandable(false);
    localdRq20.bb(localczv2);
    localczv2.brn();
    czv localczv3 = localczv2;
    Jg localJg9 = localczv3.getAppearance();
    localJg9.setElementMap(localcpa);
    localczv2.bb(localJg9);
    localJg9.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(0, 2, 0, 0));
    localJg9.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg9.rV();
    localczv2.rV();
    localdRq20.rV();
    dRq localdRq21 = dRq.checkOut();
    localdRq21.setElementMap(localcpa);
    localdRq21.setExpandable(false);
    localdRq18.bb(localdRq21);
    localdRq21.brn();
    czO localczO4 = new czO();
    localczO4.aJ();
    localczO4.setAdaptToContentSize(true);
    localdRq21.bb(localczO4);
    localczO4.brn();
    localczO4.rV();
    dRq localdRq22 = localdRq21;
    Jg localJg10 = localdRq22.getAppearance();
    localJg10.setElementMap(localcpa);
    localdRq21.bb(localJg10);
    localJg10.brn();
    bmv localbmv5 = bmv.checkOut();
    localbmv5.setElementMap(localcpa);
    localbmv5.setInsets(new Insets(2, 0, 3, 0));
    localJg10.bb(localbmv5);
    localbmv5.brn();
    localbmv5.rV();
    localJg10.rV();
    alP localalP1 = new alP();
    localalP1.aJ();
    localalP1.setElementMap(localcpa);
    localalP1.setUseDecreaseProgressTween(false);
    localalP1.setStyle("XP2");
    localalP1.setNonBlocking(false);
    localalP1.setTweenDuration(1000L);
    localdRq21.bb(localalP1);
    localalP1.brn();
    cwP localcwP6 = new cwP();
    localcwP6.aJ();
    localcwP6.setElementMap(localcpa);
    localcwP6.setSize(new Or(100.0F, 10));
    localcwP6.setAlign(ajb.dhZ);
    localalP1.bb(localcwP6);
    localcwP6.brn();
    localcwP6.rV();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa);
    localNK4.setName("collectMachine");
    localNK4.setAttribute("value");
    localNK4.setField("kama/quantityRatio");
    localalP1.bb(localNK4);
    localNK4.brn();
    localNK4.rV();
    alP localalP2 = localalP1;
    Jg localJg11 = localalP2.getAppearance();
    localJg11.setElementMap(localcpa);
    localalP1.bb(localJg11);
    localJg11.brn();
    cuR localcuR3 = new cuR();
    localcuR3.aJ();
    localcuR3.setElementMap(localcpa);
    localcuR3.setInsets(new Insets(0, 2, 0, 1));
    localJg11.bb(localcuR3);
    localcuR3.brn();
    localcuR3.rV();
    jO localjO = new jO();
    localjO.aJ();
    localjO.setElementMap(localcpa);
    localjO.setColor(new bNa(0.72F, 0.75F, 0.79F, 1.0F));
    localJg11.bb(localjO);
    localjO.brn();
    localjO.rV();
    localJg11.rV();
    localalP1.rV();
    dRq localdRq23 = dRq.checkOut();
    localdRq23.setElementMap(localcpa);
    localdRq23.setStyle("ProgressBar");
    localdRq23.setPrefSize(new Or(0, 11));
    localdRq21.bb(localdRq23);
    localdRq23.brn();
    cwP localcwP7 = new cwP();
    localcwP7.aJ();
    localcwP7.setElementMap(localcpa);
    localcwP7.setSize(new Or(100.0F, 11));
    localcwP7.setAlign(ajb.dhZ);
    localdRq23.bb(localcwP7);
    localcwP7.brn();
    localcwP7.rV();
    localdRq23.rV();
    localdRq21.rV();
    localdRq18.rV();
    j(localdRq14);
    localdRq14.rV();
    localdRq11.rV();
    localdRq9.rV();
    localdRq8.rV();
    k(localdRq6);
    localdRq6.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj j(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setStyle("itemBackground");
    localdRq1.setExpandable(false);
    localdRq1.setNonBlocking(false);
    cCu localcCu = new cCu();
    localcCu.hg("popup(citizenPopup)");
    localdRq1.setOnPopupDisplay(localcCu);
    jL localjL = new jL();
    localjL.hg("closePopup");
    localdRq1.setOnPopupHide(localjL);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setName("collectMachine");
    localNK1.setField("kama/citizenPoints");
    localNK1.setAttribute("visible");
    localdRq1.bb(localNK1);
    localNK1.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localNK1.bb(localanQ);
    localanQ.brn();
    aEJ localaEJ = new aEJ();
    localaEJ.aJ();
    localaEJ.setElementMap(localcpa);
    localaEJ.setValue("0");
    localanQ.bb(localaEJ);
    localaEJ.brn();
    localaEJ.rV();
    localanQ.rV();
    localNK1.rV();
    String str = "citizenPopup";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa);
    if ((localcpa != null) && (str != null))
      localcpa.a(str, localanG);
    localanG.setAlign(aFG.ech);
    localanG.setHotSpotPosition(aFG.ecn);
    localdRq1.bb(localanG);
    localanG.brn();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setStyle("popup");
    localanG.bb(localdRq2);
    localdRq2.brn();
    cba localcba = cba.checkOut();
    localcba.setElementMap(localcpa);
    localcba.setData(cFu.izR);
    localdRq2.bb(localcba);
    localcba.brn();
    localcba.rV();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(false);
    localdRq2.bb(localaId);
    localaId.brn();
    localaId.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("whiteBold");
    localcaF1.setExpandable(false);
    localdRq2.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg1 = localcaF2.getAppearance();
    localJg1.setElementMap(localcpa);
    ((cwJ)localJg1).setAlignment(aFG.ecj);
    localcaF1.bb(localJg1);
    localJg1.brn();
    localJg1.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("collectMachine");
    localNK2.setAttribute("text");
    localNK2.setField("kama/citizenPointsText");
    localcaF1.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localcaF1.rV();
    localdRq2.rV();
    localanG.rV();
    dRq localdRq3 = localdRq1;
    Jg localJg2 = localdRq3.getAppearance();
    localJg2.setElementMap(localcpa);
    localdRq1.bb(localJg2);
    localJg2.brn();
    cuR localcuR = new cuR();
    localcuR.aJ();
    localcuR.setElementMap(localcpa);
    localcuR.setInsets(new Insets(5, 5, 5, 5));
    localJg2.bb(localcuR);
    localcuR.brn();
    localcuR.rV();
    localJg2.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setStyle("LawLaurel");
    localczv1.setNonBlocking(true);
    localczv1.setDisplaySize(new Or(38, 38));
    localdRq1.bb(localczv1);
    localczv1.brn();
    czv localczv2 = localczv1;
    Jg localJg3 = localczv2.getAppearance();
    localJg3.setElementMap(localcpa);
    localJg3.setModulationColor(new bNa(0.82F, 0.98F, 0.32F, 1.0F));
    localczv1.bb(localJg3);
    localJg3.brn();
    localJg3.rV();
    localczv1.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj k(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    at localat = new at();
    localat.aJ();
    localat.setElementMap(localcpa);
    localat.setExpandable(false);
    localat.setHorizontal(false);
    parambdj.bb(localat);
    localat.brn();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.ecj);
    localat.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setName("collectMachine");
    localNK.setAttribute("content");
    localNK.setField("content");
    localat.bb(localNK);
    localNK.brn();
    localNK.rV();
    eR localeR = new eR();
    localeR.aJ();
    localeR.setElementMap(localcpa);
    localat.bb(localeR);
    localeR.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localeR.bb(localanQ1);
    localanQ1.brn();
    bxx localbxx = new bxx();
    localbxx.aJ();
    localbxx.setElementMap(localcpa);
    localanQ1.bb(localbxx);
    localbxx.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localbxx.bb(localanE);
    localanE.brn();
    localanE.rV();
    localbxx.rV();
    localanQ1.rV();
    String str1 = "currentItem";
    avo localavo1 = new avo();
    localavo1.aJ();
    localavo1.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localavo1);
    localeR.bb(localavo1);
    localavo1.brn();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("value");
    localavo1.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    localavo1.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localeR.bb(localdRq1);
    localdRq1.brn();
    aId localaId1 = aId.checkOut();
    localaId1.setAlign(aFG.ecj);
    localdRq1.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setExpandable(false);
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(5, 0, 7, 0));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq2.bb(localdRq4);
    localdRq4.brn();
    String str2 = "item";
    avo localavo2 = new avo();
    localavo2.aJ();
    localavo2.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localavo2);
    localdRq4.bb(localavo2);
    localavo2.brn();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("value");
    localavo2.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    localavo2.rV();
    czO localczO1 = new czO();
    localczO1.aJ();
    localczO1.setAdaptToContentSize(true);
    localdRq4.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    dRq localdRq5 = dRq.checkOut();
    localdRq5.setElementMap(localcpa);
    localdRq5.setStyle("white");
    localdRq4.bb(localdRq5);
    localdRq5.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setAlign(ajb.dhZ);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localdRq5.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    dRq localdRq6 = localdRq5;
    Jg localJg2 = localdRq6.getAppearance();
    localJg2.setElementMap(localcpa);
    localdRq5.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(2, 2, 2, 0));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    localdRq5.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localdRq7.setExpandable(false);
    localdRq4.bb(localdRq7);
    localdRq7.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.dhZ);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localdRq7.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    aId localaId2 = aId.checkOut();
    localaId2.setAlign(aFG.ecj);
    localdRq7.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    dRq localdRq8 = dRq.checkOut();
    localdRq8.setElementMap(localcpa);
    localdRq8.setStyle("itemBackground");
    localdRq8.setExpandable(false);
    localdRq8.setNonBlocking(false);
    cCu localcCu1 = new cCu();
    localcCu1.hg("popup(itemPopup)");
    localdRq8.setOnPopupDisplay(localcCu1);
    jL localjL1 = new jL();
    localjL1.hg("closePopup");
    localdRq8.setOnPopupHide(localjL1);
    localdRq7.bb(localdRq8);
    localdRq8.brn();
    String str3 = "itemPopup";
    anG localanG1 = new anG();
    localanG1.aJ();
    localanG1.setElementMap(localcpa);
    if ((localcpa != null) && (str3 != null))
      localcpa.a(str3, localanG1);
    localanG1.setAlign(aFG.ech);
    localanG1.setHotSpotPosition(aFG.ecn);
    localdRq8.bb(localanG1);
    localanG1.brn();
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa);
    localdRq9.setStyle("popup");
    localanG1.bb(localdRq9);
    localdRq9.brn();
    cba localcba1 = cba.checkOut();
    localcba1.setElementMap(localcpa);
    localcba1.setData(cFu.izR);
    localdRq9.bb(localcba1);
    localcba1.brn();
    localcba1.rV();
    aId localaId3 = aId.checkOut();
    localaId3.setHorizontal(false);
    localdRq9.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("whiteBold");
    localcaF1.setExpandable(false);
    localdRq9.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg3 = localcaF2.getAppearance();
    localJg3.setElementMap(localcpa);
    ((cwJ)localJg3).setAlignment(aFG.ecj);
    localcaF1.bb(localJg3);
    localJg3.brn();
    localJg3.rV();
    aaE localaaE3 = new aaE();
    localaaE3.aJ();
    localaaE3.setElementMap(localcpa);
    localaaE3.setAttribute("text");
    localaaE3.setField("name");
    localcaF1.bb(localaaE3);
    localaaE3.brn();
    localaaE3.rV();
    localcaF1.rV();
    localdRq9.rV();
    localanG1.rV();
    czO localczO2 = new czO();
    localczO2.aJ();
    localczO2.setAdaptToContentSize(true);
    localdRq8.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    dRq localdRq10 = localdRq8;
    Jg localJg4 = localdRq10.getAppearance();
    localJg4.setElementMap(localcpa);
    localdRq8.bb(localJg4);
    localJg4.brn();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(5, 5, 5, 5));
    localJg4.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    localJg4.rV();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setNonBlocking(true);
    localczv.setDisplaySize(new Or(38, 38));
    localdRq8.bb(localczv);
    localczv.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setAlign(ajb.dhZ);
    localczv.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv.bb(localaAR);
    localaAR.brn();
    aaE localaaE4 = new aaE();
    localaaE4.aJ();
    localaaE4.setElementMap(localcpa);
    localaaE4.setAttribute("texture");
    localaaE4.setField("iconUrl");
    localaAR.bb(localaaE4);
    localaaE4.brn();
    localaaE4.rV();
    localaAR.rV();
    localczv.rV();
    localdRq8.rV();
    dRq localdRq11 = dRq.checkOut();
    localdRq11.setElementMap(localcpa);
    localdRq11.setExpandable(false);
    localdRq11.setPrefSize(new Or(142, 0));
    localdRq7.bb(localdRq11);
    localdRq11.brn();
    aId localaId4 = aId.checkOut();
    localaId4.setAlign(aFG.eck);
    localaId4.setHorizontal(false);
    localdRq11.bb(localaId4);
    localaId4.brn();
    localaId4.rV();
    dRq localdRq12 = localdRq11;
    Jg localJg5 = localdRq12.getAppearance();
    localJg5.setElementMap(localcpa);
    localdRq11.bb(localJg5);
    localJg5.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 5, 0, 5));
    localJg5.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg5.rV();
    dRq localdRq13 = dRq.checkOut();
    localdRq13.setElementMap(localcpa);
    localdRq13.setExpandable(false);
    localdRq11.bb(localdRq13);
    localdRq13.brn();
    aId localaId5 = aId.checkOut();
    localaId5.setAlign(aFG.eck);
    localdRq13.bb(localaId5);
    localaId5.brn();
    localaId5.rV();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setStyle("bold");
    localcaF3.setExpandable(false);
    localdRq13.bb(localcaF3);
    localcaF3.brn();
    aaE localaaE5 = new aaE();
    localaaE5.aJ();
    localaaE5.setElementMap(localcpa);
    localaaE5.setAttribute("text");
    localaaE5.setField("quantity");
    localcaF3.bb(localaaE5);
    localaaE5.brn();
    localaaE5.rV();
    localcaF3.rV();
    caF localcaF4 = new caF();
    localcaF4.aJ();
    localcaF4.setElementMap(localcpa);
    localcaF4.setStyle("bold");
    localcaF4.setExpandable(false);
    localcaF4.setText("/");
    localdRq13.bb(localcaF4);
    localcaF4.brn();
    localcaF4.rV();
    caF localcaF5 = new caF();
    localcaF5.aJ();
    localcaF5.setElementMap(localcpa);
    localcaF5.setStyle("bold");
    localcaF5.setExpandable(false);
    localdRq13.bb(localcaF5);
    localcaF5.brn();
    aaE localaaE6 = new aaE();
    localaaE6.aJ();
    localaaE6.setElementMap(localcpa);
    localaaE6.setAttribute("text");
    localaaE6.setField("maxQuantity");
    localcaF5.bb(localaaE6);
    localaaE6.brn();
    localaaE6.rV();
    localcaF5.rV();
    localdRq13.rV();
    dRq localdRq14 = dRq.checkOut();
    localdRq14.setElementMap(localcpa);
    localdRq14.setExpandable(false);
    localdRq11.bb(localdRq14);
    localdRq14.brn();
    czO localczO3 = new czO();
    localczO3.aJ();
    localczO3.setAdaptToContentSize(true);
    localdRq14.bb(localczO3);
    localczO3.brn();
    localczO3.rV();
    dRq localdRq15 = localdRq14;
    Jg localJg6 = localdRq15.getAppearance();
    localJg6.setElementMap(localcpa);
    localdRq14.bb(localJg6);
    localJg6.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(2, 0, 3, 0));
    localJg6.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg6.rV();
    alP localalP1 = new alP();
    localalP1.aJ();
    localalP1.setElementMap(localcpa);
    localalP1.setUseDecreaseProgressTween(false);
    localalP1.setStyle("XP2");
    localalP1.setNonBlocking(false);
    localalP1.setTweenDuration(1000L);
    localdRq14.bb(localalP1);
    localalP1.brn();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setSize(new Or(100.0F, 10));
    localcwP4.setAlign(ajb.dhZ);
    localalP1.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    aaE localaaE7 = new aaE();
    localaaE7.aJ();
    localaaE7.setElementMap(localcpa);
    localaaE7.setAttribute("value");
    localaaE7.setField("quantityRatio");
    localalP1.bb(localaaE7);
    localaaE7.brn();
    localaaE7.rV();
    alP localalP2 = localalP1;
    Jg localJg7 = localalP2.getAppearance();
    localJg7.setElementMap(localcpa);
    localalP1.bb(localJg7);
    localJg7.brn();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(0, 2, 0, 1));
    localJg7.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    jO localjO = new jO();
    localjO.aJ();
    localjO.setElementMap(localcpa);
    localjO.setColor(new bNa(0.72F, 0.75F, 0.79F, 1.0F));
    localJg7.bb(localjO);
    localjO.brn();
    localjO.rV();
    localJg7.rV();
    localalP1.rV();
    dRq localdRq16 = dRq.checkOut();
    localdRq16.setElementMap(localcpa);
    localdRq16.setStyle("ProgressBar");
    localdRq16.setPrefSize(new Or(0, 11));
    localdRq14.bb(localdRq16);
    localdRq16.brn();
    cwP localcwP5 = new cwP();
    localcwP5.aJ();
    localcwP5.setElementMap(localcpa);
    localcwP5.setSize(new Or(100.0F, 11));
    localcwP5.setAlign(ajb.dhZ);
    localdRq16.bb(localcwP5);
    localcwP5.brn();
    localcwP5.rV();
    localdRq16.rV();
    localdRq14.rV();
    localdRq11.rV();
    dRq localdRq17 = dRq.checkOut();
    localdRq17.setElementMap(localcpa);
    localdRq17.setStyle("itemBackground");
    localdRq17.setExpandable(false);
    localdRq17.setNonBlocking(false);
    cCu localcCu2 = new cCu();
    localcCu2.hg("popup(citizenPopup)");
    localdRq17.setOnPopupDisplay(localcCu2);
    jL localjL2 = new jL();
    localjL2.hg("closePopup");
    localdRq17.setOnPopupHide(localjL2);
    localdRq7.bb(localdRq17);
    localdRq17.brn();
    aaE localaaE8 = new aaE();
    localaaE8.aJ();
    localaaE8.setElementMap(localcpa);
    localaaE8.setAttribute("visible");
    localaaE8.setField("citizenPoints");
    localdRq17.bb(localaaE8);
    localaaE8.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localaaE8.bb(localanQ2);
    localanQ2.brn();
    aEJ localaEJ = new aEJ();
    localaEJ.aJ();
    localaEJ.setElementMap(localcpa);
    localaEJ.setValue("0");
    localanQ2.bb(localaEJ);
    localaEJ.brn();
    localaEJ.rV();
    localanQ2.rV();
    localaaE8.rV();
    String str4 = "citizenPopup";
    anG localanG2 = new anG();
    localanG2.aJ();
    localanG2.setElementMap(localcpa);
    if ((localcpa != null) && (str4 != null))
      localcpa.a(str4, localanG2);
    localanG2.setAlign(aFG.ech);
    localanG2.setHotSpotPosition(aFG.ecn);
    localdRq17.bb(localanG2);
    localanG2.brn();
    dRq localdRq18 = dRq.checkOut();
    localdRq18.setElementMap(localcpa);
    localdRq18.setStyle("popup");
    localanG2.bb(localdRq18);
    localdRq18.brn();
    cba localcba2 = cba.checkOut();
    localcba2.setElementMap(localcpa);
    localcba2.setData(cFu.izR);
    localdRq18.bb(localcba2);
    localcba2.brn();
    localcba2.rV();
    aId localaId6 = aId.checkOut();
    localaId6.setHorizontal(false);
    localdRq18.bb(localaId6);
    localaId6.brn();
    localaId6.rV();
    caF localcaF6 = new caF();
    localcaF6.aJ();
    localcaF6.setElementMap(localcpa);
    localcaF6.setStyle("whiteBold");
    localcaF6.setExpandable(false);
    localdRq18.bb(localcaF6);
    localcaF6.brn();
    caF localcaF7 = localcaF6;
    Jg localJg8 = localcaF7.getAppearance();
    localJg8.setElementMap(localcpa);
    ((cwJ)localJg8).setAlignment(aFG.ecj);
    localcaF6.bb(localJg8);
    localJg8.brn();
    localJg8.rV();
    l(localcaF6);
    localcaF6.rV();
    localdRq18.rV();
    localanG2.rV();
    m(localdRq17);
    n(localdRq17);
    localdRq17.rV();
    localdRq7.rV();
    localdRq4.rV();
    localdRq2.rV();
    localdRq1.rV();
    localeR.rV();
    localat.rV();
    return localat;
  }

  public bdj l(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    aaE localaaE = new aaE();
    localaaE.aJ();
    localaaE.setElementMap(localcpa);
    localaaE.setAttribute("text");
    localaaE.setField("citizenPointsText");
    parambdj.bb(localaaE);
    localaaE.brn();
    localaaE.rV();
    return localaaE;
  }

  public bdj m(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dOc localdOc = (dOc)parambdj;
    Jg localJg = localdOc.getAppearance();
    localJg.setElementMap(localcpa);
    parambdj.bb(localJg);
    localJg.brn();
    cuR localcuR = new cuR();
    localcuR.aJ();
    localcuR.setElementMap(localcpa);
    localcuR.setInsets(new Insets(5, 5, 5, 5));
    localJg.bb(localcuR);
    localcuR.brn();
    localcuR.rV();
    localJg.rV();
    return localJg;
  }

  public bdj n(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setStyle("LawLaurel");
    localczv1.setNonBlocking(true);
    localczv1.setDisplaySize(new Or(38, 38));
    parambdj.bb(localczv1);
    localczv1.brn();
    czv localczv2 = localczv1;
    Jg localJg = localczv2.getAppearance();
    localJg.setElementMap(localcpa);
    localJg.setModulationColor(new bNa(0.82F, 0.98F, 0.32F, 1.0F));
    localczv1.bb(localJg);
    localJg.brn();
    localJg.rV();
    localczv1.rV();
    return localczv1;
  }

  public bdj o(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq = dRq.checkOut();
    localdRq.setElementMap(localcpa);
    parambdj.bb(localdRq);
    localdRq.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(100.0F, 100.0F));
    localdRq.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localdRq.rV();
    return localdRq;
  }

  public bdj p(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    biy localbiy = new biy();
    localbiy.aJ();
    localbiy.setElementMap(localcpa);
    localbiy.setStyle("close");
    localbiy.setExpandable(false);
    csA localcsA = new csA();
    localcsA.hg("unloadDialog");
    localbiy.setOnClick(localcsA);
    parambdj.bb(localbiy);
    localbiy.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(-2, -2));
    localcwP.setAlign(ajb.dhV);
    localcwP.setXOffset(-18);
    localcwP.setYOffset(-12);
    localbiy.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localbiy.rV();
    return localbiy;
  }

  public bdj q(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(-2, -2));
    localcwP.setAlign(ajb.dhY);
    localcwP.setResizeOnce(true);
    parambdj.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    return localcwP;
  }
}