import java.awt.Insets;
import java.util.Stack;

public class dj
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    bpn localbpn = new bpn();
    localbpn.aJ();
    localbpn.setElementMap(localcpa);
    localbpn.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(-2, -2));
    localcwP1.setAlign(ajb.dhY);
    localcwP1.setInitValue(true);
    localbpn.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    czO localczO1 = new czO();
    localczO1.aJ();
    localczO1.setAdaptToContentSize(true);
    localbpn.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setStyle("tiledScroll");
    localbpn.bb(localdRq1);
    localdRq1.brn();
    dRq localdRq2 = localdRq1;
    Jg localJg1 = localdRq2.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq1.bb(localJg1);
    localJg1.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(25, 10, 25, 10));
    localJg1.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(10, 5, 17, 5));
    localJg1.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    localJg1.rV();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localdRq1.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq1.bb(localdRq3);
    localdRq3.brn();
    czO localczO2 = new czO();
    localczO2.aJ();
    localczO2.setAdaptToContentSize(true);
    localdRq3.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.ech);
    localdRq3.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    String str1 = "pennon";
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localczv1);
    localczv1.setStyle("Pennon");
    localczv1.setDisplaySize(new Or(79, 113));
    localdRq3.bb(localczv1);
    localczv1.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setSize(new Or(100.0F, 100.0F));
    localczv1.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    localczv1.rV();
    axU localaxU = new axU();
    localaxU.aJ();
    localaxU.setElementMap(localcpa);
    localdRq3.bb(localaxU);
    localaxU.brn();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setAlign(ajb.dif);
    localcwP4.setSize(new Or(49, 49));
    localcwP4.setYOffset(48);
    localcwP4.setXOffset(-1);
    localaxU.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("content");
    localNK1.setName("equipableDummy");
    localNK1.setField("equipedItem");
    localaxU.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    eR localeR1 = new eR();
    localeR1.aJ();
    localeR1.setElementMap(localcpa);
    fp localfp = new fp();
    localfp.hg("wakfu.equipment:itemDropOut");
    localeR1.setOnDropOut(localfp);
    bpP localbpP = new bpP();
    localbpP.hg("wakfu.equipableDummy:unequip");
    localeR1.setOnItemDoubleClick(localbpP);
    localaxU.bb(localeR1);
    localeR1.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localeR1.bb(localanQ);
    localanQ.brn();
    bxx localbxx = new bxx();
    localbxx.aJ();
    localbxx.setElementMap(localcpa);
    localanQ.bb(localbxx);
    localbxx.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localbxx.bb(localanE);
    localanE.brn();
    localanE.rV();
    localbxx.rV();
    localanQ.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localeR1.bb(localdRq4);
    localdRq4.brn();
    czO localczO3 = new czO();
    localczO3.aJ();
    localczO3.setAdaptToContentSize(true);
    localdRq4.bb(localczO3);
    localczO3.brn();
    localczO3.rV();
    dRq localdRq5 = dRq.checkOut();
    localdRq5.setElementMap(localcpa);
    localdRq5.setNonBlocking(false);
    cCu localcCu1 = new cCu();
    localcCu1.hg("popup(descRenderablePopup)");
    localdRq5.setOnPopupDisplay(localcCu1);
    jL localjL1 = new jL();
    localjL1.hg("closePopup");
    localdRq5.setOnPopupHide(localjL1);
    localdRq4.bb(localdRq5);
    localdRq5.brn();
    String str2 = "descRenderablePopup";
    anG localanG1 = new anG();
    localanG1.aJ();
    localanG1.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localanG1);
    localanG1.setAlign(aFG.ech);
    localanG1.setHotSpotPosition(aFG.ecn);
    localdRq5.bb(localanG1);
    localanG1.brn();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq6.setPrefSize(new Or(10, 0));
    localdRq6.setStyle("popup");
    localanG1.bb(localdRq6);
    localdRq6.brn();
    cba localcba1 = cba.checkOut();
    localcba1.setElementMap(localcpa);
    localcba1.setData(cFu.izR);
    localdRq6.bb(localcba1);
    localcba1.brn();
    localcba1.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("PopupInformation");
    localdRq6.bb(localcaF1);
    localcaF1.brn();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("text");
    localaaE1.setField("name");
    localcaF1.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    caF localcaF2 = localcaF1;
    Jg localJg2 = localcaF2.getAppearance();
    localJg2.setElementMap(localcpa);
    ((cwJ)localJg2).setAlignment(aFG.ecj);
    localcaF1.bb(localJg2);
    localJg2.brn();
    localJg2.rV();
    localcaF1.rV();
    localdRq6.rV();
    localanG1.rV();
    cwP localcwP5 = new cwP();
    localcwP5.aJ();
    localcwP5.setElementMap(localcpa);
    localcwP5.setAlign(ajb.dhZ);
    localdRq5.bb(localcwP5);
    localcwP5.brn();
    localcwP5.rV();
    dRq localdRq7 = localdRq5;
    Jg localJg3 = localdRq7.getAppearance();
    localJg3.setElementMap(localcpa);
    localdRq5.bb(localJg3);
    localJg3.brn();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(2, 2, 2, 2));
    localJg3.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    localJg3.rV();
    bXx localbXx1 = new bXx();
    localbXx1.aJ();
    localbXx1.setElementMap(localcpa);
    bQa localbQa1 = new bQa();
    localbQa1.hg("wakfu.equipableDummy:dropItem");
    localbXx1.setOnDrop(localbQa1);
    dVA localdVA1 = new dVA();
    localdVA1.hg("wakfu.equipableDummy:dragItem");
    localbXx1.setOnDrag(localdVA1);
    localdRq5.bb(localbXx1);
    localbXx1.brn();
    czv localczv2 = new czv();
    localczv2.aJ();
    localczv2.setElementMap(localcpa);
    localczv2.setNonBlocking(true);
    localczv2.setDisplaySize(new Or(42, 42));
    localbXx1.bb(localczv2);
    localczv2.brn();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv2.bb(localaAR);
    localaAR.brn();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("texture");
    localaaE2.setField("iconUrl");
    localaAR.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    localaAR.rV();
    localczv2.rV();
    localbXx1.rV();
    localdRq5.rV();
    localdRq4.rV();
    localeR1.rV();
    eR localeR2 = new eR();
    localeR2.aJ();
    localeR2.setElementMap(localcpa);
    localaxU.bb(localeR2);
    localeR2.brn();
    String str3 = "Equip22";
    dRq localdRq8 = dRq.checkOut();
    localdRq8.setElementMap(localcpa);
    if ((localcpa != null) && (str3 != null))
      localcpa.a(str3, localdRq8);
    localdRq8.setNonBlocking(false);
    cCu localcCu2 = new cCu();
    localcCu2.hg("popup(descEmptyRenderablePopup)");
    localdRq8.setOnPopupDisplay(localcCu2);
    jL localjL2 = new jL();
    localjL2.hg("closePopup");
    localdRq8.setOnPopupHide(localjL2);
    localeR2.bb(localdRq8);
    localdRq8.brn();
    dRq localdRq9 = localdRq8;
    Jg localJg4 = localdRq9.getAppearance();
    localJg4.setElementMap(localcpa);
    localJg4.setModulationColor(new bNa(1.0F, 1.0F, 1.0F, 0.5F));
    localdRq8.bb(localJg4);
    localJg4.brn();
    localJg4.rV();
    String str4 = "descEmptyRenderablePopup";
    anG localanG2 = new anG();
    localanG2.aJ();
    localanG2.setElementMap(localcpa);
    if ((localcpa != null) && (str4 != null))
      localcpa.a(str4, localanG2);
    localanG2.setAlign(aFG.ech);
    localanG2.setHotSpotPosition(aFG.ecn);
    localdRq8.bb(localanG2);
    localanG2.brn();
    dRq localdRq10 = dRq.checkOut();
    localdRq10.setElementMap(localcpa);
    localdRq10.setPrefSize(new Or(10, 0));
    localdRq10.setStyle("popup");
    localanG2.bb(localdRq10);
    localdRq10.brn();
    cba localcba2 = cba.checkOut();
    localcba2.setElementMap(localcpa);
    localcba2.setData(cFu.izR);
    localdRq10.bb(localcba2);
    localcba2.brn();
    localcba2.rV();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setStyle("PopupInformation");
    String str5 = "%equipable.dummy.drop.description%";
    str5 = str5.replace("%equipable.dummy.drop.description%", cBQ.cxL().mL("equipable.dummy.drop.description"));
    localcaF3.setText(str5);
    localdRq10.bb(localcaF3);
    localcaF3.brn();
    caF localcaF4 = localcaF3;
    Jg localJg5 = localcaF4.getAppearance();
    localJg5.setElementMap(localcpa);
    ((cwJ)localJg5).setAlignment(aFG.ecj);
    localcaF3.bb(localJg5);
    localJg5.brn();
    localJg5.rV();
    localcaF3.rV();
    localdRq10.rV();
    localanG2.rV();
    bXx localbXx2 = new bXx();
    localbXx2.aJ();
    localbXx2.setElementMap(localcpa);
    bQa localbQa2 = new bQa();
    localbQa2.hg("wakfu.equipableDummy:dropItem");
    localbXx2.setOnDrop(localbQa2);
    dVA localdVA2 = new dVA();
    localdVA2.hg("wakfu.equipableDummy:dragItem");
    localbXx2.setOnDrag(localdVA2);
    localdRq8.bb(localbXx2);
    localbXx2.brn();
    localbXx2.rV();
    localdRq8.rV();
    localeR2.rV();
    localaxU.rV();
    localdRq3.rV();
    dRq localdRq11 = dRq.checkOut();
    localdRq11.setElementMap(localcpa);
    localdRq11.setPrefSize(new Or(125, 180));
    localdRq11.setExpandable(false);
    localdRq1.bb(localdRq11);
    localdRq11.brn();
    czO localczO4 = new czO();
    localczO4.aJ();
    localdRq11.bb(localczO4);
    localczO4.brn();
    localczO4.rV();
    czv localczv3 = new czv();
    localczv3.aJ();
    localczv3.setElementMap(localcpa);
    localczv3.setStyle("IconEmptyEmote");
    localczv3.setDisplaySize(new Or(90, 45));
    localdRq11.bb(localczv3);
    localczv3.brn();
    cwP localcwP6 = new cwP();
    localcwP6.aJ();
    localcwP6.setElementMap(localcpa);
    localcwP6.setSize(new Or(-2, -2));
    localcwP6.setAlign(ajb.dif);
    localczv3.bb(localcwP6);
    localcwP6.brn();
    localcwP6.rV();
    localczv3.rV();
    dRq localdRq12 = dRq.checkOut();
    localdRq12.setElementMap(localcpa);
    localdRq12.setNonBlocking(true);
    localdRq11.bb(localdRq12);
    localdRq12.brn();
    cwP localcwP7 = new cwP();
    localcwP7.aJ();
    localcwP7.setElementMap(localcpa);
    localcwP7.setAlign(ajb.dhZ);
    localdRq12.bb(localcwP7);
    localcwP7.brn();
    localcwP7.rV();
    String str6 = "localPlayerDisplay";
    auC localauC = new auC();
    localauC.aJ();
    localauC.setElementMap(localcpa);
    if ((localcpa != null) && (str6 != null))
      localcpa.a(str6, localauC);
    localauC.setOffsetY(-70.0F);
    localauC.setOffsetX(-5.0F);
    localauC.setScale(2.0F);
    localauC.setDirection(3);
    localdRq12.bb(localauC);
    localauC.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("equipableDummy");
    localNK2.setAttribute("animatedElement");
    localNK2.setField("actorDescriptorLibrary");
    localauC.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setName("equipableDummy");
    localNK3.setAttribute("animName");
    localNK3.setField("animName");
    localauC.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    localauC.rV();
    localdRq12.rV();
    localdRq11.rV();
    localdRq1.rV();
    dqa localdqa = new dqa();
    localdqa.aJ();
    localdqa.setElementMap(localcpa);
    localbpn.bb(localdqa);
    localdqa.brn();
    cwP localcwP8 = new cwP();
    localcwP8.aJ();
    localcwP8.setElementMap(localcpa);
    localcwP8.setAlign(ajb.dhT);
    localcwP8.setSize(new Or(-2, -2));
    localdqa.bb(localcwP8);
    localcwP8.brn();
    localcwP8.rV();
    czv localczv4 = new czv();
    localczv4.aJ();
    localczv4.setElementMap(localcpa);
    localczv4.setStyle("ScrollBorderTop2");
    localczv4.setNonBlocking(true);
    localdqa.bb(localczv4);
    localczv4.brn();
    localczv4.rV();
    localdqa.rV();
    czv localczv5 = new czv();
    localczv5.aJ();
    localczv5.setElementMap(localcpa);
    localczv5.setStyle("ScrollBorderBottom2");
    localbpn.bb(localczv5);
    localczv5.brn();
    cwP localcwP9 = new cwP();
    localcwP9.aJ();
    localcwP9.setElementMap(localcpa);
    localcwP9.setAlign(ajb.dif);
    localcwP9.setSize(new Or(-2, -2));
    localczv5.bb(localcwP9);
    localcwP9.brn();
    localcwP9.rV();
    localczv5.rV();
    biy localbiy = new biy();
    localbiy.aJ();
    localbiy.setElementMap(localcpa);
    localbiy.setStyle("close");
    csA localcsA = new csA();
    localcsA.hg("unloadDialog");
    localbiy.setOnClick(localcsA);
    localbpn.bb(localbiy);
    localbiy.brn();
    cwP localcwP10 = new cwP();
    localcwP10.aJ();
    localcwP10.setElementMap(localcpa);
    localcwP10.setAlign(ajb.dhV);
    localcwP10.setSize(new Or(-2, -2));
    localcwP10.setXOffset(-16);
    localcwP10.setYOffset(-13);
    localbiy.bb(localcwP10);
    localcwP10.brn();
    localcwP10.rV();
    localbiy.rV();
    localbpn.rV();
    return localbpn;
  }
}