import java.awt.Insets;
import java.util.Stack;

public class dod
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    bpn localbpn = new bpn();
    localbpn.aJ();
    localbpn.setElementMap(localcpa);
    localbpn.setPack(true);
    localbpn.brn();
    czO localczO = new czO();
    localczO.aJ();
    localczO.setAdaptToContentSize(true);
    localbpn.bb(localczO);
    localczO.brn();
    localczO.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localbpn.bb(localdRq1);
    localdRq1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    localdRq1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setStyle("windowNew");
    localbpn.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(10, 5, 12, 5));
    localJg1.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    localJg1.rV();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localdRq2.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localaId1.setAlign(aFG.ech);
    localdRq2.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dqa localdqa1 = new dqa();
    localdqa1.aJ();
    localdqa1.setElementMap(localcpa);
    localdqa1.setExpandable(false);
    localdRq2.bb(localdqa1);
    localdqa1.brn();
    dqa localdqa2 = localdqa1;
    Jg localJg2 = localdqa2.getAppearance();
    localJg2.setElementMap(localcpa);
    localdqa1.bb(localJg2);
    localJg2.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 10, 0, 10));
    localJg2.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg2.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setStyle("titleBar");
    localdqa1.bb(localdRq4);
    localdRq4.brn();
    dRq localdRq5 = localdRq4;
    Jg localJg3 = localdRq5.getAppearance();
    localJg3.setElementMap(localcpa);
    localdRq4.bb(localJg3);
    localJg3.brn();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(2, 20, 3, 20));
    localJg3.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    localJg3.rV();
    aId localaId2 = aId.checkOut();
    localaId2.setHorizontal(false);
    localdRq4.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq6.setExpandable(false);
    localdRq4.bb(localdRq6);
    localdRq6.brn();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa);
    localdpm1.setAlign(aFG.eck);
    localdRq6.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("StyledBold16White");
    localcaF1.setNonBlocking(true);
    String str1 = "%roomAdiministration%";
    str1 = str1.replace("%roomAdiministration%", cBQ.cxL().mL("roomAdiministration"));
    localcaF1.setText(str1);
    localdRq6.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg4 = localcaF2.getAppearance();
    localJg4.setElementMap(localcpa);
    ((cwJ)localJg4).setAlignment(aFG.eck);
    localcaF1.bb(localJg4);
    localJg4.brn();
    localJg4.rV();
    localcaF1.rV();
    localdRq6.rV();
    localdRq4.rV();
    localdqa1.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localdRq2.bb(localdRq7);
    localdRq7.brn();
    dRq localdRq8 = localdRq7;
    Jg localJg5 = localdRq8.getAppearance();
    localJg5.setElementMap(localcpa);
    localdRq7.bb(localJg5);
    localJg5.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 12, 0, 12));
    localJg5.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg5.rV();
    String str2 = "windowContentContainer";
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localdRq9);
    localdRq7.bb(localdRq9);
    localdRq9.brn();
    dRq localdRq10 = dRq.checkOut();
    localdRq10.setElementMap(localcpa);
    localdRq10.setStyle("white");
    localdRq9.bb(localdRq10);
    localdRq10.brn();
    dRq localdRq11 = localdRq10;
    Jg localJg6 = localdRq11.getAppearance();
    localJg6.setElementMap(localcpa);
    localdRq10.bb(localJg6);
    localJg6.brn();
    cuR localcuR3 = new cuR();
    localcuR3.aJ();
    localcuR3.setElementMap(localcpa);
    localcuR3.setInsets(new Insets(10, 14, 14, 10));
    localJg6.bb(localcuR3);
    localcuR3.brn();
    localcuR3.rV();
    localJg6.rV();
    aId localaId3 = aId.checkOut();
    localaId3.setHorizontal(false);
    localaId3.setAlign(aFG.ech);
    localdRq10.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    dRq localdRq12 = dRq.checkOut();
    localdRq12.setElementMap(localcpa);
    localdRq12.setExpandable(false);
    localdRq10.bb(localdRq12);
    localdRq12.brn();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa);
    localdpm2.setAlign(aFG.ecl);
    localdRq12.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    dRq localdRq13 = localdRq12;
    Jg localJg7 = localdRq13.getAppearance();
    localJg7.setElementMap(localcpa);
    localdRq12.bb(localJg7);
    localJg7.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 0, 2, 3));
    localJg7.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg7.rV();
    aId localaId4 = aId.checkOut();
    localaId4.setHorizontal(true);
    localdRq12.bb(localaId4);
    localaId4.brn();
    localaId4.rV();
    ccG localccG = new ccG();
    localccG.aJ();
    localccG.setElementMap(localcpa);
    localccG.setCellSize(new Or(31, 28));
    localccG.setHorizontal(true);
    localccG.setExpandable(false);
    localccG.setAutoIdealSize(true);
    localccG.setIdealSizeMinColumns(1);
    localccG.setIdealSizeMaxColumns(8);
    localccG.setIdealSizeMinRows(1);
    localccG.setIdealSizeMaxRows(1);
    localdRq12.bb(localccG);
    localccG.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("content");
    localNK1.setName("roomPermissions");
    localNK1.setField("roomTypePermList");
    localccG.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    eR localeR1 = new eR();
    localeR1.aJ();
    localeR1.setElementMap(localcpa);
    localccG.bb(localeR1);
    localeR1.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localeR1.bb(localanQ);
    localanQ.brn();
    bxx localbxx = new bxx();
    localbxx.aJ();
    localbxx.setElementMap(localcpa);
    localanQ.bb(localbxx);
    localbxx.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localbxx.bb(localanE);
    localanE.brn();
    localanE.rV();
    localbxx.rV();
    localanQ.rV();
    dRq localdRq14 = dRq.checkOut();
    localdRq14.setElementMap(localcpa);
    localdRq14.setStyle("topItemBackground");
    localeR1.bb(localdRq14);
    localdRq14.brn();
    dRq localdRq15 = localdRq14;
    Jg localJg8 = localdRq15.getAppearance();
    localJg8.setElementMap(localcpa);
    localdRq14.bb(localJg8);
    localJg8.brn();
    cuR localcuR4 = new cuR();
    localcuR4.aJ();
    localcuR4.setElementMap(localcpa);
    localcuR4.setInsets(new Insets(0, 3, 0, 3));
    localJg8.bb(localcuR4);
    localcuR4.brn();
    localcuR4.rV();
    localJg8.rV();
    aId localaId5 = aId.checkOut();
    localaId5.setHorizontal(false);
    localaId5.setAlign(aFG.eck);
    localdRq14.bb(localaId5);
    localaId5.brn();
    localaId5.rV();
    String str3 = "roomType";
    avo localavo1 = new avo();
    localavo1.aJ();
    localavo1.setElementMap(localcpa);
    if ((localcpa != null) && (str3 != null))
      localcpa.a(str3, localavo1);
    localdRq14.bb(localavo1);
    localavo1.brn();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("value");
    localavo1.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    localavo1.rV();
    dRq localdRq16 = dRq.checkOut();
    localdRq16.setElementMap(localcpa);
    localdRq16.setExpandable(false);
    localdRq14.bb(localdRq16);
    localdRq16.brn();
    dRq localdRq17 = localdRq16;
    Jg localJg9 = localdRq17.getAppearance();
    localJg9.setElementMap(localcpa);
    localdRq16.bb(localJg9);
    localJg9.brn();
    cuR localcuR5 = new cuR();
    localcuR5.aJ();
    localcuR5.setElementMap(localcpa);
    localcuR5.setInsets(new Insets(0, 0, 0, 0));
    localJg9.bb(localcuR5);
    localcuR5.brn();
    localcuR5.rV();
    localJg9.rV();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setExpandable(false);
    localczv.setDisplaySize(new Or(24, 24));
    localdRq16.bb(localczv);
    localczv.brn();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv.bb(localaAR);
    localaAR.brn();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("texture");
    localaaE2.setField("iconUrl");
    localaAR.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    localaAR.rV();
    localczv.rV();
    localdRq16.rV();
    localdRq14.rV();
    localeR1.rV();
    localccG.rV();
    localdRq12.rV();
    bbp localbbp = new bbp();
    localbbp.aJ();
    localbbp.setElementMap(localcpa);
    localbbp.setHorizontalScrollBarBehaviour(dOf.mfK);
    localbbp.setExpandable(false);
    localbbp.setMaxSize(new Or(10000, 240));
    localdRq10.bb(localbbp);
    localbbp.brn();
    dpm localdpm3 = new dpm();
    localdpm3.aJ();
    localdpm3.setElementMap(localcpa);
    localdpm3.setAlign(aFG.ecj);
    localbbp.bb(localdpm3);
    localdpm3.brn();
    localdpm3.rV();
    dRq localdRq18 = dRq.checkOut();
    localdRq18.setElementMap(localcpa);
    localbbp.bb(localdRq18);
    localdRq18.brn();
    dRq localdRq19 = localdRq18;
    Jg localJg10 = localdRq19.getAppearance();
    localJg10.setElementMap(localcpa);
    localdRq18.bb(localJg10);
    localJg10.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(0, 0, 0, 4));
    localJg10.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg10.rV();
    aId localaId6 = aId.checkOut();
    localaId6.setHorizontal(true);
    localaId6.setAlign(aFG.ecj);
    localdRq18.bb(localaId6);
    localaId6.brn();
    localaId6.rV();
    dRq localdRq20 = dRq.checkOut();
    localdRq20.setElementMap(localcpa);
    localdRq20.setPrefSize(new Or(246, 0));
    localdRq20.setExpandable(false);
    localdRq18.bb(localdRq20);
    localdRq20.brn();
    aId localaId7 = aId.checkOut();
    localaId7.setHorizontal(false);
    localaId7.setAlign(aFG.ech);
    localdRq20.bb(localaId7);
    localaId7.brn();
    localaId7.rV();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setStyle("whitebold");
    localcaF3.setPrefSize(new Or(145, 30));
    localcaF3.setExpandable(false);
    String str4 = "%desc.everyoneElse%";
    str4 = str4.replace("%desc.everyoneElse%", cBQ.cxL().mL("desc.everyoneElse"));
    localcaF3.setText(str4);
    localdRq20.bb(localcaF3);
    localcaF3.brn();
    caF localcaF4 = localcaF3;
    Jg localJg11 = localcaF4.getAppearance();
    localJg11.setElementMap(localcpa);
    ((cwJ)localJg11).setAlignment(aFG.ecj);
    localcaF3.bb(localJg11);
    localJg11.brn();
    cuR localcuR6 = new cuR();
    localcuR6.aJ();
    localcuR6.setElementMap(localcpa);
    localcuR6.setInsets(new Insets(0, 5, 0, 0));
    localJg11.bb(localcuR6);
    localcuR6.brn();
    localcuR6.rV();
    jO localjO1 = new jO();
    localjO1.aJ();
    localjO1.setElementMap(localcpa);
    localjO1.setColor(new bNa(0.43F, 0.47F, 0.47F, 1.0F));
    localJg11.bb(localjO1);
    localjO1.brn();
    localjO1.rV();
    localJg11.rV();
    localcaF3.rV();
    caF localcaF5 = new caF();
    localcaF5.aJ();
    localcaF5.setElementMap(localcpa);
    localcaF5.setStyle("whitebold");
    localcaF5.setPrefSize(new Or(145, 30));
    localcaF5.setExpandable(false);
    String str5 = "%desc.guild%";
    str5 = str5.replace("%desc.guild%", cBQ.cxL().mL("desc.guild"));
    localcaF5.setText(str5);
    localdRq20.bb(localcaF5);
    localcaF5.brn();
    caF localcaF6 = localcaF5;
    Jg localJg12 = localcaF6.getAppearance();
    localJg12.setElementMap(localcpa);
    ((cwJ)localJg12).setAlignment(aFG.ecj);
    localcaF5.bb(localJg12);
    localJg12.brn();
    cuR localcuR7 = new cuR();
    localcuR7.aJ();
    localcuR7.setElementMap(localcpa);
    localcuR7.setInsets(new Insets(0, 5, 0, 0));
    localJg12.bb(localcuR7);
    localcuR7.brn();
    localcuR7.rV();
    jO localjO2 = new jO();
    localjO2.aJ();
    localjO2.setElementMap(localcpa);
    localjO2.setColor(new bNa(0.43F, 0.47F, 0.47F, 1.0F));
    localJg12.bb(localjO2);
    localjO2.brn();
    localjO2.rV();
    localJg12.rV();
    localcaF5.rV();
    localdRq20.rV();
    at localat = new at();
    localat.aJ();
    localat.setElementMap(localcpa);
    localdRq18.bb(localat);
    localat.brn();
    aId localaId8 = aId.checkOut();
    localaId8.setHorizontal(true);
    localat.bb(localaId8);
    localaId8.brn();
    localaId8.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setAttribute("content");
    localNK2.setName("roomPermissions");
    localNK2.setField("roomTypePermList");
    localat.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    eR localeR2 = new eR();
    localeR2.aJ();
    localeR2.setElementMap(localcpa);
    localat.bb(localeR2);
    localeR2.brn();
    dRq localdRq21 = dRq.checkOut();
    localdRq21.setElementMap(localcpa);
    localeR2.bb(localdRq21);
    localdRq21.brn();
    String str6 = "roomType";
    avo localavo2 = new avo();
    localavo2.aJ();
    localavo2.setElementMap(localcpa);
    if ((localcpa != null) && (str6 != null))
      localcpa.a(str6, localavo2);
    localdRq21.bb(localavo2);
    localavo2.brn();
    aaE localaaE3 = new aaE();
    localaaE3.aJ();
    localaaE3.setElementMap(localcpa);
    localaaE3.setAttribute("value");
    localavo2.bb(localaaE3);
    localaaE3.brn();
    localaaE3.rV();
    localavo2.rV();
    aId localaId9 = aId.checkOut();
    localaId9.setHorizontal(false);
    localaId9.setAlign(aFG.ech);
    localdRq21.bb(localaId9);
    localaId9.brn();
    localaId9.rV();
    a(localdRq21);
    b(localdRq21);
    localdRq21.rV();
    localeR2.rV();
    localat.rV();
    localdRq18.rV();
    localbbp.rV();
    d(localdRq10);
    e(localdRq10);
    f(localdRq10);
    localdRq10.rV();
    localdRq9.rV();
    localdRq7.rV();
    localdRq2.rV();
    h(localbpn);
    i(localbpn);
    j(localbpn);
    localbpn.rV();
    return localbpn;
  }

  public bdj a(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    localdRq1.setPrefSize(new Or(31, 30));
    localdRq1.setStyle("MiddleItemBackground");
    parambdj.bb(localdRq1);
    localdRq1.brn();
    dRq localdRq2 = localdRq1;
    Jg localJg1 = localdRq2.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq1.bb(localJg1);
    localJg1.brn();
    jO localjO = new jO();
    localjO.aJ();
    localjO.setElementMap(localcpa);
    localjO.setColor(new bNa(0.43F, 0.47F, 0.47F, 1.0F));
    localJg1.bb(localjO);
    localjO.brn();
    localjO.rV();
    localJg1.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq3.setStyle("middleItemBackground");
    localdRq1.bb(localdRq3);
    localdRq3.brn();
    aId localaId = aId.checkOut();
    localaId.setAlign(aFG.eck);
    localdRq3.bb(localaId);
    localaId.brn();
    localaId.rV();
    br localbr = new br();
    localbr.aJ();
    localbr.setElementMap(localcpa);
    localbr.setStyle("roundBlue");
    localbr.setExpandable(false);
    csA localcsA = new csA();
    localcsA.hg("wakfu.roomAdministration:changeAnonymousPerms(roomType)");
    localbr.setOnClick(localcsA);
    cCu localcCu = new cCu();
    localcCu.hg("popup(descAutorityPopup)");
    localbr.setOnPopupDisplay(localcCu);
    jL localjL = new jL();
    localjL.hg("closePopup");
    localbr.setOnPopupHide(localjL);
    localdRq3.bb(localbr);
    localbr.brn();
    String str1 = "descAutorityPopup";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localanG);
    localanG.setAlign(aFG.ech);
    localanG.setHotSpotPosition(aFG.ecn);
    localbr.bb(localanG);
    localanG.brn();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setPrefSize(new Or(10, 0));
    localdRq4.setStyle("popup");
    localanG.bb(localdRq4);
    localdRq4.brn();
    cba localcba = cba.checkOut();
    localcba.setElementMap(localcpa);
    localcba.setData(cFu.izR);
    localdRq4.bb(localcba);
    localcba.brn();
    localcba.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("PopupInformation");
    localdRq4.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg2 = localcaF2.getAppearance();
    localJg2.setElementMap(localcpa);
    ((cwJ)localJg2).setAlignment(aFG.ecj);
    localcaF1.bb(localJg2);
    localJg2.brn();
    localJg2.rV();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("text");
    localaaE1.setField("anonymousPerms");
    localcaF1.bb(localaaE1);
    localaaE1.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    String str2 = "%desc.refuseAccess%";
    str2 = str2.replace("%desc.refuseAccess%", cBQ.cxL().mL("desc.refuseAccess"));
    localanQ.setValue(str2);
    String str3 = "%desc.authorizeAccess%";
    str3 = str3.replace("%desc.authorizeAccess%", cBQ.cxL().mL("desc.authorizeAccess"));
    localanQ.setElseValue(str3);
    localaaE1.bb(localanQ);
    localanQ.brn();
    cOk localcOk = new cOk();
    localcOk.aJ();
    localcOk.setElementMap(localcpa);
    localanQ.bb(localcOk);
    localcOk.brn();
    localcOk.rV();
    localanQ.rV();
    localaaE1.rV();
    localcaF1.rV();
    localdRq4.rV();
    localanG.rV();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("selected");
    localaaE2.setField("anonymousPerms");
    localbr.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    localbr.rV();
    localdRq3.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj b(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    localdRq1.setPrefSize(new Or(0, 30));
    parambdj.bb(localdRq1);
    localdRq1.brn();
    dRq localdRq2 = localdRq1;
    Jg localJg1 = localdRq2.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq1.bb(localJg1);
    localJg1.brn();
    jO localjO = new jO();
    localjO.aJ();
    localjO.setElementMap(localcpa);
    localjO.setColor(new bNa(0.43F, 0.47F, 0.47F, 1.0F));
    localJg1.bb(localjO);
    localjO.brn();
    localjO.rV();
    localJg1.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq3.setStyle("middleItemBackground");
    localdRq1.bb(localdRq3);
    localdRq3.brn();
    aId localaId = aId.checkOut();
    localaId.setAlign(aFG.eck);
    localdRq3.bb(localaId);
    localaId.brn();
    localaId.rV();
    br localbr = new br();
    localbr.aJ();
    localbr.setElementMap(localcpa);
    localbr.setStyle("roundblue");
    localbr.setExpandable(false);
    csA localcsA = new csA();
    localcsA.hg("wakfu.roomAdministration:changeGuildPerms(roomType)");
    localbr.setOnClick(localcsA);
    cCu localcCu = new cCu();
    localcCu.hg("popup(descAutorityPopup)");
    localbr.setOnPopupDisplay(localcCu);
    jL localjL = new jL();
    localjL.hg("closePopup");
    localbr.setOnPopupHide(localjL);
    localdRq3.bb(localbr);
    localbr.brn();
    String str1 = "descAutorityPopup";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localanG);
    localanG.setAlign(aFG.ech);
    localanG.setHotSpotPosition(aFG.ecn);
    localbr.bb(localanG);
    localanG.brn();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setPrefSize(new Or(10, 0));
    localdRq4.setStyle("popup");
    localanG.bb(localdRq4);
    localdRq4.brn();
    cba localcba = cba.checkOut();
    localcba.setElementMap(localcpa);
    localcba.setData(cFu.izR);
    localdRq4.bb(localcba);
    localcba.brn();
    localcba.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("PopupInformation");
    localdRq4.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg2 = localcaF2.getAppearance();
    localJg2.setElementMap(localcpa);
    ((cwJ)localJg2).setAlignment(aFG.ecj);
    localcaF1.bb(localJg2);
    localJg2.brn();
    localJg2.rV();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("text");
    localaaE1.setField("guildPerms");
    localcaF1.bb(localaaE1);
    localaaE1.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    String str2 = "%desc.refuseAccess%";
    str2 = str2.replace("%desc.refuseAccess%", cBQ.cxL().mL("desc.refuseAccess"));
    localanQ.setValue(str2);
    String str3 = "%desc.authorizeAccess%";
    str3 = str3.replace("%desc.authorizeAccess%", cBQ.cxL().mL("desc.authorizeAccess"));
    localanQ.setElseValue(str3);
    localaaE1.bb(localanQ);
    localanQ.brn();
    cOk localcOk = new cOk();
    localcOk.aJ();
    localcOk.setElementMap(localcpa);
    localanQ.bb(localcOk);
    localcOk.brn();
    localcOk.rV();
    localanQ.rV();
    localaaE1.rV();
    localcaF1.rV();
    localdRq4.rV();
    localanG.rV();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("selected");
    localaaE2.setField("guildPerms");
    localbr.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    localbr.rV();
    localdRq3.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj d(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    dRq localdRq2 = localdRq1;
    Jg localJg1 = localdRq2.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq1.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(5, 0, 0, 0));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    czO localczO = new czO();
    localczO.aJ();
    localczO.setAdaptToContentSize(true);
    localdRq1.bb(localczO);
    localczO.brn();
    localczO.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq3.setStyle("titleBar");
    localdRq3.setPrefSize(new Or(0, 20));
    localdRq1.bb(localdRq3);
    localdRq3.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setAlign(ajb.dhZ);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localdRq3.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    localdRq3.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setExpandable(false);
    localdRq1.bb(localdRq4);
    localdRq4.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.dhZ);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localdRq4.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    aId localaId = aId.checkOut();
    localaId.setAlign(aFG.eck);
    localdRq4.bb(localaId);
    localaId.brn();
    localaId.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("StyledBoldWhite12");
    localcWk1.setNonBlocking(true);
    String str = "%individualPermissionsTitle%";
    str = str.replace("%individualPermissionsTitle%", cBQ.cxL().mL("individualPermissionsTitle"));
    localcWk1.setText(str);
    localcWk1.setExpandable(false);
    localdRq4.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg2 = localcWk2.getAppearance();
    localJg2.setElementMap(localcpa);
    ((cwJ)localJg2).setAlignment(aFG.eck);
    localcWk1.bb(localJg2);
    localJg2.brn();
    localJg2.rV();
    localcWk1.rV();
    cWk localcWk3 = new cWk();
    localcWk3.aJ();
    localcWk3.setElementMap(localcpa);
    localcWk3.setStyle("StyledBoldWhite12");
    localcWk3.setNonBlocking(true);
    localcWk3.setExpandable(false);
    localdRq4.bb(localcWk3);
    localcWk3.brn();
    cWk localcWk4 = localcWk3;
    Jg localJg3 = localcWk4.getAppearance();
    localJg3.setElementMap(localcpa);
    ((cwJ)localJg3).setAlignment(aFG.eck);
    localcWk3.bb(localJg3);
    localJg3.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 5, 0, 0));
    localJg3.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg3.rV();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setAttribute("text");
    localNK.setName("roomPermissions");
    localNK.setField("individualMaxSizeText");
    localcWk3.bb(localNK);
    localNK.brn();
    localNK.rV();
    localcWk3.rV();
    localdRq4.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj e(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    localdRq1.setPrefSize(new Or(200, 30));
    parambdj.bb(localdRq1);
    localdRq1.brn();
    dRq localdRq2 = localdRq1;
    Jg localJg1 = localdRq2.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq1.bb(localJg1);
    localJg1.brn();
    jO localjO = new jO();
    localjO.aJ();
    localjO.setElementMap(localcpa);
    localjO.setColor(new bNa(0.55F, 0.57F, 0.57F, 1.0F));
    localJg1.bb(localjO);
    localjO.brn();
    localjO.rV();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(0, 5, 0, 0));
    localJg1.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 0, 0, 4));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    String str1 = "customName";
    aTp localaTp1 = new aTp();
    localaTp1.aJ();
    localaTp1.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localaTp1);
    localaTp1.setStyle("softGrayBevel");
    aOn localaOn = new aOn();
    localaOn.hg("wakfu.roomAdministration:addPermission(customName)");
    localaTp1.setOnKeyPress(localaOn);
    localaTp1.setMaxChars(20);
    localaTp1.setPrefSize(new Or(200, 16));
    localdRq1.bb(localaTp1);
    localaTp1.brn();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa);
    localdpm1.setAlign(aFG.eck);
    localaTp1.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    aTp localaTp2 = localaTp1;
    Jg localJg2 = localaTp2.getAppearance();
    localJg2.setElementMap(localcpa);
    localaTp1.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 0, 0, 3));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    localaTp1.rV();
    biy localbiy1 = new biy();
    localbiy1.aJ();
    localbiy1.setElementMap(localcpa);
    localbiy1.setStyle("yellowSmallStyledLight");
    localbiy1.setText("+");
    localbiy1.setExpandable(false);
    csA localcsA = new csA();
    localcsA.hg("wakfu.roomAdministration:addPermission(customName)");
    localbiy1.setOnClick(localcsA);
    cCu localcCu = new cCu();
    localcCu.hg("popup(descAddPopup)");
    localbiy1.setOnPopupDisplay(localcCu);
    jL localjL = new jL();
    localjL.hg("closePopup");
    localbiy1.setOnPopupHide(localjL);
    localdRq1.bb(localbiy1);
    localbiy1.brn();
    biy localbiy2 = localbiy1;
    Jg localJg3 = localbiy2.getAppearance();
    localJg3.setElementMap(localcpa);
    localbiy1.bb(localJg3);
    localJg3.brn();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(2, 4, 2, 5));
    localJg3.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 0, 0, 3));
    localJg3.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg3.rV();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa);
    localdpm2.setAlign(aFG.eck);
    localbiy1.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("enabled");
    localNK1.setName("roomPermissions");
    localNK1.setField("individualMaxSizeReached");
    localbiy1.bb(localNK1);
    localNK1.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localNK1.bb(localanQ);
    localanQ.brn();
    bqW localbqW = new bqW();
    localbqW.aJ();
    localbqW.setElementMap(localcpa);
    localanQ.bb(localbqW);
    localbqW.brn();
    localbqW.rV();
    localanQ.rV();
    localNK1.rV();
    String str2 = "descAddPopup";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localanG);
    localanG.setAlign(aFG.ech);
    localanG.setHotSpotPosition(aFG.ecn);
    localbiy1.bb(localanG);
    localanG.brn();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq3.setPrefSize(new Or(10, 0));
    localdRq3.setStyle("popup");
    localanG.bb(localdRq3);
    localdRq3.brn();
    aId localaId = aId.checkOut();
    localaId.setAlign(aFG.ech);
    localaId.setHorizontal(false);
    localdRq3.bb(localaId);
    localaId.brn();
    localaId.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("PopupInformation");
    String str3 = "%chat.addName%";
    str3 = str3.replace("%chat.addName%", cBQ.cxL().mL("chat.addName"));
    localcaF1.setText(str3);
    localdRq3.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg4 = localcaF2.getAppearance();
    localJg4.setElementMap(localcpa);
    ((cwJ)localJg4).setAlignment(aFG.ecj);
    localcaF1.bb(localJg4);
    localJg4.brn();
    localJg4.rV();
    localcaF1.rV();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setStyle("PopupInformation");
    String str4 = "%desc.individualRightsMaxSizeReached%";
    str4 = str4.replace("%desc.individualRightsMaxSizeReached%", cBQ.cxL().mL("desc.individualRightsMaxSizeReached"));
    localcaF3.setText(str4);
    localdRq3.bb(localcaF3);
    localcaF3.brn();
    caF localcaF4 = localcaF3;
    Jg localJg5 = localcaF4.getAppearance();
    localJg5.setElementMap(localcpa);
    ((cwJ)localJg5).setAlignment(aFG.ecj);
    localcaF3.bb(localJg5);
    localJg5.brn();
    localJg5.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setAttribute("visible");
    localNK2.setName("roomPermissions");
    localNK2.setField("individualMaxSizeReached");
    localcaF3.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localcaF3.rV();
    localdRq3.rV();
    localanG.rV();
    localbiy1.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj f(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    bbp localbbp = new bbp();
    localbbp.aJ();
    localbbp.setElementMap(localcpa);
    localbbp.setHorizontalScrollBarBehaviour(dOf.mfK);
    localbbp.setMaxSize(new Or(10000, 240));
    parambdj.bb(localbbp);
    localbbp.brn();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa);
    localdpm1.setAlign(aFG.ecj);
    localbbp.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localbbp.bb(localdRq1);
    localdRq1.brn();
    dRq localdRq2 = localdRq1;
    Jg localJg1 = localdRq2.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq1.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 0, 0, 4));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(true);
    localaId1.setAlign(aFG.ecj);
    localdRq1.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq3.setPrefSize(new Or(234, 0));
    localdRq3.setExpandable(false);
    localdRq1.bb(localdRq3);
    localdRq3.brn();
    aId localaId2 = aId.checkOut();
    localaId2.setHorizontal(false);
    localaId2.setAlign(aFG.ech);
    localdRq3.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    at localat1 = new at();
    localat1.aJ();
    localat1.setElementMap(localcpa);
    localat1.setExpandable(false);
    localdRq3.bb(localat1);
    localat1.brn();
    aId localaId3 = aId.checkOut();
    localaId3.setHorizontal(false);
    localaId3.setAlign(aFG.ech);
    localat1.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("content");
    localNK1.setName("roomPermissions");
    localNK1.setField("individualList");
    localat1.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    eR localeR1 = new eR();
    localeR1.aJ();
    localeR1.setElementMap(localcpa);
    localat1.bb(localeR1);
    localeR1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localeR1.bb(localanQ1);
    localanQ1.brn();
    bJJ localbJJ1 = new bJJ();
    localbJJ1.aJ();
    localbJJ1.setElementMap(localcpa);
    localanQ1.bb(localbJJ1);
    localbJJ1.brn();
    bxx localbxx1 = new bxx();
    localbxx1.aJ();
    localbxx1.setElementMap(localcpa);
    localbJJ1.bb(localbxx1);
    localbxx1.brn();
    anE localanE1 = new anE();
    localanE1.aJ();
    localanE1.setElementMap(localcpa);
    localbxx1.bb(localanE1);
    localanE1.brn();
    localanE1.rV();
    localbxx1.rV();
    dlQ localdlQ1 = new dlQ();
    localdlQ1.aJ();
    localdlQ1.setElementMap(localcpa);
    localdlQ1.setKey("evenIndex");
    localbJJ1.bb(localdlQ1);
    localdlQ1.brn();
    cOk localcOk1 = new cOk();
    localcOk1.aJ();
    localcOk1.setElementMap(localcpa);
    localdlQ1.bb(localcOk1);
    localcOk1.brn();
    localcOk1.rV();
    localdlQ1.rV();
    localbJJ1.rV();
    localanQ1.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setPrefSize(new Or(0, 30));
    localeR1.bb(localdRq4);
    localdRq4.brn();
    dRq localdRq5 = localdRq4;
    Jg localJg2 = localdRq5.getAppearance();
    localJg2.setElementMap(localcpa);
    localdRq4.bb(localJg2);
    localJg2.brn();
    jO localjO1 = new jO();
    localjO1.aJ();
    localjO1.setElementMap(localcpa);
    localjO1.setColor(new bNa(0.43F, 0.47F, 0.47F, 1.0F));
    localJg2.bb(localjO1);
    localjO1.brn();
    localjO1.rV();
    localJg2.rV();
    aId localaId4 = aId.checkOut();
    localaId4.setAlign(aFG.ecj);
    localdRq4.bb(localaId4);
    localaId4.brn();
    localaId4.rV();
    String str1 = "individualId";
    avo localavo1 = new avo();
    localavo1.aJ();
    localavo1.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localavo1);
    localdRq4.bb(localavo1);
    localavo1.brn();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("value");
    localaaE1.setField("id");
    localavo1.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    localavo1.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("whitebold");
    localcaF1.setExpandable(true);
    localdRq4.bb(localcaF1);
    localcaF1.brn();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("text");
    localaaE2.setField("name");
    localcaF1.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    caF localcaF2 = localcaF1;
    Jg localJg3 = localcaF2.getAppearance();
    localJg3.setElementMap(localcpa);
    ((cwJ)localJg3).setAlign(aFG.ecj);
    localcaF1.bb(localJg3);
    localJg3.brn();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(0, 5, 0, 0));
    localJg3.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    localJg3.rV();
    localcaF1.rV();
    biy localbiy1 = new biy();
    localbiy1.aJ();
    localbiy1.setElementMap(localcpa);
    localbiy1.setStyle("smallDeleteYellow");
    localbiy1.setExpandable(false);
    csA localcsA1 = new csA();
    localcsA1.hg("wakfu.roomAdministration:removePermission(individualId)");
    localbiy1.setOnClick(localcsA1);
    cCu localcCu1 = new cCu();
    localcCu1.hg("popup(removePermPopup)");
    localbiy1.setOnPopupDisplay(localcCu1);
    jL localjL1 = new jL();
    localjL1.hg("closePopup");
    localbiy1.setOnPopupHide(localjL1);
    localdRq4.bb(localbiy1);
    localbiy1.brn();
    String str2 = "removePermPopup";
    anG localanG1 = new anG();
    localanG1.aJ();
    localanG1.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localanG1);
    localanG1.setAlign(aFG.ech);
    localanG1.setHotSpotPosition(aFG.ecn);
    localbiy1.bb(localanG1);
    localanG1.brn();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq6.setPrefSize(new Or(10, 0));
    localdRq6.setStyle("popup");
    localanG1.bb(localdRq6);
    localdRq6.brn();
    cba localcba1 = cba.checkOut();
    localcba1.setElementMap(localcpa);
    localcba1.setData(cFu.izR);
    localdRq6.bb(localcba1);
    localcba1.brn();
    localcba1.rV();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setStyle("PopupInformation");
    String str3 = "%delete%";
    str3 = str3.replace("%delete%", cBQ.cxL().mL("delete"));
    localcaF3.setText(str3);
    localdRq6.bb(localcaF3);
    localcaF3.brn();
    caF localcaF4 = localcaF3;
    Jg localJg4 = localcaF4.getAppearance();
    localJg4.setElementMap(localcpa);
    ((cwJ)localJg4).setAlignment(aFG.ecj);
    localcaF3.bb(localJg4);
    localJg4.brn();
    localJg4.rV();
    localcaF3.rV();
    localdRq6.rV();
    localanG1.rV();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa);
    localdpm2.setAlign(aFG.eck);
    localbiy1.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    biy localbiy2 = localbiy1;
    Jg localJg5 = localbiy2.getAppearance();
    localJg5.setElementMap(localcpa);
    localbiy1.bb(localJg5);
    localJg5.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 0, 0, 3));
    localJg5.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg5.rV();
    localbiy1.rV();
    localdRq4.rV();
    localeR1.rV();
    eR localeR2 = new eR();
    localeR2.aJ();
    localeR2.setElementMap(localcpa);
    localat1.bb(localeR2);
    localeR2.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localeR2.bb(localanQ2);
    localanQ2.brn();
    bJJ localbJJ2 = new bJJ();
    localbJJ2.aJ();
    localbJJ2.setElementMap(localcpa);
    localanQ2.bb(localbJJ2);
    localbJJ2.brn();
    bxx localbxx2 = new bxx();
    localbxx2.aJ();
    localbxx2.setElementMap(localcpa);
    localbJJ2.bb(localbxx2);
    localbxx2.brn();
    anE localanE2 = new anE();
    localanE2.aJ();
    localanE2.setElementMap(localcpa);
    localbxx2.bb(localanE2);
    localanE2.brn();
    localanE2.rV();
    localbxx2.rV();
    dlQ localdlQ2 = new dlQ();
    localdlQ2.aJ();
    localdlQ2.setElementMap(localcpa);
    localdlQ2.setKey("oddIndex");
    localbJJ2.bb(localdlQ2);
    localdlQ2.brn();
    cOk localcOk2 = new cOk();
    localcOk2.aJ();
    localcOk2.setElementMap(localcpa);
    localdlQ2.bb(localcOk2);
    localcOk2.brn();
    localcOk2.rV();
    localdlQ2.rV();
    localbJJ2.rV();
    localanQ2.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localdRq7.setPrefSize(new Or(0, 30));
    localeR2.bb(localdRq7);
    localdRq7.brn();
    dRq localdRq8 = localdRq7;
    Jg localJg6 = localdRq8.getAppearance();
    localJg6.setElementMap(localcpa);
    localdRq7.bb(localJg6);
    localJg6.brn();
    jO localjO2 = new jO();
    localjO2.aJ();
    localjO2.setElementMap(localcpa);
    localjO2.setColor(new bNa(0.55F, 0.57F, 0.57F, 1.0F));
    localJg6.bb(localjO2);
    localjO2.brn();
    localjO2.rV();
    localJg6.rV();
    aId localaId5 = aId.checkOut();
    localaId5.setAlign(aFG.ecj);
    localdRq7.bb(localaId5);
    localaId5.brn();
    localaId5.rV();
    String str4 = "individualId";
    avo localavo2 = new avo();
    localavo2.aJ();
    localavo2.setElementMap(localcpa);
    if ((localcpa != null) && (str4 != null))
      localcpa.a(str4, localavo2);
    localdRq7.bb(localavo2);
    localavo2.brn();
    aaE localaaE3 = new aaE();
    localaaE3.aJ();
    localaaE3.setElementMap(localcpa);
    localaaE3.setAttribute("value");
    localaaE3.setField("id");
    localavo2.bb(localaaE3);
    localaaE3.brn();
    localaaE3.rV();
    localavo2.rV();
    caF localcaF5 = new caF();
    localcaF5.aJ();
    localcaF5.setElementMap(localcpa);
    localcaF5.setStyle("whitebold");
    localcaF5.setExpandable(true);
    localdRq7.bb(localcaF5);
    localcaF5.brn();
    aaE localaaE4 = new aaE();
    localaaE4.aJ();
    localaaE4.setElementMap(localcpa);
    localaaE4.setAttribute("text");
    localaaE4.setField("name");
    localcaF5.bb(localaaE4);
    localaaE4.brn();
    localaaE4.rV();
    caF localcaF6 = localcaF5;
    Jg localJg7 = localcaF6.getAppearance();
    localJg7.setElementMap(localcpa);
    ((cwJ)localJg7).setAlignment(aFG.ecj);
    localcaF5.bb(localJg7);
    localJg7.brn();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(0, 5, 0, 0));
    localJg7.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    localJg7.rV();
    localcaF5.rV();
    biy localbiy3 = new biy();
    localbiy3.aJ();
    localbiy3.setElementMap(localcpa);
    localbiy3.setStyle("smallDeleteYellow");
    localbiy3.setExpandable(false);
    csA localcsA2 = new csA();
    localcsA2.hg("wakfu.roomAdministration:removePermission(individualId)");
    localbiy3.setOnClick(localcsA2);
    cCu localcCu2 = new cCu();
    localcCu2.hg("popup(removePermPopup)");
    localbiy3.setOnPopupDisplay(localcCu2);
    jL localjL2 = new jL();
    localjL2.hg("closePopup");
    localbiy3.setOnPopupHide(localjL2);
    localdRq7.bb(localbiy3);
    localbiy3.brn();
    String str5 = "removePermPopup";
    anG localanG2 = new anG();
    localanG2.aJ();
    localanG2.setElementMap(localcpa);
    if ((localcpa != null) && (str5 != null))
      localcpa.a(str5, localanG2);
    localanG2.setAlign(aFG.ech);
    localanG2.setHotSpotPosition(aFG.ecn);
    localbiy3.bb(localanG2);
    localanG2.brn();
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa);
    localdRq9.setPrefSize(new Or(10, 0));
    localdRq9.setStyle("popup");
    localanG2.bb(localdRq9);
    localdRq9.brn();
    cba localcba2 = cba.checkOut();
    localcba2.setElementMap(localcpa);
    localcba2.setData(cFu.izR);
    localdRq9.bb(localcba2);
    localcba2.brn();
    localcba2.rV();
    caF localcaF7 = new caF();
    localcaF7.aJ();
    localcaF7.setElementMap(localcpa);
    localcaF7.setStyle("PopupInformation");
    String str6 = "%delete%";
    str6 = str6.replace("%delete%", cBQ.cxL().mL("delete"));
    localcaF7.setText(str6);
    localdRq9.bb(localcaF7);
    localcaF7.brn();
    caF localcaF8 = localcaF7;
    Jg localJg8 = localcaF8.getAppearance();
    localJg8.setElementMap(localcpa);
    ((cwJ)localJg8).setAlignment(aFG.ecj);
    localcaF7.bb(localJg8);
    localJg8.brn();
    localJg8.rV();
    localcaF7.rV();
    localdRq9.rV();
    localanG2.rV();
    dpm localdpm3 = new dpm();
    localdpm3.aJ();
    localdpm3.setElementMap(localcpa);
    localdpm3.setAlign(aFG.eck);
    localbiy3.bb(localdpm3);
    localdpm3.brn();
    localdpm3.rV();
    biy localbiy4 = localbiy3;
    Jg localJg9 = localbiy4.getAppearance();
    localJg9.setElementMap(localcpa);
    localbiy3.bb(localJg9);
    localJg9.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 0, 0, 3));
    localJg9.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg9.rV();
    localbiy3.rV();
    localdRq7.rV();
    localeR2.rV();
    localat1.rV();
    localdRq3.rV();
    at localat2 = new at();
    localat2.aJ();
    localat2.setElementMap(localcpa);
    localat2.setExpandable(false);
    localdRq1.bb(localat2);
    localat2.brn();
    aId localaId6 = aId.checkOut();
    localaId6.setHorizontal(true);
    localat2.bb(localaId6);
    localaId6.brn();
    localaId6.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setAttribute("content");
    localNK2.setName("roomPermissions");
    localNK2.setField("roomTypePermList");
    localat2.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    eR localeR3 = new eR();
    localeR3.aJ();
    localeR3.setElementMap(localcpa);
    localat2.bb(localeR3);
    localeR3.brn();
    dRq localdRq10 = dRq.checkOut();
    localdRq10.setElementMap(localcpa);
    localeR3.bb(localdRq10);
    localdRq10.brn();
    String str7 = "roomType";
    avo localavo3 = new avo();
    localavo3.aJ();
    localavo3.setElementMap(localcpa);
    if ((localcpa != null) && (str7 != null))
      localcpa.a(str7, localavo3);
    localdRq10.bb(localavo3);
    localavo3.brn();
    aaE localaaE5 = new aaE();
    localaaE5.aJ();
    localaaE5.setElementMap(localcpa);
    localaaE5.setAttribute("value");
    localavo3.bb(localaaE5);
    localaaE5.brn();
    localaaE5.rV();
    localavo3.rV();
    aId localaId7 = aId.checkOut();
    localaId7.setHorizontal(false);
    localaId7.setAlign(aFG.ech);
    localdRq10.bb(localaId7);
    localaId7.brn();
    localaId7.rV();
    g(localdRq10);
    localdRq10.rV();
    localeR3.rV();
    localat2.rV();
    localdRq1.rV();
    localbbp.rV();
    return localbbp;
  }

  public bdj g(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    String str1 = "stackList";
    at localat = new at();
    localat.aJ();
    localat.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localat);
    localat.setExpandable(false);
    localat.setHorizontal(false);
    parambdj.bb(localat);
    localat.brn();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localat.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("content");
    localaaE1.setField("individualPerms");
    localat.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    eR localeR1 = new eR();
    localeR1.aJ();
    localeR1.setElementMap(localcpa);
    localat.bb(localeR1);
    localeR1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localeR1.bb(localanQ1);
    localanQ1.brn();
    bJJ localbJJ1 = new bJJ();
    localbJJ1.aJ();
    localbJJ1.setElementMap(localcpa);
    localanQ1.bb(localbJJ1);
    localbJJ1.brn();
    bxx localbxx1 = new bxx();
    localbxx1.aJ();
    localbxx1.setElementMap(localcpa);
    localbJJ1.bb(localbxx1);
    localbxx1.brn();
    anE localanE1 = new anE();
    localanE1.aJ();
    localanE1.setElementMap(localcpa);
    localbxx1.bb(localanE1);
    localanE1.brn();
    localanE1.rV();
    localbxx1.rV();
    dlQ localdlQ1 = new dlQ();
    localdlQ1.aJ();
    localdlQ1.setElementMap(localcpa);
    localdlQ1.setKey("oddIndex");
    localbJJ1.bb(localdlQ1);
    localdlQ1.brn();
    cOk localcOk1 = new cOk();
    localcOk1.aJ();
    localcOk1.setElementMap(localcpa);
    localdlQ1.bb(localcOk1);
    localcOk1.brn();
    localcOk1.rV();
    localdlQ1.rV();
    localbJJ1.rV();
    localanQ1.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setPrefSize(new Or(31, 30));
    localeR1.bb(localdRq1);
    localdRq1.brn();
    dRq localdRq2 = localdRq1;
    Jg localJg1 = localdRq2.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq1.bb(localJg1);
    localJg1.brn();
    jO localjO1 = new jO();
    localjO1.aJ();
    localjO1.setElementMap(localcpa);
    localjO1.setColor(new bNa(0.55F, 0.57F, 0.57F, 1.0F));
    localJg1.bb(localjO1);
    localjO1.brn();
    localjO1.rV();
    localJg1.rV();
    String str2 = "individualId";
    avo localavo1 = new avo();
    localavo1.aJ();
    localavo1.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localavo1);
    localdRq1.bb(localavo1);
    localavo1.brn();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("value");
    localaaE2.setField("id");
    localavo1.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    localavo1.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq3.setStyle("MiddleItemBackground");
    localdRq1.bb(localdRq3);
    localdRq3.brn();
    aId localaId2 = aId.checkOut();
    localaId2.setAlign(aFG.eck);
    localdRq3.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    br localbr1 = new br();
    localbr1.aJ();
    localbr1.setElementMap(localcpa);
    localbr1.setStyle("roundBlue");
    localbr1.setExpandable(false);
    bvO localbvO1 = new bvO();
    localbvO1.hg("wakfu.roomAdministration:changeIndividualPerms(individualId,roomType)");
    localbr1.setOnSelectionChange(localbvO1);
    cCu localcCu1 = new cCu();
    localcCu1.hg("popup(descAutorityPopup)");
    localbr1.setOnPopupDisplay(localcCu1);
    jL localjL1 = new jL();
    localjL1.hg("closePopup");
    localbr1.setOnPopupHide(localjL1);
    localdRq3.bb(localbr1);
    localbr1.brn();
    aaE localaaE3 = new aaE();
    localaaE3.aJ();
    localaaE3.setElementMap(localcpa);
    localaaE3.setAttribute("selected");
    localaaE3.setField("granted");
    localbr1.bb(localaaE3);
    localaaE3.brn();
    localaaE3.rV();
    String str3 = "descAutorityPopup";
    anG localanG1 = new anG();
    localanG1.aJ();
    localanG1.setElementMap(localcpa);
    if ((localcpa != null) && (str3 != null))
      localcpa.a(str3, localanG1);
    localanG1.setAlign(aFG.ech);
    localanG1.setHotSpotPosition(aFG.ecn);
    localbr1.bb(localanG1);
    localanG1.brn();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setPrefSize(new Or(10, 0));
    localdRq4.setStyle("popup");
    localanG1.bb(localdRq4);
    localdRq4.brn();
    cba localcba1 = cba.checkOut();
    localcba1.setElementMap(localcpa);
    localcba1.setData(cFu.izR);
    localdRq4.bb(localcba1);
    localcba1.brn();
    localcba1.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("PopupInformation");
    localdRq4.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg2 = localcaF2.getAppearance();
    localJg2.setElementMap(localcpa);
    ((cwJ)localJg2).setAlignment(aFG.ecj);
    localcaF1.bb(localJg2);
    localJg2.brn();
    localJg2.rV();
    aaE localaaE4 = new aaE();
    localaaE4.aJ();
    localaaE4.setElementMap(localcpa);
    localaaE4.setAttribute("text");
    localaaE4.setField("granted");
    localcaF1.bb(localaaE4);
    localaaE4.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    String str4 = "%desc.refuseAccess%";
    str4 = str4.replace("%desc.refuseAccess%", cBQ.cxL().mL("desc.refuseAccess"));
    localanQ2.setValue(str4);
    String str5 = "%desc.authorizeAccess%";
    str5 = str5.replace("%desc.authorizeAccess%", cBQ.cxL().mL("desc.authorizeAccess"));
    localanQ2.setElseValue(str5);
    localaaE4.bb(localanQ2);
    localanQ2.brn();
    cOk localcOk2 = new cOk();
    localcOk2.aJ();
    localcOk2.setElementMap(localcpa);
    localanQ2.bb(localcOk2);
    localcOk2.brn();
    localcOk2.rV();
    localanQ2.rV();
    localaaE4.rV();
    localcaF1.rV();
    localdRq4.rV();
    localanG1.rV();
    localbr1.rV();
    localdRq3.rV();
    localdRq1.rV();
    localeR1.rV();
    eR localeR2 = new eR();
    localeR2.aJ();
    localeR2.setElementMap(localcpa);
    localat.bb(localeR2);
    localeR2.brn();
    anQ localanQ3 = new anQ();
    localanQ3.aJ();
    localanQ3.setElementMap(localcpa);
    localeR2.bb(localanQ3);
    localanQ3.brn();
    bJJ localbJJ2 = new bJJ();
    localbJJ2.aJ();
    localbJJ2.setElementMap(localcpa);
    localanQ3.bb(localbJJ2);
    localbJJ2.brn();
    bxx localbxx2 = new bxx();
    localbxx2.aJ();
    localbxx2.setElementMap(localcpa);
    localbJJ2.bb(localbxx2);
    localbxx2.brn();
    anE localanE2 = new anE();
    localanE2.aJ();
    localanE2.setElementMap(localcpa);
    localbxx2.bb(localanE2);
    localanE2.brn();
    localanE2.rV();
    localbxx2.rV();
    dlQ localdlQ2 = new dlQ();
    localdlQ2.aJ();
    localdlQ2.setElementMap(localcpa);
    localdlQ2.setKey("evenIndex");
    localbJJ2.bb(localdlQ2);
    localdlQ2.brn();
    cOk localcOk3 = new cOk();
    localcOk3.aJ();
    localcOk3.setElementMap(localcpa);
    localdlQ2.bb(localcOk3);
    localcOk3.brn();
    localcOk3.rV();
    localdlQ2.rV();
    localbJJ2.rV();
    localanQ3.rV();
    dRq localdRq5 = dRq.checkOut();
    localdRq5.setElementMap(localcpa);
    localdRq5.setPrefSize(new Or(31, 30));
    localeR2.bb(localdRq5);
    localdRq5.brn();
    String str6 = "individualId";
    avo localavo2 = new avo();
    localavo2.aJ();
    localavo2.setElementMap(localcpa);
    if ((localcpa != null) && (str6 != null))
      localcpa.a(str6, localavo2);
    localdRq5.bb(localavo2);
    localavo2.brn();
    aaE localaaE5 = new aaE();
    localaaE5.aJ();
    localaaE5.setElementMap(localcpa);
    localaaE5.setAttribute("value");
    localaaE5.setField("id");
    localavo2.bb(localaaE5);
    localaaE5.brn();
    localaaE5.rV();
    localavo2.rV();
    dRq localdRq6 = localdRq5;
    Jg localJg3 = localdRq6.getAppearance();
    localJg3.setElementMap(localcpa);
    localdRq5.bb(localJg3);
    localJg3.brn();
    jO localjO2 = new jO();
    localjO2.aJ();
    localjO2.setElementMap(localcpa);
    localjO2.setColor(new bNa(0.43F, 0.47F, 0.47F, 1.0F));
    localJg3.bb(localjO2);
    localjO2.brn();
    localjO2.rV();
    localJg3.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localdRq7.setStyle("middleItemBackground");
    localdRq5.bb(localdRq7);
    localdRq7.brn();
    aId localaId3 = aId.checkOut();
    localaId3.setAlign(aFG.eck);
    localdRq7.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    br localbr2 = new br();
    localbr2.aJ();
    localbr2.setElementMap(localcpa);
    localbr2.setStyle("roundblue");
    localbr2.setExpandable(false);
    bvO localbvO2 = new bvO();
    localbvO2.hg("wakfu.roomAdministration:changeIndividualPerms(individualId,roomType)");
    localbr2.setOnSelectionChange(localbvO2);
    cCu localcCu2 = new cCu();
    localcCu2.hg("popup(descAutorityPopup)");
    localbr2.setOnPopupDisplay(localcCu2);
    jL localjL2 = new jL();
    localjL2.hg("closePopup");
    localbr2.setOnPopupHide(localjL2);
    localdRq7.bb(localbr2);
    localbr2.brn();
    aaE localaaE6 = new aaE();
    localaaE6.aJ();
    localaaE6.setElementMap(localcpa);
    localaaE6.setAttribute("selected");
    localaaE6.setField("granted");
    localbr2.bb(localaaE6);
    localaaE6.brn();
    localaaE6.rV();
    String str7 = "descAutorityPopup";
    anG localanG2 = new anG();
    localanG2.aJ();
    localanG2.setElementMap(localcpa);
    if ((localcpa != null) && (str7 != null))
      localcpa.a(str7, localanG2);
    localanG2.setAlign(aFG.ech);
    localanG2.setHotSpotPosition(aFG.ecn);
    localbr2.bb(localanG2);
    localanG2.brn();
    dRq localdRq8 = dRq.checkOut();
    localdRq8.setElementMap(localcpa);
    localdRq8.setPrefSize(new Or(10, 0));
    localdRq8.setStyle("popup");
    localanG2.bb(localdRq8);
    localdRq8.brn();
    cba localcba2 = cba.checkOut();
    localcba2.setElementMap(localcpa);
    localcba2.setData(cFu.izR);
    localdRq8.bb(localcba2);
    localcba2.brn();
    localcba2.rV();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setStyle("PopupInformation");
    localdRq8.bb(localcaF3);
    localcaF3.brn();
    caF localcaF4 = localcaF3;
    Jg localJg4 = localcaF4.getAppearance();
    localJg4.setElementMap(localcpa);
    ((cwJ)localJg4).setAlignment(aFG.ecj);
    localcaF3.bb(localJg4);
    localJg4.brn();
    localJg4.rV();
    aaE localaaE7 = new aaE();
    localaaE7.aJ();
    localaaE7.setElementMap(localcpa);
    localaaE7.setAttribute("text");
    localaaE7.setField("granted");
    localcaF3.bb(localaaE7);
    localaaE7.brn();
    anQ localanQ4 = new anQ();
    localanQ4.aJ();
    localanQ4.setElementMap(localcpa);
    String str8 = "%desc.refuseAccess%";
    str8 = str8.replace("%desc.refuseAccess%", cBQ.cxL().mL("desc.refuseAccess"));
    localanQ4.setValue(str8);
    String str9 = "%desc.authorizeAccess%";
    str9 = str9.replace("%desc.authorizeAccess%", cBQ.cxL().mL("desc.authorizeAccess"));
    localanQ4.setElseValue(str9);
    localaaE7.bb(localanQ4);
    localanQ4.brn();
    cOk localcOk4 = new cOk();
    localcOk4.aJ();
    localcOk4.setElementMap(localcpa);
    localanQ4.bb(localcOk4);
    localcOk4.brn();
    localcOk4.rV();
    localanQ4.rV();
    localaaE7.rV();
    localcaF3.rV();
    localdRq8.rV();
    localanG2.rV();
    localbr2.rV();
    localdRq7.rV();
    localdRq5.rV();
    localeR2.rV();
    localat.rV();
    return localat;
  }

  public bdj h(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq = dRq.checkOut();
    localdRq.setElementMap(localcpa);
    parambdj.bb(localdRq);
    localdRq.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(100.0F, 100.0F));
    localdRq.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localdRq.rV();
    return localdRq;
  }

  public bdj i(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    biy localbiy = new biy();
    localbiy.aJ();
    localbiy.setElementMap(localcpa);
    localbiy.setStyle("close");
    localbiy.setExpandable(false);
    csA localcsA = new csA();
    localcsA.hg("unloadDialog");
    localbiy.setOnClick(localcsA);
    parambdj.bb(localbiy);
    localbiy.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(-2, -2));
    localcwP.setAlign(ajb.dhV);
    localcwP.setXOffset(-18);
    localcwP.setYOffset(-12);
    localbiy.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localbiy.rV();
    return localbiy;
  }

  public bdj j(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(-2, -2));
    localcwP.setAlign(ajb.dhZ);
    localcwP.setXOffset(-120);
    localcwP.setInitValue(true);
    parambdj.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    return localcwP;
  }
}