import java.awt.Insets;
import java.util.Stack;

public class dsK
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa1 = (cpa)this.X.peek();
    String str1 = "container";
    bpn localbpn = new bpn();
    localbpn.aJ();
    localbpn.setElementMap(localcpa1);
    if ((localcpa1 != null) && (str1 != null))
      localcpa1.a(str1, localbpn);
    localbpn.setPrefSize(new Or(10, 0));
    localbpn.setStyle("popup");
    localbpn.setPack(true);
    localbpn.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa1);
    localcwP.setInitValue(true);
    localcwP.setAlign(ajb.dhZ);
    localbpn.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    String str2 = "stateDetailPopup";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa1);
    if ((localcpa1 != null) && (str2 != null))
      localcpa1.a(str2, localanG);
    localanG.setAlign(aFG.eci);
    localanG.setHotSpotPosition(aFG.ecg);
    localbpn.bb(localanG);
    localanG.brn();
    cpa localcpa2 = localcpa1;
    localcpa1 = this.Y.nd((localcpa1 != null ? localcpa1.getId() : "") + ".itemDetailPopupInc");
    localcpa1.d(localcpa2);
    this.X.push(localcpa1);
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa1);
    localdRq1.setStyle("popup");
    localanG.bb(localdRq1);
    localdRq1.brn();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localaId1.setAlign(aFG.ech);
    localdRq1.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa1);
    localdRq2.setExpandable(false);
    localdRq2.setVisible(false);
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa1);
    localNK1.setName("describedIcon");
    localNK1.setAttribute("visible");
    localdRq2.bb(localNK1);
    localNK1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa1);
    localNK1.bb(localanQ1);
    localanQ1.brn();
    anE localanE1 = new anE();
    localanE1.aJ();
    localanE1.setElementMap(localcpa1);
    localanQ1.bb(localanE1);
    localanE1.brn();
    localanE1.rV();
    localanQ1.rV();
    localNK1.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa1);
    localcWk1.setStyle("white11");
    localcWk1.setMultiline(false);
    localdRq2.bb(localcWk1);
    localcWk1.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa1);
    localNK2.setName("describedIcon");
    localNK2.setAttribute("text");
    localcWk1.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localcWk1.rV();
    localdRq2.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa1);
    localdRq3.setExpandable(false);
    localdRq1.bb(localdRq3);
    localdRq3.brn();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa1);
    localNK3.setName("describedState");
    localNK3.setAttribute("visible");
    localdRq3.bb(localNK3);
    localNK3.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa1);
    localNK3.bb(localanQ2);
    localanQ2.brn();
    anE localanE2 = new anE();
    localanE2.aJ();
    localanE2.setElementMap(localcpa1);
    localanQ2.bb(localanE2);
    localanE2.brn();
    localanE2.rV();
    localanQ2.rV();
    localNK3.rV();
    aId localaId2 = aId.checkOut();
    localaId2.setHorizontal(false);
    localdRq3.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa1);
    localdRq3.bb(localdRq4);
    localdRq4.brn();
    aId localaId3 = aId.checkOut();
    localaId3.setAlign(aFG.ecj);
    localdRq4.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa1);
    localczv1.setExpandable(false);
    localczv1.setDisplaySize(new Or(32, 32));
    localdRq4.bb(localczv1);
    localczv1.brn();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa1);
    localdpm1.setAlign(aFG.ecj);
    localczv1.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa1);
    localczv1.bb(localaAR);
    localaAR.brn();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa1);
    localNK4.setName("describedState");
    localNK4.setAttribute("texture");
    localNK4.setField("iconUrl");
    localaAR.bb(localNK4);
    localNK4.brn();
    localNK4.rV();
    localaAR.rV();
    localczv1.rV();
    dRq localdRq5 = dRq.checkOut();
    localdRq5.setElementMap(localcpa1);
    localdRq4.bb(localdRq5);
    localdRq5.brn();
    dRq localdRq6 = localdRq5;
    Jg localJg1 = localdRq6.getAppearance();
    localJg1.setElementMap(localcpa1);
    localdRq5.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa1);
    localbmv1.setInsets(new Insets(0, 5, 0, 0));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    aId localaId4 = aId.checkOut();
    localaId4.setHorizontal(false);
    localdRq5.bb(localaId4);
    localaId4.brn();
    localaId4.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa1);
    localdRq7.setExpandable(false);
    localdRq5.bb(localdRq7);
    localdRq7.brn();
    aId localaId5 = aId.checkOut();
    localaId5.setAlign(aFG.ecj);
    localdRq7.bb(localaId5);
    localaId5.brn();
    localaId5.rV();
    cWk localcWk2 = new cWk();
    localcWk2.aJ();
    localcWk2.setElementMap(localcpa1);
    localcWk2.setStyle("bigTitle");
    localcWk2.setExpandable(false);
    localcWk2.setMinWidth(190);
    localcWk2.setNonBlocking(true);
    localdRq7.bb(localcWk2);
    localcWk2.brn();
    cWk localcWk3 = localcWk2;
    Jg localJg2 = localcWk3.getAppearance();
    localJg2.setElementMap(localcpa1);
    ((cwJ)localJg2).setAlign(aFG.ecg);
    localcWk2.bb(localJg2);
    localJg2.brn();
    localJg2.rV();
    NK localNK5 = NK.checkOut();
    localNK5.setElementMap(localcpa1);
    localNK5.setName("describedState");
    localNK5.setAttribute("text");
    localNK5.setField("nameWithFormat");
    localcWk2.bb(localNK5);
    localNK5.brn();
    localNK5.rV();
    localcWk2.rV();
    dAS localdAS = new dAS();
    localdAS.aJ();
    localdAS.setElementMap(localcpa1);
    localdRq7.bb(localdAS);
    localdAS.brn();
    localdAS.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa1);
    localcaF1.setStyle("11light");
    localcaF1.setExpandable(false);
    localdRq7.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg3 = localcaF2.getAppearance();
    localJg3.setElementMap(localcpa1);
    localcaF1.bb(localJg3);
    localJg3.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa1);
    localbmv2.setInsets(new Insets(0, 5, 0, 0));
    localJg3.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    cAf localcAf1 = cAf.checkOut();
    localcAf1.setElementMap(localcpa1);
    localcAf1.setColor(new bNa(1.0F, 1.0F, 1.0F, 1.0F));
    localJg3.bb(localcAf1);
    localcAf1.brn();
    localcAf1.rV();
    localJg3.rV();
    NK localNK6 = NK.checkOut();
    localNK6.setElementMap(localcpa1);
    localNK6.setAttribute("visible");
    localNK6.setName("describedState");
    localNK6.setField("maxLevelValue");
    localcaF1.bb(localNK6);
    localNK6.brn();
    anQ localanQ3 = new anQ();
    localanQ3.aJ();
    localanQ3.setElementMap(localcpa1);
    localNK6.bb(localanQ3);
    localanQ3.brn();
    aEJ localaEJ = new aEJ();
    localaEJ.aJ();
    localaEJ.setElementMap(localcpa1);
    localaEJ.setValue("1");
    localanQ3.bb(localaEJ);
    localaEJ.brn();
    localaEJ.rV();
    localanQ3.rV();
    localNK6.rV();
    NK localNK7 = NK.checkOut();
    localNK7.setElementMap(localcpa1);
    localNK7.setName("describedState");
    localNK7.setAttribute("text");
    localNK7.setField("level");
    localcaF1.bb(localNK7);
    localNK7.brn();
    localNK7.rV();
    localcaF1.rV();
    localdRq7.rV();
    czv localczv2 = new czv();
    localczv2.aJ();
    localczv2.setElementMap(localcpa1);
    localczv2.setStyle("stateCumulable");
    localdRq5.bb(localczv2);
    localczv2.brn();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa1);
    localdpm2.setAlign(aFG.ecj);
    localczv2.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    NK localNK8 = NK.checkOut();
    localNK8.setElementMap(localcpa1);
    localNK8.setName("describedState");
    localNK8.setAttribute("visible");
    localNK8.setField("isCumulable");
    localczv2.bb(localNK8);
    localNK8.brn();
    localNK8.rV();
    localczv2.rV();
    localdRq5.rV();
    localdRq4.rV();
    dRq localdRq8 = dRq.checkOut();
    localdRq8.setElementMap(localcpa1);
    localdRq3.bb(localdRq8);
    localdRq8.brn();
    aId localaId6 = aId.checkOut();
    localaId6.setHorizontal(false);
    localdRq8.bb(localaId6);
    localaId6.brn();
    localaId6.rV();
    NK localNK9 = NK.checkOut();
    localNK9.setElementMap(localcpa1);
    localNK9.setName("describedState");
    localNK9.setAttribute("visible");
    localNK9.setField("description");
    localdRq8.bb(localNK9);
    localNK9.brn();
    anQ localanQ4 = new anQ();
    localanQ4.aJ();
    localanQ4.setElementMap(localcpa1);
    localNK9.bb(localanQ4);
    localanQ4.brn();
    bJJ localbJJ1 = new bJJ();
    localbJJ1.aJ();
    localbJJ1.setElementMap(localcpa1);
    localanQ4.bb(localbJJ1);
    localbJJ1.brn();
    anE localanE3 = new anE();
    localanE3.aJ();
    localanE3.setElementMap(localcpa1);
    localbJJ1.bb(localanE3);
    localanE3.brn();
    localanE3.rV();
    jA localjA1 = new jA();
    localjA1.aJ();
    localjA1.setElementMap(localcpa1);
    localjA1.setValue("");
    localbJJ1.bb(localjA1);
    localjA1.brn();
    localjA1.rV();
    localbJJ1.rV();
    localanQ4.rV();
    localNK9.rV();
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa1);
    localdRq9.setExpandable(false);
    localdRq9.setStyle("lineSeparator2");
    localdRq9.setPrefSize(new Or(50, 1));
    localdRq8.bb(localdRq9);
    localdRq9.brn();
    dRq localdRq10 = localdRq9;
    Jg localJg4 = localdRq10.getAppearance();
    localJg4.setElementMap(localcpa1);
    localdRq9.bb(localJg4);
    localJg4.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa1);
    localbmv3.setInsets(new Insets(5, 20, 5, 20));
    localJg4.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg4.rV();
    localdRq9.rV();
    cWk localcWk4 = new cWk();
    localcWk4.aJ();
    localcWk4.setElementMap(localcpa1);
    localcWk4.setExpandable(false);
    localcWk4.setStyle("narrow12");
    localcWk4.setMinWidth(230);
    localdRq8.bb(localcWk4);
    localcWk4.brn();
    dpm localdpm3 = new dpm();
    localdpm3.aJ();
    localdpm3.setElementMap(localcpa1);
    localdpm3.setAlign(aFG.ecj);
    localcWk4.bb(localdpm3);
    localdpm3.brn();
    localdpm3.rV();
    cWk localcWk5 = localcWk4;
    Jg localJg5 = localcWk5.getAppearance();
    localJg5.setElementMap(localcpa1);
    localcWk4.bb(localJg5);
    localJg5.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa1);
    localbmv4.setInsets(new Insets(0, 10, 0, 0));
    localJg5.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    cAf localcAf2 = cAf.checkOut();
    localcAf2.setElementMap(localcpa1);
    localcAf2.setColor(new bNa(0.98F, 0.77F, 0.0F, 1.0F));
    localJg5.bb(localcAf2);
    localcAf2.brn();
    localcAf2.rV();
    localJg5.rV();
    NK localNK10 = NK.checkOut();
    localNK10.setElementMap(localcpa1);
    localNK10.setName("describedState");
    localNK10.setAttribute("text");
    localNK10.setField("description");
    localcWk4.bb(localNK10);
    localNK10.brn();
    localNK10.rV();
    localcWk4.rV();
    localdRq8.rV();
    dRq localdRq11 = dRq.checkOut();
    localdRq11.setElementMap(localcpa1);
    localdRq3.bb(localdRq11);
    localdRq11.brn();
    aId localaId7 = aId.checkOut();
    localaId7.setHorizontal(false);
    localdRq11.bb(localaId7);
    localaId7.brn();
    localaId7.rV();
    NK localNK11 = NK.checkOut();
    localNK11.setElementMap(localcpa1);
    localNK11.setName("describedState");
    localNK11.setAttribute("visible");
    localNK11.setField("effectDescription");
    localdRq11.bb(localNK11);
    localNK11.brn();
    anQ localanQ5 = new anQ();
    localanQ5.aJ();
    localanQ5.setElementMap(localcpa1);
    localNK11.bb(localanQ5);
    localanQ5.brn();
    bJJ localbJJ2 = new bJJ();
    localbJJ2.aJ();
    localbJJ2.setElementMap(localcpa1);
    localanQ5.bb(localbJJ2);
    localbJJ2.brn();
    anE localanE4 = new anE();
    localanE4.aJ();
    localanE4.setElementMap(localcpa1);
    localbJJ2.bb(localanE4);
    localanE4.brn();
    localanE4.rV();
    jA localjA2 = new jA();
    localjA2.aJ();
    localjA2.setElementMap(localcpa1);
    localjA2.setValue("");
    localbJJ2.bb(localjA2);
    localjA2.brn();
    localjA2.rV();
    localbJJ2.rV();
    localanQ5.rV();
    localNK11.rV();
    dRq localdRq12 = dRq.checkOut();
    localdRq12.setElementMap(localcpa1);
    localdRq12.setExpandable(false);
    localdRq12.setStyle("lineSeparator2");
    localdRq12.setPrefSize(new Or(50, 1));
    localdRq11.bb(localdRq12);
    localdRq12.brn();
    dRq localdRq13 = localdRq12;
    Jg localJg6 = localdRq13.getAppearance();
    localJg6.setElementMap(localcpa1);
    localdRq12.bb(localJg6);
    localJg6.brn();
    bmv localbmv5 = bmv.checkOut();
    localbmv5.setElementMap(localcpa1);
    localbmv5.setInsets(new Insets(5, 20, 5, 20));
    localJg6.bb(localbmv5);
    localbmv5.brn();
    localbmv5.rV();
    localJg6.rV();
    localdRq12.rV();
    at localat = new at();
    localat.aJ();
    localat.setElementMap(localcpa1);
    localat.setHorizontal(false);
    localdRq11.bb(localat);
    localat.brn();
    NK localNK12 = NK.checkOut();
    localNK12.setElementMap(localcpa1);
    localNK12.setName("describedState");
    localNK12.setAttribute("content");
    localNK12.setField("effectDescription");
    localat.bb(localNK12);
    localNK12.brn();
    localNK12.rV();
    eR localeR = new eR();
    localeR.aJ();
    localeR.setElementMap(localcpa1);
    localat.bb(localeR);
    localeR.brn();
    anQ localanQ6 = new anQ();
    localanQ6.aJ();
    localanQ6.setElementMap(localcpa1);
    localeR.bb(localanQ6);
    localanQ6.brn();
    bxx localbxx = new bxx();
    localbxx.aJ();
    localbxx.setElementMap(localcpa1);
    localanQ6.bb(localbxx);
    localbxx.brn();
    anE localanE5 = new anE();
    localanE5.aJ();
    localanE5.setElementMap(localcpa1);
    localbxx.bb(localanE5);
    localanE5.brn();
    localanE5.rV();
    localbxx.rV();
    localanQ6.rV();
    dRq localdRq14 = dRq.checkOut();
    localdRq14.setElementMap(localcpa1);
    localeR.bb(localdRq14);
    localdRq14.brn();
    a(localdRq14);
    localdRq14.rV();
    localeR.rV();
    localat.rV();
    localdRq11.rV();
    localdRq3.rV();
    localdRq1.rV();
    this.X.pop();
    localcpa1 = (cpa)this.X.peek();
    localanG.rV();
    b(localbpn);
    localbpn.rV();
    return localbpn;
  }

  public bdj a(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("white11");
    localcWk1.setMinWidth(230);
    localcWk1.setMaxWidth(230);
    localcWk1.setExpandable(false);
    localcWk1.setEnableOnlySelectablePartInteraction(true);
    bDy localbDy = new bDy();
    localbDy.hg("wakfu.spellDetails:processText(container,stateDetailPopup)");
    localcWk1.setOnMouseEnter(localbDy);
    DY localDY = new DY();
    localDY.hg("xulor:closePopup");
    localcWk1.setOnMouseExit(localDY);
    parambdj.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg = localcWk2.getAppearance();
    localJg.setElementMap(localcpa);
    localcWk1.bb(localJg);
    localJg.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(0, 5, 0, 0));
    localJg.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg.rV();
    aaE localaaE = new aaE();
    localaaE.aJ();
    localaaE.setElementMap(localcpa);
    localaaE.setAttribute("text");
    localcWk1.bb(localaaE);
    localaaE.brn();
    localaaE.rV();
    localcWk1.rV();
    return localcWk1;
  }

  public bdj b(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dqa localdqa = new dqa();
    localdqa.aJ();
    localdqa.setElementMap(localcpa);
    parambdj.bb(localdqa);
    localdqa.brn();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setStyle("darkBackgrounded");
    localdqa.bb(localdRq1);
    localdRq1.brn();
    czO localczO = new czO();
    localczO.aJ();
    localczO.setAdaptToContentSize(true);
    localdRq1.bb(localczO);
    localczO.brn();
    localczO.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setPrefSize(new Or(150, 0));
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(3, 3, 3, 3));
    localJg1.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    localJg1.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localdRq2.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq2.bb(localdRq4);
    localdRq4.brn();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setExpandable(false);
    localczv.setScaled(true);
    localczv.setDisplaySize(new Or(48, 48));
    localczv.setNonBlocking(true);
    localdRq4.bb(localczv);
    localczv.brn();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.ech);
    localczv.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv.bb(localaAR);
    localaAR.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setName("describedRunningEffect");
    localNK1.setLocal(true);
    localNK1.setField("iconUrl");
    localNK1.setAttribute("texture");
    localaAR.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    localaAR.rV();
    localczv.rV();
    dRq localdRq5 = dRq.checkOut();
    localdRq5.setElementMap(localcpa);
    localdRq4.bb(localdRq5);
    localdRq5.brn();
    dRq localdRq6 = localdRq5;
    Jg localJg2 = localdRq6.getAppearance();
    localJg2.setElementMap(localcpa);
    localdRq5.bb(localJg2);
    localJg2.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 3, 0, 0));
    localJg2.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg2.rV();
    aId localaId2 = aId.checkOut();
    localaId2.setAlign(aFG.ech);
    localaId2.setHorizontal(false);
    localdRq5.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localdRq7.setStyle("smallDarkBackground");
    localdRq7.setPrefSize(new Or(0, 20));
    localdRq7.setExpandable(false);
    localdRq5.bb(localdRq7);
    localdRq7.brn();
    dRq localdRq8 = localdRq7;
    Jg localJg3 = localdRq8.getAppearance();
    localJg3.setElementMap(localcpa);
    localdRq7.bb(localJg3);
    localJg3.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(2, 0, 2, 0));
    localJg3.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg3.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("whiteBold11");
    localcWk1.setNonBlocking(true);
    localdRq7.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg4 = localcWk2.getAppearance();
    localJg4.setElementMap(localcpa);
    ((cwJ)localJg4).setAlign(aFG.ecj);
    localcWk1.bb(localJg4);
    localJg4.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 5, 0, 5));
    localJg4.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg4.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("describedRunningEffect");
    localNK2.setLocal(true);
    localNK2.setAttribute("text");
    localNK2.setField("nameAndLevel");
    localcWk1.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localcWk1.rV();
    biy localbiy = new biy();
    localbiy.aJ();
    localbiy.setElementMap(localcpa);
    localbiy.setStyle("close");
    localbiy.setExpandable(false);
    csA localcsA1 = new csA();
    localcsA1.hg("unloadDialog");
    localbiy.setOnClick(localcsA1);
    localdRq7.bb(localbiy);
    localbiy.brn();
    localbiy.rV();
    localdRq7.rV();
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa);
    localdRq9.setExpandable(false);
    localdRq9.setPrefSize(new Or(0, 20));
    localdRq9.setStyle("smallDarkBackground");
    localdRq5.bb(localdRq9);
    localdRq9.brn();
    dRq localdRq10 = localdRq9;
    Jg localJg5 = localdRq10.getAppearance();
    localJg5.setElementMap(localcpa);
    localdRq9.bb(localJg5);
    localJg5.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(2, 0, 2, 0));
    localJg5.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(0, 5, 0, 5));
    localJg5.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    localJg5.rV();
    aId localaId3 = aId.checkOut();
    localaId3.setAlign(aFG.ecj);
    localdRq9.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setName("describedRunningEffect");
    localNK3.setLocal(true);
    localNK3.setAttribute("visible");
    localNK3.setField("remainingDurationText");
    localdRq9.bb(localNK3);
    localNK3.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localNK3.bb(localanQ1);
    localanQ1.brn();
    anE localanE1 = new anE();
    localanE1.aJ();
    localanE1.setElementMap(localcpa);
    localanQ1.bb(localanE1);
    localanE1.brn();
    localanE1.rV();
    localanQ1.rV();
    localNK3.rV();
    caF localcaF = new caF();
    localcaF.aJ();
    localcaF.setElementMap(localcpa);
    localcaF.setExpandable(false);
    localcaF.setStyle("whiteBold");
    String str = "%duration% ";
    str = str.replace("%duration%", cBQ.cxL().mL("duration"));
    localcaF.setText(str);
    localcaF.setNonBlocking(true);
    localdRq9.bb(localcaF);
    localcaF.brn();
    localcaF.rV();
    cWk localcWk3 = new cWk();
    localcWk3.aJ();
    localcWk3.setElementMap(localcpa);
    localcWk3.setStyle("white");
    localcWk3.setNonBlocking(true);
    localdRq9.bb(localcWk3);
    localcWk3.brn();
    cWk localcWk4 = localcWk3;
    Jg localJg6 = localcWk4.getAppearance();
    localJg6.setElementMap(localcpa);
    ((cwJ)localJg6).setAlign(aFG.ecj);
    localcWk3.bb(localJg6);
    localJg6.brn();
    localJg6.rV();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa);
    localNK4.setName("describedRunningEffect");
    localNK4.setLocal(true);
    localNK4.setAttribute("text");
    localNK4.setField("remainingDurationText");
    localcWk3.bb(localNK4);
    localNK4.brn();
    localNK4.rV();
    NK localNK5 = NK.checkOut();
    localNK5.setElementMap(localcpa);
    localNK5.setName("describedRunningEffect");
    localNK5.setLocal(true);
    localNK5.setAttribute("visible");
    localNK5.setField("remainingDurationText");
    localcWk3.bb(localNK5);
    localNK5.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localNK5.bb(localanQ2);
    localanQ2.brn();
    anE localanE2 = new anE();
    localanE2.aJ();
    localanE2.setElementMap(localcpa);
    localanQ2.bb(localanE2);
    localanE2.brn();
    localanE2.rV();
    localanQ2.rV();
    localNK5.rV();
    localcWk3.rV();
    localdRq9.rV();
    localdRq5.rV();
    localdRq4.rV();
    dRq localdRq11 = dRq.checkOut();
    localdRq11.setElementMap(localcpa);
    localdRq11.setStyle("smallDarkBackground");
    localdRq11.setPrefSize(new Or(0, 20));
    localdRq11.setExpandable(false);
    localdRq2.bb(localdRq11);
    localdRq11.brn();
    NK localNK6 = NK.checkOut();
    localNK6.setElementMap(localcpa);
    localNK6.setName("isInFight");
    localNK6.setAttribute("visible");
    localdRq11.bb(localNK6);
    localNK6.brn();
    anQ localanQ3 = new anQ();
    localanQ3.aJ();
    localanQ3.setElementMap(localcpa);
    localNK6.bb(localanQ3);
    localanQ3.brn();
    bJJ localbJJ = new bJJ();
    localbJJ.aJ();
    localbJJ.setElementMap(localcpa);
    localanQ3.bb(localbJJ);
    localbJJ.brn();
    bqW localbqW = new bqW();
    localbqW.aJ();
    localbqW.setElementMap(localcpa);
    localbJJ.bb(localbqW);
    localbqW.brn();
    localbqW.rV();
    cOk localcOk = new cOk();
    localcOk.aJ();
    localcOk.setElementMap(localcpa);
    localbJJ.bb(localcOk);
    localcOk.brn();
    NK localNK7 = NK.checkOut();
    localNK7.setElementMap(localcpa);
    localNK7.setName("describedRunningEffect");
    localNK7.setLocal(true);
    localNK7.setAttribute("comparedValue");
    localNK7.setField("description");
    localcOk.bb(localNK7);
    localNK7.brn();
    anQ localanQ4 = new anQ();
    localanQ4.aJ();
    localanQ4.setElementMap(localcpa);
    localNK7.bb(localanQ4);
    localanQ4.brn();
    anE localanE3 = new anE();
    localanE3.aJ();
    localanE3.setElementMap(localcpa);
    localanQ4.bb(localanE3);
    localanE3.brn();
    localanE3.rV();
    localanQ4.rV();
    localNK7.rV();
    localcOk.rV();
    localbJJ.rV();
    localanQ3.rV();
    localNK6.rV();
    dRq localdRq12 = localdRq11;
    Jg localJg7 = localdRq12.getAppearance();
    localJg7.setElementMap(localcpa);
    localdRq11.bb(localJg7);
    localJg7.brn();
    bmv localbmv5 = bmv.checkOut();
    localbmv5.setElementMap(localcpa);
    localbmv5.setInsets(new Insets(2, 0, 2, 0));
    localJg7.bb(localbmv5);
    localbmv5.brn();
    localbmv5.rV();
    cuR localcuR3 = new cuR();
    localcuR3.aJ();
    localcuR3.setElementMap(localcpa);
    localcuR3.setInsets(new Insets(5, 5, 5, 5));
    localJg7.bb(localcuR3);
    localcuR3.brn();
    localcuR3.rV();
    localJg7.rV();
    cWk localcWk5 = new cWk();
    localcWk5.aJ();
    localcWk5.setElementMap(localcpa);
    localcWk5.setStyle("narrow12");
    localcWk5.setNonBlocking(true);
    localcWk5.setMinWidth(1);
    localcWk5.setMaxWidth(230);
    localdRq11.bb(localcWk5);
    localcWk5.brn();
    cWk localcWk6 = localcWk5;
    Jg localJg8 = localcWk6.getAppearance();
    localJg8.setElementMap(localcpa);
    ((cwJ)localJg8).setAlign(aFG.ecj);
    localcWk5.bb(localJg8);
    localJg8.brn();
    cAf localcAf = cAf.checkOut();
    localcAf.setElementMap(localcpa);
    localcAf.setColor(new bNa(0.98F, 0.77F, 0.0F, 1.0F));
    localJg8.bb(localcAf);
    localcAf.brn();
    localcAf.rV();
    localJg8.rV();
    NK localNK8 = NK.checkOut();
    localNK8.setElementMap(localcpa);
    localNK8.setName("describedRunningEffect");
    localNK8.setLocal(true);
    localNK8.setAttribute("text");
    localNK8.setField("description");
    localcWk5.bb(localNK8);
    localNK8.brn();
    localNK8.rV();
    localcWk5.rV();
    localdRq11.rV();
    dRq localdRq13 = dRq.checkOut();
    localdRq13.setElementMap(localcpa);
    localdRq13.setExpandable(false);
    localdRq13.setStyle("smallDarkBackground");
    localdRq2.bb(localdRq13);
    localdRq13.brn();
    NK localNK9 = NK.checkOut();
    localNK9.setElementMap(localcpa);
    localNK9.setName("describedRunningEffect");
    localNK9.setLocal(true);
    localNK9.setAttribute("visible");
    localNK9.setField("effects");
    localdRq13.bb(localNK9);
    localNK9.brn();
    anQ localanQ5 = new anQ();
    localanQ5.aJ();
    localanQ5.setElementMap(localcpa);
    localNK9.bb(localanQ5);
    localanQ5.brn();
    anE localanE4 = new anE();
    localanE4.aJ();
    localanE4.setElementMap(localcpa);
    localanQ5.bb(localanE4);
    localanE4.brn();
    localanE4.rV();
    localanQ5.rV();
    localNK9.rV();
    dRq localdRq14 = localdRq13;
    Jg localJg9 = localdRq14.getAppearance();
    localJg9.setElementMap(localcpa);
    localdRq13.bb(localJg9);
    localJg9.brn();
    bmv localbmv6 = bmv.checkOut();
    localbmv6.setElementMap(localcpa);
    localbmv6.setInsets(new Insets(2, 0, 2, 0));
    localJg9.bb(localbmv6);
    localbmv6.brn();
    localbmv6.rV();
    cuR localcuR4 = new cuR();
    localcuR4.aJ();
    localcuR4.setElementMap(localcpa);
    localcuR4.setInsets(new Insets(5, 5, 5, 5));
    localJg9.bb(localcuR4);
    localcuR4.brn();
    localcuR4.rV();
    localJg9.rV();
    cWk localcWk7 = new cWk();
    localcWk7.aJ();
    localcWk7.setElementMap(localcpa);
    localcWk7.setStyle("white11");
    localcWk7.setMinWidth(1);
    localcWk7.setMaxWidth(230);
    localcWk7.setEnableOnlySelectablePartInteraction(true);
    csA localcsA2 = new csA();
    localcsA2.hg("wakfu.spellDetails:processText(container,stateDetailPopup)");
    localcWk7.setOnClick(localcsA2);
    bDy localbDy = new bDy();
    localbDy.hg("wakfu.spellDetails:processText(container,stateDetailPopup)");
    localcWk7.setOnMouseEnter(localbDy);
    DY localDY = new DY();
    localDY.hg("xulor:closePopup");
    localcWk7.setOnMouseExit(localDY);
    localdRq13.bb(localcWk7);
    localcWk7.brn();
    NK localNK10 = NK.checkOut();
    localNK10.setElementMap(localcpa);
    localNK10.setName("describedRunningEffect");
    localNK10.setLocal(true);
    localNK10.setAttribute("text");
    localNK10.setField("effects");
    localcWk7.bb(localNK10);
    localNK10.brn();
    localNK10.rV();
    cWk localcWk8 = localcWk7;
    Jg localJg10 = localcWk8.getAppearance();
    localJg10.setElementMap(localcpa);
    localcWk7.bb(localJg10);
    localJg10.brn();
    bmv localbmv7 = bmv.checkOut();
    localbmv7.setElementMap(localcpa);
    localbmv7.setInsets(new Insets(0, 0, 0, 0));
    localJg10.bb(localbmv7);
    localbmv7.brn();
    localbmv7.rV();
    localJg10.rV();
    localcWk7.rV();
    localdRq13.rV();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(100.0F, 100.0F));
    localdRq2.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localdRq2.rV();
    localdRq1.rV();
    localdqa.rV();
    return localdqa;
  }
}