import java.awt.Insets;
import java.util.Stack;

public class dgh
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa1 = (cpa)this.X.peek();
    bpn localbpn = new bpn();
    localbpn.aJ();
    localbpn.setElementMap(localcpa1);
    localbpn.setPack(true);
    localbpn.brn();
    czO localczO1 = new czO();
    localczO1.aJ();
    localczO1.setAdaptToContentSize(true);
    localbpn.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa1);
    localbpn.bb(localdRq1);
    localdRq1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa1);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    localdRq1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa1);
    localdRq2.setStyle("windowNew");
    localbpn.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa1);
    localdRq2.bb(localJg1);
    localJg1.brn();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa1);
    localcuR1.setInsets(new Insets(10, 5, 12, 5));
    localJg1.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    localJg1.rV();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa1);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localdRq2.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localaId1.setAlign(aFG.ech);
    localdRq2.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dqa localdqa1 = new dqa();
    localdqa1.aJ();
    localdqa1.setElementMap(localcpa1);
    localdqa1.setExpandable(false);
    localdRq2.bb(localdqa1);
    localdqa1.brn();
    dqa localdqa2 = localdqa1;
    Jg localJg2 = localdqa2.getAppearance();
    localJg2.setElementMap(localcpa1);
    localdqa1.bb(localJg2);
    localJg2.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa1);
    localbmv1.setInsets(new Insets(0, 10, 0, 10));
    localJg2.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg2.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa1);
    localdRq4.setStyle("titleBar");
    localdqa1.bb(localdRq4);
    localdRq4.brn();
    dRq localdRq5 = localdRq4;
    Jg localJg3 = localdRq5.getAppearance();
    localJg3.setElementMap(localcpa1);
    localdRq4.bb(localJg3);
    localJg3.brn();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa1);
    localcuR2.setInsets(new Insets(2, 20, 3, 20));
    localJg3.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    localJg3.rV();
    aId localaId2 = aId.checkOut();
    localaId2.setHorizontal(false);
    localdRq4.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa1);
    localdRq6.setExpandable(false);
    localdRq4.bb(localdRq6);
    localdRq6.brn();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa1);
    localdpm1.setAlign(aFG.eck);
    localdRq6.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa1);
    localcaF1.setStyle("StyledBold16White");
    localcaF1.setNonBlocking(true);
    String str1 = "%havenWorld%";
    str1 = str1.replace("%havenWorld%", cBQ.cxL().mL("havenWorld"));
    localcaF1.setText(str1);
    localdRq6.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg4 = localcaF2.getAppearance();
    localJg4.setElementMap(localcpa1);
    ((cwJ)localJg4).setAlignment(aFG.eck);
    localcaF1.bb(localJg4);
    localJg4.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa1);
    localbmv2.setInsets(new Insets(0, 0, 0, 5));
    localJg4.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg4.rV();
    localcaF1.rV();
    localdRq6.rV();
    localdRq4.rV();
    localdqa1.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa1);
    localdRq2.bb(localdRq7);
    localdRq7.brn();
    dRq localdRq8 = localdRq7;
    Jg localJg5 = localdRq8.getAppearance();
    localJg5.setElementMap(localcpa1);
    localdRq7.bb(localJg5);
    localJg5.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa1);
    localbmv3.setInsets(new Insets(0, 12, 0, 12));
    localJg5.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg5.rV();
    String str2 = "windowContentContainer";
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa1);
    if ((localcpa1 != null) && (str2 != null))
      localcpa1.a(str2, localdRq9);
    localdRq7.bb(localdRq9);
    localdRq9.brn();
    czO localczO2 = new czO();
    localczO2.aJ();
    localczO2.setAdaptToContentSize(true);
    localdRq9.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    dRq localdRq10 = localdRq9;
    Jg localJg6 = localdRq10.getAppearance();
    localJg6.setElementMap(localcpa1);
    localdRq9.bb(localJg6);
    localJg6.brn();
    cuR localcuR3 = new cuR();
    localcuR3.aJ();
    localcuR3.setElementMap(localcpa1);
    localcuR3.setInsets(new Insets(10, 0, 0, 0));
    localJg6.bb(localcuR3);
    localcuR3.brn();
    localcuR3.rV();
    localJg6.rV();
    String str3 = "elementDetailPopup";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa1);
    if ((localcpa1 != null) && (str3 != null))
      localcpa1.a(str3, localanG);
    localanG.setAlign(aFG.eci);
    localanG.setHotSpotPosition(aFG.ecg);
    localdRq9.bb(localanG);
    localanG.brn();
    cpa localcpa2 = localcpa1;
    localcpa1 = this.Y.nd((localcpa1 != null ? localcpa1.getId() : "") + ".elementDetailPopupInc");
    localcpa1.d(localcpa2);
    this.X.push(localcpa1);
    dRq localdRq11 = dRq.checkOut();
    localdRq11.setElementMap(localcpa1);
    localdRq11.setStyle("popup");
    localdRq11.setPrefSize(new Or(240, 0));
    localanG.bb(localdRq11);
    localdRq11.brn();
    aId localaId3 = aId.checkOut();
    localaId3.setHorizontal(false);
    localaId3.setAlign(aFG.ech);
    localdRq11.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    dRq localdRq12 = dRq.checkOut();
    localdRq12.setElementMap(localcpa1);
    localdRq12.setExpandable(false);
    localdRq11.bb(localdRq12);
    localdRq12.brn();
    aId localaId4 = aId.checkOut();
    localaId4.setHorizontal(false);
    localdRq12.bb(localaId4);
    localaId4.brn();
    localaId4.rV();
    dRq localdRq13 = dRq.checkOut();
    localdRq13.setElementMap(localcpa1);
    localdRq12.bb(localdRq13);
    localdRq13.brn();
    aId localaId5 = aId.checkOut();
    localaId5.setAlign(aFG.ech);
    localaId5.setHorizontal(false);
    localdRq13.bb(localaId5);
    localaId5.brn();
    localaId5.rV();
    dRq localdRq14 = dRq.checkOut();
    localdRq14.setElementMap(localcpa1);
    localdRq14.setExpandable(false);
    localdRq13.bb(localdRq14);
    localdRq14.brn();
    aId localaId6 = aId.checkOut();
    localaId6.setAlign(aFG.ecj);
    localdRq14.bb(localaId6);
    localaId6.brn();
    localaId6.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa1);
    localcWk1.setStyle("DefaultBold14White");
    localcWk1.setExpandable(false);
    localcWk1.setMinWidth(1);
    localcWk1.setMaxWidth(250);
    localdRq14.bb(localcWk1);
    localcWk1.brn();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa1);
    localdpm2.setAlign(aFG.ech);
    localcWk1.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    cWk localcWk2 = localcWk1;
    Jg localJg7 = localcWk2.getAppearance();
    localJg7.setElementMap(localcpa1);
    ((cwJ)localJg7).setAlign(aFG.ecg);
    localcWk1.bb(localJg7);
    localJg7.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa1);
    localbmv4.setInsets(new Insets(0, 5, 0, 0));
    localJg7.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg7.rV();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa1);
    localNK1.setName("havenWorldOverCatalogEntry");
    localNK1.setAttribute("text");
    localNK1.setField("name");
    localcWk1.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    localcWk1.rV();
    localdRq14.rV();
    dRq localdRq15 = dRq.checkOut();
    localdRq15.setElementMap(localcpa1);
    localdRq15.setExpandable(false);
    localdRq13.bb(localdRq15);
    localdRq15.brn();
    aId localaId7 = aId.checkOut();
    localaId7.setAlign(aFG.ecj);
    localdRq15.bb(localaId7);
    localaId7.brn();
    localaId7.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa1);
    localczv1.setDisplaySize(new Or(128, 128));
    localczv1.setKeepAspectRatio(true);
    localczv1.setExpandable(false);
    localdRq15.bb(localczv1);
    localczv1.brn();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa1);
    localczv1.bb(localaAR);
    localaAR.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa1);
    localNK2.setName("havenWorldOverCatalogEntry");
    localNK2.setAttribute("texture");
    localNK2.setField("iconUrl");
    localaAR.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localaAR.rV();
    localczv1.rV();
    dAS localdAS = new dAS();
    localdAS.aJ();
    localdAS.setElementMap(localcpa1);
    localdRq15.bb(localdAS);
    localdAS.brn();
    localdAS.rV();
    dRq localdRq16 = dRq.checkOut();
    localdRq16.setElementMap(localcpa1);
    localdRq16.setExpandable(false);
    localdRq15.bb(localdRq16);
    localdRq16.brn();
    aId localaId8 = aId.checkOut();
    localaId8.setAlign(aFG.ech);
    localaId8.setHorizontal(false);
    localdRq16.bb(localaId8);
    localaId8.brn();
    localaId8.rV();
    dRq localdRq17 = localdRq16;
    Jg localJg8 = localdRq17.getAppearance();
    localJg8.setElementMap(localcpa1);
    localdRq16.bb(localJg8);
    localJg8.brn();
    bmv localbmv5 = bmv.checkOut();
    localbmv5.setElementMap(localcpa1);
    localbmv5.setInsets(new Insets(0, 3, 0, 0));
    localJg8.bb(localbmv5);
    localbmv5.brn();
    localbmv5.rV();
    localJg8.rV();
    dRq localdRq18 = dRq.checkOut();
    localdRq18.setElementMap(localcpa1);
    localdRq18.setExpandable(false);
    localdRq16.bb(localdRq18);
    localdRq18.brn();
    dRq localdRq19 = localdRq18;
    Jg localJg9 = localdRq19.getAppearance();
    localJg9.setElementMap(localcpa1);
    localdRq18.bb(localJg9);
    localJg9.brn();
    bmv localbmv6 = bmv.checkOut();
    localbmv6.setElementMap(localcpa1);
    localbmv6.setInsets(new Insets(0, 0, 2, 0));
    localJg9.bb(localbmv6);
    localbmv6.brn();
    localbmv6.rV();
    localJg9.rV();
    aId localaId9 = aId.checkOut();
    localaId9.setHgap((short)2);
    localaId9.setAlign(aFG.ecl);
    localdRq18.bb(localaId9);
    localaId9.brn();
    localaId9.rV();
    cWk localcWk3 = new cWk();
    localcWk3.aJ();
    localcWk3.setElementMap(localcpa1);
    localcWk3.setStyle("whiteBold");
    localcWk3.setExpandable(false);
    localdRq18.bb(localcWk3);
    localcWk3.brn();
    dpm localdpm3 = new dpm();
    localdpm3.aJ();
    localdpm3.setElementMap(localcpa1);
    localdpm3.setAlign(aFG.eck);
    localcWk3.bb(localdpm3);
    localdpm3.brn();
    localdpm3.rV();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa1);
    localNK3.setName("havenWorldOverCatalogEntry");
    localNK3.setAttribute("text");
    localNK3.setField("kamasCost");
    localcWk3.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    localcWk3.rV();
    czv localczv2 = new czv();
    localczv2.aJ();
    localczv2.setElementMap(localcpa1);
    localczv2.setStyle("KamaIcon");
    localczv2.setExpandable(false);
    localdRq18.bb(localczv2);
    localczv2.brn();
    localczv2.rV();
    localdRq18.rV();
    dRq localdRq20 = dRq.checkOut();
    localdRq20.setElementMap(localcpa1);
    localdRq20.setExpandable(false);
    localdRq16.bb(localdRq20);
    localdRq20.brn();
    aId localaId10 = aId.checkOut();
    localaId10.setHgap((short)2);
    localaId10.setAlign(aFG.ecl);
    localdRq20.bb(localaId10);
    localaId10.brn();
    localaId10.rV();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa1);
    localNK4.setName("havenWorldOverCatalogEntry");
    localNK4.setAttribute("visible");
    localNK4.setField("ressourcesCost");
    localdRq20.bb(localNK4);
    localNK4.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa1);
    localNK4.bb(localanQ1);
    localanQ1.brn();
    anE localanE1 = new anE();
    localanE1.aJ();
    localanE1.setElementMap(localcpa1);
    localanQ1.bb(localanE1);
    localanE1.brn();
    localanE1.rV();
    localanQ1.rV();
    localNK4.rV();
    cWk localcWk4 = new cWk();
    localcWk4.aJ();
    localcWk4.setElementMap(localcpa1);
    localcWk4.setStyle("whiteBold");
    localcWk4.setExpandable(false);
    localdRq20.bb(localcWk4);
    localcWk4.brn();
    dpm localdpm4 = new dpm();
    localdpm4.aJ();
    localdpm4.setElementMap(localcpa1);
    localdpm4.setAlign(aFG.eck);
    localcWk4.bb(localdpm4);
    localdpm4.brn();
    localdpm4.rV();
    NK localNK5 = NK.checkOut();
    localNK5.setElementMap(localcpa1);
    localNK5.setName("havenWorldOverCatalogEntry");
    localNK5.setAttribute("text");
    localNK5.setField("ressourcesCost");
    localcWk4.bb(localNK5);
    localNK5.brn();
    localNK5.rV();
    localcWk4.rV();
    czv localczv3 = new czv();
    localczv3.aJ();
    localczv3.setElementMap(localcpa1);
    localczv3.setStyle("HavenWorldResourcesPoints");
    localczv3.setExpandable(false);
    localdRq20.bb(localczv3);
    localczv3.brn();
    localczv3.rV();
    localdRq20.rV();
    dRq localdRq21 = dRq.checkOut();
    localdRq21.setElementMap(localcpa1);
    localdRq21.setExpandable(false);
    localdRq16.bb(localdRq21);
    localdRq21.brn();
    aId localaId11 = aId.checkOut();
    localaId11.setHgap((short)2);
    localaId11.setAlign(aFG.ecl);
    localdRq21.bb(localaId11);
    localaId11.brn();
    localaId11.rV();
    NK localNK6 = NK.checkOut();
    localNK6.setElementMap(localcpa1);
    localNK6.setName("havenWorldOverCatalogEntry");
    localNK6.setAttribute("visible");
    localNK6.setField("sidoaNeed");
    localdRq21.bb(localNK6);
    localNK6.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa1);
    localNK6.bb(localanQ2);
    localanQ2.brn();
    anE localanE2 = new anE();
    localanE2.aJ();
    localanE2.setElementMap(localcpa1);
    localanQ2.bb(localanE2);
    localanE2.brn();
    localanE2.rV();
    localanQ2.rV();
    localNK6.rV();
    cWk localcWk5 = new cWk();
    localcWk5.aJ();
    localcWk5.setElementMap(localcpa1);
    localcWk5.setStyle("whiteBold");
    localcWk5.setExpandable(false);
    localdRq21.bb(localcWk5);
    localcWk5.brn();
    dpm localdpm5 = new dpm();
    localdpm5.aJ();
    localdpm5.setElementMap(localcpa1);
    localdpm5.setAlign(aFG.eck);
    localcWk5.bb(localdpm5);
    localdpm5.brn();
    localdpm5.rV();
    NK localNK7 = NK.checkOut();
    localNK7.setElementMap(localcpa1);
    localNK7.setName("havenWorldOverCatalogEntry");
    localNK7.setAttribute("text");
    localNK7.setField("sidoaNeed");
    localcWk5.bb(localNK7);
    localNK7.brn();
    localNK7.rV();
    localcWk5.rV();
    a(localdRq21);
    localdRq21.rV();
    b(localdRq16);
    d(localdRq16);
    localdRq16.rV();
    localdRq15.rV();
    localdRq13.rV();
    e(localdRq12);
    localdRq12.rV();
    f(localdRq11);
    g(localdRq11);
    h(localdRq11);
    i(localdRq11);
    localdRq11.rV();
    this.X.pop();
    localcpa1 = (cpa)this.X.peek();
    localanG.rV();
    j(localdRq9);
    k(localdRq9);
    q(localdRq9);
    localdRq9.rV();
    localdRq7.rV();
    localdRq2.rV();
    r(localbpn);
    s(localbpn);
    t(localbpn);
    localbpn.rV();
    return localbpn;
  }

  public bdj a(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setStyle("Sidoa");
    localczv.setExpandable(false);
    parambdj.bb(localczv);
    localczv.brn();
    localczv.rV();
    return localczv;
  }

  public bdj b(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq = dRq.checkOut();
    localdRq.setElementMap(localcpa);
    localdRq.setExpandable(false);
    localdRq.setVisible(false);
    parambdj.bb(localdRq);
    localdRq.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setName("havenWorldOverCatalogEntry");
    localNK1.setAttribute("visible");
    localNK1.setField("buildDelay");
    localdRq.bb(localNK1);
    localNK1.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localNK1.bb(localanQ);
    localanQ.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localanQ.bb(localanE);
    localanE.brn();
    localanE.rV();
    localanQ.rV();
    localNK1.rV();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.ecl);
    localdRq.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    aId localaId = aId.checkOut();
    localaId.setHgap((short)2);
    localdRq.bb(localaId);
    localaId.brn();
    localaId.rV();
    caF localcaF = new caF();
    localcaF.aJ();
    localcaF.setElementMap(localcpa);
    localcaF.setStyle("11Light");
    localcaF.setExpandable(false);
    localdRq.bb(localcaF);
    localcaF.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("havenWorldOverCatalogEntry");
    localNK2.setAttribute("text");
    localNK2.setField("buildDelay");
    localcaF.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localcaF.rV();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setStyle("SmallTimer");
    localczv.setExpandable(false);
    localdRq.bb(localczv);
    localczv.brn();
    localczv.rV();
    localdRq.rV();
    return localdRq;
  }

  public bdj d(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq = dRq.checkOut();
    localdRq.setElementMap(localcpa);
    localdRq.setExpandable(false);
    parambdj.bb(localdRq);
    localdRq.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setName("havenWorldOverCatalogEntry");
    localNK1.setAttribute("visible");
    localNK1.setField("surface");
    localdRq.bb(localNK1);
    localNK1.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localNK1.bb(localanQ);
    localanQ.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localanQ.bb(localanE);
    localanE.brn();
    localanE.rV();
    localanQ.rV();
    localNK1.rV();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.ecl);
    localdRq.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    aId localaId = aId.checkOut();
    localaId.setHgap((short)2);
    localdRq.bb(localaId);
    localaId.brn();
    localaId.rV();
    caF localcaF = new caF();
    localcaF.aJ();
    localcaF.setElementMap(localcpa);
    localcaF.setStyle("11Light");
    localdRq.bb(localcaF);
    localcaF.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("havenWorldOverCatalogEntry");
    localNK2.setAttribute("text");
    localNK2.setField("surface");
    localcaF.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localcaF.rV();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setStyle("IconSurface");
    localczv.setExpandable(false);
    localdRq.bb(localczv);
    localczv.brn();
    localczv.rV();
    localdRq.rV();
    return localdRq;
  }

  public bdj e(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    dRq localdRq2 = localdRq1;
    Jg localJg = localdRq2.getAppearance();
    localJg.setElementMap(localcpa);
    localdRq1.bb(localJg);
    localJg.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(0, 0, 0, 0));
    localJg.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg.rV();
    aId localaId = aId.checkOut();
    localaId.setAlign(aFG.ecl);
    localdRq1.bb(localaId);
    localaId.brn();
    localaId.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj f(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(false);
    localaId.setAlign(aFG.ech);
    localdRq1.bb(localaId);
    localaId.brn();
    localaId.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setExpandable(false);
    localdRq2.setStyle("lineSeparator2");
    localdRq2.setPrefSize(new Or(50, 1));
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(5, 20, 5, 20));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    localdRq2.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setExpandable(false);
    localcWk1.setStyle("narrow12");
    localcWk1.setMinWidth(1);
    localcWk1.setMaxWidth(230);
    localdRq1.bb(localcWk1);
    localcWk1.brn();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.ecj);
    localcWk1.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    cWk localcWk2 = localcWk1;
    Jg localJg2 = localcWk2.getAppearance();
    localJg2.setElementMap(localcpa);
    localcWk1.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 0, 0, 0));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    cAf localcAf = cAf.checkOut();
    localcAf.setElementMap(localcpa);
    localcAf.setColor(new bNa(0.98F, 0.77F, 0.0F, 1.0F));
    localJg2.bb(localcAf);
    localcAf.brn();
    localcAf.rV();
    localJg2.rV();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setName("havenWorldOverCatalogEntry");
    localNK.setAttribute("text");
    localNK.setField("description");
    localcWk1.bb(localNK);
    localNK.brn();
    localNK.rV();
    localcWk1.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj g(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setName("havenWorldOverCatalogEntry");
    localNK1.setAttribute("visible");
    localNK1.setField("effects");
    localdRq1.bb(localNK1);
    localNK1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localNK1.bb(localanQ1);
    localanQ1.brn();
    anE localanE1 = new anE();
    localanE1.aJ();
    localanE1.setElementMap(localcpa);
    localanQ1.bb(localanE1);
    localanE1.brn();
    localanE1.rV();
    localanQ1.rV();
    localNK1.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localaId1.setAlign(aFG.ech);
    localdRq1.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setExpandable(false);
    localdRq2.setStyle("lineSeparator2");
    localdRq2.setPrefSize(new Or(50, 1));
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(5, 20, 5, 20));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    localdRq2.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setExpandable(false);
    localdRq1.bb(localdRq4);
    localdRq4.brn();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa);
    localdpm1.setAlign(aFG.ecj);
    localdRq4.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    aId localaId2 = aId.checkOut();
    localaId2.setAlign(aFG.ecj);
    localdRq4.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setExpandable(false);
    String str1 = "%effects%";
    str1 = str1.replace("%effects%", cBQ.cxL().mL("effects"));
    localcaF1.setText(str1);
    localcaF1.setStyle("11BoldLight");
    localdRq4.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg2 = localcaF2.getAppearance();
    localJg2.setElementMap(localcpa);
    localcaF1.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 5, 5, 0));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    localcaF1.rV();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setExpandable(false);
    String str2 = "%effects.guildMembers%";
    str2 = str2.replace("%effects.guildMembers%", cBQ.cxL().mL("effects.guildMembers"));
    localcaF3.setText(str2);
    localcaF3.setStyle("11BoldLight");
    localdRq4.bb(localcaF3);
    localcaF3.brn();
    localcaF3.rV();
    localdRq4.rV();
    at localat = new at();
    localat.aJ();
    localat.setElementMap(localcpa);
    localat.setHorizontal(false);
    localdRq1.bb(localat);
    localat.brn();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa);
    localdpm2.setAlign(aFG.ecj);
    localat.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("havenWorldOverCatalogEntry");
    localNK2.setAttribute("content");
    localNK2.setField("effects");
    localat.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    eR localeR = new eR();
    localeR.aJ();
    localeR.setElementMap(localcpa);
    localat.bb(localeR);
    localeR.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localeR.bb(localanQ2);
    localanQ2.brn();
    bxx localbxx = new bxx();
    localbxx.aJ();
    localbxx.setElementMap(localcpa);
    localanQ2.bb(localbxx);
    localbxx.brn();
    anE localanE2 = new anE();
    localanE2.aJ();
    localanE2.setElementMap(localcpa);
    localbxx.bb(localanE2);
    localanE2.brn();
    localanE2.rV();
    localbxx.rV();
    localanQ2.rV();
    dRq localdRq5 = dRq.checkOut();
    localdRq5.setElementMap(localcpa);
    localeR.bb(localdRq5);
    localdRq5.brn();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("white11");
    localcWk1.setMultiline(true);
    localcWk1.setMinWidth(250);
    localcWk1.setMaxWidth(250);
    localcWk1.setExpandable(false);
    localdRq5.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg3 = localcWk2.getAppearance();
    localJg3.setElementMap(localcpa);
    localcWk1.bb(localJg3);
    localJg3.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 5, 0, 0));
    localJg3.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg3.rV();
    aaE localaaE = new aaE();
    localaaE.aJ();
    localaaE.setElementMap(localcpa);
    localaaE.setAttribute("text");
    localcWk1.bb(localaaE);
    localaaE.brn();
    localaaE.rV();
    localcWk1.rV();
    localdRq5.rV();
    localeR.rV();
    localat.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj h(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setName("havenWorldOverCatalogEntry");
    localNK1.setAttribute("visible");
    localNK1.setField("evolutionName");
    localdRq1.bb(localNK1);
    localNK1.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localNK1.bb(localanQ);
    localanQ.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localanQ.bb(localanE);
    localanE.brn();
    localanE.rV();
    localanQ.rV();
    localNK1.rV();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(false);
    localaId.setAlign(aFG.ech);
    localdRq1.bb(localaId);
    localaId.brn();
    localaId.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setExpandable(false);
    localdRq2.setStyle("lineSeparator2");
    localdRq2.setPrefSize(new Or(50, 1));
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(5, 20, 5, 20));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    localdRq2.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setExpandable(false);
    String str = "%desc.buildingEvolution%";
    str = str.replace("%desc.buildingEvolution%", cBQ.cxL().mL("desc.buildingEvolution"));
    localcaF1.setText(str);
    localcaF1.setStyle("11BoldLight");
    localdRq1.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg2 = localcaF2.getAppearance();
    localJg2.setElementMap(localcpa);
    localcaF1.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 5, 5, 0));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    localcaF1.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("white11");
    localcWk1.setMinWidth(1);
    localcWk1.setMaxWidth(225);
    localcWk1.setExpandable(false);
    localdRq1.bb(localcWk1);
    localcWk1.brn();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.ecj);
    localcWk1.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    cWk localcWk2 = localcWk1;
    Jg localJg3 = localcWk2.getAppearance();
    localJg3.setElementMap(localcpa);
    localcWk1.bb(localJg3);
    localJg3.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 10, 5, 0));
    localJg3.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg3.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("havenWorldOverCatalogEntry");
    localNK2.setAttribute("text");
    localNK2.setField("evolutionName");
    localcWk1.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localcWk1.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj i(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("visible");
    localNK1.setName("havenWorldOverCatalogEntry");
    localNK1.setField("conditions");
    localdRq1.bb(localNK1);
    localNK1.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localNK1.bb(localanQ);
    localanQ.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localanQ.bb(localanE);
    localanE.brn();
    localanE.rV();
    localanQ.rV();
    localNK1.rV();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(false);
    localaId.setAlign(aFG.ech);
    localdRq1.bb(localaId);
    localaId.brn();
    localaId.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setExpandable(false);
    localdRq2.setStyle("lineSeparator2");
    localdRq2.setPrefSize(new Or(50, 1));
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(5, 20, 5, 20));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    localdRq2.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setExpandable(false);
    String str = "%requirements%";
    str = str.replace("%requirements%", cBQ.cxL().mL("requirements"));
    localcaF1.setText(str);
    localcaF1.setStyle("11BoldLight");
    localdRq1.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg2 = localcaF2.getAppearance();
    localJg2.setElementMap(localcpa);
    localcaF1.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 5, 5, 0));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    localcaF1.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("white11");
    localcWk1.setMinWidth(1);
    localcWk1.setMaxWidth(225);
    localcWk1.setExpandable(false);
    localdRq1.bb(localcWk1);
    localcWk1.brn();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.ecj);
    localcWk1.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    cWk localcWk2 = localcWk1;
    Jg localJg3 = localcWk2.getAppearance();
    localJg3.setElementMap(localcpa);
    localcWk1.bb(localJg3);
    localJg3.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 10, 5, 0));
    localJg3.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg3.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("havenWorldOverCatalogEntry");
    localNK2.setAttribute("text");
    localNK2.setField("conditions");
    localcWk1.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localcWk1.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj j(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setStyle("ScrollString");
    parambdj.bb(localdRq1);
    localdRq1.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setAlign(ajb.dia);
    localcwP.setSize(new Or(10, 100.0F));
    localcwP.setXOffset(-5);
    localdRq1.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    dRq localdRq2 = localdRq1;
    Jg localJg = localdRq2.getAppearance();
    localJg.setElementMap(localcpa);
    localdRq1.bb(localJg);
    localJg.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(30, 0, 35, 0));
    localJg.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj k(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setStyle("Encyclopedia");
    localdRq1.setExpandable(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localcwP1.setAlign(ajb.dhZ);
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    dRq localdRq2 = localdRq1;
    Jg localJg1 = localdRq2.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq1.bb(localJg1);
    localJg1.brn();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(0, 10, 0, 0));
    localJg1.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(17, 3, 20, 0));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    czO localczO1 = new czO();
    localczO1.aJ();
    localczO1.setAdaptToContentSize(true);
    localdRq1.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq3.setStyle("tiledScroll");
    localdRq3.setPrefSize(new Or(0, 500));
    localdRq1.bb(localdRq3);
    localdRq3.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.dhZ);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localdRq3.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    dRq localdRq4 = localdRq3;
    Jg localJg2 = localdRq4.getAppearance();
    localJg2.setElementMap(localcpa);
    localdRq3.bb(localJg2);
    localJg2.brn();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(5, 10, 0, 0));
    localJg2.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 10, 0, 20));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setAlign(aFG.ech);
    localaId1.setHorizontal(false);
    localdRq3.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dRq localdRq5 = dRq.checkOut();
    localdRq5.setElementMap(localcpa);
    localdRq5.setExpandable(false);
    localdRq5.setPrefSize(new Or(0, 130));
    localdRq3.bb(localdRq5);
    localdRq5.brn();
    czO localczO2 = new czO();
    localczO2.aJ();
    localczO2.setAdaptToContentSize(true);
    localdRq5.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq6.setStyle("EncyclopediaSplashTitle");
    localdRq6.setPrefSize(new Or(0, 30));
    localdRq6.setExpandable(false);
    localdRq5.bb(localdRq6);
    localdRq6.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setAlign(ajb.dhT);
    localcwP3.setSize(new Or(100.0F, -2));
    localdRq6.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    dRq localdRq7 = localdRq6;
    Jg localJg3 = localdRq7.getAppearance();
    localJg3.setElementMap(localcpa);
    localdRq6.bb(localJg3);
    localJg3.brn();
    cuR localcuR3 = new cuR();
    localcuR3.aJ();
    localcuR3.setElementMap(localcpa);
    localcuR3.setInsets(new Insets(0, 0, 3, 0));
    localJg3.bb(localcuR3);
    localcuR3.brn();
    localcuR3.rV();
    localJg3.rV();
    aId localaId2 = aId.checkOut();
    localaId2.setAlign(aFG.eck);
    localdRq6.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setDisplaySize(new Or(83, 39));
    localczv1.setStyle("NationLeftDecorator");
    localczv1.setExpandable(false);
    localdRq6.bb(localczv1);
    localczv1.brn();
    localczv1.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("StyledBold16White");
    localcWk1.setNonBlocking(true);
    localcWk1.setExpandable(false);
    localcWk1.setMinWidth(1);
    localcWk1.setMaxWidth(250);
    localdRq6.bb(localcWk1);
    localcWk1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("text");
    localNK1.setField("havenWorldName");
    localNK1.setName("havenWorld");
    localcWk1.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    localcWk1.rV();
    czv localczv2 = new czv();
    localczv2.aJ();
    localczv2.setElementMap(localcpa);
    localczv2.setDisplaySize(new Or(83, 39));
    localczv2.setStyle("NationRightDecorator");
    localczv2.setExpandable(false);
    localdRq6.bb(localczv2);
    localczv2.brn();
    localczv2.rV();
    localdRq6.rV();
    dRq localdRq8 = dRq.checkOut();
    localdRq8.setElementMap(localcpa);
    localdRq5.bb(localdRq8);
    localdRq8.brn();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setAlign(ajb.dif);
    localdRq8.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    aId localaId3 = aId.checkOut();
    localaId3.setHorizontal(false);
    localaId3.setAlign(aFG.ech);
    localaId3.setVgap((short)8);
    localdRq8.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    dRq localdRq9 = localdRq8;
    Jg localJg4 = localdRq9.getAppearance();
    localJg4.setElementMap(localcpa);
    localdRq8.bb(localJg4);
    localJg4.brn();
    cuR localcuR4 = new cuR();
    localcuR4.aJ();
    localcuR4.setElementMap(localcpa);
    localcuR4.setInsets(new Insets(0, 5, 0, 10));
    localJg4.bb(localcuR4);
    localcuR4.brn();
    localcuR4.rV();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 150, 0, 0));
    localJg4.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg4.rV();
    dRq localdRq10 = dRq.checkOut();
    localdRq10.setElementMap(localcpa);
    localdRq10.setExpandable(false);
    localdRq8.bb(localdRq10);
    localdRq10.brn();
    czO localczO3 = new czO();
    localczO3.aJ();
    localczO3.setAdaptToContentSize(true);
    localdRq10.bb(localczO3);
    localczO3.brn();
    localczO3.rV();
    dRq localdRq11 = dRq.checkOut();
    localdRq11.setElementMap(localcpa);
    localdRq11.setStyle("TiledScrollCenter");
    localdRq11.setPrefSize(new Or(0, 20));
    localdRq10.bb(localdRq11);
    localdRq11.brn();
    cwP localcwP5 = new cwP();
    localcwP5.aJ();
    localcwP5.setElementMap(localcpa);
    localcwP5.setAlign(ajb.dhY);
    localcwP5.setSize(new Or(100.0F, -2));
    localdRq11.bb(localcwP5);
    localcwP5.brn();
    localcwP5.rV();
    localdRq11.rV();
    czv localczv3 = new czv();
    localczv3.aJ();
    localczv3.setElementMap(localcpa);
    localczv3.setStyle("TiledScrollTop");
    localczv3.setDisplaySize(new Or(260, 4));
    localdRq10.bb(localczv3);
    localczv3.brn();
    cwP localcwP6 = new cwP();
    localcwP6.aJ();
    localcwP6.setElementMap(localcpa);
    localcwP6.setAlign(ajb.dhR);
    localczv3.bb(localcwP6);
    localcwP6.brn();
    localcwP6.rV();
    localczv3.rV();
    czv localczv4 = new czv();
    localczv4.aJ();
    localczv4.setElementMap(localcpa);
    localczv4.setStyle("TiledScrollBottom");
    localczv4.setDisplaySize(new Or(260, 4));
    localdRq10.bb(localczv4);
    localczv4.brn();
    cwP localcwP7 = new cwP();
    localcwP7.aJ();
    localcwP7.setElementMap(localcpa);
    localcwP7.setAlign(ajb.did);
    localczv4.bb(localcwP7);
    localcwP7.brn();
    localcwP7.rV();
    localczv4.rV();
    dRq localdRq12 = dRq.checkOut();
    localdRq12.setElementMap(localcpa);
    localdRq10.bb(localdRq12);
    localdRq12.brn();
    cwP localcwP8 = new cwP();
    localcwP8.aJ();
    localcwP8.setElementMap(localcpa);
    localcwP8.setAlign(ajb.dhZ);
    localcwP8.setSize(new Or(100.0F, -2));
    localdRq12.bb(localcwP8);
    localcwP8.brn();
    localcwP8.rV();
    aId localaId4 = aId.checkOut();
    localaId4.setAlign(aFG.ecj);
    localdRq12.bb(localaId4);
    localaId4.brn();
    localaId4.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("darkBold");
    localcaF1.setExpandable(false);
    String str1 = "%ownerWithComas%";
    str1 = str1.replace("%ownerWithComas%", cBQ.cxL().mL("ownerWithComas"));
    localcaF1.setText(str1);
    localdRq12.bb(localcaF1);
    localcaF1.brn();
    localcaF1.rV();
    cWk localcWk2 = new cWk();
    localcWk2.aJ();
    localcWk2.setElementMap(localcpa);
    localcWk2.setStyle("darkTitle");
    localcWk2.setExpandable(false);
    localdRq12.bb(localcWk2);
    localcWk2.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setAttribute("text");
    localNK2.setField("guildName");
    localNK2.setName("havenWorld");
    localcWk2.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localcWk2.rV();
    localdRq12.rV();
    localdRq10.rV();
    dRq localdRq13 = dRq.checkOut();
    localdRq13.setElementMap(localcpa);
    localdRq13.setExpandable(false);
    localdRq8.bb(localdRq13);
    localdRq13.brn();
    czO localczO4 = new czO();
    localczO4.aJ();
    localczO4.setAdaptToContentSize(true);
    localdRq13.bb(localczO4);
    localczO4.brn();
    localczO4.rV();
    dRq localdRq14 = dRq.checkOut();
    localdRq14.setElementMap(localcpa);
    localdRq14.setStyle("TiledScrollCenter");
    localdRq14.setPrefSize(new Or(0, 20));
    localdRq13.bb(localdRq14);
    localdRq14.brn();
    cwP localcwP9 = new cwP();
    localcwP9.aJ();
    localcwP9.setElementMap(localcpa);
    localcwP9.setAlign(ajb.dhY);
    localcwP9.setSize(new Or(100.0F, -2));
    localdRq14.bb(localcwP9);
    localcwP9.brn();
    localcwP9.rV();
    localdRq14.rV();
    czv localczv5 = new czv();
    localczv5.aJ();
    localczv5.setElementMap(localcpa);
    localczv5.setStyle("TiledScrollTop");
    localczv5.setDisplaySize(new Or(260, 4));
    localdRq13.bb(localczv5);
    localczv5.brn();
    cwP localcwP10 = new cwP();
    localcwP10.aJ();
    localcwP10.setElementMap(localcpa);
    localcwP10.setAlign(ajb.dhR);
    localczv5.bb(localcwP10);
    localcwP10.brn();
    localcwP10.rV();
    localczv5.rV();
    czv localczv6 = new czv();
    localczv6.aJ();
    localczv6.setElementMap(localcpa);
    localczv6.setStyle("TiledScrollBottom");
    localczv6.setDisplaySize(new Or(260, 4));
    localdRq13.bb(localczv6);
    localczv6.brn();
    cwP localcwP11 = new cwP();
    localcwP11.aJ();
    localcwP11.setElementMap(localcpa);
    localcwP11.setAlign(ajb.did);
    localczv6.bb(localcwP11);
    localcwP11.brn();
    localcwP11.rV();
    localczv6.rV();
    dRq localdRq15 = dRq.checkOut();
    localdRq15.setElementMap(localcpa);
    localdRq13.bb(localdRq15);
    localdRq15.brn();
    cwP localcwP12 = new cwP();
    localcwP12.aJ();
    localcwP12.setElementMap(localcpa);
    localcwP12.setAlign(ajb.dhZ);
    localcwP12.setSize(new Or(100.0F, -2));
    localdRq15.bb(localcwP12);
    localcwP12.brn();
    localcwP12.rV();
    aId localaId5 = aId.checkOut();
    localaId5.setAlign(aFG.ecj);
    localdRq15.bb(localaId5);
    localaId5.brn();
    localaId5.rV();
    caF localcaF2 = new caF();
    localcaF2.aJ();
    localcaF2.setElementMap(localcpa);
    localcaF2.setStyle("darkBold");
    localcaF2.setExpandable(false);
    String str2 = "%actualRank%";
    str2 = str2.replace("%actualRank%", cBQ.cxL().mL("actualRank"));
    localcaF2.setText(str2);
    localdRq15.bb(localcaF2);
    localcaF2.brn();
    localcaF2.rV();
    cWk localcWk3 = new cWk();
    localcWk3.aJ();
    localcWk3.setElementMap(localcpa);
    localcWk3.setStyle("darkTitle");
    localcWk3.setExpandable(false);
    localdRq15.bb(localcWk3);
    localcWk3.brn();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setAttribute("text");
    localNK3.setField("guildRank");
    localNK3.setName("havenWorld");
    localcWk3.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    localcWk3.rV();
    localdRq15.rV();
    localdRq13.rV();
    dRq localdRq16 = dRq.checkOut();
    localdRq16.setElementMap(localcpa);
    localdRq16.setExpandable(false);
    localdRq8.bb(localdRq16);
    localdRq16.brn();
    czO localczO5 = new czO();
    localczO5.aJ();
    localczO5.setAdaptToContentSize(true);
    localdRq16.bb(localczO5);
    localczO5.brn();
    localczO5.rV();
    dRq localdRq17 = dRq.checkOut();
    localdRq17.setElementMap(localcpa);
    localdRq17.setStyle("TiledScrollCenter");
    localdRq17.setPrefSize(new Or(0, 20));
    localdRq16.bb(localdRq17);
    localdRq17.brn();
    cwP localcwP13 = new cwP();
    localcwP13.aJ();
    localcwP13.setElementMap(localcpa);
    localcwP13.setAlign(ajb.dhY);
    localcwP13.setSize(new Or(100.0F, -2));
    localdRq17.bb(localcwP13);
    localcwP13.brn();
    localcwP13.rV();
    localdRq17.rV();
    czv localczv7 = new czv();
    localczv7.aJ();
    localczv7.setElementMap(localcpa);
    localczv7.setStyle("TiledScrollTop");
    localczv7.setDisplaySize(new Or(260, 4));
    localdRq16.bb(localczv7);
    localczv7.brn();
    cwP localcwP14 = new cwP();
    localcwP14.aJ();
    localcwP14.setElementMap(localcpa);
    localcwP14.setAlign(ajb.dhR);
    localczv7.bb(localcwP14);
    localcwP14.brn();
    localcwP14.rV();
    localczv7.rV();
    czv localczv8 = new czv();
    localczv8.aJ();
    localczv8.setElementMap(localcpa);
    localczv8.setStyle("TiledScrollBottom");
    localczv8.setDisplaySize(new Or(260, 4));
    localdRq16.bb(localczv8);
    localczv8.brn();
    cwP localcwP15 = new cwP();
    localcwP15.aJ();
    localcwP15.setElementMap(localcpa);
    localcwP15.setAlign(ajb.did);
    localczv8.bb(localcwP15);
    localcwP15.brn();
    localcwP15.rV();
    localczv8.rV();
    dRq localdRq18 = dRq.checkOut();
    localdRq18.setElementMap(localcpa);
    localdRq16.bb(localdRq18);
    localdRq18.brn();
    cwP localcwP16 = new cwP();
    localcwP16.aJ();
    localcwP16.setElementMap(localcpa);
    localcwP16.setAlign(ajb.dhZ);
    localcwP16.setSize(new Or(100.0F, -2));
    localdRq18.bb(localcwP16);
    localcwP16.brn();
    localcwP16.rV();
    aId localaId6 = aId.checkOut();
    localaId6.setAlign(aFG.ecj);
    localdRq18.bb(localaId6);
    localaId6.brn();
    localaId6.rV();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setStyle("darkBold");
    localcaF3.setExpandable(false);
    String str3 = "%actualConquestRank%";
    str3 = str3.replace("%actualConquestRank%", cBQ.cxL().mL("actualConquestRank"));
    localcaF3.setText(str3);
    localdRq18.bb(localcaF3);
    localcaF3.brn();
    localcaF3.rV();
    cWk localcWk4 = new cWk();
    localcWk4.aJ();
    localcWk4.setElementMap(localcpa);
    localcWk4.setStyle("darkTitle");
    localcWk4.setExpandable(false);
    localdRq18.bb(localcWk4);
    localcWk4.brn();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa);
    localNK4.setAttribute("text");
    localNK4.setField("conquestRank");
    localNK4.setName("havenWorld");
    localcWk4.bb(localNK4);
    localNK4.brn();
    localNK4.rV();
    localcWk4.rV();
    localdRq18.rV();
    localdRq16.rV();
    localdRq8.rV();
    l(localdRq5);
    localdRq5.rV();
    m(localdRq3);
    n(localdRq3);
    o(localdRq3);
    p(localdRq3);
    localdRq3.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj l(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setStyle("HavenWorldMini");
    parambdj.bb(localczv);
    localczv.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setAlign(ajb.dhR);
    localcwP.setYOffset(-10);
    localczv.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localczv.rV();
    return localczv;
  }

  public bdj m(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    localdRq1.setNonBlocking(false);
    csA localcsA = new csA();
    localcsA.hg("wakfu.havenWorldPanel:toggleOpenBuildingList");
    localdRq1.setOnClick(localcsA);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    czO localczO = new czO();
    localczO.aJ();
    localczO.setAdaptToContentSize(true);
    localdRq1.bb(localczO);
    localczO.brn();
    localczO.rV();
    dRq localdRq2 = localdRq1;
    Jg localJg1 = localdRq2.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq1.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(15, 0, 0, 0));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setStyle("scrollTitleBar");
    localdRq1.bb(localczv1);
    localczv1.brn();
    czv localczv2 = localczv1;
    Jg localJg2 = localczv2.getAppearance();
    localJg2.setElementMap(localcpa);
    localJg2.setModulationColor(new bNa(1.0F, 1.0F, 1.0F, 0.8F));
    localczv1.bb(localJg2);
    localJg2.brn();
    localJg2.rV();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setAlign(ajb.dhZ);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localczv1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    localczv1.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq3.setExpandable(false);
    localdRq1.bb(localdRq3);
    localdRq3.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.dhZ);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localdRq3.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    aId localaId = aId.checkOut();
    localaId.setAlign(aFG.ecj);
    localdRq3.bb(localaId);
    localaId.brn();
    localaId.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("WhiteTitle");
    localcaF1.setEnableShrinking(false);
    localcaF1.setExpandable(false);
    String str = "%buildingsBuiltList%";
    str = str.replace("%buildingsBuiltList%", cBQ.cxL().mL("buildingsBuiltList"));
    localcaF1.setText(str);
    localdRq3.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg3 = localcaF2.getAppearance();
    localJg3.setElementMap(localcpa);
    ((cwJ)localJg3).setAlignment(aFG.ecj);
    localcaF1.bb(localJg3);
    localJg3.brn();
    localJg3.rV();
    caF localcaF3 = localcaF1;
    Jg localJg4 = localcaF3.getAppearance();
    localJg4.setElementMap(localcpa);
    localcaF1.bb(localJg4);
    localJg4.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 30, 0, 0));
    localJg4.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg4.rV();
    localcaF1.rV();
    czv localczv3 = new czv();
    localczv3.aJ();
    localczv3.setElementMap(localcpa);
    localczv3.setExpandable(false);
    localdRq3.bb(localczv3);
    localczv3.brn();
    czv localczv4 = localczv3;
    Jg localJg5 = localczv4.getAppearance();
    localJg5.setElementMap(localcpa);
    localczv3.bb(localJg5);
    localJg5.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 10, 0, 0));
    localJg5.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg5.rV();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setAttribute("style");
    localNK.setField("buildingsOpenned");
    localNK.setName("havenWorld");
    localczv3.bb(localNK);
    localNK.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localanQ.setValue("DownArrowMarket");
    localanQ.setElseValue("RightArrowMarket");
    localNK.bb(localanQ);
    localanQ.brn();
    cOk localcOk = new cOk();
    localcOk.aJ();
    localcOk.setElementMap(localcpa);
    localanQ.bb(localcOk);
    localcOk.brn();
    localcOk.rV();
    localanQ.rV();
    localNK.rV();
    localczv3.rV();
    localdRq3.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj n(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    ccG localccG = new ccG();
    localccG.aJ();
    localccG.setElementMap(localcpa);
    localccG.setCellSize(new Or(64, 64));
    localccG.setAutoIdealSize(true);
    localccG.setIdealSizeMaxColumns(6);
    localccG.setIdealSizeMinColumns(1);
    localccG.setIdealSizeMinRows(1);
    localccG.setIdealSizeMaxRows(30);
    localccG.setExpandable(false);
    localccG.setVisible(false);
    parambdj.bb(localccG);
    localccG.brn();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.ecj);
    localccG.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("content");
    localNK1.setField("buildingList");
    localNK1.setName("havenWorld");
    localccG.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setAttribute("visible");
    localNK2.setField("buildingsOpenned");
    localNK2.setName("havenWorld");
    localccG.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    eR localeR1 = new eR();
    localeR1.aJ();
    localeR1.setElementMap(localcpa);
    localccG.bb(localeR1);
    localeR1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localeR1.bb(localanQ1);
    localanQ1.brn();
    bxx localbxx1 = new bxx();
    localbxx1.aJ();
    localbxx1.setElementMap(localcpa);
    localanQ1.bb(localbxx1);
    localbxx1.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localbxx1.bb(localanE);
    localanE.brn();
    localanE.rV();
    localbxx1.rV();
    localanQ1.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localeR1.bb(localdRq1);
    localdRq1.brn();
    String str = "element";
    avo localavo = new avo();
    localavo.aJ();
    localavo.setElementMap(localcpa);
    if ((localcpa != null) && (str != null))
      localcpa.a(str, localavo);
    localdRq1.bb(localavo);
    localavo.brn();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("value");
    localavo.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    localavo.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setExpandable(false);
    localdRq2.setPrefSize(new Or(50, 50));
    localdRq2.setNonBlocking(false);
    DY localDY = new DY();
    localDY.hg("wakfu.havenWorldPanel:onMouseOutElement(element,elementDetailPopup)");
    localdRq2.setOnMouseExit(localDY);
    bDy localbDy = new bDy();
    localbDy.hg("wakfu.havenWorldPanel:onMouseOverElement(element,elementDetailPopup)");
    localdRq2.setOnMouseEnter(localbDy);
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setNonBlocking(true);
    localczv.setDisplaySize(new Or(50, 50));
    localdRq2.bb(localczv);
    localczv.brn();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv.bb(localaAR);
    localaAR.brn();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("texture");
    localaaE2.setField("iconUrl");
    localaAR.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    localaAR.rV();
    localczv.rV();
    localdRq2.rV();
    localdRq1.rV();
    localeR1.rV();
    eR localeR2 = new eR();
    localeR2.aJ();
    localeR2.setElementMap(localcpa);
    localccG.bb(localeR2);
    localeR2.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localeR2.bb(localanQ2);
    localanQ2.brn();
    bxx localbxx2 = new bxx();
    localbxx2.aJ();
    localbxx2.setElementMap(localcpa);
    localanQ2.bb(localbxx2);
    localbxx2.brn();
    aIB localaIB = new aIB();
    localaIB.aJ();
    localaIB.setElementMap(localcpa);
    localbxx2.bb(localaIB);
    localaIB.brn();
    localaIB.rV();
    localbxx2.rV();
    localanQ2.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localeR2.bb(localdRq3);
    localdRq3.brn();
    localdRq3.rV();
    localeR2.rV();
    localccG.rV();
    return localccG;
  }

  public bdj o(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    localdRq1.setNonBlocking(false);
    csA localcsA = new csA();
    localcsA.hg("wakfu.havenWorldPanel:toggleOpenEvolutingBuildingList");
    localdRq1.setOnClick(localcsA);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    czO localczO = new czO();
    localczO.aJ();
    localczO.setAdaptToContentSize(true);
    localdRq1.bb(localczO);
    localczO.brn();
    localczO.rV();
    dRq localdRq2 = localdRq1;
    Jg localJg1 = localdRq2.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq1.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(15, 0, 0, 0));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setStyle("scrollTitleBar");
    localdRq1.bb(localczv1);
    localczv1.brn();
    czv localczv2 = localczv1;
    Jg localJg2 = localczv2.getAppearance();
    localJg2.setElementMap(localcpa);
    localJg2.setModulationColor(new bNa(1.0F, 1.0F, 1.0F, 0.8F));
    localczv1.bb(localJg2);
    localJg2.brn();
    localJg2.rV();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setAlign(ajb.dhZ);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localczv1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    localczv1.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq3.setExpandable(false);
    localdRq1.bb(localdRq3);
    localdRq3.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.dhZ);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localdRq3.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    aId localaId = aId.checkOut();
    localaId.setAlign(aFG.ecj);
    localdRq3.bb(localaId);
    localaId.brn();
    localaId.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("WhiteTitle");
    localcaF1.setEnableShrinking(false);
    localcaF1.setExpandable(false);
    String str = "%evolutingBuildingsList%";
    str = str.replace("%evolutingBuildingsList%", cBQ.cxL().mL("evolutingBuildingsList"));
    localcaF1.setText(str);
    localdRq3.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg3 = localcaF2.getAppearance();
    localJg3.setElementMap(localcpa);
    ((cwJ)localJg3).setAlignment(aFG.ecj);
    localcaF1.bb(localJg3);
    localJg3.brn();
    localJg3.rV();
    caF localcaF3 = localcaF1;
    Jg localJg4 = localcaF3.getAppearance();
    localJg4.setElementMap(localcpa);
    localcaF1.bb(localJg4);
    localJg4.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 30, 0, 0));
    localJg4.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg4.rV();
    localcaF1.rV();
    czv localczv3 = new czv();
    localczv3.aJ();
    localczv3.setElementMap(localcpa);
    localczv3.setExpandable(false);
    localdRq3.bb(localczv3);
    localczv3.brn();
    czv localczv4 = localczv3;
    Jg localJg5 = localczv4.getAppearance();
    localJg5.setElementMap(localcpa);
    localczv3.bb(localJg5);
    localJg5.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 10, 0, 0));
    localJg5.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg5.rV();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setAttribute("style");
    localNK.setField("evolutingBuildingsOpenned");
    localNK.setName("havenWorld");
    localczv3.bb(localNK);
    localNK.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localanQ.setValue("DownArrowMarket");
    localanQ.setElseValue("RightArrowMarket");
    localNK.bb(localanQ);
    localanQ.brn();
    cOk localcOk = new cOk();
    localcOk.aJ();
    localcOk.setElementMap(localcpa);
    localanQ.bb(localcOk);
    localcOk.brn();
    localcOk.rV();
    localanQ.rV();
    localNK.rV();
    localczv3.rV();
    localdRq3.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj p(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    ccG localccG = new ccG();
    localccG.aJ();
    localccG.setElementMap(localcpa);
    localccG.setCellSize(new Or(64, 64));
    localccG.setAutoIdealSize(true);
    localccG.setIdealSizeMaxColumns(6);
    localccG.setIdealSizeMinColumns(1);
    localccG.setIdealSizeMinRows(1);
    localccG.setIdealSizeMaxRows(30);
    localccG.setExpandable(false);
    localccG.setVisible(false);
    parambdj.bb(localccG);
    localccG.brn();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.ecj);
    localccG.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("content");
    localNK1.setField("evolutingBuildingList");
    localNK1.setName("havenWorld");
    localccG.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setAttribute("visible");
    localNK2.setField("evolutingBuildingsOpenned");
    localNK2.setName("havenWorld");
    localccG.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    eR localeR1 = new eR();
    localeR1.aJ();
    localeR1.setElementMap(localcpa);
    localccG.bb(localeR1);
    localeR1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localeR1.bb(localanQ1);
    localanQ1.brn();
    bxx localbxx1 = new bxx();
    localbxx1.aJ();
    localbxx1.setElementMap(localcpa);
    localanQ1.bb(localbxx1);
    localbxx1.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localbxx1.bb(localanE);
    localanE.brn();
    localanE.rV();
    localbxx1.rV();
    localanQ1.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localeR1.bb(localdRq1);
    localdRq1.brn();
    String str = "element";
    avo localavo = new avo();
    localavo.aJ();
    localavo.setElementMap(localcpa);
    if ((localcpa != null) && (str != null))
      localcpa.a(str, localavo);
    localdRq1.bb(localavo);
    localavo.brn();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("value");
    localavo.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    localavo.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setExpandable(false);
    localdRq2.setPrefSize(new Or(50, 50));
    localdRq2.setNonBlocking(false);
    DY localDY = new DY();
    localDY.hg("wakfu.havenWorldPanel:onMouseOutElement(element,elementDetailPopup)");
    localdRq2.setOnMouseExit(localDY);
    bDy localbDy = new bDy();
    localbDy.hg("wakfu.havenWorldPanel:onMouseOverElement(element,elementDetailPopup)");
    localdRq2.setOnMouseEnter(localbDy);
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setNonBlocking(true);
    localczv.setDisplaySize(new Or(50, 50));
    localdRq2.bb(localczv);
    localczv.brn();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv.bb(localaAR);
    localaAR.brn();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("texture");
    localaaE2.setField("iconUrl");
    localaAR.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    localaAR.rV();
    localczv.rV();
    localdRq2.rV();
    localdRq1.rV();
    localeR1.rV();
    eR localeR2 = new eR();
    localeR2.aJ();
    localeR2.setElementMap(localcpa);
    localccG.bb(localeR2);
    localeR2.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localeR2.bb(localanQ2);
    localanQ2.brn();
    bxx localbxx2 = new bxx();
    localbxx2.aJ();
    localbxx2.setElementMap(localcpa);
    localanQ2.bb(localbxx2);
    localbxx2.brn();
    aIB localaIB = new aIB();
    localaIB.aJ();
    localaIB.setElementMap(localcpa);
    localbxx2.bb(localaIB);
    localaIB.brn();
    localaIB.rV();
    localbxx2.rV();
    localanQ2.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localeR2.bb(localdRq3);
    localdRq3.brn();
    localdRq3.rV();
    localeR2.rV();
    localccG.rV();
    return localccG;
  }

  public bdj q(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq = dRq.checkOut();
    localdRq.setElementMap(localcpa);
    localdRq.setStyle("EncyclopediaPane");
    localdRq.setNonBlocking(true);
    parambdj.bb(localdRq);
    localdRq.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setAlign(ajb.dhT);
    localcwP.setSize(new Or(100.0F, 100.0F));
    localcwP.setYOffset(1);
    localdRq.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localdRq.rV();
    return localdRq;
  }

  public bdj r(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq = dRq.checkOut();
    localdRq.setElementMap(localcpa);
    parambdj.bb(localdRq);
    localdRq.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(100.0F, 100.0F));
    localdRq.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localdRq.rV();
    return localdRq;
  }

  public bdj s(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    biy localbiy = new biy();
    localbiy.aJ();
    localbiy.setElementMap(localcpa);
    localbiy.setStyle("close");
    localbiy.setExpandable(false);
    csA localcsA = new csA();
    localcsA.hg("unloadDialog");
    localbiy.setOnClick(localcsA);
    parambdj.bb(localbiy);
    localbiy.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(-2, -2));
    localcwP.setAlign(ajb.dhV);
    localcwP.setXOffset(-18);
    localcwP.setYOffset(-12);
    localbiy.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localbiy.rV();
    return localbiy;
  }

  public bdj t(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(-2, -2));
    localcwP.setAlign(ajb.dhZ);
    localcwP.setResizeOnce(true);
    parambdj.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    return localcwP;
  }
}