import java.util.Stack;

public class cgJ
  implements aTK
{
  private uk W;
  private Stack X = new Stack();

  public void a(cpa paramcpa, uk paramuk, dOc paramdOc)
  {
    this.W = paramuk;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    dOc localdOc = paramdOc;
    Jg localJg = localdOc.getAppearance();
    localJg.setElementMap(localcpa);
    paramdOc.bb(localJg);
    localJg.brn();
    aAR localaAR1 = aAR.checkOut();
    localaAR1.setElementMap(localcpa);
    localaAR1.setPosition(ajb.dhR);
    localaAR1.setX(397);
    localaAR1.setY(510);
    localaAR1.setWidth(3);
    localaAR1.setHeight(8);
    localaAR1.setTexture(this.W.aH("default_0.tga"));
    localJg.bb(localaAR1);
    localaAR1.brn();
    localaAR1.rV();
    aAR localaAR2 = aAR.checkOut();
    localaAR2.setElementMap(localcpa);
    localaAR2.setPosition(ajb.dhT);
    localaAR2.setX(932);
    localaAR2.setY(563);
    localaAR2.setWidth(1);
    localaAR2.setHeight(8);
    localaAR2.setTexture(this.W.aH("default_0.tga"));
    localJg.bb(localaAR2);
    localaAR2.brn();
    localaAR2.rV();
    aAR localaAR3 = aAR.checkOut();
    localaAR3.setElementMap(localcpa);
    localaAR3.setPosition(ajb.dhV);
    localaAR3.setX(397);
    localaAR3.setY(521);
    localaAR3.setWidth(3);
    localaAR3.setHeight(8);
    localaAR3.setTexture(this.W.aH("default_0.tga"));
    localJg.bb(localaAR3);
    localaAR3.brn();
    localaAR3.rV();
    aAR localaAR4 = aAR.checkOut();
    localaAR4.setElementMap(localcpa);
    localaAR4.setPosition(ajb.dhY);
    localaAR4.setX(891);
    localaAR4.setY(109);
    localaAR4.setWidth(3);
    localaAR4.setHeight(1);
    localaAR4.setTexture(this.W.aH("default_0.tga"));
    localJg.bb(localaAR4);
    localaAR4.brn();
    localaAR4.rV();
    aAR localaAR5 = aAR.checkOut();
    localaAR5.setElementMap(localcpa);
    localaAR5.setPosition(ajb.dhZ);
    localaAR5.setX(854);
    localaAR5.setY(618);
    localaAR5.setWidth(1);
    localaAR5.setHeight(11);
    localaAR5.setTexture(this.W.aH("default_0.tga"));
    localJg.bb(localaAR5);
    localaAR5.brn();
    localaAR5.rV();
    aAR localaAR6 = aAR.checkOut();
    localaAR6.setElementMap(localcpa);
    localaAR6.setPosition(ajb.dia);
    localaAR6.setX(247);
    localaAR6.setY(834);
    localaAR6.setWidth(3);
    localaAR6.setHeight(1);
    localaAR6.setTexture(this.W.aH("default_0.tga"));
    localJg.bb(localaAR6);
    localaAR6.brn();
    localaAR6.rV();
    aAR localaAR7 = aAR.checkOut();
    localaAR7.setElementMap(localcpa);
    localaAR7.setPosition(ajb.did);
    localaAR7.setX(745);
    localaAR7.setY(368);
    localaAR7.setWidth(3);
    localaAR7.setHeight(5);
    localaAR7.setTexture(this.W.aH("default_0.tga"));
    localJg.bb(localaAR7);
    localaAR7.brn();
    localaAR7.rV();
    aAR localaAR8 = aAR.checkOut();
    localaAR8.setElementMap(localcpa);
    localaAR8.setPosition(ajb.dif);
    localaAR8.setX(2);
    localaAR8.setY(375);
    localaAR8.setWidth(1);
    localaAR8.setHeight(5);
    localaAR8.setTexture(this.W.aH("default_0.tga"));
    localJg.bb(localaAR8);
    localaAR8.brn();
    localaAR8.rV();
    aAR localaAR9 = aAR.checkOut();
    localaAR9.setElementMap(localcpa);
    localaAR9.setPosition(ajb.dih);
    localaAR9.setX(254);
    localaAR9.setY(376);
    localaAR9.setWidth(3);
    localaAR9.setHeight(5);
    localaAR9.setTexture(this.W.aH("default_0.tga"));
    localJg.bb(localaAR9);
    localaAR9.brn();
    localaAR9.rV();
    localJg.rV();
  }
}