import java.awt.Insets;
import java.util.Stack;

public class cOK
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    bpn localbpn = new bpn();
    localbpn.aJ();
    localbpn.setElementMap(localcpa);
    localbpn.brn();
    czO localczO1 = new czO();
    localczO1.aJ();
    localczO1.setAdaptToContentSize(true);
    localbpn.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localbpn.bb(localdRq1);
    localdRq1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    localdRq1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setStyle("windowNew");
    localbpn.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(10, 5, 12, 5));
    localJg1.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    localJg1.rV();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localdRq2.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localaId1.setAlign(aFG.ech);
    localdRq2.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dqa localdqa1 = new dqa();
    localdqa1.aJ();
    localdqa1.setElementMap(localcpa);
    localdqa1.setExpandable(false);
    localdRq2.bb(localdqa1);
    localdqa1.brn();
    dqa localdqa2 = localdqa1;
    Jg localJg2 = localdqa2.getAppearance();
    localJg2.setElementMap(localcpa);
    localdqa1.bb(localJg2);
    localJg2.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 10, 0, 10));
    localJg2.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg2.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setStyle("titleBar");
    localdqa1.bb(localdRq4);
    localdRq4.brn();
    dRq localdRq5 = localdRq4;
    Jg localJg3 = localdRq5.getAppearance();
    localJg3.setElementMap(localcpa);
    localdRq4.bb(localJg3);
    localJg3.brn();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(2, 20, 3, 20));
    localJg3.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    localJg3.rV();
    aId localaId2 = aId.checkOut();
    localaId2.setHorizontal(false);
    localdRq4.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq6.setExpandable(false);
    localdRq4.bb(localdRq6);
    localdRq6.brn();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa);
    localdpm1.setAlign(aFG.eck);
    localdRq6.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("StyledBold16White");
    localcaF1.setNonBlocking(true);
    String str1 = "%eventsCalendar.title%";
    str1 = str1.replace("%eventsCalendar.title%", cBQ.cxL().mL("eventsCalendar.title"));
    localcaF1.setText(str1);
    localdRq6.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg4 = localcaF2.getAppearance();
    localJg4.setElementMap(localcpa);
    ((cwJ)localJg4).setAlign(aFG.eck);
    localcaF1.bb(localJg4);
    localJg4.brn();
    localJg4.rV();
    localcaF1.rV();
    localdRq6.rV();
    localdRq4.rV();
    localdqa1.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localdRq2.bb(localdRq7);
    localdRq7.brn();
    dRq localdRq8 = localdRq7;
    Jg localJg5 = localdRq8.getAppearance();
    localJg5.setElementMap(localcpa);
    localdRq7.bb(localJg5);
    localJg5.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 12, 0, 12));
    localJg5.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg5.rV();
    String str2 = "windowContentContainer";
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localdRq9);
    localdRq9.setPrefSize(new Or(0, 0));
    localdRq7.bb(localdRq9);
    localdRq9.brn();
    dRq localdRq10 = dRq.checkOut();
    localdRq10.setElementMap(localcpa);
    localdRq9.bb(localdRq10);
    localdRq10.brn();
    aId localaId3 = aId.checkOut();
    localaId3.setAlign(aFG.ecj);
    localdRq10.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    dRq localdRq11 = dRq.checkOut();
    localdRq11.setElementMap(localcpa);
    localdRq11.setExpandable(false);
    localdRq10.bb(localdRq11);
    localdRq11.brn();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa);
    localdpm2.setAlign(aFG.ech);
    localdRq11.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    aId localaId4 = aId.checkOut();
    localaId4.setHorizontal(false);
    localdRq11.bb(localaId4);
    localaId4.brn();
    localaId4.rV();
    dRq localdRq12 = dRq.checkOut();
    localdRq12.setElementMap(localcpa);
    localdRq12.setExpandable(false);
    localdRq11.bb(localdRq12);
    localdRq12.brn();
    dpm localdpm3 = new dpm();
    localdpm3.aJ();
    localdpm3.setElementMap(localcpa);
    localdpm3.setAlign(aFG.ecl);
    localdRq12.bb(localdpm3);
    localdpm3.brn();
    localdpm3.rV();
    ddG localddG1 = new ddG();
    localddG1.aJ();
    localddG1.setElementMap(localcpa);
    localddG1.setExpandable(false);
    localddG1.setPrefSize(new Or(100, 15));
    dTZ localdTZ1 = new dTZ();
    localdTZ1.hg("wakfu.eventsCalendar:changeCurrentMonth");
    localddG1.setOnListSelectionChange(localdTZ1);
    localdRq12.bb(localddG1);
    localddG1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("content");
    localNK1.setName("eventsCalendar");
    localNK1.setField("calendar/monthesList");
    localddG1.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setAttribute("selectedValue");
    localNK2.setName("eventsCalendar");
    localNK2.setField("calendar/selectedMonth");
    localddG1.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    axU localaxU1 = new axU();
    localaxU1.aJ();
    localaxU1.setElementMap(localcpa);
    localddG1.bb(localaxU1);
    localaxU1.brn();
    eR localeR1 = new eR();
    localeR1.aJ();
    localeR1.setElementMap(localcpa);
    localaxU1.bb(localeR1);
    localeR1.brn();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setNonBlocking(true);
    localeR1.bb(localcaF3);
    localcaF3.brn();
    dpm localdpm4 = new dpm();
    localdpm4.aJ();
    localdpm4.setElementMap(localcpa);
    localdpm4.setAlign(aFG.eck);
    localcaF3.bb(localdpm4);
    localdpm4.brn();
    localdpm4.rV();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("text");
    localaaE1.setField("description");
    localcaF3.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    localcaF3.rV();
    localeR1.rV();
    localaxU1.rV();
    ccG localccG1 = new ccG();
    localccG1.aJ();
    localccG1.setElementMap(localcpa);
    localccG1.setHorizontal(false);
    localccG1.setCellSize(new Or(100.0F, 16));
    localddG1.bb(localccG1);
    localccG1.brn();
    eR localeR2 = new eR();
    localeR2.aJ();
    localeR2.setElementMap(localcpa);
    localccG1.bb(localeR2);
    localeR2.brn();
    caF localcaF4 = new caF();
    localcaF4.aJ();
    localcaF4.setElementMap(localcpa);
    localcaF4.setNonBlocking(true);
    localeR2.bb(localcaF4);
    localcaF4.brn();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("text");
    localaaE2.setField("description");
    localcaF4.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    caF localcaF5 = localcaF4;
    Jg localJg6 = localcaF5.getAppearance();
    localJg6.setElementMap(localcpa);
    localcaF4.bb(localJg6);
    localJg6.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 10, 0, 0));
    localJg6.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg6.rV();
    localcaF4.rV();
    localeR2.rV();
    localccG1.rV();
    localddG1.rV();
    ddG localddG2 = new ddG();
    localddG2.aJ();
    localddG2.setElementMap(localcpa);
    localddG2.setExpandable(false);
    localddG2.setPrefSize(new Or(50, 15));
    dTZ localdTZ2 = new dTZ();
    localdTZ2.hg("wakfu.eventsCalendar:changeCurrentYear");
    localddG2.setOnListSelectionChange(localdTZ2);
    localdRq12.bb(localddG2);
    localddG2.brn();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setAttribute("content");
    localNK3.setName("eventsCalendar");
    localNK3.setField("calendar/yearsList");
    localddG2.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa);
    localNK4.setAttribute("selectedValue");
    localNK4.setName("eventsCalendar");
    localNK4.setField("calendar/selectedYear");
    localddG2.bb(localNK4);
    localNK4.brn();
    localNK4.rV();
    axU localaxU2 = new axU();
    localaxU2.aJ();
    localaxU2.setElementMap(localcpa);
    localddG2.bb(localaxU2);
    localaxU2.brn();
    eR localeR3 = new eR();
    localeR3.aJ();
    localeR3.setElementMap(localcpa);
    localaxU2.bb(localeR3);
    localeR3.brn();
    caF localcaF6 = new caF();
    localcaF6.aJ();
    localcaF6.setElementMap(localcpa);
    localcaF6.setNonBlocking(true);
    localeR3.bb(localcaF6);
    localcaF6.brn();
    dpm localdpm5 = new dpm();
    localdpm5.aJ();
    localdpm5.setElementMap(localcpa);
    localdpm5.setAlign(aFG.eck);
    localcaF6.bb(localdpm5);
    localdpm5.brn();
    localdpm5.rV();
    aaE localaaE3 = new aaE();
    localaaE3.aJ();
    localaaE3.setElementMap(localcpa);
    localaaE3.setAttribute("text");
    localcaF6.bb(localaaE3);
    localaaE3.brn();
    localaaE3.rV();
    localcaF6.rV();
    localeR3.rV();
    localaxU2.rV();
    ccG localccG2 = new ccG();
    localccG2.aJ();
    localccG2.setElementMap(localcpa);
    localccG2.setHorizontal(false);
    localccG2.setCellSize(new Or(100.0F, 16));
    localddG2.bb(localccG2);
    localccG2.brn();
    eR localeR4 = new eR();
    localeR4.aJ();
    localeR4.setElementMap(localcpa);
    localccG2.bb(localeR4);
    localeR4.brn();
    caF localcaF7 = new caF();
    localcaF7.aJ();
    localcaF7.setElementMap(localcpa);
    localcaF7.setNonBlocking(true);
    localeR4.bb(localcaF7);
    localcaF7.brn();
    aaE localaaE4 = new aaE();
    localaaE4.aJ();
    localaaE4.setElementMap(localcpa);
    localaaE4.setAttribute("text");
    localcaF7.bb(localaaE4);
    localaaE4.brn();
    localaaE4.rV();
    caF localcaF8 = localcaF7;
    Jg localJg7 = localcaF8.getAppearance();
    localJg7.setElementMap(localcpa);
    localcaF7.bb(localJg7);
    localJg7.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(0, 10, 0, 0));
    localJg7.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg7.rV();
    localcaF7.rV();
    localeR4.rV();
    localccG2.rV();
    localddG2.rV();
    localdRq12.rV();
    String str3 = "calendar";
    bWa localbWa = new bWa();
    localbWa.aJ();
    localbWa.setElementMap(localcpa);
    if ((localcpa != null) && (str3 != null))
      localcpa.a(str3, localbWa);
    localbWa.setExpandable(false);
    localbWa.setCellSize(new Or(100, 95));
    localbWa.setDateMargin(new Insets(0, 0, 5, 6));
    localdRq11.bb(localbWa);
    localbWa.brn();
    eR localeR5 = new eR();
    localeR5.aJ();
    localeR5.setElementMap(localcpa);
    localbWa.bb(localeR5);
    localeR5.brn();
    dRq localdRq13 = dRq.checkOut();
    localdRq13.setElementMap(localcpa);
    localdRq13.setStyle("caracs");
    localeR5.bb(localdRq13);
    localdRq13.brn();
    czO localczO2 = new czO();
    localczO2.aJ();
    localdRq13.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    dRq localdRq14 = dRq.checkOut();
    localdRq14.setElementMap(localcpa);
    localdRq13.bb(localdRq14);
    localdRq14.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setSize(new Or(100.0F, 100.0F));
    localdRq14.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    aId localaId5 = aId.checkOut();
    localaId5.setAlign(aFG.ecj);
    localdRq14.bb(localaId5);
    localaId5.brn();
    localaId5.rV();
    ccG localccG3 = new ccG();
    localccG3.aJ();
    localccG3.setElementMap(localcpa);
    localccG3.setHorizontal(false);
    localccG3.setCellSize(new Or(21, 21));
    localccG3.setAutoIdealSize(true);
    localccG3.setShrinkable(true);
    localccG3.setMaxSize(new Or(84, 63));
    localccG3.setIdealSizeMinColumns(0);
    localccG3.setIdealSizeMaxColumns(4);
    localccG3.setExpandable(false);
    anx localanx = new anx();
    localanx.hg("wakfu.eventsCalendar:displayEventDescriptionPopup(eventDescriptionPopup)");
    localccG3.setOnItemOver(localanx);
    cVk localcVk = new cVk();
    localcVk.hg("wakfu.eventsCalendar:hideEventDescriptionPopup(eventDescriptionPopup)");
    localccG3.setOnItemOut(localcVk);
    aqC localaqC = new aqC();
    localaqC.hg("wakfu.eventsCalendar:openEditEventDialog");
    localccG3.setOnItemClick(localaqC);
    localdRq14.bb(localccG3);
    localccG3.brn();
    dpm localdpm6 = new dpm();
    localdpm6.aJ();
    localdpm6.setElementMap(localcpa);
    localdpm6.setAlign(aFG.ech);
    localccG3.bb(localdpm6);
    localdpm6.brn();
    localdpm6.rV();
    aaE localaaE5 = new aaE();
    localaaE5.aJ();
    localaaE5.setElementMap(localcpa);
    localaaE5.setAttribute("content");
    localccG3.bb(localaaE5);
    localaaE5.brn();
    localaaE5.rV();
    eR localeR6 = new eR();
    localeR6.aJ();
    localeR6.setElementMap(localcpa);
    localccG3.bb(localeR6);
    localeR6.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localeR6.bb(localanQ);
    localanQ.brn();
    bxx localbxx = new bxx();
    localbxx.aJ();
    localbxx.setElementMap(localcpa);
    localanQ.bb(localbxx);
    localbxx.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localbxx.bb(localanE);
    localanE.brn();
    localanE.rV();
    localbxx.rV();
    localanQ.rV();
    dRq localdRq15 = dRq.checkOut();
    localdRq15.setElementMap(localcpa);
    localeR6.bb(localdRq15);
    localdRq15.brn();
    a(localdRq15);
    b(localdRq15);
    d(localdRq15);
    localdRq15.rV();
    localeR6.rV();
    localccG3.rV();
    localdRq14.rV();
    e(localdRq13);
    localdRq13.rV();
    localeR5.rV();
    localbWa.rV();
    localdRq11.rV();
    localdRq10.rV();
    localdRq9.rV();
    localdRq7.rV();
    localdRq2.rV();
    f(localbpn);
    g(localbpn);
    h(localbpn);
    i(localbpn);
    localbpn.rV();
    return localbpn;
  }

  public bdj a(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    czO localczO = new czO();
    localczO.aJ();
    localczO.setAdaptToContentSize(true);
    parambdj.bb(localczO);
    localczO.brn();
    localczO.rV();
    return null;
  }

  public bdj b(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    biy localbiy = new biy();
    localbiy.aJ();
    localbiy.setElementMap(localcpa);
    localbiy.setStyle("flat");
    localbiy.setPrefSize(new Or(18, 18));
    parambdj.bb(localbiy);
    localbiy.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setAlign(ajb.dhZ);
    localbiy.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localbiy.rV();
    return localbiy;
  }

  public bdj d(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setDisplaySize(new Or(16, 16));
    localczv.setNonBlocking(true);
    parambdj.bb(localczv);
    localczv.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setAlign(ajb.dhZ);
    localczv.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv.bb(localaAR);
    localaAR.brn();
    aaE localaaE = new aaE();
    localaaE.aJ();
    localaaE.setElementMap(localcpa);
    localaaE.setAttribute("texture");
    localaaE.setField("iconUrl");
    localaAR.bb(localaaE);
    localaaE.brn();
    localaaE.rV();
    localaAR.rV();
    localczv.rV();
    return localczv;
  }

  public bdj e(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    biy localbiy = new biy();
    localbiy.aJ();
    localbiy.setElementMap(localcpa);
    localbiy.setStyle("add");
    csA localcsA = new csA();
    localcsA.hg("wakfu.eventsCalendar:openCreateEventDialog");
    localbiy.setOnClick(localcsA);
    cCu localcCu = new cCu();
    localcCu.hg("popup(descCreateEventPopup)");
    localbiy.setOnPopupDisplay(localcCu);
    jL localjL = new jL();
    localjL.hg("closePopup");
    localbiy.setOnPopupHide(localjL);
    parambdj.bb(localbiy);
    localbiy.brn();
    String str1 = "descCreateEventPopup";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localanG);
    localanG.setAlign(aFG.ecl);
    localanG.setHotSpotPosition(aFG.ecj);
    localbiy.bb(localanG);
    localanG.brn();
    dRq localdRq = dRq.checkOut();
    localdRq.setElementMap(localcpa);
    localdRq.setPrefSize(new Or(10, 0));
    localdRq.setStyle("popup");
    localanG.bb(localdRq);
    localdRq.brn();
    cba localcba = cba.checkOut();
    localcba.setElementMap(localcpa);
    localcba.setData(cFu.izR);
    localdRq.bb(localcba);
    localcba.brn();
    localcba.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("PopupInformation");
    String str2 = "%eventsCalendar.create.title%";
    str2 = str2.replace("%eventsCalendar.create.title%", cBQ.cxL().mL("eventsCalendar.create.title"));
    localcaF1.setText(str2);
    localdRq.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg = localcaF2.getAppearance();
    localJg.setElementMap(localcpa);
    ((cwJ)localJg).setAlignment(aFG.ecj);
    localcaF1.bb(localJg);
    localJg.brn();
    localJg.rV();
    localcaF1.rV();
    localdRq.rV();
    localanG.rV();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setAlign(ajb.did);
    localbiy.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localbiy.rV();
    return localbiy;
  }

  public bdj f(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq = dRq.checkOut();
    localdRq.setElementMap(localcpa);
    parambdj.bb(localdRq);
    localdRq.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(100.0F, 100.0F));
    localdRq.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localdRq.rV();
    return localdRq;
  }

  public bdj g(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    biy localbiy = new biy();
    localbiy.aJ();
    localbiy.setElementMap(localcpa);
    localbiy.setStyle("close");
    localbiy.setExpandable(false);
    csA localcsA = new csA();
    localcsA.hg("wakfu.eventsCalendar:closeDialog");
    localbiy.setOnClick(localcsA);
    parambdj.bb(localbiy);
    localbiy.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(-2, -2));
    localcwP.setAlign(ajb.dhV);
    localcwP.setXOffset(-18);
    localcwP.setYOffset(-12);
    localbiy.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localbiy.rV();
    return localbiy;
  }

  public bdj h(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(-2, -2));
    localcwP.setAlign(ajb.dhZ);
    localcwP.setInitValue(true);
    parambdj.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    return localcwP;
  }

  public bdj i(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    String str1 = "eventDescriptionPopup";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localanG);
    parambdj.bb(localanG);
    localanG.brn();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setStyle("popup");
    localdRq1.setPrefSize(new Or(300, 0));
    localanG.bb(localdRq1);
    localdRq1.brn();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localdRq1.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setExpandable(false);
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("bigTitle");
    localcWk1.setMinWidth(180);
    localdRq2.bb(localcWk1);
    localcWk1.brn();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa);
    localdpm1.setAlign(aFG.ecj);
    localcWk1.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setName("calendar.event.detail");
    localNK1.setAttribute("text");
    localNK1.setField("title");
    localcWk1.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    localcWk1.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq3.setExpandable(false);
    localdRq2.bb(localdRq3);
    localdRq3.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("calendar.event.detail");
    localNK2.setAttribute("visible");
    localNK2.setField("areParticipantsLimited");
    localdRq3.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setStyle("singleCharacterIcon");
    localdRq3.bb(localczv1);
    localczv1.brn();
    localczv1.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("11Light");
    localcaF1.setExpandable(false);
    localdRq3.bb(localcaF1);
    localcaF1.brn();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa);
    localdpm2.setAlign(aFG.ecj);
    localcaF1.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setName("calendar.event.detail");
    localNK3.setAttribute("text");
    localNK3.setField("numParticipantsDesc");
    localcaF1.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    localcaF1.rV();
    localdRq3.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setExpandable(false);
    localdRq2.bb(localdRq4);
    localdRq4.brn();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa);
    localNK4.setName("calendar.event.detail");
    localNK4.setAttribute("visible");
    localNK4.setField("areParticipantsLimited");
    localdRq4.bb(localNK4);
    localNK4.brn();
    localNK4.rV();
    czv localczv2 = new czv();
    localczv2.aJ();
    localczv2.setElementMap(localcpa);
    localczv2.setStyle("tripleCharacterIcon");
    localdRq4.bb(localczv2);
    localczv2.brn();
    localczv2.rV();
    caF localcaF2 = new caF();
    localcaF2.aJ();
    localcaF2.setElementMap(localcpa);
    localcaF2.setStyle("11Light");
    localcaF2.setExpandable(false);
    localdRq4.bb(localcaF2);
    localcaF2.brn();
    dpm localdpm3 = new dpm();
    localdpm3.aJ();
    localdpm3.setElementMap(localcpa);
    localdpm3.setAlign(aFG.ecj);
    localcaF2.bb(localdpm3);
    localdpm3.brn();
    localdpm3.rV();
    NK localNK5 = NK.checkOut();
    localNK5.setElementMap(localcpa);
    localNK5.setName("calendar.event.detail");
    localNK5.setAttribute("text");
    localNK5.setField("numRegistrationsDesc");
    localcaF2.bb(localNK5);
    localNK5.brn();
    localNK5.rV();
    localcaF2.rV();
    localdRq4.rV();
    localdRq2.rV();
    dRq localdRq5 = dRq.checkOut();
    localdRq5.setElementMap(localcpa);
    localdRq5.setExpandable(false);
    localdRq5.setStyle("lineSeparator2");
    localdRq5.setPrefSize(new Or(50, 1));
    localdRq1.bb(localdRq5);
    localdRq5.brn();
    dRq localdRq6 = localdRq5;
    Jg localJg1 = localdRq6.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq5.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(5, 20, 5, 20));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    localdRq5.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localdRq1.bb(localdRq7);
    localdRq7.brn();
    aId localaId2 = aId.checkOut();
    localaId2.setHorizontal(false);
    localdRq7.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setExpandable(false);
    String str2 = "%description%";
    str2 = str2.replace("%description%", cBQ.cxL().mL("description"));
    localcaF3.setText(str2);
    localcaF3.setStyle("11BoldLight");
    localdRq7.bb(localcaF3);
    localcaF3.brn();
    localcaF3.rV();
    cWk localcWk2 = new cWk();
    localcWk2.aJ();
    localcWk2.setElementMap(localcpa);
    localcWk2.setStyle("White11");
    localcWk2.setExpandable(false);
    localcWk2.setMinWidth(280);
    localdRq7.bb(localcWk2);
    localcWk2.brn();
    dpm localdpm4 = new dpm();
    localdpm4.aJ();
    localdpm4.setElementMap(localcpa);
    localdpm4.setAlign(aFG.ecj);
    localcWk2.bb(localdpm4);
    localdpm4.brn();
    localdpm4.rV();
    cWk localcWk3 = localcWk2;
    Jg localJg2 = localcWk3.getAppearance();
    localJg2.setElementMap(localcpa);
    localcWk2.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 5, 0, 0));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    NK localNK6 = NK.checkOut();
    localNK6.setElementMap(localcpa);
    localNK6.setName("calendar.event.detail");
    localNK6.setAttribute("text");
    localNK6.setField("description");
    localcWk2.bb(localNK6);
    localNK6.brn();
    localNK6.rV();
    localcWk2.rV();
    localdRq7.rV();
    dRq localdRq8 = dRq.checkOut();
    localdRq8.setElementMap(localcpa);
    localdRq1.bb(localdRq8);
    localdRq8.brn();
    NK localNK7 = NK.checkOut();
    localNK7.setElementMap(localcpa);
    localNK7.setAttribute("visible");
    localNK7.setName("calendar.event.detail");
    localNK7.setField("startDateDesc");
    localdRq8.bb(localNK7);
    localNK7.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localNK7.bb(localanQ1);
    localanQ1.brn();
    dDu localdDu = new dDu();
    localdDu.aJ();
    localdDu.setElementMap(localcpa);
    localanQ1.bb(localdDu);
    localdDu.brn();
    bSP localbSP = new bSP();
    localbSP.aJ();
    localbSP.setElementMap(localcpa);
    localbSP.setValue("");
    localdDu.bb(localbSP);
    localbSP.brn();
    localbSP.rV();
    localdDu.rV();
    localanQ1.rV();
    localNK7.rV();
    aId localaId3 = aId.checkOut();
    localaId3.setAlign(aFG.ecj);
    localdRq8.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    dRq localdRq9 = localdRq8;
    Jg localJg3 = localdRq9.getAppearance();
    localJg3.setElementMap(localcpa);
    localdRq8.bb(localJg3);
    localJg3.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(5, 0, 0, 0));
    localJg3.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg3.rV();
    caF localcaF4 = new caF();
    localcaF4.aJ();
    localcaF4.setElementMap(localcpa);
    localcaF4.setExpandable(false);
    String str3 = "%eventsCalendar.startDate%";
    str3 = str3.replace("%eventsCalendar.startDate%", cBQ.cxL().mL("eventsCalendar.startDate"));
    localcaF4.setText(str3);
    localcaF4.setStyle("11BoldLight");
    localdRq8.bb(localcaF4);
    localcaF4.brn();
    caF localcaF5 = localcaF4;
    Jg localJg4 = localcaF5.getAppearance();
    localJg4.setElementMap(localcpa);
    localcaF4.bb(localJg4);
    localJg4.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(0, 0, 0, 5));
    localJg4.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg4.rV();
    localcaF4.rV();
    cWk localcWk4 = new cWk();
    localcWk4.aJ();
    localcWk4.setElementMap(localcpa);
    localcWk4.setStyle("White11");
    localcWk4.setExpandable(false);
    localcWk4.setMinWidth(180);
    localdRq8.bb(localcWk4);
    localcWk4.brn();
    dpm localdpm5 = new dpm();
    localdpm5.aJ();
    localdpm5.setElementMap(localcpa);
    localdpm5.setAlign(aFG.ecj);
    localcWk4.bb(localdpm5);
    localdpm5.brn();
    localdpm5.rV();
    NK localNK8 = NK.checkOut();
    localNK8.setElementMap(localcpa);
    localNK8.setName("calendar.event.detail");
    localNK8.setAttribute("text");
    localNK8.setField("startDateDesc");
    localcWk4.bb(localNK8);
    localNK8.brn();
    localNK8.rV();
    localcWk4.rV();
    localdRq8.rV();
    dRq localdRq10 = dRq.checkOut();
    localdRq10.setElementMap(localcpa);
    localdRq1.bb(localdRq10);
    localdRq10.brn();
    NK localNK9 = NK.checkOut();
    localNK9.setElementMap(localcpa);
    localNK9.setAttribute("visible");
    localNK9.setName("calendar.event.detail");
    localNK9.setField("endDateDesc");
    localdRq10.bb(localNK9);
    localNK9.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localNK9.bb(localanQ2);
    localanQ2.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localanQ2.bb(localanE);
    localanE.brn();
    localanE.rV();
    localanQ2.rV();
    localNK9.rV();
    aId localaId4 = aId.checkOut();
    localaId4.setAlign(aFG.ecj);
    localdRq10.bb(localaId4);
    localaId4.brn();
    localaId4.rV();
    dRq localdRq11 = localdRq10;
    Jg localJg5 = localdRq11.getAppearance();
    localJg5.setElementMap(localcpa);
    localdRq10.bb(localJg5);
    localJg5.brn();
    bmv localbmv5 = bmv.checkOut();
    localbmv5.setElementMap(localcpa);
    localbmv5.setInsets(new Insets(5, 0, 0, 0));
    localJg5.bb(localbmv5);
    localbmv5.brn();
    localbmv5.rV();
    localJg5.rV();
    caF localcaF6 = new caF();
    localcaF6.aJ();
    localcaF6.setElementMap(localcpa);
    localcaF6.setExpandable(false);
    String str4 = "%eventsCalendar.endDate%";
    str4 = str4.replace("%eventsCalendar.endDate%", cBQ.cxL().mL("eventsCalendar.endDate"));
    localcaF6.setText(str4);
    localcaF6.setStyle("11BoldLight");
    localdRq10.bb(localcaF6);
    localcaF6.brn();
    caF localcaF7 = localcaF6;
    Jg localJg6 = localcaF7.getAppearance();
    localJg6.setElementMap(localcpa);
    localcaF6.bb(localJg6);
    localJg6.brn();
    bmv localbmv6 = bmv.checkOut();
    localbmv6.setElementMap(localcpa);
    localbmv6.setInsets(new Insets(0, 0, 0, 5));
    localJg6.bb(localbmv6);
    localbmv6.brn();
    localbmv6.rV();
    localJg6.rV();
    localcaF6.rV();
    cWk localcWk5 = new cWk();
    localcWk5.aJ();
    localcWk5.setElementMap(localcpa);
    localcWk5.setStyle("White11");
    localcWk5.setExpandable(false);
    localcWk5.setMinWidth(180);
    localdRq10.bb(localcWk5);
    localcWk5.brn();
    dpm localdpm6 = new dpm();
    localdpm6.aJ();
    localdpm6.setElementMap(localcpa);
    localdpm6.setAlign(aFG.ecj);
    localcWk5.bb(localdpm6);
    localdpm6.brn();
    localdpm6.rV();
    NK localNK10 = NK.checkOut();
    localNK10.setElementMap(localcpa);
    localNK10.setName("calendar.event.detail");
    localNK10.setAttribute("text");
    localNK10.setField("endDateDesc");
    localcWk5.bb(localNK10);
    localNK10.brn();
    localNK10.rV();
    localcWk5.rV();
    localdRq10.rV();
    localdRq1.rV();
    localanG.rV();
    return localanG;
  }
}