import java.awt.Insets;
import java.util.Stack;

public class bgu
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setVisible(false);
    localdRq1.brn();
    aId localaId1 = aId.checkOut();
    localdRq1.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setName("itemPopupDetail");
    localNK1.setAttribute("visible");
    localdRq1.bb(localNK1);
    localNK1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localNK1.bb(localanQ1);
    localanQ1.brn();
    anE localanE1 = new anE();
    localanE1.aJ();
    localanE1.setElementMap(localcpa);
    localanQ1.bb(localanE1);
    localanE1.brn();
    localanE1.rV();
    localanQ1.rV();
    localNK1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setExpandable(false);
    localdRq2.setPrefSize(new Or(250, 0));
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    cuR localcuR = new cuR();
    localcuR.aJ();
    localcuR.setElementMap(localcpa);
    localcuR.setInsets(new Insets(6, 6, 6, 6));
    localJg1.bb(localcuR);
    localcuR.brn();
    localcuR.rV();
    jO localjO = new jO();
    localjO.aJ();
    localjO.setElementMap(localcpa);
    localjO.setColor(new bNa(0.0F, 0.0F, 0.0F, 0.9F));
    localJg1.bb(localjO);
    localjO.brn();
    localjO.rV();
    localJg1.rV();
    aId localaId2 = aId.checkOut();
    localaId2.setAlign(aFG.ech);
    localaId2.setHorizontal(false);
    localdRq2.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setExpandable(false);
    localdRq2.bb(localdRq4);
    localdRq4.brn();
    aId localaId3 = aId.checkOut();
    localdRq4.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    dRq localdRq5 = dRq.checkOut();
    localdRq5.setElementMap(localcpa);
    localdRq4.bb(localdRq5);
    localdRq5.brn();
    aId localaId4 = aId.checkOut();
    localaId4.setHorizontal(false);
    localaId4.setAlign(aFG.ech);
    localdRq5.bb(localaId4);
    localaId4.brn();
    localaId4.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("bigTitle");
    localcaF1.setExpandable(false);
    localdRq5.bb(localcaF1);
    localcaF1.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("itemPopupDetail");
    localNK2.setAttribute("text");
    localNK2.setField("name");
    localcaF1.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localcaF1.rV();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq6.setExpandable(false);
    localdRq5.bb(localdRq6);
    localdRq6.brn();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa);
    localdpm1.setAlign(aFG.ecj);
    localdRq6.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("white11");
    localcWk1.setMultiline(false);
    localdRq6.bb(localcWk1);
    localcWk1.brn();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setAttribute("text");
    localNK3.setName("itemPopupDetail");
    localNK3.setField("type");
    localcWk1.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    localcWk1.rV();
    localdRq6.rV();
    localdRq5.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localdRq7.setExpandable(false);
    localdRq4.bb(localdRq7);
    localdRq7.brn();
    dRq localdRq8 = localdRq7;
    Jg localJg2 = localdRq8.getAppearance();
    localJg2.setElementMap(localcpa);
    localdRq7.bb(localJg2);
    localJg2.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(3, 0, 0, 0));
    localJg2.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg2.rV();
    aId localaId5 = aId.checkOut();
    localaId5.setHorizontal(false);
    localaId5.setAlign(aFG.ech);
    localdRq7.bb(localaId5);
    localaId5.brn();
    localaId5.rV();
    cWk localcWk2 = new cWk();
    localcWk2.aJ();
    localcWk2.setElementMap(localcpa);
    localcWk2.setStyle("white11");
    localcWk2.setExpandable(false);
    localdRq7.bb(localcWk2);
    localcWk2.brn();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa);
    localdpm2.setAlign(aFG.ecl);
    localcWk2.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa);
    localNK4.setName("itemPopupDetail");
    localNK4.setAttribute("text");
    localNK4.setField("levelDescription");
    localcWk2.bb(localNK4);
    localNK4.brn();
    localNK4.rV();
    localcWk2.rV();
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa);
    localdRq9.setExpandable(false);
    localdRq7.bb(localdRq9);
    localdRq9.brn();
    dpm localdpm3 = new dpm();
    localdpm3.aJ();
    localdpm3.setElementMap(localcpa);
    localdpm3.setAlign(aFG.ecl);
    localdRq9.bb(localdpm3);
    localdpm3.brn();
    localdpm3.rV();
    NK localNK5 = NK.checkOut();
    localNK5.setElementMap(localcpa);
    localNK5.setName("itemPopupDetail");
    localNK5.setAttribute("visible");
    localNK5.setField("ap");
    localdRq9.bb(localNK5);
    localNK5.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localNK5.bb(localanQ2);
    localanQ2.brn();
    jA localjA = new jA();
    localjA.aJ();
    localjA.setElementMap(localcpa);
    localjA.setValue("0");
    localanQ2.bb(localjA);
    localjA.brn();
    localjA.rV();
    localanQ2.rV();
    localNK5.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setStyle("iconAP");
    localczv1.setExpandable(false);
    localdRq9.bb(localczv1);
    localczv1.brn();
    localczv1.rV();
    caF localcaF2 = new caF();
    localcaF2.aJ();
    localcaF2.setElementMap(localcpa);
    localcaF2.setStyle("11Light");
    localdRq9.bb(localcaF2);
    localcaF2.brn();
    NK localNK6 = NK.checkOut();
    localNK6.setElementMap(localcpa);
    localNK6.setName("itemPopupDetail");
    localNK6.setAttribute("text");
    localNK6.setField("ap");
    localcaF2.bb(localNK6);
    localNK6.brn();
    localNK6.rV();
    localcaF2.rV();
    localdRq9.rV();
    dRq localdRq10 = dRq.checkOut();
    localdRq10.setElementMap(localcpa);
    localdRq10.setExpandable(false);
    localdRq7.bb(localdRq10);
    localdRq10.brn();
    dpm localdpm4 = new dpm();
    localdpm4.aJ();
    localdpm4.setElementMap(localcpa);
    localdpm4.setAlign(aFG.ecl);
    localdRq10.bb(localdpm4);
    localdpm4.brn();
    localdpm4.rV();
    NK localNK7 = NK.checkOut();
    localNK7.setElementMap(localcpa);
    localNK7.setName("itemPopupDetail");
    localNK7.setAttribute("visible");
    localNK7.setField("range");
    localdRq10.bb(localNK7);
    localNK7.brn();
    anQ localanQ3 = new anQ();
    localanQ3.aJ();
    localanQ3.setElementMap(localcpa);
    localNK7.bb(localanQ3);
    localanQ3.brn();
    anE localanE2 = new anE();
    localanE2.aJ();
    localanE2.setElementMap(localcpa);
    localanQ3.bb(localanE2);
    localanE2.brn();
    localanE2.rV();
    localanQ3.rV();
    localNK7.rV();
    czv localczv2 = new czv();
    localczv2.aJ();
    localczv2.setElementMap(localcpa);
    localczv2.setStyle("smallSword");
    localczv2.setExpandable(false);
    localdRq10.bb(localczv2);
    localczv2.brn();
    localczv2.rV();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setStyle("11Light");
    localdRq10.bb(localcaF3);
    localcaF3.brn();
    NK localNK8 = NK.checkOut();
    localNK8.setElementMap(localcpa);
    localNK8.setName("itemPopupDetail");
    localNK8.setAttribute("text");
    localNK8.setField("range");
    localcaF3.bb(localNK8);
    localNK8.brn();
    localNK8.rV();
    localcaF3.rV();
    localdRq10.rV();
    localdRq7.rV();
    localdRq4.rV();
    dRq localdRq11 = dRq.checkOut();
    localdRq11.setElementMap(localcpa);
    localdRq11.setExpandable(false);
    localdRq2.bb(localdRq11);
    localdRq11.brn();
    NK localNK9 = NK.checkOut();
    localNK9.setElementMap(localcpa);
    localNK9.setAttribute("visible");
    localNK9.setName("itemPopupDetail");
    localNK9.setField("effect");
    localdRq11.bb(localNK9);
    localNK9.brn();
    anQ localanQ4 = new anQ();
    localanQ4.aJ();
    localanQ4.setElementMap(localcpa);
    localanQ4.setValue("false");
    localanQ4.setElseValue("true");
    localNK9.bb(localanQ4);
    localanQ4.brn();
    bSP localbSP1 = new bSP();
    localbSP1.aJ();
    localbSP1.setElementMap(localcpa);
    localbSP1.setValue("");
    localanQ4.bb(localbSP1);
    localbSP1.brn();
    localbSP1.rV();
    localanQ4.rV();
    localNK9.rV();
    aId localaId6 = aId.checkOut();
    localaId6.setHorizontal(false);
    localdRq11.bb(localaId6);
    localaId6.brn();
    localaId6.rV();
    dRq localdRq12 = dRq.checkOut();
    localdRq12.setElementMap(localcpa);
    localdRq12.setExpandable(false);
    localdRq12.setStyle("lineSeparator");
    localdRq12.setPrefSize(new Or(0, 7));
    localdRq11.bb(localdRq12);
    localdRq12.brn();
    dRq localdRq13 = localdRq12;
    Jg localJg3 = localdRq13.getAppearance();
    localJg3.setElementMap(localcpa);
    localdRq12.bb(localJg3);
    localJg3.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(5, 0, 2, 0));
    localJg3.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg3.rV();
    localdRq12.rV();
    caF localcaF4 = new caF();
    localcaF4.aJ();
    localcaF4.setElementMap(localcpa);
    localcaF4.setExpandable(false);
    String str = "%effects.characteristics%";
    str = str.replace("%effects.characteristics%", cBQ.cxL().mL("effects.characteristics"));
    localcaF4.setText(str);
    localcaF4.setStyle("11");
    localdRq11.bb(localcaF4);
    localcaF4.brn();
    cba localcba = cba.checkOut();
    localcba.setElementMap(localcpa);
    localcba.setData(cFu.izR);
    localcaF4.bb(localcba);
    localcba.brn();
    localcba.rV();
    caF localcaF5 = localcaF4;
    Jg localJg4 = localcaF5.getAppearance();
    localJg4.setElementMap(localcpa);
    localcaF4.bb(localJg4);
    localJg4.brn();
    cAf localcAf = cAf.checkOut();
    localcAf.setElementMap(localcpa);
    localcAf.setColor(new bNa(1.0F, 1.0F, 1.0F, 1.0F));
    localJg4.bb(localcAf);
    localcAf.brn();
    localcAf.rV();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 5, 5, 0));
    localJg4.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg4.rV();
    localcaF4.rV();
    cWk localcWk3 = new cWk();
    localcWk3.aJ();
    localcWk3.setElementMap(localcpa);
    localcWk3.setStyle("white11");
    localcWk3.setMinWidth(230);
    localdRq11.bb(localcWk3);
    localcWk3.brn();
    NK localNK10 = NK.checkOut();
    localNK10.setElementMap(localcpa);
    localNK10.setAttribute("visible");
    localNK10.setName("itemPopupDetail");
    localNK10.setField("effectDetails");
    localcWk3.bb(localNK10);
    localNK10.brn();
    anQ localanQ5 = new anQ();
    localanQ5.aJ();
    localanQ5.setElementMap(localcpa);
    localanQ5.setValue("false");
    localanQ5.setElseValue("true");
    localNK10.bb(localanQ5);
    localanQ5.brn();
    boQ localboQ1 = new boQ();
    localboQ1.aJ();
    localboQ1.setElementMap(localcpa);
    localanQ5.bb(localboQ1);
    localboQ1.brn();
    bSP localbSP2 = new bSP();
    localbSP2.aJ();
    localbSP2.setElementMap(localcpa);
    localbSP2.setValue("");
    localboQ1.bb(localbSP2);
    localbSP2.brn();
    localbSP2.rV();
    cOk localcOk1 = new cOk();
    localcOk1.aJ();
    localcOk1.setElementMap(localcpa);
    localboQ1.bb(localcOk1);
    localcOk1.brn();
    NK localNK11 = NK.checkOut();
    localNK11.setElementMap(localcpa);
    localNK11.setAttribute("comparedValue");
    localNK11.setName("isFromEquipedShortcut");
    localcOk1.bb(localNK11);
    localNK11.brn();
    localNK11.rV();
    localcOk1.rV();
    cOk localcOk2 = new cOk();
    localcOk2.aJ();
    localcOk2.setElementMap(localcpa);
    localboQ1.bb(localcOk2);
    localcOk2.brn();
    NK localNK12 = NK.checkOut();
    localNK12.setElementMap(localcpa);
    localNK12.setAttribute("comparedValue");
    localNK12.setName("isFromShortcut");
    localcOk2.bb(localNK12);
    localNK12.brn();
    localNK12.rV();
    localcOk2.rV();
    localboQ1.rV();
    localanQ5.rV();
    localNK10.rV();
    cWk localcWk4 = localcWk3;
    Jg localJg5 = localcWk4.getAppearance();
    localJg5.setElementMap(localcpa);
    localcWk3.bb(localJg5);
    localJg5.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(0, 20, 0, 0));
    localJg5.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg5.rV();
    NK localNK13 = NK.checkOut();
    localNK13.setElementMap(localcpa);
    localNK13.setName("itemPopupDetail");
    localNK13.setAttribute("text");
    localNK13.setField("effectDetails");
    localcWk3.bb(localNK13);
    localNK13.brn();
    localNK13.rV();
    localcWk3.rV();
    cWk localcWk5 = new cWk();
    localcWk5.aJ();
    localcWk5.setElementMap(localcpa);
    localcWk5.setStyle("white11");
    localcWk5.setMinWidth(230);
    localcWk5.setVisible(false);
    localdRq11.bb(localcWk5);
    localcWk5.brn();
    NK localNK14 = NK.checkOut();
    localNK14.setElementMap(localcpa);
    localNK14.setAttribute("visible");
    localNK14.setName("isFromEquipedShortcut");
    localcWk5.bb(localNK14);
    localNK14.brn();
    anQ localanQ6 = new anQ();
    localanQ6.aJ();
    localanQ6.setElementMap(localcpa);
    localanQ6.setValue("false");
    localanQ6.setElseValue("true");
    localNK14.bb(localanQ6);
    localanQ6.brn();
    boQ localboQ2 = new boQ();
    localboQ2.aJ();
    localboQ2.setElementMap(localcpa);
    localanQ6.bb(localboQ2);
    localboQ2.brn();
    bJJ localbJJ = new bJJ();
    localbJJ.aJ();
    localbJJ.setElementMap(localcpa);
    localboQ2.bb(localbJJ);
    localbJJ.brn();
    bqW localbqW1 = new bqW();
    localbqW1.aJ();
    localbqW1.setElementMap(localcpa);
    localbJJ.bb(localbqW1);
    localbqW1.brn();
    localbqW1.rV();
    bqW localbqW2 = new bqW();
    localbqW2.aJ();
    localbqW2.setElementMap(localcpa);
    localbJJ.bb(localbqW2);
    localbqW2.brn();
    a(localbqW2);
    localbqW2.rV();
    localbJJ.rV();
    b(localboQ2);
    localboQ2.rV();
    localanQ6.rV();
    localNK14.rV();
    d(localcWk5);
    e(localcWk5);
    localcWk5.rV();
    localdRq11.rV();
    localdRq2.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj a(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setAttribute("comparedValue");
    localNK.setName("isFromShortcut");
    parambdj.bb(localNK);
    localNK.brn();
    localNK.rV();
    return localNK;
  }

  public bdj b(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    bSP localbSP = new bSP();
    localbSP.aJ();
    localbSP.setElementMap(localcpa);
    localbSP.setValue("");
    parambdj.bb(localbSP);
    localbSP.brn();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setName("itemPopupDetail");
    localNK.setAttribute("comparedValue");
    localNK.setField("effect");
    localbSP.bb(localNK);
    localNK.brn();
    localNK.rV();
    localbSP.rV();
    return localbSP;
  }

  public bdj d(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dOc localdOc = (dOc)parambdj;
    Jg localJg = localdOc.getAppearance();
    localJg.setElementMap(localcpa);
    parambdj.bb(localJg);
    localJg.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(0, 20, 0, 0));
    localJg.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg.rV();
    return localJg;
  }

  public bdj e(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setName("itemPopupDetail");
    localNK.setAttribute("text");
    localNK.setField("effectDetails");
    parambdj.bb(localNK);
    localNK.brn();
    localNK.rV();
    return localNK;
  }
}