import java.awt.Insets;
import java.util.Stack;

public class aQQ
  implements aTK
{
  private uk W;
  private Stack X = new Stack();

  public void a(cpa paramcpa, uk paramuk, dOc paramdOc)
  {
    this.W = paramuk;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(0, 5, 0, 0));
    paramdOc.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    dOc localdOc = paramdOc;
    Jg localJg = localdOc.getAppearance();
    localJg.setElementMap(localcpa);
    ((cwJ)localJg).setAlignment(aFG.ecj);
    localJg.setState("default");
    paramdOc.bb(localJg);
    localJg.brn();
    bJA localbJA = bJA.checkOut();
    localbJA.setRenderer(cBQ.cxL().bSM().aI("defaultFont"));
    localbJA.setElementMap(localcpa);
    localJg.bb(localbJA);
    localbJA.brn();
    localbJA.rV();
    String str1 = "defaultDarkColor";
    cAf localcAf = cAf.checkOut();
    localcAf.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localcAf);
    localcAf.setColor(new bNa(0.29F, 0.17F, 0.07F, 1.0F));
    localJg.bb(localcAf);
    localcAf.brn();
    localcAf.rV();
    String str2 = "characterBookLabelBackground";
    aen localaen = aen.checkOut();
    localaen.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localaen);
    localaen.setScaled(true);
    localJg.bb(localaen);
    localaen.brn();
    aAR localaAR1 = aAR.checkOut();
    localaAR1.setElementMap(localcpa);
    localaAR1.setPosition(ajb.dhZ);
    localaAR1.setX(668);
    localaAR1.setY(176);
    localaAR1.setWidth(208);
    localaAR1.setHeight(15);
    localaAR1.setTexture(this.W.aH("default_1.tga"));
    localaen.bb(localaAR1);
    localaAR1.brn();
    localaAR1.rV();
    localaen.rV();
    String str3 = "characterBookLabelBorder";
    Cx localCx = new Cx();
    localCx.aJ();
    localCx.setElementMap(localcpa);
    if ((localcpa != null) && (str3 != null))
      localcpa.a(str3, localCx);
    localJg.bb(localCx);
    localCx.brn();
    aAR localaAR2 = aAR.checkOut();
    localaAR2.setElementMap(localcpa);
    localaAR2.setPosition(ajb.dhR);
    localaAR2.setX(841);
    localaAR2.setY(228);
    localaAR2.setWidth(4);
    localaAR2.setHeight(4);
    localaAR2.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR2);
    localaAR2.brn();
    localaAR2.rV();
    aAR localaAR3 = aAR.checkOut();
    localaAR3.setElementMap(localcpa);
    localaAR3.setPosition(ajb.dhT);
    localaAR3.setX(238);
    localaAR3.setY(132);
    localaAR3.setWidth(208);
    localaAR3.setHeight(4);
    localaAR3.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR3);
    localaAR3.brn();
    localaAR3.rV();
    aAR localaAR4 = aAR.checkOut();
    localaAR4.setElementMap(localcpa);
    localaAR4.setPosition(ajb.dhV);
    localaAR4.setX(436);
    localaAR4.setY(150);
    localaAR4.setWidth(4);
    localaAR4.setHeight(4);
    localaAR4.setTexture(this.W.aH("default_0.tga"));
    localCx.bb(localaAR4);
    localaAR4.brn();
    localaAR4.rV();
    aAR localaAR5 = aAR.checkOut();
    localaAR5.setElementMap(localcpa);
    localaAR5.setPosition(ajb.dia);
    localaAR5.setX(868);
    localaAR5.setY(728);
    localaAR5.setWidth(4);
    localaAR5.setHeight(15);
    localaAR5.setTexture(this.W.aH("default_0.tga"));
    localCx.bb(localaAR5);
    localaAR5.brn();
    localaAR5.rV();
    aAR localaAR6 = aAR.checkOut();
    localaAR6.setElementMap(localcpa);
    localaAR6.setPosition(ajb.dih);
    localaAR6.setX(396);
    localaAR6.setY(311);
    localaAR6.setWidth(4);
    localaAR6.setHeight(4);
    localaAR6.setTexture(this.W.aH("default_0.tga"));
    localCx.bb(localaAR6);
    localaAR6.brn();
    localaAR6.rV();
    aAR localaAR7 = aAR.checkOut();
    localaAR7.setElementMap(localcpa);
    localaAR7.setPosition(ajb.dif);
    localaAR7.setX(650);
    localaAR7.setY(132);
    localaAR7.setWidth(204);
    localaAR7.setHeight(4);
    localaAR7.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR7);
    localaAR7.brn();
    localaAR7.rV();
    aAR localaAR8 = aAR.checkOut();
    localaAR8.setElementMap(localcpa);
    localaAR8.setPosition(ajb.did);
    localaAR8.setX(769);
    localaAR8.setY(15);
    localaAR8.setWidth(4);
    localaAR8.setHeight(4);
    localaAR8.setTexture(this.W.aH("default_0.tga"));
    localCx.bb(localaAR8);
    localaAR8.brn();
    localaAR8.rV();
    aAR localaAR9 = aAR.checkOut();
    localaAR9.setElementMap(localcpa);
    localaAR9.setPosition(ajb.dhY);
    localaAR9.setX(868);
    localaAR9.setY(710);
    localaAR9.setWidth(4);
    localaAR9.setHeight(15);
    localaAR9.setTexture(this.W.aH("default_0.tga"));
    localCx.bb(localaAR9);
    localaAR9.brn();
    localaAR9.rV();
    localCx.rV();
    localJg.rV();
  }
}