import java.awt.Insets;
import java.util.Stack;

public class bkb
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(-2, -2));
    localcwP1.setAlign(ajb.dia);
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    czO localczO1 = new czO();
    localczO1.aJ();
    localczO1.setAdaptToContentSize(true);
    localdRq1.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setStyle("tiledScroll");
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(false);
    localdRq2.bb(localaId);
    localaId.brn();
    localaId.rV();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(25, 10, 25, 10));
    localJg1.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    cuR localcuR = new cuR();
    localcuR.aJ();
    localcuR.setElementMap(localcpa);
    localcuR.setInsets(new Insets(13, 5, 13, 5));
    localJg1.bb(localcuR);
    localcuR.brn();
    localcuR.rV();
    localJg1.rV();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localdRq2.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    ccG localccG = new ccG();
    localccG.aJ();
    localccG.setElementMap(localcpa);
    localccG.setStyle("alpha");
    localccG.setCellSize(new Or(100.0F, 65));
    localccG.setHorizontal(false);
    localccG.setPrefSize(new Or(204, 300));
    localdRq2.bb(localccG);
    localccG.brn();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.eck);
    localccG.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setName("gazettes");
    localNK.setAttribute("content");
    localccG.bb(localNK);
    localNK.brn();
    localNK.rV();
    eR localeR1 = new eR();
    localeR1.aJ();
    localeR1.setElementMap(localcpa);
    aqC localaqC = new aqC();
    localaqC.hg("wakfu.gazette:displayGazette");
    localeR1.setOnItemClick(localaqC);
    localccG.bb(localeR1);
    localeR1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localeR1.bb(localanQ1);
    localanQ1.brn();
    bxx localbxx1 = new bxx();
    localbxx1.aJ();
    localbxx1.setElementMap(localcpa);
    localanQ1.bb(localbxx1);
    localbxx1.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localbxx1.bb(localanE);
    localanE.brn();
    localanE.rV();
    localbxx1.rV();
    localanQ1.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localeR1.bb(localdRq4);
    localdRq4.brn();
    czO localczO2 = new czO();
    localczO2.aJ();
    localdRq4.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setStyle("GazetteItemBackground");
    localdRq4.bb(localczv1);
    localczv1.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setSize(new Or(-2, -2));
    localcwP3.setAlign(ajb.dhZ);
    localczv1.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    czv localczv2 = localczv1;
    Jg localJg2 = localczv2.getAppearance();
    localJg2.setElementMap(localcpa);
    localczv1.bb(localJg2);
    localJg2.brn();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("modulationColor");
    localaaE1.setField("new");
    localJg2.bb(localaaE1);
    localaaE1.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localanQ2.setValue("1,1,1,1");
    localanQ2.setElseValue("0.8,0.8,0.8,1");
    localaaE1.bb(localanQ2);
    localanQ2.brn();
    cOk localcOk = new cOk();
    localcOk.aJ();
    localcOk.setElementMap(localcpa);
    localanQ2.bb(localcOk);
    localcOk.brn();
    localcOk.rV();
    localanQ2.rV();
    localaaE1.rV();
    localJg2.rV();
    localczv1.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("StyledBoldDark10");
    localcWk1.setMinWidth(1);
    localcWk1.setMaxWidth(165);
    localcWk1.setNonBlocking(true);
    localdRq4.bb(localcWk1);
    localcWk1.brn();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setSize(new Or(-2, -2));
    localcwP4.setAlign(ajb.dhZ);
    localcwP4.setXOffset(-2);
    localcWk1.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("text");
    localaaE2.setField("title");
    localcWk1.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    localcWk1.rV();
    cWk localcWk2 = new cWk();
    localcWk2.aJ();
    localcWk2.setElementMap(localcpa);
    localcWk2.setStyle("StyledBoldDark10");
    localcWk2.setMinWidth(1);
    localcWk2.setMaxWidth(165);
    localcWk2.setNonBlocking(true);
    localdRq4.bb(localcWk2);
    localcWk2.brn();
    cwP localcwP5 = new cwP();
    localcwP5.aJ();
    localcwP5.setElementMap(localcpa);
    localcwP5.setSize(new Or(-2, -2));
    localcwP5.setAlign(ajb.dif);
    localcwP5.setXOffset(-2);
    localcwP5.setYOffset(9);
    localcWk2.bb(localcwP5);
    localcwP5.brn();
    localcwP5.rV();
    aaE localaaE3 = new aaE();
    localaaE3.aJ();
    localaaE3.setElementMap(localcpa);
    localaaE3.setAttribute("text");
    localaaE3.setField("issueNumber");
    localcWk2.bb(localaaE3);
    localaaE3.brn();
    localaaE3.rV();
    localcWk2.rV();
    localdRq4.rV();
    localeR1.rV();
    eR localeR2 = new eR();
    localeR2.aJ();
    localeR2.setElementMap(localcpa);
    localccG.bb(localeR2);
    localeR2.brn();
    anQ localanQ3 = new anQ();
    localanQ3.aJ();
    localanQ3.setElementMap(localcpa);
    localeR2.bb(localanQ3);
    localanQ3.brn();
    bxx localbxx2 = new bxx();
    localbxx2.aJ();
    localbxx2.setElementMap(localcpa);
    localanQ3.bb(localbxx2);
    localbxx2.brn();
    aIB localaIB = new aIB();
    localaIB.aJ();
    localaIB.setElementMap(localcpa);
    localbxx2.bb(localaIB);
    localaIB.brn();
    localaIB.rV();
    localbxx2.rV();
    localanQ3.rV();
    czv localczv3 = new czv();
    localczv3.aJ();
    localczv3.setElementMap(localcpa);
    localczv3.setStyle("GazetteItemBackground");
    localeR2.bb(localczv3);
    localczv3.brn();
    czv localczv4 = localczv3;
    Jg localJg3 = localczv4.getAppearance();
    localJg3.setElementMap(localcpa);
    localJg3.setModulationColor(new bNa(0.8F, 0.8F, 0.8F, 1.0F));
    localczv3.bb(localJg3);
    localJg3.brn();
    localJg3.rV();
    localczv3.rV();
    localeR2.rV();
    localccG.rV();
    localdRq2.rV();
    czv localczv5 = new czv();
    localczv5.aJ();
    localczv5.setElementMap(localcpa);
    localczv5.setStyle("ScrollBorderTop2");
    localdRq1.bb(localczv5);
    localczv5.brn();
    cwP localcwP6 = new cwP();
    localcwP6.aJ();
    localcwP6.setElementMap(localcpa);
    localcwP6.setAlign(ajb.dhT);
    localcwP6.setSize(new Or(-2, -2));
    localczv5.bb(localcwP6);
    localcwP6.brn();
    localcwP6.rV();
    localczv5.rV();
    czv localczv6 = new czv();
    localczv6.aJ();
    localczv6.setElementMap(localcpa);
    localczv6.setStyle("ScrollBorderBottom2");
    localdRq1.bb(localczv6);
    localczv6.brn();
    cwP localcwP7 = new cwP();
    localcwP7.aJ();
    localcwP7.setElementMap(localcpa);
    localcwP7.setAlign(ajb.dif);
    localcwP7.setSize(new Or(-2, -2));
    localczv6.bb(localcwP7);
    localcwP7.brn();
    localcwP7.rV();
    localczv6.rV();
    biy localbiy = new biy();
    localbiy.aJ();
    localbiy.setElementMap(localcpa);
    localbiy.setStyle("close");
    csA localcsA = new csA();
    localcsA.hg("unloadDialog");
    localbiy.setOnClick(localcsA);
    localdRq1.bb(localbiy);
    localbiy.brn();
    cwP localcwP8 = new cwP();
    localcwP8.aJ();
    localcwP8.setElementMap(localcpa);
    localcwP8.setAlign(ajb.dhV);
    localcwP8.setSize(new Or(-2, -2));
    localcwP8.setXOffset(-16);
    localcwP8.setYOffset(-13);
    localbiy.bb(localcwP8);
    localcwP8.brn();
    localcwP8.rV();
    localbiy.rV();
    localdRq1.rV();
    return localdRq1;
  }
}