import java.awt.Insets;
import java.util.Stack;

public class dMQ
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa1 = (cpa)this.X.peek();
    bpn localbpn = new bpn();
    localbpn.aJ();
    localbpn.setElementMap(localcpa1);
    localbpn.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa1);
    localcwP1.setAlign(ajb.dhY);
    localcwP1.setXOffset(75);
    localcwP1.setInitValue(true);
    localbpn.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    czO localczO1 = new czO();
    localczO1.aJ();
    localczO1.setAdaptToContentSize(true);
    localbpn.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    String str1 = "monsterPopup";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa1);
    if ((localcpa1 != null) && (str1 != null))
      localcpa1.a(str1, localanG);
    localanG.setAlign(aFG.ech);
    localanG.setHotSpotPosition(aFG.ecn);
    localbpn.bb(localanG);
    localanG.brn();
    cpa localcpa2 = localcpa1;
    localcpa1 = this.Y.nd((localcpa1 != null ? localcpa1.getId() : "") + ".creatureDescriptionTooltip");
    localcpa1.d(localcpa2);
    this.X.push(localcpa1);
    String str2 = "creatureDescriptionTooltip";
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa1);
    if ((localcpa1 != null) && (str2 != null))
      localcpa1.a(str2, localdRq1);
    localdRq1.setVisible(false);
    localanG.bb(localdRq1);
    localdRq1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa1);
    localNK1.setAttribute("visible");
    localNK1.setName("osamodasSymbiot.describedCreature");
    localdRq1.bb(localNK1);
    localNK1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa1);
    localNK1.bb(localanQ1);
    localanQ1.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa1);
    localanQ1.bb(localanE);
    localanE.brn();
    localanE.rV();
    localanQ1.rV();
    localNK1.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setAlign(aFG.ech);
    localaId1.setHorizontal(false);
    localdRq1.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa1);
    localdRq2.setExpandable(false);
    localdRq2.setStyle("popup");
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    aId localaId2 = aId.checkOut();
    localdRq2.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa1);
    localdRq3.setExpandable(false);
    localdRq3.setPrefSize(new Or(46, 46));
    localdRq2.bb(localdRq3);
    localdRq3.brn();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa1);
    localdpm1.setAlign(aFG.ech);
    localdRq3.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    czO localczO2 = new czO();
    localczO2.aJ();
    localczO2.setAdaptToContentSize(true);
    localdRq3.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    dRq localdRq4 = localdRq3;
    Jg localJg1 = localdRq4.getAppearance();
    localJg1.setElementMap(localcpa1);
    localdRq3.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa1);
    localbmv1.setInsets(new Insets(0, 0, 0, 2));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    dRq localdRq5 = dRq.checkOut();
    localdRq5.setElementMap(localcpa1);
    localdRq5.setStyle("caracs");
    localdRq3.bb(localdRq5);
    localdRq5.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa1);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localdRq5.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    localdRq5.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa1);
    localczv1.setDisplaySize(new Or(46, 46));
    localczv1.setNonBlocking(true);
    localdRq3.bb(localczv1);
    localczv1.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa1);
    localcwP3.setAlign(ajb.dhZ);
    localcwP3.setSize(new Or(-2, -2));
    localczv1.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa1);
    localczv1.bb(localaAR);
    localaAR.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa1);
    localNK2.setName("osamodasSymbiot.describedCreature");
    localNK2.setAttribute("texture");
    localNK2.setField("iconUrl");
    localaAR.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localaAR.rV();
    localczv1.rV();
    localdRq3.rV();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa1);
    localdRq6.setExpandable(false);
    localdRq2.bb(localdRq6);
    localdRq6.brn();
    aId localaId3 = aId.checkOut();
    localaId3.setHorizontal(false);
    localaId3.setAlign(aFG.ech);
    localdRq6.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa1);
    localdRq7.setExpandable(false);
    localdRq6.bb(localdRq7);
    localdRq7.brn();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa1);
    localdpm2.setAlign(aFG.ecj);
    localdRq7.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa1);
    localcWk1.setStyle("bigTitle");
    localcWk1.setNonBlocking(true);
    localcWk1.setExpandable(false);
    localcWk1.setMultiline(false);
    localdRq7.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg2 = localcWk2.getAppearance();
    localJg2.setElementMap(localcpa1);
    localcWk1.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa1);
    localbmv2.setInsets(new Insets(0, 0, 0, 10));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa1);
    localNK3.setName("osamodasSymbiot.describedCreature");
    localNK3.setAttribute("text");
    localNK3.setField("name");
    localcWk1.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    localcWk1.rV();
    dAS localdAS = new dAS();
    localdAS.aJ();
    localdAS.setElementMap(localcpa1);
    localdRq7.bb(localdAS);
    localdAS.brn();
    localdAS.rV();
    dRq localdRq8 = dRq.checkOut();
    localdRq8.setElementMap(localcpa1);
    localdRq8.setExpandable(false);
    localdRq7.bb(localdRq8);
    localdRq8.brn();
    aId localaId4 = aId.checkOut();
    localaId4.setAlign(aFG.ecl);
    localdRq8.bb(localaId4);
    localaId4.brn();
    localaId4.rV();
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa1);
    localdRq9.setExpandable(false);
    localdRq8.bb(localdRq9);
    localdRq9.brn();
    aId localaId5 = aId.checkOut();
    localaId5.setAlign(aFG.ecj);
    localdRq9.bb(localaId5);
    localaId5.brn();
    localaId5.rV();
    dRq localdRq10 = localdRq9;
    Jg localJg3 = localdRq10.getAppearance();
    localJg3.setElementMap(localcpa1);
    localdRq9.bb(localJg3);
    localJg3.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa1);
    localbmv3.setInsets(new Insets(0, 0, 0, 2));
    localJg3.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg3.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa1);
    localcaF1.setStyle("11");
    localcaF1.setExpandable(false);
    localcaF1.setNonBlocking(true);
    localdRq9.bb(localcaF1);
    localcaF1.brn();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa1);
    localNK4.setAttribute("text");
    localNK4.setField("hp");
    localNK4.setName("osamodasSymbiot.describedCreature");
    localcaF1.bb(localNK4);
    localNK4.brn();
    localNK4.rV();
    caF localcaF2 = localcaF1;
    Jg localJg4 = localcaF2.getAppearance();
    localJg4.setElementMap(localcpa1);
    localcaF1.bb(localJg4);
    localJg4.brn();
    cAf localcAf1 = cAf.checkOut();
    localcAf1.setElementMap(localcpa1);
    localcAf1.setColor(new bNa(1.0F, 1.0F, 1.0F, 1.0F));
    localJg4.bb(localcAf1);
    localcAf1.brn();
    localcAf1.rV();
    localJg4.rV();
    localcaF1.rV();
    czv localczv2 = new czv();
    localczv2.aJ();
    localczv2.setElementMap(localcpa1);
    localczv2.setStyle("iconHP");
    localczv2.setExpandable(false);
    localdRq9.bb(localczv2);
    localczv2.brn();
    localczv2.rV();
    localdRq9.rV();
    dRq localdRq11 = dRq.checkOut();
    localdRq11.setElementMap(localcpa1);
    localdRq11.setExpandable(false);
    localdRq8.bb(localdRq11);
    localdRq11.brn();
    aId localaId6 = aId.checkOut();
    localaId6.setAlign(aFG.ecj);
    localdRq11.bb(localaId6);
    localaId6.brn();
    localaId6.rV();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa1);
    localcaF3.setStyle("11");
    String str3 = "%spellDescription.levelShort%";
    str3 = str3.replace("%spellDescription.levelShort%", cBQ.cxL().mL("spellDescription.levelShort"));
    localcaF3.setText(str3);
    localcaF3.setExpandable(false);
    localcaF3.setNonBlocking(true);
    localdRq11.bb(localcaF3);
    localcaF3.brn();
    caF localcaF4 = localcaF3;
    Jg localJg5 = localcaF4.getAppearance();
    localJg5.setElementMap(localcpa1);
    localcaF3.bb(localJg5);
    localJg5.brn();
    cAf localcAf2 = cAf.checkOut();
    localcAf2.setElementMap(localcpa1);
    localcAf2.setColor(new bNa(1.0F, 1.0F, 1.0F, 1.0F));
    localJg5.bb(localcAf2);
    localcAf2.brn();
    localcAf2.rV();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa1);
    localbmv4.setInsets(new Insets(0, 0, 0, 5));
    localJg5.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg5.rV();
    localcaF3.rV();
    caF localcaF5 = new caF();
    localcaF5.aJ();
    localcaF5.setElementMap(localcpa1);
    localcaF5.setStyle("11");
    localcaF5.setExpandable(false);
    localcaF5.setNonBlocking(true);
    localdRq11.bb(localcaF5);
    localcaF5.brn();
    NK localNK5 = NK.checkOut();
    localNK5.setElementMap(localcpa1);
    localNK5.setAttribute("text");
    localNK5.setField("level");
    localNK5.setName("osamodasSymbiot.describedCreature");
    localcaF5.bb(localNK5);
    localNK5.brn();
    localNK5.rV();
    caF localcaF6 = localcaF5;
    Jg localJg6 = localcaF6.getAppearance();
    localJg6.setElementMap(localcpa1);
    localcaF5.bb(localJg6);
    localJg6.brn();
    cAf localcAf3 = cAf.checkOut();
    localcAf3.setElementMap(localcpa1);
    localcAf3.setColor(new bNa(1.0F, 1.0F, 1.0F, 1.0F));
    localJg6.bb(localcAf3);
    localcAf3.brn();
    localcAf3.rV();
    localJg6.rV();
    localcaF5.rV();
    localdRq11.rV();
    localdRq8.rV();
    localdRq7.rV();
    dRq localdRq12 = dRq.checkOut();
    localdRq12.setElementMap(localcpa1);
    localdRq12.setExpandable(false);
    localdRq6.bb(localdRq12);
    localdRq12.brn();
    aId localaId7 = aId.checkOut();
    localaId7.setAlign(aFG.ecl);
    localdRq12.bb(localaId7);
    localaId7.brn();
    localaId7.rV();
    dRq localdRq13 = dRq.checkOut();
    localdRq13.setElementMap(localcpa1);
    localdRq13.setExpandable(false);
    localdRq13.setVisible(false);
    localdRq12.bb(localdRq13);
    localdRq13.brn();
    aId localaId8 = aId.checkOut();
    localaId8.setHgap((short)2);
    localdRq13.bb(localaId8);
    localaId8.brn();
    localaId8.rV();
    NK localNK6 = NK.checkOut();
    localNK6.setElementMap(localcpa1);
    localNK6.setAttribute("visible");
    localNK6.setName("describedSpell");
    localNK6.setField("ap");
    localdRq13.bb(localNK6);
    localNK6.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa1);
    localNK6.bb(localanQ2);
    localanQ2.brn();
    aEJ localaEJ1 = new aEJ();
    localaEJ1.aJ();
    localaEJ1.setElementMap(localcpa1);
    localaEJ1.setValue("0");
    localanQ2.bb(localaEJ1);
    localaEJ1.brn();
    localaEJ1.rV();
    localanQ2.rV();
    localNK6.rV();
    caF localcaF7 = new caF();
    localcaF7.aJ();
    localcaF7.setElementMap(localcpa1);
    localcaF7.setStyle("11Light");
    localcaF7.setExpandable(false);
    localdRq13.bb(localcaF7);
    localcaF7.brn();
    NK localNK7 = NK.checkOut();
    localNK7.setElementMap(localcpa1);
    localNK7.setName("describedSpell");
    localNK7.setAttribute("text");
    localNK7.setField("ap");
    localcaF7.bb(localNK7);
    localNK7.brn();
    localNK7.rV();
    localcaF7.rV();
    czv localczv3 = new czv();
    localczv3.aJ();
    localczv3.setElementMap(localcpa1);
    localczv3.setStyle("iconAP");
    localczv3.setExpandable(false);
    localdRq13.bb(localczv3);
    localczv3.brn();
    localczv3.rV();
    dRq localdRq14 = localdRq13;
    Jg localJg7 = localdRq14.getAppearance();
    localJg7.setElementMap(localcpa1);
    localdRq13.bb(localJg7);
    localJg7.brn();
    bmv localbmv5 = bmv.checkOut();
    localbmv5.setElementMap(localcpa1);
    localbmv5.setInsets(new Insets(0, 3, 0, 0));
    localJg7.bb(localbmv5);
    localbmv5.brn();
    localbmv5.rV();
    localJg7.rV();
    localdRq13.rV();
    dRq localdRq15 = dRq.checkOut();
    localdRq15.setElementMap(localcpa1);
    localdRq15.setExpandable(false);
    localdRq15.setVisible(false);
    localdRq12.bb(localdRq15);
    localdRq15.brn();
    aId localaId9 = aId.checkOut();
    localaId9.setHgap((short)2);
    localdRq15.bb(localaId9);
    localaId9.brn();
    localaId9.rV();
    NK localNK8 = NK.checkOut();
    localNK8.setElementMap(localcpa1);
    localNK8.setAttribute("visible");
    localNK8.setName("describedSpell");
    localNK8.setField("mp");
    localdRq15.bb(localNK8);
    localNK8.brn();
    anQ localanQ3 = new anQ();
    localanQ3.aJ();
    localanQ3.setElementMap(localcpa1);
    localNK8.bb(localanQ3);
    localanQ3.brn();
    aEJ localaEJ2 = new aEJ();
    localaEJ2.aJ();
    localaEJ2.setElementMap(localcpa1);
    localaEJ2.setValue("0");
    localanQ3.bb(localaEJ2);
    localaEJ2.brn();
    localaEJ2.rV();
    localanQ3.rV();
    localNK8.rV();
    caF localcaF8 = new caF();
    localcaF8.aJ();
    localcaF8.setElementMap(localcpa1);
    localcaF8.setStyle("11Light");
    localcaF8.setExpandable(false);
    localdRq15.bb(localcaF8);
    localcaF8.brn();
    NK localNK9 = NK.checkOut();
    localNK9.setElementMap(localcpa1);
    localNK9.setName("describedSpell");
    localNK9.setAttribute("text");
    localNK9.setField("mp");
    localcaF8.bb(localNK9);
    localNK9.brn();
    localNK9.rV();
    localcaF8.rV();
    czv localczv4 = new czv();
    localczv4.aJ();
    localczv4.setElementMap(localcpa1);
    localczv4.setStyle("iconMP");
    localczv4.setExpandable(false);
    localdRq15.bb(localczv4);
    localczv4.brn();
    localczv4.rV();
    dRq localdRq16 = localdRq15;
    Jg localJg8 = localdRq16.getAppearance();
    localJg8.setElementMap(localcpa1);
    localdRq15.bb(localJg8);
    localJg8.brn();
    bmv localbmv6 = bmv.checkOut();
    localbmv6.setElementMap(localcpa1);
    localbmv6.setInsets(new Insets(0, 3, 0, 0));
    localJg8.bb(localbmv6);
    localbmv6.brn();
    localbmv6.rV();
    localJg8.rV();
    localdRq15.rV();
    a(localdRq12);
    b(localdRq12);
    localdRq12.rV();
    d(localdRq6);
    localdRq6.rV();
    localdRq2.rV();
    localdRq1.rV();
    this.X.pop();
    localcpa1 = (cpa)this.X.peek();
    localanG.rV();
    e(localbpn);
    f(localbpn);
    g(localbpn);
    h(localbpn);
    i(localbpn);
    localbpn.rV();
    return localbpn;
  }

  public bdj a(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    localdRq1.setVisible(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    aId localaId = aId.checkOut();
    localaId.setHgap((short)2);
    localdRq1.bb(localaId);
    localaId.brn();
    localaId.rV();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("visible");
    localNK1.setName("describedSpell");
    localNK1.setField("wp");
    localdRq1.bb(localNK1);
    localNK1.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localNK1.bb(localanQ);
    localanQ.brn();
    aEJ localaEJ = new aEJ();
    localaEJ.aJ();
    localaEJ.setElementMap(localcpa);
    localaEJ.setValue("0");
    localanQ.bb(localaEJ);
    localaEJ.brn();
    localaEJ.rV();
    localanQ.rV();
    localNK1.rV();
    caF localcaF = new caF();
    localcaF.aJ();
    localcaF.setElementMap(localcpa);
    localcaF.setStyle("11Light");
    localcaF.setExpandable(false);
    localdRq1.bb(localcaF);
    localcaF.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("describedSpell");
    localNK2.setAttribute("text");
    localNK2.setField("wp");
    localcaF.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localcaF.rV();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setStyle("iconWP");
    localczv.setExpandable(false);
    localdRq1.bb(localczv);
    localczv.brn();
    localczv.rV();
    dRq localdRq2 = localdRq1;
    Jg localJg = localdRq2.getAppearance();
    localJg.setElementMap(localcpa);
    localdRq1.bb(localJg);
    localJg.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(0, 3, 0, 0));
    localJg.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj b(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    dRq localdRq2 = localdRq1;
    Jg localJg1 = localdRq2.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq1.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(2, 0, 0, 0));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.ecl);
    localdRq1.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    aId localaId = aId.checkOut();
    localaId.setHgap((short)2);
    localdRq1.bb(localaId);
    localaId.brn();
    localaId.rV();
    caF localcaF = new caF();
    localcaF.aJ();
    localcaF.setElementMap(localcpa);
    localcaF.setStyle("11Light");
    localdRq1.bb(localcaF);
    localcaF.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setName("describedSpell");
    localNK1.setAttribute("text");
    localNK1.setField("range");
    localcaF.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    localcaF.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setStyle("rangeIcon");
    localczv1.setExpandable(false);
    localdRq1.bb(localczv1);
    localczv1.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("describedSpell");
    localNK2.setAttribute("style");
    localNK2.setField("testLineOfSight");
    localczv1.bb(localNK2);
    localNK2.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localanQ.setValue("rangeIcon");
    localanQ.setElseValue("noLineOfSightIcon");
    localNK2.bb(localanQ);
    localanQ.brn();
    cOk localcOk = new cOk();
    localcOk.aJ();
    localcOk.setElementMap(localcpa);
    localanQ.bb(localcOk);
    localcOk.brn();
    localcOk.rV();
    localanQ.rV();
    localNK2.rV();
    localczv1.rV();
    czv localczv2 = new czv();
    localczv2.aJ();
    localczv2.setElementMap(localcpa);
    localczv2.setStyle("UnlockedRange");
    localczv2.setExpandable(false);
    localczv2.setNonBlocking(false);
    localdRq1.bb(localczv2);
    localczv2.brn();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setName("describedSpell");
    localNK3.setAttribute("visible");
    localNK3.setField("modifiableRange");
    localczv2.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    localczv2.rV();
    dRq localdRq3 = localdRq1;
    Jg localJg2 = localdRq3.getAppearance();
    localJg2.setElementMap(localcpa);
    localdRq1.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 3, 0, 0));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj d(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setName("osamodasSymbiot.describedCreature");
    localNK1.setAttribute("visible");
    localNK1.setField("unavailableReasons");
    localdRq1.bb(localNK1);
    localNK1.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localNK1.bb(localanQ);
    localanQ.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localanQ.bb(localanE);
    localanE.brn();
    localanE.rV();
    localanQ.rV();
    localNK1.rV();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(false);
    localaId.setAlign(aFG.ech);
    localdRq1.bb(localaId);
    localaId.brn();
    localaId.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setExpandable(false);
    localdRq2.setStyle("lineSeparator2");
    localdRq2.setPrefSize(new Or(50, 1));
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(2, 20, 2, 20));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    localdRq2.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("white11");
    localcWk1.setMultiline(true);
    localcWk1.setMinWidth(250);
    localcWk1.setMaxWidth(250);
    localcWk1.setExpandable(false);
    localdRq1.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg2 = localcWk2.getAppearance();
    localJg2.setElementMap(localcpa);
    localcWk1.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 5, 0, 0));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    cAf localcAf = cAf.checkOut();
    localcAf.setElementMap(localcpa);
    localcAf.setColor(new bNa(1.0F, 0.0F, 0.0F, 1.0F));
    localcAf.setName("text");
    localJg2.bb(localcAf);
    localcAf.brn();
    localcAf.rV();
    localJg2.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("osamodasSymbiot.describedCreature");
    localNK2.setAttribute("text");
    localNK2.setField("unavailableReasons");
    localcWk1.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localcWk1.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj e(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setStyle("OsamodasSymbioteBackground");
    localczv.setNonBlocking(true);
    parambdj.bb(localczv);
    localczv.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setAlign(ajb.dhZ);
    localcwP.setSize(new Or(269, 116));
    localczv.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localczv.rV();
    return localczv;
  }

  public bdj f(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dqa localdqa = new dqa();
    localdqa.aJ();
    localdqa.setElementMap(localcpa);
    parambdj.bb(localdqa);
    localdqa.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setAlign(ajb.dhZ);
    localcwP.setSize(new Or(90.0F, 80.0F));
    localdqa.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localdqa.rV();
    return localdqa;
  }

  public bdj g(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setMinWidth(1);
    localcWk1.setMaxWidth(20);
    localcWk1.setStyle("White16Bordered");
    localcWk1.setNonBlocking(false);
    cCu localcCu = new cCu();
    localcCu.hg("popup(leaderShipCapacityPopup)");
    localcWk1.setOnPopupDisplay(localcCu);
    jL localjL = new jL();
    localjL.hg("closePopup");
    localcWk1.setOnPopupHide(localjL);
    parambdj.bb(localcWk1);
    localcWk1.brn();
    String str1 = "leaderShipCapacityPopup";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localanG);
    localanG.setAlign(aFG.eci);
    localanG.setHotSpotPosition(aFG.ecm);
    localcWk1.bb(localanG);
    localanG.brn();
    dRq localdRq = dRq.checkOut();
    localdRq.setElementMap(localcpa);
    localdRq.setPrefSize(new Or(10, 0));
    localdRq.setStyle("popup");
    localanG.bb(localdRq);
    localdRq.brn();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(false);
    localaId.setAlign(aFG.ech);
    localdRq.bb(localaId);
    localaId.brn();
    localaId.rV();
    cWk localcWk2 = new cWk();
    localcWk2.aJ();
    localcWk2.setElementMap(localcpa);
    localcWk2.setMinWidth(100);
    localcWk2.setStyle("white11");
    String str2 = "%leaderShipCapacityDescription%";
    str2 = str2.replace("%leaderShipCapacityDescription%", cBQ.cxL().mL("leaderShipCapacityDescription"));
    localcWk2.setText(str2);
    localdRq.bb(localcWk2);
    localcWk2.brn();
    localcWk2.rV();
    localdRq.rV();
    localanG.rV();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setAlign(ajb.dhR);
    localcwP.setXOffset(40);
    localcwP.setYOffset(-7);
    localcWk1.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setAttribute("text");
    localNK.setName("osamodasSymbiot");
    localNK.setField("currentLeadershipCapacity");
    localcWk1.bb(localNK);
    localNK.brn();
    localNK.rV();
    localcWk1.rV();
    return localcWk1;
  }

  public bdj h(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    String str1 = "list";
    ccG localccG = new ccG();
    localccG.aJ();
    localccG.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localccG);
    localccG.setScrollBar(false);
    localccG.setCellSize(new Or(39, 45));
    localccG.setAutoIdealSize(true);
    localccG.setIdealSizeMaxRows(1);
    localccG.setIdealSizeMinRows(1);
    localccG.setIdealSizeMaxColumns(5);
    localccG.setIdealSizeMinColumns(5);
    anx localanx = new anx();
    localanx.hg("wakfu.popupInfos:showPopup(monsterPopup,list);wakfu.osamodasSymbiot:monsterPopup");
    localccG.setOnItemOver(localanx);
    cVk localcVk = new cVk();
    localcVk.hg("closePopup;wakfu.osamodasSymbiot:closeMonsterPopup");
    localccG.setOnItemOut(localcVk);
    localccG.setNonBlocking(true);
    parambdj.bb(localccG);
    localccG.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setAlign(ajb.dif);
    localcwP1.setSize(new Or(-2, -2));
    localcwP1.setXOffset(7);
    localcwP1.setYOffset(14);
    localccG.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setName("osamodasSymbiot");
    localNK1.setField("capturedCreatures");
    localNK1.setAttribute("content");
    localccG.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    eR localeR1 = new eR();
    localeR1.aJ();
    localeR1.setElementMap(localcpa);
    vT localvT = new vT();
    localvT.hg("wakfu.osamodasSymbiot:selectNextCreature()");
    localeR1.setOnMouseWheel(localvT);
    aqC localaqC = new aqC();
    localaqC.hg("wakfu.osamodasSymbiot:selectCreature()");
    localeR1.setOnItemClick(localaqC);
    localccG.bb(localeR1);
    localeR1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localeR1.bb(localanQ1);
    localanQ1.brn();
    bxx localbxx1 = new bxx();
    localbxx1.aJ();
    localbxx1.setElementMap(localcpa);
    localanQ1.bb(localbxx1);
    localbxx1.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localbxx1.bb(localanE);
    localanE.brn();
    localanE.rV();
    localbxx1.rV();
    localanQ1.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setStyle("ShortcutBarBoxBackground");
    localdRq1.setNonBlocking(false);
    localeR1.bb(localdRq1);
    localdRq1.brn();
    dRq localdRq2 = localdRq1;
    Jg localJg1 = localdRq2.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq1.bb(localJg1);
    localJg1.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setName("osamodasSymbiot");
    localNK2.setField("selectedCreature");
    localNK2.setAttribute("modulationColor");
    localJg1.bb(localNK2);
    localNK2.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localanQ2.setElseValue("0.37,0.32,0.24");
    localanQ2.setValue("1,1,1");
    localNK2.bb(localanQ2);
    localanQ2.brn();
    bSP localbSP = new bSP();
    localbSP.aJ();
    localbSP.setElementMap(localcpa);
    localanQ2.bb(localbSP);
    localbSP.brn();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("value");
    localbSP.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    localbSP.rV();
    localanQ2.rV();
    localNK2.rV();
    cuR localcuR = new cuR();
    localcuR.aJ();
    localcuR.setElementMap(localcpa);
    localcuR.setInsets(new Insets(6, 4, 8, 4));
    localJg1.bb(localcuR);
    localcuR.brn();
    localcuR.rV();
    localJg1.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq1.bb(localdRq3);
    localdRq3.brn();
    czO localczO1 = new czO();
    localczO1.aJ();
    localdRq3.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setNonBlocking(true);
    localczv1.setScaled(true);
    localczv1.setDisplaySize(new Or(31, 31));
    localdRq3.bb(localczv1);
    localczv1.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.dhZ);
    localczv1.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    czv localczv2 = localczv1;
    Jg localJg2 = localczv2.getAppearance();
    localJg2.setElementMap(localcpa);
    localczv1.bb(localJg2);
    localJg2.brn();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setField("isAvailable");
    localaaE2.setAttribute("modulationColor");
    localJg2.bb(localaaE2);
    localaaE2.brn();
    anQ localanQ3 = new anQ();
    localanQ3.aJ();
    localanQ3.setElementMap(localcpa);
    localanQ3.setValue("1,1,1");
    localanQ3.setElseValue("0.3,0.3,0.3");
    localaaE2.bb(localanQ3);
    localanQ3.brn();
    cOk localcOk = new cOk();
    localcOk.aJ();
    localcOk.setElementMap(localcpa);
    localanQ3.bb(localcOk);
    localcOk.brn();
    localcOk.rV();
    localanQ3.rV();
    localaaE2.rV();
    localJg2.rV();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv1.bb(localaAR);
    localaAR.brn();
    aaE localaaE3 = new aaE();
    localaaE3.aJ();
    localaaE3.setElementMap(localcpa);
    localaaE3.setAttribute("texture");
    localaaE3.setField("iconUrl");
    localaAR.bb(localaaE3);
    localaaE3.brn();
    localaaE3.rV();
    localaAR.rV();
    localczv1.rV();
    localdRq3.rV();
    localdRq1.rV();
    localeR1.rV();
    eR localeR2 = new eR();
    localeR2.aJ();
    localeR2.setElementMap(localcpa);
    localccG.bb(localeR2);
    localeR2.brn();
    anQ localanQ4 = new anQ();
    localanQ4.aJ();
    localanQ4.setElementMap(localcpa);
    localeR2.bb(localanQ4);
    localanQ4.brn();
    bJJ localbJJ1 = new bJJ();
    localbJJ1.aJ();
    localbJJ1.setElementMap(localcpa);
    localanQ4.bb(localbJJ1);
    localbJJ1.brn();
    bxx localbxx2 = new bxx();
    localbxx2.aJ();
    localbxx2.setElementMap(localcpa);
    localbJJ1.bb(localbxx2);
    localbxx2.brn();
    aIB localaIB1 = new aIB();
    localaIB1.aJ();
    localaIB1.setElementMap(localcpa);
    localbxx2.bb(localaIB1);
    localaIB1.brn();
    localaIB1.rV();
    localbxx2.rV();
    dlQ localdlQ1 = new dlQ();
    localdlQ1.aJ();
    localdlQ1.setElementMap(localcpa);
    localdlQ1.setKey("tableIndex");
    localbJJ1.bb(localdlQ1);
    localdlQ1.brn();
    asH localasH1 = new asH();
    localasH1.aJ();
    localasH1.setElementMap(localcpa);
    localdlQ1.bb(localasH1);
    localasH1.brn();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setName("osamodasSymbiot");
    localNK3.setField("maxSize");
    localNK3.setAttribute("value");
    localasH1.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    localasH1.rV();
    localdlQ1.rV();
    localbJJ1.rV();
    localanQ4.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setPrefSize(new Or(25, 25));
    localdRq4.setStyle("ShortcutBarBoxBackground");
    localeR2.bb(localdRq4);
    localdRq4.brn();
    dRq localdRq5 = localdRq4;
    Jg localJg3 = localdRq5.getAppearance();
    localJg3.setElementMap(localcpa);
    localJg3.setModulationColor(new bNa(0.37F, 0.32F, 0.24F, 1.0F));
    localdRq4.bb(localJg3);
    localJg3.brn();
    localJg3.rV();
    localdRq4.rV();
    localeR2.rV();
    eR localeR3 = new eR();
    localeR3.aJ();
    localeR3.setElementMap(localcpa);
    localccG.bb(localeR3);
    localeR3.brn();
    anQ localanQ5 = new anQ();
    localanQ5.aJ();
    localanQ5.setElementMap(localcpa);
    localeR3.bb(localanQ5);
    localanQ5.brn();
    bJJ localbJJ2 = new bJJ();
    localbJJ2.aJ();
    localbJJ2.setElementMap(localcpa);
    localanQ5.bb(localbJJ2);
    localbJJ2.brn();
    bxx localbxx3 = new bxx();
    localbxx3.aJ();
    localbxx3.setElementMap(localcpa);
    localbJJ2.bb(localbxx3);
    localbxx3.brn();
    aIB localaIB2 = new aIB();
    localaIB2.aJ();
    localaIB2.setElementMap(localcpa);
    localbxx3.bb(localaIB2);
    localaIB2.brn();
    localaIB2.rV();
    localbxx3.rV();
    dlQ localdlQ2 = new dlQ();
    localdlQ2.aJ();
    localdlQ2.setElementMap(localcpa);
    localdlQ2.setKey("tableIndex");
    localbJJ2.bb(localdlQ2);
    localdlQ2.brn();
    dDu localdDu = new dDu();
    localdDu.aJ();
    localdDu.setElementMap(localcpa);
    localdlQ2.bb(localdDu);
    localdDu.brn();
    asH localasH2 = new asH();
    localasH2.aJ();
    localasH2.setElementMap(localcpa);
    localdDu.bb(localasH2);
    localasH2.brn();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa);
    localNK4.setName("osamodasSymbiot");
    localNK4.setField("maxSize");
    localNK4.setAttribute("value");
    localasH2.bb(localNK4);
    localNK4.brn();
    localNK4.rV();
    localasH2.rV();
    localdDu.rV();
    localdlQ2.rV();
    localbJJ2.rV();
    localanQ5.rV();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq6.setPrefSize(new Or(25, 25));
    localdRq6.setStyle("ShortcutBarBoxBackground");
    cCu localcCu = new cCu();
    localcCu.hg("popup(levelUpGobgobForSlots)");
    localdRq6.setOnPopupDisplay(localcCu);
    jL localjL = new jL();
    localjL.hg("closePopup");
    localdRq6.setOnPopupHide(localjL);
    localeR3.bb(localdRq6);
    localdRq6.brn();
    String str2 = "levelUpGobgobForSlots";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localanG);
    localanG.setAlign(aFG.ech);
    localanG.setHotSpotPosition(aFG.ecn);
    localdRq6.bb(localanG);
    localanG.brn();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localdRq7.setPrefSize(new Or(10, 0));
    localdRq7.setStyle("popup");
    localanG.bb(localdRq7);
    localdRq7.brn();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(false);
    localaId.setAlign(aFG.ech);
    localdRq7.bb(localaId);
    localaId.brn();
    localaId.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setMinWidth(100);
    localcWk1.setStyle("white11");
    String str3 = "%desc.levelUpGobgobForSlots%";
    str3 = str3.replace("%desc.levelUpGobgobForSlots%", cBQ.cxL().mL("desc.levelUpGobgobForSlots"));
    localcWk1.setText(str3);
    localdRq7.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg4 = localcWk2.getAppearance();
    localJg4.setElementMap(localcpa);
    localcWk1.bb(localJg4);
    localJg4.brn();
    cAf localcAf = cAf.checkOut();
    localcAf.setElementMap(localcpa);
    localcAf.setColor(new bNa(1.0F, 0.0F, 0.0F, 1.0F));
    localcAf.setName("text");
    localJg4.bb(localcAf);
    localcAf.brn();
    localcAf.rV();
    localJg4.rV();
    localcWk1.rV();
    localdRq7.rV();
    localanG.rV();
    dRq localdRq8 = localdRq6;
    Jg localJg5 = localdRq8.getAppearance();
    localJg5.setElementMap(localcpa);
    localJg5.setModulationColor(new bNa(0.37F, 0.32F, 0.24F, 1.0F));
    localdRq6.bb(localJg5);
    localJg5.brn();
    localJg5.rV();
    czO localczO2 = new czO();
    localczO2.aJ();
    localdRq6.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa);
    localdRq9.setPrefSize(new Or(29, 29));
    localdRq6.bb(localdRq9);
    localdRq9.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setAlign(ajb.dhZ);
    localdRq9.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    dRq localdRq10 = localdRq9;
    Jg localJg6 = localdRq10.getAppearance();
    localJg6.setElementMap(localcpa);
    localdRq9.bb(localJg6);
    localJg6.brn();
    jO localjO = new jO();
    localjO.aJ();
    localjO.setElementMap(localcpa);
    localjO.setColor(new bNa(0.0F, 0.0F, 0.0F, 0.5F));
    localJg6.bb(localjO);
    localjO.brn();
    localjO.rV();
    localJg6.rV();
    localdRq9.rV();
    czv localczv3 = new czv();
    localczv3.aJ();
    localczv3.setElementMap(localcpa);
    localczv3.setStyle("PadLock");
    localczv3.setDisplaySize(new Or(16, 23));
    localdRq6.bb(localczv3);
    localczv3.brn();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setAlign(ajb.dhZ);
    localczv3.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    localczv3.rV();
    localdRq6.rV();
    localeR3.rV();
    String str4 = "creatureId";
    avo localavo = new avo();
    localavo.aJ();
    localavo.setElementMap(localcpa);
    if ((localcpa != null) && (str4 != null))
      localcpa.a(str4, localavo);
    localccG.bb(localavo);
    localavo.brn();
    aaE localaaE4 = new aaE();
    localaaE4.aJ();
    localaaE4.setElementMap(localcpa);
    localaaE4.setField("id");
    localaaE4.setAttribute("value");
    localavo.bb(localaaE4);
    localaaE4.brn();
    localaaE4.rV();
    localavo.rV();
    localccG.rV();
    return localccG;
  }

  public bdj i(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    biy localbiy = new biy();
    localbiy.aJ();
    localbiy.setElementMap(localcpa);
    localbiy.setStyle("SymbioteClose");
    csA localcsA = new csA();
    localcsA.hg("unloadDialog");
    localbiy.setOnClick(localcsA);
    parambdj.bb(localbiy);
    localbiy.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setAlign(ajb.dia);
    localcwP.setYOffset(10);
    localcwP.setXOffset(-12);
    localbiy.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localbiy.rV();
    return localbiy;
  }
}