import java.util.Stack;

public class dUR
  implements aTK
{
  private uk W;
  private Stack X = new Stack();

  public void a(cpa paramcpa, uk paramuk, dOc paramdOc)
  {
    this.W = paramuk;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    dOc localdOc = paramdOc;
    Jg localJg = localdOc.getAppearance();
    localJg.setElementMap(localcpa);
    ((cwJ)localJg).setAlignment(aFG.eck);
    paramdOc.bb(localJg);
    localJg.brn();
    bJA localbJA = bJA.checkOut();
    localbJA.setRenderer(cBQ.cxL().bSM().aI("defaultBoldFont"));
    localbJA.setElementMap(localcpa);
    localJg.bb(localbJA);
    localbJA.brn();
    localbJA.rV();
    String str1 = "defaultBlackColor";
    cAf localcAf = cAf.checkOut();
    localcAf.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localcAf);
    localcAf.setColor(new bNa(0.1F, 0.1F, 0.1F, 1.0F));
    localJg.bb(localcAf);
    localcAf.brn();
    localcAf.rV();
    String str2 = "lightBorder";
    Cx localCx = new Cx();
    localCx.aJ();
    localCx.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localCx);
    localJg.bb(localCx);
    localCx.brn();
    aAR localaAR1 = aAR.checkOut();
    localaAR1.setElementMap(localcpa);
    localaAR1.setPosition(ajb.dhR);
    localaAR1.setX(800);
    localaAR1.setY(4);
    localaAR1.setWidth(5);
    localaAR1.setHeight(5);
    localaAR1.setTexture(this.W.aH("default_0.tga"));
    localCx.bb(localaAR1);
    localaAR1.brn();
    localaAR1.rV();
    aAR localaAR2 = aAR.checkOut();
    localaAR2.setElementMap(localcpa);
    localaAR2.setPosition(ajb.dhT);
    localaAR2.setX(100);
    localaAR2.setY(140);
    localaAR2.setWidth(27);
    localaAR2.setHeight(5);
    localaAR2.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR2);
    localaAR2.brn();
    localaAR2.rV();
    aAR localaAR3 = aAR.checkOut();
    localaAR3.setElementMap(localcpa);
    localaAR3.setPosition(ajb.dhV);
    localaAR3.setX(74);
    localaAR3.setY(755);
    localaAR3.setWidth(5);
    localaAR3.setHeight(5);
    localaAR3.setTexture(this.W.aH("default_0.tga"));
    localCx.bb(localaAR3);
    localaAR3.brn();
    localaAR3.rV();
    aAR localaAR4 = aAR.checkOut();
    localaAR4.setElementMap(localcpa);
    localaAR4.setPosition(ajb.dia);
    localaAR4.setX(74);
    localaAR4.setY(763);
    localaAR4.setWidth(5);
    localaAR4.setHeight(27);
    localaAR4.setTexture(this.W.aH("default_0.tga"));
    localCx.bb(localaAR4);
    localaAR4.brn();
    localaAR4.rV();
    aAR localaAR5 = aAR.checkOut();
    localaAR5.setElementMap(localcpa);
    localaAR5.setPosition(ajb.dih);
    localaAR5.setX(622);
    localaAR5.setY(179);
    localaAR5.setWidth(5);
    localaAR5.setHeight(5);
    localaAR5.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR5);
    localaAR5.brn();
    localaAR5.rV();
    aAR localaAR6 = aAR.checkOut();
    localaAR6.setElementMap(localcpa);
    localaAR6.setPosition(ajb.dif);
    localaAR6.setX(70);
    localaAR6.setY(140);
    localaAR6.setWidth(27);
    localaAR6.setHeight(5);
    localaAR6.setTexture(this.W.aH("default_1.tga"));
    localCx.bb(localaAR6);
    localaAR6.brn();
    localaAR6.rV();
    aAR localaAR7 = aAR.checkOut();
    localaAR7.setElementMap(localcpa);
    localaAR7.setPosition(ajb.did);
    localaAR7.setX(337);
    localaAR7.setY(249);
    localaAR7.setWidth(5);
    localaAR7.setHeight(5);
    localaAR7.setTexture(this.W.aH("default_0.tga"));
    localCx.bb(localaAR7);
    localaAR7.brn();
    localaAR7.rV();
    aAR localaAR8 = aAR.checkOut();
    localaAR8.setElementMap(localcpa);
    localaAR8.setPosition(ajb.dhY);
    localaAR8.setX(74);
    localaAR8.setY(793);
    localaAR8.setWidth(5);
    localaAR8.setHeight(27);
    localaAR8.setTexture(this.W.aH("default_0.tga"));
    localCx.bb(localaAR8);
    localaAR8.brn();
    localaAR8.rV();
    localCx.rV();
    String str3 = "lightBackground";
    aen localaen = aen.checkOut();
    localaen.setElementMap(localcpa);
    if ((localcpa != null) && (str3 != null))
      localcpa.a(str3, localaen);
    localaen.setScaled(true);
    localJg.bb(localaen);
    localaen.brn();
    aAR localaAR9 = aAR.checkOut();
    localaAR9.setElementMap(localcpa);
    localaAR9.setPosition(ajb.dhZ);
    localaAR9.setX(81);
    localaAR9.setY(83);
    localaAR9.setWidth(27);
    localaAR9.setHeight(27);
    localaAR9.setTexture(this.W.aH("default_0.tga"));
    localaen.bb(localaAR9);
    localaAR9.brn();
    localaAR9.rV();
    localaen.rV();
    localJg.rV();
  }
}