import java.awt.Insets;
import java.util.Stack;

public class GQ
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    bpn localbpn = new bpn();
    localbpn.aJ();
    localbpn.setElementMap(localcpa);
    localbpn.setPack(true);
    localbpn.brn();
    czO localczO1 = new czO();
    localczO1.aJ();
    localczO1.setAdaptToContentSize(true);
    localbpn.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localbpn.bb(localdRq1);
    localdRq1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    localdRq1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setStyle("windowNew");
    localbpn.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(10, 5, 12, 5));
    localJg1.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    localJg1.rV();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localdRq2.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localaId1.setAlign(aFG.ech);
    localdRq2.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dqa localdqa1 = new dqa();
    localdqa1.aJ();
    localdqa1.setElementMap(localcpa);
    localdqa1.setExpandable(false);
    localdRq2.bb(localdqa1);
    localdqa1.brn();
    dqa localdqa2 = localdqa1;
    Jg localJg2 = localdqa2.getAppearance();
    localJg2.setElementMap(localcpa);
    localdqa1.bb(localJg2);
    localJg2.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 10, 0, 10));
    localJg2.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg2.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setStyle("titleBar");
    localdqa1.bb(localdRq4);
    localdRq4.brn();
    dRq localdRq5 = localdRq4;
    Jg localJg3 = localdRq5.getAppearance();
    localJg3.setElementMap(localcpa);
    localdRq4.bb(localJg3);
    localJg3.brn();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(2, 20, 3, 20));
    localJg3.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    localJg3.rV();
    aId localaId2 = aId.checkOut();
    localaId2.setHorizontal(false);
    localdRq4.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq6.setExpandable(false);
    localdRq4.bb(localdRq6);
    localdRq6.brn();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa);
    localdpm1.setAlign(aFG.eck);
    localdRq6.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("StyledBold16White");
    localcaF1.setNonBlocking(true);
    String str1 = "%nationSelection.title%";
    str1 = str1.replace("%nationSelection.title%", cBQ.cxL().mL("nationSelection.title"));
    localcaF1.setText(str1);
    localdRq6.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg4 = localcaF2.getAppearance();
    localJg4.setElementMap(localcpa);
    ((cwJ)localJg4).setAlignment(aFG.eck);
    localcaF1.bb(localJg4);
    localJg4.brn();
    localJg4.rV();
    localcaF1.rV();
    localdRq6.rV();
    localdRq4.rV();
    localdqa1.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localdRq2.bb(localdRq7);
    localdRq7.brn();
    dRq localdRq8 = localdRq7;
    Jg localJg5 = localdRq8.getAppearance();
    localJg5.setElementMap(localcpa);
    localdRq7.bb(localJg5);
    localJg5.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 12, 0, 12));
    localJg5.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg5.rV();
    String str2 = "windowContentContainer";
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localdRq9);
    localdRq7.bb(localdRq9);
    localdRq9.brn();
    String str3 = "list";
    ccG localccG = new ccG();
    localccG.aJ();
    localccG.setElementMap(localcpa);
    if ((localcpa != null) && (str3 != null))
      localcpa.a(str3, localccG);
    localccG.setPrefSize(new Or(960, 460));
    localccG.setCellSize(new Or(240, 460));
    localdRq9.bb(localccG);
    localccG.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("content");
    localNK1.setName("nationSelectionList");
    localccG.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    eR localeR = new eR();
    localeR.aJ();
    localeR.setElementMap(localcpa);
    localccG.bb(localeR);
    localeR.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localeR.bb(localanQ1);
    localanQ1.brn();
    bxx localbxx = new bxx();
    localbxx.aJ();
    localbxx.setElementMap(localcpa);
    localanQ1.bb(localbxx);
    localbxx.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localbxx.bb(localanE);
    localanE.brn();
    localanE.rV();
    localbxx.rV();
    localanQ1.rV();
    String str4 = "nationSelection";
    avo localavo = new avo();
    localavo.aJ();
    localavo.setElementMap(localcpa);
    if ((localcpa != null) && (str4 != null))
      localcpa.a(str4, localavo);
    localeR.bb(localavo);
    localavo.brn();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("value");
    localavo.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    localavo.rV();
    dRq localdRq10 = dRq.checkOut();
    localdRq10.setElementMap(localcpa);
    localdRq10.setNonBlocking(false);
    bDy localbDy = new bDy();
    localbDy.hg("wakfu.nationSelectionPanel:onMouseOverElement(nationSelection)");
    localdRq10.setOnMouseEnter(localbDy);
    DY localDY = new DY();
    localDY.hg("wakfu.nationSelectionPanel:onMouseOutElement");
    localdRq10.setOnMouseExit(localDY);
    localeR.bb(localdRq10);
    localdRq10.brn();
    czO localczO2 = new czO();
    localczO2.aJ();
    localczO2.setAdaptToContentSize(true);
    localdRq10.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    dRq localdRq11 = dRq.checkOut();
    localdRq11.setElementMap(localcpa);
    localdRq11.setExpandable(false);
    localdRq11.setPrefSize(new Or(220, 60));
    localdRq10.bb(localdRq11);
    localdRq11.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setAlign(ajb.dif);
    localcwP3.setXOffset(-10);
    localdRq11.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    dRq localdRq12 = localdRq11;
    Jg localJg6 = localdRq12.getAppearance();
    localJg6.setElementMap(localcpa);
    localdRq11.bb(localJg6);
    localJg6.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(20, 0, 0, 0));
    localJg6.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg6.rV();
    czO localczO3 = new czO();
    localczO3.aJ();
    localczO3.setAdaptToContentSize(true);
    localdRq11.bb(localczO3);
    localczO3.brn();
    localczO3.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setStyle("TimelineTimerBackgroundVerticalFlip");
    localczv1.setDisplaySize(new Or(57, 36));
    localczv1.setNonBlocking(false);
    localdRq11.bb(localczv1);
    localczv1.brn();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setAlign(ajb.dhY);
    localczv1.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    czv localczv2 = localczv1;
    Jg localJg7 = localczv2.getAppearance();
    localJg7.setElementMap(localcpa);
    localJg7.setModulationColor(new bNa(1.0F, 1.0F, 1.0F, 0.3F));
    localczv1.bb(localJg7);
    localJg7.brn();
    localJg7.rV();
    localczv1.rV();
    czv localczv3 = new czv();
    localczv3.aJ();
    localczv3.setElementMap(localcpa);
    localczv3.setStyle("TimelineTimerBackgroundVerticalHorizontalFlip");
    localczv3.setDisplaySize(new Or(57, 36));
    localczv3.setNonBlocking(false);
    localdRq11.bb(localczv3);
    localczv3.brn();
    cwP localcwP5 = new cwP();
    localcwP5.aJ();
    localcwP5.setElementMap(localcpa);
    localcwP5.setAlign(ajb.dia);
    localczv3.bb(localcwP5);
    localcwP5.brn();
    localcwP5.rV();
    czv localczv4 = localczv3;
    Jg localJg8 = localczv4.getAppearance();
    localJg8.setElementMap(localcpa);
    localJg8.setModulationColor(new bNa(1.0F, 1.0F, 1.0F, 0.3F));
    localczv3.bb(localJg8);
    localJg8.brn();
    localJg8.rV();
    localczv3.rV();
    dRq localdRq13 = dRq.checkOut();
    localdRq13.setElementMap(localcpa);
    localdRq11.bb(localdRq13);
    localdRq13.brn();
    cwP localcwP6 = new cwP();
    localcwP6.aJ();
    localcwP6.setElementMap(localcpa);
    localcwP6.setAlign(ajb.dhZ);
    localdRq13.bb(localcwP6);
    localcwP6.brn();
    localcwP6.rV();
    czO localczO4 = new czO();
    localczO4.aJ();
    localczO4.setAdaptToContentSize(true);
    localdRq13.bb(localczO4);
    localczO4.brn();
    localczO4.rV();
    dRq localdRq14 = dRq.checkOut();
    localdRq14.setElementMap(localcpa);
    localdRq13.bb(localdRq14);
    localdRq14.brn();
    cwP localcwP7 = new cwP();
    localcwP7.aJ();
    localcwP7.setElementMap(localcpa);
    localcwP7.setAlign(ajb.dhT);
    localcwP7.setSize(new Or(100.0F, -2));
    localdRq14.bb(localcwP7);
    localcwP7.brn();
    localcwP7.rV();
    czv localczv5 = new czv();
    localczv5.aJ();
    localczv5.setElementMap(localcpa);
    localczv5.setStyle("SundialLeftButtonContainer");
    localczv5.setNonBlocking(true);
    localczv5.setExpandable(false);
    localdRq14.bb(localczv5);
    localczv5.brn();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa);
    localdpm2.setAlign(aFG.ech);
    localczv5.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    localczv5.rV();
    czv localczv6 = new czv();
    localczv6.aJ();
    localczv6.setElementMap(localcpa);
    localczv6.setStyle("SundialCenterButtonContainer");
    localczv6.setNonBlocking(true);
    localdRq14.bb(localczv6);
    localczv6.brn();
    dpm localdpm3 = new dpm();
    localdpm3.aJ();
    localdpm3.setElementMap(localcpa);
    localdpm3.setAlign(aFG.ech);
    localczv6.bb(localdpm3);
    localdpm3.brn();
    localdpm3.rV();
    localczv6.rV();
    czv localczv7 = new czv();
    localczv7.aJ();
    localczv7.setElementMap(localcpa);
    localczv7.setStyle("SundialRightButtonContainer");
    localczv7.setNonBlocking(true);
    localczv7.setExpandable(false);
    localdRq14.bb(localczv7);
    localczv7.brn();
    dpm localdpm4 = new dpm();
    localdpm4.aJ();
    localdpm4.setElementMap(localcpa);
    localdpm4.setAlign(aFG.ech);
    localczv7.bb(localdpm4);
    localdpm4.brn();
    localdpm4.rV();
    localczv7.rV();
    localdRq14.rV();
    biy localbiy1 = new biy();
    localbiy1.aJ();
    localbiy1.setElementMap(localcpa);
    localbiy1.setStyle("big");
    localbiy1.setExpandable(false);
    csA localcsA = new csA();
    localcsA.hg("wakfu.nationSelectionPanel:chooseNation(nationSelection)");
    localbiy1.setOnClick(localcsA);
    cCu localcCu = new cCu();
    localcCu.hg("popup(choosePopup)");
    localbiy1.setOnPopupDisplay(localcCu);
    jL localjL = new jL();
    localjL.hg("closePopup");
    localbiy1.setOnPopupHide(localjL);
    String str5 = "%choose%";
    str5 = str5.replace("%choose%", cBQ.cxL().mL("choose"));
    localbiy1.setText(str5);
    localdRq13.bb(localbiy1);
    localbiy1.brn();
    cwP localcwP8 = new cwP();
    localcwP8.aJ();
    localcwP8.setElementMap(localcpa);
    localcwP8.setAlign(ajb.dhZ);
    localbiy1.bb(localcwP8);
    localcwP8.brn();
    localcwP8.rV();
    biy localbiy2 = localbiy1;
    Jg localJg9 = localbiy2.getAppearance();
    localJg9.setElementMap(localcpa);
    localbiy1.bb(localJg9);
    localJg9.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(0, 20, 0, 20));
    localJg9.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    cuR localcuR3 = new cuR();
    localcuR3.aJ();
    localcuR3.setElementMap(localcpa);
    localcuR3.setInsets(new Insets(2, 15, 2, 15));
    localJg9.bb(localcuR3);
    localcuR3.brn();
    localcuR3.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setAttribute("modulationColor");
    localNK2.setName("selectedNation");
    localJg9.bb(localNK2);
    localNK2.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localanQ2.setValue("0.28,0.86,0.83,1");
    localanQ2.setElseValue("1,1,1");
    localNK2.bb(localanQ2);
    localanQ2.brn();
    bSP localbSP = new bSP();
    localbSP.aJ();
    localbSP.setElementMap(localcpa);
    localanQ2.bb(localbSP);
    localbSP.brn();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("value");
    localbSP.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    localbSP.rV();
    localanQ2.rV();
    localNK2.rV();
    localJg9.rV();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setAttribute("enabled");
    localNK3.setName("localPlayer");
    localNK3.setField("hasNation");
    localbiy1.bb(localNK3);
    localNK3.brn();
    anQ localanQ3 = new anQ();
    localanQ3.aJ();
    localanQ3.setElementMap(localcpa);
    localNK3.bb(localanQ3);
    localanQ3.brn();
    bqW localbqW = new bqW();
    localbqW.aJ();
    localbqW.setElementMap(localcpa);
    localanQ3.bb(localbqW);
    localbqW.brn();
    localbqW.rV();
    localanQ3.rV();
    localNK3.rV();
    String str6 = "choosePopup";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa);
    if ((localcpa != null) && (str6 != null))
      localcpa.a(str6, localanG);
    localanG.setAlign(aFG.ech);
    localanG.setHotSpotPosition(aFG.ecn);
    localbiy1.bb(localanG);
    localanG.brn();
    dRq localdRq15 = dRq.checkOut();
    localdRq15.setElementMap(localcpa);
    localdRq15.setPrefSize(new Or(10, 0));
    localdRq15.setStyle("popup");
    localanG.bb(localdRq15);
    localdRq15.brn();
    cba localcba = cba.checkOut();
    localcba.setElementMap(localcpa);
    localcba.setData(cFu.izR);
    localdRq15.bb(localcba);
    localcba.brn();
    localcba.rV();
    aId localaId3 = aId.checkOut();
    localaId3.setHorizontal(false);
    localaId3.setAlign(aFG.ech);
    localdRq15.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    a(localdRq15);
    b(localdRq15);
    localdRq15.rV();
    localanG.rV();
    localbiy1.rV();
    localdRq13.rV();
    localdRq11.rV();
    d(localdRq10);
    k(localdRq10);
    localdRq10.rV();
    localeR.rV();
    localccG.rV();
    localdRq9.rV();
    localdRq7.rV();
    localdRq2.rV();
    l(localbpn);
    m(localbpn);
    n(localbpn);
    localbpn.rV();
    return localbpn;
  }

  public bdj a(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("PopupInformation");
    String str = "%choose%";
    str = str.replace("%choose%", cBQ.cxL().mL("choose"));
    localcaF1.setText(str);
    parambdj.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg = localcaF2.getAppearance();
    localJg.setElementMap(localcpa);
    ((cwJ)localJg).setAlignment(aFG.ecj);
    localcaF1.bb(localJg);
    localJg.brn();
    localJg.rV();
    localcaF1.rV();
    return localcaF1;
  }

  public bdj b(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("PopupInformation");
    localcWk1.setExpandable(false);
    String str = "%nationSelection.alreadySet%";
    str = str.replace("%nationSelection.alreadySet%", cBQ.cxL().mL("nationSelection.alreadySet"));
    localcWk1.setText(str);
    parambdj.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg = localcWk2.getAppearance();
    localJg.setElementMap(localcpa);
    ((cwJ)localJg).setAlignment(aFG.ecj);
    localcWk1.bb(localJg);
    localJg.brn();
    cAf localcAf = cAf.checkOut();
    localcAf.setElementMap(localcpa);
    localcAf.setColor(new bNa(0.8F, 0.1F, 0.1F, 1.0F));
    localJg.bb(localcAf);
    localcAf.brn();
    localcAf.rV();
    localJg.rV();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setAttribute("visible");
    localNK.setName("localPlayer");
    localNK.setField("hasNation");
    localcWk1.bb(localNK);
    localNK.brn();
    localNK.rV();
    localcWk1.rV();
    return localcWk1;
  }

  public bdj d(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setStyle("tiledScroll");
    localdRq1.setNonBlocking(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setAlign(ajb.dhZ);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    dRq localdRq2 = localdRq1;
    Jg localJg1 = localdRq2.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq1.bb(localJg1);
    localJg1.brn();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(0, 0, 0, 0));
    localJg1.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(17, 12, 55, 30));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    czO localczO1 = new czO();
    localczO1.aJ();
    localczO1.setAdaptToContentSize(true);
    localdRq1.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq1.bb(localdRq3);
    localdRq3.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.dhZ);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localdRq3.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localaId1.setAlign(aFG.ech);
    localdRq3.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setStyle("EncyclopediaSplashTitle");
    localdRq4.setPrefSize(new Or(0, 30));
    localdRq4.setExpandable(false);
    localdRq3.bb(localdRq4);
    localdRq4.brn();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa);
    localdpm1.setAlign(aFG.eck);
    localdRq4.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    dRq localdRq5 = localdRq4;
    Jg localJg2 = localdRq5.getAppearance();
    localJg2.setElementMap(localcpa);
    localdRq4.bb(localJg2);
    localJg2.brn();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(0, 0, 3, 0));
    localJg2.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(5, 0, 0, 0));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    aId localaId2 = aId.checkOut();
    localaId2.setAlign(aFG.eck);
    localdRq4.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("StyledBold16White");
    localcWk1.setNonBlocking(true);
    localcWk1.setExpandable(false);
    String str1 = "%upgrades%";
    str1 = str1.replace("%upgrades%", cBQ.cxL().mL("upgrades"));
    localcWk1.setText(str1);
    localdRq4.bb(localcWk1);
    localcWk1.brn();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("text");
    localaaE1.setField("nation/name");
    localcWk1.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    localcWk1.rV();
    localdRq4.rV();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq6.setExpandable(false);
    localdRq3.bb(localdRq6);
    localdRq6.brn();
    czO localczO2 = new czO();
    localczO2.aJ();
    localczO2.setAdaptToContentSize(true);
    localdRq6.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localdRq7.setExpandable(false);
    localdRq7.setStyle("lineSeparator");
    localdRq6.bb(localdRq7);
    localdRq7.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setAlign(ajb.dif);
    localcwP3.setSize(new Or(100.0F, 7));
    localdRq7.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    localdRq7.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setExpandable(false);
    localczv1.setStyle("KamaPoi");
    localdRq6.bb(localczv1);
    localczv1.brn();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setAlign(ajb.dhY);
    localczv1.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    localczv1.rV();
    cWk localcWk2 = new cWk();
    localcWk2.aJ();
    localcWk2.setElementMap(localcpa);
    localcWk2.setStyle("StyledBoldDark12");
    String str2 = "%richness%";
    str2 = str2.replace("%richness%", cBQ.cxL().mL("richness"));
    localcWk2.setText(str2);
    localdRq6.bb(localcWk2);
    localcWk2.brn();
    cwP localcwP5 = new cwP();
    localcwP5.aJ();
    localcwP5.setElementMap(localcpa);
    localcwP5.setAlign(ajb.dhY);
    localcWk2.bb(localcwP5);
    localcwP5.brn();
    localcwP5.rV();
    cWk localcWk3 = localcWk2;
    Jg localJg3 = localcWk3.getAppearance();
    localJg3.setElementMap(localcpa);
    localcWk2.bb(localJg3);
    localJg3.brn();
    cuR localcuR3 = new cuR();
    localcuR3.aJ();
    localcuR3.setElementMap(localcpa);
    localcuR3.setInsets(new Insets(0, 32, 0, 0));
    localJg3.bb(localcuR3);
    localcuR3.brn();
    localcuR3.rV();
    localJg3.rV();
    localcWk2.rV();
    localdRq6.rV();
    cWk localcWk4 = new cWk();
    localcWk4.aJ();
    localcWk4.setElementMap(localcpa);
    localcWk4.setStyle("SmallSetSubTitle");
    localcWk4.setExpandable(false);
    localdRq3.bb(localcWk4);
    localcWk4.brn();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa);
    localdpm2.setAlign(aFG.eck);
    localcWk4.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("text");
    localaaE2.setField("totalCash");
    localcWk4.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    localcWk4.rV();
    dRq localdRq8 = dRq.checkOut();
    localdRq8.setElementMap(localcpa);
    localdRq8.setExpandable(false);
    localdRq3.bb(localdRq8);
    localdRq8.brn();
    czO localczO3 = new czO();
    localczO3.aJ();
    localczO3.setAdaptToContentSize(true);
    localdRq8.bb(localczO3);
    localczO3.brn();
    localczO3.rV();
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa);
    localdRq9.setExpandable(false);
    localdRq9.setStyle("lineSeparator");
    localdRq8.bb(localdRq9);
    localdRq9.brn();
    cwP localcwP6 = new cwP();
    localcwP6.aJ();
    localcwP6.setElementMap(localcpa);
    localcwP6.setAlign(ajb.dif);
    localcwP6.setSize(new Or(100.0F, 7));
    localdRq9.bb(localcwP6);
    localcwP6.brn();
    localcwP6.rV();
    localdRq9.rV();
    czv localczv2 = new czv();
    localczv2.aJ();
    localczv2.setElementMap(localcpa);
    localczv2.setExpandable(false);
    localczv2.setStyle("ChestPoi");
    localdRq8.bb(localczv2);
    localczv2.brn();
    cwP localcwP7 = new cwP();
    localcwP7.aJ();
    localcwP7.setElementMap(localcpa);
    localcwP7.setAlign(ajb.dhY);
    localczv2.bb(localcwP7);
    localcwP7.brn();
    localcwP7.rV();
    localczv2.rV();
    cWk localcWk5 = new cWk();
    localcWk5.aJ();
    localcWk5.setElementMap(localcpa);
    localcWk5.setStyle("StyledBoldDark12");
    String str3 = "%inhabitantCount%";
    str3 = str3.replace("%inhabitantCount%", cBQ.cxL().mL("inhabitantCount"));
    localcWk5.setText(str3);
    localdRq8.bb(localcWk5);
    localcWk5.brn();
    cwP localcwP8 = new cwP();
    localcwP8.aJ();
    localcwP8.setElementMap(localcpa);
    localcwP8.setAlign(ajb.dhY);
    localcWk5.bb(localcwP8);
    localcwP8.brn();
    localcwP8.rV();
    cWk localcWk6 = localcWk5;
    Jg localJg4 = localcWk6.getAppearance();
    localJg4.setElementMap(localcpa);
    localcWk5.bb(localJg4);
    localJg4.brn();
    cuR localcuR4 = new cuR();
    localcuR4.aJ();
    localcuR4.setElementMap(localcpa);
    localcuR4.setInsets(new Insets(0, 32, 0, 0));
    localJg4.bb(localcuR4);
    localcuR4.brn();
    localcuR4.rV();
    localJg4.rV();
    localcWk5.rV();
    localdRq8.rV();
    cWk localcWk7 = new cWk();
    localcWk7.aJ();
    localcWk7.setElementMap(localcpa);
    localcWk7.setStyle("SmallSetSubTitle");
    localcWk7.setExpandable(false);
    localdRq3.bb(localcWk7);
    localcWk7.brn();
    dpm localdpm3 = new dpm();
    localdpm3.aJ();
    localdpm3.setElementMap(localcpa);
    localdpm3.setAlign(aFG.eck);
    localcWk7.bb(localdpm3);
    localdpm3.brn();
    localdpm3.rV();
    aaE localaaE3 = new aaE();
    localaaE3.aJ();
    localaaE3.setElementMap(localcpa);
    localaaE3.setAttribute("text");
    localaaE3.setField("populationSize");
    localcWk7.bb(localaaE3);
    localaaE3.brn();
    localaaE3.rV();
    localcWk7.rV();
    dRq localdRq10 = dRq.checkOut();
    localdRq10.setElementMap(localcpa);
    localdRq10.setExpandable(false);
    localdRq3.bb(localdRq10);
    localdRq10.brn();
    czO localczO4 = new czO();
    localczO4.aJ();
    localczO4.setAdaptToContentSize(true);
    localdRq10.bb(localczO4);
    localczO4.brn();
    localczO4.rV();
    dRq localdRq11 = dRq.checkOut();
    localdRq11.setElementMap(localcpa);
    localdRq11.setExpandable(false);
    localdRq11.setStyle("lineSeparator");
    localdRq10.bb(localdRq11);
    localdRq11.brn();
    cwP localcwP9 = new cwP();
    localcwP9.aJ();
    localcwP9.setElementMap(localcpa);
    localcwP9.setAlign(ajb.dif);
    localcwP9.setSize(new Or(100.0F, 7));
    localdRq11.bb(localcwP9);
    localcwP9.brn();
    localcwP9.rV();
    localdRq11.rV();
    czv localczv3 = new czv();
    localczv3.aJ();
    localczv3.setElementMap(localcpa);
    localczv3.setExpandable(false);
    localczv3.setStyle("swordPoi");
    localdRq10.bb(localczv3);
    localczv3.brn();
    cwP localcwP10 = new cwP();
    localcwP10.aJ();
    localcwP10.setElementMap(localcpa);
    localcwP10.setAlign(ajb.dhY);
    localczv3.bb(localcwP10);
    localcwP10.brn();
    localcwP10.rV();
    localczv3.rV();
    cWk localcWk8 = new cWk();
    localcWk8.aJ();
    localcWk8.setElementMap(localcpa);
    localcWk8.setStyle("StyledBoldDark12");
    String str4 = "%nation.governor%";
    str4 = str4.replace("%nation.governor%", cBQ.cxL().mL("nation.governor"));
    localcWk8.setText(str4);
    localdRq10.bb(localcWk8);
    localcWk8.brn();
    cwP localcwP11 = new cwP();
    localcwP11.aJ();
    localcwP11.setElementMap(localcpa);
    localcwP11.setAlign(ajb.dhY);
    localcWk8.bb(localcwP11);
    localcwP11.brn();
    localcwP11.rV();
    cWk localcWk9 = localcWk8;
    Jg localJg5 = localcWk9.getAppearance();
    localJg5.setElementMap(localcpa);
    localcWk8.bb(localJg5);
    localJg5.brn();
    cuR localcuR5 = new cuR();
    localcuR5.aJ();
    localcuR5.setElementMap(localcpa);
    localcuR5.setInsets(new Insets(0, 32, 0, 0));
    localJg5.bb(localcuR5);
    localcuR5.brn();
    localcuR5.rV();
    localJg5.rV();
    localcWk8.rV();
    localdRq10.rV();
    cWk localcWk10 = new cWk();
    localcWk10.aJ();
    localcWk10.setElementMap(localcpa);
    localcWk10.setStyle("SmallSetSubTitle");
    localcWk10.setExpandable(false);
    localdRq3.bb(localcWk10);
    localcWk10.brn();
    dpm localdpm4 = new dpm();
    localdpm4.aJ();
    localdpm4.setElementMap(localcpa);
    localdpm4.setAlign(aFG.eck);
    localcWk10.bb(localdpm4);
    localdpm4.brn();
    localdpm4.rV();
    aaE localaaE4 = new aaE();
    localaaE4.aJ();
    localaaE4.setElementMap(localcpa);
    localaaE4.setAttribute("text");
    localaaE4.setField("governorName");
    localcWk10.bb(localaaE4);
    localaaE4.brn();
    localaaE4.rV();
    localcWk10.rV();
    dRq localdRq12 = dRq.checkOut();
    localdRq12.setElementMap(localcpa);
    localdRq12.setExpandable(false);
    localdRq3.bb(localdRq12);
    localdRq12.brn();
    czO localczO5 = new czO();
    localczO5.aJ();
    localczO5.setAdaptToContentSize(true);
    localdRq12.bb(localczO5);
    localczO5.brn();
    localczO5.rV();
    dRq localdRq13 = dRq.checkOut();
    localdRq13.setElementMap(localcpa);
    localdRq13.setExpandable(false);
    localdRq13.setStyle("lineSeparator");
    localdRq12.bb(localdRq13);
    localdRq13.brn();
    cwP localcwP12 = new cwP();
    localcwP12.aJ();
    localcwP12.setElementMap(localcpa);
    localcwP12.setAlign(ajb.dif);
    localcwP12.setSize(new Or(100.0F, 7));
    localdRq13.bb(localcwP12);
    localcwP12.brn();
    localcwP12.rV();
    localdRq13.rV();
    czv localczv4 = new czv();
    localczv4.aJ();
    localczv4.setElementMap(localcpa);
    localczv4.setExpandable(false);
    localczv4.setStyle("flagPoi");
    localdRq12.bb(localczv4);
    localczv4.brn();
    cwP localcwP13 = new cwP();
    localcwP13.aJ();
    localcwP13.setElementMap(localcpa);
    localcwP13.setAlign(ajb.dhY);
    localcwP13.setXOffset(5);
    localczv4.bb(localcwP13);
    localcwP13.brn();
    localcwP13.rV();
    localczv4.rV();
    cWk localcWk11 = new cWk();
    localcWk11.aJ();
    localcWk11.setElementMap(localcpa);
    localcWk11.setStyle("StyledBoldDark12");
    String str5 = "%territoriesCount%";
    str5 = str5.replace("%territoriesCount%", cBQ.cxL().mL("territoriesCount"));
    localcWk11.setText(str5);
    localdRq12.bb(localcWk11);
    localcWk11.brn();
    cwP localcwP14 = new cwP();
    localcwP14.aJ();
    localcwP14.setElementMap(localcpa);
    localcwP14.setAlign(ajb.dhY);
    localcWk11.bb(localcwP14);
    localcwP14.brn();
    localcwP14.rV();
    cWk localcWk12 = localcWk11;
    Jg localJg6 = localcWk12.getAppearance();
    localJg6.setElementMap(localcpa);
    localcWk11.bb(localJg6);
    localJg6.brn();
    cuR localcuR6 = new cuR();
    localcuR6.aJ();
    localcuR6.setElementMap(localcpa);
    localcuR6.setInsets(new Insets(0, 32, 0, 0));
    localJg6.bb(localcuR6);
    localcuR6.brn();
    localcuR6.rV();
    localJg6.rV();
    localcWk11.rV();
    localdRq12.rV();
    cWk localcWk13 = new cWk();
    localcWk13.aJ();
    localcWk13.setElementMap(localcpa);
    localcWk13.setStyle("SmallSetSubTitle");
    localcWk13.setExpandable(false);
    localdRq3.bb(localcWk13);
    localcWk13.brn();
    dpm localdpm5 = new dpm();
    localdpm5.aJ();
    localdpm5.setElementMap(localcpa);
    localdpm5.setAlign(aFG.eck);
    localcWk13.bb(localdpm5);
    localdpm5.brn();
    localdpm5.rV();
    aaE localaaE5 = new aaE();
    localaaE5.aJ();
    localaaE5.setElementMap(localcpa);
    localaaE5.setAttribute("text");
    localaaE5.setField("territoriesCount");
    localcWk13.bb(localaaE5);
    localaaE5.brn();
    localaaE5.rV();
    localcWk13.rV();
    dRq localdRq14 = dRq.checkOut();
    localdRq14.setElementMap(localcpa);
    localdRq14.setExpandable(false);
    localdRq3.bb(localdRq14);
    localdRq14.brn();
    e(localdRq14);
    f(localdRq14);
    g(localdRq14);
    h(localdRq14);
    localdRq14.rV();
    i(localdRq3);
    j(localdRq3);
    localdRq3.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj e(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    czO localczO = new czO();
    localczO.aJ();
    localczO.setAdaptToContentSize(true);
    parambdj.bb(localczO);
    localczO.brn();
    localczO.rV();
    return null;
  }

  public bdj f(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq = dRq.checkOut();
    localdRq.setElementMap(localcpa);
    localdRq.setExpandable(false);
    localdRq.setStyle("lineSeparator");
    parambdj.bb(localdRq);
    localdRq.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setAlign(ajb.dif);
    localcwP.setSize(new Or(100.0F, 7));
    localdRq.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localdRq.rV();
    return localdRq;
  }

  public bdj g(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setExpandable(false);
    localczv.setStyle("questionPoi");
    parambdj.bb(localczv);
    localczv.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setAlign(ajb.dhY);
    localcwP.setXOffset(5);
    localczv.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localczv.rV();
    return localczv;
  }

  public bdj h(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("StyledBoldDark12");
    String str = "%nationAlignments%";
    str = str.replace("%nationAlignments%", cBQ.cxL().mL("nationAlignments"));
    localcWk1.setText(str);
    parambdj.bb(localcWk1);
    localcWk1.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setAlign(ajb.dhY);
    localcWk1.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    cWk localcWk2 = localcWk1;
    Jg localJg = localcWk2.getAppearance();
    localJg.setElementMap(localcpa);
    localcWk1.bb(localJg);
    localJg.brn();
    cuR localcuR = new cuR();
    localcuR.aJ();
    localcuR.setElementMap(localcpa);
    localcuR.setInsets(new Insets(0, 32, 0, 0));
    localJg.bb(localcuR);
    localcuR.brn();
    localcuR.rV();
    localJg.rV();
    localcWk1.rV();
    return localcWk1;
  }

  public bdj i(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    cWk localcWk = new cWk();
    localcWk.aJ();
    localcWk.setElementMap(localcpa);
    localcWk.setStyle("SmallSetSubTitle");
    localcWk.setExpandable(false);
    parambdj.bb(localcWk);
    localcWk.brn();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.eck);
    localcWk.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    aaE localaaE = new aaE();
    localaaE.aJ();
    localaaE.setElementMap(localcpa);
    localaaE.setAttribute("text");
    localaaE.setField("nationAlignments");
    localcWk.bb(localaaE);
    localaaE.brn();
    localaaE.rV();
    localcWk.rV();
    return localcWk;
  }

  public bdj j(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq = dRq.checkOut();
    localdRq.setElementMap(localcpa);
    localdRq.setExpandable(false);
    parambdj.bb(localdRq);
    localdRq.brn();
    czO localczO = new czO();
    localczO.aJ();
    localczO.setAdaptToContentSize(true);
    localdRq.bb(localczO);
    localczO.brn();
    localczO.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setExpandable(false);
    localczv1.setDisplaySize(new Or(80, 80));
    localdRq.bb(localczv1);
    localczv1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setAlign(ajb.dhY);
    localczv1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    czv localczv2 = localczv1;
    Jg localJg = localczv2.getAppearance();
    localJg.setElementMap(localcpa);
    localczv1.bb(localJg);
    localJg.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(0, 5, 0, 0));
    localJg.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg.rV();
    aAR localaAR1 = aAR.checkOut();
    localaAR1.setElementMap(localcpa);
    localczv1.bb(localaAR1);
    localaAR1.brn();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("texture");
    localaaE1.setField("nation/passportStampIconUrl");
    localaAR1.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    localaAR1.rV();
    localczv1.rV();
    czv localczv3 = new czv();
    localczv3.aJ();
    localczv3.setElementMap(localcpa);
    localczv3.setExpandable(false);
    localczv3.setDisplaySize(new Or(140, 110));
    localdRq.bb(localczv3);
    localczv3.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.dia);
    localczv3.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    aAR localaAR2 = aAR.checkOut();
    localaAR2.setElementMap(localcpa);
    localczv3.bb(localaAR2);
    localaAR2.brn();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("texture");
    localaaE2.setField("selectionIcon");
    localaAR2.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    localaAR2.rV();
    localczv3.rV();
    localdRq.rV();
    return localdRq;
  }

  public bdj k(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setStyle("EncyclopediaPane");
    localdRq1.setNonBlocking(true);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setAlign(ajb.dhT);
    localcwP.setSize(new Or(260, 100.0F));
    localcwP.setXOffset(-9);
    localcwP.setYOffset(1);
    localdRq1.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    dRq localdRq2 = localdRq1;
    Jg localJg = localdRq2.getAppearance();
    localJg.setElementMap(localcpa);
    localdRq1.bb(localJg);
    localJg.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(0, 0, 35, 0));
    localJg.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj l(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq = dRq.checkOut();
    localdRq.setElementMap(localcpa);
    parambdj.bb(localdRq);
    localdRq.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(100.0F, 100.0F));
    localdRq.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localdRq.rV();
    return localdRq;
  }

  public bdj m(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    biy localbiy = new biy();
    localbiy.aJ();
    localbiy.setElementMap(localcpa);
    localbiy.setStyle("close");
    localbiy.setExpandable(false);
    csA localcsA = new csA();
    localcsA.hg("unloadDialog");
    localbiy.setOnClick(localcsA);
    parambdj.bb(localbiy);
    localbiy.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(-2, -2));
    localcwP.setAlign(ajb.dhV);
    localcwP.setXOffset(-18);
    localcwP.setYOffset(-12);
    localbiy.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localbiy.rV();
    return localbiy;
  }

  public bdj n(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(-2, -2));
    localcwP.setAlign(ajb.dhZ);
    localcwP.setInitValue(true);
    parambdj.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    return localcwP;
  }
}