import java.awt.Insets;
import java.util.Stack;

public class dPa
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    String str1 = "fleaHistoryDialog";
    bpn localbpn = new bpn();
    localbpn.aJ();
    localbpn.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localbpn);
    localbpn.setPack(true);
    localbpn.brn();
    czO localczO1 = new czO();
    localczO1.aJ();
    localczO1.setAdaptToContentSize(true);
    localbpn.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localbpn.bb(localdRq1);
    localdRq1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    localdRq1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setStyle("windowNew");
    localbpn.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(10, 5, 12, 5));
    localJg1.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    localJg1.rV();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localdRq2.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localaId1.setAlign(aFG.ech);
    localdRq2.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dqa localdqa1 = new dqa();
    localdqa1.aJ();
    localdqa1.setElementMap(localcpa);
    localdqa1.setExpandable(false);
    localdRq2.bb(localdqa1);
    localdqa1.brn();
    dqa localdqa2 = localdqa1;
    Jg localJg2 = localdqa2.getAppearance();
    localJg2.setElementMap(localcpa);
    localdqa1.bb(localJg2);
    localJg2.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 10, 0, 10));
    localJg2.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg2.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setStyle("titleBar");
    localdqa1.bb(localdRq4);
    localdRq4.brn();
    dRq localdRq5 = localdRq4;
    Jg localJg3 = localdRq5.getAppearance();
    localJg3.setElementMap(localcpa);
    localdRq4.bb(localJg3);
    localJg3.brn();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(2, 20, 3, 20));
    localJg3.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    localJg3.rV();
    aId localaId2 = aId.checkOut();
    localaId2.setHorizontal(false);
    localdRq4.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq6.setExpandable(false);
    localdRq4.bb(localdRq6);
    localdRq6.brn();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa);
    localdpm1.setAlign(aFG.eck);
    localdRq6.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("StyledBold16White");
    localcaF1.setNonBlocking(true);
    String str2 = "%flea.salesLog%";
    str2 = str2.replace("%flea.salesLog%", cBQ.cxL().mL("flea.salesLog"));
    localcaF1.setText(str2);
    localdRq6.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg4 = localcaF2.getAppearance();
    localJg4.setElementMap(localcpa);
    ((cwJ)localJg4).setAlignment(aFG.eck);
    localcaF1.bb(localJg4);
    localJg4.brn();
    localJg4.rV();
    localcaF1.rV();
    localdRq6.rV();
    localdRq4.rV();
    localdqa1.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localdRq2.bb(localdRq7);
    localdRq7.brn();
    dRq localdRq8 = localdRq7;
    Jg localJg5 = localdRq8.getAppearance();
    localJg5.setElementMap(localcpa);
    localdRq7.bb(localJg5);
    localJg5.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 12, 0, 12));
    localJg5.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg5.rV();
    String str3 = "windowContentContainer";
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa);
    if ((localcpa != null) && (str3 != null))
      localcpa.a(str3, localdRq9);
    localdRq7.bb(localdRq9);
    localdRq9.brn();
    dRq localdRq10 = dRq.checkOut();
    localdRq10.setElementMap(localcpa);
    localdRq9.bb(localdRq10);
    localdRq10.brn();
    czO localczO2 = new czO();
    localczO2.aJ();
    localczO2.setAdaptToContentSize(true);
    localdRq10.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    dRq localdRq11 = localdRq10;
    Jg localJg6 = localdRq11.getAppearance();
    localJg6.setElementMap(localcpa);
    localdRq10.bb(localJg6);
    localJg6.brn();
    cuR localcuR3 = new cuR();
    localcuR3.aJ();
    localcuR3.setElementMap(localcpa);
    localcuR3.setInsets(new Insets(0, 0, 0, 0));
    localJg6.bb(localcuR3);
    localcuR3.brn();
    localcuR3.rV();
    localJg6.rV();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setStyle("bold");
    String str4 = "%noSale%";
    str4 = str4.replace("%noSale%", cBQ.cxL().mL("noSale"));
    localcaF3.setText(str4);
    localdRq10.bb(localcaF3);
    localcaF3.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setAlign(ajb.dhZ);
    localcaF3.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    caF localcaF4 = localcaF3;
    Jg localJg7 = localcaF4.getAppearance();
    localJg7.setElementMap(localcpa);
    ((cwJ)localJg7).setAlign(aFG.eck);
    localcaF3.bb(localJg7);
    localJg7.brn();
    localJg7.rV();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("visible");
    localNK1.setName("saleHistory");
    localNK1.setField("hasSales");
    localcaF3.bb(localNK1);
    localNK1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localNK1.bb(localanQ1);
    localanQ1.brn();
    bqW localbqW = new bqW();
    localbqW.aJ();
    localbqW.setElementMap(localcpa);
    localanQ1.bb(localbqW);
    localbqW.brn();
    localbqW.rV();
    localanQ1.rV();
    localNK1.rV();
    localcaF3.rV();
    dRq localdRq12 = dRq.checkOut();
    localdRq12.setElementMap(localcpa);
    localdRq10.bb(localdRq12);
    localdRq12.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setAttribute("visible");
    localNK2.setName("saleHistory");
    localNK2.setField("hasSales");
    localdRq12.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    aId localaId3 = aId.checkOut();
    localaId3.setHorizontal(false);
    localdRq12.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setAlign(ajb.dhZ);
    localcwP4.setSize(new Or(100.0F, 100.0F));
    localdRq12.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    dRq localdRq13 = dRq.checkOut();
    localdRq13.setElementMap(localcpa);
    localdRq12.bb(localdRq13);
    localdRq13.brn();
    dRq localdRq14 = localdRq13;
    Jg localJg8 = localdRq14.getAppearance();
    localJg8.setElementMap(localcpa);
    localdRq13.bb(localJg8);
    localJg8.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(5, 0, 10, 0));
    localJg8.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg8.rV();
    biy localbiy1 = new biy();
    localbiy1.aJ();
    localbiy1.setElementMap(localcpa);
    localbiy1.setStyle("whiteLeftArrow");
    csA localcsA1 = new csA();
    localcsA1.hg("wakfu.dimensionalBagFleaHistory:previousPage");
    localbiy1.setOnClick(localcsA1);
    localbiy1.setExpandable(false);
    localdRq13.bb(localbiy1);
    localbiy1.brn();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setAttribute("enabled");
    localNK3.setName("saleHistory");
    localNK3.setField("hasPrevious");
    localbiy1.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    localbiy1.rV();
    dRq localdRq15 = dRq.checkOut();
    localdRq15.setElementMap(localcpa);
    localdRq15.setStyle("ShortcutRowBackgroundFull");
    localdRq15.setExpandable(false);
    localdRq15.setPrefSize(new Or(150, 0));
    localdRq13.bb(localdRq15);
    localdRq15.brn();
    dRq localdRq16 = localdRq15;
    Jg localJg9 = localdRq16.getAppearance();
    localJg9.setElementMap(localcpa);
    localdRq15.bb(localJg9);
    localJg9.brn();
    cuR localcuR4 = new cuR();
    localcuR4.aJ();
    localcuR4.setElementMap(localcpa);
    localcuR4.setInsets(new Insets(2, 5, 2, 5));
    localJg9.bb(localcuR4);
    localcuR4.brn();
    localcuR4.rV();
    localJg9.rV();
    caF localcaF5 = new caF();
    localcaF5.aJ();
    localcaF5.setElementMap(localcpa);
    localcaF5.setStyle("bold");
    localdRq15.bb(localcaF5);
    localcaF5.brn();
    caF localcaF6 = localcaF5;
    Jg localJg10 = localcaF6.getAppearance();
    localJg10.setElementMap(localcpa);
    ((cwJ)localJg10).setAlign(aFG.eck);
    localcaF5.bb(localJg10);
    localJg10.brn();
    localJg10.rV();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa);
    localNK4.setAttribute("text");
    localNK4.setName("saleHistory");
    localNK4.setField("sales/date");
    localcaF5.bb(localNK4);
    localNK4.brn();
    localNK4.rV();
    localcaF5.rV();
    localdRq15.rV();
    biy localbiy2 = new biy();
    localbiy2.aJ();
    localbiy2.setElementMap(localcpa);
    localbiy2.setStyle("whiteRightArrow");
    csA localcsA2 = new csA();
    localcsA2.hg("wakfu.dimensionalBagFleaHistory:nextPage");
    localbiy2.setOnClick(localcsA2);
    localbiy2.setExpandable(false);
    localdRq13.bb(localbiy2);
    localbiy2.brn();
    NK localNK5 = NK.checkOut();
    localNK5.setElementMap(localcpa);
    localNK5.setAttribute("enabled");
    localNK5.setName("saleHistory");
    localNK5.setField("hasNext");
    localbiy2.bb(localNK5);
    localNK5.brn();
    localNK5.rV();
    localbiy2.rV();
    dAS localdAS = new dAS();
    localdAS.aJ();
    localdAS.setElementMap(localcpa);
    localdRq13.bb(localdAS);
    localdAS.brn();
    localdAS.rV();
    dRq localdRq17 = dRq.checkOut();
    localdRq17.setElementMap(localcpa);
    localdRq17.setStyle("flat");
    localdRq17.setExpandable(false);
    localdRq13.bb(localdRq17);
    localdRq17.brn();
    caF localcaF7 = new caF();
    localcaF7.aJ();
    localcaF7.setElementMap(localcpa);
    localcaF7.setStyle("bold");
    String str5 = "%totalSalesOfTheDay%";
    str5 = str5.replace("%totalSalesOfTheDay%", cBQ.cxL().mL("totalSalesOfTheDay"));
    localcaF7.setText(str5);
    localdRq17.bb(localcaF7);
    localcaF7.brn();
    caF localcaF8 = localcaF7;
    Jg localJg11 = localcaF8.getAppearance();
    localJg11.setElementMap(localcpa);
    localcaF7.bb(localJg11);
    localJg11.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(0, 3, 0, 3));
    localJg11.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg11.rV();
    localcaF7.rV();
    dRq localdRq18 = dRq.checkOut();
    localdRq18.setElementMap(localcpa);
    localdRq18.setStyle("ShortcutRowBackgroundFull");
    localdRq18.setExpandable(false);
    localdRq18.setPrefSize(new Or(100, 0));
    localdRq17.bb(localdRq18);
    localdRq18.brn();
    dRq localdRq19 = localdRq18;
    Jg localJg12 = localdRq19.getAppearance();
    localJg12.setElementMap(localcpa);
    localdRq18.bb(localJg12);
    localJg12.brn();
    cuR localcuR5 = new cuR();
    localcuR5.aJ();
    localcuR5.setElementMap(localcpa);
    localcuR5.setInsets(new Insets(2, 5, 2, 5));
    localJg12.bb(localcuR5);
    localcuR5.brn();
    localcuR5.rV();
    localJg12.rV();
    caF localcaF9 = new caF();
    localcaF9.aJ();
    localcaF9.setElementMap(localcpa);
    localcaF9.setStyle("bold");
    localdRq18.bb(localcaF9);
    localcaF9.brn();
    NK localNK6 = NK.checkOut();
    localNK6.setElementMap(localcpa);
    localNK6.setAttribute("text");
    localNK6.setName("saleHistory");
    localNK6.setField("sales/totalSales");
    localcaF9.bb(localNK6);
    localNK6.brn();
    localNK6.rV();
    caF localcaF10 = localcaF9;
    Jg localJg13 = localcaF10.getAppearance();
    localJg13.setElementMap(localcpa);
    ((cwJ)localJg13).setAlign(aFG.ecl);
    localcaF9.bb(localJg13);
    localJg13.brn();
    bmv localbmv5 = bmv.checkOut();
    localbmv5.setElementMap(localcpa);
    localbmv5.setInsets(new Insets(0, 0, 0, 3));
    localJg13.bb(localbmv5);
    localbmv5.brn();
    localbmv5.rV();
    localJg13.rV();
    localcaF9.rV();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setStyle("kamas");
    localczv.setExpandable(false);
    localdRq18.bb(localczv);
    localczv.brn();
    localczv.rV();
    localdRq18.rV();
    localdRq17.rV();
    localdRq13.rV();
    ccG localccG = new ccG();
    localccG.aJ();
    localccG.setElementMap(localcpa);
    localccG.setHorizontal(false);
    localccG.setCellSize(new Or(600, 48));
    localccG.setExpandable(false);
    localccG.setAutoIdealSize(true);
    localccG.setIdealSizeMinColumns(1);
    localccG.setIdealSizeMaxColumns(1);
    localccG.setIdealSizeMinRows(1);
    localccG.setIdealSizeMaxRows(5);
    localdRq12.bb(localccG);
    localccG.brn();
    NK localNK7 = NK.checkOut();
    localNK7.setElementMap(localcpa);
    localNK7.setAttribute("content");
    localNK7.setName("saleHistory");
    localNK7.setField("sales/sales");
    localccG.bb(localNK7);
    localNK7.brn();
    localNK7.rV();
    eR localeR = new eR();
    localeR.aJ();
    localeR.setElementMap(localcpa);
    localccG.bb(localeR);
    localeR.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localeR.bb(localanQ2);
    localanQ2.brn();
    bxx localbxx = new bxx();
    localbxx.aJ();
    localbxx.setElementMap(localcpa);
    localanQ2.bb(localbxx);
    localbxx.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localbxx.bb(localanE);
    localanE.brn();
    localanE.rV();
    localbxx.rV();
    localanQ2.rV();
    dRq localdRq20 = dRq.checkOut();
    localdRq20.setElementMap(localcpa);
    localdRq20.setStyle("flat");
    localeR.bb(localdRq20);
    localdRq20.brn();
    aId localaId4 = aId.checkOut();
    localaId4.setAlign(aFG.ecj);
    localdRq20.bb(localaId4);
    localaId4.brn();
    localaId4.rV();
    dRq localdRq21 = dRq.checkOut();
    localdRq21.setElementMap(localcpa);
    localdRq21.setStyle("flat");
    localdRq21.setPrefSize(new Or(0, 35));
    localdRq20.bb(localdRq21);
    localdRq21.brn();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa);
    localdpm2.setAlign(aFG.eck);
    localdRq21.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    a(localdRq21);
    b(localdRq21);
    d(localdRq21);
    localdRq21.rV();
    e(localdRq20);
    f(localdRq20);
    localdRq20.rV();
    localeR.rV();
    localccG.rV();
    localdRq12.rV();
    localdRq10.rV();
    localdRq9.rV();
    localdRq7.rV();
    localdRq2.rV();
    g(localbpn);
    h(localbpn);
    i(localbpn);
    localbpn.rV();
    return localbpn;
  }

  public bdj a(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(false);
    parambdj.bb(localaId);
    localaId.brn();
    localaId.rV();
    return null;
  }

  public bdj b(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    String str = "%buyer%";
    str = str.replace("%buyer%", cBQ.cxL().mL("buyer"));
    localcaF1.setText(str);
    localcaF1.setStyle("bold");
    parambdj.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg = localcaF2.getAppearance();
    localJg.setElementMap(localcpa);
    ((cwJ)localJg).setAlign(aFG.eck);
    localcaF1.bb(localJg);
    localJg.brn();
    localJg.rV();
    localcaF1.rV();
    return localcaF1;
  }

  public bdj d(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setStyle("ShortcutRowBackgroundFull");
    localdRq1.setPrefSize(new Or(150, 0));
    parambdj.bb(localdRq1);
    localdRq1.brn();
    dRq localdRq2 = localdRq1;
    Jg localJg1 = localdRq2.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq1.bb(localJg1);
    localJg1.brn();
    cuR localcuR = new cuR();
    localcuR.aJ();
    localcuR.setElementMap(localcpa);
    localcuR.setInsets(new Insets(2, 5, 2, 5));
    localJg1.bb(localcuR);
    localcuR.brn();
    localcuR.rV();
    localJg1.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("bold");
    localdRq1.bb(localcaF1);
    localcaF1.brn();
    aaE localaaE = new aaE();
    localaaE.aJ();
    localaaE.setElementMap(localcpa);
    localaaE.setAttribute("text");
    localaaE.setField("playerName");
    localcaF1.bb(localaaE);
    localaaE.brn();
    localaaE.rV();
    caF localcaF2 = localcaF1;
    Jg localJg2 = localcaF2.getAppearance();
    localJg2.setElementMap(localcpa);
    ((cwJ)localJg2).setAlign(aFG.eck);
    localcaF1.bb(localJg2);
    localJg2.brn();
    localJg2.rV();
    localcaF1.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj e(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    dRq localdRq2 = localdRq1;
    Jg localJg1 = localdRq2.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq1.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 0, 0, 2));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.ech);
    localdRq1.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    ccG localccG1 = new ccG();
    localccG1.aJ();
    localccG1.setElementMap(localcpa);
    localccG1.setCellSize(new Or(42, 42));
    localccG1.setExpandable(false);
    localccG1.setPrefSize(new Or(252, 0));
    localccG1.setAutoIdealSize(true);
    localccG1.setIdealSizeMinColumns(6);
    localccG1.setIdealSizeMaxColumns(6);
    localdRq1.bb(localccG1);
    localccG1.brn();
    ccG localccG2 = localccG1;
    Jg localJg2 = localccG2.getAppearance();
    localJg2.setElementMap(localcpa);
    localccG1.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 0, 0, 0));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("content");
    localaaE1.setField("items");
    localccG1.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    eR localeR1 = new eR();
    localeR1.aJ();
    localeR1.setElementMap(localcpa);
    aqC localaqC = new aqC();
    localaqC.hg("wakfu:openItemDetailWindow(fleaHistoryDialog)");
    localeR1.setOnItemClick(localaqC);
    localccG1.bb(localeR1);
    localeR1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localeR1.bb(localanQ1);
    localanQ1.brn();
    bxx localbxx1 = new bxx();
    localbxx1.aJ();
    localbxx1.setElementMap(localcpa);
    localanQ1.bb(localbxx1);
    localbxx1.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localbxx1.bb(localanE);
    localanE.brn();
    localanE.rV();
    localbxx1.rV();
    localanQ1.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq3.setStyle("itemBackground");
    cCu localcCu = new cCu();
    localcCu.hg("popup(fightItemNamePopup)");
    localdRq3.setOnPopupDisplay(localcCu);
    jL localjL = new jL();
    localjL.hg("closePopup");
    localdRq3.setOnPopupHide(localjL);
    localdRq3.setNonBlocking(false);
    localeR1.bb(localdRq3);
    localdRq3.brn();
    dRq localdRq4 = localdRq3;
    Jg localJg3 = localdRq4.getAppearance();
    localJg3.setElementMap(localcpa);
    localdRq3.bb(localJg3);
    localJg3.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 1, 0, 1));
    localJg3.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg3.rV();
    czO localczO = new czO();
    localczO.aJ();
    localdRq3.bb(localczO);
    localczO.brn();
    localczO.rV();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setScaled(true);
    localczv.setDisplaySize(new Or(32, 32));
    localdRq3.bb(localczv);
    localczv.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setAlign(ajb.dhZ);
    localczv.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv.bb(localaAR);
    localaAR.brn();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("texture");
    localaaE2.setField("iconUrl");
    localaAR.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    localaAR.rV();
    localczv.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setNonBlocking(true);
    localcaF1.setStyle("White10Bordered");
    localdRq3.bb(localcaF1);
    localcaF1.brn();
    aaE localaaE3 = new aaE();
    localaaE3.aJ();
    localaaE3.setElementMap(localcpa);
    localaaE3.setAttribute("visible");
    localaaE3.setField("quantity");
    localcaF1.bb(localaaE3);
    localaaE3.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localaaE3.bb(localanQ2);
    localanQ2.brn();
    aEJ localaEJ = new aEJ();
    localaEJ.aJ();
    localaEJ.setElementMap(localcpa);
    localaEJ.setValue("1");
    localanQ2.bb(localaEJ);
    localaEJ.brn();
    localaEJ.rV();
    localanQ2.rV();
    localaaE3.rV();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.did);
    localcaF1.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    caF localcaF2 = localcaF1;
    Jg localJg4 = localcaF2.getAppearance();
    localJg4.setElementMap(localcpa);
    localcaF1.bb(localJg4);
    localJg4.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(0, 5, 0, 0));
    localJg4.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg4.rV();
    aaE localaaE4 = new aaE();
    localaaE4.aJ();
    localaaE4.setElementMap(localcpa);
    localaaE4.setAttribute("text");
    localaaE4.setField("quantity");
    localcaF1.bb(localaaE4);
    localaaE4.brn();
    localaaE4.rV();
    localcaF1.rV();
    String str = "fightItemNamePopup";
    anG localanG = new anG();
    localanG.aJ();
    localanG.setElementMap(localcpa);
    if ((localcpa != null) && (str != null))
      localcpa.a(str, localanG);
    localanG.setAlign(aFG.ech);
    localanG.setHotSpotPosition(aFG.ecn);
    localdRq3.bb(localanG);
    localanG.brn();
    dRq localdRq5 = dRq.checkOut();
    localdRq5.setElementMap(localcpa);
    localdRq5.setPrefSize(new Or(10, 0));
    localdRq5.setStyle("popup");
    localanG.bb(localdRq5);
    localdRq5.brn();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setStyle("PopupInformation");
    localdRq5.bb(localcaF3);
    localcaF3.brn();
    caF localcaF4 = localcaF3;
    Jg localJg5 = localcaF4.getAppearance();
    localJg5.setElementMap(localcpa);
    ((cwJ)localJg5).setAlignment(aFG.ecj);
    localcaF3.bb(localJg5);
    localJg5.brn();
    localJg5.rV();
    aaE localaaE5 = new aaE();
    localaaE5.aJ();
    localaaE5.setElementMap(localcpa);
    localaaE5.setAttribute("text");
    localaaE5.setField("name");
    localcaF3.bb(localaaE5);
    localaaE5.brn();
    localaaE5.rV();
    localcaF3.rV();
    localdRq5.rV();
    localanG.rV();
    localdRq3.rV();
    localeR1.rV();
    eR localeR2 = new eR();
    localeR2.aJ();
    localeR2.setElementMap(localcpa);
    localccG1.bb(localeR2);
    localeR2.brn();
    anQ localanQ3 = new anQ();
    localanQ3.aJ();
    localanQ3.setElementMap(localcpa);
    localeR2.bb(localanQ3);
    localanQ3.brn();
    bxx localbxx2 = new bxx();
    localbxx2.aJ();
    localbxx2.setElementMap(localcpa);
    localanQ3.bb(localbxx2);
    localbxx2.brn();
    aIB localaIB = new aIB();
    localaIB.aJ();
    localaIB.setElementMap(localcpa);
    localbxx2.bb(localaIB);
    localaIB.brn();
    localaIB.rV();
    localbxx2.rV();
    localanQ3.rV();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq6.setStyle("itemBackground");
    localeR2.bb(localdRq6);
    localdRq6.brn();
    dRq localdRq7 = localdRq6;
    Jg localJg6 = localdRq7.getAppearance();
    localJg6.setElementMap(localcpa);
    localJg6.setModulationColor(new bNa(1.0F, 1.0F, 1.0F, 0.4F));
    localdRq6.bb(localJg6);
    localJg6.brn();
    localJg6.rV();
    localdRq6.rV();
    localeR2.rV();
    localccG1.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj f(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setStyle("flat");
    localdRq1.setPrefSize(new Or(0, 35));
    parambdj.bb(localdRq1);
    localdRq1.brn();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.eck);
    localdRq1.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(false);
    localdRq1.bb(localaId);
    localaId.brn();
    localaId.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    String str = "%totalSales%";
    str = str.replace("%totalSales%", cBQ.cxL().mL("totalSales"));
    localcaF1.setText(str);
    localcaF1.setStyle("bold");
    localdRq1.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg1 = localcaF2.getAppearance();
    localJg1.setElementMap(localcpa);
    ((cwJ)localJg1).setAlign(aFG.eck);
    localcaF1.bb(localJg1);
    localJg1.brn();
    localJg1.rV();
    localcaF1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setStyle("ShortcutRowBackgroundFull");
    localdRq2.setPrefSize(new Or(150, 0));
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg2 = localdRq3.getAppearance();
    localJg2.setElementMap(localcpa);
    localdRq2.bb(localJg2);
    localJg2.brn();
    cuR localcuR = new cuR();
    localcuR.aJ();
    localcuR.setElementMap(localcpa);
    localcuR.setInsets(new Insets(2, 5, 2, 5));
    localJg2.bb(localcuR);
    localcuR.brn();
    localcuR.rV();
    localJg2.rV();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setStyle("bold");
    localdRq2.bb(localcaF3);
    localcaF3.brn();
    aaE localaaE = new aaE();
    localaaE.aJ();
    localaaE.setElementMap(localcpa);
    localaaE.setAttribute("text");
    localaaE.setField("kamas");
    localcaF3.bb(localaaE);
    localaaE.brn();
    localaaE.rV();
    caF localcaF4 = localcaF3;
    Jg localJg3 = localcaF4.getAppearance();
    localJg3.setElementMap(localcpa);
    ((cwJ)localJg3).setAlign(aFG.ecl);
    localcaF3.bb(localJg3);
    localJg3.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(0, 0, 0, 3));
    localJg3.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg3.rV();
    localcaF3.rV();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setStyle("kamas");
    localczv.setExpandable(false);
    localdRq2.bb(localczv);
    localczv.brn();
    localczv.rV();
    localdRq2.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj g(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq = dRq.checkOut();
    localdRq.setElementMap(localcpa);
    parambdj.bb(localdRq);
    localdRq.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(100.0F, 100.0F));
    localdRq.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localdRq.rV();
    return localdRq;
  }

  public bdj h(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    biy localbiy = new biy();
    localbiy.aJ();
    localbiy.setElementMap(localcpa);
    localbiy.setStyle("close");
    localbiy.setExpandable(false);
    csA localcsA = new csA();
    localcsA.hg("wakfu.dimensionalBagFleaHistory:closeDialog");
    localbiy.setOnClick(localcsA);
    parambdj.bb(localbiy);
    localbiy.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(-2, -2));
    localcwP.setAlign(ajb.dhV);
    localcwP.setXOffset(-18);
    localcwP.setYOffset(-12);
    localbiy.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localbiy.rV();
    return localbiy;
  }

  public bdj i(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(-2, -2));
    localcwP.setAlign(ajb.dhZ);
    localcwP.setXOffset(-120);
    localcwP.setInitValue(true);
    parambdj.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    return localcwP;
  }
}