import java.awt.Insets;
import java.util.Stack;

public class bKW
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(-2, -2));
    localcwP1.setAlign(ajb.dhY);
    localcwP1.setXOffset(-20);
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    czO localczO1 = new czO();
    localczO1.aJ();
    localczO1.setAdaptToContentSize(true);
    localdRq1.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setStyle("tiledScroll");
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(20, 12, 20, 13));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(13, 0, 13, 0));
    localJg1.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    localJg1.rV();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localdRq2.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localdRq2.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setNonBlocking(false);
    localdRq2.bb(localdRq4);
    localdRq4.brn();
    aId localaId2 = aId.checkOut();
    localaId2.setHorizontal(false);
    localaId2.setAlign(aFG.ech);
    localdRq4.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    dRq localdRq5 = dRq.checkOut();
    localdRq5.setElementMap(localcpa);
    localdRq5.setStyle("AchievementUnlockedSplashScaled2");
    localdRq5.setExpandable(false);
    localdRq4.bb(localdRq5);
    localdRq5.brn();
    dRq localdRq6 = localdRq5;
    Jg localJg2 = localdRq6.getAppearance();
    localJg2.setElementMap(localcpa);
    localdRq5.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 13, 0, 0));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(13, 10, 13, 10));
    localJg2.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    localJg2.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("defaultBold22");
    localcaF1.setExpandable(false);
    localdRq5.bb(localcaF1);
    localcaF1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setLocal(true);
    localNK1.setName("questListBar");
    localNK1.setAttribute("text");
    localNK1.setField("achievementIndexText");
    localcaF1.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa);
    localdpm1.setAlign(aFG.ech);
    localcaF1.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    caF localcaF2 = localcaF1;
    Jg localJg3 = localcaF2.getAppearance();
    localJg3.setElementMap(localcpa);
    localcaF1.bb(localJg3);
    localJg3.brn();
    cAf localcAf1 = cAf.checkOut();
    localcAf1.setElementMap(localcpa);
    localcAf1.setColor(new bNa(0.94F, 0.86F, 0.66F, 1.0F));
    localJg3.bb(localcAf1);
    localcAf1.brn();
    localcAf1.rV();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(0, 0, 0, 10));
    localJg3.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg3.rV();
    localcaF1.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("styledBoldWhite12");
    localcWk1.setMinWidth(1);
    localcWk1.setMaxWidth(180);
    localcWk1.setExpandable(false);
    localdRq5.bb(localcWk1);
    localcWk1.brn();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa);
    localdpm2.setAlign(aFG.ech);
    localcWk1.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setLocal(true);
    localNK2.setName("displayedAchievement");
    localNK2.setAttribute("text");
    localNK2.setField("name");
    localcWk1.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    cWk localcWk2 = localcWk1;
    Jg localJg4 = localcWk2.getAppearance();
    localJg4.setElementMap(localcpa);
    localcWk1.bb(localJg4);
    localJg4.brn();
    cAf localcAf2 = cAf.checkOut();
    localcAf2.setElementMap(localcpa);
    localcAf2.setColor(new bNa(0.94F, 0.86F, 0.66F, 1.0F));
    localJg4.bb(localcAf2);
    localcAf2.brn();
    localcAf2.rV();
    localJg4.rV();
    localcWk1.rV();
    localdRq5.rV();
    at localat1 = new at();
    localat1.aJ();
    localat1.setElementMap(localcpa);
    localat1.setHorizontal(false);
    localat1.setExpandable(false);
    localdRq4.bb(localat1);
    localat1.brn();
    at localat2 = localat1;
    Jg localJg5 = localat2.getAppearance();
    localJg5.setElementMap(localcpa);
    localat1.bb(localJg5);
    localJg5.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(0, 15, 0, 15));
    localJg5.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg5.rV();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setLocal(true);
    localNK3.setName("displayedAchievement");
    localNK3.setAttribute("content");
    localNK3.setField("goals");
    localat1.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    eR localeR = new eR();
    localeR.aJ();
    localeR.setElementMap(localcpa);
    localat1.bb(localeR);
    localeR.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localeR.bb(localanQ1);
    localanQ1.brn();
    bxx localbxx = new bxx();
    localbxx.aJ();
    localbxx.setElementMap(localcpa);
    localanQ1.bb(localbxx);
    localbxx.brn();
    anE localanE1 = new anE();
    localanE1.aJ();
    localanE1.setElementMap(localcpa);
    localbxx.bb(localanE1);
    localanE1.brn();
    localanE1.rV();
    localbxx.rV();
    localanQ1.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localeR.bb(localdRq7);
    localdRq7.brn();
    aId localaId3 = aId.checkOut();
    localaId3.setAlign(aFG.ecj);
    localdRq7.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    cWk localcWk3 = new cWk();
    localcWk3.aJ();
    localcWk3.setElementMap(localcpa);
    localcWk3.setStyle("styledBoldDark12");
    localcWk3.setExpandable(false);
    localcWk3.setMinWidth(180);
    localcWk3.setMaxWidth(180);
    localdRq7.bb(localcWk3);
    localcWk3.brn();
    cWk localcWk4 = localcWk3;
    Jg localJg6 = localcWk4.getAppearance();
    localJg6.setElementMap(localcpa);
    ((cwJ)localJg6).setAlign(aFG.ecj);
    localcWk3.bb(localJg6);
    localJg6.brn();
    bmv localbmv5 = bmv.checkOut();
    localbmv5.setElementMap(localcpa);
    localbmv5.setInsets(new Insets(0, 0, 0, 0));
    localJg6.bb(localbmv5);
    localbmv5.brn();
    localbmv5.rV();
    cuR localcuR3 = new cuR();
    localcuR3.aJ();
    localcuR3.setElementMap(localcpa);
    localcuR3.setInsets(new Insets(7, 0, 7, 0));
    localJg6.bb(localcuR3);
    localcuR3.brn();
    localcuR3.rV();
    localJg6.rV();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("text");
    localaaE1.setField("description");
    localcWk3.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    localcWk3.rV();
    dAS localdAS = new dAS();
    localdAS.aJ();
    localdAS.setElementMap(localcpa);
    localdRq7.bb(localdAS);
    localdAS.brn();
    localdAS.rV();
    cWk localcWk5 = new cWk();
    localcWk5.aJ();
    localcWk5.setElementMap(localcpa);
    localcWk5.setExpandable(false);
    localcWk5.setStyle("styledBoldDark12");
    localcWk5.setNonBlocking(true);
    localdRq7.bb(localcWk5);
    localcWk5.brn();
    cWk localcWk6 = localcWk5;
    Jg localJg7 = localcWk6.getAppearance();
    localJg7.setElementMap(localcpa);
    ((cwJ)localJg7).setAlign(aFG.eck);
    localcWk5.bb(localJg7);
    localJg7.brn();
    localJg7.rV();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("text");
    localaaE2.setField("progressionText");
    localcWk5.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    aaE localaaE3 = new aaE();
    localaaE3.aJ();
    localaaE3.setElementMap(localcpa);
    localaaE3.setAttribute("visible");
    localaaE3.setField("isCompleted");
    localcWk5.bb(localaaE3);
    localaaE3.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localaaE3.bb(localanQ2);
    localanQ2.brn();
    bJJ localbJJ1 = new bJJ();
    localbJJ1.aJ();
    localbJJ1.setElementMap(localcpa);
    localanQ2.bb(localbJJ1);
    localbJJ1.brn();
    bqW localbqW1 = new bqW();
    localbqW1.aJ();
    localbqW1.setElementMap(localcpa);
    localbJJ1.bb(localbqW1);
    localbqW1.brn();
    localbqW1.rV();
    bqW localbqW2 = new bqW();
    localbqW2.aJ();
    localbqW2.setElementMap(localcpa);
    localbJJ1.bb(localbqW2);
    localbqW2.brn();
    aaE localaaE4 = new aaE();
    localaaE4.aJ();
    localaaE4.setElementMap(localcpa);
    localaaE4.setAttribute("comparedValue");
    localaaE4.setField("progressionText");
    localbqW2.bb(localaaE4);
    localaaE4.brn();
    anQ localanQ3 = new anQ();
    localanQ3.aJ();
    localanQ3.setElementMap(localcpa);
    localaaE4.bb(localanQ3);
    localanQ3.brn();
    bSP localbSP = new bSP();
    localbSP.aJ();
    localbSP.setElementMap(localcpa);
    localbSP.setValue("-1");
    localanQ3.bb(localbSP);
    localbSP.brn();
    localbSP.rV();
    localanQ3.rV();
    localaaE4.rV();
    localbqW2.rV();
    localbJJ1.rV();
    localanQ2.rV();
    localaaE3.rV();
    localcWk5.rV();
    localdRq7.rV();
    localeR.rV();
    localat1.rV();
    cWk localcWk7 = new cWk();
    localcWk7.aJ();
    localcWk7.setElementMap(localcpa);
    localcWk7.setStyle("darkBold");
    localcWk7.setExpandable(false);
    localcWk7.setMinWidth(1);
    localcWk7.setMaxWidth(200);
    localcWk7.setText("bg");
    localdRq4.bb(localcWk7);
    localcWk7.brn();
    cWk localcWk8 = localcWk7;
    Jg localJg8 = localcWk8.getAppearance();
    localJg8.setElementMap(localcpa);
    localcWk7.bb(localJg8);
    localJg8.brn();
    bmv localbmv6 = bmv.checkOut();
    localbmv6.setElementMap(localcpa);
    localbmv6.setInsets(new Insets(5, 20, 5, 20));
    localJg8.bb(localbmv6);
    localbmv6.brn();
    localbmv6.rV();
    localJg8.rV();
    dpm localdpm3 = new dpm();
    localdpm3.aJ();
    localdpm3.setElementMap(localcpa);
    localdpm3.setAlign(aFG.ecj);
    localcWk7.bb(localdpm3);
    localdpm3.brn();
    localdpm3.rV();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa);
    localNK4.setLocal(true);
    localNK4.setName("displayedAchievement");
    localNK4.setAttribute("text");
    localNK4.setField("backgroundText");
    localcWk7.bb(localNK4);
    localNK4.brn();
    localNK4.rV();
    NK localNK5 = NK.checkOut();
    localNK5.setElementMap(localcpa);
    localNK5.setLocal(true);
    localNK5.setName("displayedAchievement");
    localNK5.setAttribute("visible");
    localNK5.setField("backgroundText");
    localcWk7.bb(localNK5);
    localNK5.brn();
    anQ localanQ4 = new anQ();
    localanQ4.aJ();
    localanQ4.setElementMap(localcpa);
    localNK5.bb(localanQ4);
    localanQ4.brn();
    bJJ localbJJ2 = new bJJ();
    localbJJ2.aJ();
    localbJJ2.setElementMap(localcpa);
    localanQ4.bb(localbJJ2);
    localbJJ2.brn();
    anE localanE2 = new anE();
    localanE2.aJ();
    localanE2.setElementMap(localcpa);
    localbJJ2.bb(localanE2);
    localanE2.brn();
    localanE2.rV();
    jA localjA = new jA();
    localjA.aJ();
    localjA.setElementMap(localcpa);
    localjA.setValue("");
    localbJJ2.bb(localjA);
    localjA.brn();
    localjA.rV();
    localbJJ2.rV();
    localanQ4.rV();
    localNK5.rV();
    localcWk7.rV();
    dRq localdRq8 = dRq.checkOut();
    localdRq8.setElementMap(localcpa);
    localdRq8.setExpandable(false);
    localdRq4.bb(localdRq8);
    localdRq8.brn();
    dRq localdRq9 = localdRq8;
    Jg localJg9 = localdRq9.getAppearance();
    localJg9.setElementMap(localcpa);
    localdRq8.bb(localJg9);
    localJg9.brn();
    bmv localbmv7 = bmv.checkOut();
    localbmv7.setElementMap(localcpa);
    localbmv7.setInsets(new Insets(5, 13, 5, 13));
    localJg9.bb(localbmv7);
    localbmv7.brn();
    localbmv7.rV();
    localJg9.rV();
    dpm localdpm4 = new dpm();
    localdpm4.aJ();
    localdpm4.setElementMap(localcpa);
    localdpm4.setAlign(aFG.eck);
    localdRq8.bb(localdpm4);
    localdpm4.brn();
    localdpm4.rV();
    czO localczO2 = new czO();
    localczO2.aJ();
    localczO2.setAdaptToContentSize(true);
    localdRq8.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setStyle("scrollTitleBar");
    localczv.setDisplaySize(new Or(210, 29));
    localdRq8.bb(localczv);
    localczv.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setSize(new Or(-2, -2));
    localcwP3.setAlign(ajb.dhY);
    localczv.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    localczv.rV();
    cWk localcWk9 = new cWk();
    localcWk9.aJ();
    localcWk9.setElementMap(localcpa);
    localcWk9.setStyle("styledBoldWhite12");
    localcWk9.setNonBlocking(true);
    String str = "%achievement.reward%";
    str = str.replace("%achievement.reward%", cBQ.cxL().mL("achievement.reward"));
    localcWk9.setText(str);
    localdRq8.bb(localcWk9);
    localcWk9.brn();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setAlign(ajb.dhY);
    localcwP4.setSize(new Or(100.0F, 2));
    localcWk9.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    cWk localcWk10 = localcWk9;
    Jg localJg10 = localcWk10.getAppearance();
    localJg10.setElementMap(localcpa);
    ((cwJ)localJg10).setAlign(aFG.eck);
    localcWk9.bb(localJg10);
    localJg10.brn();
    a(localJg10);
    localJg10.rV();
    localcWk9.rV();
    localdRq8.rV();
    b(localdRq4);
    localdRq4.rV();
    d(localdRq2);
    localdRq2.rV();
    e(localdRq1);
    f(localdRq1);
    localdRq1.rV();
    return localdRq1;
  }

  public bdj a(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    cAf localcAf = cAf.checkOut();
    localcAf.setElementMap(localcpa);
    localcAf.setColor(new bNa(0.94F, 0.86F, 0.66F, 1.0F));
    parambdj.bb(localcAf);
    localcAf.brn();
    localcAf.rV();
    return localcAf;
  }

  public bdj b(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    ccG localccG1 = new ccG();
    localccG1.aJ();
    localccG1.setElementMap(localcpa);
    localccG1.setCellSize(new Or(170, 52));
    localccG1.setPrefSize(new Or(0, 0));
    localccG1.setExpandable(false);
    localccG1.setAutoIdealSize(true);
    localccG1.setIdealSizeMinColumns(1);
    localccG1.setIdealSizeMaxColumns(1);
    parambdj.bb(localccG1);
    localccG1.brn();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setLocal(true);
    localNK.setName("displayedAchievement");
    localNK.setField("rewards");
    localNK.setAttribute("content");
    localccG1.bb(localNK);
    localNK.brn();
    localNK.rV();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.eck);
    localccG1.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    ccG localccG2 = localccG1;
    Jg localJg1 = localccG2.getAppearance();
    localJg1.setElementMap(localcpa);
    localccG1.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 0, 0, 0));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    eR localeR = new eR();
    localeR.aJ();
    localeR.setElementMap(localcpa);
    aqC localaqC = new aqC();
    localaqC.hg("wakfu:openItemDetailWindow()");
    localeR.setOnItemClick(localaqC);
    localccG1.bb(localeR);
    localeR.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localeR.bb(localanQ1);
    localanQ1.brn();
    bxx localbxx = new bxx();
    localbxx.aJ();
    localbxx.setElementMap(localcpa);
    localanQ1.bb(localbxx);
    localbxx.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localbxx.bb(localanE);
    localanE.brn();
    localanE.rV();
    localbxx.rV();
    localanQ1.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localeR.bb(localdRq1);
    localdRq1.brn();
    aId localaId = aId.checkOut();
    localaId.setAlign(aFG.ecj);
    localdRq1.bb(localaId);
    localaId.brn();
    localaId.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setExpandable(false);
    localdRq1.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg2 = localdRq3.getAppearance();
    localJg2.setElementMap(localcpa);
    localdRq2.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 0, 0, 5));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    czO localczO = new czO();
    localczO.aJ();
    localczO.setAdaptToContentSize(true);
    localdRq2.bb(localczO);
    localczO.brn();
    localczO.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setStyle("IconEmptyEmote");
    localdRq2.bb(localczv1);
    localczv1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(-2, -2));
    localcwP1.setAlign(ajb.dhZ);
    localczv1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    localczv1.rV();
    czv localczv2 = new czv();
    localczv2.aJ();
    localczv2.setElementMap(localcpa);
    localczv2.setDisplaySize(new Or(48, 48));
    localdRq2.bb(localczv2);
    localczv2.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.dhZ);
    localcwP2.setSize(new Or(-2, -2));
    localczv2.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    aAR localaAR = aAR.checkOut();
    localaAR.setElementMap(localcpa);
    localczv2.bb(localaAR);
    localaAR.brn();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("texture");
    localaaE1.setField("iconUrl");
    localaAR.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    localaAR.rV();
    localczv2.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("bold");
    localdRq2.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg3 = localcaF2.getAppearance();
    localJg3.setElementMap(localcpa);
    localcaF1.bb(localJg3);
    localJg3.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(5, 5, 5, 5));
    localJg3.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    cAf localcAf = cAf.checkOut();
    localcAf.setElementMap(localcpa);
    localcAf.setColor(new bNa(0.29F, 0.17F, 0.07F, 1.0F));
    localcAf.setName("text");
    localJg3.bb(localcAf);
    localcAf.brn();
    localcAf.rV();
    localJg3.rV();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setSize(new Or(-2, -2));
    localcwP3.setAlign(ajb.dih);
    localcaF1.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("text");
    localaaE2.setField("quantity");
    localcaF1.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    aaE localaaE3 = new aaE();
    localaaE3.aJ();
    localaaE3.setElementMap(localcpa);
    localaaE3.setAttribute("visible");
    localaaE3.setField("quantity");
    localcaF1.bb(localaaE3);
    localaaE3.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localaaE3.bb(localanQ2);
    localanQ2.brn();
    aEJ localaEJ = new aEJ();
    localaEJ.aJ();
    localaEJ.setElementMap(localcpa);
    localaEJ.setValue("1");
    localanQ2.bb(localaEJ);
    localaEJ.brn();
    localaEJ.rV();
    localanQ2.rV();
    localaaE3.rV();
    localcaF1.rV();
    localdRq2.rV();
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    localcWk1.setStyle("styledBoldDark10");
    localcWk1.setMinWidth(1);
    localcWk1.setMaxWidth(115);
    localcWk1.setExpandable(false);
    localdRq1.bb(localcWk1);
    localcWk1.brn();
    aaE localaaE4 = new aaE();
    localaaE4.aJ();
    localaaE4.setElementMap(localcpa);
    localaaE4.setAttribute("text");
    localaaE4.setField("description");
    localcWk1.bb(localaaE4);
    localaaE4.brn();
    localaaE4.rV();
    cWk localcWk2 = localcWk1;
    Jg localJg4 = localcWk2.getAppearance();
    localJg4.setElementMap(localcpa);
    ((cwJ)localJg4).setAlign(aFG.ech);
    localcWk1.bb(localJg4);
    localJg4.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(10, 0, 0, 0));
    localJg4.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg4.rV();
    localcWk1.rV();
    localdRq1.rV();
    localeR.rV();
    localccG1.rV();
    return localccG1;
  }

  public bdj d(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setVisible(false);
    localdRq1.setNonBlocking(false);
    localdRq1.setExpandable(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setLocal(true);
    localNK1.setName("questListBar");
    localNK1.setAttribute("visible");
    localdRq1.bb(localNK1);
    localNK1.brn();
    anQ localanQ1 = new anQ();
    localanQ1.aJ();
    localanQ1.setElementMap(localcpa);
    localNK1.bb(localanQ1);
    localanQ1.brn();
    anE localanE1 = new anE();
    localanE1.aJ();
    localanE1.setElementMap(localcpa);
    localanQ1.bb(localanE1);
    localanE1.brn();
    localanE1.rV();
    localanQ1.rV();
    localNK1.rV();
    aId localaId = aId.checkOut();
    localaId.setAlign(aFG.eck);
    localdRq1.bb(localaId);
    localaId.brn();
    localaId.rV();
    ccG localccG = new ccG();
    localccG.aJ();
    localccG.setElementMap(localcpa);
    localccG.setCellSize(new Or(19, 20));
    localccG.setAutoIdealSize(true);
    localccG.setIdealSizeMinColumns(1);
    localccG.setIdealSizeMaxColumns(10);
    localccG.setIdealSizeMinRows(1);
    localccG.setIdealSizeMaxRows(1);
    localdRq1.bb(localccG);
    localccG.brn();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa);
    localdpm1.setAlign(aFG.eck);
    localccG.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setLocal(true);
    localNK2.setName("questListBar");
    localNK2.setAttribute("content");
    localNK2.setField("quests");
    localccG.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    eR localeR = new eR();
    localeR.aJ();
    localeR.setElementMap(localcpa);
    localccG.bb(localeR);
    localeR.brn();
    anQ localanQ2 = new anQ();
    localanQ2.aJ();
    localanQ2.setElementMap(localcpa);
    localeR.bb(localanQ2);
    localanQ2.brn();
    bxx localbxx = new bxx();
    localbxx.aJ();
    localbxx.setElementMap(localcpa);
    localanQ2.bb(localbxx);
    localbxx.brn();
    anE localanE2 = new anE();
    localanE2.aJ();
    localanE2.setElementMap(localcpa);
    localbxx.bb(localanE2);
    localanE2.brn();
    localanE2.rV();
    localbxx.rV();
    localanQ2.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localeR.bb(localdRq2);
    localdRq2.brn();
    czO localczO = new czO();
    localczO.aJ();
    localczO.setAdaptToContentSize(true);
    localdRq2.bb(localczO);
    localczO.brn();
    localczO.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setStyle("AchievementListComplete");
    localdRq2.bb(localczv1);
    localczv1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(-2, -2));
    localcwP1.setAlign(ajb.dhZ);
    localczv1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("visible");
    localaaE1.setField("isCompleted");
    localczv1.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    localczv1.rV();
    czv localczv2 = new czv();
    localczv2.aJ();
    localczv2.setElementMap(localcpa);
    localczv2.setStyle("AchievementListInactive");
    localdRq2.bb(localczv2);
    localczv2.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setSize(new Or(-2, -2));
    localcwP2.setAlign(ajb.dhZ);
    localczv2.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setAttribute("visible");
    localaaE2.setField("isActivated");
    localczv2.bb(localaaE2);
    localaaE2.brn();
    anQ localanQ3 = new anQ();
    localanQ3.aJ();
    localanQ3.setElementMap(localcpa);
    localaaE2.bb(localanQ3);
    localanQ3.brn();
    bqW localbqW1 = new bqW();
    localbqW1.aJ();
    localbqW1.setElementMap(localcpa);
    localanQ3.bb(localbqW1);
    localbqW1.brn();
    localbqW1.rV();
    localanQ3.rV();
    localaaE2.rV();
    localczv2.rV();
    czv localczv3 = new czv();
    localczv3.aJ();
    localczv3.setElementMap(localcpa);
    localczv3.setStyle("AchievementListActive");
    localdRq2.bb(localczv3);
    localczv3.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setSize(new Or(-2, -2));
    localcwP3.setAlign(ajb.dhZ);
    localczv3.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    aaE localaaE3 = new aaE();
    localaaE3.aJ();
    localaaE3.setElementMap(localcpa);
    localaaE3.setAttribute("visible");
    localaaE3.setField("isActivated");
    localczv3.bb(localaaE3);
    localaaE3.brn();
    anQ localanQ4 = new anQ();
    localanQ4.aJ();
    localanQ4.setElementMap(localcpa);
    localaaE3.bb(localanQ4);
    localanQ4.brn();
    bJJ localbJJ = new bJJ();
    localbJJ.aJ();
    localbJJ.setElementMap(localcpa);
    localanQ4.bb(localbJJ);
    localbJJ.brn();
    cOk localcOk = new cOk();
    localcOk.aJ();
    localcOk.setElementMap(localcpa);
    localbJJ.bb(localcOk);
    localcOk.brn();
    localcOk.rV();
    bqW localbqW2 = new bqW();
    localbqW2.aJ();
    localbqW2.setElementMap(localcpa);
    localbJJ.bb(localbqW2);
    localbqW2.brn();
    aaE localaaE4 = new aaE();
    localaaE4.aJ();
    localaaE4.setElementMap(localcpa);
    localaaE4.setAttribute("comparedValue");
    localaaE4.setField("isCompleted");
    localbqW2.bb(localaaE4);
    localaaE4.brn();
    localaaE4.rV();
    localbqW2.rV();
    localbJJ.rV();
    localanQ4.rV();
    localaaE3.rV();
    localczv3.rV();
    String str = "quest";
    avo localavo = new avo();
    localavo.aJ();
    localavo.setElementMap(localcpa);
    if ((localcpa != null) && (str != null))
      localcpa.a(str, localavo);
    localdRq2.bb(localavo);
    localavo.brn();
    aaE localaaE5 = new aaE();
    localaaE5.aJ();
    localaaE5.setElementMap(localcpa);
    localaaE5.setAttribute("value");
    localavo.bb(localaaE5);
    localaaE5.brn();
    localaaE5.rV();
    localavo.rV();
    localdRq2.rV();
    localeR.rV();
    localccG.rV();
    dRq localdRq3 = localdRq1;
    Jg localJg = localdRq3.getAppearance();
    localJg.setElementMap(localcpa);
    localdRq1.bb(localJg);
    localJg.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(0, 0, 15, 0));
    localJg.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg.rV();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa);
    localdpm2.setAlign(aFG.eck);
    localdRq1.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj e(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setStyle("ScrollBorderTop2");
    localczv.setDisplaySize(new Or(260, 45));
    parambdj.bb(localczv);
    localczv.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setAlign(ajb.dhT);
    localcwP.setSize(new Or(-2, -2));
    localczv.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localczv.rV();
    return localczv;
  }

  public bdj f(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    czv localczv = new czv();
    localczv.aJ();
    localczv.setElementMap(localcpa);
    localczv.setStyle("ScrollBorderBottom2");
    localczv.setDisplaySize(new Or(260, 45));
    parambdj.bb(localczv);
    localczv.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setAlign(ajb.dif);
    localcwP.setSize(new Or(-2, -2));
    localczv.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localczv.rV();
    return localczv;
  }
}