import java.util.Stack;

public class bwr
  implements aTK
{
  private uk W;
  private Stack X = new Stack();

  public void a(cpa paramcpa, uk paramuk, dOc paramdOc)
  {
    this.W = paramuk;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    dOc localdOc1 = paramdOc;
    Jg localJg1 = localdOc1.getAppearance();
    localJg1.setElementMap(localcpa);
    ((cwJ)localJg1).setAlignment(aFG.ecj);
    localJg1.setState("default");
    paramdOc.bb(localJg1);
    localJg1.brn();
    bJA localbJA1 = bJA.checkOut();
    localbJA1.setRenderer(cBQ.cxL().bSM().aI("defaultFont"));
    localbJA1.setElementMap(localcpa);
    localJg1.bb(localbJA1);
    localbJA1.brn();
    localbJA1.rV();
    String str1 = "defaultLightColor";
    cAf localcAf1 = cAf.checkOut();
    localcAf1.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localcAf1);
    localcAf1.setColor(new bNa(1.0F, 1.0F, 1.0F, 1.0F));
    localJg1.bb(localcAf1);
    localcAf1.brn();
    localcAf1.rV();
    aAR localaAR1 = aAR.checkOut();
    localaAR1.setElementMap(localcpa);
    localaAR1.setPosition(ajb.dhZ);
    localaAR1.setX(464);
    localaAR1.setY(234);
    localaAR1.setWidth(20);
    localaAR1.setHeight(20);
    localaAR1.setTexture(this.W.aH("default_1.tga"));
    localJg1.bb(localaAR1);
    localaAR1.brn();
    localaAR1.rV();
    localJg1.rV();
    dOc localdOc2 = paramdOc;
    Jg localJg2 = localdOc2.getAppearance();
    localJg2.setElementMap(localcpa);
    ((cwJ)localJg2).setAlignment(aFG.ecj);
    localJg2.setState("mouseHover");
    paramdOc.bb(localJg2);
    localJg2.brn();
    bJA localbJA2 = bJA.checkOut();
    localbJA2.setRenderer(cBQ.cxL().bSM().aI("defaultFont"));
    localbJA2.setElementMap(localcpa);
    localJg2.bb(localbJA2);
    localbJA2.brn();
    localbJA2.rV();
    String str2 = "defaultLightColor";
    cAf localcAf2 = cAf.checkOut();
    localcAf2.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localcAf2);
    localcAf2.setColor(new bNa(1.0F, 1.0F, 1.0F, 1.0F));
    localJg2.bb(localcAf2);
    localcAf2.brn();
    localcAf2.rV();
    aAR localaAR2 = aAR.checkOut();
    localaAR2.setElementMap(localcpa);
    localaAR2.setPosition(ajb.dhZ);
    localaAR2.setX(303);
    localaAR2.setY(5);
    localaAR2.setWidth(20);
    localaAR2.setHeight(20);
    localaAR2.setTexture(this.W.aH("default_0.tga"));
    localJg2.bb(localaAR2);
    localaAR2.brn();
    localaAR2.rV();
    localJg2.rV();
    dOc localdOc3 = paramdOc;
    Jg localJg3 = localdOc3.getAppearance();
    localJg3.setElementMap(localcpa);
    ((cwJ)localJg3).setAlignment(aFG.ecj);
    localJg3.setState("pressed");
    paramdOc.bb(localJg3);
    localJg3.brn();
    bJA localbJA3 = bJA.checkOut();
    localbJA3.setRenderer(cBQ.cxL().bSM().aI("defaultFont"));
    localbJA3.setElementMap(localcpa);
    localJg3.bb(localbJA3);
    localbJA3.brn();
    localbJA3.rV();
    String str3 = "defaultLightColor";
    cAf localcAf3 = cAf.checkOut();
    localcAf3.setElementMap(localcpa);
    if ((localcpa != null) && (str3 != null))
      localcpa.a(str3, localcAf3);
    localcAf3.setColor(new bNa(1.0F, 1.0F, 1.0F, 1.0F));
    localJg3.bb(localcAf3);
    localcAf3.brn();
    localcAf3.rV();
    aAR localaAR3 = aAR.checkOut();
    localaAR3.setElementMap(localcpa);
    localaAR3.setPosition(ajb.dhZ);
    localaAR3.setX(368);
    localaAR3.setY(5);
    localaAR3.setWidth(20);
    localaAR3.setHeight(20);
    localaAR3.setTexture(this.W.aH("default_0.tga"));
    localJg3.bb(localaAR3);
    localaAR3.brn();
    localaAR3.rV();
    localJg3.rV();
    dOc localdOc4 = paramdOc;
    Jg localJg4 = localdOc4.getAppearance();
    localJg4.setElementMap(localcpa);
    ((cwJ)localJg4).setAlignment(aFG.ecj);
    localJg4.setState("selected");
    paramdOc.bb(localJg4);
    localJg4.brn();
    bJA localbJA4 = bJA.checkOut();
    localbJA4.setRenderer(cBQ.cxL().bSM().aI("defaultFont"));
    localbJA4.setElementMap(localcpa);
    localJg4.bb(localbJA4);
    localbJA4.brn();
    localbJA4.rV();
    String str4 = "defaultLightColor";
    cAf localcAf4 = cAf.checkOut();
    localcAf4.setElementMap(localcpa);
    if ((localcpa != null) && (str4 != null))
      localcpa.a(str4, localcAf4);
    localcAf4.setColor(new bNa(1.0F, 1.0F, 1.0F, 1.0F));
    localJg4.bb(localcAf4);
    localcAf4.brn();
    localcAf4.rV();
    aAR localaAR4 = aAR.checkOut();
    localaAR4.setElementMap(localcpa);
    localaAR4.setPosition(ajb.dhZ);
    localaAR4.setX(579);
    localaAR4.setY(234);
    localaAR4.setWidth(20);
    localaAR4.setHeight(20);
    localaAR4.setTexture(this.W.aH("default_1.tga"));
    localJg4.bb(localaAR4);
    localaAR4.brn();
    localaAR4.rV();
    localJg4.rV();
    dOc localdOc5 = paramdOc;
    Jg localJg5 = localdOc5.getAppearance();
    localJg5.setElementMap(localcpa);
    ((cwJ)localJg5).setAlignment(aFG.ecj);
    localJg5.setState("mouseHoverSelected");
    paramdOc.bb(localJg5);
    localJg5.brn();
    bJA localbJA5 = bJA.checkOut();
    localbJA5.setRenderer(cBQ.cxL().bSM().aI("defaultFont"));
    localbJA5.setElementMap(localcpa);
    localJg5.bb(localbJA5);
    localbJA5.brn();
    localbJA5.rV();
    String str5 = "defaultLightColor";
    cAf localcAf5 = cAf.checkOut();
    localcAf5.setElementMap(localcpa);
    if ((localcpa != null) && (str5 != null))
      localcpa.a(str5, localcAf5);
    localcAf5.setColor(new bNa(1.0F, 1.0F, 1.0F, 1.0F));
    localJg5.bb(localcAf5);
    localcAf5.brn();
    localcAf5.rV();
    aAR localaAR5 = aAR.checkOut();
    localaAR5.setElementMap(localcpa);
    localaAR5.setPosition(ajb.dhZ);
    localaAR5.setX(368);
    localaAR5.setY(5);
    localaAR5.setWidth(20);
    localaAR5.setHeight(20);
    localaAR5.setTexture(this.W.aH("default_0.tga"));
    localJg5.bb(localaAR5);
    localaAR5.brn();
    localaAR5.rV();
    localJg5.rV();
    dOc localdOc6 = paramdOc;
    Jg localJg6 = localdOc6.getAppearance();
    localJg6.setElementMap(localcpa);
    ((cwJ)localJg6).setAlignment(aFG.ecj);
    localJg6.setState("pressedSelected");
    paramdOc.bb(localJg6);
    localJg6.brn();
    bJA localbJA6 = bJA.checkOut();
    localbJA6.setRenderer(cBQ.cxL().bSM().aI("defaultFont"));
    localbJA6.setElementMap(localcpa);
    localJg6.bb(localbJA6);
    localbJA6.brn();
    localbJA6.rV();
    String str6 = "defaultLightColor";
    cAf localcAf6 = cAf.checkOut();
    localcAf6.setElementMap(localcpa);
    if ((localcpa != null) && (str6 != null))
      localcpa.a(str6, localcAf6);
    localcAf6.setColor(new bNa(1.0F, 1.0F, 1.0F, 1.0F));
    localJg6.bb(localcAf6);
    localcAf6.brn();
    localcAf6.rV();
    aAR localaAR6 = aAR.checkOut();
    localaAR6.setElementMap(localcpa);
    localaAR6.setPosition(ajb.dhZ);
    localaAR6.setX(303);
    localaAR6.setY(5);
    localaAR6.setWidth(20);
    localaAR6.setHeight(20);
    localaAR6.setTexture(this.W.aH("default_0.tga"));
    localJg6.bb(localaAR6);
    localaAR6.brn();
    localaAR6.rV();
    localJg6.rV();
  }
}