import java.awt.Insets;
import java.util.Stack;

public class cKk
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    String str1 = "root";
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localdRq1);
    localdRq1.setNonBlocking(false);
    localdRq1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    dRq localdRq2 = localdRq1;
    Jg localJg1 = localdRq2.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq1.bb(localJg1);
    localJg1.brn();
    jO localjO = new jO();
    localjO.aJ();
    localjO.setElementMap(localcpa);
    localjO.setColor(new bNa(1.0F, 1.0F, 1.0F, 1.0F));
    localJg1.bb(localjO);
    localjO.brn();
    localjO.rV();
    localJg1.rV();
    String str2 = "selectedWorldReference";
    avo localavo1 = new avo();
    localavo1.aJ();
    localavo1.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localavo1);
    localdRq1.bb(localavo1);
    localavo1.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("value");
    localNK1.setName("worldChoice.selectedWorldReference");
    localavo1.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    localavo1.rV();
    czO localczO1 = new czO();
    localczO1.aJ();
    localdRq1.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq3.setStyle("loginGradientBottom");
    localdRq1.bb(localdRq3);
    localdRq3.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setAlign(ajb.dif);
    localcwP2.setSize(new Or(100.0F, 250));
    localdRq3.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    localdRq3.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setStyle("characterChoiceLeftBackgroundDecorator");
    localdRq1.bb(localczv1);
    localczv1.brn();
    czv localczv2 = localczv1;
    Jg localJg2 = localczv2.getAppearance();
    localJg2.setElementMap(localcpa);
    localczv1.bb(localJg2);
    localJg2.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(200, 0, 0, 0));
    localJg2.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg2.rV();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setAlign(ajb.dhY);
    localczv1.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    localczv1.rV();
    czv localczv3 = new czv();
    localczv3.aJ();
    localczv3.setElementMap(localcpa);
    localczv3.setStyle("characterChoiceRightBackgroundDecorator");
    localdRq1.bb(localczv3);
    localczv3.brn();
    czv localczv4 = localczv3;
    Jg localJg3 = localczv4.getAppearance();
    localJg3.setElementMap(localcpa);
    localczv3.bb(localJg3);
    localJg3.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(200, 0, 0, 0));
    localJg3.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg3.rV();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setAlign(ajb.dia);
    localczv3.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    localczv3.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq1.bb(localdRq4);
    localdRq4.brn();
    cwP localcwP5 = new cwP();
    localcwP5.aJ();
    localcwP5.setElementMap(localcpa);
    localcwP5.setAlign(ajb.dhT);
    localdRq4.bb(localcwP5);
    localcwP5.brn();
    localcwP5.rV();
    dRq localdRq5 = localdRq4;
    Jg localJg4 = localdRq5.getAppearance();
    localJg4.setElementMap(localcpa);
    localdRq4.bb(localJg4);
    localJg4.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(10, 0, 0, 0));
    localJg4.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg4.rV();
    bTm localbTm1 = new bTm();
    localbTm1.aJ();
    localdRq4.bb(localbTm1);
    localbTm1.brn();
    localbTm1.rV();
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    localdRq4.bb(localdRq6);
    localdRq6.brn();
    cba localcba1 = cba.checkOut();
    localcba1.setElementMap(localcpa);
    localcba1.setData(cFu.izR);
    localdRq6.bb(localcba1);
    localcba1.brn();
    localcba1.rV();
    bTm localbTm2 = new bTm();
    localbTm2.aJ();
    localdRq6.bb(localbTm2);
    localbTm2.brn();
    localbTm2.rV();
    czv localczv5 = new czv();
    localczv5.aJ();
    localczv5.setElementMap(localcpa);
    localczv5.setStyle("leftLine");
    localdRq6.bb(localczv5);
    localczv5.brn();
    cba localcba2 = cba.checkOut();
    localcba2.setElementMap(localcpa);
    localcba2.setData(cFu.izV);
    localczv5.bb(localcba2);
    localcba2.brn();
    localcba2.rV();
    localczv5.rV();
    czv localczv6 = new czv();
    localczv6.aJ();
    localczv6.setElementMap(localcpa);
    localczv6.setStyle("rightLine");
    localdRq6.bb(localczv6);
    localczv6.brn();
    cba localcba3 = cba.checkOut();
    localcba3.setElementMap(localcpa);
    localcba3.setData(cFu.izU);
    localczv6.bb(localcba3);
    localcba3.brn();
    localcba3.rV();
    localczv6.rV();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localdRq6.bb(localdRq7);
    localdRq7.brn();
    dRq localdRq8 = localdRq7;
    Jg localJg5 = localdRq8.getAppearance();
    localJg5.setElementMap(localcpa);
    localdRq7.bb(localJg5);
    localJg5.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(0, 5, 0, 5));
    localJg5.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg5.rV();
    cba localcba4 = cba.checkOut();
    localcba4.setElementMap(localcpa);
    localcba4.setData(cFu.izR);
    localdRq7.bb(localcba4);
    localcba4.brn();
    localcba4.rV();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    String str3 = "%selection%";
    str3 = str3.replace("%selection%", cBQ.cxL().mL("selection"));
    localcaF1.setText(str3);
    localcaF1.setStyle("characterCreationMainTitle");
    localdRq7.bb(localcaF1);
    localcaF1.brn();
    localcaF1.rV();
    localdRq7.rV();
    localdRq6.rV();
    caF localcaF2 = new caF();
    localcaF2.aJ();
    localcaF2.setElementMap(localcpa);
    String str4 = "%yourWorld%";
    str4 = str4.replace("%yourWorld%", cBQ.cxL().mL("yourWorld"));
    localcaF2.setText(str4);
    localcaF2.setStyle("characterCreationTitle");
    localdRq4.bb(localcaF2);
    localcaF2.brn();
    cba localcba5 = cba.checkOut();
    localcba5.setElementMap(localcpa);
    localcba5.setData(cFu.izT);
    localcaF2.bb(localcba5);
    localcba5.brn();
    localcba5.rV();
    caF localcaF3 = localcaF2;
    Jg localJg6 = localcaF3.getAppearance();
    localJg6.setElementMap(localcpa);
    ((cwJ)localJg6).setAlignment(aFG.eck);
    localcaF2.bb(localJg6);
    localJg6.brn();
    localJg6.rV();
    localcaF2.rV();
    localdRq4.rV();
    String str5 = "sub";
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa);
    if ((localcpa != null) && (str5 != null))
      localcpa.a(str5, localdRq9);
    localdRq1.bb(localdRq9);
    localdRq9.brn();
    cwP localcwP6 = new cwP();
    localcwP6.aJ();
    localcwP6.setElementMap(localcpa);
    localcwP6.setAlign(ajb.dhZ);
    localdRq9.bb(localcwP6);
    localcwP6.brn();
    localcwP6.rV();
    dRq localdRq10 = localdRq9;
    Jg localJg7 = localdRq10.getAppearance();
    localJg7.setElementMap(localcpa);
    localdRq9.bb(localJg7);
    localJg7.brn();
    bmv localbmv5 = bmv.checkOut();
    localbmv5.setElementMap(localcpa);
    localbmv5.setInsets(new Insets(50, 0, 0, 0));
    localJg7.bb(localbmv5);
    localbmv5.brn();
    localbmv5.rV();
    localJg7.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localdRq9.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dRq localdRq11 = dRq.checkOut();
    localdRq11.setElementMap(localcpa);
    localdRq11.setStyle("worldChoiceBackground");
    localdRq11.setPrefSize(new Or(948, 546));
    localdRq9.bb(localdRq11);
    localdRq11.brn();
    String str6 = "world";
    bmG localbmG = new bmG();
    localbmG.aJ();
    localbmG.setElementMap(localcpa);
    if ((localcpa != null) && (str6 != null))
      localcpa.a(str6, localbmG);
    localdRq11.bb(localbmG);
    localbmG.brn();
    localbmG.rV();
    ccG localccG1 = new ccG();
    localccG1.aJ();
    localccG1.setElementMap(localcpa);
    localccG1.setCellSize(new Or(210, 345));
    localccG1.setAlign(aFG.eck);
    localdRq11.bb(localccG1);
    localccG1.brn();
    ccG localccG2 = localccG1;
    Jg localJg8 = localccG2.getAppearance();
    localJg8.setElementMap(localcpa);
    localccG1.bb(localJg8);
    localJg8.brn();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(140, 0, 0, 0));
    localJg8.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    localJg8.rV();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setAttribute("content");
    localNK2.setName("worldChoice.worldReferencesList");
    localccG1.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    eR localeR = new eR();
    localeR.aJ();
    localeR.setElementMap(localcpa);
    localccG1.bb(localeR);
    localeR.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localeR.bb(localanQ);
    localanQ.brn();
    bxx localbxx = new bxx();
    localbxx.aJ();
    localbxx.setElementMap(localcpa);
    localanQ.bb(localbxx);
    localbxx.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localbxx.bb(localanE);
    localanE.brn();
    localanE.rV();
    localbxx.rV();
    localanQ.rV();
    dRq localdRq12 = dRq.checkOut();
    localdRq12.setElementMap(localcpa);
    localdRq12.setNonBlocking(true);
    localeR.bb(localdRq12);
    localdRq12.brn();
    String str7 = "worldReference";
    avo localavo2 = new avo();
    localavo2.aJ();
    localavo2.setElementMap(localcpa);
    if ((localcpa != null) && (str7 != null))
      localcpa.a(str7, localavo2);
    localdRq12.bb(localavo2);
    localavo2.brn();
    aaE localaaE1 = new aaE();
    localaaE1.aJ();
    localaaE1.setElementMap(localcpa);
    localaaE1.setAttribute("value");
    localavo2.bb(localaaE1);
    localaaE1.brn();
    localaaE1.rV();
    localavo2.rV();
    bTm localbTm3 = new bTm();
    localbTm3.aJ();
    localdRq12.bb(localbTm3);
    localbTm3.brn();
    localbTm3.rV();
    dRq localdRq13 = dRq.checkOut();
    localdRq13.setElementMap(localcpa);
    localdRq12.bb(localdRq13);
    localdRq13.brn();
    cba localcba6 = cba.checkOut();
    localcba6.setElementMap(localcpa);
    localcba6.setData(cFu.izR);
    localdRq13.bb(localcba6);
    localcba6.brn();
    localcba6.rV();
    czO localczO2 = new czO();
    localczO2.aJ();
    localdRq13.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    dRq localdRq14 = dRq.checkOut();
    localdRq14.setElementMap(localcpa);
    localdRq14.setStyle("worldChoicePaysage");
    localdRq13.bb(localdRq14);
    localdRq14.brn();
    cwP localcwP7 = new cwP();
    localcwP7.aJ();
    localcwP7.setElementMap(localcpa);
    localcwP7.setAlign(ajb.dhZ);
    localcwP7.setSize(new Or(209, 249));
    localdRq14.bb(localcwP7);
    localcwP7.brn();
    localcwP7.rV();
    localdRq14.rV();
    aHd localaHd = new aHd();
    localaHd.aJ();
    localaHd.setElementMap(localcpa);
    localaHd.setGroupId("world");
    localaHd.setStyle("worldChoiceGate");
    adV localadV = new adV();
    localadV.hg("wakfu.worldChoice:selectWorld(worldReference)");
    localaHd.setOnMouseRelease(localadV);
    Zd localZd = new Zd();
    localZd.hg("wakfu.worldChoice:validWorldDoubleClick(worldReference)");
    localaHd.setOnDoubleClick(localZd);
    bDy localbDy = new bDy();
    localbDy.hg("wakfu.worldChoice:mouseEnterOnWorld(worldReference)");
    localaHd.setOnMouseEnter(localbDy);
    DY localDY = new DY();
    localDY.hg("wakfu.worldChoice:mouseExitOffWorld");
    localaHd.setOnMouseExit(localDY);
    localdRq13.bb(localaHd);
    localaHd.brn();
    cwP localcwP8 = new cwP();
    localcwP8.aJ();
    localcwP8.setElementMap(localcpa);
    localcwP8.setAlign(ajb.dhZ);
    localaHd.bb(localcwP8);
    localcwP8.brn();
    localcwP8.rV();
    localaHd.rV();
    aEY localaEY1 = new aEY();
    localaEY1.aJ();
    localaEY1.setElementMap(localcpa);
    localaEY1.setRepeatNumber(1);
    localaEY1.setStyle("worldChoiceSmallCharacter");
    localaEY1.setNonBlocking(true);
    localdRq13.bb(localaEY1);
    localaEY1.brn();
    cwP localcwP9 = new cwP();
    localcwP9.aJ();
    localcwP9.setElementMap(localcpa);
    localcwP9.setAlign(ajb.dhZ);
    localaEY1.bb(localcwP9);
    localcwP9.brn();
    localcwP9.rV();
    aEY localaEY2 = localaEY1;
    Jg localJg9 = localaEY2.getAppearance();
    localJg9.setElementMap(localcpa);
    localaEY1.bb(localJg9);
    localJg9.brn();
    bmv localbmv6 = bmv.checkOut();
    localbmv6.setElementMap(localcpa);
    localbmv6.setInsets(new Insets(180, 0, 0, 0));
    localJg9.bb(localbmv6);
    localbmv6.brn();
    localbmv6.rV();
    localJg9.rV();
    aaE localaaE2 = new aaE();
    localaaE2.aJ();
    localaaE2.setElementMap(localcpa);
    localaaE2.setField("characterNumber");
    localaaE2.setAttribute("repeatNumber");
    localaEY1.bb(localaaE2);
    localaaE2.brn();
    localaaE2.rV();
    localaEY1.rV();
    localdRq13.rV();
    dRq localdRq15 = dRq.checkOut();
    localdRq15.setElementMap(localcpa);
    localdRq12.bb(localdRq15);
    localdRq15.brn();
    cba localcba7 = cba.checkOut();
    localcba7.setElementMap(localcpa);
    localcba7.setData(cFu.izT);
    localdRq15.bb(localcba7);
    localcba7.brn();
    localcba7.rV();
    dRq localdRq16 = localdRq15;
    Jg localJg10 = localdRq16.getAppearance();
    localJg10.setElementMap(localcpa);
    localdRq15.bb(localJg10);
    localJg10.brn();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(0, 0, 10, 0));
    localJg10.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    bmv localbmv7 = bmv.checkOut();
    localbmv7.setElementMap(localcpa);
    localbmv7.setInsets(new Insets(0, 20, 0, 20));
    localJg10.bb(localbmv7);
    localbmv7.brn();
    localbmv7.rV();
    localJg10.rV();
    aId localaId2 = aId.checkOut();
    localaId2.setHorizontal(false);
    localdRq15.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    caF localcaF4 = new caF();
    localcaF4.aJ();
    localcaF4.setElementMap(localcpa);
    localcaF4.setStyle("title");
    localcaF4.setNonBlocking(true);
    localdRq15.bb(localcaF4);
    localcaF4.brn();
    a(localcaF4);
    b(localcaF4);
    localcaF4.rV();
    d(localdRq15);
    e(localdRq15);
    localdRq15.rV();
    localdRq12.rV();
    localeR.rV();
    localccG1.rV();
    localdRq11.rV();
    f(localdRq9);
    localdRq9.rV();
    g(localdRq1);
    localdRq1.rV();
    return localdRq1;
  }

  public bdj a(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dOc localdOc = (dOc)parambdj;
    Jg localJg = localdOc.getAppearance();
    localJg.setElementMap(localcpa);
    ((cwJ)localJg).setAlignment(aFG.eck);
    parambdj.bb(localJg);
    localJg.brn();
    localJg.rV();
    return localJg;
  }

  public bdj b(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    aaE localaaE = new aaE();
    localaaE.aJ();
    localaaE.setElementMap(localcpa);
    localaaE.setAttribute("text");
    localaaE.setField("realName");
    parambdj.bb(localaaE);
    localaaE.brn();
    localaaE.rV();
    return localaaE;
  }

  public bdj d(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    cWk localcWk = new cWk();
    localcWk.aJ();
    localcWk.setElementMap(localcpa);
    localcWk.setStyle("worldChoiceServerStatus");
    parambdj.bb(localcWk);
    localcWk.brn();
    aaE localaaE = new aaE();
    localaaE.aJ();
    localaaE.setElementMap(localcpa);
    localaaE.setField("status");
    localaaE.setAttribute("text");
    localcWk.bb(localaaE);
    localaaE.brn();
    localaaE.rV();
    localcWk.rV();
    return localcWk;
  }

  public bdj e(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    caF localcaF = new caF();
    localcaF.aJ();
    localcaF.setElementMap(localcpa);
    localcaF.setStyle("worldChoiceServerInfo");
    parambdj.bb(localcaF);
    localcaF.brn();
    aaE localaaE = new aaE();
    localaaE.aJ();
    localaaE.setElementMap(localcpa);
    localaaE.setAttribute("text");
    localaaE.setField("community");
    localcaF.bb(localaaE);
    localaaE.brn();
    localaaE.rV();
    localcaF.rV();
    return localcaF;
  }

  public bdj f(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    dpm localdpm = new dpm();
    localdpm.aJ();
    localdpm.setElementMap(localcpa);
    localdpm.setAlign(aFG.eck);
    localdRq1.bb(localdpm);
    localdpm.brn();
    localdpm.rV();
    dRq localdRq2 = localdRq1;
    Jg localJg1 = localdRq2.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq1.bb(localJg1);
    localJg1.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(0, 5, 0, 5));
    localJg1.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    localJg1.rV();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(false);
    localdRq1.bb(localaId);
    localaId.brn();
    localaId.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq3.setStyle("greyBackgrounded");
    localdRq1.bb(localdRq3);
    localdRq3.brn();
    dRq localdRq4 = localdRq3;
    Jg localJg2 = localdRq4.getAppearance();
    localJg2.setElementMap(localcpa);
    localdRq3.bb(localJg2);
    localJg2.brn();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(3, 10, 3, 10));
    localJg2.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    localJg2.rV();
    biy localbiy1 = new biy();
    localbiy1.aJ();
    localbiy1.setElementMap(localcpa);
    localbiy1.setStyle("big");
    localbiy1.setClickSoundId(600002);
    String str = "%valid%";
    str = str.replace("%valid%", cBQ.cxL().mL("valid"));
    localbiy1.setText(str);
    localbiy1.setFocusable(true);
    localbiy1.setFocused(true);
    csA localcsA = new csA();
    localcsA.hg("wakfu.worldChoice:validWorld(selectedWorldReference)");
    localbiy1.setOnClick(localcsA);
    localdRq3.bb(localbiy1);
    localbiy1.brn();
    biy localbiy2 = localbiy1;
    Jg localJg3 = localbiy2.getAppearance();
    localJg3.setElementMap(localcpa);
    localbiy1.bb(localJg3);
    localJg3.brn();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(5, 15, 5, 15));
    localJg3.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    localJg3.rV();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setName("worldChoice.selectedWorldReference");
    localNK.setAttribute("enabled");
    localbiy1.bb(localNK);
    localNK.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localNK.bb(localanQ);
    localanQ.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localanQ.bb(localanE);
    localanE.brn();
    localanE.rV();
    localanQ.rV();
    localNK.rV();
    localbiy1.rV();
    localdRq3.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj g(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setVisible(false);
    localdRq1.setStyle("rollOverBackground");
    parambdj.bb(localdRq1);
    localdRq1.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setAlign(ajb.dhZ);
    localcwP.setSize(new Or(510, 468));
    localdRq1.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    dRq localdRq2 = localdRq1;
    Jg localJg = localdRq2.getAppearance();
    localJg.setElementMap(localcpa);
    localdRq1.bb(localJg);
    localJg.brn();
    bmv localbmv = bmv.checkOut();
    localbmv.setElementMap(localcpa);
    localbmv.setInsets(new Insets(320, 0, 0, 0));
    localJg.bb(localbmv);
    localbmv.brn();
    localbmv.rV();
    cuR localcuR = new cuR();
    localcuR.aJ();
    localcuR.setElementMap(localcpa);
    localcuR.setInsets(new Insets(30, 30, 30, 30));
    localJg.bb(localcuR);
    localcuR.brn();
    localcuR.rV();
    localJg.rV();
    aId localaId = aId.checkOut();
    localaId.setHorizontal(false);
    localdRq1.bb(localaId);
    localaId.brn();
    localaId.rV();
    caF localcaF = new caF();
    localcaF.aJ();
    localcaF.setElementMap(localcpa);
    localcaF.setStyle("bold");
    localdRq1.bb(localcaF);
    localcaF.brn();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("text");
    localNK1.setName("worldChoice.overWorldReference");
    localNK1.setField("realName");
    localcaF.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    localcaF.rV();
    cWk localcWk = new cWk();
    localcWk.aJ();
    localcWk.setElementMap(localcpa);
    localcWk.setMinWidth(450);
    localdRq1.bb(localcWk);
    localcWk.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setAttribute("text");
    localNK2.setName("worldChoice.overWorldReference");
    localNK2.setField("description");
    localcWk.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    localcWk.rV();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setAttribute("visible");
    localNK3.setName("worldChoice.overWorldReference");
    localdRq1.bb(localNK3);
    localNK3.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localNK3.bb(localanQ);
    localanQ.brn();
    anE localanE = new anE();
    localanE.aJ();
    localanE.setElementMap(localcpa);
    localanQ.bb(localanE);
    localanE.brn();
    localanE.rV();
    localanQ.rV();
    localNK3.rV();
    localdRq1.rV();
    return localdRq1;
  }
}