import java.awt.Insets;
import java.util.Stack;

public class dlc
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    bpn localbpn = new bpn();
    localbpn.aJ();
    localbpn.setElementMap(localcpa);
    localbpn.brn();
    czO localczO1 = new czO();
    localczO1.aJ();
    localczO1.setAdaptToContentSize(true);
    localbpn.bb(localczO1);
    localczO1.brn();
    localczO1.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setStyle("new");
    localbpn.bb(localdRq1);
    localdRq1.brn();
    dRq localdRq2 = localdRq1;
    Jg localJg1 = localdRq2.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq1.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(50, 50, 50, 50));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localaId1.setAlign(aFG.ech);
    localdRq1.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dqa localdqa1 = new dqa();
    localdqa1.aJ();
    localdqa1.setElementMap(localcpa);
    localdqa1.setExpandable(false);
    localdRq1.bb(localdqa1);
    localdqa1.brn();
    dqa localdqa2 = localdqa1;
    Jg localJg2 = localdqa2.getAppearance();
    localJg2.setElementMap(localcpa);
    localdqa1.bb(localJg2);
    localJg2.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 15, 0, 15));
    localJg2.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg2.rV();
    localdqa1.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq1.bb(localdRq3);
    localdRq3.brn();
    dRq localdRq4 = localdRq3;
    Jg localJg3 = localdRq4.getAppearance();
    localJg3.setElementMap(localcpa);
    localdRq3.bb(localJg3);
    localJg3.brn();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(3, 12, 0, 12));
    localJg3.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg3.rV();
    String str1 = "windowContentContainer";
    dRq localdRq5 = dRq.checkOut();
    localdRq5.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localdRq5);
    localdRq3.bb(localdRq5);
    localdRq5.brn();
    dRq localdRq6 = localdRq5;
    Jg localJg4 = localdRq6.getAppearance();
    localJg4.setElementMap(localcpa);
    localdRq5.bb(localJg4);
    localJg4.brn();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(16, 23, 16, 23));
    localJg4.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    localJg4.rV();
    aId localaId2 = aId.checkOut();
    localaId2.setHorizontal(false);
    localdRq5.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    String str2 = "messageBoxTextView";
    cWk localcWk1 = new cWk();
    localcWk1.aJ();
    localcWk1.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localcWk1);
    localcWk1.setMinWidth(250);
    csA localcsA = new csA();
    localcsA.hg("wakfu:openLinkInBrowser");
    localcWk1.setOnClick(localcsA);
    localdRq5.bb(localcWk1);
    localcWk1.brn();
    cWk localcWk2 = localcWk1;
    Jg localJg5 = localcWk2.getAppearance();
    localJg5.setElementMap(localcpa);
    localcWk1.bb(localJg5);
    localJg5.brn();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(5, 5, 5, 5));
    localJg5.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg5.rV();
    localcWk1.rV();
    String str3 = "messageBoxTextEditor";
    aTp localaTp1 = new aTp();
    localaTp1.aJ();
    localaTp1.setElementMap(localcpa);
    if ((localcpa != null) && (str3 != null))
      localcpa.a(str3, localaTp1);
    localdRq5.bb(localaTp1);
    localaTp1.brn();
    aTp localaTp2 = localaTp1;
    Jg localJg6 = localaTp2.getAppearance();
    localJg6.setElementMap(localcpa);
    localaTp1.bb(localJg6);
    localJg6.brn();
    bmv localbmv5 = bmv.checkOut();
    localbmv5.setElementMap(localcpa);
    localbmv5.setInsets(new Insets(5, 5, 5, 5));
    localJg6.bb(localbmv5);
    localbmv5.brn();
    localbmv5.rV();
    localJg6.rV();
    localaTp1.rV();
    String str4 = "messageBoxButtonsContainer";
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    if ((localcpa != null) && (str4 != null))
      localcpa.a(str4, localdRq7);
    localdRq7.setExpandable(false);
    localdRq5.bb(localdRq7);
    localdRq7.brn();
    aId localaId3 = aId.checkOut();
    localaId3.setAlign(aFG.eck);
    localdRq7.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    dRq localdRq8 = localdRq7;
    Jg localJg7 = localdRq8.getAppearance();
    localJg7.setElementMap(localcpa);
    localdRq7.bb(localJg7);
    localJg7.brn();
    bmv localbmv6 = bmv.checkOut();
    localbmv6.setElementMap(localcpa);
    localbmv6.setInsets(new Insets(5, 0, 5, 0));
    localJg7.bb(localbmv6);
    localbmv6.brn();
    localbmv6.rV();
    localJg7.rV();
    String str5 = "messageBoxButton";
    biy localbiy1 = new biy();
    localbiy1.aJ();
    localbiy1.setElementMap(localcpa);
    if ((localcpa != null) && (str5 != null))
      localcpa.a(str5, localbiy1);
    localbiy1.setPrefSize(new Or(50, 0));
    localbiy1.setExpandable(false);
    localbiy1.setStyle("small");
    localdRq7.bb(localbiy1);
    localbiy1.brn();
    biy localbiy2 = localbiy1;
    Jg localJg8 = localbiy2.getAppearance();
    localJg8.setElementMap(localcpa);
    localbiy1.bb(localJg8);
    localJg8.brn();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(0, 10, 0, 10));
    localJg8.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    localJg8.rV();
    localbiy1.rV();
    localdRq7.rV();
    localdRq5.rV();
    localdRq3.rV();
    localdRq1.rV();
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa);
    localbpn.bb(localdRq9);
    localdRq9.brn();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localdRq9.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    czO localczO2 = new czO();
    localczO2.aJ();
    localczO2.setAdaptToContentSize(true);
    localdRq9.bb(localczO2);
    localczO2.brn();
    localczO2.rV();
    dRq localdRq10 = dRq.checkOut();
    localdRq10.setElementMap(localcpa);
    localdRq9.bb(localdRq10);
    localdRq10.brn();
    cwP localcwP3 = new cwP();
    localcwP3.aJ();
    localcwP3.setElementMap(localcpa);
    localcwP3.setAlign(ajb.dhT);
    localcwP3.setYOffset(-20);
    localcwP3.setSize(new Or(-2, -2));
    localdRq10.bb(localcwP3);
    localcwP3.brn();
    localcwP3.rV();
    czO localczO3 = new czO();
    localczO3.aJ();
    localczO3.setAdaptToContentSize(true);
    localdRq10.bb(localczO3);
    localczO3.brn();
    localczO3.rV();
    czv localczv1 = new czv();
    localczv1.aJ();
    localczv1.setElementMap(localcpa);
    localczv1.setStyle("messageBoxIconDecorator");
    localczv1.setNonBlocking(true);
    localdRq10.bb(localczv1);
    localczv1.brn();
    cwP localcwP4 = new cwP();
    localcwP4.aJ();
    localcwP4.setElementMap(localcpa);
    localcwP4.setAlign(ajb.dhZ);
    localcwP4.setSize(new Or(-2, -2));
    localczv1.bb(localcwP4);
    localcwP4.brn();
    localcwP4.rV();
    localczv1.rV();
    String str6 = "messageBoxImage";
    czv localczv2 = new czv();
    localczv2.aJ();
    localczv2.setElementMap(localcpa);
    if ((localcpa != null) && (str6 != null))
      localcpa.a(str6, localczv2);
    localczv2.setNonBlocking(true);
    localczv2.setScaled(true);
    localczv2.setKeepAspectRatio(true);
    localdRq10.bb(localczv2);
    localczv2.brn();
    cwP localcwP5 = new cwP();
    localcwP5.aJ();
    localcwP5.setElementMap(localcpa);
    localcwP5.setAlign(ajb.dhZ);
    localcwP5.setSize(new Or(-2, -2));
    localcwP5.setYOffset(12);
    localczv2.bb(localcwP5);
    localcwP5.brn();
    localcwP5.rV();
    localczv2.rV();
    localdRq10.rV();
    localdRq9.rV();
    cwP localcwP6 = new cwP();
    localcwP6.aJ();
    localcwP6.setElementMap(localcpa);
    localcwP6.setAlign(ajb.dhZ);
    localbpn.bb(localcwP6);
    localcwP6.brn();
    localcwP6.rV();
    localbpn.rV();
    return localbpn;
  }
}