import java.awt.Insets;
import java.util.Stack;

public class cyK
  implements cEa
{
  private Stack X = new Stack();
  private cDA Y;

  public bdj a(cDA paramcDA, cpa paramcpa)
  {
    this.Y = paramcDA;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    bpn localbpn = new bpn();
    localbpn.aJ();
    localbpn.setElementMap(localcpa);
    localbpn.setPack(true);
    localbpn.brn();
    czO localczO = new czO();
    localczO.aJ();
    localczO.setAdaptToContentSize(true);
    localbpn.bb(localczO);
    localczO.brn();
    localczO.rV();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localbpn.bb(localdRq1);
    localdRq1.brn();
    cwP localcwP1 = new cwP();
    localcwP1.aJ();
    localcwP1.setElementMap(localcpa);
    localcwP1.setSize(new Or(100.0F, 100.0F));
    localdRq1.bb(localcwP1);
    localcwP1.brn();
    localcwP1.rV();
    localdRq1.rV();
    dRq localdRq2 = dRq.checkOut();
    localdRq2.setElementMap(localcpa);
    localdRq2.setStyle("windowNew");
    localbpn.bb(localdRq2);
    localdRq2.brn();
    dRq localdRq3 = localdRq2;
    Jg localJg1 = localdRq3.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq2.bb(localJg1);
    localJg1.brn();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(10, 5, 12, 5));
    localJg1.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    localJg1.rV();
    cwP localcwP2 = new cwP();
    localcwP2.aJ();
    localcwP2.setElementMap(localcpa);
    localcwP2.setSize(new Or(100.0F, 100.0F));
    localdRq2.bb(localcwP2);
    localcwP2.brn();
    localcwP2.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localaId1.setAlign(aFG.ech);
    localdRq2.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dqa localdqa1 = new dqa();
    localdqa1.aJ();
    localdqa1.setElementMap(localcpa);
    localdqa1.setExpandable(false);
    localdRq2.bb(localdqa1);
    localdqa1.brn();
    dqa localdqa2 = localdqa1;
    Jg localJg2 = localdqa2.getAppearance();
    localJg2.setElementMap(localcpa);
    localdqa1.bb(localJg2);
    localJg2.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(0, 10, 0, 10));
    localJg2.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg2.rV();
    localdqa1.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq2.bb(localdRq4);
    localdRq4.brn();
    dRq localdRq5 = localdRq4;
    Jg localJg3 = localdRq5.getAppearance();
    localJg3.setElementMap(localcpa);
    localdRq4.bb(localJg3);
    localJg3.brn();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(0, 12, 0, 12));
    localJg3.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg3.rV();
    String str1 = "windowContentContainer";
    dRq localdRq6 = dRq.checkOut();
    localdRq6.setElementMap(localcpa);
    if ((localcpa != null) && (str1 != null))
      localcpa.a(str1, localdRq6);
    localdRq4.bb(localdRq6);
    localdRq6.brn();
    dRq localdRq7 = dRq.checkOut();
    localdRq7.setElementMap(localcpa);
    localdRq6.bb(localdRq7);
    localdRq7.brn();
    aId localaId2 = aId.checkOut();
    localaId2.setAlign(aFG.ech);
    localaId2.setHorizontal(false);
    localdRq7.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    dRq localdRq8 = dRq.checkOut();
    localdRq8.setElementMap(localcpa);
    localdRq8.setExpandable(false);
    localdRq7.bb(localdRq8);
    localdRq8.brn();
    aId localaId3 = aId.checkOut();
    localaId3.setAlign(aFG.ech);
    localaId3.setHorizontal(false);
    localdRq8.bb(localaId3);
    localaId3.brn();
    localaId3.rV();
    NK localNK1 = NK.checkOut();
    localNK1.setElementMap(localcpa);
    localNK1.setAttribute("visible");
    localNK1.setName("isEditingGuildDescs");
    localdRq8.bb(localNK1);
    localNK1.brn();
    localNK1.rV();
    dRq localdRq9 = dRq.checkOut();
    localdRq9.setElementMap(localcpa);
    localdRq9.setExpandable(false);
    localdRq8.bb(localdRq9);
    localdRq9.brn();
    NK localNK2 = NK.checkOut();
    localNK2.setElementMap(localcpa);
    localNK2.setAttribute("visible");
    localNK2.setName("guild");
    localNK2.setField("hasRightToEditGuildDescription");
    localdRq9.bb(localNK2);
    localNK2.brn();
    localNK2.rV();
    aId localaId4 = aId.checkOut();
    localaId4.setHorizontal(false);
    localaId4.setAlign(aFG.ech);
    localdRq9.bb(localaId4);
    localaId4.brn();
    localaId4.rV();
    dRq localdRq10 = dRq.checkOut();
    localdRq10.setElementMap(localcpa);
    localdRq10.setStyle("titleBar");
    localdRq10.setExpandable(false);
    localdRq9.bb(localdRq10);
    localdRq10.brn();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("whiteTitle");
    String str2 = "%guild.description%";
    str2 = str2.replace("%guild.description%", cBQ.cxL().mL("guild.description"));
    localcaF1.setText(str2);
    localcaF1.setNonBlocking(true);
    localcaF1.setExpandable(false);
    localdRq10.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg4 = localcaF2.getAppearance();
    localJg4.setElementMap(localcpa);
    ((cwJ)localJg4).setAlign(aFG.ech);
    localcaF1.bb(localJg4);
    localJg4.brn();
    localJg4.rV();
    localcaF1.rV();
    localdRq10.rV();
    dRq localdRq11 = dRq.checkOut();
    localdRq11.setElementMap(localcpa);
    localdRq11.setStyle("ShortcutRowBackgroundFull");
    localdRq11.setExpandable(false);
    localdRq9.bb(localdRq11);
    localdRq11.brn();
    dRq localdRq12 = localdRq11;
    Jg localJg5 = localdRq12.getAppearance();
    localJg5.setElementMap(localcpa);
    localdRq11.bb(localJg5);
    localJg5.brn();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(3, 3, 3, 3));
    localJg5.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(2, 2, 5, 2));
    localJg5.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg5.rV();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa);
    localdpm1.setAlign(aFG.ecj);
    localdRq11.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    aId localaId5 = aId.checkOut();
    localaId5.setAlign(aFG.ecj);
    localdRq11.bb(localaId5);
    localaId5.brn();
    localaId5.rV();
    String str3 = "guildDescription";
    aTp localaTp1 = new aTp();
    localaTp1.aJ();
    localaTp1.setElementMap(localcpa);
    if ((localcpa != null) && (str3 != null))
      localcpa.a(str3, localaTp1);
    localaTp1.setRestrict("[.*&[^<>]]");
    localaTp1.setStyle("withoutBorder");
    localaTp1.setMaxChars(200);
    localaTp1.setPrefSize(new Or(300, 100));
    localaTp1.setExpandable(false);
    aOn localaOn1 = new aOn();
    localaOn1.hg("wakfu.guildManagement:onKeyEvent(applyDescription)");
    localaTp1.setOnKeyPress(localaOn1);
    localaTp1.setMultiline(true);
    localdRq11.bb(localaTp1);
    localaTp1.brn();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa);
    localdpm2.setAlign(aFG.ech);
    localaTp1.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    NK localNK3 = NK.checkOut();
    localNK3.setElementMap(localcpa);
    localNK3.setName("guild");
    localNK3.setAttribute("text");
    localNK3.setField("guildDescription");
    localaTp1.bb(localNK3);
    localNK3.brn();
    localNK3.rV();
    localaTp1.rV();
    localdRq11.rV();
    String str4 = "applyDescription";
    biy localbiy1 = new biy();
    localbiy1.aJ();
    localbiy1.setElementMap(localcpa);
    if ((localcpa != null) && (str4 != null))
      localcpa.a(str4, localbiy1);
    String str5 = "%apply%";
    str5 = str5.replace("%apply%", cBQ.cxL().mL("apply"));
    localbiy1.setText(str5);
    localbiy1.setExpandable(false);
    csA localcsA1 = new csA();
    localcsA1.hg("wakfu.guildManagement:applyGuildDescription(guildDescription)");
    localbiy1.setOnClick(localcsA1);
    localbiy1.setEnabled(false);
    localdRq9.bb(localbiy1);
    localbiy1.brn();
    dpm localdpm3 = new dpm();
    localdpm3.aJ();
    localdpm3.setElementMap(localcpa);
    localdpm3.setAlign(aFG.ecl);
    localbiy1.bb(localdpm3);
    localdpm3.brn();
    localdpm3.rV();
    biy localbiy2 = localbiy1;
    Jg localJg6 = localbiy2.getAppearance();
    localJg6.setElementMap(localcpa);
    localbiy1.bb(localJg6);
    localJg6.brn();
    cuR localcuR3 = new cuR();
    localcuR3.aJ();
    localcuR3.setElementMap(localcpa);
    localcuR3.setInsets(new Insets(0, 5, 0, 5));
    localJg6.bb(localcuR3);
    localcuR3.brn();
    localcuR3.rV();
    bmv localbmv4 = bmv.checkOut();
    localbmv4.setElementMap(localcpa);
    localbmv4.setInsets(new Insets(5, 0, 0, 5));
    localJg6.bb(localbmv4);
    localbmv4.brn();
    localbmv4.rV();
    localJg6.rV();
    localbiy1.rV();
    localdRq9.rV();
    dRq localdRq13 = dRq.checkOut();
    localdRq13.setElementMap(localcpa);
    localdRq13.setExpandable(false);
    localdRq8.bb(localdRq13);
    localdRq13.brn();
    NK localNK4 = NK.checkOut();
    localNK4.setElementMap(localcpa);
    localNK4.setAttribute("visible");
    localNK4.setName("guild");
    localNK4.setField("hasRightToEditGuildMessage");
    localdRq13.bb(localNK4);
    localNK4.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localNK4.bb(localanQ);
    localanQ.brn();
    bJJ localbJJ = new bJJ();
    localbJJ.aJ();
    localbJJ.setElementMap(localcpa);
    localanQ.bb(localbJJ);
    localbJJ.brn();
    cOk localcOk1 = new cOk();
    localcOk1.aJ();
    localcOk1.setElementMap(localcpa);
    localbJJ.bb(localcOk1);
    localcOk1.brn();
    localcOk1.rV();
    cOk localcOk2 = new cOk();
    localcOk2.aJ();
    localcOk2.setElementMap(localcpa);
    localbJJ.bb(localcOk2);
    localcOk2.brn();
    localcOk2.rV();
    localbJJ.rV();
    localanQ.rV();
    localNK4.rV();
    dRq localdRq14 = localdRq13;
    Jg localJg7 = localdRq14.getAppearance();
    localJg7.setElementMap(localcpa);
    localdRq13.bb(localJg7);
    localJg7.brn();
    bmv localbmv5 = bmv.checkOut();
    localbmv5.setElementMap(localcpa);
    localbmv5.setInsets(new Insets(10, 0, 0, 0));
    localJg7.bb(localbmv5);
    localbmv5.brn();
    localbmv5.rV();
    localJg7.rV();
    localdRq13.rV();
    dRq localdRq15 = dRq.checkOut();
    localdRq15.setElementMap(localcpa);
    localdRq15.setExpandable(false);
    localdRq8.bb(localdRq15);
    localdRq15.brn();
    NK localNK5 = NK.checkOut();
    localNK5.setElementMap(localcpa);
    localNK5.setAttribute("visible");
    localNK5.setName("guild");
    localNK5.setField("hasRightToEditGuildMessage");
    localdRq15.bb(localNK5);
    localNK5.brn();
    localNK5.rV();
    aId localaId6 = aId.checkOut();
    localaId6.setHorizontal(false);
    localaId6.setAlign(aFG.ech);
    localdRq15.bb(localaId6);
    localaId6.brn();
    localaId6.rV();
    dRq localdRq16 = dRq.checkOut();
    localdRq16.setElementMap(localcpa);
    localdRq16.setStyle("titleBar");
    localdRq16.setExpandable(false);
    localdRq15.bb(localdRq16);
    localdRq16.brn();
    caF localcaF3 = new caF();
    localcaF3.aJ();
    localcaF3.setElementMap(localcpa);
    localcaF3.setStyle("whiteTitle");
    String str6 = "%guild.message%";
    str6 = str6.replace("%guild.message%", cBQ.cxL().mL("guild.message"));
    localcaF3.setText(str6);
    localcaF3.setNonBlocking(true);
    localcaF3.setExpandable(false);
    localdRq16.bb(localcaF3);
    localcaF3.brn();
    caF localcaF4 = localcaF3;
    Jg localJg8 = localcaF4.getAppearance();
    localJg8.setElementMap(localcpa);
    ((cwJ)localJg8).setAlign(aFG.ech);
    localcaF3.bb(localJg8);
    localJg8.brn();
    localJg8.rV();
    localcaF3.rV();
    localdRq16.rV();
    dRq localdRq17 = dRq.checkOut();
    localdRq17.setElementMap(localcpa);
    localdRq17.setStyle("ShortcutRowBackgroundFull");
    localdRq17.setExpandable(false);
    localdRq15.bb(localdRq17);
    localdRq17.brn();
    dRq localdRq18 = localdRq17;
    Jg localJg9 = localdRq18.getAppearance();
    localJg9.setElementMap(localcpa);
    localdRq17.bb(localJg9);
    localJg9.brn();
    cuR localcuR4 = new cuR();
    localcuR4.aJ();
    localcuR4.setElementMap(localcpa);
    localcuR4.setInsets(new Insets(3, 3, 3, 3));
    localJg9.bb(localcuR4);
    localcuR4.brn();
    localcuR4.rV();
    bmv localbmv6 = bmv.checkOut();
    localbmv6.setElementMap(localcpa);
    localbmv6.setInsets(new Insets(2, 2, 5, 2));
    localJg9.bb(localbmv6);
    localbmv6.brn();
    localbmv6.rV();
    localJg9.rV();
    dpm localdpm4 = new dpm();
    localdpm4.aJ();
    localdpm4.setElementMap(localcpa);
    localdpm4.setAlign(aFG.ecj);
    localdRq17.bb(localdpm4);
    localdpm4.brn();
    localdpm4.rV();
    aId localaId7 = aId.checkOut();
    localaId7.setAlign(aFG.ecj);
    localdRq17.bb(localaId7);
    localaId7.brn();
    localaId7.rV();
    String str7 = "guildMessage";
    aTp localaTp2 = new aTp();
    localaTp2.aJ();
    localaTp2.setElementMap(localcpa);
    if ((localcpa != null) && (str7 != null))
      localcpa.a(str7, localaTp2);
    localaTp2.setStyle("withoutBorder");
    localaTp2.setMaxChars(200);
    localaTp2.setPrefSize(new Or(300, 100));
    localaTp2.setExpandable(false);
    aOn localaOn2 = new aOn();
    localaOn2.hg("wakfu.guildManagement:onKeyEvent(applyMessage)");
    localaTp2.setOnKeyPress(localaOn2);
    localaTp2.setMultiline(true);
    localdRq17.bb(localaTp2);
    localaTp2.brn();
    NK localNK6 = NK.checkOut();
    localNK6.setElementMap(localcpa);
    localNK6.setName("guild");
    localNK6.setAttribute("text");
    localNK6.setField("guildMessage");
    localaTp2.bb(localNK6);
    localNK6.brn();
    localNK6.rV();
    dpm localdpm5 = new dpm();
    localdpm5.aJ();
    localdpm5.setElementMap(localcpa);
    localdpm5.setAlign(aFG.ech);
    localaTp2.bb(localdpm5);
    localdpm5.brn();
    localdpm5.rV();
    localaTp2.rV();
    localdRq17.rV();
    String str8 = "applyMessage";
    biy localbiy3 = new biy();
    localbiy3.aJ();
    localbiy3.setElementMap(localcpa);
    if ((localcpa != null) && (str8 != null))
      localcpa.a(str8, localbiy3);
    String str9 = "%apply%";
    str9 = str9.replace("%apply%", cBQ.cxL().mL("apply"));
    localbiy3.setText(str9);
    localbiy3.setExpandable(false);
    csA localcsA2 = new csA();
    localcsA2.hg("wakfu.guildManagement:applyGuildMessage(guildMessage)");
    localbiy3.setOnClick(localcsA2);
    localbiy3.setEnabled(false);
    localdRq15.bb(localbiy3);
    localbiy3.brn();
    dpm localdpm6 = new dpm();
    localdpm6.aJ();
    localdpm6.setElementMap(localcpa);
    localdpm6.setAlign(aFG.ecl);
    localbiy3.bb(localdpm6);
    localdpm6.brn();
    localdpm6.rV();
    biy localbiy4 = localbiy3;
    Jg localJg10 = localbiy4.getAppearance();
    localJg10.setElementMap(localcpa);
    localbiy3.bb(localJg10);
    localJg10.brn();
    cuR localcuR5 = new cuR();
    localcuR5.aJ();
    localcuR5.setElementMap(localcpa);
    localcuR5.setInsets(new Insets(0, 5, 0, 5));
    localJg10.bb(localcuR5);
    localcuR5.brn();
    localcuR5.rV();
    bmv localbmv7 = bmv.checkOut();
    localbmv7.setElementMap(localcpa);
    localbmv7.setInsets(new Insets(5, 0, 0, 5));
    localJg10.bb(localbmv7);
    localbmv7.brn();
    localbmv7.rV();
    localJg10.rV();
    localbiy3.rV();
    localdRq15.rV();
    localdRq8.rV();
    dRq localdRq19 = dRq.checkOut();
    localdRq19.setElementMap(localcpa);
    localdRq19.setExpandable(false);
    localdRq7.bb(localdRq19);
    localdRq19.brn();
    a(localdRq19);
    b(localdRq19);
    d(localdRq19);
    localdRq19.rV();
    localdRq7.rV();
    localdRq6.rV();
    localdRq4.rV();
    localdRq2.rV();
    e(localbpn);
    f(localbpn);
    g(localbpn);
    localbpn.rV();
    return localbpn;
  }

  public bdj a(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    aId localaId = aId.checkOut();
    localaId.setAlign(aFG.ech);
    localaId.setHorizontal(false);
    parambdj.bb(localaId);
    localaId.brn();
    localaId.rV();
    return null;
  }

  public bdj b(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setAttribute("visible");
    localNK.setName("isEditingGuildDescs");
    parambdj.bb(localNK);
    localNK.brn();
    anQ localanQ = new anQ();
    localanQ.aJ();
    localanQ.setElementMap(localcpa);
    localNK.bb(localanQ);
    localanQ.brn();
    bqW localbqW = new bqW();
    localbqW.aJ();
    localbqW.setElementMap(localcpa);
    localanQ.bb(localbqW);
    localbqW.brn();
    localbqW.rV();
    localanQ.rV();
    localNK.rV();
    return localNK;
  }

  public bdj d(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq1 = dRq.checkOut();
    localdRq1.setElementMap(localcpa);
    localdRq1.setExpandable(false);
    parambdj.bb(localdRq1);
    localdRq1.brn();
    dRq localdRq2 = localdRq1;
    Jg localJg1 = localdRq2.getAppearance();
    localJg1.setElementMap(localcpa);
    localdRq1.bb(localJg1);
    localJg1.brn();
    bmv localbmv1 = bmv.checkOut();
    localbmv1.setElementMap(localcpa);
    localbmv1.setInsets(new Insets(10, 0, 0, 0));
    localJg1.bb(localbmv1);
    localbmv1.brn();
    localbmv1.rV();
    localJg1.rV();
    aId localaId1 = aId.checkOut();
    localaId1.setHorizontal(false);
    localaId1.setAlign(aFG.ech);
    localdRq1.bb(localaId1);
    localaId1.brn();
    localaId1.rV();
    dRq localdRq3 = dRq.checkOut();
    localdRq3.setElementMap(localcpa);
    localdRq3.setStyle("titleBar");
    localdRq3.setExpandable(false);
    localdRq1.bb(localdRq3);
    localdRq3.brn();
    caF localcaF1 = new caF();
    localcaF1.aJ();
    localcaF1.setElementMap(localcpa);
    localcaF1.setStyle("whiteTitle");
    String str1 = "%guild.personalNote%";
    str1 = str1.replace("%guild.personalNote%", cBQ.cxL().mL("guild.personalNote"));
    localcaF1.setText(str1);
    localcaF1.setNonBlocking(true);
    localcaF1.setExpandable(false);
    localdRq3.bb(localcaF1);
    localcaF1.brn();
    caF localcaF2 = localcaF1;
    Jg localJg2 = localcaF2.getAppearance();
    localJg2.setElementMap(localcpa);
    ((cwJ)localJg2).setAlign(aFG.ech);
    localcaF1.bb(localJg2);
    localJg2.brn();
    localJg2.rV();
    localcaF1.rV();
    localdRq3.rV();
    dRq localdRq4 = dRq.checkOut();
    localdRq4.setElementMap(localcpa);
    localdRq4.setStyle("ShortcutRowBackgroundFull");
    localdRq4.setExpandable(false);
    localdRq1.bb(localdRq4);
    localdRq4.brn();
    dRq localdRq5 = localdRq4;
    Jg localJg3 = localdRq5.getAppearance();
    localJg3.setElementMap(localcpa);
    localdRq4.bb(localJg3);
    localJg3.brn();
    cuR localcuR1 = new cuR();
    localcuR1.aJ();
    localcuR1.setElementMap(localcpa);
    localcuR1.setInsets(new Insets(3, 3, 3, 3));
    localJg3.bb(localcuR1);
    localcuR1.brn();
    localcuR1.rV();
    bmv localbmv2 = bmv.checkOut();
    localbmv2.setElementMap(localcpa);
    localbmv2.setInsets(new Insets(2, 2, 5, 2));
    localJg3.bb(localbmv2);
    localbmv2.brn();
    localbmv2.rV();
    localJg3.rV();
    dpm localdpm1 = new dpm();
    localdpm1.aJ();
    localdpm1.setElementMap(localcpa);
    localdpm1.setAlign(aFG.ecj);
    localdRq4.bb(localdpm1);
    localdpm1.brn();
    localdpm1.rV();
    aId localaId2 = aId.checkOut();
    localaId2.setAlign(aFG.ecj);
    localdRq4.bb(localaId2);
    localaId2.brn();
    localaId2.rV();
    String str2 = "guildPersonalMessage";
    aTp localaTp = new aTp();
    localaTp.aJ();
    localaTp.setElementMap(localcpa);
    if ((localcpa != null) && (str2 != null))
      localcpa.a(str2, localaTp);
    localaTp.setRestrict("[.*&[^<>]]");
    localaTp.setStyle("withoutBorder");
    localaTp.setMaxChars(200);
    localaTp.setPrefSize(new Or(200, 50));
    localaTp.setExpandable(false);
    aOn localaOn = new aOn();
    localaOn.hg("wakfu.guildManagement:onKeyEvent(applyPersonalMessage)");
    localaTp.setOnKeyPress(localaOn);
    localaTp.setMultiline(true);
    localdRq4.bb(localaTp);
    localaTp.brn();
    NK localNK = NK.checkOut();
    localNK.setElementMap(localcpa);
    localNK.setName("selectedGuildRank");
    localNK.setAttribute("text");
    localNK.setField("guildMessage");
    localaTp.bb(localNK);
    localNK.brn();
    localNK.rV();
    dpm localdpm2 = new dpm();
    localdpm2.aJ();
    localdpm2.setElementMap(localcpa);
    localdpm2.setAlign(aFG.ech);
    localaTp.bb(localdpm2);
    localdpm2.brn();
    localdpm2.rV();
    localaTp.rV();
    localdRq4.rV();
    String str3 = "applyPersonalMessage";
    biy localbiy1 = new biy();
    localbiy1.aJ();
    localbiy1.setElementMap(localcpa);
    if ((localcpa != null) && (str3 != null))
      localcpa.a(str3, localbiy1);
    String str4 = "%apply%";
    str4 = str4.replace("%apply%", cBQ.cxL().mL("apply"));
    localbiy1.setText(str4);
    localbiy1.setExpandable(false);
    csA localcsA = new csA();
    localcsA.hg("wakfu.guildManagement:applyGuildMessage(guildPersonalMessage)");
    localbiy1.setOnClick(localcsA);
    localbiy1.setEnabled(false);
    localdRq1.bb(localbiy1);
    localbiy1.brn();
    dpm localdpm3 = new dpm();
    localdpm3.aJ();
    localdpm3.setElementMap(localcpa);
    localdpm3.setAlign(aFG.ecl);
    localbiy1.bb(localdpm3);
    localdpm3.brn();
    localdpm3.rV();
    biy localbiy2 = localbiy1;
    Jg localJg4 = localbiy2.getAppearance();
    localJg4.setElementMap(localcpa);
    localbiy1.bb(localJg4);
    localJg4.brn();
    cuR localcuR2 = new cuR();
    localcuR2.aJ();
    localcuR2.setElementMap(localcpa);
    localcuR2.setInsets(new Insets(0, 5, 0, 5));
    localJg4.bb(localcuR2);
    localcuR2.brn();
    localcuR2.rV();
    bmv localbmv3 = bmv.checkOut();
    localbmv3.setElementMap(localcpa);
    localbmv3.setInsets(new Insets(5, 0, 0, 5));
    localJg4.bb(localbmv3);
    localbmv3.brn();
    localbmv3.rV();
    localJg4.rV();
    localbiy1.rV();
    localdRq1.rV();
    return localdRq1;
  }

  public bdj e(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    dRq localdRq = dRq.checkOut();
    localdRq.setElementMap(localcpa);
    parambdj.bb(localdRq);
    localdRq.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(100.0F, 100.0F));
    localdRq.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localdRq.rV();
    return localdRq;
  }

  public bdj f(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    biy localbiy = new biy();
    localbiy.aJ();
    localbiy.setElementMap(localcpa);
    localbiy.setStyle("close");
    localbiy.setExpandable(false);
    csA localcsA = new csA();
    localcsA.hg("unloadDialog");
    localbiy.setOnClick(localcsA);
    parambdj.bb(localbiy);
    localbiy.brn();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(-2, -2));
    localcwP.setAlign(ajb.dhV);
    localcwP.setXOffset(-18);
    localcwP.setYOffset(-12);
    localbiy.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    localbiy.rV();
    return localbiy;
  }

  public bdj g(bdj parambdj)
  {
    cpa localcpa = (cpa)this.X.peek();
    cwP localcwP = new cwP();
    localcwP.aJ();
    localcwP.setElementMap(localcpa);
    localcwP.setSize(new Or(-2, -2));
    localcwP.setAlign(ajb.dhZ);
    localcwP.setResizeOnce(true);
    parambdj.bb(localcwP);
    localcwP.brn();
    localcwP.rV();
    return localcwP;
  }
}