import java.util.Stack;

public class cuN
  implements aTK
{
  private uk W;
  private Stack X = new Stack();

  public void a(cpa paramcpa, uk paramuk, dOc paramdOc)
  {
    this.W = paramuk;
    this.X.push(paramcpa);
    cpa localcpa = (cpa)this.X.peek();
    dOc localdOc1 = paramdOc;
    Jg localJg = localdOc1.getAppearance();
    localJg.setElementMap(localcpa);
    paramdOc.bb(localJg);
    localJg.brn();
    dOc localdOc2 = (dOc)localJg.getParentOfType(dOc.class);
    dOc localdOc3 = localdOc2.getWidgetByThemeElementName("textEditor", false);
    Object localObject4;
    Object localObject5;
    Object localObject6;
    Object localObject7;
    Object localObject8;
    Object localObject9;
    Object localObject10;
    Object localObject11;
    Object localObject12;
    Object localObject13;
    Object localObject14;
    Object localObject15;
    if (localdOc3 != null)
    {
      localdOc4 = (dOc)localdOc3;
      localObject1 = localdOc4.getAppearance();
      ((Jg)localObject1).setElementMap(localcpa);
      ((cwJ)localObject1).setAlign(aFG.ecl);
      localdOc3.bb((bdj)localObject1);
      ((Jg)localObject1).brn();
      localObject2 = bJA.checkOut();
      ((bJA)localObject2).setRenderer(cBQ.cxL().bSM().aI("defaultSmallBoldFont"));
      ((bJA)localObject2).setElementMap(localcpa);
      ((Jg)localObject1).bb((bdj)localObject2);
      ((bJA)localObject2).brn();
      ((bJA)localObject2).rV();
      localObject3 = "defaultDarkColor";
      localObject4 = cAf.checkOut();
      ((cAf)localObject4).setElementMap(localcpa);
      if ((localcpa != null) && (localObject3 != null))
        localcpa.a((String)localObject3, (aNL)localObject4);
      ((cAf)localObject4).setColor(new bNa(0.29F, 0.17F, 0.07F, 1.0F));
      ((Jg)localObject1).bb((bdj)localObject4);
      ((cAf)localObject4).brn();
      ((cAf)localObject4).rV();
      localObject5 = "textEditorLightBorder";
      localObject6 = new Cx();
      ((Cx)localObject6).aJ();
      ((Cx)localObject6).setElementMap(localcpa);
      if ((localcpa != null) && (localObject5 != null))
        localcpa.a((String)localObject5, (aNL)localObject6);
      ((Jg)localObject1).bb((bdj)localObject6);
      ((Cx)localObject6).brn();
      localObject7 = aAR.checkOut();
      ((aAR)localObject7).setElementMap(localcpa);
      ((aAR)localObject7).setPosition(ajb.dhR);
      ((aAR)localObject7).setX(797);
      ((aAR)localObject7).setY(214);
      ((aAR)localObject7).setWidth(4);
      ((aAR)localObject7).setHeight(4);
      ((aAR)localObject7).setTexture(this.W.aH("default_1.tga"));
      ((Cx)localObject6).bb((bdj)localObject7);
      ((aAR)localObject7).brn();
      ((aAR)localObject7).rV();
      localObject8 = aAR.checkOut();
      ((aAR)localObject8).setElementMap(localcpa);
      ((aAR)localObject8).setPosition(ajb.dhT);
      ((aAR)localObject8).setX(237);
      ((aAR)localObject8).setY(82);
      ((aAR)localObject8).setWidth(20);
      ((aAR)localObject8).setHeight(4);
      ((aAR)localObject8).setTexture(this.W.aH("default_0.tga"));
      ((Cx)localObject6).bb((bdj)localObject8);
      ((aAR)localObject8).brn();
      ((aAR)localObject8).rV();
      localObject9 = aAR.checkOut();
      ((aAR)localObject9).setElementMap(localcpa);
      ((aAR)localObject9).setPosition(ajb.dhV);
      ((aAR)localObject9).setX(338);
      ((aAR)localObject9).setY(340);
      ((aAR)localObject9).setWidth(4);
      ((aAR)localObject9).setHeight(4);
      ((aAR)localObject9).setTexture(this.W.aH("default_0.tga"));
      ((Cx)localObject6).bb((bdj)localObject9);
      ((aAR)localObject9).brn();
      ((aAR)localObject9).rV();
      localObject10 = aAR.checkOut();
      ((aAR)localObject10).setElementMap(localcpa);
      ((aAR)localObject10).setPosition(ajb.dia);
      ((aAR)localObject10).setX(929);
      ((aAR)localObject10).setY(398);
      ((aAR)localObject10).setWidth(4);
      ((aAR)localObject10).setHeight(7);
      ((aAR)localObject10).setTexture(this.W.aH("default_0.tga"));
      ((Cx)localObject6).bb((bdj)localObject10);
      ((aAR)localObject10).brn();
      ((aAR)localObject10).rV();
      localObject11 = aAR.checkOut();
      ((aAR)localObject11).setElementMap(localcpa);
      ((aAR)localObject11).setPosition(ajb.dih);
      ((aAR)localObject11).setX(1003);
      ((aAR)localObject11).setY(54);
      ((aAR)localObject11).setWidth(4);
      ((aAR)localObject11).setHeight(3);
      ((aAR)localObject11).setTexture(this.W.aH("default_0.tga"));
      ((Cx)localObject6).bb((bdj)localObject11);
      ((aAR)localObject11).brn();
      ((aAR)localObject11).rV();
      localObject12 = aAR.checkOut();
      ((aAR)localObject12).setElementMap(localcpa);
      ((aAR)localObject12).setPosition(ajb.dif);
      ((aAR)localObject12).setX(854);
      ((aAR)localObject12).setY(588);
      ((aAR)localObject12).setWidth(20);
      ((aAR)localObject12).setHeight(3);
      ((aAR)localObject12).setTexture(this.W.aH("default_0.tga"));
      ((Cx)localObject6).bb((bdj)localObject12);
      ((aAR)localObject12).brn();
      ((aAR)localObject12).rV();
      localObject13 = aAR.checkOut();
      ((aAR)localObject13).setElementMap(localcpa);
      ((aAR)localObject13).setPosition(ajb.did);
      ((aAR)localObject13).setX(191);
      ((aAR)localObject13).setY(82);
      ((aAR)localObject13).setWidth(4);
      ((aAR)localObject13).setHeight(3);
      ((aAR)localObject13).setTexture(this.W.aH("default_0.tga"));
      ((Cx)localObject6).bb((bdj)localObject13);
      ((aAR)localObject13).brn();
      ((aAR)localObject13).rV();
      localObject14 = aAR.checkOut();
      ((aAR)localObject14).setElementMap(localcpa);
      ((aAR)localObject14).setPosition(ajb.dhY);
      ((aAR)localObject14).setX(929);
      ((aAR)localObject14).setY(408);
      ((aAR)localObject14).setWidth(4);
      ((aAR)localObject14).setHeight(7);
      ((aAR)localObject14).setTexture(this.W.aH("default_0.tga"));
      ((Cx)localObject6).bb((bdj)localObject14);
      ((aAR)localObject14).brn();
      ((aAR)localObject14).rV();
      ((Cx)localObject6).rV();
      localObject15 = "textEditorLightBackground";
      aen localaen = aen.checkOut();
      localaen.setElementMap(localcpa);
      if ((localcpa != null) && (localObject15 != null))
        localcpa.a((String)localObject15, localaen);
      localaen.setScaled(true);
      ((Jg)localObject1).bb(localaen);
      localaen.brn();
      aAR localaAR = aAR.checkOut();
      localaAR.setElementMap(localcpa);
      localaAR.setPosition(ajb.dhZ);
      localaAR.setX(147);
      localaAR.setY(178);
      localaAR.setWidth(20);
      localaAR.setHeight(7);
      localaAR.setTexture(this.W.aH("default_0.tga"));
      localaen.bb(localaAR);
      localaAR.brn();
      localaAR.rV();
      localaen.rV();
      ((Jg)localObject1).rV();
    }
    dOc localdOc4 = (dOc)localJg.getParentOfType(dOc.class);
    Object localObject1 = localdOc4.getWidgetByThemeElementName("increaseButton", false);
    if (localObject1 != null)
    {
      localObject2 = (dOc)localObject1;
      localObject3 = ((dOc)localObject2).getAppearance();
      ((Jg)localObject3).setElementMap(localcpa);
      ((Jg)localObject3).setState("default");
      ((aNL)localObject1).bb((bdj)localObject3);
      ((Jg)localObject3).brn();
      localObject4 = aAR.checkOut();
      ((aAR)localObject4).setElementMap(localcpa);
      ((aAR)localObject4).setPosition(ajb.dhZ);
      ((aAR)localObject4).setX(418);
      ((aAR)localObject4).setY(150);
      ((aAR)localObject4).setWidth(17);
      ((aAR)localObject4).setHeight(9);
      ((aAR)localObject4).setTexture(this.W.aH("default_1.tga"));
      ((Jg)localObject3).bb((bdj)localObject4);
      ((aAR)localObject4).brn();
      ((aAR)localObject4).rV();
      ((Jg)localObject3).rV();
      localObject5 = (dOc)localObject1;
      localObject6 = ((dOc)localObject5).getAppearance();
      ((Jg)localObject6).setElementMap(localcpa);
      ((Jg)localObject6).setState("mouseHover");
      ((aNL)localObject1).bb((bdj)localObject6);
      ((Jg)localObject6).brn();
      localObject7 = aAR.checkOut();
      ((aAR)localObject7).setElementMap(localcpa);
      ((aAR)localObject7).setPosition(ajb.dhZ);
      ((aAR)localObject7).setX(418);
      ((aAR)localObject7).setY(150);
      ((aAR)localObject7).setWidth(17);
      ((aAR)localObject7).setHeight(9);
      ((aAR)localObject7).setTexture(this.W.aH("default_1.tga"));
      ((Jg)localObject6).bb((bdj)localObject7);
      ((aAR)localObject7).brn();
      ((aAR)localObject7).rV();
      ((Jg)localObject6).rV();
      localObject8 = (dOc)localObject1;
      localObject9 = ((dOc)localObject8).getAppearance();
      ((Jg)localObject9).setElementMap(localcpa);
      ((Jg)localObject9).setState("disabled");
      ((aNL)localObject1).bb((bdj)localObject9);
      ((Jg)localObject9).brn();
      localObject10 = aAR.checkOut();
      ((aAR)localObject10).setElementMap(localcpa);
      ((aAR)localObject10).setPosition(ajb.dhZ);
      ((aAR)localObject10).setX(418);
      ((aAR)localObject10).setY(150);
      ((aAR)localObject10).setWidth(17);
      ((aAR)localObject10).setHeight(9);
      ((aAR)localObject10).setTexture(this.W.aH("default_1.tga"));
      ((Jg)localObject9).bb((bdj)localObject10);
      ((aAR)localObject10).brn();
      ((aAR)localObject10).rV();
      ((Jg)localObject9).rV();
      localObject11 = (dOc)localObject1;
      localObject12 = ((dOc)localObject11).getAppearance();
      ((Jg)localObject12).setElementMap(localcpa);
      ((Jg)localObject12).setState("pressed");
      ((aNL)localObject1).bb((bdj)localObject12);
      ((Jg)localObject12).brn();
      localObject13 = aAR.checkOut();
      ((aAR)localObject13).setElementMap(localcpa);
      ((aAR)localObject13).setPosition(ajb.dhZ);
      ((aAR)localObject13).setX(418);
      ((aAR)localObject13).setY(150);
      ((aAR)localObject13).setWidth(17);
      ((aAR)localObject13).setHeight(9);
      ((aAR)localObject13).setTexture(this.W.aH("default_1.tga"));
      ((Jg)localObject12).bb((bdj)localObject13);
      ((aAR)localObject13).brn();
      ((aAR)localObject13).rV();
      ((Jg)localObject12).rV();
    }
    Object localObject2 = (dOc)localJg.getParentOfType(dOc.class);
    Object localObject3 = ((dOc)localObject2).getWidgetByThemeElementName("decreaseButton", false);
    if (localObject3 != null)
    {
      localObject4 = (dOc)localObject3;
      localObject5 = ((dOc)localObject4).getAppearance();
      ((Jg)localObject5).setElementMap(localcpa);
      ((Jg)localObject5).setState("default");
      ((aNL)localObject3).bb((bdj)localObject5);
      ((Jg)localObject5).brn();
      localObject6 = aAR.checkOut();
      ((aAR)localObject6).setElementMap(localcpa);
      ((aAR)localObject6).setPosition(ajb.dhZ);
      ((aAR)localObject6).setX(418);
      ((aAR)localObject6).setY(150);
      ((aAR)localObject6).setWidth(17);
      ((aAR)localObject6).setHeight(9);
      ((aAR)localObject6).setTexture(this.W.aH("default_1.tga"));
      ((Jg)localObject5).bb((bdj)localObject6);
      ((aAR)localObject6).brn();
      ((aAR)localObject6).rV();
      ((Jg)localObject5).rV();
      localObject7 = (dOc)localObject3;
      localObject8 = ((dOc)localObject7).getAppearance();
      ((Jg)localObject8).setElementMap(localcpa);
      ((Jg)localObject8).setState("mouseHover");
      ((aNL)localObject3).bb((bdj)localObject8);
      ((Jg)localObject8).brn();
      localObject9 = aAR.checkOut();
      ((aAR)localObject9).setElementMap(localcpa);
      ((aAR)localObject9).setPosition(ajb.dhZ);
      ((aAR)localObject9).setX(418);
      ((aAR)localObject9).setY(150);
      ((aAR)localObject9).setWidth(17);
      ((aAR)localObject9).setHeight(9);
      ((aAR)localObject9).setTexture(this.W.aH("default_1.tga"));
      ((Jg)localObject8).bb((bdj)localObject9);
      ((aAR)localObject9).brn();
      ((aAR)localObject9).rV();
      ((Jg)localObject8).rV();
      localObject10 = (dOc)localObject3;
      localObject11 = ((dOc)localObject10).getAppearance();
      ((Jg)localObject11).setElementMap(localcpa);
      ((Jg)localObject11).setState("disabled");
      ((aNL)localObject3).bb((bdj)localObject11);
      ((Jg)localObject11).brn();
      localObject12 = aAR.checkOut();
      ((aAR)localObject12).setElementMap(localcpa);
      ((aAR)localObject12).setPosition(ajb.dhZ);
      ((aAR)localObject12).setX(418);
      ((aAR)localObject12).setY(150);
      ((aAR)localObject12).setWidth(17);
      ((aAR)localObject12).setHeight(9);
      ((aAR)localObject12).setTexture(this.W.aH("default_1.tga"));
      ((Jg)localObject11).bb((bdj)localObject12);
      ((aAR)localObject12).brn();
      ((aAR)localObject12).rV();
      ((Jg)localObject11).rV();
      localObject13 = (dOc)localObject3;
      localObject14 = ((dOc)localObject13).getAppearance();
      ((Jg)localObject14).setElementMap(localcpa);
      ((Jg)localObject14).setState("pressed");
      ((aNL)localObject3).bb((bdj)localObject14);
      ((Jg)localObject14).brn();
      localObject15 = aAR.checkOut();
      ((aAR)localObject15).setElementMap(localcpa);
      ((aAR)localObject15).setPosition(ajb.dhZ);
      ((aAR)localObject15).setX(418);
      ((aAR)localObject15).setY(150);
      ((aAR)localObject15).setWidth(17);
      ((aAR)localObject15).setHeight(9);
      ((aAR)localObject15).setTexture(this.W.aH("default_1.tga"));
      ((Jg)localObject14).bb((bdj)localObject15);
      ((aAR)localObject15).brn();
      ((aAR)localObject15).rV();
      ((Jg)localObject14).rV();
    }
    localJg.rV();
  }
}