/*
* generated by Xtext
*/
package macroscipting;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MacroStandaloneSetup extends MacroStandaloneSetupGenerated{

	public static void doSetup() {
		new MacroStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

