/*
 * generated by Xtext
 */
package macroscipting;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MacroRuntimeModule extends macroscipting.AbstractMacroRuntimeModule {

}
