/*
* generated by Xtext
*/
package macroscipting;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MacroUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return macroscipting.ui.internal.MacroActivator.getInstance().getInjector("macroscipting.Macro");
	}
	
}
