/*
 * generated by Xtext
 */
package macroscipting.ui.contentassist

import macroscipting.ui.contentassist.AbstractMacroProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
class MacroProposalProvider extends AbstractMacroProposalProvider {
}
